#!/bin/bash

# Base directory (script location)
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Configurable directories
WORDPRESS_WORKDIR="${WORDPRESS_WORKDIR:-$BASE_DIR/wordpress-plugins}"
PLUGIN_DIR="${PLUGIN_DIR:-$BASE_DIR/wp-content/plugins}"
MIRROR_DIR="${MIRROR_DIR:-$BASE_DIR/mirror}"
LOGS_DIR="${LOGS_DIR:-$BASE_DIR/plugin-logs}"

# Check for CF_WORKER_URL environment variable
if [ -z "$CF_WORKER_URL" ]; then
    echo "Error: CF_WORKER_URL environment variable is not set." >&2
    exit 1
fi

DOWNLOAD_BASE_URL="https://downloads.wordpress.org/plugin"

# Other variables
DOWNLOAD_LINK_API='y'

ADDITIONAL_PLUGINS=(
    "qqworld-speed-4-china"
    "disqus-latest-comments"
    "faq-schema-block-to-accordion"
    "internal-links-generator"
    "plugin-inspector"
    "meow-analytics"
    "gg-woo-feed"
    "gf-forms-uk-address-format"
    "hot-blocks"
    "currencyr"
    "ship-per-product"
    "pj-page-cache-red"
    "wpf2b-addon-blocklist"
    "video-player-block"
    "goodreviews"
    "wf-cpanel-email-accounts"
    "sticky-element"
    "formentor-elementor-form-plus"
    "bus-booking-manager"
    "addonify-floating-cart"
    "stafflist"
    "nextcart-woocommerce-migration"
    "simple-myisam-to-innodb"
    "media-vault"
    "twitter-follow"
    "ethereum-wallet"
    "adopt"
    "pages-order"
    "mysqli"
    "wc-price-history"
    "minimum-featured-image-size"
    "wp-residence-add-on-for-wp-all-import"
    "rotating-lightbox-gallery"
    "sharethis-reaction-buttons"
    "sportspress-for-cricket"
    "fv-clone-screen-options"
    "sg-checkout-location-picker"
    "wp-duoshuo-gravatar"
    "woo-add-to-quote"
    "piano"
    "pos-entegrator"
    "display-authors-widget"
    "disable-all-wp-updates"
    "slider-pro-lite"
    "disable-hide-comment-url"
    "wp-nav-plus"
    "dm-confirm-email"
    "skillbars"
    "simple-custom-content"
    "enhanced-categories"
    "acf-flexible-layouts-manager"
    "prevent-concurrent-logins"
    "wp-secure-by-sitesecuritymonitorcom"
    "leira-cron-jobs"
    "icons-font-loader"
    "simple-registration-form"
    "cf7-cep-autofill"
    "kn-social-slide"
    "tripadvisor-shortcode"
    "gpx-viewer"
    "global-site-tag-tracking"
    "stock-quote"
    "bp-auto-group-join"
    "timologia-for-woocommerce"
    "buddypress-friends"
    "print-page"
    "space-boxes"
    "list-last-changes"
    "duplicate-title-checker"
    "ultra-community"
    "separator-shortcode-and-widget"
    "z-companion"
    "clarity-ad-blocker"
    "piwigopress"
    "xunhu-wechat-payment-for-woocommerce"
    "wordpress-plugin-framework-reloaded"
    "woo-lookbook"
    "community-events"
    "woocommerce-hide-checkout-shipping-address"
    "notifier"
    "subscribe-to-unlock-lite"
    "script-compressor"
    "gp-back-to-top"
    "wovax-idx"
    "zibal-payment-gateway-for-woocommerce"
    "rapyd-payments"
    "remove-admin-toolbar"
    "nikan-woocomerce-base"
    "wp-delete-user-accounts"
    "order-calendar-for-woocommerce"
    "qr-code-generator-widget"
    "hide-trackbacks"
    "zen-addons-for-siteorigin-page-builder"
    "wp-real-time-social-proof"
    "massive-visual-builder-page-layout-builder"
    "orderstorm-wordpress-e-commerce"
    "wc-product-bundles"
    "music-press-pro"
    "gf-infusionsoft"
    "demon-image-annotation"
    "sj-elementor-addon"
    "exclusive-content-password-protect"
    "reset-roles-and-capabilities"
    "woo-fortnox-hub"
    "list-posts-by-category"
    "blueconic"
    "web2application"
    "knowledgebase-helpdesk"
    "flexia-core"
    "event-page"
    "social-pug-author-box"
    "post-meta"
    "nextgen-gallery-image-chooser"
    "seo-consultant"
    "wp-toolbelt"
    "visitor-maps-extended-referer-field"
    "total-donations"
    "expivi"
    "posts-character-count-admin"
    "gnu-terry-pratchett"
    "acf-link-picker-field"
    "woo-shop-slider-lite"
    "key4ce-osticket-bridge"
    "directorypress-frontend"
    "woo-product-builder"
    "post-password-plugin"
    "categories-metabox-enhanced"
    "advanced-real-estate-mortgage-calculator"
    "wpec-related-products"
    "bws-testimonials"
    "login-with-azure"
    "auto-ftp"
    "dewdrop-custom-scrollbar"
    "design-experiments"
    "ultimate-watermark"
    "custom-fields-csv-xml-importer"
    "woo-product-hover-show-info-tooltip"
    "basic-authentication"
    "preload-lcp-image"
    "before-after-image-compare"
    "s3-image-optimizer"
    "wc-sales-count-manager"
    "tinymce-advanced-language-pack"
    "wc-sslcommerz-easycheckout"
    "theme-file-duplicator"
    "rocket-fireworks"
    "social-profilr-display-social-network-profile"
    "wpsso-faq"
    "phpinfo"
    "drag-and-drop-form-builder-for-contact-form-7"
    "rsfirewall"
    "media-library-file-size"
    "no-copy"
    "buddypress-restrict-group-creation"
    "woocommerce-bcash"
    "color-mobile-browser-address-bar"
    "3d-slider-slicebox"
    "rs-author-info-box"
    "page-navigator-widget"
    "wp-script-optimizer"
    "nextpage-buttons"
    "posterous-importer"
    "extra-shortcodes"
    "glance-that"
    "gravity-forms-mass-import"
    "sendy-widget"
    "scd-smart-currency-detector"
    "attributes-table"
    "connections-business-directory-login"
    "dt-author-box"
    "mobile-builder"
    "mihdan-lite-youtube-embed"
    "pretty-sidebar-categories"
    "accredible-certificates"
    "mortgage-rates"
    "free-product-table-for-woocommerce"
    "bainternet-simple-toc"
    "add-anchor-links"
    "contact-form-master"
    "post-type-transfer"
    "custom-field-taxonomies"
    "woo-payment-gateways-bank-indo-kode-payment"
    "comment-email-verify"
    "social-divi"
    "electronic-signatures"
    "manycontacts-bar"
    "striptease"
    "twitter-anywhere-plus"
    "css-above-the-fold"
    "embed-sharepoint-onedrive-documents"
    "db-access-adminer"
    "dsgvo-youtube"
    "gutentoc-advance-table-of-content"
    "image-parallax"
    "bible-verse-display"
    "ram108-sape"
    "snowball"
    "navayan-csv-export"
    "flash-show-and-hide-box"
    "wp-widget-gallery"
    "fantastic-elasticsearch"
    "collapsible-widget-area"
    "tutor-lms-divi-modules"
    "wc-easypost-shipping"
    "overlay-image-divi-module"
    "wp-unformatted"
    "admiral-adblock-suite"
    "hikari-category-permalink"
    "aarambha-demo-sites"
    "comment-notifier-no-spammers"
    "404-page"
    "legull"
    "get-page-ids"
    "wp-draftsforfriends"
    "rcd-right-click-disabler"
    "wp-tooltip"
    "wp-weixin"
    "gf-google-address-autocomplete"
    "woocommerce-auto-restore-stock"
    "link-hopper"
    "wp-widget-sugarcrm-lead-module"
    "simply-sociable"
    "shipany"
    "show-all-comments-in-one-page"
    "vindi-woocommerce-subscriptions"
    "wp-google-plus-connect"
    "bbpress-pencil-unread"
    "just-the-page"
    "ezyonlinebookings-online-booking-system"
    "please-link-2-me"
    "better-http-redirects"
    "formfacade"
    "contact-form-x"
    "bp-member-swipe"
    "accordion-menu"
    "weather-press"
    "awesome-guten-text"
    "wp-sendgrid-mailer"
    "css3-preloader-ultimate"
    "wp-gallery-remote"
    "clicktoaddress-auto-complete"
    "bbpress-report-content"
    "wp-politic"
    "bring-back-the-get-shortlink-button"
    "r3df-dashboard-language-switcher"
    "the-daily-horoscope"
    "disable-wp-registration-page"
    "premmerce-woocommerce-multi-currency"
    "anything-order-by-terms"
    "tabs-in-post-editor"
    "woo-pricing-table"
    "create-category-in-bulk"
    "fikraticker"
    "cb-pinterest-image-pinner"
    "organic-custom-content"
    "open-rdw-kenteken-voertuiginformatie"
    "adminpad"
    "acf-dropzone"
    "flickr-photo-post"
    "cross-promotion-content-recommendations"
    "photopress"
    "blog-manager-wp"
    "cryptocurrency-price-widget"
    "group-forum-subscription-for-buddypress"
    "fx-editor"
    "ccavenue-gateway-for-woocommerce"
    "blog-introduction"
    "show-twitter-followers"
    "spacious-toolkit"
    "wp-qiniu"
    "font-size"
    "gd-topic-polls"
    "countdown"
    "mailster-live"
    "new-simple-gallery"
    "wp-thumbnail"
    "post-list-wp"
    "advanced-product-wishlist-for-woo"
    "eazy-ad-unblocker"
    "wp-custom-widget"
    "wp-e-commerce-product-showroom"
    "remove-orphan-shortcodes"
    "wp-hijri"
    "scissors-watermark"
    "wp-maintenance-developer"
    "mw-wp-form-recaptcha"
    "updated-today-plugin"
    "bg-patterns"
    "onceki-yazi-linki"
    "vikappointments"
    "tinymce-emoticons"
    "ical-events"
    "daily-horoscope-wp-widget"
    "animategl"
    "maje-media-remove-admin-bar"
    "bp2wp-full-sync"
    "make-pdf-newspaper"
    "advanced-category-column"
    "eazy-cf-catpcha"
    "gallery-for-ultimate-member"
    "wp-hide-show-featured-image"
    "ship-to-a-different-address-checked-unchecked"
    "linkt"
    "wow-armory"
    "viral-sign-ups"
    "category-post-shortcode"
    "carbon-copy"
    "razorpay-subscriptions-for-woocommerce"
    "quick-flag"
    "registered-only"
    "three-column-screen-layout"
    "wp-post-nav"
    "storeya-like-box"
    "themerain-core"
    "print-this-page"
    "category-shortcode-w-generator"
    "font-awesome-wp"
    "cheetaho-image-optimizer"
    "bbpress-threaded-replies"
    "pinyin-permalink"
    "dokan-vendor-dashboard"
    "jotform-integration"
    "wp-simple-anchors-links"
    "tags-page"
    "customizable-search-widget"
    "woo-yapay"
    "yet-another-simple-gallery"
    "pdf-catalog-woocommerce"
    "ai-co-pilot-for-wp"
    "unlimited-theme-addons"
    "wpms-site-maintenance-mode"
    "latest-custom-post-type-updates"
    "wployalty"
    "kits-templates-and-patterns"
    "wordpress-data-guards"
    "contact-form-7-gravity-forms"
    "meks-quick-plugin-disabler"
    "wc-booster"
    "hidden-wp-admin"
    "tinymce-advanced-qtranslate-fix-editor-problems"
    "content-audit"
    "allow-epub-and-mobi-formats-upload"
    "ip-address-widget-ii"
    "enhanced-header-footer-injections"
    "subscribe-to-download-lite"
    "cardgate"
    "gpp-base-hook-widgets"
    "export-plus"
    "shadows"
    "visualmodo-elements"
    "oembed-external-video"
    "active-campaign-wpforms"
    "playerzbr"
    "advanced-301-and-302-redirect"
    "ultimate-twitter-profile-widget"
    "wp-sendfox"
    "smart-agenda-prise-de-rendez-vous-en-ligne"
    "afterpay-payment-gateway-for-woocommerce"
    "admin-search"
    "automatic-internal-links-for-seo"
    "woo-binary-mlm"
    "modal-portfolio"
    "pipdisqus"
    "post-carousel-for-dv-builder"
    "bullhorn-oscp"
    "woo-rede"
    "fix-windows-compatibility"
    "wp-mobile-x"
    "launch-checklist"
    "wp-exclude-from-homepage"
    "purgely"
    "archive"
    "wp-video-html5-video-player"
    "dynamic-image-resizer"
    "wp-editor-fontsize"
    "genesis-shortcodes"
    "buddypress-usernames-only"
    "emoji-toolbar"
    "dbc-backup-2"
    "site-closed"
    "hybrid-hook"
    "postmagthemes-demo-import"
    "bbp-user-ranking"
    "mtphr-galleries"
    "menubar-widgets"
    "checkoutx"
    "duplicate-tec-event"
    "sandbox"
    "home-page-slideshow"
    "custom-metadata"
    "fnffm-radio"
    "genesis-accessible"
    "paytm-donation"
    "seo-kiss"
    "xt-woo-ajax-add-to-cart"
    "linkedin-sc"
    "company-presentation"
    "metatag"
    "kagg-pagespeed-module"
    "gosign-posts-slider-block"
    "cool-author-box"
    "simpleanalytics"
    "vertical-scroll-slideshow-gallery-v2"
    "msrp-for-woocommerce"
    "comment-license"
    "before-after-image-comparison-slider-for-visual-composer"
    "nextgen-gallery-comments"
    "woo-product-slider-block"
    "kento-splash-screen"
    "sellsy"
    "cf7-cleverreach-integration"
    "wc-wise-gateway"
    "mailster-mailgun"
    "post-sliders"
    "wp-term-colors"
    "wiki-embed"
    "background-changer"
    "imagelightbox"
    "simple-post-expiration"
    "mailer-dragon"
    "advanced-fancybox"
    "array-toolkit"
    "notely"
    "drivr-google-drive-file-picker"
    "maxicharts-gravity-forms-source-add-on"
    "ip-locator"
    "rss-2-post"
    "smart-product-gallery-slider"
    "suevafree-essential-kit"
    "seatreg"
    "skyword-plugin"
    "registrations-for-woocommerce"
    "wp-magnific-popup"
    "acf-ninjaforms-add-on"
    "multicolumn-category-widget"
    "contact-page"
    "scroll-text-widget"
    "wp-admin-microblog"
    "simple-owl-carousel"
    "progressive-web-apps"
    "customer-reviews-for-woocommerce"
    "page-specific-sidebars"
    "pjw-page-excerpt"
    "video-gallery-playlist"
    "custom-login-logo-lite"
    "admin-locale"
    "color-scheme-every-theme"
    "postcodes4u-address-finder"
    "specific-cssjs-for-posts-and-pages"
    "auto-thumbnailer"
    "wp-quick-post-duplicator"
    "woo-shipping-for-nova-poshta"
    "woocommerce-drop-down-cart-widget"
    "pe-category-filter"
    "xunhu-alipay-payment-for-woocommerce"
    "wpspeed-localbusiness-schema"
    "mobileesp-for-wordpress"
    "disable-url-autocorrect-guessing"
    "simpaisa-wallet-payment-services"
    "cf7-material-design"
    "gravity-forms-auto-placeholders"
    "page-hierarchy-plug-in"
    "multidomain"
    "gamipress-buddypress-group-leaderboard"
    "honeypot-toolkit"
    "better-adsense-targeting"
    "feeder-ninja-feed"
    "asset-queue-manager"
    "insert-amazon-images"
    "premium-seo-pack-light-version"
    "sitewide-newsletter"
    "wpvn-username-changer"
    "c9-blocks"
    "noshop"
    "gn-xml-sitemap"
    "awesome-logo-carousel-block"
    "custom-comment-form-title"
    "acf-flexible-content-modal"
    "easy-verification"
    "tz-plus-gallery"
    "canonical-seo-content-syndication"
    "wp-mapa-politico-spain"
    "display-featured-image-in-post-list"
    "xtra-settings"
    "howescape-unity3d-webgl"
    "covid-19-alert"
    "simple-site-verify"
    "infolinks"
    "append-link-on-copy"
    "background-videos-for-visual-composer"
    "zi-hide-price-and-add-to-cart-for-woocommerce"
    "remove-protected-in-title"
    "wp-js-about-visitor"
    "woocommerce-prices"
    "memberlite-elements"
    "simple-podcasting"
    "wp-smtp-config"
    "christmas-countdown-clock"
    "visual-biography-editor"
    "boxberry"
    "os-diagnosis-generator"
    "kortez-toolset"
    "archive-title"
    "resizable-editor-sidebar"
    "genesis-admin-bar-plus"
    "dadevarzan-common"
    "reverbnation-widgets"
    "checklist"
    "pryc-wp-tinymce-more-buttons"
    "jigsaw"
    "security-protection"
    "post-to-csv"
    "wp-recaptcha-bp"
    "advanced-shipping-validation-for-woocommerce"
    "react"
    "seo-stats-widget"
    "captain-up"
    "feed-for-tiktok"
    "iconic-navigation"
    "gravatar-signup-encouragement"
    "bp-instant-chat"
    "startwp-extended"
    "eshoplogisticru"
    "bbpress-recaptcha"
    "advanced-featured-page-widget"
    "slideshare-oembed-for-wordpress"
    "read-later-buttons"
    "affiliatewp-external-referral-links"
    "elastic-email-subscribe-form"
    "permalink-trailing-slash-fixer"
    "anchor-block"
    "elfsight-addons-for-elementor"
    "plerdy-heatmap"
    "x-currency"
    "advanced-font-changer"
    "buddypress-maps"
    "wpsso-organization-place"
    "ejabberd-account-tools"
    "genesis-extra-settings-transporter"
    "travelmap-blog"
    "sensitive-tag-cloud"
    "category-coloumn"
    "particle-background"
    "sakolawp-lite"
    "wp-evernote-site-memory"
    "sharing-is-caring"
    "browsealoud"
    "falling-things"
    "ai-muse"
    "advanced-steam-widget"
    "acf-restrict-color-picker"
    "report-broken-links"
    "theme-data-importor-by-phoeniixx"
    "minotar-minecraft-avatars"
    "vertical-menu-widget"
    "voice-search"
    "customizer"
    "acymailing-integration-for-woocommerce"
    "cf7-gated-content"
    "easy-content-slider"
    "mobile-navigation"
    "harrys-gravatar-cache"
    "embedder-for-google-reviews"
    "wp-post-meta-revisions"
    "en-spam"
    "social-share-floating-icons"
    "egw-widgets-hover-effects"
    "rename-taxonomies"
    "blighty-explorer"
    "wc-wallet"
    "woo-show-single-variations-shop-category"
    "wp-hotel-booking-stripe-payment"
    "supapress"
    "buddypress-who-clicked-at-my-profile"
    "custom-template-lifterlms"
    "seriously-simple-speakers"
    "affiliate-ads-builder-for-clickbank-products"
    "virtuaria-pagseguro"
    "image-flicker"
    "mutual-buddies"
    "woo-sold-individually-for-variations"
    "ark-relatedpost"
    "ev-widget-post"
    "skyroom-wp"
    "wp-create-multiple-posts-pages"
    "beans-woocommerce-loyalty-rewards"
    "thoughtful-comments"
    "3dcart-wp-online-store"
    "tamara-checkout"
    "business-reviews-wp"
    "contact-us-by-lord-linus"
    "permissions-editor-for-ninja-forms"
    "tinymce-editor-font-fix"
    "ab-google-map-travel"
    "inspector-wp"
    "taxonomy-discounts-woocommerce"
    "wpc-smart-notification"
    "cmyee-momentopress"
    "edd-coming-soon"
    "cjdropshipping"
    "responsive-videos-fitvids"
    "autocomplete-for-relevanssi"
    "wp-sri"
    "page-tag-cloud"
    "html-post-editor-new"
    "bulk-edit-posts-on-frontend"
    "gwebpro-store-locator"
    "speed-up-clean-wp"
    "easy-video-reviews"
    "f2-tumblr-widget"
    "enable-wp-debug-from-admin-dashboard"
    "wp-php-version-display"
    "cosmic-blocks"
    "collect-and-deliver-interface-for-woocommerce"
    "aspose-pdf-exporter"
    "notes-widget-wrapper"
    "cc-bmi-calculator"
    "wp-qr-code-generator"
    "jcwp-youtube-channel-embed"
    "custom-preloader"
    "pmc-disable-comments"
    "author-post-ratings"
    "echelon-so"
    "cbxgooglemap"
    "events-manager-zoom"
    "change-username"
    "bp-group-frontpage"
    "geo-to-lat"
    "arena-liveblog-and-chat-tool"
    "hide-my-dates"
    "svg-favicon"
    "contact-widgets-for-elementor"
    "adiaha-hotel"
    "wc-webmoney"
    "discography"
    "webfinger"
    "force-plugin-updates-check"
    "gys-themed-categories-2"
    "digitalsignagepress-lite"
    "m1downloadlist"
    "addressbook"
    "simple-www-redirect"
    "content-switcher"
    "site-launcher"
    "decimal-product-quantity-for-woocommerce"
    "woocommerce-and-wp-emember-integration"
    "better-youtube-embed-block"
    "wpc-product-size-chart"
    "allow-wordpowerpoint-file-uploads"
    "advanced-custom-fields-limiter-field"
    "plugin-grouper"
    "slyd"
    "wc-shipstation-shipping"
    "simple-theme-options"
    "bp-tinymce"
    "templates-and-addons-for-wpbakery-page-builder"
    "enhanced-search-form"
    "free-online-plagiarism-checker"
    "spiderdisplay"
    "use-administrator-password"
    "wpmu-no-nag"
    "woo-salesforce-plugin-crm-perks"
    "clean-notifications"
    "h5pxapikatchu"
    "sb-popular-posts-tabbed-widget"
    "sitespeaker-widget"
    "cricket-moods"
    "leaddyno"
    "thinktwit"
    "ezwebplayer-wordpress-pro-video-plugin"
    "sinking-dropdowns"
    "wp-profitshare"
    "quadmenu-avada"
    "live-simple-clock"
    "tlitl-auto-twitter-poster"
    "ccbpress-core"
    "mangopay-woocommerce"
    "shoppingfeeder"
    "improved-user-search-in-backend"
    "delink-comment-author"
    "idataffiliates"
    "shiptimize-for-woocommerce"
    "wppao-sitemap"
    "wpcc-seo-meta-keywords"
    "pronamic-events"
    "wp-bible"
    "featured-link-image"
    "jumplead"
    "current-template-name"
    "replace-default-words"
    "remove-noreferrer"
    "wpc-product-table"
    "google-maps-travel-route"
    "simple-definition-list-blocks"
    "hum"
    "wp-post-disclaimer"
    "rollover-tab"
    "social-media-widget-icon"
    "showpass"
    "query-monitor-twig-profile"
    "customizer-custom-css"
    "woocommerce-photos-product-tab"
    "consolety"
    "custom-post-type-rewrite"
    "easy-paypal-digital-downloads"
    "dynamic-animations-for-elementor"
    "widgets-in-columns"
    "timeline-express-html-excerpt-add-on"
    "default-media-uploader-view"
    "bulk-add-terms"
    "simple-responsive-images"
    "snow-my-wp"
    "google-weather-4-wp"
    "hoo-contact-form"
    "wordpress-comment-images"
    "wpmktgengine"
    "bns-smf-feeds"
    "wp-image-makers-easy-hotspot-solution"
    "premmerce-redirect-manager"
    "payever-woocommerce-gateway"
    "realhomes-xml-csv-property-listings-import"
    "server-status-for-minecraft-pc-pe"
    "wp-joomag"
    "wc-save-for-later"
    "simple-notices"
    "woocommerce-quick-view-lite"
    "events-listing-widget"
    "easy-yandex-metrica"
    "wc-call-for-price"
    "forumwp"
    "edd-paystack"
    "wp-catergory-show"
    "fancy-lightbox"
    "woo-pelecard-gateway"
    "flexo-slider"
    "physical-custom-upload-folder"
    "fade-in-fade-out-xml-rss-feed"
    "recent-related-post-and-page"
    "woo-cart-limit"
    "gravity-forms-post-updates"
    "gosign-gallery-box-block"
    "numix-post-slider"
    "wp-instantarticles"
    "comment-form-csrf-protection"
    "liza-spotify-widget-for-elementor"
    "ajax-random-posts"
    "image-editor-by-pixo"
    "order-delivery-date-and-time"
    "sportspress-for-ice-hockey"
    "wp-cron-cleaner"
    "auction-software"
    "shortcodes-in-sidebar"
    "photection"
    "byrev-gallery-pagination-for-wordpress"
    "w2s-migrate-woo-to-shopify"
    "projectopia-core"
    "content-parts"
    "seo-backlink-monitor"
    "html5-boilerplate"
    "meta-tags-for-seo"
    "backup-restore-divi-theme-options"
    "terms-popup-on-user-login"
    "announcement-bar"
    "fixed-widget-area"
    "anac-xml-viewer"
    "komoju-japanese-payments"
    "easy-widget-columns"
    "wp-galleria"
    "be-media-from-production"
    "tp-gallery-slider"
    "bykea-cash-online-payments"
    "pushnews"
    "contact-form-7-get-and-show-parameter-from-url"
    "usercentrics-consent-management-platform"
    "get-post"
    "wpmu-plugin-stats"
    "wp-smugmug"
    "wedgies-shortcode"
    "wp-images-lazy-loading"
    "shortpixel-critical-css"
    "tabbed-sidebar-widgets"
    "individual-multisite-author"
    "gf-block-ips"
    "lj-longtail-seo"
    "wp-router"
    "simple-social-login"
    "wild-apricot-login"
    "map-my-posts"
    "image-shadow"
    "json-feed"
    "force-password-change"
    "demo-bar"
    "text-control-2"
    "woocommerce-putler-connector"
    "musopress-discography"
    "login-logger"
    "ithemeland-woo-bulk-product-editor-lite"
    "cleaner-plugin-installer"
    "wp-property-listings"
    "members-page-only-for-logged-in-users"
    "youtube-thumbnailer"
    "google-map-with-fancybox-popup"
    "mhm-menu-separator"
    "protect-schemaorg-markup-in-html-editor"
    "manage-upload-types"
    "custom-team-manager"
    "root-cookie"
    "document-repository"
    "advanced-dewplayer"
    "bsecure"
    "style-tweaker"
    "hierarchy"
    "second-street-promotion"
    "pics-mash"
    "uix-page-builder"
    "mailup-email-and-newsletter-subscription-form"
    "wpcos"
    "edd-toolbar"
    "quotes-shortcode-and-widget"
    "wp-prefix-changer"
    "simple-social-bar"
    "cyberpress"
    "header-customizer-lite"
    "m4wp-portfolio"
    "bp-xprofile-wp-user-sync"
    "gf-hubspot"
    "transliterado"
    "add-cloned-sites-for-wpmu-batch"
    "autothumb"
    "additional-order-filters-for-woocommerce"
    "woocommerce-digital-content-delivery-with-drm-flickrocket"
    "powered-minifier"
    "counters-block"
    "pal-for-edd"
    "apptivo-business-site"
    "plugin-test-drive"
    "privilege-widget"
    "cryptopay-wc-lite"
    "recent-comments-widget-with-comment-excerpts"
    "cloudflare-cache-purge"
    "wp-subdomains-revisited"
    "under-construction-light"
    "gravityformsapprovals"
    "ctrify"
    "wp-twitterbadge"
    "css3-transitions"
    "interactive-polish-map"
    "automatically-hierarchic-categories-in-menu"
    "easydigitaldownloads-hoststreamsell-extension"
    "display-post-metadata"
    "pargo"
    "culqi-checkout"
    "blog-post-calendar-widget"
    "google-reader-widget"
    "elex-minimum-order-amount-for-woocommerce"
    "restore-paypal-standard-for-woocommerce"
    "relocate-upload"
    "front-page-cats"
    "get-chat-app"
    "terms-and-conditions-per-product"
    "mailster-multi-smtp"
    "posti-shipping"
    "creative-instagram"
    "dashboard-post-it"
    "hybrid-hook-widgets"
    "wp-multilingual-sitemap"
    "autocomplete-address-and-location-picker-for-woocommerce"
    "wp-ds-faq-plus"
    "infinite-slider"
    "edd-digital-signature-add-on"
    "oxygen-tutor-lms"
    "canonical-link"
    "textme-sms-integration"
    "quote-of-the-day-itslum"
    "hide-cart-functions"
    "address-geocoder"
    "melonpan-block-container"
    "um-jobboardwp"
    "shipcloud-for-woocommerce"
    "ai-auto-tool"
    "sf-adminbar-tools"
    "memberpress-addon-for-wp-courseware"
    "sheetdb"
    "woo-ukrposhta"
    "apaczka-pl-mapa-punktow"
    "wp-parsi-jwplayer"
    "xhanch-my-quote"
    "xl-tab"
    "offsprout-page-builder"
    "wp-tarteaucitron-js-self-hosted"
    "wp-geonames"
    "woocommerce-buddypress-integration-xprofile-checkout-manager"
    "karma-by-kadar"
    "yektanet-ecommerce"
    "recent-posts-slider-responsive"
    "echbay-facebook-messenger"
    "passwords-evolved"
    "basic-bilingual"
    "easy-wp"
    "crypto-coin-ticker"
    "replain"
    "xpert-tab"
    "stock-market-charts-from-finviz"
    "genesis-bootstrap-carousel"
    "superfish"
    "post-editor-buttons-fork"
    "lj-custom-menu-links"
    "sports-rankings-lists"
    "touch-fashion-slider-elementor-addon"
    "fapi-member"
    "related-content-by-plugz"
    "fluent-boards"
    "last-updated-shortcode"
    "rss-via-shortcode-on-page-post"
    "slazzer-background-changer"
    "twitters-bootstrap-shortcodes-ultimate"
    "shoutcast-and-icecast-html5-web-radio-player-by-yesstreaming-com"
    "wp-custom-menu-filter-plugin"
    "twitter-digest"
    "gf-upload-to-email-attachment"
    "woo-billomat"
    "f4-woocommerce-shipping-phone-and-e-mail"
    "just-responsive-images"
    "wp-system-info"
    "xt-woo-points-rewards"
    "buddymenu-buddylinks"
    "wpgcal"
    "woo-accounting-report"
    "ultimate-ajax-login"
    "knr-author-list-widget"
    "address-validation-address-auto-complete"
    "responsive-table"
    "genesis-simple-breadcrumbs"
    "cat-by-tags-table"
    "razorpay-payment-button-elementor"
    "easy-digital-downloads-frontend-submissions-product-details-widget"
    "better-core-video-embeds"
    "developer-mode"
    "post-carousel-divi"
    "plugin-notes"
    "tinymce-visual-editor-comment"
    "wp-featured-soliloquy-sliders"
    "wpnamedusers"
    "revision-cleaner"
    "hide-archive-label"
    "timeline-block-block"
    "blockstrap-page-builder-blocks"
    "hide-wp-login"
    "simple-seo-pack"
    "chikkili-google-pay-for-woocommerce"
    "wc-search-orders-by-product"
    "catch-scroll-progress-bar"
    "ht-team-member"
    "wordpress-jquery-ui-effects"
    "wp-visitorflow"
    "slimbox-2-slideshow"
    "custom-field-for-wp-job-manager"
    "easy-dash-for-learndash"
    "live-search-custom-fields-lite"
    "unofficial-twitter-widget"
    "clink"
    "guardgiant"
    "widget-output-cache"
    "about-the-author-advanced"
    "mobile-menu-builder"
    "bard-extra"
    "woo-load-group-attributes-product"
    "woocommerce-categories-menu"
    "bonway-static-block-editor"
    "lf-hiker"
    "cartboss"
    "pwd-wp-favicon"
    "wp-jquery-pdf-paged"
    "adrotate-switch"
    "news-ticker-for-wordpress"
    "wp-theater"
    "multisite-user-registration-manager"
    "kredeum-nfts"
    "enable-standard-paypal-for-woocommerce"
    "wp-sexylightbox"
    "wp-easy-events"
    "easy-panorama"
    "wp-home-page-menu"
    "wiser-notify"
    "pageloader-lite"
    "ws-force-login-page"
    "booking-system-edoobox"
    "wp-login-timeout-settings"
    "simple-spoiler"
    "prettify-code-syntax"
    "chronological-posts"
    "genesis-optimized-social-share"
    "searchwp-api"
    "snapwidget-wp-instagram-widget"
    "dashboard-maintenance-mode"
    "tags4page"
    "kento-ads-rotator"
    "search-replace-for-elementor"
    "360-video"
    "enhanced-custom-permalinks"
    "majestic-support"
    "genesis-widgetized-archive"
    "phpsword-google-analytics"
    "timeline-twitter-feed"
    "rentmy-online-rental-shop"
    "invoicing-quotes"
    "country-code-selector"
    "dima-take-action"
    "theme-blvd-importer"
    "wp-post-series"
    "spam-byebye"
    "accessibility-enabler"
    "better-yourls"
    "post-meta-controls"
    "multidealer"
    "fix-alt-text"
    "call-to-action-widget"
    "post-meta-data-manager"
    "gsearch-plus"
    "viabill-woocommerce"
    "openpay-spei"
    "custom-database-applications-by-caspio"
    "price-table-for-wpbakery-page-builder"
    "rss-blogroll"
    "stripe-checkouts"
    "podbean-shortcode"
    "my-reservation-system"
    "wp-max-submit-protect"
    "simple-slider"
    "metalpriceapi"
    "contact-form-7-customfield-in-mail"
    "wechat"
    "storefront-jetpack"
    "wpzoom-beaver-builder-templates"
    "onesignal-sender"
    "bank-mellat-edd-gateway"
    "wp-datatable"
    "dx-auto-publish"
    "reset-database"
    "postname-permalink-auto-redirect"
    "ufhealth-require-image-alt-tags"
    "charts-and-graphs-for-elementor"
    "enhanced-youtube-shortcode"
    "boei-help"
    "weather-in-any-city-widget"
    "text-slider-testimonial"
    "watchcountcom-wordpress-plugin"
    "swiftninjapro-inspect-element-console-blocker"
    "xml-for-avito"
    "author-filters"
    "auto-post-after-image-upload"
    "two-factor-auth"
    "wp-subscribe-author"
    "icon-separator"
    "admin-username-changer"
    "custom-page-menus"
    "breadcrumb-block"
    "wp-optimizer"
    "import-xml-csv-settings-to-all-in-one-seo-pack"
    "ultimate-fields"
    "spam-stopper"
    "woocommerce-billink"
    "empty-wp-blog-or-website"
    "brs-booking-reservation-system-woocommerce"
    "easy-wysiwyg-style"
    "page-rank-stats-for-alexa-google"
    "gp-social-share-svg"
    "alibaba"
    "matchheight"
    "add-post-thumbnail-shortcode"
    "specify-missing-image-dimensions"
    "w3dev-fancybox"
    "pta-shortcodes"
    "fullscreen-background"
    "smooth-streaming-player"
    "personal-contact-info-widget"
    "ht-newsletter-for-elementor"
    "sn-rating"
    "wp-siren-recent-posts-by-category"
    "category-visibility-ipeat"
    "product-bundles-bulk-discounts-for-woocommerce"
    "tl-coming-soon"
    "am-events"
    "featured-audio"
    "ifttt-bridge"
    "ar-for-woocommerce"
    "testimonial-wp-block"
    "hashbuddy"
    "widget-classes"
    "elegant-themes-demo-importer"
    "oomph-hidden-tags"
    "iprojectweb"
    "custom-post-type-parents"
    "contact-form-7-infusionsoft-add-on"
    "mb-imagechimp-rss-feed-enhancer"
    "block-for-mailchimp"
    "add-link-to-copied-text"
    "word-statistics-plugin"
    "classy-wp-list-pages"
    "posts-viewed-recently"
    "cf7-getresponse"
    "aba-payway-woocommerce-payment-gateway"
    "houzez-woo-addon"
    "suffusion-shortcodes"
    "paypal-donation"
    "tube-video-curator"
    "improved-sale-badges-free-version"
    "old-post-spinner"
    "html5-video-background"
    "cloudfilt-codes"
    "marketing-and-seo-booster"
    "sip-reviews-shortcode-woocommerce"
    "debounce-io-email-validator"
    "custom-post-type-rss-feed"
    "video-thumbnails-reloaded"
    "asteroids-widget"
    "google-plus-badge-like-fb-like-box"
    "woo-pacsoft-unifaun"
    "hello-world"
    "contact-form-7-city-field-extension"
    "crypto"
    "heyoya-voice-comments-reviews"
    "suicide"
    "timed-content-for-beaver-builder"
    "auto-woocommerce-affiliate-account-creation"
    "faq-block"
    "chicory-recipe-ingredients"
    "remove-comment-websiteurl-box"
    "book-previewer-for-woocommerce"
    "dublin-core-metadata-generator"
    "woominecraft"
    "pay-with-paytm-qr-offline-payment-gateway"
    "image-feed-widget"
    "posts-list"
    "adbutler"
    "minecraft-server-status-checker"
    "russian-privacy-policy-page-and-notice"
    "kino-event-calendar-plugin"
    "ithemelandco-woo-report"
    "bwp-polldaddy"
    "eelv-newsletter"
    "payssion-international-payment-gateway"
    "etsy-importer"
    "drip-gravity-forms"
    "wish-wait-list-for-woocommerce"
    "quotable"
    "ck-and-syntaxhighlighter"
    "connections-toolbar"
    "wp-sheet-editor-edd-downloads"
    "nodeinfo"
    "plationline"
    "reading-time"
    "rehashs-twitter-widget"
    "simple-googlebot-visit"
    "civil-footnotes"
    "are-you-robot-recaptcha"
    "gestione-circolari"
    "username"
    "clerkio"
    "wp-hide-category"
    "portfolio-manager-lite"
    "cal-embedder-lite"
    "header-enhancement"
    "plugin-toggle"
    "default-sort-ascend"
    "hashtag"
    "easy-post-types-fields"
    "simply-hide-pages"
    "sportspress-for-baseball"
    "cookiebar"
    "maestro-connector"
    "send-from"
    "wp-prestashop"
    "wp-countdown-block"
    "wp-referral-code"
    "iframe-wrapper"
    "cyrillic-slugs"
    "wp-service-payment-form-with-authorizenet"
    "ai-image-generator-lab"
    "filled-in"
    "affiliatewp-allow-own-referrals"
    "wp-excerpt-generator"
    "menu-item-duplicator"
    "oauth-client-for-user-authentication"
    "chamber-dashboard-events-calendar"
    "remove-rss-feed"
    "dashboard-notes"
    "webcam-viewer"
    "video-codes"
    "wp-ad-manager"
    "preload-featured-images"
    "jonradio-display-kitchen-sink"
    "user-domain-whitelist"
    "visit-counter"
    "redirect-all-types"
    "nativerent"
    "svegliat-buttons"
    "china-video-block"
    "oganro-reservation-widget"
    "terms-order-wp"
    "client-documentation"
    "upload-widget"
    "responsive-post-preview"
    "igit-posts-slider-widget"
    "select-featured-posts"
    "simple-price-calculator-basic"
    "sliced-invoices-gravity-forms"
    "frontend-dashboard-captcha"
    "payment-gateways-by-currency-for-woocommerce"
    "rsvp-me"
    "support-webp"
    "theme-inspector"
    "indicate-external-links"
    "evolution-google-analytics-code"
    "geetest"
    "openpix-for-woocommerce"
    "image-responsive-slider"
    "liteweight-podcast"
    "petfinder-listings"
    "widget-pagination"
    "instant-articles"
    "wpqr-qr-code"
    "csh-login"
    "personal-welcome"
    "gpp-about-you-widget"
    "sharing-plus"
    "feedblitz-feedsmart"
    "custom-block-patterns"
    "wp-editarea"
    "swift-demo-import"
    "wp-ssl-redirect"
    "bws-linkedin"
    "b-pricing-table"
    "exit-pop"
    "performance-optimization-order-styles-and-javascript"
    "pages-children"
    "floating-widgets"
    "revi-io-customer-and-product-reviews"
    "genesis-hooks"
    "scrollbar-designer"
    "subscriber-discounts-for-woocommerce"
    "nepali-post-date"
    "online-leaf"
    "marekkis-watermark"
    "zillaportfolio"
    "uk-address-postcode-validation"
    "3-word-address-validation-field"
    "markdown-for-wordpress-and-bbpress"
    "annonces"
    "magic-tooltips-for-contact-form-7"
    "multi-currency-wallet"
    "codebulls-top-bar"
    "spreadr-for-woocomerce"
    "easy-popup"
    "social-icon-widget"
    "wp-zillow-review-slider"
    "plagiarism"
    "woo-graphql-api"
    "cf7-sms-extension"
    "call-me-spoot"
    "woocommerce-direct-variation-link"
    "wp-easy-poll-afo"
    "twst-login-block"
    "woo-slider-pro-drag-drop-slider-builder-for-woocommerce"
    "faceted-search"
    "widget-box-lite"
    "elfsight-blocks"
    "wp-customize-login-page"
    "nextgenthemes-jsdelivr-this"
    "easy-tynt"
    "mycbgenie-clickbank-storefront"
    "simple-author-highlighter"
    "wpbits-addons-for-elementor"
    "17track"
    "cardinity-free-payment-gateway-for-woocommerce"
    "wp-yomigana"
    "replace-broken-images"
    "post-list"
    "text-scrolling-widget"
    "advanced-custom-fields-taxonomy-field-add-on"
    "werk-aan-de-muur"
    "featured-image-in-content"
    "responsive-photo-gallery-wp"
    "multimediamonster-full-screen-background-images"
    "cf7-mce"
    "sopa-blackout-plugin"
    "comment-form-js-validation"
    "social-counters"
    "custom-product-stickers-for-woocommerce"
    "admin-links-sidebar-widget"
    "calculo-do-frete-somente-com-o-cep-wc-brasil"
    "ultimate-fonts"
    "rtler"
    "wishlist-member-addon-for-wp-courseware"
    "easy-fullscreen-slider"
    "wp-url-shorten"
    "custom-post-types-relationships-cptr"
    "paypal-promotions-and-insights"
    "opensea"
    "jin-menu"
    "wp-compare-tables"
    "file-media-renamer"
    "if-widget"
    "shipping-viet-nam-woocommerce"
    "de_de"
    "lorem-shortcode"
    "external-video-for-everybody"
    "f4-total-stock-value-for-woocommerce"
    "gobot"
    "ltl-freight-quotes-worldwide-express-edition"
    "image-mapper"
    "toplistcz"
    "mark-posts"
    "jetpack-contact-form-auto-reply"
    "wp-simple-custom-form"
    "nextgen-gallery-date"
    "bug-library"
    "astoundify-recaptcha"
    "woo-mailchimp-newsletter-discount"
    "gazchaps-woocommerce-auto-category-product-thumbnails"
    "post-type-select-for-advanced-custom-fields"
    "sports-club-management"
    "facto-facturacioacuten-electroacutenica"
    "stylish-google-sheet-reader"
    "the-events-calendar-user-css"
    "property-hive-stamp-duty-calculator"
    "qzzr-shortcode"
    "gs-only-pdf-preview"
    "customized-recent-comments"
    "postepay-woocommerce-gateway"
    "slivery-extender"
    "simple-content-slider"
    "shape-dividers-plus"
    "bp-simple-private"
    "advanced-custom-fields-oembed-field"
    "wp-link-preview"
    "date-time-picker-for-wpforms"
    "multiple-location-google-map"
    "instashop"
    "wp-smushit-nextgen-gallery-integration"
    "wp-surveys"
    "hesabfa-accounting"
    "mstw-schedules-scoreboards"
    "cf7-custom-spinner"
    "dynamic-widget-content"
    "wp-bootstrap-navmenu"
    "fast-flickr-widget"
    "link-to-url-post"
    "awebsome-online-registered-users-widget"
    "pdf-builder-for-gravity"
    "vlibras-widget"
    "initial-letter"
    "wordpress-hebrew-date"
    "moojax-comment-posting"
    "twitter-real-time-search-scrolling"
    "subscription-payu-latam"
    "page-takeover"
    "the-single-background"
    "logo-slideshow"
    "daext-autolinks-manager"
    "siliconfolio"
    "b2i-investor-tools"
    "rays-grid"
    "gf-uploads-as-attachments"
    "disable-gravity-forms-fields"
    "woocommerce-cestina"
    "hd-quiz-save-results-light"
    "fusion-extension-menu"
    "syntax-highlighter-with-add-button-in-editor"
    "widget-instance"
    "simple-responsive-menu"
    "news-ticker-tj"
    "cuelinks"
    "potter-kit"
    "embed-github-gist"
    "promolayer-popup-builder"
    "addfunc-mobile-detect"
    "indianic-testimonial"
    "limit-attempts-booster"
    "cssjockey-add-ons"
    "evernote-sync"
    "get-user-custom-field-values"
    "free-vehicle-data-uk"
    "wc-provincia-canton-distrito"
    "nofollow-internal-links"
    "sticky-header-2020"
    "anti-spam-reloaded"
    "hjqs-mentions-legales-fr"
    "awin-data-feed"
    "integration-with-bitrix24"
    "jcwp-scroll-to-top"
    "call-to-action-customizable-block"
    "remarkety-for-woocommerce"
    "wpcommand"
    "wp-flashy-marketing-automation"
    "relevanssi-light"
    "dx-login-register"
    "robokassa-payment-gateway-saphali"
    "bea-sanitize-filename"
    "visual-sitemap"
    "okay-toolkit"
    "wp-hotel-booking-wpml-support"
    "amazon-product-feeder"
    "xm-backup"
    "better-variation-price-for-woocommerce"
    "wp-spid-italia"
    "flipping-cards"
    "simple-google-news-de"
    "csv-to-webpage-plugin"
    "woo-sofortuberweisung-gateway"
    "social-links-sidebar"
    "wp-featured"
    "joomsport-prediction"
    "milestone"
    "easycron"
    "wp-simple-related-posts"
    "price-field"
    "you-can-quote-me-on-that"
    "inazo-flamingo-automatically-delete-old-messages"
    "wp-admintools"
    "personal-dictionary"
    "multilingual-comments-number"
    "hide-wordpress-version"
    "vc-addon-for-wp-courseware"
    "product-preview-for-woocommerce"
    "html5-chat"
    "push-notifications-by-larapush"
    "external-url-featured-image"
    "wikipedia-preview"
    "ifolders"
    "wp-click-info"
    "agoda-affiliate-partners-text-link-generator"
    "rentpress-for-websites"
    "document"
    "safety-exit"
    "chamber-dashboard-crm"
    "genki-youtube-comments"
    "woo-random-product-sorting-with-pagination"
    "back-to-the-top-button"
    "google-404"
    "advanced-author-bio"
    "advanced-category-and-custom-taxonomy-image"
    "photo-gallery-portfolio"
    "wisepops-popups"
    "attention-grabber-hello-bar-alternative"
    "stranoweb-ajax-login"
    "buddypress-activity-stream-bar"
    "shortcode-generator"
    "wp-multicollinks"
    "wp-user-activity"
    "simple-attribution"
    "acf-focal-point"
    "wordpress-web-service"
    "ra-socialize-button"
    "live-2d"
    "stage-file-proxy"
    "fake-pay-for-woocommerce"
    "visibility-control-for-learnpress"
    "tg-copy-protection"
    "tr-post-slider-widget"
    "wp-custom-html-pages"
    "add-links-to-pages"
    "hamburger-icon-menu-lite"
    "fluent-booking"
    "woo-gateway-fedapay"
    "um-custom-tab-builder-lite"
    "bestfreebie-elementor-icons"
    "xg-accordion"
    "gamipress-multimedia-content"
    "slideonline"
    "wp-sync-for-notion"
    "gf-zoho"
    "admin-branding-and-tweaks"
    "modal-register"
    "tranzly"
    "custom-script-integration"
    "redirect2homepage"
    "automatic-nbsp"
    "advanced-currency-switcher"
    "animated-counters"
    "wp-mouse-custom-cursor"
    "screen-options-and-help-show-customize"
    "perfit-signup-form"
    "easy-download-media-counter"
    "hyper-pwa"
    "multiple-gf-form-on-single-page"
    "system-dashboard"
    "bp-group-chatroom"
    "optimize-javascript"
    "wpvivid-snapshot-database"
    "wpscreens"
    "igotweb-wp-mp-links"
    "twitter-follow-button-plugin"
    "kitpack-for-persian-elementor"
    "woo-popup"
    "conference-scheduler"
    "gravity-forms-popup-widget"
    "wp-theme-plugin-editor-disable"
    "age-gate-lite"
    "simple-pdf-exporter"
    "zopim-live-chat-addon"
    "court-reservation"
    "get-log-in"
    "jalbum-badge"
    "custom-registration-and-login"
    "jetpack-subscription-form"
    "animate-on-scroll"
    "bilingual-linker"
    "country-detection-polylang"
    "floating-nextprev"
    "expire-sticky-posts"
    "wp-polls-with-cubepoints"
    "wp-tweaks"
    "acf-page-builder-field"
    "easy-site-importer"
    "wp-support-ticket"
    "private-suite"
    "page-view-count-by-webline"
    "toolbar-extras-oxygen"
    "dfp-ads"
    "extended-super-admins"
    "sliding-enquiry-form"
    "global-shop-discount-for-woocommerce"
    "paste-as-plain-text"
    "visitor-counter"
    "sucursales-correo-argentino-para-woocommerce"
    "wettervorhersage"
    "wordpresscom-importer"
    "backwp"
    "mycustomizer-woocommerce-connector"
    "simple-block-gallery"
    "movable-type-backup-importer"
    "smartpay"
    "paygate-payweb-for-woocommerce"
    "buddypress-follow-me"
    "add-highslide"
    "like-dislike-plus-counter"
    "wp-stripe-global-payments"
    "seriously-simple-transcripts"
    "mpress-banners"
    "math-quiz"
    "new-post-notification"
    "woocommerce-product-badge"
    "floating-awesome-button"
    "wp2appir"
    "protected-wp-login"
    "sociable-polska-edycja"
    "webyx"
    "bcs-support"
    "opengraph-and-microdata-generator"
    "show-stock-quotes"
    "woocommerce-weight-country-based-shipping"
    "jvm-woocommerce-wishlist"
    "wpjaipho"
    "wc-custom-post-types"
    "etsy-widget"
    "search-tags"
    "rurumo"
    "multi-currency-paypal-donations"
    "icecast-now-playing"
    "ootb-openstreetmap"
    "chessgame-shizzle"
    "live-stream-badger"
    "outfunnel"
    "login-redirect"
    "product-price-by-formula-for-woocommerce"
    "product-size-charts-for-woocommerce"
    "xorbin-analog-flash-clock"
    "advanced-custom-fields-number-slider"
    "country-redirect"
    "restore-id"
    "jetpack-extras"
    "language-redirect"
    "simple-feature-requests"
    "streamweasels-youtube-integration"
    "wp-page-loading"
    "woo-variations-style-buttons"
    "only-for-registered-users"
    "wp-bcrypt"
    "hide-drafts-in-menus"
    "buddypress-shortcodes"
    "restore-classic-editor"
    "wordpress-posts-timeline"
    "woo-payumoney"
    "w2o-admin-drop-down-menu"
    "multi-location-google-map"
    "wanna-isotope"
    "add-user-metadata"
    "waka-bulk-page"
    "bmlt-wordpress-satellite-plugin"
    "remove-howdy"
    "fc-auto-loan-calculator"
    "mww-disclaimer-buttons"
    "gravity-forms-multi-currency"
    "buddykit"
    "no-title-tooltips"
    "force-non-ssl"
    "epicwin-subscribers"
    "replybox"
    "woo-dis-comments-and-ratings"
    "kint-php-debugger"
    "buddypress-recaptcha"
    "simple-shipping-labels-for-woocommerce"
    "content-grid-slider"
    "freepay-for-woocommerce"
    "caldera-forms-translation"
    "naked-social-share"
    "pure-php-localization"
    "polaroid-on-the-fly"
    "twb-woocommerce-reviews"
    "ammu-demo-import"
    "countdown-clock-timer"
    "wpfrom-email"
    "latest-posts-widget"
    "proof-factor-social-proof-notifications-for-woocommerce"
    "regen-thumbs"
    "some-chinese-please"
    "post-slides"
    "live-css-js-code-editor"
    "comments-not-replied-to"
    "wp-jobs"
    "excerpt-tools"
    "search-with-typesense"
    "hidpi-gravatars"
    "listicles"
    "bknewsticker"
    "video-embed-privacy"
    "hh-sortable"
    "ad-blocking-advisor"
    "wp-responsive-slab-text"
    "automatic-post-publishing-scheduler"
    "wp-sns-share"
    "map-block-leaflet"
    "lh-copy-media-file"
    "tm-replace-howdy"
    "wp-touch-slider"
    "ppm-accordion"
    "helloprint"
    "google-distance-calculator"
    "dashboard-widget-sidebar"
    "custom-posts-order"
    "wpc-variations-table"
    "affiliatewp-force-pending-referrals"
    "ultimate-content-views"
    "wp-copysafe-video"
    "off-page-seo"
    "advanced-custom-fields-widget-area-field"
    "wp-quiz-importer"
    "easy-youtube-gallery"
    "rankchecker-io-integration"
    "event-schema"
    "w3speedster-wp"
    "icon-fonts"
    "meta-box-text-limiter"
    "square-thumbnails"
    "awesome-visitor-counter"
    "run-sql-query"
    "client-scroller-widget"
    "qwerty-admin-panel-theme-plugin"
    "custom-css-and-js"
    "digital-license-manager"
    "mobile-css"
    "the-seo-rich-snippets"
    "bicycles-by-falbar"
    "badgeos-badgestack-add-on"
    "post-type-spotlight"
    "vipps-recurring-payments-gateway-for-woocommerce"
    "author-or-user-image"
    "dutchdate"
    "bbp-core"
    "bread"
    "advanced-xprofile-fields-for-buddypress"
    "splash-popup-for-woocommerce"
    "capital-epay-woocommerce-payment-gateway"
    "wp-soundsystem"
    "background-slideshow"
    "gamipress-leaderboards-include-exclude-users"
    "clearscope"
    "step-by-step"
    "lazy-load-control-for-elementor"
    "pofily-woo-product-filters"
    "nines-music"
    "form-to-post"
    "wpsso-google-merchant-feed"
    "pay-with-mtn-momo-woocommerce"
    "ajax-heartbeat-tool"
    "fcm-push-notification-from-wp"
    "flexi"
    "eonet-live-search"
    "dynamic-audio-player-basic"
    "post-gallery-slider"
    "to-do-list"
    "woo-direct-checkout-button"
    "advent-calender"
    "herzog-dupont"
    "backup-bolt"
    "kush-micro-news"
    "wpc-product-faqs"
    "page-list-widget"
    "disable-wp-theme-updates-advance"
    "ajax-dropdowns"
    "qnap-nas-backup"
    "bulk-term-generator"
    "https-domain-alias"
    "schema-for-article"
    "and-the-winner-is"
    "instant-css"
    "fg-opencart-to-woocommerce"
    "product-of-the-day-for-woocommerce"
    "headmeta"
    "simple-vertical-timeline"
    "payment-page"
    "seo-engine"
    "clinked-client-portal"
    "woo-sidebar-category-accordion"
    "webriti-custom-login-page"
    "aam-protected-media-files"
    "mz-mindbody-api"
    "email"
    "chip-for-woocommerce"
    "meks-easy-maps"
    "hootboard"
    "wc-phonepe"
    "bp-group-reviews"
    "gf-divi"
    "getresponse-official"
    "vc-flipbox"
    "another-events-calendar"
    "ftp-sync"
    "helcim-commerce-for-woocommerce"
    "wpc-smart-price-filter"
    "cache-master"
    "custom-progress-bar"
    "formsite"
    "multibanco-e-ou-payshop-by-lusopay"
    "breaking-news-wp"
    "bbp-members-only"
    "relink"
    "popup-to-share"
    "push-notification-mobile-and-web-app"
    "hr-management-lite"
    "forum-wordpress-fr"
    "cm-footnotes"
    "ultimate-post-slider"
    "utopia-cron"
    "thanh-toan-qrcode"
    "automatic-plugins"
    "rp-news-ticker"
    "pronamic-domain-mapping"
    "travelmap"
    "block-specific-spam-woo-orders"
    "zstore-manager-basic"
    "the-events-calendar-outlook-import-fix"
    "wp-no-bot-question"
    "date-today-nepali"
    "video-playlist-for-youtube"
    "bp-attachments"
    "quform-mailchimp"
    "data8-validation-for-contact-form-7"
    "visual-form-builder-magic"
    "pinterest-site-verification"
    "wptelegram-comments"
    "wishlist-for-woocommerce"
    "video-conferencing-with-bbb"
    "export-custom-pages"
    "mb-youtube-videos"
    "toolbox-for-asgaros-forum"
    "wc-gateway-greeninvoice"
    "dehkadeh-fonts"
    "ydn-download"
    "woocommerce-multiple-addresses"
    "blocks-for-eventbrite"
    "academy-starter-templates"
    "get-latest-tweets"
    "template-for-custom-post-types"
    "css-js-booster"
    "buddypress-humanity"
    "awsom-drop-down-archive"
    "code-highlighter"
    "mapnavigator"
    "advanced-disable-parent-menu-link"
    "contasimple"
    "infinite-scroll-and-load-more-ajax-pagination"
    "livetv-bundle"
    "domain-theme"
    "cta-button-styler"
    "image-archives"
    "gutena-kit"
    "nanosupport"
    "weather-widget-esotanc-weather"
    "nowpayments-for-woocommerce"
    "php-version"
    "wpa-woocommerce-product-gallery-lite"
    "custom-currency-symbol-for-woocommerce"
    "integration-cds"
    "scriblio"
    "media-folder"
    "one-tap-google-sign-in"
    "related-posts-by-category-widget"
    "fade-in-fade-out-post-title"
    "lazy-load-background-images-for-elementor"
    "octolize-shipping-cost-on-product-page"
    "nhsblocks"
    "editor-custom-color-palette"
    "companion-revision-manager"
    "wenderhost-subpages-widget"
    "iphone-control-panel"
    "back-to-top-pro"
    "simple-copy-post"
    "videos-on-admin-dashboard"
    "wemanage-app-worker"
    "advanced-faq-manager"
    "wpc-smart-messages"
    "image-sitemap"
    "wp-syntax-integration"
    "vietqr"
    "meet-your-commenters"
    "hover-image-button"
    "woo-dp-internetmarke"
    "totalsurvey"
    "zoho-subscriptions"
    "wpspeed"
    "search-replace-wpcode"
    "cestina-pro-wordpress"
    "seo-friendly-images-for-wp"
    "show-useragent"
    "mdc-youtube-downloader"
    "comment-mail"
    "email-test"
    "amministrazione-aperta"
    "bot-for-telegram-on-woocommerce"
    "the-permalinker"
    "flickr-tag-cloud-widget"
    "link-to-telegram"
    "simple-xml-sitemap"
    "proxy-real-ip"
    "google-highlight"
    "acf-enhanced-message-field"
    "a-random-number"
    "secsign"
    "simple-select-all-text-box"
    "drag-to-share"
    "steady-wp"
    "catalyst-excerpts-plus"
    "mailpoet-gravity-forms-add-on"
    "csv-to-sorttable"
    "meta-box-facetwp-integrator"
    "time-clock"
    "wp-compress-html"
    "fastdee"
    "dintero-checkout-for-woocommerce"
    "webo-facto-connector"
    "leartes-try-exchange-rates"
    "eucookielaw"
)

# Define user agents with weights
declare -A USER_AGENTS
USER_AGENTS=(
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"]=5
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"]=7
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"]=6
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36 Edg/91.0.864.54"]=5
    ["Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 OPR/77.0.4054.277"]=3
    ["Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (iPad; CPU OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Vivaldi/4.0"]=1
    ["Mozilla/5.0 (Android 11; Mobile; rv:68.0) Gecko/68.0 Firefox/88.0"]=1
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"]=15
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/534.36"]=12
)

OPENED_PLUGINS_FILE="${WORDPRESS_WORKDIR}/opened_plugins.txt"
CLOSED_PLUGINS_FILE="${WORDPRESS_WORKDIR}/closed_plugins.txt"
LAST_VERSION_FILE="${WORDPRESS_WORKDIR}/last_versions.txt"
PARALLEL_JOBS=1

DOWNLOAD_ALL_PLUGINS='n'
LIST_ONLY='n'
ALL_PLUGINS_FILE="${WORDPRESS_WORKDIR}/wp-plugin-svn-list.txt"

DELAY_DOWNLOADS='n'
DELAY_DURATION=5

FORCE_UPDATE='n'
CACHE_ONLY='n'

mkdir -p "$WORDPRESS_WORKDIR" "$MIRROR_DIR" "$LOGS_DIR"
rm -f "$OPENED_PLUGINS_FILE"
touch "$OPENED_PLUGINS_FILE"
DEBUG_MODE=0

while getopts "p:dalD:t:fc" opt; do
    case ${opt} in
        p ) PARALLEL_JOBS=$OPTARG ;;
        d ) DEBUG_MODE=1 ;;
        a ) DOWNLOAD_ALL_PLUGINS='y' ;;
        l ) LIST_ONLY='y' ;;
        D ) DELAY_DOWNLOADS=$OPTARG ;;
        t ) DELAY_DURATION=$OPTARG ;;
        f ) FORCE_UPDATE='y' ;;
        c ) CACHE_ONLY='y' ;;    # New option for cache-only
        \? ) echo "Usage: $0 [-p PARALLEL_JOBS] [-d] [-a] [-l] [-D DELAY_DOWNLOADS] [-t DELAY_DURATION] [-f] [-c]" 1>&2; exit 1 ;;
    esac
done

debug_log() {
    if [ "$DEBUG_MODE" -eq 1 ]; then
        echo "[DEBUG] $1" >&2
    fi
}

get_random_user_agent() {
    echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
}

get_latest_version_and_download_link() {
    local plugin=$1
    debug_log "Checking latest version and download link for $plugin"
    
    local api_url="https://api.wordpress.org/plugins/info/1.0/${plugin}.json"
    local user_agent=$(get_random_user_agent)
    local api_response=$(curl -s -H "User-Agent: $user_agent" "$api_url")
    
    if echo "$api_response" | jq -e '.error' >/dev/null; then
        local error_message=$(echo "$api_response" | jq -r '.error')
        if [ "$error_message" = "closed" ]; then
            echo "closed"
            return 2
        else
        echo "Error: $error_message for plugin $plugin" >&2
        return 1
        fi
    fi
    
    local version=$(echo "$api_response" | jq -r '.version // empty')
    local download_link=$(echo "$api_response" | jq -r '.download_link // empty')
    
    if [ -n "$version" ] && [ -n "$download_link" ]; then
        echo "$version $download_link"
        return 0
    else
        echo "Error: Cannot fetch version or download link for $plugin" >&2
        return 1
    fi
}

download_plugin() {
    local plugin=$1
    local version=$2
    local api_download_link=$3
    local output_file="${MIRROR_DIR}/${plugin}.${version}.zip"
    local header_file="${LOGS_DIR}/${plugin}.${version}.headers"
    local constructed_download_link="${DOWNLOAD_BASE_URL}/${plugin}.${version}.zip"
    local download_link

    if [ "$DEBUG_MODE" -eq 1 ]; then
        debug_log "API-provided download link for $plugin: $api_download_link"
        debug_log "Constructed download link for $plugin: $constructed_download_link"
    fi

    if [ "$DOWNLOAD_LINK_API" == 'y' ] && [ -n "$api_download_link" ]; then
        download_link="$api_download_link"
        debug_log "Using API-provided download link for $plugin: $download_link"
    else
        download_link="$constructed_download_link"
        debug_log "Using constructed download link for $plugin: $download_link"
    fi

    debug_log "Downloading $plugin version $version through Cloudflare Worker"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)
    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o /dev/null "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    else
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o "$output_file" "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    fi

    if [ $? -eq 0 ]; then
        if [ "$CACHE_ONLY" == 'y' ]; then
            debug_log "Plugin $plugin version $version cached successfully."
            return 0
        fi

        local file_size=$(stat -c%s "$output_file")
        if [ "$file_size" -lt 1000 ]; then
            echo "Error: Downloaded file for $plugin is too small (${file_size} bytes). Possible download issue." >&2
            return 1
        fi

        local source=$(grep -i "X-Source:" "$header_file" | cut -d' ' -f2 | tr -d '\r')
        if [ "$source" == "R2" ]; then
            debug_log "Successfully downloaded $plugin version $version from R2 storage"
        elif [ "$source" == "WordPress" ]; then
            debug_log "Successfully downloaded $plugin version $version from WordPress"
            debug_log "R2 bucket saving for plugin zip occurred"
        else
            debug_log "Skipped download for $plugin $version zip (already exists locally)"
        fi

        return 0
    else
        echo "Error: Failed to download $plugin version $version" >&2
        return 1
    fi
}

save_plugin_info() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.json"

    debug_log "Saving plugin json metadata for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying metadata download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    if [ "$CACHE_ONLY" == 'y' ]; then
        # When in cache-only mode, output to /dev/null
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin metadata for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache json metadata for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            if [ "$source" = "R2" ]; then
                debug_log "json metadata for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "json metadata for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin json occurred"
            else
                debug_log "json metadata for $plugin version $version saved (json metadata file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save json metadata for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

fetch_and_save_checksums() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.checksums.json"

    debug_log "Fetching and saving checksums for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying checksums download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    debug_log "Sending request to Worker for checksums: CF_WORKER_URL?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"

    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin checksums for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache checksums for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        debug_log "Received response with status code: $status_code"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            debug_log "Response source: $source"
            if [ "$source" = "R2" ]; then
                debug_log "Checksums for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "Checksums for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin checksums occurred"
            else
                debug_log "Checksums for $plugin version $version saved (checksums file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save checksums for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

process_plugin() {
    local plugin=$1
    plugin=$(echo "$plugin" | sed 's/^\/\|\/$//g')

    # Check if the plugin is already known to be closed
    if grep -q "^$plugin$" "$CLOSED_PLUGINS_FILE" 2>/dev/null; then
        echo "Plugin $plugin is known to be closed. Skipping."
        return 0
    fi

    echo "Processing plugin: $plugin"

    VERSION_AND_LINK=$(get_latest_version_and_download_link "$plugin")
    local version_check_status=$?
    
    if [ $version_check_status -eq 1 ]; then
        echo "Skipping $plugin due to version fetch error."
        return 1
    elif [ $version_check_status -eq 2 ]; then
        echo "Plugin $plugin is closed. Skipping download and processing."
        echo "$plugin" >> "$CLOSED_PLUGINS_FILE"
        if save_plugin_info "$plugin" "closed"; then
            debug_log "Successfully saved json metadata for closed plugin $plugin."
        else
            debug_log "Failed to save json metadata for closed plugin $plugin."
        fi
        return 0
    fi
    
    LATEST_VERSION=$(echo "$VERSION_AND_LINK" | cut -d' ' -f1)
    API_DOWNLOAD_LINK=$(echo "$VERSION_AND_LINK" | cut -d' ' -f2-)

    debug_log "Latest version for $plugin: $LATEST_VERSION"
    debug_log "API download link for $plugin: $API_DOWNLOAD_LINK"

    STORED_VERSION=$(grep "^$plugin" "$LAST_VERSION_FILE" | awk '{print $2}')
    debug_log "Stored version for $plugin: $STORED_VERSION"

    if [ "$CACHE_ONLY" != 'y' ] && [ "$LATEST_VERSION" == "$STORED_VERSION" ] && [ -f "${MIRROR_DIR}/${plugin}.${LATEST_VERSION}.zip" ]; then
        echo "$plugin is up-to-date and exists in mirror directory. Skipping download..."
    else
        start_time=$(date +%s.%N)

        if download_plugin "$plugin" "$LATEST_VERSION" "$API_DOWNLOAD_LINK"; then
            if [ "$CACHE_ONLY" != 'y' ]; then
                sed -i "/^$plugin/d" "$LAST_VERSION_FILE"
                echo "$plugin $LATEST_VERSION" >> "$LAST_VERSION_FILE"
            fi
            echo "Successfully processed $plugin."
        else
            echo "Error: Failed to process $plugin." >&2
        fi

        end_time=$(date +%s.%N)
        duration=$(echo "$end_time - $start_time" | bc)
        printf "Time taken for %s: %.4f seconds\n" "$plugin" "$duration"
    fi

    if save_plugin_info "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully saved json metadata for $plugin."
    else
        debug_log "Failed to save json metadata for $plugin."
    fi

    if fetch_and_save_checksums "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully fetched and saved checksums for $plugin."
    else
        debug_log "Failed to fetch and save checksums for $plugin."
    fi

    if [ $version_check_status -eq 0 ]; then
        echo "$plugin" >> "$OPENED_PLUGINS_FILE"
    fi
}

populate_all_plugins() {
    if [ ! -f "$ALL_PLUGINS_FILE" ] || [ "$LIST_ONLY" == 'y' ]; then
        echo "Fetching list of all WordPress plugins..."
        svn list https://plugins.svn.wordpress.org/ | sed 's/\/$//g' > "$ALL_PLUGINS_FILE"
        plugin_count=$(wc -l < "$ALL_PLUGINS_FILE")
        echo "Plugin list (${plugin_count}) saved to $ALL_PLUGINS_FILE"
    fi
    
    if [ "$LIST_ONLY" == 'n' ]; then
        ALL_PLUGINS=()
        while IFS= read -r line; do
            ALL_PLUGINS+=("$line")
        done < "$ALL_PLUGINS_FILE"
        echo "Loaded ${#ALL_PLUGINS[@]} plugins."
    fi
}

if [ "$LIST_ONLY" == 'y' ]; then
    populate_all_plugins
    echo "Plugin list created. Exiting without downloading."
    exit 0
fi

if [ "$DOWNLOAD_ALL_PLUGINS" == 'y' ]; then
    populate_all_plugins
    COMBINED_PLUGINS=("${ALL_PLUGINS[@]}")
else
    if [ ! -d "$PLUGIN_DIR" ]; then
        echo "Warning: Plugin directory $PLUGIN_DIR does not exist or is invalid."
        PLUGIN_LIST=()
    else
        PLUGIN_LIST=($(ls -d "$PLUGIN_DIR"/*/ 2>/dev/null | xargs -n 1 basename))

        if [ ${#PLUGIN_LIST[@]} -eq 0 ]; then
            echo "No plugins found in $PLUGIN_DIR."
        fi
    fi

    COMBINED_PLUGINS=(${PLUGIN_LIST[@]} ${ADDITIONAL_PLUGINS[@]})
    COMBINED_PLUGINS=($(echo "${COMBINED_PLUGINS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
fi

if [ ${#COMBINED_PLUGINS[@]} -eq 0 ]; then
    echo "No plugins to download. Exiting."
    exit 0
fi

mkdir -p "$MIRROR_DIR"
touch "$LAST_VERSION_FILE"

if [ "$PARALLEL_JOBS" -gt 1 ]; then
    echo "Running in parallel with $PARALLEL_JOBS jobs..."
    echo "Variables before export:"

    # WordPress-related directories
    echo "WORDPRESS_WORKDIR: $WORDPRESS_WORKDIR"
    echo "PLUGIN_DIR: $PLUGIN_DIR"
    echo "MIRROR_DIR: $MIRROR_DIR"
    echo "LOGS_DIR: $LOGS_DIR"

    # Cloudflare Worker related URLs
    echo "CF_WORKER_URL: $CF_WORKER_URL"

    # Flags and options
    echo "DOWNLOAD_LINK_API: $DOWNLOAD_LINK_API"
    echo "DOWNLOAD_ALL_PLUGINS: $DOWNLOAD_ALL_PLUGINS"
    echo "LIST_ONLY: $LIST_ONLY"
    echo "DELAY_DOWNLOADS: $DELAY_DOWNLOADS"
    echo "DELAY_DURATION: $DELAY_DURATION"
    echo "FORCE_UPDATE: $FORCE_UPDATE"
    echo "CACHE_ONLY: $CACHE_ONLY"

    # File paths
    echo "OPENED_PLUGINS_FILE: $OPENED_PLUGINS_FILE"
    echo "CLOSED_PLUGINS_FILE: $CLOSED_PLUGINS_FILE"
    echo "LAST_VERSION_FILE: $LAST_VERSION_FILE"
    echo "ALL_PLUGINS_FILE: $ALL_PLUGINS_FILE"

    # Parallel job configuration
    echo "PARALLEL_JOBS: $PARALLEL_JOBS"

    # User Agents mapping
    echo "USER_AGENTS: ${USER_AGENTS[@]}"

    # Additional plugins to be processed
    # echo "ADDITIONAL_PLUGINS: ${ADDITIONAL_PLUGINS[@]}"

    # Plugin List (loaded from directory or ALL_PLUGINS_FILE)
    #echo "PLUGIN_LIST: ${PLUGIN_LIST[@]}"
    #echo "COMBINED_PLUGINS: ${COMBINED_PLUGINS[@]}"

    # First, export all variables including USER_AGENTS
    export DOWNLOAD_BASE_URL MIRROR_DIR LAST_VERSION_FILE DEBUG_MODE DOWNLOAD_LINK_API LOGS_DIR ALL_PLUGINS_FILE DOWNLOAD_ALL_PLUGINS LIST_ONLY CF_WORKER_URL DELAY_DOWNLOADS DELAY_DURATION FORCE_UPDATE CACHE_ONLY WORDPRESS_WORKDIR PLUGIN_DIR PARALLEL_JOBS OPENED_PLUGINS_FILE CLOSED_PLUGINS_FILE USER_AGENTS

    # Then, export the functions
    export -f process_plugin get_latest_version_and_download_link download_plugin debug_log populate_all_plugins save_plugin_info get_random_user_agent fetch_and_save_checksums
    printf "%s\n" "${COMBINED_PLUGINS[@]}" | xargs -P $PARALLEL_JOBS -I {} bash -c 'process_plugin "$@"' _ {}
else
    for plugin in "${COMBINED_PLUGINS[@]}"; do
        process_plugin "$plugin"
    done
fi

if [ -f "$CLOSED_PLUGINS_FILE" ]; then
    echo
    echo "Closed Plugin List:"
    cat "$CLOSED_PLUGINS_FILE" | sort | uniq || true
    echo
    echo "Total closed plugins: $(wc -l < "$CLOSED_PLUGINS_FILE")"
    echo
else
    echo
    echo "No closed plugins found."
    echo
fi
echo "Plugin download process completed."
