#!/bin/bash

# Base directory (script location)
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Configurable directories
WORDPRESS_WORKDIR="${WORDPRESS_WORKDIR:-$BASE_DIR/wordpress-plugins}"
PLUGIN_DIR="${PLUGIN_DIR:-$BASE_DIR/wp-content/plugins}"
MIRROR_DIR="${MIRROR_DIR:-$BASE_DIR/mirror}"
LOGS_DIR="${LOGS_DIR:-$BASE_DIR/plugin-logs}"

# Check for CF_WORKER_URL environment variable
if [ -z "$CF_WORKER_URL" ]; then
    echo "Error: CF_WORKER_URL environment variable is not set." >&2
    exit 1
fi

DOWNLOAD_BASE_URL="https://downloads.wordpress.org/plugin"

# Other variables
DOWNLOAD_LINK_API='y'

ADDITIONAL_PLUGINS=(
    "tour-operator-special-offers"
    "edd-metrics"
    "skysa-text-ticker-app"
    "total-social-counter"
    "eventupon-calendar"
    "publish-and-redirect-to-add-new-post"
    "css-live"
    "amazing-team-member-carousel"
    "delete-post-with-attachments"
    "netgiro-payment-gateway-for-woocommerce"
    "simple-auto-linker-seo-tool"
    "soldpress"
    "my-geo-posts-free"
    "wp-social-stream"
    "catconvert"
    "woo-cardknox-gateway"
    "swiss-qr-bill"
    "affiliates-ninja-forms"
    "page-manager-for-elementor"
    "easy-tiktok-feed"
    "wp-block-referrer-spam"
    "kount-fraud-prevention"
    "emi-loan-calculator"
    "swiper-for-visual-composer"
    "shoparize"
    "wp-themes-plugins-stats"
    "lucky-wheel-exit-intent-wheelio-popup-for-spin-a-sale-by-wheely-sales"
    "primary-categories"
    "post-category"
    "userplace-member-subscription-restriction-payments"
    "in3-marketing"
    "smoove-abandoned-cart-trigger-for-woocommerce"
    "dynamic-404-page"
    "customize-wpadmin"
    "internet-connection-status"
    "hyvor-talk"
    "hey-notify"
    "cbxtakeatour"
    "woocommerce-nigeria-states"
    "flowplayer-playlist"
    "ai-image-alt-text-generator-for-wp"
    "force-image-download"
    "snoobi-bv-analytics-tracking"
    "simple-related-posts-in-page"
    "sdac-post-slideshows"
    "debug-bar-super-globals"
    "wp-qr-code-login"
    "idna"
    "default-quantity-for-woocommerce"
    "nyasro-nepali-date-converter"
    "find-function"
    "offcanvas-menu"
    "auto-youtube-summarize"
    "pv-anlagen"
    "buy-widget-coinbase"
    "tiny-yardage-calculator"
    "restaurant-logic"
    "modalcontact"
    "wp-places"
    "search-top-bar"
    "current-year-shortcodes"
    "shopp-customer-register"
    "author-categories"
    "comments-engine-ai"
    "woocommerce-payu-india-payment-gateway"
    "ajax-manufactory"
    "iwr-tooltip"
    "addurilka"
    "post-from-frontend"
    "support-ticket-system-for-woocommerce"
    "todo-list-block"
    "sb-breadcrumbs"
    "engagebay-gravity-forms"
    "atariage-dashboard-feed"
    "easy-fontawesome"
    "brilliant-easy-exclude-posts"
    "guten-free-options"
    "indexnow-pro-seznam-cz"
    "wordpress-events"
    "sim-clickable-links"
    "sublime-custom-js-editor"
    "beagle-security-wp-security-advanced-penetration-testing"
    "jinx-the-javascript-includer"
    "beer-directory"
    "daily-attendance"
    "monitor-seo-essentials"
    "mandatory-excerpt"
    "simple-ads-posting"
    "somewhere-search-box"
    "woocommerce-alter-inventory"
    "docupress"
    "smntcs-admin-maintenance"
    "ff-tab-widget"
    "buddypress-qtranslate"
    "wp-tbl"
    "acf-advanced-search"
    "chatsupport"
    "gwebpro-contact-form-7-mailchimp-extension"
    "link-shield"
    "just-writing-statistics"
    "bingmaps"
    "custom-post-type-widget-blocks"
    "wp-custom-rest-api-generator"
    "dimme-calendar"
    "latest-posts-with-thumbnails-and-ads"
    "xeno"
    "kings-caption-hover"
    "dsgvo"
    "wp-conditional-themes"
    "qr-code-adv"
    "custom-field-data-icons"
    "compact-admin"
    "sister-pages"
    "bp-expand-activity"
    "pc-ktai-content-selecter"
    "fse-classic"
    "stylish-scrolling-title"
    "course"
    "pripre"
    "postcode-shipping-module"
    "wordpress-e-commerce-history"
    "language-translate"
    "wc-empty-cart"
    "customize-dokan-dashboard-endpoints"
    "skip-confirmation-on"
    "teg-twitter-api"
    "user-status-shortcode"
    "wpseo-pinterest-rich-pins-for-woocommerce"
    "dragdropr"
    "site-counter"
    "matomo-analytics"
    "goo-page-level-ads"
    "block-control"
    "dashboard-widgets-network-removal"
    "ez-overlay"
    "dynamic-sidebar-menu"
    "yd-zoomify"
    "random-post-thumbnail"
    "ip2location-widget"
    "add-fediverse-icons-to-jetpack"
    "pop-menus-for-wp-admin"
    "clearblue-due-date-calculator"
    "login-popup-modal"
    "brightslider"
    "wp-listings-pro"
    "review-slider-for-woocommerce"
    "vr-calendar"
    "sso-vbulletin"
    "advanced-custom-fields-shortcode-field"
    "tfo-graphviz"
    "postgallery"
    "rsvpify-oembed"
    "configpress"
    "multi-gallery"
    "grand-job"
    "object-data-sync-for-salesforce"
    "bing-ads-uet"
    "wp-customizer"
    "attachment-download-on-gravity-form-submission"
    "wp-gfycat"
    "smart-quotes"
    "public-woo-api"
    "wp-email-debug"
    "author-signature"
    "pryc-wp-404-to-homepage-301-redirect"
    "color-scheme-field-for-advanced-custom-fields-pro"
    "enable-site-ping-wpmu"
    "intensedebate-importer"
    "appscenic"
    "hybrid-gallery"
    "meetinghub"
    "wp-pricing-table"
    "advanced-wpperformance"
    "change-proceed-to-checkout-text"
    "exclusive-hover-effects"
    "railway-pnr-status"
    "themeshark-elementor"
    "pressfore-preloaders"
    "iframecatcher"
    "livehelp-chat"
    "soccer-engine-lite"
    "wp-white-label-login"
    "restrictedarea"
    "wp-liveshopping-caroussel"
    "easy-softonic-contact-form"
    "iframe-block"
    "simple-accessible-spoilers"
    "the-bootstrap-themes-companion"
    "block-a-saurus"
    "debug-elementor"
    "custom-wp-css-js"
    "cj-custom-content"
    "mcatfilter"
    "fx-email-log"
    "wp-simple-plugin-upload"
    "list-one-category-of-posts"
    "all-in-one-background"
    "rajoshik-post-feature-image-from-url"
    "seo-smart-link-targets"
    "snowy"
    "slider-seo"
    "responsive-tab-widget"
    "client-power-tools"
    "multi-step-forms-free-for-elementor"
    "wp-awesome-scrollbar"
    "wp-partner"
    "allow-only-1-product-in-cart-for-woocommerce"
    "infinite-notification"
    "wp-bootstrap-widgets"
    "greymatter-importer"
    "contact-form-7-to-post"
    "aus-telegram-channel"
    "fluidcoins-wc-payment-gateway"
    "datetime-fields-for-gravityforms"
    "details-summary-block"
    "robotswhiz"
    "wpyaa-alipay-wechat-for-woocommerce"
    "content-insights"
    "autofields"
    "twitter-sp2"
    "mediaflow"
    "wetter"
    "iframe-less-reloaded"
    "leadlovers-forms"
    "biblegateway-links-shortcode"
    "better-404-redirect-to-homepage"
    "mini-termin"
    "rdp-linkedin-login"
    "ts-comfort-database"
    "chip-get-image"
    "tumblr-follow-button"
    "stylecss-load-last-version"
    "wp-bootstrap-carousel-by-it-pixelz"
    "woo-katalog"
    "dj-accessibility"
    "remove-pingback-trackback-comments"
    "simple-mastodon-verification"
    "creative-tag-cloud"
    "site-private"
    "al3x-file-manager"
    "wp-tracy"
    "mb-comment-meta"
    "wp-basic-seo-meta"
    "wash-care-symbols-for-woocommerce"
    "property-hive-rental-yield-calculator"
    "postcasa"
    "nc-ajax-cart-for-woocommerce"
    "image-hotspot"
    "relevanssi-dashboard"
    "icollect"
    "wp-shieldon"
    "toll-free-sms"
    "floating-tiktok-button"
    "russian-number-comments"
    "ip2phrase-widget"
    "add-campo-rut-cf7"
    "better-messages-wcfm-integration"
    "designer"
    "word-count-and-social-shares"
    "tave-integration-using-gravity-forms"
    "enweby-variation-swatches-for-woocommerce"
    "space-lover"
    "etsy-mini"
    "acymailing-custom-headers"
    "file-download"
    "salesfeed"
    "give-it-away-now"
    "wp-branding-bar"
    "multisite-tos"
    "wysylajtaniej-pl"
    "doofinder"
    "advanced-pdf-generator"
    "wdes-responsive-popup"
    "team-showcase-awesome"
    "acymailing-table-of-contents-generator"
    "wp-phanfare"
    "gdy-modular-content"
    "retreat-booking-guru-connect"
    "captcha-eu"
    "litprotocol-wp-lit-gated"
    "octillion-widget-for-btc-e-pamm-account"
    "blank"
    "lh-multipart-email"
    "my-ibook"
    "wiseagentleadform"
    "frontend-product-editor"
    "horizontal-line-styles"
    "ecolet"
    "140follow"
    "wpavatar"
    "custom-product-type-for-woocommerce"
    "wp-our-team"
    "wp-htaccess-optimize"
    "geodatasource-country-region-dropdown"
    "promotore-simple-analytics"
    "fake-whos-online-widget"
    "cc-syntax-highlight"
    "travelmanager-buchungssoftware"
    "factureaza-me"
    "restrict-user-registration"
    "woo-groups-discount"
    "price-changer-for-woocommerce"
    "acf-image-size-select"
    "control-horas"
    "gg-widget-title-link"
    "rich-snippets-enhancement-with-rank-math"
    "web-rank-get"
    "materializer"
    "override-post-title-with-first-content-heading"
    "weebly-importer"
    "auto-numbering-post"
    "aec-kiosque"
    "nextgen-icin-onizleme"
    "parcel2go-shipping"
    "authentication-and-xmlrpc-log-writer"
    "hizzle-recaptcha"
    "openpgp-form-encryption"
    "wp-quizr"
    "download-media-file"
    "woo-torob"
    "add-to-google-calendar-contact-form-7"
    "avectra-netforum-single-sign-on"
    "force-post-title"
    "popliup"
    "wp-imsizer"
    "nubuilder-forte"
    "audienceplayer"
    "archive-disabler"
    "transizroutes"
    "givexpert"
    "duplicate-it"
    "call-now-and-chat-buttons"
    "wpc-admin-columns"
    "woo-subcategory-thumb"
    "give-double-the-donation"
    "wp-upload-rename"
    "e-commerce-payment-gateway-kevin"
    "limited-category-lists-widget"
    "wp-thumbs"
    "portfolio-for-elementor"
    "force-update-check-for-plugins-and-themes"
    "page-load-ajax"
    "productive-style"
    "ghost-tags"
    "wp-dev-dashboard"
    "ht-pay-jp-for-kintone"
    "portfolio-block"
    "two-factor-sms"
    "comment-probation"
    "product-badges"
    "no-user-enumeration"
    "wp-glossary-hover"
    "rebrand-amelia"
    "wp-blog-news"
    "footer-header-js-css"
    "on-demand-revalidation"
    "auto-update-themes"
    "custom-taxonomy-columns"
    "latest-posts-by-author-with-content"
    "category-views-by-webline"
    "meta-theme-colour"
    "vrpconnector"
    "stonehenge-em-mollie"
    "catalyst-connect"
    "bible-search"
    "magic-popups-customizable-and-lightweight"
    "smart-dofollow"
    "aarons-no-ssl-flash-upload"
    "birth-chart-compatibility"
    "wp-steem"
    "bluex-for-woocommerce"
    "connect-to-apple-music"
    "sf-bootstrap-menu"
    "tinymce-chinese-convert"
    "status-bar-color-changer-for-android"
    "fiverr-official-search-box"
    "service-booking-manager"
    "samandehi-logo-manager"
    "wp-orphanage"
    "custom-new-user-notification"
    "smaily-for-contact-form-7"
    "data-collection-form"
    "star-snippets-rich-snippet-vote"
    "animated-al-list"
    "aac-scoring"
    "connatix-video-embed"
    "wp-bbcode"
    "image-caption-links"
    "mybb-last-topics"
    "smtp-sendinblue"
    "amwal-checkout"
    "formidable-customizations"
    "woo-product-reorder"
    "wp-vn-oembed"
    "skip-to-timestamp"
    "uss-upyun"
    "responsive-google-effect-portfolio-grid"
    "post-like-dislike"
    "tinywebdb-api"
    "add-twitter-anywhere"
    "editorial-rating"
    "ts-webfonts-for-standard-plan"
    "popup-maker-buddypress-integration"
    "acf-simple-tooltip"
    "indicadores-economicos-para-colombia"
    "wens-ie-css3-support"
    "rest-api-blocks"
    "wikipedia-widget"
    "automate-hub-free-by-sperse-io"
    "discourage-search-engines-dashboard-notification"
    "timelinejs"
    "wigzo"
    "trustmeter-for-google"
    "user-count"
    "wp-algolia"
    "bbpress-direct-quotes"
    "multiple-excerpt-lengths"
    "make-disable-admin-email-verification-prompt"
    "rename-users"
    "header-cleanup"
    "gr-order-category-post"
    "custom-pagination-permalinks"
    "wordpress-copyscape-plugin"
    "fx-gallery-widget"
    "update-notifications"
    "toolstruthsocial"
    "feedback-modal-for-website"
    "archives-by-category-and-date"
    "coupon-grab"
    "bp-group-categoriestypes"
    "simple-zippyshare-embed"
    "brozzme-cookie-notification"
    "zen"
    "gutenberg-block-for-slick-slider"
    "simple-pricing-tables-vc-extension"
    "jcwp-left-right-key-navigation"
    "tr-register-only"
    "wpml-json-api"
    "polygon-recent-comments-with-avatar"
    "disable-autocomplete"
    "expire-posts"
    "bible-verses"
    "matches"
    "jetpack-twitter-via"
    "hcv4-payment-gateway"
    "main-entrance"
    "bitpace-crypto-payment-gateway"
    "easy-voice-mail"
    "force-https-srcset"
    "opay-payment-gateway-for-woocommerce"
    "auto-future-date"
    "genesis-staff-bio-grid"
    "deregister-contact-form-7"
    "leader"
    "ajax-widget-area"
    "altcoins-donation-widget"
    "ngd-custom-add-to-cart-label"
    "admin-thumbnails"
    "wp-license-manager"
    "post-typographer"
    "fin-accounting-for-woocommerce"
    "lazy-load-adsense"
    "carrot-quest"
    "houdini"
    "foloosi-for-woocommerce"
    "be-popia-compliant"
    "embed-google-drive"
    "campaign-monitor-for-formcraft"
    "alert-me"
    "limit-widgets"
    "boekuwzending-for-woocommerce"
    "wooreports-free"
    "plugin-update-blocker"
    "add-on-cf7-for-notion"
    "bulk-mail-send"
    "widget-display-options"
    "mcninja-post-styles"
    "cryptocurrency-converter"
    "all-woocommerce-export"
    "optimizer-for-faster-websites"
    "external-thumbnail"
    "zenlatest"
    "application-passwords-enable"
    "wp-issuu-viewer"
    "probelix-blowball"
    "elex-australia-post-shipping"
    "account-manager-woocommerce"
    "coub"
    "category-based-archives"
    "bizcalendar-web"
    "seo-slugs-dutch"
    "share-on-social"
    "photoshelter-importer"
    "simple-login-screen-customizer"
    "pkt1-centro-de-envios"
    "nw-description-for-custom-post-types"
    "crypto-donations"
    "collapsible-categories-in-the-dashboard"
    "sticky-chat-button"
    "cornify-for-wordpress"
    "waves"
    "earnware-connect"
    "spweather"
    "scrolltotop"
    "buying-buddy-idx-crm"
    "easy-custom-oceanwp-shop"
    "tieexpire-automated-post-expiry"
    "debug-media"
    "advance-widget-pack"
    "daknetcorp-auto-tag-category"
    "tainacan-url-metadata-type"
    "baw-google-author"
    "pdf-invoicing-for-woocommerce"
    "survey"
    "easy-pull-quotes"
    "resize-tag-cloud"
    "lawpress"
    "wp-slide-categorywise"
    "sharedaddy-more-control"
    "nacc-wordpress-plugin"
    "cookie-wise"
    "mw-taxonomy"
    "embed-videogjirafa"
    "wp-property-feed-to-houzez-theme-connector"
    "mi-tienda-mercadolibre"
    "joomla-to-wordpress-migrated-users-authentication-plugin"
    "processingjs-for-wp"
    "wsb-brands"
    "zoom-image-shortcode"
    "moderate-selected-posts"
    "google-plus-share-and-plusone-button"
    "mailpoet-wysija-mandrill-spam-and-bounce-cleaner"
    "ns-custom-add-to-cart-button-for-woocoomerce"
    "dicode-icons-pack"
    "wc-pagaleve"
    "combidesk-snelstart"
    "wc-moldovaagroindbank"
    "girafi"
    "disable-check-comment-flood"
    "sudoku-game"
    "aam-animate-scroll"
    "animate-blocks"
    "cultbooking-booking-engine"
    "inbox"
    "bns-twitter-follow-button"
    "buddypress-user-registration-auto-group"
    "block-disposable-email-addresses"
    "easify-server-woocommerce"
    "os-our-team"
    "simple-text-slider"
    "cart66-cloud-members"
    "story-lines"
    "schema-scalpel"
    "beautiful-salat"
    "simple-twitter-follow-me-button"
    "admin-login-monitor"
    "buddypress-monster-widget"
    "mdt-google-news"
    "standard-accordion"
    "shortcodely"
    "icono-pure-css-icons"
    "playbuzz-oembed"
    "subscriber-website"
    "multimanager-wp"
    "cb-disable-comment-url"
    "cw-google-analytics-datenschutz"
    "mediarss-with-post-thumbnail"
    "wp-float-related-posts"
    "simple-soc-widget"
    "wp-ticketbai"
    "wp-redirects-contact-form-7"
    "improving-search-form-accessibility"
    "light-admin-theme"
    "wp-data-logger"
    "mysearchtermspresenter"
    "webshare"
    "themes-artist-demo-importer"
    "gosign-logo-slider-block"
    "cforms-plugin"
    "smithers-login"
    "parallelize-downloads"
    "wp-maintenance-page"
    "salesmartly-chat"
    "woo-verotelcardbilling-flexpay"
    "uikit-wp-integrator"
    "buythis-shortcode"
    "mcping"
    "realplaces-xml-csv-property-listings-import"
    "wp-spider-cache"
    "debugger"
    "banner-alerts"
    "easy-bulk-subpage-creator"
    "wschat-live-chat"
    "zeemaps"
    "themebrowser"
    "no-captcha-spam-block"
    "tw-switch-mobile-domain"
    "wpsite-limit-posts"
    "alpha-pay-wechat-pay-alipay-for-woocommerce"
    "cache-control-by-cacholong"
    "sportspress-for-volleyball"
    "admin-login-url-change"
    "snsimple-email"
    "rivercraft"
    "lightweight-contact-form"
    "warcraft-news"
    "per-post-language"
    "subcategory-list-widget"
    "weather-widget-wp"
    "geoswitch"
    "bbp-private-forum-visibility"
    "gt-geo-targeting"
    "private-uploads"
    "enviopack-argentina"
    "wc-share-cart-url"
    "frontpage-title-meta-description"
    "remove-admin-bar-menu"
    "appointment-form-manager"
    "wp-cartoon"
    "lunar-sell-photos-online"
    "wp-comment-humility"
    "solat-times"
    "tablebooker"
    "aucor-url-sanitizer"
    "kolakube-email-forms"
    "toms-product-video"
    "shopwarden"
    "wp-avim"
    "multi-google-analytics"
    "ssl-for-logged-in-users"
    "alpha-cache"
    "wp-faqs"
    "neon-product-designer-for-woocommerce"
    "bybrick-accordion"
    "ni-woo-sales-commission"
    "woo-cost-of-shipping"
    "cf7-sendinblue-opt-in-checkbox"
    "image-blur"
    "orbisius-quick-nav"
    "cal-com"
    "agency-toolkit"
    "quickstart"
    "loi-hamon"
    "seamlesschex-echeck-payments"
    "new-user-dashboard"
    "serp-rank"
    "css-file-selector"
    "code-revisions"
    "salesworks-media-sitemap"
    "bible-link-multilingual"
    "snippets-block"
    "tismy-user-profile-upload"
    "all-in-one-slider"
    "drag-and-sort"
    "sticky-header-on-scroll"
    "course-migration-for-learndash"
    "version-assets"
    "privacy-consent-assistant"
    "wordpress-remove-version"
    "grassblade-xapi-lifterlms"
    "gamipress-conditional-emails-recipients"
    "e-junkie"
    "dx-unanswered-comments"
    "more-mails-for-cf7"
    "freesoul-switch-theme"
    "admin-bar-theme-switcher"
    "comment-moderation-role"
    "archiver"
    "theme-to-browser-t2b-control"
    "ah-prism-syntax-highlighter"
    "cb-contact-form"
    "getrss"
    "genesis-style-shortcodes"
    "team-up"
    "login-xchange"
    "custom-exit-to-dashboard"
    "woocommerce-custom-order-data"
    "chaiport-payment"
    "custom-dashboard-messages"
    "auto-rename-media-on-upload"
    "varnish-wp"
    "wp-russian-quicktags"
    "appointment-buddy-online-appointment-booking-by-accrete"
    "album-cover-finder"
    "scode-by-mojwp"
    "geo-my-wp-current-location-forms"
    "ro-slugs"
    "course-wizard-for-sensei"
    "notification-bbpress"
    "add-user-meta"
    "tecslider"
    "customize-inline-editing"
    "wp-fixed-social-profile-icons"
    "depay-payments"
    "private-feed-keys"
    "plum-code-box"
    "external-database-access-using-wp-user"
    "raek-real-time-identification"
    "mensy"
    "docs2site"
    "avalicious"
    "gp-google-login"
    "wp-cache-block"
    "bbpress-last-topics"
    "wp-bottr-connect"
    "several-images-slider-widget"
    "wpgenealogy"
    "add-to-cart-ajax-for-hello-elementor"
    "manage-tinymce-editor"
    "user-role-sidebar-menu"
    "ns-custom-message-cart"
    "magazine-edition-control"
    "estadisticas-web"
    "falang-for-wpbakery-lite"
    "mylco"
    "automatic-email-testing-for-wp"
    "custom-right-click-menu"
    "lsx-testimonials"
    "jwd-teams"
    "themepacific-review-lite"
    "age-verification-screen-for-woocommerce"
    "wp-squish"
    "capturly-optimize-your-website"
    "jellyfish-invaders"
    "wpcj-testimonials"
    "kanban-shortcodes"
    "micromint"
    "1on1-url-redirects"
    "inn-ao-detector"
    "dj-elementor-frontend"
    "e-commerce-by-salescart"
    "playstation-network-status"
    "cf7-editor-button"
    "show-all-products-shortcode-for-woocommerce"
    "innozilla-image-gallery-8"
    "skyword-publishing-api"
    "bp-group-hierarchy-propagate"
    "almar"
    "r3df-beaver-builder-tinymce-advanced-icon-fix"
    "serverless-radio"
    "tl-auto-feature-image"
    "page-swapper"
    "disk-space-usage"
    "ai-scribe-the-chatgpt-powered-seo-content-creation-wizard"
    "vanilla-adaptive-maps"
    "turbolinks"
    "descriptive-menu-widget"
    "posts-in-category-menu"
    "exchange-addon-custom-loop"
    "sara-covid"
    "woo-layout-editor"
    "background-animation-blocks"
    "make-clickable"
    "komparu-comparison-module"
    "wp-less-compiler"
    "open-web-analytics"
    "wp-featured-screenshot"
    "aivoov-text-to-speech"
    "no-slug-conflicts-with-trash"
    "tag-selector"
    "trustedshops-consent-manager"
    "pagenamed-menu-classes"
    "storefront-gridder"
    "pr-gateway-connect"
    "minecraft-workbench-tooltips"
    "wc-adyen-payment-gateway"
    "woocommerce-products-by-custom-tax"
    "wp-rss-fetcher-shortcode"
    "wpc-smart-product-collections"
    "k-timelinda"
    "associate-attachment"
    "nextgen-to-wiziapp"
    "youtube-dj"
    "mobble-shortcodes"
    "document-engine"
    "nocturne-dark-mode"
    "daily-logo"
    "genesis-subtitles"
    "gs-coach"
    "content-restrictor-for-divi"
    "global-smtp"
    "cg-scroll-to-top"
    "a-z-indexing-startup"
    "juniper-companion"
    "multilingual-demo-data-creator"
    "info-blocks-for-woocommerce"
    "genesis-promotion-box"
    "thumbar"
    "rp-post-nav"
    "yay-images"
    "bb-delete-cache"
    "form-data-collector"
    "acf-price"
    "1003-mortgage-application"
    "theme-companion"
    "gmagick"
    "404-redirector"
    "the-marquee-block"
    "newebpay-payment"
    "favorite-links-widget"
    "wc-backorder-split"
    "web-testimonials"
    "editor-wysiwyg-background-color"
    "strings-sanitizer"
    "wpcode-content-ratio"
    "paj-featured-image-owl-carousel"
    "post-category-gallery"
    "fundiin"
    "wp-tweetbutton-plus"
    "back-to-top-button"
    "posts-in-posts"
    "woo-cashback"
    "custom-colors"
    "comment-redlist"
    "bitcoin-payments-by-chainside-net-for-woocommerce"
    "upper-menu-for-twenty-eleven"
    "uploads"
    "shared-whiteboard"
    "content-sort"
    "wpsimpletools-maintenance-mode"
    "post-template-select"
    "tallykit"
    "wc-qazeek-payment-gateway"
    "aploblocks"
    "subtitle"
    "ca-quick-view"
    "edd-list-file-names"
    "wp-foliolio"
    "like-dislike-voting"
    "acf-pro-sync"
    "jsfiddle-shortcode"
    "daniels-dropdowns"
    "wp-kakao-plusfriend"
    "quote-tweet"
    "wp-company-info"
    "easy-testimonial-blocks"
    "stepform"
    "bcs-bertline-book-importer"
    "ems-payments-for-woocommerce"
    "accordion-panel-for-category-and-products"
    "wp-ucanhide"
    "bitvolo-trustless-crypto-payment-gateway"
    "simple-slideout-menu"
    "brozzme-product-navigation"
    "unlimited"
    "disable-widgets"
    "thumbnail-link-for-woo"
    "social-share-block"
    "custom-sender-for-email-before-download"
    "custom-admin-login"
    "post-slider-free"
    "show-parent-comment"
    "staff-list-widget-proper-url"
    "frontier-query"
    "amberlink"
    "developer-code-editor"
    "czater"
    "sorting-woocommerce-lite-edition"
    "vadi-faq"
    "search-with-google"
    "stop-sopa"
    "date-translator"
    "subpages-expand"
    "quick-and-easy-post-creation-for-acf-relationship-fields"
    "multilpe-social-media"
    "wp-whoosh"
    "dynamic-text-field-for-contact-form-7"
    "email-customizer-and-designer-for-woocommerce"
    "wizshop"
    "glotpress-notify"
    "shortcode-datastore"
    "forms-by-made-it"
    "free-downloads-edd"
    "scrollkit"
    "edd-simple-after-payment-redirect"
    "awocoupon"
    "category-for-pages"
    "autologin-on-register-for-buddyboss"
    "locations-and-areas"
    "reachmail-subscription-forms"
    "spanish-quote-of-the-day-frase-del-dia"
    "contact-form-7-wysiwyg-field"
    "wp-admin-block"
    "involve-me"
    "otp-authenticator"
    "about-our-services"
    "whmcs-price"
    "edd-midtrans-gateway"
    "woo-instant-bitcoin"
    "search-index-page-content"
    "horizontal-post-slider"
    "yahoo-weather-plugin"
    "kanpress"
    "taxonomy-thumbnail-widget"
    "leads-5050-visitor-insights"
    "storenvy"
    "snack-ads-txt"
    "custom-business-locations"
    "wp-custom-emails"
    "simple-tournament-brackets"
    "wc-restrict-payment-methods"
    "klaro-consent-manager"
    "wp-monero-miner-pro"
    "extended-random-number-generator"
    "layers"
    "image-captcha-for-gravity-forms"
    "team-showcase-ultimate"
    "gmaptip"
    "cs-remove-version-number-from-css-js"
    "pwd-theme-switcher"
    "cp-phone-link"
    "tsp-disable-auto-save"
    "cc-flickr-widget"
    "animated-number-counter"
    "live-support-desk"
    "wapuu-dashboard-pet"
    "wp-viewstl"
    "message-popup-for-contact-form-7"
    "news-element"
    "smyles-wp-job-manager-field-editor-import"
    "wp-extra-template-tags"
    "order-barcode-for-woocommerce"
    "woocommerce-products-without-featured-images"
    "mini-course-generator"
    "posts-by-taxonomy-widget"
    "aicomments"
    "simple-seo-by-falbar"
    "wp-easy-toggles"
    "plugin-activation-tracker"
    "quran-gateway"
    "smugbuy"
    "starcross-mlb-standings-widget"
    "gdreseller"
    "wp-hypermd"
    "igreen-alexa-site-rank"
    "fathom-analytics-conversions"
    "feed-delay"
    "quform-wpml"
    "display-pages-shortcode"
    "mycred-memberpress"
    "mini-wp-gdpr"
    "block-profile-card"
    "custom-post-popup"
    "category-expander"
    "rotating-links-widget"
    "aspire-smart-faq"
    "easy-url-rewrite"
    "post-draft-preview"
    "compact-view-mode"
    "inquiry-form-to-posts-or-pages"
    "movingboxes-wp"
    "http-requests-manager"
    "range-slider-addon-for-gravity-forms"
    "lcp-ajax-pagination"
    "wp-localscroll"
    "optin-comment-notifications"
    "the-media-widget"
    "wp-world-weather-online"
    "customizer-theme-resizer"
    "wp-yui-menu"
    "scriptrr-google-profile"
    "hide-product-image-for-woocommerce"
    "admin-featured-image"
    "shorturl"
    "nino-contact-form"
    "videos"
    "ultimate-custom-scrollbar"
    "comment-ip-trace"
    "falang-q-importer"
    "order-post"
    "wc-ready2order-integration"
    "eyoung"
    "camptix-payfast-gateway"
    "ehive-objects-image-grid"
    "geo-targeted-posts"
    "acf-permalinks"
    "kalendarium-cz"
    "pdf-importer-for-gravity"
    "hookywoo"
    "gtranslate-dynamic-media"
    "events-manager-pro-extended"
    "bp-whats-hot"
    "speech-balloon-maker"
    "appointlet"
    "category-excluder-from-theme-customizer"
    "helpfulcrowd-product-reviews"
    "wp-vcard"
    "userdeck"
    "wp-sudoku-plus"
    "recipe-snippets"
    "assign-categories"
    "admin-bar-tools"
    "wp-e-commerce-change-currency-symbols"
    "advanced-custom-types-for-divi"
    "smartsorting"
    "acf-flexible-columns"
    "roomlio-group-chat"
    "wparty"
    "simple-multi-inventory-for-woocommerce"
    "motion"
    "contact-form-to-wp-posts"
    "mzz-stat"
    "highlight-text"
    "abeta-punchout"
    "advanced-posts-per-page"
    "360-product-viewer-for-woocommerce"
    "thepointofsalecom-widget-shortcode"
    "wdv-mailchimp-ajax"
    "cackle-last-comments-widget"
    "ajax-load-more-post"
    "import-products-to-vk"
    "adobe-dtm"
    "nc-wishlist-for-woocommerce"
    "chimpbridge"
    "ultimate-wp-rest"
    "lifterlms-wpmktgengine-extension"
    "jquery-color-picker"
    "juiz-user-custom"
    "vinubis-video-editor"
    "wordstamp"
    "appful-app"
    "terminal-africa"
    "captcha-garb"
    "wc-paygol"
    "contactum"
    "tooltipster"
    "wp-webclap"
    "coinmall"
    "helppress"
    "notifications"
    "chatbot-botnation"
    "show-pending-comments-count"
    "legalweb-cloud"
    "adminbar-manager"
    "wpturbo"
    "woo-new"
    "gosign-header-image-block"
    "ricerca-smart-search"
    "codup-woocommerce-dynamic-pricing-table-view"
    "npr-story-api"
    "octavius-rocks"
    "content-update-notification"
    "worldnet-payments-gateway-for-woocommerce"
    "text-changer-for-welcart"
    "post-internal-link-removal"
    "easy-digital-downloads-putler-connector"
    "mypress"
    "compact-mce"
    "admin-select-box-to-select2"
    "document-library"
    "wp-job-portal-by-jane"
    "comments-manager-for-windows-phone7"
    "goo-pie-chart"
    "ucat-next-story"
    "affiliatewp-affiliate-banners-widget"
    "conditional-payment-gateways-for-woocommerce"
    "google-for-page"
    "fast-speed-index"
    "scratch-and-win"
    "three-object-viewer"
    "trulia"
    "info-nutricional"
    "custom-category-image"
    "customizr-addons"
    "mobile-friendly-twenty-ten"
    "boxful-fulfillment"
    "default-gravatar-sans"
    "qubotchat"
    "clickdesigns"
    "advanced-custom-fields-tag-it"
    "login-to-read-more"
    "wp-author-report-free"
    "wp-redis-cache"
    "osmaps"
    "guahan-flickr-widget"
    "live-stream-church"
    "revisioner"
    "qq-avatar"
    "web-push-notifications-lite"
    "wpdevdesign-oxygen-essentials"
    "wooplatnica"
    "woo-qr-shipping-address-pip"
    "affiliates-ready-light"
    "sgt-carousel-gallery"
    "screen-reader-text-format"
    "insert-math"
    "noor-starter-templates"
    "bma-lite-appointment-booking-and-scheduling"
    "multi-image-widget"
    "acf-field-selector-field"
    "moosend-landing-pages"
    "joke-of-the-day-advanced"
    "nepirity-analytics"
    "smodin-rewriter"
    "wc-sofinco-3xcb"
    "geo-targetly-geo-content"
    "wp-arabic-virtual-keyboard"
    "unicode-character-keyboard"
    "ltl-freight-quotes-freightquote-edition"
    "nuconomy-insights"
    "connector-civicrm-mcrestface"
    "designious-library-setup"
    "post-pay-counter-wp-slimstat-visits"
    "website-thumbshots"
    "yes-youtube-essential-statistics-widget"
    "custom-google-fonts"
    "frndzk-easy-mobile-theme-switcher-with-theme-pack"
    "buddypress-profile-visitors"
    "prepare-new-version"
    "redfox-companion"
    "image-custom-class"
    "woograbexpress"
    "fp-linkedin-company-profile"
    "rsvpmaker-volunteer-roles"
    "vampire-character"
    "sell-from-blog"
    "wp-post-frontend"
    "comment-tweets"
    "caspers-leave-notice"
    "soccer-live-scores"
    "dans-gsheets"
    "bamboo-backups"
    "simple-multisite-login-log"
    "countdown-woocommerce-sale"
    "wc-uala-bis"
    "roadmap"
    "fanimani-pl"
    "wp-podcasts-manager"
    "goodbye-syntax-highlighter"
    "magic-login-mail"
    "json-importer"
    "product-icon-badge"
    "nextcellent-gallery-media-addon"
    "iamport-for-easy-digital-downloads"
    "wc-payler"
    "wp-unit-converter"
    "tl-bulk-comment-delete"
    "insecure-content-warning"
    "jquery-roundabout-for-posts"
    "geo-mark"
    "langtolang-dictionary"
    "wp-hashed-ids"
    "bp-repost-activity"
    "add-a-yoast-breadcrumb"
    "opentracker-analytics"
    "flexible-faqs"
    "per-form-confirmation-pages-for-givewp"
    "simple-stripe"
    "translation-detector"
    "display-category-posts-via-shortcode-lite"
    "compositepost"
    "ehive-object-tags-widget"
    "easy-elementor-addons"
    "meta-seo-benignsource"
    "fade"
    "ip2currency-converter"
    "cryptocurrency-prijsvergelijking-widget"
    "border-image"
    "gpano"
    "twl-easy-call"
    "ar-php"
    "plugin-builder"
    "bulk-page-stub-creator"
    "wplocalplus-lite"
    "mblog"
    "tock-widget"
    "show-posts-fade-inout-fix"
    "cg-dynamic-sidebar"
    "site-mode"
    "restore-permanently-delete-post-or-page-data"
    "edd-digital-badge"
    "admin-user-message"
    "ip-geolocation"
    "shownotes"
    "wp-ssl"
    "html-parser"
    "bruce-clay-seo"
    "also-in-this-series"
    "wp-moon-phase-widget"
    "cat-post-type"
    "seo-content-randomizer"
    "readability"
    "badgeos-group-management-add-on"
    "taxonomy-toolbox"
    "media-filter"
    "5usujian-bottom-pop"
    "english-premier-league-table"
    "years-since"
    "last-comments-without-links"
    "buzzfeed-style-personality-quizes"
    "rotate-soundcloud-player"
    "all-round-order"
    "conditional-custom-fields-shortcode"
    "categories-autolink"
    "media-select-bulk-downloader"
    "avify"
    "apache-password-protect"
    "cf7-honeypot-plus"
    "addy-autocomplete-woocommerce"
    "kuicklist"
    "superadmin-helper"
    "pyplugger-for-pyscript"
    "wp-gravatar-https"
    "author-list"
    "badges"
    "mobile-contact-line"
    "simple-debug"
    "rss-chimp"
    "wp-wpcat-json-rest"
    "freecontactformdotcom"
    "media-metadata-list"
    "opcache-scripts"
    "certifica-wp"
    "nopeamedia"
    "gallerya"
    "popcustoms-integration-for-woocommerce"
    "custom-style"
    "my-related-posts"
    "cache-buddy"
    "buooy-sticky-header"
    "el-gallery"
    "buzz-this"
    "live-dashboard"
    "wp-comment-validation"
    "footer-on-homepage"
    "ps-user-login-count"
    "orbisius-bbpress-enhancer"
    "easy-plugin-stats"
    "ixml"
    "gambling-affiliate-link-checker"
    "tpay-ge-woocommerce"
    "tl-sms"
    "bd-mobile-payments-gateway"
    "valentines-day"
    "impactpubs"
    "search-fixer"
    "easy-digital-downloads-empty-cart"
    "truncate-comments"
    "subscriptiondna"
    "advanced-rank-checker"
    "prestashop-user-compatibility"
    "smart-syntax"
    "advanced-sticky-posts"
    "maintenance-work"
    "gtin-schema-for-woo"
    "wd3k-go-top-down"
    "calenso-booking"
    "phpinclusion"
    "pilopress"
    "login-form-anywhere"
    "tweetiepie"
    "trusted-only"
    "field-helper-for-gravity-forms"
    "business-card-block"
    "protect-wordpress-form-hacker"
    "kd-google-plus-badge"
    "ilogic-accessibility"
    "uv-b-connector-for-woocommerce"
    "wp-uighur-fonts"
    "pubexchange"
    "newscred-publishing"
    "woo-oscommerce-sync"
    "rss-feeds-disabler"
    "styler-for-contact-form-7"
    "payl8r-finance-gateway-for-woocommerce"
    "admin-menus-accessibility"
    "abwpwoo"
    "wp-admin-bar-effect"
    "zen-dash"
    "wi-games-widget"
    "free-product-sample"
    "wpmk-pdf-generator"
    "oneclick-whatsapp-hello"
    "woo-price-quote-inquiry"
    "rescue-children-banner"
    "hide-any-page"
    "virtualspirits-chatbot"
    "force-featured-image"
    "sara-ajax-search"
    "z-credit-webcheckout-for-woo"
    "cache-purge-helper"
    "bbpress-activity-tracker"
    "kintpv-connect"
    "latest-post-shortcode-slider-extension"
    "liveeditor"
    "tripplan"
    "check-search-engine-visibility-on-migration"
    "ehive-access"
    "fx-random-image"
    "sapo-videos-o-embed"
    "fraudlabs-pro-for-easy-digital-downloads"
    "wp-squirrelmail"
    "regiondetect"
    "eewee-pinterest"
    "wp-food-manager"
    "simple-currency-exchange-converter"
    "wc-cryptum-checkout"
    "all-embed-addons-for-elementor"
    "you-save-x-for-woocommerce"
    "bp-profile-home-widgets"
    "friendlycase"
    "hide-option-for-ozhs-admin-drop-down-menu"
    "episode-vii-countdown-widget"
    "if-shortcode"
    "likely"
    "wp-emphasis"
    "pdf-for-wpforms"
    "wp-remove-category-prefix"
    "add-to-cart-button-for-woocommerce"
    "heimu"
    "smart-currency-converter"
    "block-ie6"
    "sibs-woocommerce"
    "modern-admin-comments"
    "u-loader"
    "easiest-contact-form"
    "makelaarsservice"
    "x-cart-integration"
    "wc-checkout-terms-popup"
    "select-category-to-post"
    "hide-old-posts"
    "force-jpeg-quality"
    "trust-txt"
    "wp-nofollow-more-links"
    "gw-visual-composer-hover-box"
    "activitysparks"
    "ghtime-plugin"
    "wp-lozad"
    "genesis-subpage-sidebar"
    "wp-sort-posts"
    "bbp-gdpr"
    "abusech-httpbl-check"
    "post2mail"
    "sark-migs"
    "9mail-wp-email-templates-designer"
    "pfand-deposit-for-woocommerce-products"
    "docs-auto-tags"
    "lana-security"
    "wp-faucet-direct"
    "recent-posts-by-tags"
    "super-simple-post-page-restricor"
    "app-display-page"
    "wc-epayco-payment-gateway"
    "winorder-wppizza-connector"
    "infusionsoft-one-click-upsell"
    "xml-documents"
    "alergenos-alimentarios-indianwebs"
    "bverse-convert"
    "all-in-one-seo-agency-toolbox"
    "sewn-in-xml-sitemap"
    "top-position-google-finance"
    "share-on-vkontakte"
    "wp-masonry-infinite-scroll"
    "comma-diacritics"
    "woocommerce-live-stock-quantity"
    "valitorpay-payment-gateway-for-woocommerce"
    "swiftninjapro-youtube-embed"
    "multifile-upload"
    "easy-stripe"
    "advance-custom-import-and-export"
    "knit-pay-pro"
    "cluevo-lms-extension-oembed-modules"
    "media-item-url"
    "lqthemes-companion"
    "auto-subscribe-users"
    "galleriapress"
    "save-and-continue-link-recovery-for-gravity-forms"
    "gifty"
    "background-block"
    "flying-twitter-birds"
    "kudos"
    "wp-compiler"
    "pay-with-ath-movil-woocommerce-gateway"
    "tabs-maker"
    "metro-share"
    "webphone"
    "advanced-custom-data"
    "custom-post-type-template-redirect"
    "wpftp"
    "edd-wepay-oauth2"
    "read-next-fly-box"
    "xml-rss-parser-widget"
    "embad"
    "gf-ach-field"
    "paytomorrow"
    "tifinagh"
    "accessibility-access-keys"
    "edit-parent-comment-id"
    "wareki"
    "custom-xml-feed"
    "integrate-elementor-form-with-mailster"
    "sliced-invoices-formidable-forms"
    "wp-codeshield"
    "analytify-contact-form-7-gooogle-analytics-tracking"
    "stylish-notification-popup"
    "debug-bar-localization"
    "myworks-sync-for-xero"
    "advanced-timeline-block"
    "zibal-payment-gateway-for-gravity-forms"
    "featured-posts-pro"
    "wpsolr-free"
    "card-block"
    "woo-prune-orders"
    "chart-expert"
    "wordpress-twitter-follow-button"
    "feed-changer"
    "terms-dictionary"
    "unipay-payment-gateway-for-woocommerce"
    "woo-oca-app"
    "responsive-owl-carousel"
    "css-me"
    "autolink"
    "selectel-storage-upload"
    "curriculum-vitae-by-osflake"
    "dl-leadback"
    "vanilla-bean-icon-setter"
    "apc-cache-purge"
    "random-post-list"
    "plx-portal-connector"
    "elo-rating-shortcode"
    "aj-easy-calculator"
    "player-leaderboard"
    "ableplayer"
    "supreme-addons-for-beaver-builder-lite"
    "ehive-objects-tag-cloud-widget"
    "netfirms-pretty-permalinks"
    "seo-beginner-auto-post"
    "lh-buddypress-export-xprofile-data"
    "integrate-clientify"
    "custom-sidebar-links"
    "products-purchase-price-for-woocommerce"
    "grad-aparat-rss"
    "td-ticket-system"
    "endora"
    "child-themes-helper"
    "fripixel-crypto-quotation"
    "mrkv-monobank-extended"
    "gamipress-transfers-notes"
    "top-5-educational-flash-interactive-games-for-schools"
    "wp-analytics-tag-manager"
    "shared-house"
    "woo-custom-empty-price"
    "post-automator"
    "affiliates-recaptcha"
    "themeszone-woocommerce-ajax-quantity"
    "gfdesigns"
    "disable-000webhost-branding"
    "custom-profile-avatar"
    "testimonial-awesome"
    "fontiran-font-changer"
    "guan-image-notes"
    "prodalet"
    "gumpress"
    "get-flickr-thumbnails"
    "payitmonthly-for-woocommerce"
    "hide-custom-fields"
    "convertedin-ai-automation-for-woocommerce"
    "menu-item-types-button"
    "woo-sonypayment"
    "wp-butler"
    "cf7-smtp"
    "easy-optimizer"
    "voting-for-a-photo"
    "op-addon-for-wp-courseware"
    "ltl-freight-quotes-unishippers-edition"
    "sdac-related-content"
    "pingchecker"
    "videowarrior"
    "safe-editor"
    "beapi-maintenance-mode"
    "seo-rank-analyser"
    "summy"
    "bulk-page-maker"
    "gravity-forms-rss"
    "nivo-slider-widget"
    "remove-wp-version-number"
    "display-links-by-category"
    "current-promotions-display"
    "extra-details-on-shop-page"
    "oembed-in-library"
    "custom-admin-menu"
    "recentcomments"
    "reorder-my-sites"
    "wpcasa-gravity-forms"
    "merge-menus"
    "wpc-free-gift-coupons"
    "ajax-login-by-wph"
    "acymailing-universal-filter"
    "wpuf-login-redirect"
    "scd-smart-currency-detector-variant-for-dokan"
    "easy-custom-js-and-css"
    "advanced-comment-validation"
    "monthly-horoscopes"
    "tabs-block"
    "shipdeo-woo"
    "as-nice-scroll"
    "make-it-srcset"
    "wp-conditional-post-restrictions"
    "polylang-auto-translation"
    "twitter-extented"
    "rd-dashboard-pdf"
    "wpt-demo-importer"
    "wp-sacloud-webaccel"
    "ty-gia-gia-vang"
    "dynamic-links"
    "rexcrawler"
    "get-menu-joomla"
    "wp-zombaio"
    "wp-notice-blocker"
    "pmzez-page-loader"
    "wp-sphinx-search"
    "wp-likejs"
    "system-information"
    "og-meta"
    "another-twitter-extension"
    "feedburner-right-now-stats"
    "scd-smart-currency-detector-variant-for-wcmp"
    "szechenyi-2020-logo"
    "linked-variation"
    "grid-accordion"
    "section-subnav"
    "reposter-reloaded"
    "payza-payments"
    "celebrity-polls"
    "hipaatizer"
    "bp-profile-activity-wall"
    "tao-quotes"
    "kunze-law"
    "image-sizes-controller"
    "seraphinite-discount-for-woocommerce"
    "wp-cloudflare-cache"
    "seo-rets"
    "pure-css-circle-progress-bar"
    "pym-shortcode"
    "block-domain-email-addresses-for-contact-form-7"
    "illustrations"
    "cnet-api-search"
    "tiny-link"
    "aw-woocommerce-pos"
    "forms-3rdparty-dynamic-fields"
    "saoshyant-slider"
    "webcupon"
    "slovenska-posta-epodaci-harok"
    "kento-ajax-contact-form"
    "smntcs-woocommerce-free-gift"
    "simplybook"
    "simple-google-font-adder"
    "ilc-folding"
    "easy-replace"
    "wp-tips"
    "gallery-showcase"
    "scan-external-links"
    "tinymce-paste-in-plain-text-by-default"
    "cf7-cost-calculator"
    "konvertiraj-me"
    "twitter-card-generator"
    "wp-zillow"
    "givebutter"
    "stock-triggers-for-woocommerce"
    "sf-archiver"
    "mygdex-for-woocommerce"
    "we-gallery"
    "small-package-quotes-unishippers-edition"
    "reenable-shortlink-item-in-admin-toolbar"
    "on-screen-keyboard"
    "store-migration-products-orders-import-export-with-excel"
    "woo-add-custom-text"
    "import-vk"
    "wppedia"
    "mtmo-b-v"
    "taxnalogy-aliexpress-product-importer"
    "posts-shared-counter-for-social-website"
    "eventos"
    "shipfunk-woocommerce-shipping"
    "jquery-googleslides"
    "easy-admin-theme"
    "modify-profile-fields-dashboard-menu-buttons"
    "accordion-archive-widget"
    "admin-command-palette"
    "show-pages-list"
    "licenses-manager-for-woocommerce"
    "el-club-de-la-noticia"
    "wp-cookie-consent"
    "inline-js-block-for-gutenberg"
    "wp-logs"
    "shipping-envia-colvanes-woo"
    "custom-tags-lists"
    "bluecounterwidget"
    "quandoo-restaurant-reservations"
    "magnetis-call-tracking"
    "cookies-manager"
    "misterchat"
    "usermaven"
    "tainacan-extra-view-modes"
    "mixtape-machine"
    "gmap-venturit"
    "custom-post-text"
    "rename-plugins-folder"
    "woo-most-viewed-products"
    "sedox-performance-vehicle-catalogue"
    "available-payment-options-plugin"
    "yourplugins-wc-conditional-cart-notices"
    "fast-translate"
)

# Define user agents with weights
declare -A USER_AGENTS
USER_AGENTS=(
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"]=5
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"]=7
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"]=6
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36 Edg/91.0.864.54"]=5
    ["Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 OPR/77.0.4054.277"]=3
    ["Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (iPad; CPU OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Vivaldi/4.0"]=1
    ["Mozilla/5.0 (Android 11; Mobile; rv:68.0) Gecko/68.0 Firefox/88.0"]=1
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"]=15
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/534.36"]=12
)

OPENED_PLUGINS_FILE="${WORDPRESS_WORKDIR}/opened_plugins.txt"
CLOSED_PLUGINS_FILE="${WORDPRESS_WORKDIR}/closed_plugins.txt"
LAST_VERSION_FILE="${WORDPRESS_WORKDIR}/last_versions.txt"
PARALLEL_JOBS=1

DOWNLOAD_ALL_PLUGINS='n'
LIST_ONLY='n'
ALL_PLUGINS_FILE="${WORDPRESS_WORKDIR}/wp-plugin-svn-list.txt"
START_COUNT=0
END_COUNT=0

DELAY_DOWNLOADS='n'
DELAY_DURATION=5

FORCE_UPDATE='n'
CACHE_ONLY='n'

mkdir -p "$WORDPRESS_WORKDIR" "$MIRROR_DIR" "$LOGS_DIR"
rm -f "$OPENED_PLUGINS_FILE"
touch "$OPENED_PLUGINS_FILE"
DEBUG_MODE=0

while getopts "p:dalD:t:fcs:e:" opt; do
    case ${opt} in
        p ) PARALLEL_JOBS=$OPTARG ;;
        d ) DEBUG_MODE=1 ;;
        a ) DOWNLOAD_ALL_PLUGINS='y' ;;
        l ) LIST_ONLY='y' ;;
        D ) DELAY_DOWNLOADS=$OPTARG ;;
        t ) DELAY_DURATION=$OPTARG ;;
        f ) FORCE_UPDATE='y' ;;
        c ) CACHE_ONLY='y' ;;
        s ) START_COUNT=$OPTARG ;;
        e ) END_COUNT=$OPTARG ;;
        \? ) echo "Usage: $0 [-p PARALLEL_JOBS] [-d] [-a] [-l] [-D DELAY_DOWNLOADS] [-t DELAY_DURATION] [-f] [-c] [-s START_COUNT] [-e END_COUNT]" 1>&2; exit 1 ;;
    esac
done

debug_log() {
    if [ "$DEBUG_MODE" -eq 1 ]; then
        echo "[DEBUG] $1" >&2
    fi
}

get_random_user_agent() {
    echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
}

get_latest_version_and_download_link() {
    local plugin=$1
    debug_log "Checking latest version and download link for $plugin"
    
    local api_url="https://api.wordpress.org/plugins/info/1.0/${plugin}.json"
    local user_agent=$(get_random_user_agent)
    local api_response=$(curl -s -H "User-Agent: $user_agent" "$api_url")
    
    if echo "$api_response" | jq -e '.error' >/dev/null; then
        local error_message=$(echo "$api_response" | jq -r '.error')
        if [ "$error_message" = "closed" ]; then
            echo "closed"
            return 2
        else
        echo "Error: $error_message for plugin $plugin" >&2
        return 1
        fi
    fi
    
    local version=$(echo "$api_response" | jq -r '.version // empty')
    local download_link=$(echo "$api_response" | jq -r '.download_link // empty')
    
    if [ -n "$version" ] && [ -n "$download_link" ]; then
        echo "$version $download_link"
        return 0
    else
        echo "Error: Cannot fetch version or download link for $plugin" >&2
        return 1
    fi
}

download_plugin() {
    local plugin=$1
    local version=$2
    local api_download_link=$3
    local output_file="${MIRROR_DIR}/${plugin}.${version}.zip"
    local header_file="${LOGS_DIR}/${plugin}.${version}.headers"
    local constructed_download_link="${DOWNLOAD_BASE_URL}/${plugin}.${version}.zip"
    local download_link

    if [ "$DEBUG_MODE" -eq 1 ]; then
        debug_log "API-provided download link for $plugin: $api_download_link"
        debug_log "Constructed download link for $plugin: $constructed_download_link"
    fi

    if [ "$DOWNLOAD_LINK_API" == 'y' ] && [ -n "$api_download_link" ]; then
        download_link="$api_download_link"
        debug_log "Using API-provided download link for $plugin: $download_link"
    else
        download_link="$constructed_download_link"
        debug_log "Using constructed download link for $plugin: $download_link"
    fi

    debug_log "Downloading $plugin version $version through Cloudflare Worker"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)
    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o /dev/null "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    else
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o "$output_file" "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    fi

    if [ $? -eq 0 ]; then
        if [ "$CACHE_ONLY" == 'y' ]; then
            debug_log "Plugin $plugin version $version cached successfully."
            return 0
        fi

        local file_size=$(stat -c%s "$output_file")
        if [ "$file_size" -lt 1000 ]; then
            echo "Error: Downloaded file for $plugin is too small (${file_size} bytes). Possible download issue." >&2
            return 1
        fi

        local source=$(grep -i "X-Source:" "$header_file" | cut -d' ' -f2 | tr -d '\r')
        if [ "$source" == "R2" ]; then
            debug_log "Successfully downloaded $plugin version $version from R2 storage"
        elif [ "$source" == "WordPress" ]; then
            debug_log "Successfully downloaded $plugin version $version from WordPress"
            debug_log "R2 bucket saving for plugin zip occurred"
        else
            debug_log "Skipped download for $plugin $version zip (already exists locally)"
        fi

        return 0
    else
        echo "Error: Failed to download $plugin version $version" >&2
        return 1
    fi
}

save_plugin_info() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.json"

    debug_log "Saving plugin json metadata for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying metadata download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    if [ "$CACHE_ONLY" == 'y' ]; then
        # When in cache-only mode, output to /dev/null
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin metadata for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache json metadata for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            if [ "$source" = "R2" ]; then
                debug_log "json metadata for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "json metadata for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin json occurred"
            else
                debug_log "json metadata for $plugin version $version saved (json metadata file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save json metadata for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

fetch_and_save_checksums() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.checksums.json"

    debug_log "Fetching and saving checksums for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying checksums download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    debug_log "Sending request to Worker for checksums: CF_WORKER_URL?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"

    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin checksums for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache checksums for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        debug_log "Received response with status code: $status_code"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            debug_log "Response source: $source"
            if [ "$source" = "R2" ]; then
                debug_log "Checksums for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "Checksums for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin checksums occurred"
            else
                debug_log "Checksums for $plugin version $version saved (checksums file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save checksums for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

process_plugin() {
    local plugin=$1
    plugin=$(echo "$plugin" | sed 's/^\/\|\/$//g')

    # Check if the plugin is already known to be closed
    if grep -q "^$plugin$" "$CLOSED_PLUGINS_FILE" 2>/dev/null; then
        echo "Plugin $plugin is known to be closed. Skipping."
        return 0
    fi

    echo "Processing plugin: $plugin"

    VERSION_AND_LINK=$(get_latest_version_and_download_link "$plugin")
    local version_check_status=$?
    
    if [ $version_check_status -eq 1 ]; then
        echo "Skipping $plugin due to version fetch error."
        return 1
    elif [ $version_check_status -eq 2 ]; then
        echo "Plugin $plugin is closed. Skipping download and processing."
        echo "$plugin" >> "$CLOSED_PLUGINS_FILE"
        if save_plugin_info "$plugin" "closed"; then
            debug_log "Successfully saved json metadata for closed plugin $plugin."
        else
            debug_log "Failed to save json metadata for closed plugin $plugin."
        fi
        return 0
    fi
    
    LATEST_VERSION=$(echo "$VERSION_AND_LINK" | cut -d' ' -f1)
    API_DOWNLOAD_LINK=$(echo "$VERSION_AND_LINK" | cut -d' ' -f2-)

    debug_log "Latest version for $plugin: $LATEST_VERSION"
    debug_log "API download link for $plugin: $API_DOWNLOAD_LINK"

    STORED_VERSION=$(grep "^$plugin" "$LAST_VERSION_FILE" | awk '{print $2}')
    debug_log "Stored version for $plugin: $STORED_VERSION"

    if [ "$CACHE_ONLY" != 'y' ] && [ "$LATEST_VERSION" == "$STORED_VERSION" ] && [ -f "${MIRROR_DIR}/${plugin}.${LATEST_VERSION}.zip" ]; then
        echo "$plugin is up-to-date and exists in mirror directory. Skipping download..."
    else
        start_time=$(date +%s.%N)

        if download_plugin "$plugin" "$LATEST_VERSION" "$API_DOWNLOAD_LINK"; then
            if [ "$CACHE_ONLY" != 'y' ]; then
                sed -i "/^$plugin/d" "$LAST_VERSION_FILE"
                echo "$plugin $LATEST_VERSION" >> "$LAST_VERSION_FILE"
            fi
            echo "Successfully processed $plugin."
        else
            echo "Error: Failed to process $plugin." >&2
        fi

        end_time=$(date +%s.%N)
        duration=$(echo "$end_time - $start_time" | bc)
        printf "Time taken for %s: %.4f seconds\n" "$plugin" "$duration"
    fi

    if save_plugin_info "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully saved json metadata for $plugin."
    else
        debug_log "Failed to save json metadata for $plugin."
    fi

    if fetch_and_save_checksums "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully fetched and saved checksums for $plugin."
    else
        debug_log "Failed to fetch and save checksums for $plugin."
    fi

    if [ $version_check_status -eq 0 ]; then
        echo "$plugin" >> "$OPENED_PLUGINS_FILE"
    fi
}

populate_all_plugins() {
    if [ ! -f "$ALL_PLUGINS_FILE" ] || [ "$LIST_ONLY" == 'y' ]; then
        echo "Fetching list of all WordPress plugins..."
        svn list https://plugins.svn.wordpress.org/ | sed 's/\/$//g' > "$ALL_PLUGINS_FILE"
        plugin_count=$(wc -l < "$ALL_PLUGINS_FILE")
        echo "Plugin list (${plugin_count}) saved to $ALL_PLUGINS_FILE"
    fi
    
    if [ "$LIST_ONLY" == 'n' ]; then
        ALL_PLUGINS=()
        if [ "$DOWNLOAD_ALL_PLUGINS" == 'y' ] && [ $START_COUNT -gt 0 ] && [ $END_COUNT -ge $START_COUNT ]; then
            echo "Processing plugins from line $START_COUNT to $END_COUNT"
            while IFS= read -r line; do
                ALL_PLUGINS+=("$line")
            done < <(sed -n "${START_COUNT},${END_COUNT}p" "$ALL_PLUGINS_FILE")
        else
            while IFS= read -r line; do
                ALL_PLUGINS+=("$line")
            done < "$ALL_PLUGINS_FILE"
        fi
        echo "Loaded ${#ALL_PLUGINS[@]} plugins."
    fi
}

if [ "$LIST_ONLY" == 'y' ]; then
    populate_all_plugins
    echo "Plugin list created. Exiting without downloading."
    exit 0
fi

if [ "$DOWNLOAD_ALL_PLUGINS" == 'y' ]; then
    populate_all_plugins
    COMBINED_PLUGINS=("${ALL_PLUGINS[@]}")
else
    if [ ! -d "$PLUGIN_DIR" ]; then
        echo "Warning: Plugin directory $PLUGIN_DIR does not exist or is invalid."
        PLUGIN_LIST=()
    else
        PLUGIN_LIST=($(ls -d "$PLUGIN_DIR"/*/ 2>/dev/null | xargs -n 1 basename))

        if [ ${#PLUGIN_LIST[@]} -eq 0 ]; then
            echo "No plugins found in $PLUGIN_DIR."
        fi
    fi

    COMBINED_PLUGINS=(${PLUGIN_LIST[@]} ${ADDITIONAL_PLUGINS[@]})
    COMBINED_PLUGINS=($(echo "${COMBINED_PLUGINS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
fi

if [ ${#COMBINED_PLUGINS[@]} -eq 0 ]; then
    echo "No plugins to download. Exiting."
    exit 0
fi

mkdir -p "$MIRROR_DIR"
touch "$LAST_VERSION_FILE"

if [ "$PARALLEL_JOBS" -gt 1 ]; then
    echo "Running in parallel with $PARALLEL_JOBS jobs..."
    echo "Variables before export:"

    # WordPress-related directories
    echo "WORDPRESS_WORKDIR: $WORDPRESS_WORKDIR"
    echo "PLUGIN_DIR: $PLUGIN_DIR"
    echo "MIRROR_DIR: $MIRROR_DIR"
    echo "LOGS_DIR: $LOGS_DIR"

    # Cloudflare Worker related URLs
    echo "CF_WORKER_URL: $CF_WORKER_URL"

    # Flags and options
    echo "DOWNLOAD_LINK_API: $DOWNLOAD_LINK_API"
    echo "DOWNLOAD_ALL_PLUGINS: $DOWNLOAD_ALL_PLUGINS"
    echo "LIST_ONLY: $LIST_ONLY"
    echo "DELAY_DOWNLOADS: $DELAY_DOWNLOADS"
    echo "DELAY_DURATION: $DELAY_DURATION"
    echo "FORCE_UPDATE: $FORCE_UPDATE"
    echo "CACHE_ONLY: $CACHE_ONLY"

    # File paths
    echo "OPENED_PLUGINS_FILE: $OPENED_PLUGINS_FILE"
    echo "CLOSED_PLUGINS_FILE: $CLOSED_PLUGINS_FILE"
    echo "LAST_VERSION_FILE: $LAST_VERSION_FILE"
    echo "ALL_PLUGINS_FILE: $ALL_PLUGINS_FILE"

    # Parallel job configuration
    echo "PARALLEL_JOBS: $PARALLEL_JOBS"

    # User Agents mapping
    echo "USER_AGENTS: ${USER_AGENTS[@]}"

    # Additional plugins to be processed
    # echo "ADDITIONAL_PLUGINS: ${ADDITIONAL_PLUGINS[@]}"

    # Plugin List (loaded from directory or ALL_PLUGINS_FILE)
    #echo "PLUGIN_LIST: ${PLUGIN_LIST[@]}"
    #echo "COMBINED_PLUGINS: ${COMBINED_PLUGINS[@]}"

    # First, export all variables including USER_AGENTS
    export DOWNLOAD_BASE_URL MIRROR_DIR LAST_VERSION_FILE DEBUG_MODE DOWNLOAD_LINK_API LOGS_DIR ALL_PLUGINS_FILE DOWNLOAD_ALL_PLUGINS LIST_ONLY CF_WORKER_URL DELAY_DOWNLOADS DELAY_DURATION FORCE_UPDATE CACHE_ONLY WORDPRESS_WORKDIR PLUGIN_DIR PARALLEL_JOBS OPENED_PLUGINS_FILE CLOSED_PLUGINS_FILE USER_AGENTS

    # Then, export the functions
    export -f process_plugin get_latest_version_and_download_link download_plugin debug_log populate_all_plugins save_plugin_info get_random_user_agent fetch_and_save_checksums
    printf "%s\n" "${COMBINED_PLUGINS[@]}" | xargs -P $PARALLEL_JOBS -I {} bash -c 'process_plugin "$@"' _ {}
else
    for plugin in "${COMBINED_PLUGINS[@]}"; do
        process_plugin "$plugin"
    done
fi

if [ "$DOWNLOAD_ALL_PLUGINS" == 'y' ]; then
    if [ -f "$CLOSED_PLUGINS_FILE" ]; then
        echo
        echo "Closed Plugin List: $CLOSED_PLUGINS_FILE"
        echo "Total closed plugins: $(wc -l < "$CLOSED_PLUGINS_FILE")"
    else
        echo
        echo "No closed plugins found."
    fi
    if [ -f "$OPENED_PLUGINS_FILE" ]; then
        echo
        echo "Opened Plugin List: $OPENED_PLUGINS_FILE"
        echo "Total opened plugins: $(wc -l < "$OPENED_PLUGINS_FILE")"
    else
        echo
        echo "No open plugins found."
    fi
fi
echo "Plugin download process completed."
