#!/bin/bash

# Base directory (script location)
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Configurable directories
WORDPRESS_WORKDIR="${WORDPRESS_WORKDIR:-$BASE_DIR/wordpress-plugins}"
PLUGIN_DIR="${PLUGIN_DIR:-$BASE_DIR/wp-content/plugins}"
MIRROR_DIR="${MIRROR_DIR:-$BASE_DIR/mirror}"
LOGS_DIR="${LOGS_DIR:-$BASE_DIR/plugin-logs}"

# Check for CF_WORKER_URL environment variable
if [ -z "$CF_WORKER_URL" ]; then
    echo "Error: CF_WORKER_URL environment variable is not set." >&2
    exit 1
fi

DOWNLOAD_BASE_URL="https://downloads.wordpress.org/plugin"

# Other variables
DOWNLOAD_LINK_API='y'

ADDITIONAL_PLUGINS=(
    "set-aside"
    "better-user-profile-fields"
    "revinsite"
    "pro-locker"
    "duplicate-pages-and-posts"
    "moneycollect-payment-gateway-for-woocommerce"
    "ultimate-post-thumbnails"
    "mediopay"
    "davids-admin-post-control"
    "mailpoet-bbpress-add-on"
    "ps-hide-price-and-add-to-cart-for-woocommerce"
    "chat-orders-for-woo"
    "get-remote-url-info"
    "eacsimplesmtp"
    "bbpress-update-status"
    "respek-nature"
    "quick-testimonials"
    "theme-grep-by-boldgrid"
    "farm-calculators"
    "nantuki-yify-torrent-adder"
    "bbp-contacts"
    "wp-loginout-link-with-login-popup"
    "beauty-license-verification"
    "simple-featured-image-column"
    "intlwp"
    "disable-adjacent-rel-links"
    "custom-widget-post"
    "product-sync-master-sheet"
    "aramex-optilog-woocommerce"
    "selective-importers"
    "use-helvetica-dangit"
    "image-meta"
    "ultimate-feed-gallery"
    "semalt-seo"
    "utility-pack-for-wp-all-export"
    "spraypay"
    "woo-asaas-multiple-accounts"
    "paybybank"
    "photopress-sideways-gallery"
    "paylabs-payment-gateway"
    "woocommerce-recommendations"
    "wavenami-forms-and-mapping"
    "wc-live-sale-notifications"
    "page-listing-categories"
    "domain-age-checker-tool"
    "membership-with-imis-and-membercms"
    "videozen"
    "ksher-payment"
    "block-feed-and-comments-via-robots-txt"
    "wp-keybase-verification"
    "processing-js-easy"
    "ngg-tinymce-description-editor"
    "piwikcounter"
    "woo-pardakht"
    "toolsfors3"
    "saaspricing"
    "date-price-calendar"
    "menu-description"
    "controller-fields-for-contact-form-7"
    "easy-announcements"
    "simple-classifieds"
    "youtube-like-rating"
    "braintree-donations"
    "my-wp-bxslider"
    "quickupload"
    "theme-bakery"
    "keep-the-score"
    "advanced-htaccess-optimizer-editor"
    "inject-o-matic"
    "custom-image-attributes"
    "inline-markdown"
    "wp-pages-advanced"
    "sx-rss-ticker"
    "wmenu-digital-menu-and-restaurant-ordering"
    "allure-gallery"
    "nautilus-trips"
    "affylite"
    "faq-module-for-divi"
    "wp-flake"
    "versionit"
    "email-author-on-publish"
    "comments-everywhere"
    "editorial-guidelines"
    "generate-user-invoices"
    "app-reviews-lite"
    "msg91-by-vasim-shaikh"
    "real-update"
    "mb-rank-math"
    "dm-pojo-menu-mobile"
    "fcp-lightest-lightbox"
    "charts-blocks"
    "extend-gamipress"
    "enroll-via-ipn"
    "byob-shopp-connect-for-thesis"
    "wp-menu-effects"
    "rss-ground"
    "frequently-asked-questions"
    "gravity-forms-extended-merge-tags"
    "secure-encrypted-form"
    "bad-ip-wp"
    "link-updated"
    "im-wp-linker-lite-for-woocommerce"
    "surbma-smtp"
    "widget-favorites"
    "comment-section-manager"
    "mobile-theme-switcher-2"
    "notificare-website-push"
    "latest-box"
    "remove-blank-p-tag"
    "wp-link-analysis"
    "login-timeout-sessions"
    "adenergizer"
    "wp-mega-menu-recent-posts"
    "avatar-project"
    "gnupay-kcp"
    "twittee-text-tweet"
    "plugin-reinstaller"
    "frontend-add-post"
    "snappy-surveys"
    "wpboutik"
    "woocommerce-chinese-style"
    "eewee-flattr"
    "registration-integration-for-mirespond"
    "wp-favorites"
    "brief-message"
    "wp-socialight"
    "bizexaminer-learndash-extension"
    "bkc-wp-shortcodes"
    "wp-quick-search"
    "archivespress"
    "recent-commentators"
    "appointmentsw"
    "endomondo-summary"
    "colourlovers-rss-widget"
    "input-scanner"
    "mediavine-amp-redirect"
    "wpsimpletools-html-code"
    "wp-google-auto-directions-path-finder"
    "cj-affiliate-network-integration"
    "demovox"
    "hero-section-for-elementor"
    "custom-code-keeper"
    "surbma-optimonk"
    "only-pages-in-feed"
    "ltm-popup-form"
    "meetup-events-widget"
    "advertikon-freeshipping-teaser"
    "compatibility-mode-disabler"
    "text-unfold-for-elementor"
    "multi-favicons"
    "wp-unformating"
    "page-size-checker"
    "recent-photos-widget"
    "fg-gallery"
    "entro-coming-soon-per-postpage-or-global"
    "eewee-twitter-card"
    "webtv-embed"
    "lastfm-now-playing"
    "pattison-media-attribution"
    "preview-link-generator"
    "pdf-for-gravity-forms"
    "restrict-tags"
    "image-annotator"
    "taro-open-hour"
    "all-settings"
    "woocommerce-ownedit"
    "gp-price-block"
    "blog-page-editor-for-elementor"
    "woo-request-network"
    "faqz"
    "external-group-rss-tab-extension"
    "imagemenu"
    "wp-bloginfo-shortcode"
    "korea-map"
    "wp-image-sizes"
    "ry-toolkit"
    "wpfaqblock"
    "bulk-view-post"
    "wp-business-directory-free"
    "sales-popup-for-woocommerce"
    "nutsforpress-smtp-mail"
    "smart-seo"
    "11sight-video-audio-calls-and-text-chat"
    "kannada-chankya-neeti"
    "jackshare"
    "mp-auto-more-tag"
    "google-news-links"
    "covid19-popup"
    "shop-by-look"
    "cookieconsent-io"
    "tipo-documento-peru"
    "ssp-stacktable-tables"
    "hyperise-opengraph-tags"
    "kenzap-steps"
    "srizon-flickr-gallery-basic"
    "front-end-pm-woocommerce-integration"
    "scrollup"
    "os-anspress-custom-fields"
    "youtube-videos-thumbnails-with-lightbox-popup"
    "loopdesk"
    "bcloud-elementor-form-extender"
    "time-express"
    "visit-site"
    "awesome-instant-search"
    "rel-nofollow-categories"
    "subscriber-discounts-for-easy-digital-downloads"
    "html5-details-polyfill"
    "wp-lemme-know"
    "hindi-to-lat"
    "auto-publish-drafts"
    "weiterlesen-auf-den-anfang"
    "playground"
    "syron-gallery-post-type-plugin"
    "acb-scratchpad"
    "screen-reader-text-theme-support"
    "kletterpartner-suche"
    "osbn"
    "floating-wishlist-for-woo"
    "wiget-poster-s"
    "arbitrary-sidebars"
    "amazing-shortcodes-for-visual-composer"
    "blockplayer"
    "martinus-partnersky-system"
    "reservation-system-for-restaurants"
    "author-box-by-nocksoft"
    "temporary-access-for-users"
    "neos-connector-for-fakturama"
    "airliners-widget"
    "at-many-themes"
    "maintenance-alerts"
    "boat-rental-system"
    "wp-giosg"
    "increase-sales"
    "bossadmin"
    "simple-inventory"
    "sv-gravity-forms-enhancer"
    "awasete-yomitai-for-wordpress"
    "all-in-one-messenger"
    "brainpop-uk-learning-video"
    "multisite-shared-blocks"
    "notice-board-by-towkir"
    "schubwerk"
    "wp-color-browser"
    "random-image-block-for-block-editor"
    "wp-quick-navi"
    "cart-messages-for-woocommerce"
    "disclaimer-by-elan42"
    "woocommerce-hide-password-protected-products"
    "fv-swiftype"
    "saner-admin"
    "lsmooths-next-page-posts"
    "simple-flickr-display"
    "slidercat"
    "post-scriptum"
    "wp-switch-user"
    "best-suggestion-boxes"
    "totej-vat-display-selector"
    "handschrifts-integration-for-discord"
    "pdf-shortcodes-ultimate"
    "carbon-offset"
    "drupal-password-encryption"
    "netcents-gateway"
    "post-thumbnail-column"
    "monetbil-edd-gateway"
    "searchbar-org-search"
    "tg-email-protection"
    "woo-tcs-extension"
    "wp-modalplate"
    "woocommerce-stellar"
    "ccr-client-testimonials"
    "likecheese"
    "rv-super-editors"
    "custom-post-type-lister-cpt-lister"
    "jitbit-helpdesk"
    "vividly"
    "evolution-no-version-number"
    "cloudflare-url-replacement"
    "wp-html-rotator"
    "cp-popular-blog"
    "disable-fatal-error-handler"
    "wp28-pague-com-pix"
    "floating-feedback"
    "user-recent-search-history"
    "simple-pdf-bar"
    "easy-download"
    "before-after-content"
    "complete-paypal-payments-for-woocommerce"
    "wide-banner"
    "social-analytics-extensionextends-your-google-analytics"
    "woo-payment-processing-payleap"
    "remaintenance"
    "easy-jump-links-menus"
    "wp-audiofanzine-news"
    "blocks-builder"
    "zsquared-connector-for-zoho-inventory"
    "wp-admin-bar-mover"
    "official-pricerunner-product-feed"
    "tooltip-crazy"
    "trade-ideas-vision"
    "fondy-rcp-gateway"
    "safe-attachment-names"
    "5-sterrenspecialist"
    "persian-nested-showhide-text"
    "ctc-rating"
    "oppso-maps"
    "cyr-to-arabic"
    "automatic-translation"
    "wp-blame"
    "current-year-and-footer-information"
    "auto-login-with-cloudflare"
    "brozzme-hover-integration"
    "buttonz"
    "badger"
    "online-succes"
    "ogulo-360-tour"
    "mooberry-book-manager-image-fixer"
    "simple-relative-content"
    "table-optimizer"
    "is-photo-gallery"
    "ruscurrency-widget"
    "wc-handcash-payments"
    "tp-elementor-addons-kits"
    "wp-anywhere-widgets"
    "drip-payments"
    "spots-importexport"
    "encode-decode-tool"
    "faq-shortcode"
    "zmplugin"
    "ysd-comment"
    "live-preview"
    "heatclix-analytics"
    "disablemu"
    "vietnamese-slug"
    "rsv-slider"
    "stumble-page-social-widget"
    "crosspeakoms"
    "gi-weather"
    "wp-multiratings"
    "bs-user-products"
    "headliner-disco-free"
    "media-ally"
    "ultimate-sms-feedback-form"
    "wp-easy-tools-compression"
    "display-author-option"
    "predikan"
    "wp-seo-locations"
    "woo-xchange-payments"
    "jigoshop-order-locator"
    "wp-tag-this"
    "wplingo"
    "wp-auto-restaurant-finder"
    "delicious-curator"
    "family-law-express-news-widget"
    "wordpress-shortcodes-api"
    "happiness-reports-for-help-scout"
    "nav-menu-query-meta-box"
    "boostbox"
    "intervention"
    "discount-percentage-for-woocommerce"
    "catchfeeder"
    "edd-block-editor"
    "trust-form-for-flamingo"
    "wp-heart-throb"
    "poll-and-survey"
    "otfm-countdown-to-new-year-block"
    "minty"
    "fep-contact-form"
    "ls-social-feed"
    "hot-corners"
    "mindvalley-seo-force"
    "custom-fields-for-jwt-authentication-for-wp-rest-api"
    "mambo-joomla-importer"
    "posty-widget"
    "fnffm-bangla-radio"
    "intravert"
    "smart-sitemap-generator"
    "collapse-magic"
    "hot-accordion"
    "section-separator"
    "dev-info-bar"
    "stepped-content"
    "otter-text-chat-widget"
    "vamaship-shipping"
    "more-plugin-info"
    "tematres-thesaurus"
    "timestocome-category-of-posts-sidebar-widget"
    "hide-admin-menu-items"
    "monster-downloader"
    "wp-morphext"
    "quantumcloud-pagespeed-friendly-analytics-tracking"
    "loghero"
    "ft-rockpress"
    "easy-digital-downloads-slack-notifications"
    "really-simple-tweet"
    "wp-open-files-in-new-window"
    "simple-excel-pricelist-for-woocommerce"
    "js-file-selector"
    "wowquestionnaire"
    "comments-users-mentions"
    "ppm-tooltip"
    "comment-inform"
    "sip-calculator"
    "user-avatar-for-woocommerce"
    "wc-free-shipping-per-package"
    "browser-shots-carousel"
    "ie-compatibility-mode-checker"
    "wp-cookie-tool"
    "eight-degree-posts-list"
    "vishwa-301-redirects"
    "typerocket-ui"
    "featured-images-for-shopp"
    "wp-plugin-data"
    "disable-site-health"
    "f12-wc-accessories"
    "call-button"
    "woo-efactuurdirect"
    "offsite-post"
    "gp-auto-extract"
    "woocommerce-dynamic-sorting"
    "display-price-free"
    "bw-product-stories"
    "eidlogin"
    "mnumidesigner"
    "scrollbar-customizer"
    "blogbuzztime-for-wp"
    "wc-cryptopay-gateway"
    "better-plugin-recommendations"
    "edithtmldom"
    "paid-memberships-pro-takbull-gateway"
    "simple-business-data"
    "coremetrics"
    "admin-taxonomy-autocomplete"
    "url-redirect-and-rewrite"
    "thumbnail-before-content"
    "quizzlestick"
    "edocr-document-viewer"
    "ts-search-slug"
    "update-comment-count"
    "smartcrop"
    "orcas-civicrm-event-list"
    "json-rest-api-subscriptions"
    "genesis-portfolio"
    "produck"
    "paygreen-impact"
    "vignette"
    "youtube-direct"
    "industrial-and-factorial-addons-for-kingcomposer"
    "softtemplates-for-elementor"
    "safe-php-code-widget"
    "x3p0-breadcrumbs"
    "accept-sagepay-payments-using-contact-form-7"
    "exit-monitor"
    "user-register-from-csv"
    "gg-bought-together"
    "simple-range-slider-for-gravityforms"
    "variationpress"
    "myscoop-rank-display"
    "my-press"
    "contact-group-button"
    "hipsum-pixel"
    "wizhi-submenus"
    "agilityfeats-click-to-call"
    "stats-widget"
    "lobby-chatwing"
    "smoothbook"
    "show-notice-or-message-on-admin-area"
    "clicker-counter"
    "javascript-shortcode"
    "credibility"
    "tf-button"
    "notify-on-action"
    "simple-pricing-table-for-elementor"
    "wp-markupcollection"
    "cb-faq-responsive-accordion"
    "chat-with-me-on-zalo"
    "orbisius-warning-suppressor"
    "vnpay-for-woocommerce"
    "followize-extension-gf"
    "http-authentication-by-kimofy"
    "seo-optimized-slideshow"
    "retroposts"
    "hide-the-admin-bar"
    "nom-event-management"
    "pondol-widget-visitor-stats"
    "privacy-acceptance-tracker"
    "bots-master"
    "product-delivery-date"
    "simple-meta-tag-for-pages-and-post"
    "limit-bio"
    "simple-crm-csv-import"
    "charlie-sheen-quote-generator"
    "keeping-points"
    "sargas-recaptcha"
    "img-responsive"
    "simple-youtube-widget"
    "pricing-tables-block"
    "wpematico-polylang"
    "ob-contact-form-to-db"
    "pmc-lockdown"
    "pco-media-handler"
    "onex-custom-popup-builder"
    "acclectic-media-organizer"
    "attachment-page-redirect-x"
    "quotemedia-tools"
    "motif-wordpress-theme-switcher"
    "woo-product-suggest"
    "ct-social"
    "sv-press-permit-show-available-content-for-user"
    "blogroll-block"
    "insert-js-or-css-in-post-via-custom-field"
    "eazy-project-management"
    "better-my-sites-menu"
    "footer-widget-bundle"
    "fb-gocardless-hosted-for-gravity-forms"
    "oneds-start"
    "himis-plugin-organizer"
    "woo-product-variation-range-slider"
    "top-tweetmeme"
    "wp-minimize-admin-bar"
    "report-an-error"
    "zidy-chatbot"
    "acf-page-level"
    "fullscreen-gallery"
    "visual-qr-code-generator"
    "glasses-for-woocommerce"
    "wc-bitpay-gateway"
    "post-checkout-registration-for-woocommerce"
    "fancy-news"
    "cbxwpemaillogger"
    "post-glue"
    "fillet"
    "donate-with-robokassa"
    "stm-woocommerce-gallery"
    "admin-menu-class-by-010pixel"
    "unobtrusive-admin-bar"
    "activity-log-memberpress"
    "meeple-like-us-boardgamegeek"
    "beanstream-gateway-for-woocommerce"
    "clicktowhat-whatsapp-widget"
    "docswell-embed"
    "epaybg-payments"
    "redpic-js-css-optimizer"
    "login-with-yourmembership"
    "realtimehot-weibo"
    "encryption-tools-generator"
    "admin-bar-hopper"
    "honking-goose"
    "jsm-decolorize"
    "subscriber-boost-for-mailchimp"
    "bitcoin-paywall"
    "elastik-addons-for-elementor"
    "contact-blaster"
    "twitter-account-box"
    "wp-easy-login"
    "contact-form-monster"
    "spam-protection-without-captcha"
    "kp-fastest-cf7-recaptcha"
    "dms-shortcode-module-for-divi"
    "french-slugs"
    "wc-reports-lite"
    "wc-vimeo"
    "taeggie-feed"
    "wp-scroll-up"
    "crm-lead-management"
    "doggus-clean-heads"
    "awesome-pricing-tables-lite-by-optimalplugins"
    "gateway-camptix-paynow-payment"
    "wpxon-ajax-contact-form"
    "rg-responsive-gallery"
    "featured-property-widget"
    "ageverify-by-inverite"
    "wp-opcache-patch"
    "map-locator"
    "mentions-legales-par-webdeclic"
    "redirect-homepage-after-logout"
    "cloudkassir-for-woocommerce"
    "ultimate-amp"
    "moldavian-currency-widget"
    "easy-map"
    "kin-icon-picker"
    "main-menu-html-site-map"
    "notify-odoo"
    "disable-pdf-thumbnails"
    "social-engage"
    "remove-administrators"
    "accessibility-statement"
    "filter-rss-feed"
    "islamic-content-archive-for-learn-the-quran"
    "push-down-banners"
    "wp-seo-nofollow"
    "mega-ad"
    "divvyhq"
    "scroll-to-anywhere"
    "presseportal"
    "custom-backorders-for-woocommerce"
    "easy-url-shortcodes-eus"
    "perspective-3d-carousel"
    "lagersystem-dk-parcelpickup-locator-for-woocommerce"
    "show-comment-policy"
    "block-admin-user-logins"
    "auto-text-typing"
    "siuc-click-fraud-detect"
    "right-here-right-now"
    "quietly-insights"
    "member-minder"
    "pay-again-gateway"
    "custom-login-error-message"
    "leafly-menu-embed"
    "soccer-action"
    "dk-white-label"
    "stylish-preloader"
    "catalyst-connect-client-portal"
    "scope-publisher"
    "vk-image"
    "time-limited-account"
    "uvibapay"
    "kpir"
    "ao-lfsmanager"
    "disable-lazy-loading-for-iframes"
    "simple-wp-content-protector"
    "ff-dealers"
    "author-social-links"
    "twitter-tag"
    "recipress-pantrywidget"
    "prostudio-auto-meta-images"
    "omny-studio"
    "trash-emptier"
    "safe-auto-update-restore-manager"
    "simplesurance-insurance-integration"
    "search-by-taxonomy-tag-cloud-search"
    "mrm-recipes"
    "dropdown-search-option-for-contact-form-7"
    "wpa-clean-updates"
    "pdf-creator"
    "universal-honey-pot"
    "template-part-shortcode"
    "featured-video-for-woocommerce"
    "mapbox-for-wp"
    "meta-locker"
    "totalpat"
    "unique-easy-share-posts"
    "flirty-leads"
    "view-category"
    "valsto-payment-for-woocommerce"
    "bulk-post-status-update"
    "wc-quick-customer-redirects"
    "widget-to-shortcode"
    "aw-schema"
    "mg-instamojo-for-give"
    "tutsup-epub-creator-free"
    "strip-non-registered-shortcodes-for-wordpress"
    "external-linker"
    "update-intervals"
    "lnkbio"
    "update-page-cache"
    "woo-cart-additional-fee"
    "content-relations"
    "woo-simple-gift-wrapping"
    "simple-ajax-form"
    "bibliar-search-in-the-bible"
    "wp-monsters"
    "dx-category-reports"
    "whoa-rotate"
    "wordcount"
    "bbpress-analytics"
    "sherky-simple-portfolio"
    "comment-by-tweet"
    "bulk-categories-edit-for-media"
    "klipspringer"
    "variation-swatches-adjacent-products-for-woocommerce"
    "skip-or-remove-cart-page-for-woocommerce"
    "simple-baseball-scoreboard"
    "at-sms"
    "db-error-customizer"
    "gmo-share-connection"
    "iveribuynow"
    "410-delete-pages-seo"
    "content-protection-and-disable-right-click"
    "wopo-solitaire-web-based-game-online"
    "case-study-ninja"
    "fastest-share-buttons"
    "chesser-autoreplace"
    "pure-feed-widget"
    "show-related-post"
    "genie-business-payment-gateway"
    "delete-old-posts-and-pictures"
    "nextdate"
    "sitemile-terms-of-use-agree"
    "otter-waiver-waiver-embed"
    "simple-zoomer"
    "resource-versioning"
    "public-good"
    "dynamic-mo-loader"
    "jeba-news-ticker"
    "dakyaco-recaptcha"
    "wp-duplicate-posts-and-pages"
    "pmpro-multiple-currencies"
    "editor-cleanup-for-divi-builder"
    "wow-entrance-effects-wee"
    "guard"
    "led-site-indicator"
    "where-im-going"
    "seo-ready"
    "time-ago-units"
    "wp-unpublish"
    "onlyoffice-docspace"
    "rsilitech-postcode-availability"
    "selective-tags"
    "twd-smtp-mail"
    "wp-jalapeno"
    "bayarcash-wc"
    "o-rly-comment-spam-search"
    "be-main-category"
    "djhackraj-admin-template"
    "telephone-input-for-contact-form-7"
    "woocommerce-invoice-payment-gateway"
    "woocommerce-product-subscription-mailpoet"
    "ship-log"
    "stylizedx"
    "click-to-scroll"
    "chip-for-fluent-forms"
    "asl-blocks"
    "wc-label-replacer"
    "einsatzberichte-oo"
    "ccr-featured-posts"
    "network-sites-counts-dashboard-widget"
    "purpleads"
    "wp-sheet-editor-post-templates"
    "emojin"
    "bmi-widget"
    "custom-recent-posts-widget-plus"
    "speakstaff-player"
    "stacktack"
    "check-wallet"
    "simple-gist-embed"
    "wordpress-improve"
    "bulk-order-update-for-woocommerce"
    "woo-postcode-validator"
    "dco-post-validator"
    "custom-sticky-notes"
    "wp-chinese-optimize"
    "chbd-simple-jquery-modal"
    "gist-for-robots-wordpress"
    "private-wp-by-ilusix"
    "ns-custom-css"
    "mino-flatsome-title-with-category"
    "advanced-custom-order-status-for-woocommerce"
    "acf-default-image-addon"
    "micro-archive-widget"
    "safelayout-elegant-icons"
    "beacon-web-analytics"
    "repeating-post"
    "debtcom-business-in-a-box"
    "dynamically-dynamic-sidebar"
    "nicescroll4wp"
    "dashboard-posts-stats"
    "cron-job-mail-setup-for-user-role"
    "interactive-posts-ippm"
    "zarehbin"
    "documents-tab-for-woocommerce"
    "liquid-treemap"
    "custom-accordion-block"
    "cart-dropdown-webaddict"
    "sea-sp-community-edition"
    "smntcs-pinterest-save-button"
    "wp-storyboard-gallery"
    "linklay-embed"
    "dismiss-privacy-nag"
    "flexistatic"
    "wp-e-commerce-table-price-shortcode"
    "uwi-homes-widget"
    "channelize-io-real-time-messaging-and-video-calling"
    "lti-sitemap"
    "blocksolid-snippets"
    "web3-token-gate"
    "dlm-changelog"
    "simple-wp-gallery-pro"
    "wp-bigapp"
    "hover-effect"
    "big-boom-initialize-wp"
    "dbtools"
    "miln-photo-feed"
    "chart-for-elementor"
    "role-content-restriction"
    "enqueue-me"
    "nuno-sarmento-custom-css-js"
    "radio-widget-popular"
    "cc-minify"
    "cart-conversion-rate-calculator"
    "wunsch-indexde-wishlists"
    "github-api"
    "plaintracker"
    "gosweetspot-shipping-options"
    "utilities-for-mtg"
    "acf-page-grandchildren"
    "splendid-sales-booster"
    "active-catalog"
    "runtastic-widget"
    "wp-site-links"
    "portfolio-perfect"
    "wp-speed-404"
    "click-to-tweeet-block"
    "insert-post-from-front-end-with-featured-image"
    "known-plugin-dependencies"
    "post-like"
    "video-lightbox-woocommerce"
    "order-postback-woo"
    "acf-meio-mask-field"
    "menu-choice"
    "son-of-clippy"
    "recommend-us"
    "tweak-hidden-options"
    "cynderhost"
    "shareme"
    "mana-symbols"
    "change-font-size-and-color"
    "copyright-shortcodes"
    "gmail-like-gravatar-fallback"
    "extract-blockquote-info"
    "food-business-gross-profit-calculator"
    "crudiator"
    "gf-privacy-addon"
    "cost-calculator-for-elementor"
    "wp-smart-seo"
    "wpkmkz-boostrap-grid-widgets"
    "weforms-pdf"
    "tcbd-custom-scrollbar"
    "compatiblizr"
    "klan1-functions"
    "phplist-comment-subscriber"
    "simple-math-calculator"
    "wp-syntax-highlighter"
    "woo-mahacod-post"
    "listenability"
    "segmetrics"
    "query-loop-post-selector"
    "woo-currency-gel"
    "nutrition-table"
    "acl-floating-cart-for-woocommerce"
    "userlog"
    "startupx-toolkit"
    "regenerate-post-slug-on-save"
    "wp-monitor-dollar"
    "eazy-http-headers"
    "dxfview"
    "jbx-category-columns"
    "lh-html-cleaner"
    "video-playlist-lite"
    "wp-idados-crud"
    "bbpress-popular-topics"
    "screenshot-generator"
    "fail2wp"
    "responsive-iframe-googlemap"
    "change-titles-case"
    "automatic-hx-menu"
    "nopin"
    "civic-sip"
    "woo-prism"
    "wp2tianya"
    "press-this-v2"
    "wp-headless-menu-editor"
    "adbuilder"
    "recaptcha-give"
    "simple-newsletter"
    "page-editor-full-width"
    "add-rakuten"
    "livemesh-weight-based-shipping"
    "crowdfunding-login-form"
    "sassify"
    "i2clipart"
    "amazing-neo-brands"
    "wp-backbone"
    "okhi-woocommerce"
    "twitter-tools-search-tags"
    "presstags"
    "comment-notice"
    "uw-freelancer"
    "secure-password-generator"
    "cms-blocks"
    "simple-course-creator-post-meta"
    "ysd-301redirect"
    "motivation-generator"
    "channel-subscribe-youtube"
    "growth-hacking-analytics-by-qunb"
    "wpp-post-series"
    "disable-fullscreen-mode"
    "extra-post-images"
    "wp-internetvista"
    "responsive-bit-faq-manager"
    "ticket-press"
    "wpg-detect-browser"
    "curatorcrowd-recipe-box"
    "eduport-flyout"
    "vaccine"
    "insiderdata360-code"
    "rateit"
    "daves-outdated-browser-warning"
    "i2-azon"
    "pushalert-onsite-messaging"
    "search-order-by-product-sku-for-woocommerce"
    "smarttouchinteractive-form-builder"
    "ctr-widget"
    "add-overcast-payments-to-seriously-simple-podcasting"
    "hello-event"
    "omniform"
    "price-list-block"
    "wp-login-button"
    "wp-easy-member-neo"
    "best-images-slider"
    "ltl-freight-quotes-purolator-freight-edition"
    "image-type-converter"
    "meta-auth"
    "wp-autopost-trakttv-activity"
    "the-joshua-project-nation-info"
    "sh-email-alert"
    "view-post"
    "debug-assistant"
    "syntaxhighlighter-evolved-applescript"
    "right-click-disable-for-secure"
    "spam-catharsis"
    "cute-news-ticker"
    "ah-jwt-auth"
    "infinite-product-scroll"
    "easy-social-sharebar"
    "mailazy"
    "imu-calculator"
    "haiku-deck-oembed"
    "aixostats"
    "moderdonizer"
    "family-friendly"
    "jumpstart-banners"
    "ultimate-sticky-popup-widgets"
    "kiwi-com-widget"
    "dbisso-cfs-taxonomy-field"
    "disable-post-fonctionnality"
    "frontpage-to-category"
    "doubanshow-for-wordpress"
    "woomaxmin"
    "jigoshop-mini-cart"
    "fegallery"
    "post-in-post"
    "postsummary"
    "photoswipe-foogallery"
    "taxonomy-terms-list-block"
    "min-and-max-order-amount-for-woo-payment-gateways"
    "wc-nuvei-payment-gateway"
    "simpul-blogs-by-esotech"
    "code-snippets-by-webpals"
    "go-live-url-update"
    "custom-wishlist"
    "easy-wp-admin-customizer"
    "kursy-walut-exchange-rates"
    "hoverswap"
    "simpletwit"
    "posts-from-images"
    "domelhornet-for-sociable-2"
    "product-batch-for-woocommerce"
    "fewc-extra-checkout-fields-for-woocommerce"
    "wp-white-label"
    "woocommerce-advanced-newsletter-integration-ani"
    "xml-sitemap-generator-for-videos"
    "kiticon-icon-block"
    "the-winnower-publisher"
    "bulk-meta-editor"
    "cforms2-old-tracking-db"
    "pmr-media-library-image-dimensions"
    "chronoflo-calendar-shortcode"
    "factura-electronica-cr"
    "pronamic-feed-images"
    "responsive-bottom-up-slider"
    "sociallist"
    "max-access"
    "wp-librejs"
    "cookieless-privacy-focused-google-analytics"
    "urvanov-richtext-addfmt"
    "excerpt-editor-for-beaver-builder"
    "hello-server"
    "connect-gamipress-and-discord"
    "mojoauth"
    "wp-fancy-gallery"
    "feedback-manager"
    "sharable-password-protected-posts"
    "orphan-word"
    "wp-thumbnail-column"
    "filetype-icons"
    "bp-signup-member-type"
    "woocommerce-customer-notes-to-completed-order-emails"
    "acf-search-google-maps"
    "add-custom-content-after-post"
    "product-table-for-group-products"
    "applicant-tracking-system"
    "one-post-widget"
    "umich-oidc-login"
    "purchase-order-woocommerce-addon"
    "prevent-email-change"
    "lh-http2-server-push"
    "conditional-logic-solution"
    "ilovemachineproblem-responsive-google-map"
    "muloqot-top-panel"
    "tampile-temperature-conversion-widget"
    "nextapp"
    "add-banner-extension"
    "free-product-for-woocommerce"
    "partita-iva-per-fattura-elettronica"
    "rnd-experts-sip-calculator"
    "buk-appointments"
    "better-categories"
    "markitup"
    "showtweets"
    "dka-more-clean-permalinks"
    "mail-caesar"
    "power-form-7"
    "upload-genesis-logo"
    "pricex-lite"
    "local-classifieds"
    "cache-tweets-widget"
    "wp-simple-faq"
    "hide-text-shortcode"
    "thanh-lien-he-moblie-minhducbiz"
    "aweos-admin-style"
    "citation-importer"
    "wp-store-locator-extenders"
    "heartrails-capture"
    "tiqbiz-api"
    "easy-digital-downloads-location-export"
    "wp-eventpress"
    "upload-field-lite-formidable"
    "out-of-stock-badge"
    "feexpay"
    "bogo-translate-acf"
    "easyamazon"
    "automatic-internal-links"
    "photokit"
    "featured-image-rss-enclosure"
    "thoughtmetric-for-woocommerce"
    "pending-status"
    "skip-rss"
    "inline-review"
    "twig-anything-csv"
    "wp-browser-platform-detection"
    "javascript-obfuscator"
    "wp-shortify"
    "generator-razer-gold-pin-store"
    "restricted-blocks"
    "speedup-optimization"
    "export-2-multisite"
    "add-sku-to-email-notifications-in-wp-e-commerce"
    "monoblog-8912"
    "units"
    "spyrowebz-slider"
    "keltos-tarot-plugin"
    "cod-default-status-for-woocommerce"
    "search-limiter-blocker"
    "provincias-de-ecuador-para-woocommerce"
    "autor-buscar-pagina"
    "maximum-width-container"
    "xl-product-carousel"
    "joudisoft-general-wp-mobile-application"
    "turnsocial-toolbar"
    "free-shipping-bar-widget-for-elementor"
    "aio-shortcodes"
    "ai-postpix"
    "qtext-x-widget"
    "mutual-funds-data"
    "content-expiration"
    "catnip"
    "vcat-posts-at-google-maps"
    "css-naked-day"
    "icheckmovies-widget"
    "randomposts-widget"
    "callweb"
    "agecheck"
    "aircash-for-woocommerce"
    "wc-products-visibility"
    "wp-asambleas"
    "zero-to-free-text"
    "completly-random-widget"
    "readable"
    "creo-currency-converter-lite-for-woocommerce"
    "ai-bot"
    "extension-for-wp-job-manager-support-in-elementor-pro"
    "professional-login-and-registration-page-style"
    "the-dude"
    "wp-opensearch"
    "dealads"
    "pushpro-push-notifications"
    "w2pe-measurement-widget"
    "woocommerce-hot-products-by-category-and-vendor"
    "wp-image-filters"
    "page-restriction-with-role"
    "3d-printing-pro-by-boostfab"
    "entourance"
    "sim-social-feed"
    "menu-based-sidebar"
    "apoyl-toutiaopush"
    "processing-projects"
    "candifly"
    "easy-demo-importer"
    "xml-rpc-administrator"
    "wp-config-constants"
    "clock-widgets"
    "almost-users-only"
    "last-modified-and-if-modified-since-headers"
    "ga-admin-taxonomy-search"
    "cashfree-gravity-forms"
    "archiiv"
    "enqueueror"
    "minimalist-tag-cloud"
    "degree-of-difficulty-for-sensei"
    "okpay-payment-gateway"
    "back-to-the-future"
    "sharetimetable-booking"
    "devrama-image-lazyload"
    "hide-wp-customizer-options"
    "rainyshots"
    "disable-browser-telephone-format-detection"
    "multiple-roles-per-user"
    "pixel-clusters"
    "languageback"
    "linkedin-badge-by-pixelpillow"
    "zoneboard"
    "client-dash-status-cake-add-on"
    "info-blocks"
    "hatena-bookmark-comment"
    "consignment-store-for-woocommerce"
    "technicality-google-analytics"
    "fluent-comments"
    "wp-smartbanner"
    "dietmaster-pro-nutrition"
    "chalet-montagne-com-tools"
    "advanced-dashboard-for-woocommerce"
    "image-alt-editor"
    "melonpan-block-code"
    "caspio-deployment-control"
    "gna-contact-form-7-sms"
    "show-random-products"
    "logs-display"
    "woo-sub-categories"
    "wp-responsive-media-gallery"
    "dp-addthis"
    "embed-light-field-photos"
    "simple-flexi-slider-by-lms-it"
    "cc-cache"
    "dh-press"
    "remove-jquery-migrate-safely"
    "ai-content-writer-chatgpt"
    "theme-detector"
    "easy-pricing-forms"
    "meal-planner"
    "wpmerchant"
    "cache-manifest"
    "error-log-viewer-wp"
    "aj-csv-to-datatable"
    "inazo-advanced-ads-management"
    "banckle-crm"
    "recent-posts-only"
    "wp-aaieduhr-auth"
    "gitblock"
    "shp-rssimage"
    "seo-auto-image-tags"
    "tootpress"
    "ultimate-side-banners"
    "all-post-statuses-for-add-link"
    "moonify"
    "dco-shortcodes-menu"
    "pinpointe-form-integration"
    "foundationtables"
    "simple-not-found-rescue"
    "technoscore-hotjar-tracking"
    "4-author-cheer-up-donate"
    "payment-gateway-poli-for-woocommerce"
    "social-bot"
    "woo-lhv-hire-purchase"
    "ninjaseo"
    "nf-livecounter"
    "countdowndays"
    "wp-theme-shapeshifter-extensions"
    "dark-mode-karen-lite"
    "fb-analytics"
    "email-login-attempts"
    "actus-animated-words-slider"
    "nextgen-tinymce-gallery-description"
    "sticky-add-to-cart"
    "resize-editor"
    "peq-leia-mais-adobe-srpy"
    "wp-switch-admin-email-verification-off"
    "product-display-for-prestashop"
    "coder-block"
    "social-photo-gallery"
    "custom-messages-in-rss-feed"
    "solutions-ad-manager"
    "awesome-headlines-generator-lite-by-optimalplugins"
    "virtual-signature"
    "html-classified-recent-posts-comments-widgets"
    "shift8-remote-update"
    "octagon-support-forum-for-envato"
    "pagemanager"
    "datalayer-for-elementor"
    "fediverse-embeds"
    "fullscreen-ajax-loader"
    "wp-flickr-embed-plus"
    "ddevs-media-gallery"
    "humans-dot-txt"
    "wc-products-ticker"
    "sendcloud-email-sender"
    "cryptocurrency-nft"
    "text-message-contact-form-biztext"
    "hide-core-update-notice"
    "wc-exporter-for-reviso"
    "mobiswitch"
    "squirrels-auto-inventory"
    "oxy-relogin-window"
    "ghl-connect"
    "day-spelled"
    "meteosales"
    "mk-auto-youtube-player"
    "sensiri"
    "ultimate-db-manager-lite"
    "allparcels-shipping-module"
    "adzan-and-iqamah-times-a-simple-reminder"
    "dismiss-privacy-tools"
    "fluentc-translation"
    "managead"
    "webvtt"
    "carolyn-google-analytics"
    "tuyul-ninja"
    "filerobot-digital-asset-management-and-acceleration"
    "citrasms-woocommerce-sms-notification"
    "securepay-for-wpjobster"
    "redirect-to-latest-post-in-category"
    "kenzap-timetable"
    "pixel-for-web-stories"
    "pryc-wp-widget-shortcode"
    "attribution"
    "simple-presenter"
    "ads-txt-lab"
    "great-circle-mapper"
    "goldnet-sip-simple"
    "intelliwidget-gallery-slides"
    "image-hover-effects-for-wpbakery-page-builder"
    "mm-dashboard-customizer"
    "gravityforms-fatzebra"
    "yabe-bricksbender"
    "content-sell-licenses-for-woocommerce"
    "woo-aus-ezi-freight"
    "wakker-media-newsletter-checkout-checkbox"
    "mailchimp-and-constant-contact-integration"
    "woo-cross-sell-popup"
    "springest-partners"
    "regenerate-download-permissions-for-orders"
    "wp-admin-filter-search"
    "feedback-unlocked-download"
    "sl-map"
    "gel-proximity-for-woocommerce"
    "cstris"
    "boom-cdn"
    "spoiler-alert-js"
    "ai-chatbot-live-chat-for-wordpress-using-chatgpt"
    "simple-settings"
    "simple-goods"
    "quiet-comment-disable"
    "awesome-snowfall-animation"
    "any-word-search"
    "anomify"
    "os3-website-protector"
    "local-shipping-labels-for-woocommerce"
    "my-wpdb"
    "beautiful-product-offers-for-woocommerce"
    "amd"
    "free-contact-us"
    "mobile-app-banners"
    "marketpress-frontend"
    "neeed"
    "moodgiver-hide-shop-categories"
    "cart-total-rounding"
    "wphelpful"
    "imagebox-module"
    "wpbatch-scroll-to-top"
    "blue-storage"
    "connect"
    "credly-pro-custom-assertion"
    "webcake"
    "hong-kong-fps-woo-payment"
    "vidlive"
    "modenapaymentgateway"
    "detect-missing-adblocker"
    "wp-double-protection"
    "stop-auto-update"
    "wolframalpha"
    "jm-buddy-translate"
    "locationews"
    "reservation"
    "buddypress-connect-for-tally-framework"
    "ticket-help-desk-system-lite"
    "audience1st-ticket-availability"
    "total-spent-by-customer-for-woocommerce"
    "nutsforpress-maintenance-mode"
    "newsletter-rss-block"
    "gp-hide-menu-options-by-role"
    "lh-cache-remote-images"
    "ct-page-editors"
    "multisite-widget-link"
    "add-style-to-post"
    "blocks-post-grid"
    "tag-wiki"
    "the-j-a-mortram-share-this-story"
    "video-game-life-meter"
    "before-after-image-comparison-slider-block"
    "instacash-pos-payment"
    "webhook-for-wcfm-vendors"
    "js-switch"
    "bad-comments"
    "quote-of-the-moment"
    "tidyoutput"
    "quotepro-office-widget"
    "which-blocks"
    "politik-bei-uns"
    "crm-for-contact-form-7"
    "display-category-image"
    "autolink-generator"
    "wp-pricing"
    "ios-smart-app-banner-for-safari"
    "nepali-forex-rate"
    "banman"
    "up-sell-trio-for-woocommerce"
    "broadcast-to-telegram"
    "store-manager"
    "wp-mobily"
    "easy-wp-google-tag-manager"
    "woo-login-to-see-price-and-buy"
    "pollux"
    "mks-video-embed-with-shortcode"
    "adminbar-on-off"
    "customer-loyalty-for-woocommerce"
    "wpmayor-dashboard-feed"
    "custom-swatches-for-iris-color-picker"
    "mainichi-shopify-products-connect"
    "simple-flickr-set"
    "web-developers-portfolio-plugin"
    "feed-importer-micro-blog"
    "ciusan-restrict-widget"
    "inaccessibility-checker"
    "cr-flexible-comment-moderation"
    "ultimate-team-showcase"
    "wp-stop-profanity"
    "demomentsomtres-image-feed-widget"
    "maxi-woo-ajax-navigation"
    "payflexi-split-payment-gateway"
    "doctorlogic-components"
    "bizsugar-voting-button"
    "vcos"
    "be-rest-endpoints"
    "qr-user-login"
    "simply-contact"
    "mycausora-donation-widget"
    "wirtualna-polska-pixel"
    "edd-checkout-message"
    "simple-email-queue"
    "swiftad"
    "retcform"
    "urakanji-wiki-converter"
    "powerup"
    "wp-contact-form-7-db-handler"
    "prevent-users-from-deleting-pages-posts-custom-post-types"
    "inseri-core"
    "mine-metamask"
    "zoneit-backup"
    "plink-payment-gateway"
    "simple-faq-manager"
    "elex-reachship-multi-carrier-conditional-shipping"
    "wc-shipengine-shipping"
    "rank-with-schema"
    "my-widgets"
    "identity-plus"
    "curiyo-links"
    "statut-3d-cube"
    "posts-slider-shortcode"
    "headit"
    "alpha-single-product-for-elementor"
    "covid-19"
    "wp-triage"
    "enlightenedimages"
    "upcoming-events-for-eventbrite"
    "first-purchase-discount-for-woocommerce"
    "video-lead-form"
    "img-dead-simple-contact-form"
    "podcasts"
    "url2png-screenshots"
    "hello-login"
    "kunato-ai"
    "masterwoos-woocommerce-variations-per-page"
    "gna-change-mail-sender"
    "wp-posts-most-read"
    "picture-quote-of-the-day-by-azquotes"
    "wpgalerts"
    "missing-content"
    "bcd-roster"
    "jentis"
    "catalog-enquiry"
    "tarot-online"
    "song-book"
    "pco-kint"
    "open-payout"
    "mc-login-code"
    "archive-links-nofollow"
    "recent-pages"
    "daily-christian-bible-verses"
    "bad-tournament"
    "thank-money-post"
    "advanced-pricing-addon-wpbakery"
    "discourage-search-engines-by-url"
    "remove-custom-post-type-slug-from-permalink"
    "download-monitor-learndash-integration"
    "hc-privacy-compactor"
    "product-feed-silver"
    "landing-lion-landing-pages"
    "coder-customizer-framework"
    "resourcify"
    "wemap"
    "google-author-button"
    "pagepeeker"
    "szamlahegy-woocommerce"
    "share-goodreads-update"
    "precise-columns"
    "justintv-twitch-oembed"
    "fl3r-randavatar"
    "distinct-preview"
)

# Define user agents with weights
declare -A USER_AGENTS
USER_AGENTS=(
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"]=5
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"]=7
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"]=6
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36 Edg/91.0.864.54"]=5
    ["Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 OPR/77.0.4054.277"]=3
    ["Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (iPad; CPU OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Vivaldi/4.0"]=1
    ["Mozilla/5.0 (Android 11; Mobile; rv:68.0) Gecko/68.0 Firefox/88.0"]=1
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"]=15
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/534.36"]=12
)

OPENED_PLUGINS_FILE="${WORDPRESS_WORKDIR}/opened_plugins.txt"
CLOSED_PLUGINS_FILE="${WORDPRESS_WORKDIR}/closed_plugins.txt"
LAST_VERSION_FILE="${WORDPRESS_WORKDIR}/last_versions.txt"
PARALLEL_JOBS=1

DOWNLOAD_ALL_PLUGINS='n'
LIST_ONLY='n'
ALL_PLUGINS_FILE="${WORDPRESS_WORKDIR}/wp-plugin-svn-list.txt"

DELAY_DOWNLOADS='n'
DELAY_DURATION=5

FORCE_UPDATE='n'
CACHE_ONLY='n'

mkdir -p "$WORDPRESS_WORKDIR" "$MIRROR_DIR" "$LOGS_DIR"
rm -f "$OPENED_PLUGINS_FILE"
touch "$OPENED_PLUGINS_FILE"
DEBUG_MODE=0

while getopts "p:dalD:t:fc" opt; do
    case ${opt} in
        p ) PARALLEL_JOBS=$OPTARG ;;
        d ) DEBUG_MODE=1 ;;
        a ) DOWNLOAD_ALL_PLUGINS='y' ;;
        l ) LIST_ONLY='y' ;;
        D ) DELAY_DOWNLOADS=$OPTARG ;;
        t ) DELAY_DURATION=$OPTARG ;;
        f ) FORCE_UPDATE='y' ;;
        c ) CACHE_ONLY='y' ;;    # New option for cache-only
        \? ) echo "Usage: $0 [-p PARALLEL_JOBS] [-d] [-a] [-l] [-D DELAY_DOWNLOADS] [-t DELAY_DURATION] [-f] [-c]" 1>&2; exit 1 ;;
    esac
done

debug_log() {
    if [ "$DEBUG_MODE" -eq 1 ]; then
        echo "[DEBUG] $1" >&2
    fi
}

get_random_user_agent() {
    echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
}

get_latest_version_and_download_link() {
    local plugin=$1
    debug_log "Checking latest version and download link for $plugin"
    
    local api_url="https://api.wordpress.org/plugins/info/1.0/${plugin}.json"
    local user_agent=$(get_random_user_agent)
    local api_response=$(curl -s -H "User-Agent: $user_agent" "$api_url")
    
    if echo "$api_response" | jq -e '.error' >/dev/null; then
        local error_message=$(echo "$api_response" | jq -r '.error')
        if [ "$error_message" = "closed" ]; then
            echo "closed"
            return 2
        else
        echo "Error: $error_message for plugin $plugin" >&2
        return 1
        fi
    fi
    
    local version=$(echo "$api_response" | jq -r '.version // empty')
    local download_link=$(echo "$api_response" | jq -r '.download_link // empty')
    
    if [ -n "$version" ] && [ -n "$download_link" ]; then
        echo "$version $download_link"
        return 0
    else
        echo "Error: Cannot fetch version or download link for $plugin" >&2
        return 1
    fi
}

download_plugin() {
    local plugin=$1
    local version=$2
    local api_download_link=$3
    local output_file="${MIRROR_DIR}/${plugin}.${version}.zip"
    local header_file="${LOGS_DIR}/${plugin}.${version}.headers"
    local constructed_download_link="${DOWNLOAD_BASE_URL}/${plugin}.${version}.zip"
    local download_link

    if [ "$DEBUG_MODE" -eq 1 ]; then
        debug_log "API-provided download link for $plugin: $api_download_link"
        debug_log "Constructed download link for $plugin: $constructed_download_link"
    fi

    if [ "$DOWNLOAD_LINK_API" == 'y' ] && [ -n "$api_download_link" ]; then
        download_link="$api_download_link"
        debug_log "Using API-provided download link for $plugin: $download_link"
    else
        download_link="$constructed_download_link"
        debug_log "Using constructed download link for $plugin: $download_link"
    fi

    debug_log "Downloading $plugin version $version through Cloudflare Worker"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)
    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o /dev/null "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    else
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o "$output_file" "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    fi

    if [ $? -eq 0 ]; then
        if [ "$CACHE_ONLY" == 'y' ]; then
            debug_log "Plugin $plugin version $version cached successfully."
            return 0
        fi

        local file_size=$(stat -c%s "$output_file")
        if [ "$file_size" -lt 1000 ]; then
            echo "Error: Downloaded file for $plugin is too small (${file_size} bytes). Possible download issue." >&2
            return 1
        fi

        local source=$(grep -i "X-Source:" "$header_file" | cut -d' ' -f2 | tr -d '\r')
        if [ "$source" == "R2" ]; then
            debug_log "Successfully downloaded $plugin version $version from R2 storage"
        elif [ "$source" == "WordPress" ]; then
            debug_log "Successfully downloaded $plugin version $version from WordPress"
            debug_log "R2 bucket saving for plugin zip occurred"
        else
            debug_log "Skipped download for $plugin $version zip (already exists locally)"
        fi

        return 0
    else
        echo "Error: Failed to download $plugin version $version" >&2
        return 1
    fi
}

save_plugin_info() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.json"

    debug_log "Saving plugin json metadata for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying metadata download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    if [ "$CACHE_ONLY" == 'y' ]; then
        # When in cache-only mode, output to /dev/null
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin metadata for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache json metadata for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            if [ "$source" = "R2" ]; then
                debug_log "json metadata for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "json metadata for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin json occurred"
            else
                debug_log "json metadata for $plugin version $version saved (json metadata file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save json metadata for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

fetch_and_save_checksums() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.checksums.json"

    debug_log "Fetching and saving checksums for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying checksums download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    debug_log "Sending request to Worker for checksums: CF_WORKER_URL?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"

    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin checksums for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache checksums for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        debug_log "Received response with status code: $status_code"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            debug_log "Response source: $source"
            if [ "$source" = "R2" ]; then
                debug_log "Checksums for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "Checksums for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin checksums occurred"
            else
                debug_log "Checksums for $plugin version $version saved (checksums file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save checksums for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

process_plugin() {
    local plugin=$1

    # Check if the plugin is already known to be closed
    if grep -q "^$plugin$" "$CLOSED_PLUGINS_FILE" 2>/dev/null; then
        echo "Plugin $plugin is known to be closed. Skipping."
        return 0
    fi

    echo "Processing plugin: $plugin"

    VERSION_AND_LINK=$(get_latest_version_and_download_link "$plugin")
    local version_check_status=$?
    
    if [ $version_check_status -eq 1 ]; then
        echo "Skipping $plugin due to version fetch error."
        return 1
    elif [ $version_check_status -eq 2 ]; then
        echo "Plugin $plugin is closed. Skipping download and processing."
        echo "$plugin" >> "$CLOSED_PLUGINS_FILE"
        if save_plugin_info "$plugin" "closed"; then
            debug_log "Successfully saved json metadata for closed plugin $plugin."
        else
            debug_log "Failed to save json metadata for closed plugin $plugin."
        fi
        return 0
    fi
    
    LATEST_VERSION=$(echo "$VERSION_AND_LINK" | cut -d' ' -f1)
    API_DOWNLOAD_LINK=$(echo "$VERSION_AND_LINK" | cut -d' ' -f2-)

    debug_log "Latest version for $plugin: $LATEST_VERSION"
    debug_log "API download link for $plugin: $API_DOWNLOAD_LINK"

    STORED_VERSION=$(grep "^$plugin" "$LAST_VERSION_FILE" | awk '{print $2}')
    debug_log "Stored version for $plugin: $STORED_VERSION"

    if [ "$CACHE_ONLY" != 'y' ] && [ "$LATEST_VERSION" == "$STORED_VERSION" ] && [ -f "${MIRROR_DIR}/${plugin}.${LATEST_VERSION}.zip" ]; then
        echo "$plugin is up-to-date and exists in mirror directory. Skipping download..."
    else
        start_time=$(date +%s.%N)

        if download_plugin "$plugin" "$LATEST_VERSION" "$API_DOWNLOAD_LINK"; then
            if [ "$CACHE_ONLY" != 'y' ]; then
                sed -i "/^$plugin/d" "$LAST_VERSION_FILE"
                echo "$plugin $LATEST_VERSION" >> "$LAST_VERSION_FILE"
            fi
            echo "Successfully processed $plugin."
        else
            echo "Error: Failed to process $plugin." >&2
        fi

        end_time=$(date +%s.%N)
        duration=$(echo "$end_time - $start_time" | bc)
        printf "Time taken for %s: %.4f seconds\n" "$plugin" "$duration"
    fi

    if save_plugin_info "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully saved json metadata for $plugin."
    else
        debug_log "Failed to save json metadata for $plugin."
    fi

    if fetch_and_save_checksums "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully fetched and saved checksums for $plugin."
    else
        debug_log "Failed to fetch and save checksums for $plugin."
    fi

    if [ $version_check_status -eq 0 ]; then
        echo "$plugin" >> "$OPENED_PLUGINS_FILE"
    fi
}

populate_all_plugins() {
    if [ ! -f "$ALL_PLUGINS_FILE" ] || [ "$LIST_ONLY" == 'y' ]; then
        echo "Fetching list of all WordPress plugins..."
        svn list https://plugins.svn.wordpress.org/ | sed 's/\/$//g' > "$ALL_PLUGINS_FILE"
        plugin_count=$(wc -l < "$ALL_PLUGINS_FILE")
        echo "Plugin list (${plugin_count}) saved to $ALL_PLUGINS_FILE"
    fi
    
    if [ "$LIST_ONLY" == 'n' ]; then
        ALL_PLUGINS=()
        while IFS= read -r line; do
            ALL_PLUGINS+=("$line")
        done < "$ALL_PLUGINS_FILE"
        echo "Loaded ${#ALL_PLUGINS[@]} plugins."
    fi
}

if [ "$LIST_ONLY" == 'y' ]; then
    populate_all_plugins
    echo "Plugin list created. Exiting without downloading."
    exit 0
fi

if [ "$DOWNLOAD_ALL_PLUGINS" == 'y' ]; then
    populate_all_plugins
    COMBINED_PLUGINS=("${ALL_PLUGINS[@]}")
else
    if [ ! -d "$PLUGIN_DIR" ]; then
        echo "Warning: Plugin directory $PLUGIN_DIR does not exist or is invalid."
        PLUGIN_LIST=()
    else
        PLUGIN_LIST=($(ls -d "$PLUGIN_DIR"/*/ 2>/dev/null | xargs -n 1 basename))

        if [ ${#PLUGIN_LIST[@]} -eq 0 ]; then
            echo "No plugins found in $PLUGIN_DIR."
        fi
    fi

    COMBINED_PLUGINS=(${PLUGIN_LIST[@]} ${ADDITIONAL_PLUGINS[@]})
    COMBINED_PLUGINS=($(echo "${COMBINED_PLUGINS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
fi

if [ ${#COMBINED_PLUGINS[@]} -eq 0 ]; then
    echo "No plugins to download. Exiting."
    exit 0
fi

mkdir -p "$MIRROR_DIR"
touch "$LAST_VERSION_FILE"

if [ "$PARALLEL_JOBS" -gt 1 ]; then
    echo "Running in parallel with $PARALLEL_JOBS jobs..."
    # First, export all variables including USER_AGENTS
    export DOWNLOAD_BASE_URL MIRROR_DIR LAST_VERSION_FILE DEBUG_MODE DOWNLOAD_LINK_API LOGS_DIR ALL_PLUGINS_FILE DOWNLOAD_ALL_PLUGINS LIST_ONLY CF_WORKER_URL DELAY_DOWNLOADS DELAY_DURATION FORCE_UPDATE CACHE_ONLY USER_AGENTS

    # Then, export the functions
    export -f process_plugin get_latest_version_and_download_link download_plugin debug_log populate_all_plugins save_plugin_info get_random_user_agent fetch_and_save_checksums
    printf "%s\n" "${COMBINED_PLUGINS[@]}" | xargs -P $PARALLEL_JOBS -I {} bash -c 'process_plugin "$@"' _ {}
else
    for plugin in "${COMBINED_PLUGINS[@]}"; do
        process_plugin "$plugin"
    done
fi

if [ -f "$CLOSED_PLUGINS_FILE" ]; then
    echo
    echo "Closed Plugin List:"
    cat "$CLOSED_PLUGINS_FILE" | sort | uniq || true
    echo
    echo "Total closed plugins: $(wc -l < "$CLOSED_PLUGINS_FILE")"
    echo
else
    echo
    echo "No closed plugins found."
    echo
fi
echo "Plugin download process completed."
