#!/bin/bash

# Base directory (script location)
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Configurable directories
WORDPRESS_WORKDIR="${WORDPRESS_WORKDIR:-$BASE_DIR/wordpress-plugins}"
PLUGIN_DIR="${PLUGIN_DIR:-$BASE_DIR/wp-content/plugins}"
MIRROR_DIR="${MIRROR_DIR:-$BASE_DIR/mirror}"
LOGS_DIR="${LOGS_DIR:-$BASE_DIR/plugin-logs}"

# Check for CF_WORKER_URL environment variable
if [ -z "$CF_WORKER_URL" ]; then
    echo "Error: CF_WORKER_URL environment variable is not set." >&2
    exit 1
fi

DOWNLOAD_BASE_URL="https://downloads.wordpress.org/plugin"

# Other variables
DOWNLOAD_LINK_API='y'

ADDITIONAL_PLUGINS=(
    "ninja-columns"
    "biorhythm"
    "backuppressgenius"
    "wc-granatum"
    "greenmail-email-marketing"
    "taptree-payments-for-woocommerce"
    "emoji-shortcode"
    "download-count"
    "dwp-loginizer"
    "recent-wp-user-visitors"
    "disable-feed-category"
    "bvd-easy-gallery-manager"
    "advanced-twitter"
    "home-badges"
    "um-user-switching"
    "aa-pdf-reader"
    "felicette-pedigree-litters"
    "basic-scroll-to-top"
    "combo-wp-rewrite-slugs"
    "metamax"
    "sv-woocommerce-order-export"
    "import-bookmarks"
    "pixter-image-digital-license"
    "feedback-extended"
    "easy-ajax-mail-subscription"
    "scoreboard-widget"
    "post-announcement"
    "editor-file-search"
    "mycred-rank-plus"
    "plugin-modification-date"
    "hits-counter"
    "ss-preloader"
    "twpw-stop-remote-comments"
    "aasigninwidget"
    "wp-mucaptcha"
    "overstock-affiliate-links"
    "live-preview-product-options-lite"
    "http11-403-forbidden-header-on-a-failed-login"
    "fix-jumping-header-divi"
    "responsive-video-embedder"
    "wp-wallcreeper"
    "thoughts-of-the-day"
    "custom-post-type-list-field-for-contact-form-7"
    "site-settings"
    "auto-anchor"
    "invition-print-ship-zakeke"
    "pando-extra"
    "sql-table-lookup"
    "theme-search"
    "extlnk"
    "venby"
    "snapplify-e-commerce"
    "ni-woocommerce-order-delivery"
    "conversation-viewer-display-chat-bubbles"
    "fixes-for-mod-pagespeed"
    "makesafe"
    "optio-integration-tools"
    "user-registration-and-login"
    "message-trigger"
    "censorship"
    "cutecaptcha"
    "reaction-buttons-by-heateor"
    "simple-ssl-redirects"
    "flash-sale-product-wc-wpshare247"
    "captchafox-for-forms"
    "spikkl-address-lookup"
    "press-loft-affiliate-network"
    "iksweb"
    "vicodo-live-video-chat"
    "visited-states"
    "shorten-subcategorys-link"
    "choice-payment-gateway-for-woocommerce"
    "openmost-site-kit"
    "multisite-mediasync"
    "admin-login-sms-notification"
    "essential-wp-tools"
    "different-shipping-and-billing-address-for-woocommerce"
    "covid-19-float-button"
    "woo-facturadirecta"
    "speed-booster-by-melotheme"
    "messeninfode-widget"
    "events-manager-rich-snippets"
    "tcbd-modals"
    "easy-meta-builder"
    "wp-random-feeds"
    "pronamic-subscriptions"
    "bkc-action-hooks"
    "large-csv-import-handler"
    "woo-konto-checkout"
    "seomix-disable-core-sitemaps"
    "scaleengine-sevu-video-security"
    "browsable-wordpress-tags"
    "template-usage"
    "jigoshop-credimax"
    "zero-ecoimpact-woocommerce"
    "wholesalex-wcfm-b2b-multivendor-marketplace"
    "fx-login-notification"
    "translate-websites-translentor"
    "ravelry-designs-widget"
    "amp-img-shortcode"
    "mini-live-preview-url"
    "mystem-extra"
    "getty-ghetto-slider"
    "ztorie"
    "query-string-remover-from-static-resources"
    "eventbee-rsvp-widget"
    "ga-made-simple"
    "post-admin-social-stats"
    "ap-stream-to-rocket"
    "mindvalley-edit-link"
    "make-autop"
    "higher-education-connect"
    "wp-directory-listing"
    "magic-login-api"
    "browsing-history"
    "textboxes"
    "social-feed"
    "yr-activity-link"
    "caret-ez-google-maps"
    "dsense-like-posts"
    "widget-rotator"
    "geo-masala"
    "pcf-new-year-countdown"
    "tattoo-shop-manager"
    "stock-count-report-for-woocommerce"
    "user-registration-email-validator"
    "multifox-plus"
    "lz-scroll-up"
    "custom-post-type-calculator"
    "blocksplus"
    "dokme"
    "wpcf7-email-collector"
    "inxpress-shipping-extension"
    "user-agent-blocker"
    "html-to-pdf-converter"
    "ambition-cloud-gf-add-on"
    "batsignal"
    "salonmonster-online-booking-for-salons-and-spas"
    "contributors"
    "sell-with-razorpay"
    "woo-update-cart-qty-dynamic"
    "qroko-blocks"
    "better-detection"
    "hypersell-cod-order-form"
    "ngan-luong-payment-gateway-for-woocommerce"
    "free-gifts-widget-with-images"
    "reminder-mail-system"
    "uktw"
    "couponpanel"
    "redlink-widget"
    "admin-announce"
    "leanpress"
    "optimum-exit-popup"
    "retro-color-scheme"
    "code-quality-control-tool"
    "garanti-bbva-virtual-pos-application-integration"
    "mme-real-estate"
    "fullworks-scanner"
    "wp-posts-ticker"
    "seo-external-links"
    "wowtag-widget"
    "theme-versioning"
    "sowprog-import-the-events-calendar"
    "recotrust-integration"
    "mietshop-shopsystem"
    "hm-news-ticker"
    "images-to-posts"
    "content-copy-finder"
    "charty"
    "apuracao-eleicoes-brasil"
    "opengrapher"
    "advanced-button-block"
    "quiposte-orders-tracking-for-woocommerce"
    "pit-title-capitalize"
    "surveyanyplace"
    "woo-simple-variation-tools"
    "dynamic-blocks-builder"
    "blog-settings"
    "never-outdated"
    "wp-talkshoe-archives"
    "wao-io"
    "magnifinance-invoice-system"
    "quickreviewer-html-review"
    "clean-yoast-seo-cache"
    "trigger-browsersync"
    "tap-to-top"
    "moove-logistica-for-woocommerce"
    "add-authors-not-users"
    "grab-image-from-remote-url"
    "fogata-bots"
    "zp-post-slider"
    "pods-toolbar"
    "ngo-list"
    "doo-block-patterns"
    "junoe-xmlrpc-additional-methods"
    "expan-pro"
    "filejet-pro"
    "category-external-feed-plugin"
    "wplms-woocommerce-membership-addon"
    "global-content"
    "wp-taf-metar-widget"
    "8pay-payment-gateway"
    "plugin-categories"
    "embed-bare-image-links"
    "basic-social-share-buttons"
    "visual-header"
    "embed-outlook-teams-calendar-events"
    "custom-login-screen"
    "multi-vendor-marketplace-b2b-for-wholesalex-dokan"
    "phraseanet-client"
    "atlas-discuss-quote-form"
    "image-caption-on-featured"
    "udvd-contactpage-generator"
    "pageview-content-restriction"
    "bbpress-new-topic-notifications-to-inbox"
    "flagship-shipping-extension-for-woocommerce"
    "total-cost-input-for-woocommerce"
    "curatewp-nested-posts"
    "term-thumbnails"
    "lh-buddypress-multi-network"
    "recolize"
    "advanced-options-for-woocommerce"
    "get-different-front-page"
    "link-away"
    "pet-webcam-widget"
    "udssl-time-tracker"
    "truvisibility-plagiarism-checker"
    "gp-format-csv"
    "zalo-official-live-chat"
    "pagebreak-description"
    "cf7-referrer-url"
    "oktopost-tracking-code"
    "wp-soavis"
    "eewee-sellsy"
    "my-kindle-books"
    "dig-bloginfo-shortcode"
    "basic-banner"
    "professional-contact-form"
    "sharespring"
    "if-as-shortcode"
    "plugin-all-info"
    "fancy-testimonials"
    "eve-online-pheal-api"
    "csrhub-sustainability-rating-widget"
    "pollcaster-shortcode"
    "wpbmb-entrez"
    "heliblocks"
    "sortbyme"
    "am-wp-which-template"
    "gift-ribbon"
    "new-tab-actions-by-wasiwarez"
    "wp-local-storage"
    "hectane"
    "extensions-for-two-factor"
    "user-login-magic-links"
    "blockbuddy"
    "wp-forecast-weather"
    "product-widget-glopart"
    "eledo-pdf-attachments-for-woocommerce"
    "article"
    "responsive-scrollable-table"
    "image-sizes-on-demand"
    "socialman"
    "ga-code-management"
    "socialmyblog"
    "square-bracket-hack-prevention"
    "slack-edd"
    "timer-element-for-elementor"
    "appbuff-testimonial-for-elementor"
    "grouped-content"
    "string-override"
    "add-pingbacks"
    "shipping-deprisa-woo"
    "qr-pay-gateway"
    "inventive-stock-player-lite"
    "foundation-live-shortcodes"
    "no-encontrado-404"
    "gb-quick-launch"
    "concrete-calculator"
    "wp-yearly-and-monthly-archive-list"
    "wp-chimp"
    "wowpress"
    "simple-wc-order-exportimport"
    "stimulate-correct-headings"
    "myportfolio"
    "linkbuildingadmin"
    "vies-validator"
    "tor-blocker-by-inazo"
    "ml-social"
    "wp-css-and-js-code"
    "scattered-polaroids-image-gallery"
    "zia3-rotating-words"
    "mycred-badge-plus"
    "parallax-slider"
    "reve-dynamic-widget"
    "link-designer-lite"
    "gauge-meter-slider-jquery"
    "ubuntu-ribbon"
    "news-list"
    "csv-download"
    "woo-generate-new-password-reset-link"
    "quality-driven"
    "default-post-sort"
    "lsd-simple-cache"
    "checkin"
    "marketpress-category-browser"
    "frontgallery"
    "wp-security-txt"
    "simple-table-rates-shipping-for-woocommerce"
    "officials-templates-for-sportspress"
    "solidie"
    "dob-easy-shortcoder"
    "bbp-topic-like-button"
    "wp-adrom-newsletter"
    "signups"
    "redevoke-sampath-paycorp-payment-gateway-paycorp"
    "umnico-live-chat"
    "uk-tax-and-mot-checker"
    "smartarget-viber-contact-us"
    "myanalytics"
    "wplb-widget-total"
    "vulnerabilities-check"
    "wpnativeapps"
    "list-my-posts"
    "superrss"
    "accumulus-subscription-commerce"
    "wotnot"
    "webico-timline-flatsome-addons"
    "edd-search"
    "gp"
    "notify-update-par-jm-crea"
    "woo-payworks-payment-gateway"
    "simply-map-me"
    "float-faq"
    "yo-cookie"
    "woocommerce-w3c-digital-data-layer"
    "aw-skr"
    "lianaautomation-gf"
    "mijireh-checkout-for-gravity-forms"
    "gf-cloud"
    "hizzle-slideshows"
    "wp-virtualtour"
    "widget-styler"
    "novel-navigation-links"
    "zim-airtime"
    "samply"
    "random-auto-featured-image"
    "mycookie-gdpr-compliance"
    "gm-import"
    "quick-tags"
    "custom-page-links"
    "wc-aarin-pix"
    "ogpanic"
    "signature-field-for-elementor-forms"
    "disable-trash"
    "callback"
    "bs-maps-google-map-and-leaflet-map-for-elementor-and-wpbakery"
    "easy-popup-maker"
    "protect-rss"
    "better-serbian-search"
    "secure-access"
    "advanced-password-security"
    "lj-tag-parser"
    "wpr-admin-amplify"
    "framed-slideshow-gallery"
    "logo-carousel-slider-wp"
    "echbay-for-flatsome"
    "verifiedvisitors"
    "sync-feedly"
    "freeze"
    "pepro-cf7-sms-notifier"
    "user-password-reset"
    "user-referral-free"
    "yetix-request-form"
    "redirect-on-first-login"
    "hide-wp-front-admin-bar"
    "wp-rest-api-customizer"
    "cmobile-christmas-calendar"
    "year-updater"
    "universal-icons"
    "shipping-countdown-for-woocommerce"
    "ngcareers"
    "weluka-lite"
    "login-token"
    "comment-form-wp"
    "acf-feeds-for-gravity-forms"
    "disable-editor-by-1-click"
    "disable-password-changed-notifications"
    "futurama-quote-generator"
    "islamic-database"
    "awesome-arrow-navigation"
    "amp-revolution"
    "social-header-meta"
    "f13-google-maps-shortcode"
    "combidesk-quickbooks"
    "rotating-hero-image"
    "wp-dream-carousel"
    "wp-imgur-extra"
    "codecorun-other-installation-details"
    "ainsys-integrations-framework-connector"
    "ipros24-google-translate-widget"
    "uploads-for-woocommerce"
    "htp-smtp"
    "mowomo-variable-fonts"
    "the-board"
    "consentforads"
    "mklasens-faq"
    "grisha-gplus-gallery"
    "lh-recover-password"
    "sesamy"
    "nft-galleries"
    "check-missing-featured-images"
    "ajaxify-wp-post-comment-form"
    "woo-sendy-subscriptions"
    "wp-hide-that"
    "no-google-fonts"
    "change-wp-cron-request-url"
    "focus-object-cache"
    "tsu-popup"
    "twitterply-for-webmasters"
    "compare-hosting-performance"
    "clear-widget"
    "clocksky"
    "ns-recover-abandoned-cart"
    "multi-admin-emails"
    "shopperapproved-reviews"
    "lean-wp-engine-staging-theme"
    "adspirit"
    "hiringthing-job-listings"
    "better-time-based-greeting-widget"
    "press-this-auto-close"
    "chatterbox"
    "roven-omnibus"
    "widget-for-co-authors"
    "stn-save-to-nextcloud"
    "scroll-me-up-button"
    "pousadinhas-search-widget"
    "yeloni-customizable-popup-for-mailchimp"
    "img-custom-post-types"
    "slug-accents-replacer"
    "private-feed-key"
    "2cpay"
    "dashboard-widgets"
    "comment-link-moderation-whitelist"
    "epic-tap-widgets"
    "dl-block-right-mouse-button"
    "box-tracker"
    "adplus"
    "time-between-comments"
    "flexible-ab-results"
    "dogeapi-donate-widget"
    "wp-google-speed-insight"
    "pleasant-viewer"
    "mojuredfiscalization"
    "manual-payment-gateway-paypal"
    "simple-seo-criteria-check"
    "kk-blog-card"
    "shopwedo-easyshipper"
    "acquaint-slick-slider"
    "social-handles"
    "kenzap-blog"
    "jb-nice-scroll"
    "embed-swagger-ui"
    "sort-settings-menu"
    "dashboard-wiget"
    "full-width-distraction-free-writing"
    "web-video-recorder"
    "flat-twitter"
    "nusvg"
    "aklamator-float-video-on-your-blog"
    "cf7-mobile-notification"
    "yablog"
    "wpcj-chimp"
    "wp-css-generator"
    "post-switch"
    "viversum-mondphase"
    "restore-admin-header"
    "wp-e-commerce-region-based-shipping-for-australia-states"
    "ga-authors"
    "mint-bird-feeder"
    "event-countdown"
    "redirect-attachment-pages"
    "numeric-slugs"
    "quick-edit"
    "content-analytics"
    "monk"
    "wp-maintenance-vek"
    "data-generator"
    "dx-getty-images-oembed"
    "wp-tutorial-maker"
    "make-clickable-tweet"
    "featured-products-by-category"
    "simple-audioplayer"
    "copywriting-cz"
    "server-info-wp"
    "bg-church-memos"
    "awesome-scroll-to-top"
    "shared-vision-light"
    "zem-stl-viewer"
    "tcbd-wp-admin-bar-hide"
    "aweber-params-shortcode"
    "audio-envelope"
    "tracktodate"
    "rs-change-howdy-verbiage"
    "visit-notifications"
    "ltd-tickets"
    "comprehensive-appearance-admin"
    "bytecoder-post-ticker"
    "pac-weekly-timetable"
    "shopeo-analytics"
    "add-device-type-to-body-class"
    "ep4-more-embeds"
    "totalform"
    "ht-call-now"
    "manifold-google-maps"
    "popup-zyrex"
    "wp-media-assistant"
    "big-blog-map"
    "wf-popup-menu"
    "wp-scheduled-read-only"
    "vd-ratings"
    "rocketr-payment-gateway-for-woocommerce"
    "bbggooglemaps"
    "my-two-cents"
    "behind-closed-doors"
    "wp-link-pages-extended"
    "secured-wp"
    "quick-bulk-tags-creator"
    "seo-keyword-emphasis"
    "dark-mode-for-twenty-nineteen"
    "psi-meta"
    "wp-smartappbanner"
    "searchplus"
    "outshifter-export"
    "fine-dashboard-client"
    "nice-slider"
    "simple-word-counter"
    "salespanel"
    "whats-new-popup-generator"
    "woo-dhl-tracking-form"
    "shipbubble"
    "wc-frequently-purchased-together"
    "paragraph-level-ids"
    "anti-tor"
    "kings-different-content-for-members"
    "wp-featured-entries"
    "page-wise-gallery"
    "2-factor"
    "affiliate-notice-manager"
    "archive-akkordion"
    "yamato-atobarai-for-woo"
    "ultimate-icon-shortcodes"
    "dirittopratico"
    "affiliasale"
    "lh-paragraph-ids"
    "contact-form-shortcode-ajax"
    "custom-recovery-mode-email"
    "pattern-css"
    "include-content-by-shortcode"
    "cpt-to-map-store"
    "ot-admin-theme"
    "nutsforpress-restricted-contents"
    "wp-owner-mark"
    "allgrainbeer"
    "fl3r-accessibility-suite"
    "embed-googledrive-audios"
    "invoiceboo-invoices-for-woocommerce"
    "pronamic-google-conversion"
    "a3-user-importer"
    "senseios-careers"
    "wp-users-list-widget"
    "accounting-records-copywriter"
    "logger-for-wp-mail-smtp"
    "quizad"
    "redirect-modal-based-on-country"
    "reachlocal-convertcontacts"
    "popup-zen"
    "responsive-containers"
    "jam-taxonomy-image"
    "einstein-quotes"
    "advanced-term-fields-colors"
    "event-alley"
    "authors-list-based-on-recent-posts"
    "store-central-deliveries"
    "extend-theme-cusotomizer"
    "content-gallery-slider"
    "welcome-mobile"
    "change-autosave-interval"
    "smartarget-social-contact-us"
    "edit-next"
    "kenzap-stats"
    "word-freshener"
    "podinbox-accept-voice-messages-on-your-website"
    "sorting-option-in-network-search-for-buddyboss"
    "words-content"
    "playcz-top-radios"
    "amumu-naver-searchbar"
    "scud-the-shortcode-disabler"
    "wing-forms"
    "hootsy"
    "wp-tipi"
    "keyboard-save"
    "ruven-themes-gallery"
    "basic-recent-commented-posts-widget"
    "login-attempt-limit"
    "auto-trash-delete"
    "presets"
    "wpcl-beaver-extender"
    "hr-scroll-top"
    "ai-seo-translator"
    "lightning-payment-gateway-lnbits"
    "prayer-times-by-aladhan"
    "tekserve-single-post-shortcode"
    "lastweets"
    "icanwp-reservation-form-connector-for-choice-hotels"
    "bbp-tweet"
    "bytheway"
    "trail-passion"
    "atompub"
    "block-referers"
    "parole-chiave-in-evidenza"
    "contact-button"
    "contributor-notifications"
    "add-html-in-url"
    "additional-charge"
    "taknalogy-reviews"
    "keywords-by-datadump"
    "wp-romaniachat"
    "woo-image-flipper"
    "text-replacer"
    "simple-certain-time-to-show-content"
    "yalw"
    "rest-console-embed"
    "media-checkboard"
    "geotheme-advance-search-widget"
    "ss-device-detector"
    "post-admin-view-count"
    "selective-reading"
    "resolve-for-woocommerce"
    "autotag-posts-by-shift1"
    "admin-right-click-menu"
    "bitbucket-issues"
    "cf7-text-field-size-addon"
    "sideup-ksa"
    "teg-wp-dialog"
    "change-debug-log-location"
    "woo-cheetahpay-payment-gateway"
    "gear5"
    "reach-me"
    "horizontal-tabs"
    "ob-contact-form"
    "c4d-post-show"
    "aspose-cloud-email-to-post"
    "notification-master"
    "digital-asset-manager"
    "traveledmap-embeded-map"
    "ithink-shipping"
    "fancy-xiami"
    "ac-simple-post-widget"
    "wp-tagman"
    "meteoweather"
    "ab-post-view-counter"
    "wp-search-with-algolia-bogo-extension"
    "ruby-help-desk"
    "repeater-for-elementor"
    "kb-woocommerce-braspress"
    "tfcarousel-box-addon-for-elementor"
    "lw-mwp-tools"
    "smp-simple-poll"
    "ultimate-twitter-feed"
    "last-tap-events"
    "night-traffic-light"
    "picturefill-fix-for-woocommerce"
    "apprised"
    "shopweltde-widget"
    "woocommerce-teams"
    "cloud-rebue-wpsms"
    "cashtippr-woocommerce-addon"
    "orders-filter-in-my-account"
    "picdefense-io-image-copyright-risk-checker"
    "woocommerce-bgn"
    "wp-post-demo"
    "eazy-css-slider"
    "equipe-for-wordpress"
    "tidy-archives"
    "salat-time"
    "vp-shipping-rate"
    "inline-video-shortcodes"
    "age-shortcodes"
    "practicepulse-tools"
    "beam-one-click-checkout"
    "awesome-protfolio"
    "site-language-definition"
    "mmfilesi-random-post"
    "advanced-custom-fields-menu-field"
    "in-browser-image-compression"
    "wp-recently-viewed"
    "pages-from-a-category"
    "causes"
    "online-billing-service"
    "fixed-image-all-position-drag-and-drop"
    "ruven-themes-portfolio"
    "siteglue"
    "youtube-poster"
    "customize-woo"
    "coupons"
    "sgdiet-tdee-calculator"
    "cloudstitch"
    "my-responsive-testimonial"
    "visit-email-by-systems-mit-ltd"
    "custom-woo-cart-button"
    "simple-digital-clock"
    "stellissimo-serp"
    "dynamic-cloudinary"
    "auto-tagger-for-amazon"
    "admire-extra"
    "flexible-pdf"
    "internet4associations-single-sign-on"
    "caramelopay"
    "wp-list-pages-tweaks"
    "dhivehi-keyboard"
    "infocob-crm-products"
    "ct-optimization"
    "starter-blog-templates-for-faith-blog"
    "pm-truncated-recent-posts"
    "mm-dashboard-sharing"
    "speedaf-express-for-woocommerce"
    "pitta-migration"
    "sm00sh-for-sociable-1"
    "cleio-toolbox"
    "pbp-gf-bd-address"
    "notification-bar-v"
    "contenido-del-dia"
    "lh-profile-page"
    "doko-box-builder"
    "poper"
    "contact-form-counter"
    "particles-backgrounds-addon-for-wpbakery-page-builder-lite"
    "admin-email-address-changer"
    "post-type-manager"
    "tp-product-tooltip"
    "add-file-version-afv"
    "landing-page-settings-for-genesis"
    "golf-tracker"
    "awesome-wp-responsive-slider"
    "seize-the-day"
    "greek-namedays-widget"
    "theme-powerkit"
    "advanced-google-recaptcha-for-woocommerce"
    "dn-shipping-by-weight"
    "wp-one-login"
    "eg-attachments-human-o2-icons"
    "woocommerce-category-rating"
    "local-gajs"
    "details-king-pro"
    "adminbar-remover"
    "acf-yandex-maps-field"
    "simplest-analytics"
    "widgetkits"
    "dropahint-integration"
    "wp-html-mail-give"
    "snoobi-tracking"
    "mif-bp-customizer"
    "readme-generator"
    "fine-dashboard-source"
    "b-locator"
    "subsbase-integration"
    "website-accessibility-audit-checker"
    "wp-get-directions"
    "gateway-aqayepardakht-easy-digital-downloads"
    "serve_static"
    "forum-permissions-bbpress"
    "jhakkas-elements"
    "f13-github-mini-profile-widget"
    "db-signatures"
    "user-dashboard-notifications"
    "styles-library"
    "wc-shipmondo-shipping"
    "mfs-post-viewer"
    "sr-piechirt-wp"
    "wftda-rankings-widget"
    "newpath-wildapricot-press"
    "dropshipping-with-ebay-for-woocommerce"
    "lsw-organize-drafts"
    "lock-bad-user"
    "yogo-booking"
    "easy-anti-spam-bots"
    "map-my-locations"
    "shortcode-get-child-list"
    "ez-done-file-manager"
    "get-terms-name-like"
    "calendario-runnerplace"
    "vp-slider"
    "wp-real-ip-based-access-control"
    "comic-rocket-ad-network-widget"
    "rcp-vat"
    "printdoors-for-woocommerce"
    "stop-spamco"
    "search-boxes-integration-for-booking-affiliates"
    "gsy-export-posts-to-pdf"
    "show-external-links"
    "blogtal-trackback"
    "zipp-chat"
    "nodeless-paywall"
    "advanced-images-gallery-with-lightbox"
    "wp-search-keyword-highlight"
    "wp-jquery-spam"
    "gallery-made-easy"
    "wishlist-member-api-testing"
    "wp-uninstaller-by-azed"
    "cite-references"
    "bogoxlib"
    "yalst-live-chat"
    "c4d-woo-compare"
    "sama-payment-gateway"
    "disable-css-js-cache"
    "borica-payments"
    "language-saver-for-splash-pages-using-wpml"
    "wp-sellfy-master"
    "byconsole-greetingcard"
    "ssl-checker"
    "hannan-woocommerce-authorizenet-aim-payment-gateway"
    "rbs-remote-dashboard-welcome"
    "force-members-logon"
    "wp-metrize-icons"
    "afables"
    "wp-foursquare"
    "adjust-users-screen"
    "multi-roles-vendor"
    "snufel-free-guest-post"
    "wc-block-emails"
    "keywords-cloud"
    "wine-club"
    "ais-ip-blocker"
    "bangla-comment"
    "wpfuturecal"
    "zool-viral-ads"
    "easy-user-tags"
    "apa-banner-slider"
    "duminex-invoice"
    "ultimate-membership-pro-paystack"
    "addiction-recovery-connector"
    "jobpass"
    "wp-stripe-cart"
    "ultima-clock-widget"
    "anonymous-comments"
    "tinyratings"
    "wc-subscription-report-lite"
    "all-posts-default-cat"
    "easy-collapse-accordion"
    "comment-moderation-highlighter"
    "rv-auto-featured-image"
    "lh-logged-in-static-frontpage"
    "wordpen"
    "sell-ads"
    "rss-desktop-notifications"
    "bvalidator"
    "feed-back"
    "cf7save-extension"
    "show-your-github-activities"
    "keyring-reactions-importer"
    "comment-genius"
    "ultimate-wp-slider"
    "ach-update-woo-download-links"
    "ga-image-carousel"
    "responsivity"
    "secure-post-with-link"
    "event-organiser-ngo"
    "push-notification-sender"
    "google-url-creator"
    "yahoo-screen-embed"
    "pushninja"
    "wc-order-notification-by-category"
    "ni-country-sales-report-for-woocommerce"
    "brandy-blocks"
    "scroll-to-top-inthiscode"
    "vat-calculator-plus"
    "prevent-read-more-scroll"
    "image-merger"
    "svn-updater"
    "aspose-cloud-presentation-importer"
    "freedam-web-notices"
    "custom-admin-panel-by-2cloud"
    "wpsea-functionality"
    "sargapay"
    "eduadmin-booking-klarna-checkout"
    "easy-post-duplicator"
    "salesfire"
    "remove-wp-footer-credit"
    "redirect-anonymous-users"
    "wc-mobilpayments-card"
    "hoversignal"
    "bannerwoo"
    "beautiful-multiselect-search-lite"
    "userplus"
    "simple-woo-affiliate-tracking"
    "asset-store-publisher-contact-form"
    "infoplus-connect-for-woocommerce"
    "listagram"
    "frontend-login-and-registration-blocks"
    "easy-digital-downloads-pricing-select"
    "use-bangla-fonts"
    "quickdashboard"
    "animation-menus-highlight"
    "pocket-widget"
    "moby-rss-widget"
    "event-stream-gallery"
    "qanva-powertools-for-elementor"
    "enhanced-comment-validation"
    "honorific-buddypress-members-name"
    "social-wall-widget"
    "commenters-can-add-tags"
    "live-admin-navigation-filter"
    "soulmatch"
    "punnel-landing-page-builder"
    "quick-easy-analytics"
    "all-in-one-wc"
    "remove-p-tag-around-image"
    "hiweb-lightbox"
    "securepay-for-givewp"
    "i-dont-endorse-google"
    "pasteboard"
    "maintenance-countdown"
    "ider-login"
    "ym-contact-display"
    "prevent-users-concurrent-sign-in"
    "catna-woo-name-your-price-and-offers"
    "control-wp-core-emails"
    "elex-embed-youtube-video-gallery"
    "pushbots-web-push-notifications"
    "simple-openerp7-login"
    "code-repository"
    "liebe-ist-liebeszitat"
    "easy-csv-restaurant-menus"
    "shortcode-for-my-mitsu-estimation-form"
    "magic-post-translate"
    "oheso-version-report"
    "leadbi"
    "tracking-url-builder-for-analytics"
    "asap507-panama-shipping-api-integration"
    "wp-emo-ello"
    "the-prospect-farmer"
    "mailman-registration"
    "eazy-image-slider-block"
    "keybe-widget-chat"
    "shop-3d"
    "custom-comment-links"
    "mi13-like"
    "disable-comments-with-google-authorship"
    "scuba-logger"
    "monoslideshow"
    "listify-multi-location-for-wp-job-manager"
    "bubuku-disable-related-videos"
    "wc-qpaypro"
    "dismiss-welcome-nag"
    "everyday-hero-widget"
    "category-contributors"
    "free-wp-booster-by-ads-pro"
    "wp-social-blocks"
    "showgplus"
    "hot-tags"
    "infinite-related-next-post-manager"
    "easexport-gravity-forms-scheduled-entries-export"
    "ai-chatbot-easy-integration"
    "all-custom-fields-groups"
    "pxl-tools"
    "valutni-kursove"
    "panomity-wp-cache"
    "apollo-site-tools"
    "login-with-qr"
    "cf7-2checkout"
    "explara-events"
    "sobex-tech"
    "showhide-shortcode"
    "lineate"
    "flexible-hreview"
    "gravitation-brands"
    "plugins-site-menu-link"
    "security-assassin"
    "cms-product-zoom-for-woocommerce"
    "product-view-count"
    "permalink-history"
    "rollbar-logging"
    "imageurlreturner"
    "glamour"
    "mz-newsticker"
    "mapbb"
    "wind-speed-converter"
    "kaya-login-captcha"
    "wc-paybox-payment-gateway"
    "profile-views-for-ultimate-member"
    "ai-alt-text-generator"
    "maxicharts-timeline"
    "recaptcha-protected-downloads"
    "naiba-coming-soon"
    "my-simple-form"
    "comparatore-prezzi-woocommerce"
    "smntcs-theme-list-view"
    "enable-turnstile-cloudflare-for-gravity-forms"
    "show-current-width"
    "wp-live-debug"
    "hasoffers"
    "get-noticed-horizontal-subscribe-bar"
    "c4d-woo-category"
    "clever-tracking"
    "contextual-category-widget"
    "rss-via-shortcode"
    "rentpress-amenities-manager-add-on"
    "lewe-jira-connector"
    "whippet"
    "bms-qr-code"
    "c4d-woo-category-grid-zoom"
    "wp-sponsorship"
    "no-spam-in-backend"
    "custom-social-media-widget"
    "integrate-nekorekten-wc"
    "ar-model-viewer-for-woocommerce"
    "geekseller"
    "query-generator"
    "costa-rica-currency-exchange-rate"
    "tapstream-app-banners"
    "l7-display-posts"
    "wc-multi-currency-switcher"
    "seraphinite-downloads-stats"
    "wp-store-lite"
    "shortcodes-in-titles"
    "opes-wp-ads-manager"
    "text-popover"
    "thumbnail-hover-menu-for-elementor"
    "mp3-quran"
    "wp-angular"
    "shoppable"
    "withings-scale"
    "wp-rupeefont"
    "wp-autotrack"
    "current-theme-body-class"
    "wp-amara-shortcode"
    "experto-cta-widget"
    "polskie-eplatnosci-online-payment-gateway-for-woocommerce"
    "ivrita"
    "mobile-redirection-for-pages-and-posts"
    "ga-code-visibility"
    "crm2go"
    "alobaidi-gallery"
    "ojama-flying-sankocho"
    "hello-motivation"
    "answering-contact-form-faq-page-add-on"
    "blue-billywig"
    "admail-list-builder-signup-forms"
    "bot-libre-chatbot"
    "wp-simplepasswordchange"
    "webinara"
    "inline-css-block-gutenberg"
    "world-oil-supply-clock"
    "rs-social-sidebar"
    "melonpan-block-post-list"
    "export-customers-from-woo-to-csv"
    "invelity-gls-connect"
    "flaming-forms"
    "d2l-wp-color-picker-enhancement"
    "root-category-recent-posts"
    "change-comment-parent"
    "custom-post-links"
    "wajeez-otd"
    "electric-migration"
    "mhcode-wp-bootstrap-nav"
    "tcbd-alert"
    "rebrandly-domain-redirect"
    "yo-gallery"
    "mnotifysms-for-woo"
    "themereps-helper"
    "neptune-style-element"
    "dashboard-clock"
    "gp-remove-projects-from-breadcrumbs"
    "image-gallery-horizontal"
    "nouw-css"
    "patron-memberships-patreon-connect"
    "restrict-contributors-from-scheduled-posts"
    "f13-github-repo-shortcode"
    "homie"
    "better-video-playlist"
    "combined-search"
    "r-nice-scroll"
    "autocomplete-for-tinymce"
    "cricket-preloader"
    "wp-lucky-search"
    "authorize-ip-address"
    "magic-inliner"
    "wc-checkout-custom-billing-phone-field"
    "datetime-picker"
    "simple-content-adder"
    "recordbrowser"
    "login-external-redirect"
    "ensighten"
    "popup-tb"
    "small-wp-security"
    "sc-vue"
    "wp-simple-maintenance-mode"
    "gmo-widget-custom"
    "simple-search-rewrite"
    "swiftpost"
    "push-monkey-light"
    "comments-archive"
    "update-your-footer-wp"
    "storecontrl-wp-connection"
    "prevent-password-reuse"
    "sortable-block"
    "carbon-fields-qtranslate"
    "no-english-comments"
    "woocommerce-userfollowup"
    "crunchbase-api-widget"
    "remove-super-admin-from-user-list-table"
    "simple-custom-vote"
    "bootstrap-slider-by-themescode"
    "fullscreen-video-embed"
    "calder-svg"
    "acf-wpml-theme-options"
    "simple-noai-and-noimageai"
    "fyyd-podcast-shortcodes"
    "asciiplayer"
    "better-captcha"
    "dqh-series-system"
    "nearby-places-search"
    "mamurjor-student-result"
    "simdex-toggle-wp-admin-notifications"
    "woocommerce-aways-show-add-to-cart"
    "ausmed-document-button"
    "rb-site-social-links"
    "ecommerce-addon"
    "image-plus"
    "connect-lifterlms-to-discord"
    "smugmug-insert"
    "template-dictionary"
    "banner-display-thumbnail"
    "gravity-to-solve360"
    "wp-developer-toolkit"
    "attrace"
    "dx-github-badge"
    "wtg-csv-exporter"
    "simplify-post-taxonomy"
    "debug-log-parser"
    "hey-cdp"
    "wc-shipping-option-by-user-role"
    "simple-analytics-tag-beta"
    "wava-payment"
    "otp-by-email"
    "cpa-offerwall"
    "wp-revealer"
    "kh-easy-user-settings"
    "rotem-mortgage-calculator"
    "oceanpayment-creditcard-gateway"
    "quickteller-business-payment"
    "wc-image-swapper"
    "seo-custom-fields"
    "wp-front-end-login"
    "ad-short"
    "zencoder-video"
    "shift8-geoip-location"
    "chris-force-password-reset"
    "gmt-post-ids"
    "easy-video-call"
    "link-to-wp-files"
    "no-stock-notice"
    "wp-identity"
    "collection"
    "counters-integration"
    "wp-image-box-overly"
    "wp-valid-email"
    "cute-scroll-to-top"
    "te-icecast-station-info"
    "all-in-one-wp-content-security"
    "everviz"
    "responsive-pagination"
    "mcavoy"
    "aceblocks"
    "quick-add-child"
    "rate-limiting-for-contact-form-7"
    "sightmill-nps"
    "image-automatic-alt-text-and-caption"
    "hr-press-lite"
    "animated-accordion"
    "aklamator-twitch-videofloat"
    "custom-cms"
    "businessmonitor-reviewfeed"
    "tornevall-networks-dnsbl-implementation"
    "wp-bitbucket"
    "admin-column-view-selector"
    "werecover-wendi"
    "ra-mod-multibyt-slug"
    "wp-linkpress-lite"
    "custom-css-for-pages"
    "banner-image-for-post-and-page"
    "botscout-comment-protection"
    "woocommerce-mesasix-stripe-payment-extension"
    "aml-league"
    "payware-mobile-payments-for-woocommerce"
    "cryptanil-payment-gateway"
    "change-out-of-stock-text-for-woocommerce"
    "dynamic-custom-header-replacement"
    "evadav"
    "wp-systempay"
    "flickr-over-gfw"
    "traditores-in-one-year"
    "coming-soon-tmc"
    "amadiscount"
    "floating-cart-for-woo"
    "rest-cent-donations"
    "anyclip-media"
    "delete-default-post"
    "mxr-easy-embed-wall"
    "3d-xr-library"
    "author-periodic-report"
    "social-fellow"
    "income-activator-referral-revenue"
    "wl-wc-newsletter"
    "ezcount-paypal-ipn"
    "wc-bulk-buyer-discounts"
    "wp-coffeescript"
    "color-div-box"
    "woo-payment-gateway-bitcoinus"
    "nagishly"
    "simple-sticky-header-menu"
    "s-dev-seo"
    "simple-event-summary-for-sportspress"
    "recipe-creator"
    "wp-api-fftt"
    "travel-maps"
    "bang-syslog"
    "blaatschaap-sso-vatsim"
    "makhlas"
    "private-user-comments"
    "wfs-simple-contact"
    "notifylk-sms-for-woocommerce"
    "organizing"
    "sypher-cookie-consent"
    "floating-cart-woocommerce"
    "haremo-social-screenshots"
    "wp-hidetext"
    "category-and-tag-feeds"
    "agin-crm-sending-leads"
    "wp-dlm-faq"
    "istk-add-on"
    "doublewp-tcpdf-wrapper"
    "woo-bulk-email"
    "kenzap-brands"
    "woo-google-analytics-enhanced-ecommerce"
    "gna-miscellaneous"
    "gc-yml-creator"
    "markeking-floating-cart"
    "love-brave-browser"
    "awesome-capital-letter"
    "woo-shortcode-popup"
    "fix-email-return-path"
    "wpbatch-awesome-slider"
    "accept-payments-wp"
    "climate-tagger"
    "sp-random-hello-bar"
    "freespee-call-tracking"
    "pray-time"
    "rundiz-downloads"
    "subscribe-google-groups"
    "damedia-giglist"
    "vistrom-media-library-categories"
    "inline-reveal-js"
    "lingoeducation"
    "subordinate-post-type-helpers"
    "os-pricing-tables"
    "gv-excel-export"
    "hexa-team-responsive-grid-free"
    "enquir3-case-studies"
    "whale-kit"
    "ractivejs"
    "sheeble-share-widget"
    "basic-google-authorship"
    "cvw-songkick-widget"
    "pe-theme-elements-info"
    "trancelantic-playlist"
    "delete-post"
    "evgeny-muravjev-typograph"
    "autoclaimer"
    "sb-comment"
    "convert-docx2post"
    "complex-tv-embed"
    "nearst-for-woocommerce"
    "registar-nestalih"
    "avp-website-solution"
    "paste-analytics"
    "mp-automate-lite-for-mailpoet"
    "id4me"
    "wao-io-cache-control"
    "garrett-county-planning-tool-gcpt"
    "ws-redirect-wp"
    "lumeer-embed"
    "wp-css-version-history"
    "wc-thank-you-page"
    "gravity-all-fields-plain"
    "simple-football-score-board"
    "3d-menu-awesome"
    "readability-index"
    "dizzyjam"
    "extended-api-xml-rpc"
    "calculation-shipping"
    "rk-hreview-for-wp"
    "custom-spinner-for-woocommerce"
    "wc-variations-generator"
    "awesome-mw-wp-form-styles"
    "ni-purchase-orderpo-for-woocommerce"
    "protected-registration"
    "cc-redirects"
    "securepay-for-gravityforms"
    "plus-features-for-advanced-custom-fields"
    "wpciteulike"
    "dinatur"
    "expertfile-expert-content-templates"
    "iw-profile"
    "rokgallery-pages-list"
    "business-reviews"
    "yoopay-woocommerce-gateway"
    "show-more-p2"
    "events-manager-add-on-multisite-mail-settings"
    "taxonomy-chain-menu"
    "additional-js"
    "categories-expiration-date"
    "santucommerce"
    "wc-delivery-lpost"
    "cc-travel"
    "zone-marker"
    "logic-hop-woocommerce-add-on"
    "canvasflow"
    "easy-player"
    "qcomment"
    "plugin-version-control"
    "mw-theme-uri-shortcode"
    "laiser-tag-plus"
    "yourls-link-creator-bulk-generate"
    "olympus-featured-posts-widget"
    "tc-flexslider"
    "family-wiki"
    "vnshipping-for-woocommerce"
    "scratchpad"
    "altocloud-analytics-communications-for-woocommerce"
    "forceprivate"
    "trigger-happy"
    "movable-mobile-menu"
    "display-terms-shortcode"
    "visual-inspector-sync"
    "zanto-country-detector"
    "go-copy-active-plugins"
    "simple-fading-testimonials-widget"
    "shareboost"
    "container-block"
    "addfunc-ids"
    "bangladesh-district-upazilla-dropdown-list-for-contact-form-7"
    "ald-login-page"
    "ivalt"
    "wc-max-quantity"
    "customize-plugin-manager"
    "halloween-box"
    "wp-lever"
    "overwrite-it"
    "no-premium"
    "wp-dofollow-comment-links"
    "full-site-cache-cf"
    "cactus-info-slider"
    "woo-multistep-checkout-like-magento"
    "tribe-events-oembed"
    "press-release-newsroom"
    "webar"
    "woo-paytriot-gateway"
    "crankwheel"
    "kratos-anti-spam"
    "awesome-youtube-embed"
    "wp-client-logo-carousel-list"
    "page-metrics"
    "ai-content-writer-generator"
    "tuxquote"
    "better-reply"
    "wp-droid"
    "social-feeds-for-elementor"
    "yamuslim-prayer-time-wordpress-widget"
    "external-outbonding-links"
    "kg-inline-code"
    "mr-utils"
    "cybersoldier"
    "auto-privacy-docs"
    "vrpress"
    "selar-co-widget"
    "twenty-fifteen-disqus-style"
    "interactive-map-of-florida"
    "side-cart-plus-for-woocommerce"
    "browse-topic"
    "cookie-connector-for-themer"
    "get-noticed-our-blog"
    "gbs-product-catalog"
    "basemapper"
    "plugin-health-check"
    "custom-posts-builder"
    "wp-drinking-age"
    "wp-ignitor"
    "sell-media-affiliate"
    "customize-comments"
    "simple-learn-japanese-quiz"
    "auto-refresh-post-page"
    "csp-antsst"
    "widgets-for-thingspeak"
    "remove-nofollow-commenter-link"
    "members-only-shop-for-patreon-woocommerce"
    "wishlist-with-hearts"
    "instant-locations"
    "zodiac-sign-information-widget"
    "simple-testimonial"
    "hylsay-text-reading"
)

# Define user agents with weights
declare -A USER_AGENTS
USER_AGENTS=(
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"]=5
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"]=7
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"]=6
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36 Edg/91.0.864.54"]=5
    ["Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 OPR/77.0.4054.277"]=3
    ["Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (iPad; CPU OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Vivaldi/4.0"]=1
    ["Mozilla/5.0 (Android 11; Mobile; rv:68.0) Gecko/68.0 Firefox/88.0"]=1
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"]=15
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/534.36"]=12
)

CLOSED_PLUGINS_FILE="${WORDPRESS_WORKDIR}/closed_plugins.txt"
LAST_VERSION_FILE="${WORDPRESS_WORKDIR}/last_versions.txt"
PARALLEL_JOBS=1

DOWNLOAD_ALL_PLUGINS='n'
LIST_ONLY='n'
ALL_PLUGINS_FILE="${WORDPRESS_WORKDIR}/wp-plugin-svn-list.txt"

DELAY_DOWNLOADS='n'
DELAY_DURATION=5

FORCE_UPDATE='n'
CACHE_ONLY='n'

mkdir -p "$WORDPRESS_WORKDIR" "$MIRROR_DIR" "$LOGS_DIR"
DEBUG_MODE=0

while getopts "p:dalD:t:fc" opt; do
    case ${opt} in
        p ) PARALLEL_JOBS=$OPTARG ;;
        d ) DEBUG_MODE=1 ;;
        a ) DOWNLOAD_ALL_PLUGINS='y' ;;
        l ) LIST_ONLY='y' ;;
        D ) DELAY_DOWNLOADS=$OPTARG ;;
        t ) DELAY_DURATION=$OPTARG ;;
        f ) FORCE_UPDATE='y' ;;
        c ) CACHE_ONLY='y' ;;    # New option for cache-only
        \? ) echo "Usage: $0 [-p PARALLEL_JOBS] [-d] [-a] [-l] [-D DELAY_DOWNLOADS] [-t DELAY_DURATION] [-f] [-c]" 1>&2; exit 1 ;;
    esac
done

debug_log() {
    if [ "$DEBUG_MODE" -eq 1 ]; then
        echo "[DEBUG] $1" >&2
    fi
}

get_random_user_agent() {
    echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
}

get_latest_version_and_download_link() {
    local plugin=$1
    debug_log "Checking latest version and download link for $plugin"
    
    local api_url="https://api.wordpress.org/plugins/info/1.0/${plugin}.json"
    local user_agent=$(get_random_user_agent)
    local api_response=$(curl -s -H "User-Agent: $user_agent" "$api_url")
    
    if echo "$api_response" | jq -e '.error' >/dev/null; then
        local error_message=$(echo "$api_response" | jq -r '.error')
        if [ "$error_message" = "closed" ]; then
            echo "closed"
            return 2
        else
        echo "Error: $error_message for plugin $plugin" >&2
        return 1
        fi
    fi
    
    local version=$(echo "$api_response" | jq -r '.version // empty')
    local download_link=$(echo "$api_response" | jq -r '.download_link // empty')
    
    if [ -n "$version" ] && [ -n "$download_link" ]; then
        echo "$version $download_link"
        return 0
    else
        echo "Error: Cannot fetch version or download link for $plugin" >&2
        return 1
    fi
}

download_plugin() {
    local plugin=$1
    local version=$2
    local api_download_link=$3
    local output_file="${MIRROR_DIR}/${plugin}.${version}.zip"
    local header_file="${LOGS_DIR}/${plugin}.${version}.headers"
    local constructed_download_link="${DOWNLOAD_BASE_URL}/${plugin}.${version}.zip"
    local download_link

    if [ "$DEBUG_MODE" -eq 1 ]; then
        debug_log "API-provided download link for $plugin: $api_download_link"
        debug_log "Constructed download link for $plugin: $constructed_download_link"
    fi

    if [ "$DOWNLOAD_LINK_API" == 'y' ] && [ -n "$api_download_link" ]; then
        download_link="$api_download_link"
        debug_log "Using API-provided download link for $plugin: $download_link"
    else
        download_link="$constructed_download_link"
        debug_log "Using constructed download link for $plugin: $download_link"
    fi

    debug_log "Downloading $plugin version $version through Cloudflare Worker"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)
    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o /dev/null "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    else
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o "$output_file" "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    fi

    if [ $? -eq 0 ]; then
        if [ "$CACHE_ONLY" == 'y' ]; then
            debug_log "Plugin $plugin version $version cached successfully."
            return 0
        fi

        local file_size=$(stat -c%s "$output_file")
        if [ "$file_size" -lt 1000 ]; then
            echo "Error: Downloaded file for $plugin is too small (${file_size} bytes). Possible download issue." >&2
            return 1
        fi

        local source=$(grep -i "X-Source:" "$header_file" | cut -d' ' -f2 | tr -d '\r')
        if [ "$source" == "R2" ]; then
            debug_log "Successfully downloaded $plugin version $version from R2 storage"
        elif [ "$source" == "WordPress" ]; then
            debug_log "Successfully downloaded $plugin version $version from WordPress"
            debug_log "R2 bucket saving for plugin zip occurred"
        else
            debug_log "Skipped download for $plugin $version zip (already exists locally)"
        fi

        return 0
    else
        echo "Error: Failed to download $plugin version $version" >&2
        return 1
    fi
}

save_plugin_info() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.json"

    debug_log "Saving plugin json metadata for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying metadata download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    if [ "$CACHE_ONLY" == 'y' ]; then
        # When in cache-only mode, output to /dev/null
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin metadata for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache json metadata for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            if [ "$source" = "R2" ]; then
                debug_log "json metadata for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "json metadata for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin json occurred"
            else
                debug_log "json metadata for $plugin version $version saved (json metadata file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save json metadata for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

fetch_and_save_checksums() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.checksums.json"

    debug_log "Fetching and saving checksums for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying checksums download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    debug_log "Sending request to Worker for checksums: CF_WORKER_URL?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"

    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin checksums for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache checksums for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        debug_log "Received response with status code: $status_code"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            debug_log "Response source: $source"
            if [ "$source" = "R2" ]; then
                debug_log "Checksums for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "Checksums for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin checksums occurred"
            else
                debug_log "Checksums for $plugin version $version saved (checksums file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save checksums for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

process_plugin() {
    local plugin=$1

    # Check if the plugin is already known to be closed
    if grep -q "^$plugin$" "$CLOSED_PLUGINS_FILE" 2>/dev/null; then
        echo "Plugin $plugin is known to be closed. Skipping."
        return 0
    fi

    echo "Processing plugin: $plugin"

    VERSION_AND_LINK=$(get_latest_version_and_download_link "$plugin")
    local version_check_status=$?
    
    if [ $version_check_status -eq 1 ]; then
        echo "Skipping $plugin due to version fetch error."
        return 1
    elif [ $version_check_status -eq 2 ]; then
        echo "Plugin $plugin is closed. Skipping download and processing."
        echo "$plugin" >> "$CLOSED_PLUGINS_FILE"
        if save_plugin_info "$plugin" "closed"; then
            debug_log "Successfully saved json metadata for closed plugin $plugin."
        else
            debug_log "Failed to save json metadata for closed plugin $plugin."
        fi
        return 0
    fi
    
    LATEST_VERSION=$(echo "$VERSION_AND_LINK" | cut -d' ' -f1)
    API_DOWNLOAD_LINK=$(echo "$VERSION_AND_LINK" | cut -d' ' -f2-)

    debug_log "Latest version for $plugin: $LATEST_VERSION"
    debug_log "API download link for $plugin: $API_DOWNLOAD_LINK"

    STORED_VERSION=$(grep "^$plugin" "$LAST_VERSION_FILE" | awk '{print $2}')
    debug_log "Stored version for $plugin: $STORED_VERSION"

    if [ "$CACHE_ONLY" != 'y' ] && [ "$LATEST_VERSION" == "$STORED_VERSION" ] && [ -f "${MIRROR_DIR}/${plugin}.${LATEST_VERSION}.zip" ]; then
        echo "$plugin is up-to-date and exists in mirror directory. Skipping download..."
    else
        start_time=$(date +%s.%N)

        if download_plugin "$plugin" "$LATEST_VERSION" "$API_DOWNLOAD_LINK"; then
            if [ "$CACHE_ONLY" != 'y' ]; then
                sed -i "/^$plugin/d" "$LAST_VERSION_FILE"
                echo "$plugin $LATEST_VERSION" >> "$LAST_VERSION_FILE"
            fi
            echo "Successfully processed $plugin."
        else
            echo "Error: Failed to process $plugin." >&2
        fi

        end_time=$(date +%s.%N)
        duration=$(echo "$end_time - $start_time" | bc)
        printf "Time taken for %s: %.4f seconds\n" "$plugin" "$duration"
    fi

    if save_plugin_info "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully saved json metadata for $plugin."
    else
        debug_log "Failed to save json metadata for $plugin."
    fi

    if fetch_and_save_checksums "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully fetched and saved checksums for $plugin."
    else
        debug_log "Failed to fetch and save checksums for $plugin."
    fi
}

populate_all_plugins() {
    if [ ! -f "$ALL_PLUGINS_FILE" ] || [ "$LIST_ONLY" == 'y' ]; then
        echo "Fetching list of all WordPress plugins..."
        svn list https://plugins.svn.wordpress.org/ | sed 's/\/$//g' > "$ALL_PLUGINS_FILE"
        plugin_count=$(wc -l < "$ALL_PLUGINS_FILE")
        echo "Plugin list (${plugin_count}) saved to $ALL_PLUGINS_FILE"
    fi
    
    if [ "$LIST_ONLY" == 'n' ]; then
        ALL_PLUGINS=()
        while IFS= read -r line; do
            ALL_PLUGINS+=("$line")
        done < "$ALL_PLUGINS_FILE"
        echo "Loaded ${#ALL_PLUGINS[@]} plugins."
    fi
}

if [ "$LIST_ONLY" == 'y' ]; then
    populate_all_plugins
    echo "Plugin list created. Exiting without downloading."
    exit 0
fi

if [ "$DOWNLOAD_ALL_PLUGINS" == 'y' ]; then
    populate_all_plugins
    COMBINED_PLUGINS=("${ALL_PLUGINS[@]}")
else
    if [ ! -d "$PLUGIN_DIR" ]; then
        echo "Warning: Plugin directory $PLUGIN_DIR does not exist or is invalid."
        PLUGIN_LIST=()
    else
        PLUGIN_LIST=($(ls -d "$PLUGIN_DIR"/*/ 2>/dev/null | xargs -n 1 basename))

        if [ ${#PLUGIN_LIST[@]} -eq 0 ]; then
            echo "No plugins found in $PLUGIN_DIR."
        fi
    fi

    COMBINED_PLUGINS=(${PLUGIN_LIST[@]} ${ADDITIONAL_PLUGINS[@]})
    COMBINED_PLUGINS=($(echo "${COMBINED_PLUGINS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
fi

if [ ${#COMBINED_PLUGINS[@]} -eq 0 ]; then
    echo "No plugins to download. Exiting."
    exit 0
fi

mkdir -p "$MIRROR_DIR"
touch "$LAST_VERSION_FILE"

if [ "$PARALLEL_JOBS" -gt 1 ]; then
    echo "Running in parallel with $PARALLEL_JOBS jobs..."
    # First, export all variables including USER_AGENTS
    export DOWNLOAD_BASE_URL MIRROR_DIR LAST_VERSION_FILE DEBUG_MODE DOWNLOAD_LINK_API LOGS_DIR ALL_PLUGINS_FILE DOWNLOAD_ALL_PLUGINS LIST_ONLY CF_WORKER_URL DELAY_DOWNLOADS DELAY_DURATION FORCE_UPDATE CACHE_ONLY USER_AGENTS

    # Then, export the functions
    export -f process_plugin get_latest_version_and_download_link download_plugin debug_log populate_all_plugins save_plugin_info get_random_user_agent fetch_and_save_checksums
    printf "%s\n" "${COMBINED_PLUGINS[@]}" | xargs -P $PARALLEL_JOBS -I {} bash -c 'process_plugin "$@"' _ {}
else
    for plugin in "${COMBINED_PLUGINS[@]}"; do
        process_plugin "$plugin"
    done
fi

if [ -f "$CLOSED_PLUGINS_FILE" ]; then
    echo
    echo "Closed Plugin List:"
    cat "$CLOSED_PLUGINS_FILE" | sort | uniq || true
    echo
    echo "Total closed plugins: $(wc -l < "$CLOSED_PLUGINS_FILE")"
    echo
else
    echo
    echo "No closed plugins found."
    echo
fi
echo "Plugin download process completed."
