#!/bin/bash

# Base directory (script location)
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Configurable directories
WORDPRESS_WORKDIR="${WORDPRESS_WORKDIR:-$BASE_DIR/wordpress-plugins}"
PLUGIN_DIR="${PLUGIN_DIR:-$BASE_DIR/wp-content/plugins}"
MIRROR_DIR="${MIRROR_DIR:-$BASE_DIR/mirror}"
LOGS_DIR="${LOGS_DIR:-$BASE_DIR/plugin-logs}"

# Check for CF_WORKER_URL environment variable
if [ -z "$CF_WORKER_URL" ]; then
    echo "Error: CF_WORKER_URL environment variable is not set." >&2
    exit 1
fi

DOWNLOAD_BASE_URL="https://downloads.wordpress.org/plugin"

# Other variables
DOWNLOAD_LINK_API='y'

ADDITIONAL_PLUGINS=(
    "alt-report"
    "distinct-preview"
    "wikiembedder"
    "lanyrd-splat-widget"
    "wp-post-rating"
    "cf7-required-custom-field"
    "bbp-dofollow"
    "postapanduri"
    "msy-drop-shipping"
    "career-work-with-us"
    "woocommerce-phone-payments"
    "read-a-poem-month-by-month"
    "update-post-with-exif-data"
    "synchronise-news-ticker"
    "iphods-itunes-top-products-rss-widget"
    "wp-theme-scripts"
    "ajax-contact-forms"
    "todayish-in-history"
    "gravityform-to-custom-post"
    "tsp-on-this-day"
    "wp-url-shortener"
    "comments-reactions"
    "yumjam-require-login"
    "featured-image-column-display"
    "filter-anything"
    "wp-include-posts"
    "detector"
    "mihdan-public-post-preview"
    "infocob-tracking"
    "global-custom-fields"
    "chatsystemio"
    "ac-custom-loop-shortcode"
    "add-logo-backoffice-easily"
    "hu-permalinks"
    "wp-markerboard"
    "user-links-for-wp-menus"
    "post-comment-validation"
    "wp-select-primary-category"
    "widgetized-categories"
    "indesign-random-quotes"
    "block-user-ads"
    "move-postpage-to-subsite"
    "auto-referrer"
    "sendpress-for-woocommerce"
    "wp-etherpad-lite"
    "diasposter"
    "genesis-rest-api-integration"
    "1pointmail-optinbox-for-wp"
    "prettycode"
    "wpb-woocommerce-widgets-accordion"
    "content-randomizer-free"
    "dynamic-donation"
    "add-template-for-contact-form-7"
    "wp-post-of-the-day"
    "logisnap"
    "move-nav-menu"
    "wp-guardian"
    "category-class"
    "embedy-wall"
    "easy-affiliate-cloaker"
    "block-styles"
    "email-validation-filter-for-contact-form-7"
    "cf7-progress-bar"
    "astro-woocommerce-free-gift"
    "turnupsecurity-http-headers"
    "fashe-companion"
    "octolio"
    "best2pay-payment-method-visamastercard"
    "edd-taxjar"
    "nifty-related-posts"
    "disable-media-uploader-button"
    "ddev-find-replace"
    "review-widget-addon-for-divi"
    "wc-cbk"
    "concise-antispam"
    "daily-image"
    "category-view-row-action"
    "experitus-form"
    "wp-dailymotion-video-fetcher"
    "gf-hero"
    "contentpress"
    "ngg-simple-history"
    "priceline-partner-network-official-searchbox"
    "hf-preloader-awesome"
    "wpchargebee"
    "google-image-proxy"
    "ibantest-for-woocommerce"
    "wp-microdata"
    "thermometer-for-woocommerce-crowdfunding"
    "map-visualizer"
    "secure-admin-login-with-customize"
    "youtube-xhtml-and-mobile"
    "wp-dirls"
    "bmlt-meeting-map"
    "image-hover-effects-for-elementor"
    "health-fitness-quotes-widget"
    "shift8-modal"
    "oll-cielo-checkout"
    "simple-fast-highlighter"
    "ttc-user-comment-count"
    "seedtrace-transparency"
    "shortcodes-gravity-form"
    "maniacal-maze"
    "puredevs-customer-history-for-woocommerce"
    "ics"
    "qinvoice-connect-for-gravity-forms"
    "social-media-icon"
    "content-protect-by-time-lock"
    "makeiteasy-popup"
    "widget-subtitle"
    "experience-builder"
    "kanban-ninja-forms"
    "coeur-admin-color-scheme"
    "easify-woocommerce-connector"
    "total-archive-by-fotan"
    "ssl-wireless-sms-notification"
    "qpmn-pod-by-qp-group"
    "demomentsomtres-shortcodes"
    "raven-analytics"
    "wordpress-archive-chart"
    "zillametrics-google-tag-manager"
    "simple-notification"
    "wp-shortcodes-in-widgets"
    "kuvatfi-picker"
    "casted"
    "easy-digital-downloads-payment-icons-widget"
    "boost360-for-doctors"
    "gp-additional-links"
    "gecko-grid-layout"
    "my-hello-dolly"
    "event-scheduler"
    "disable-comments-for-post-types"
    "wp-fetlife-importer"
    "wpessential-icons"
    "wc-couryier"
    "payaza"
    "tag-cloud-per-category"
    "sepa-girocode"
    "move-post"
    "code-injection"
    "woocommerce-paginate-variations"
    "lb-colorbox"
    "ajax-comment-with-sweet-alert"
    "invigor-pay-wechat-pay-for-woocommerce"
    "modify-comment-parent"
    "permissions-security-audit"
    "popup-image"
    "serbian-dinar-exchange-rates"
    "todays-posts"
    "easy-email-integration"
    "wc-expire-products"
    "bb-edition-control"
    "reviewer-rich-snippets"
    "payable-payment-gateway-for-woocommerce"
    "integration-shops-united-woocommerce"
    "nmr-strava-activities"
    "endora-lite"
    "font-zoom"
    "actus-animated-tags"
    "youtube-random-videos"
    "easy-development"
    "webmiro-bluepay-woo-addon"
    "pp-lv-feed-for-woocommerce"
    "e-shops-cart2"
    "gig-promotion-for-fiverr"
    "big-emoji-comments"
    "ecommerce-mercadopago-chile"
    "social-view"
    "aye-aye-frame"
    "surbma-jetpack-responsive-videos"
    "the-bucketlister"
    "wootoolkit"
    "wp-event-manager-migration"
    "group-category-creator"
    "ripple-by-wowmotion"
    "paperlit"
    "spr-posts-import"
    "disable-rss-feeds-and-comments"
    "payment-gateway-for-telcell"
    "megabase-calendar"
    "olalaweb-woocommerce-category-prices"
    "pdf-invoice-for-woocommerce"
    "wp-query-generator"
    "daily-hadith-widget"
    "custom-template-post"
    "e-carousel"
    "dozent-lms-certificate"
    "rb-post-views-columns"
    "steptotal"
    "post-snippet"
    "copy-nav-menu-items"
    "pebo-masonry-free"
    "sapo-feed"
    "feed2post-ircf"
    "woo-extra-fee"
    "multisite-postie-cron-creator"
    "wc-fedex-shipping"
    "wp-collectiveaccess"
    "classroom-library"
    "woo-sale-price"
    "craftgate-payment-gateway"
    "post-reading-progress"
    "getgit"
    "sitelint"
    "gust-daisy-ui"
    "dynamic-taxonomy-menu-items"
    "scare-hackers-off"
    "recipe-blocks"
    "addismap-elementor-element"
    "gsy-content-filter"
    "chat-everywhere"
    "toggle-tax-for-woocommerce"
    "notify-duplicate-title"
    "pelepay-integration-for-woocommerce"
    "masquerade"
    "gna-cate-list"
    "betting-payback-calculator"
    "my-custom-login"
    "boton-fixmedia"
    "woocommerce-invoice-sharing"
    "pars-slider"
    "dash-rewriter"
    "switch-cta-box"
    "custom-news-widget"
    "article-json-ld"
    "weeby-testimonial"
    "manchete-atual-newsfeed"
    "time-limit-for-users"
    "wc-category-description-jump-under-products"
    "primary-key-fixer"
    "dadevarzan-wp-video"
    "advanced-slider-for-elementor"
    "iats-online-forms"
    "global-seller-services-for-woocommerce"
    "formidable-to-slack"
    "national-characters"
    "woo-payid-gateway"
    "menu-manager-ultra"
    "featured-product-by-category-name"
    "wpwing-pdf-invoice-packing-slip-for-woocommerce"
    "personalizewp"
    "amateur-tv"
    "kutub-i-sitte"
    "bayarcash-givewp"
    "click2pay-pagamentos"
    "covid-19-em-tempo-real"
    "coceca"
    "vgpodcasts-alertbar"
    "xolo-addon"
    "nc-taxonomy-meta"
    "kcpt-fading-image-widget"
    "gna-page-list"
    "skill-bar-wp"
    "gplugin"
    "mywidget-recommendations"
    "bp-user-activity"
    "tc-post-carousel"
    "pretty-opt-in-lite"
    "mynx-page-builder"
    "dynamaker-cad-configurator-integration"
    "4nton-extensions"
    "ht-blocks"
    "csh-callback"
    "simpleapplinks"
    "glo3d"
    "simple-csv-table"
    "bamboo-layout"
    "results-count-remix"
    "theme-catalog"
    "option-editor"
    "simple-pop-up"
    "blocksolid-gather"
    "pagination-rel-meta"
    "wpcloudhosting"
    "sidenav"
    "fetch-twitter-count-for-wordpress"
    "wp-ban-manager"
    "ocws-admin-bar-greeting"
    "simply-disable-comments"
    "pixi-image-gallery"
    "login-logout-shortcode-simple"
    "as-scroll-to-top"
    "wp-guest-post-manager"
    "post-grid-free"
    "my-album-gallery"
    "wp-property-feed-to-residence-theme-connector"
    "line-styled-menu"
    "demonstrator"
    "masy-gallery"
    "abantecart-embedding"
    "jimmo-wp-property-finance-budget-calculator"
    "bbp-close-old-topics"
    "fx-seo"
    "lb-select-location"
    "livecaller"
    "athena-post-expiration"
    "map2app-connector"
    "image-rights"
    "cart-checkout-confirmation"
    "change-class-in-viewport"
    "ai-generated-post"
    "code-monkeys-proposals"
    "gr-dashboard-notes"
    "actionpress"
    "video-embeds"
    "change-attachment-size"
    "dw-twitter-base"
    "tng-accept-cookies"
    "bigmart-elements"
    "jpress-admin-column-search"
    "testimonials-block"
    "change-header-image-url"
    "integer-wp-security"
    "dummynator"
    "remove-url-field-from-comment-form-in-generatepress-theme"
    "brazilian-fields-registry-wp"
    "notification-bar-builder-for-elementor"
    "mystical-companion"
    "amber-alert-nederland"
    "summits-alert"
    "continuous-delivery"
    "tigo-money-payment-gateway"
    "embed-kindle"
    "sb-clean"
    "drimify-widget"
    "custom-blocks-templates"
    "enviopack-mexico"
    "cpt-recent-entries-widgets"
    "cff-fitness-and-health-operations"
    "products-feed-generator"
    "trunkrs-for-woocommerce"
    "placeholder-fallback"
    "theme-tweak"
    "ultimate-post-by-mail"
    "shortcode-ajax"
    "melu-live-chat"
    "wpcc-pco-giving"
    "wc-product-likes-comments"
    "tracking-code-for-woocommerce"
    "fp-rss-category-excluder"
    "row-column-testmonial-with-widget"
    "subitosms"
    "libravatar"
    "grid-social-boxes"
    "surve"
    "view-user-metadata"
    "wp-wallet"
    "energy-saver"
    "gravity-forms-ab-testing"
    "press-search"
    "woo-add-to-cart-redirect"
    "acf-conditional-logic-extended"
    "edu-results-publishing"
    "track-a-click-on-google-analytics"
    "force-html-edition"
    "blacklist-keys-manager"
    "prophoto-light-blue-api-add-on"
    "woocommerce-last-purchased"
    "ie6-und-ie7-detection-script"
    "aweber-dev-facile"
    "post-smtp-for-mainwp"
    "delovye-linii-for-woocommerce"
    "optinopoli"
    "image-annotations"
    "axio-core"
    "simple-product-counter"
    "set-html-lang-attribute-per-post"
    "event-countdown-timer"
    "export2word"
    "widget-custom-loop"
    "book-collection-star-rating"
    "infomous"
    "wpoker"
    "forumial-sso"
    "document-uploader"
    "studio375-notifizzy"
    "hero-section-genesis"
    "tcbd-tooltip"
    "biz-calendar-grant"
    "best-ads-block-detector"
    "is-it-snowing"
    "thumbs-up"
    "mma-news-widget"
    "wp-qrencoder"
    "astro-media"
    "pgreca-chat"
    "wpinterface-add-ons"
    "wp-before-after-image-slider"
    "haru-vidi"
    "chiliforms"
    "simple-post-status-notifications"
    "wp-api-json-reader"
    "freq-func-collection"
    "ginger-tag-remover"
    "hw-feed-cleaner"
    "affiliate-promotions"
    "wpbuddy"
    "hostvn-admin-optimize"
    "loft-maintenance"
    "rad-bootstrap-3-blocks"
    "move-user-roles"
    "duzz-custom-portal"
    "hide-shipping-methods"
    "light-slider"
    "wp-comment-vote"
    "elex-discount-per-country"
    "multiple-editors"
    "fast-yandex-metrika"
    "hide-update-wp-message"
    "temporarily-hidden-content"
    "truelayer-for-woocommerce"
    "inspiring-dashboards"
    "add-amazon-block"
    "bb-date-and-years-shortcode"
    "quasar-variable-attributes"
    "generate-posts-and-terms"
    "oembed-internal-link"
    "filter-search-page"
    "award-force-sso"
    "hide-content"
    "first-name-and-last-name-on-registration-page"
    "wp-twitter-profile-widget"
    "posts-filter-by-title"
    "the-related-posts"
    "animate-wp"
    "netcash-pay-now-payment-gateway-for-woocommerce"
    "woo-il-ilce-secici"
    "jms-rss-feed"
    "driveworks-block-form-embed"
    "bq-musical-notes"
    "wp-distraction-free-view"
    "block-minimap"
    "mips-payment-gateway-for-woocommerce"
    "blogroll-dropdown-links"
    "prepear"
    "sticky-topbar"
    "hexyimagewidget"
    "wpapi-shortcode-and-widgets"
    "success-fail-popup-message-for-contact-form-7"
    "tp-next-previous-button-in-single-product-page"
    "facilita-form-tracker"
    "livemesh-table-rate-shipping"
    "integracion-afip"
    "wp-post-import"
    "login-watchdog"
    "wp-peon"
    "text-carousel-block"
    "range-slider-field-for-contact-form-7"
    "fr-thumbnails-folder"
    "nostr-verify"
    "star-rating-review-w"
    "bible-readings-for-seriously-simple"
    "woo-bulgarian-shipping-lite"
    "the-video-popup"
    "temple-lock"
    "best-configuration"
    "onlist"
    "dadevarzan-wp-personnel"
    "caret-country-access-limit"
    "selected-posts-widget"
    "kenzap-pricing"
    "greedycoupon"
    "order-item-notes-for-woocommerce"
    "wc-telegram-bot"
    "simple-picture-view"
    "buooy-scroll-to-top"
    "archive-pages-in-search-lite"
    "featured-image-checker"
    "homerunner-smartcheckout"
    "bilych-gallery"
    "premium-link-cloaker-lite"
    "latin-now"
    "age-checkbox-for-woocommerce"
    "delivery-rate-for-sagawa-express"
    "nggimages"
    "easysell"
    "bdtask-crm"
    "meetup-winner"
    "ramadan-alert-bangladesh-timing"
    "tc-specify-search-form"
    "imagex"
    "brisko-hooks-display"
    "wpneon-gocodes"
    "astronomy-picture-of-the-day"
    "simple-hsts-preload"
    "press-tab-to-search"
    "map-posts-free"
    "wp-easy-crm"
    "post-section-votes"
    "jemployee"
    "diigo-bookmarks-widget"
    "global-styles-mods"
    "post-requirements"
    "adshares"
    "link-badges"
    "mirrar"
    "aramex"
    "toggle-comments"
    "wp-webhooks-email-integration"
    "mobli-image-gallery-widget"
    "ivan-gospodinow-cache"
    "better-social-feeds"
    "share-on-bluesky"
    "spamgone"
    "wordpress-plus-one-button"
    "awesome-share-button"
    "pp-recurring-payment"
    "woo-pay-via-proxyapi"
    "basic-alerts"
    "advanced-custom-blocks"
    "dream-popup"
    "top-scroller"
    "datadev-total-express-for-woocommerce"
    "opengraphiq-lite"
    "comment-form-access"
    "stylish-login-pro"
    "digipay-payment-gateway"
    "members-multisite-user-roles-sync"
    "pay-a-coffee"
    "all-images-ai"
    "double-title"
    "just-add-lipsum"
    "product-display-for-opencart"
    "vine-ma"
    "woo-product-collage"
    "reviews-sorted"
    "debug-bar-toggle"
    "simply-captcha"
    "wpalerts"
    "compress-then-upload"
    "wp-plain-text-post"
    "signature-one"
    "wp-domains"
    "wc-price-badge"
    "featured-image-notes"
    "cf7-for-elementor"
    "multilingual-comments-wpml"
    "mywp-login-form"
    "funny-fruits"
    "minimalist-stripe-checkout-for-woocommerce"
    "fastershare"
    "api-for-poker-mavens"
    "cf7-goal-tracking-extension"
    "resources"
    "easy-tinymce-editor-add-button"
    "hawaiian-characters"
    "woo-gift-product"
    "lh-xprofile-forms"
    "verfacto"
    "danamojo"
    "mindestbestellwert-minimum-order-value-for-woocommerce"
    "cfs-yoast-analysis"
    "the-sixtyseven-song-requester"
    "quran-live"
    "blogs-peru-ping"
    "wc-customer-related-order"
    "wpgraphicstudio"
    "site-analytics-widget"
    "pro-adblock"
    "wc-guest-checkout-single-product"
    "wopo-minesweeper"
    "alleaktien-quantitativ"
    "super-wp-hide-admin-bar"
    "kktc-doviz-kurlari"
    "carto"
    "zenkipay"
    "vextras-woocommerce"
    "stibee-email-subscription-form"
    "sksoftware-postone-for-woocommerce"
    "the-voice-designer-by-data-driven-design"
    "one-active-logged-in-session"
    "pay-with-square-in-memberpress"
    "smart-code-escape"
    "hm-simple-facebook-page"
    "wp-resume-shortcode"
    "wp-seo-supercharger"
    "wp-remote-multisite-post"
    "wp-geoloc"
    "photosynth-embed"
    "user-popularity-contest"
    "comfino-payment-gateway"
    "doubledome-google-analytics"
    "selected-posts-in-widget"
    "pay-with-square-in-gravity-forms"
    "remember-old-post-widget"
    "network-copier"
    "a2zvideoapi"
    "flexible-scroll-top"
    "lcs-https"
    "insert"
    "itunes-appstore-app-ranking"
    "rudimentary-information"
    "web-recipe-clipper"
    "change-colors-for-woocommerce"
    "add-region-by-country-for-woocommerce"
    "wp-hooks-browser"
    "easiest-coming-soon-page"
    "nook-widget"
    "gravitation-slider"
    "oembed-flickrlinkr"
    "simple-recent-post-widget"
    "bulk-sms-smsnet24"
    "lazy-load-clarity"
    "button-for-doctolib"
    "latipay-for-woo"
    "vc-countdown-ocoder"
    "tags-als-news-keywords"
    "openphoto"
    "fermiac-siftscience-for-woocommerce"
    "paypal-yearly-subscription"
    "plain-text-custom-post-type"
    "church-theme-content-integration"
    "affiliate-amazon-blockaab"
    "hizzle-forms"
    "validar-identidad-cf7"
    "track-incoming-referrer"
    "s2member-pro-shortcode"
    "rss-shortcode-wtemplate"
    "grid-element-trash"
    "smoothscrollto"
    "posts-in-map"
    "platron-payment-gate-woocommerce"
    "sementes-cas-gcrs"
    "tgg-wp-optimizer"
    "logdash-activity-log"
    "shipped-order-in-woo"
    "wp-system"
    "all-twitter"
    "radio-vera"
    "eh-mortgage-calculator"
    "checkout-freemius"
    "fl3r-user-agent-comments"
    "minimum-viable-sharing-meta"
    "wp-alerts-bars"
    "sendbird-ai-chatbot"
    "funny-equations"
    "register-post-types-and-taxonomies"
    "updates-api-inspector"
    "simplest-colorbox"
    "critique"
    "eblagajna-webshop"
    "cookie-law-script-italiano"
    "webpoint-login"
    "nova-dashboard-widget-bbc-news-technology"
    "ios-icon-renderer"
    "wp-hide-referer"
    "swipe"
    "jsm-show-order-meta"
    "switch-pages"
    "auto-category-for-posts"
    "polzo-ogmeta"
    "codja-wc-ajax-search"
    "ellie-code-snippet"
    "surbma-before-after"
    "kento-clients-feedback"
    "simple-schema"
    "excerpt-old-posts"
    "sqlite-cache"
    "google-map-tab"
    "automatically-wallpaper-changer"
    "buyte"
    "cpd-journals"
    "post-taxonomy-column"
    "edshelf-widget"
    "express-it"
    "jquery-remove-upcase-accents"
    "restaurantops-orders"
    "qr-link-generator-for-wp"
    "saragna-social-stream"
    "quevedo"
    "ez-slider"
    "quizess"
    "data-dash"
    "brand-my-login"
    "warm-welcome"
    "ra-new-post-auto-set-status-private"
    "awsome-youtube-subscribe"
    "admin-menu-width"
    "emojized"
    "revampcrm-woocommerce"
    "landing-page-creator-with-custom-posts"
    "recent-top-most-comment-parents"
    "gmaps-clickn-load-for-divi"
    "woosignal-woocommerce-app"
    "leadeo-lite"
    "lookbook-embed"
    "awesome-addons-for-elementor"
    "search-by-user"
    "keymanweb"
    "tea-page-content"
    "endless-addons-for-elementor"
    "gp-import-from-wp-org"
    "allow-wp-admin-access"
    "color-palette-block"
    "wp-avoider"
    "ventipay"
    "mw-wp-form-line-notify"
    "simple-php-info"
    "captcha-solution"
    "tc-ecommerce"
    "image-source-overlay"
    "wp-openweathermap-weather-forecast-lite"
    "post-snippits"
    "grabzit-web-capture"
    "bannerlid"
    "gunner-technology-asynchronous-asset-loader"
    "rename-groups"
    "variation-auto-expire-for-woocommerce"
    "auto-alt-text"
    "bordered-blocks"
    "visualmods-inline"
    "azo-ads"
    "key-shortcut-formatter"
    "handl-hide-content"
    "minimal-shortcode-ui"
    "pett-tube"
    "easy-taxonomy-support"
    "launchkit"
    "wc-force-pass"
    "invelity-products-feeds"
    "make-money-calculator-v10"
    "desire-portfolio-filter"
    "dhl-ecommerce-apac"
    "wpis"
    "github-shortcode"
    "remove-meta-boxes-per-user-role"
    "latest-posts-slides"
    "track-visitors"
    "post-head-includes"
    "add-dummy-post"
    "wp-add-user-contact-fields"
    "gs-to-wp"
    "wp-shelly-control"
    "clubmember"
    "twitter-hashtag"
    "woo-crm"
    "digilirapay-blockchain-payment-gateway"
    "shortcore"
    "columns-and-sections-link-for-elementor"
    "widget-revisions"
    "featured-image-gallery-widget"
    "turisbook-booking-system"
    "hiweb-theme-switcher"
    "wplms-user-generated-quiz"
    "qqworld-share"
    "hookit-related-products"
    "post-feedback"
    "image-compositions"
    "acf-code-snippets"
    "woo-addpay-gateway"
    "ligery"
    "l7-automatic-updates"
    "woocommerce-paystand"
    "remove-jquery-migrate-log"
    "simpleedit"
    "zen-custom-fields"
    "custom-post-taxonomy-hierarchy-seo"
    "category-post-boxes"
    "tyxo"
    "lowermedia-iframes-on-demand"
    "vestacp-dashboard-widget"
    "dashboard-help"
    "web-visitor-counter"
    "abcbiz-addons"
    "reviews-from-google"
    "importer-for-gravity-forms-and-nationbuilder"
    "team-118group-agent"
    "woocommerce-inspector"
    "possan-lastpost"
    "email-2-mailchimp"
    "bbtemplate"
    "internal-site-seo"
    "basic-auth-for-wp-admin"
    "custom-new-user-email-template"
    "woo-custom-taxonomies-coupons"
    "stocklist-integrator"
    "widget-area-builder"
    "register-settings-api"
    "qanva-custom-mouse-for-elementor"
    "custom-shortlink-structure"
    "dashboard-widgets-control"
    "recently-registered-widget"
    "islamic-archive-for-new-muslims"
    "completionist"
    "no-updates-for-plugins-under-svn"
    "automatic-heating-numbering"
    "sb-responseframe"
    "shorten2list"
    "openbroker"
    "ctrl-user-generator"
    "wpbatch-simple-slider"
    "ak-sharing-buttons"
    "random-theme"
    "orbisius-snippets"
    "multiple-carts-for-woo-free-by-wp-masters"
    "transafe-payments-for-woocommerce"
    "textbox"
    "who-owns-your-country"
    "ab-simple-feeds"
    "wp-socially-related"
    "search-with-algolia-headless-extention"
    "pixelconcept-automanager-marketplace"
    "textp2p-texting-widget"
    "jelly"
    "internet-archive-video-resizer"
    "lof-slider-news"
    "orcsnet-from-inditip"
    "raopress-chat-firebase-chat-for-visitors"
    "simple-nft-protection-manager"
    "healthy-filenames"
    "skash-payment"
    "vandar-gravityform"
    "pages-on-top"
    "rateitcool"
    "sp-display-widgets"
    "lazy-embed"
    "g-live-cms"
    "direct-link"
    "boxcoin-cloud"
    "tourmake-elementor-addons"
    "twitcasting-status"
    "cbxscratingreview"
    "when-last-login-welcome-email-add-on"
    "change-post-label"
    "rise-hotel-booking"
    "custom-widget-creator"
    "tambar"
    "vat-assist-for-woocommerce"
    "delivengo"
    "grandeljay-mailjet-integration"
    "socialproofy"
    "wp-youtube-video-optimizer"
    "wp-posts-table"
    "clinicsoftware-com-crm"
    "gravity-froms-monthpicker"
    "cresta-addons-for-elementor"
    "admin-bar-edit-links-for-gravity-forms"
    "dl-codemirror"
    "eldolink"
    "eacsoftwareregistry-distribution-sdk"
    "ckav-elementor-booster"
    "aztheme-toolkit"
    "ngg-image-chooser-block"
    "sp-disable-site"
    "tcbd-lost-password-remove"
    "nix-prefix"
    "lh-export-users-to-csv"
    "category-seo"
    "woocommerce-csv-export-for-user-roles"
    "gpxconnect"
    "mysqlist"
    "refback"
    "ciusan-nice-scroll"
    "unique-uploaded-media-name"
    "mt8-secret-comments"
    "wp-get-the-table"
    "fullestop-analytics-code-option"
    "require-taxonomy-image-category-tag"
    "bsd-svg-icons"
    "smart-varnish"
    "wp-git-deploy"
    "simple-woo-reviews-lite"
    "not-modified"
    "sweet-glossary"
    "twism"
    "wc-payment-gateway-easycard"
    "ruven-themes-post-formats-ui"
    "bright-link-previews"
    "jquery-cookie-url-fix"
    "winelog"
    "sm-youtube-video-iframe"
    "ng-wp-gallery"
    "mintnft"
    "custom-social-icon"
    "beatgig-calendar-embed"
    "fx-share"
    "cticker"
    "native-wp-cleaner"
    "fiddlemail"
    "inclusive-parents"
    "save-page-to-pdf"
    "isbn-book-search"
    "simple-socnets"
    "woocommerce-better-feeds"
    "content-shelf-shopping-cart"
    "st-breadcrumbs"
    "bbp-follow-users"
    "ajaxify-comments"
    "ultimate-reviews-rocket"
    "restrict-wp-pages-with-redirect"
    "universal-ads"
    "vendor-templates-dokan"
    "hide-shipping-methods-in-woocommerce"
    "sparkle-elementor-kit"
    "cat-block"
    "cc-sentry"
    "ds-gallery"
    "imagets"
    "woo-virtual-merchant"
    "disable-email-notifications"
    "wp-easy-contact-form"
    "attribution-query-string-manager"
    "related-tags"
    "paay"
    "azurecurve-display-after-post-content"
    "rewrite-email-address"
    "arnold-analytics"
    "perfit-woocommerce"
    "seo-images-reloaded"
    "wp-easy-tooltips"
    "link-back-badge-widget"
    "ccr-event"
    "print-array"
    "hide-post-tags"
    "slideshow-reloaded"
    "clear-debuglog-cron"
    "ultimate-carousel"
    "dynamiccategorytagcloud"
    "author-profile-image"
    "wp-ajax-register-login"
    "recent-topics-for-ipboard"
    "simple-todo-list"
    "advanced-what-should-we-write-about-next"
    "notes"
    "browser-compatibility-warning"
    "autocomplete-wizard"
    "scheduled-posts-dashboad-widget"
    "disable-visual-editor-when-published"
    "wp-update-mail-notification"
    "and-it-portfolio-for-elementor"
    "masterbip-comunas-de-chile"
    "scheduly"
    "daily-posts-widget"
    "bosssocial"
    "juiz-user-login-by-email"
    "uqrate"
    "editor-blocks-border"
    "ipp-simple-loading"
    "lead-magnets"
    "wp-piwik-notifier"
    "wp-easy-directory-link"
    "push-notifications-for-web"
    "wp-network-stats"
    "easy-progressive-web-app"
    "gap-hub-enquiryform"
    "remove-admin-bar-from-previews"
    "member-gravatars"
    "qtranslate-loves-wp-e-commerce"
    "cts-infusionsoft-form-shortcode"
    "custom-adsense-plugin"
    "bloginfo-shortcode"
    "preserve-mainwp"
    "easy-casino-table"
    "silent-update"
    "asset-preloader"
    "wordpress-zootool"
    "wp-slidebean"
    "linux-day"
    "shopeo-wp-core"
    "preload-everything"
    "clickable-date"
    "auto-maps"
    "shrinktheweb-refresh-all"
    "coronavirus-info"
    "miratio"
    "top-3-jackpots"
    "truanon-identity"
    "eacsoftwareregistry-subscription-webhooks"
    "longer-login"
    "deligent-variable-block-width"
    "tweets-widget"
    "woocommerce-connect-for-tally-framework"
    "query-filter"
    "revenue-generator"
    "thron"
    "bizmerlinhr-jobboard"
    "remove-website-link-field-from-comment-section"
    "vg-remove-html-comments"
    "album-products-for-woocommerce"
    "easy-to-manage-vendor"
    "posts-on-a-map"
    "combine-galleries"
    "mighty-builder"
    "mad-cow-customizer-for-woocommerce"
    "don-security"
    "catalogo"
    "hb-freshdesk"
    "retainly"
    "gna-korean-sns"
    "dogo-content-widget"
    "wc-estimate-and-quote"
    "bsplaces"
    "privateanalytix"
    "custom-validation-error-message-cf7"
    "grassblade-xapi-gamipress"
    "globkurier"
    "gravity-forms-recently-viewed-products"
    "logo-slider-free"
    "lord-linus-online-visitor"
    "sfx-woo-donate"
    "audiotyped-ux"
    "extender-all-in-one-for-elementor"
    "legalblink-policy"
    "custom-post-type-filters-for-users-insights"
    "simple-bulk-episodes"
    "woning-website-uitbreiding"
    "wp-promoter"
    "awesome-parallax-effects"
    "exif-viewer"
    "tabletize-json-connector"
    "box-tracker-portal"
    "plaintext-newsletter"
    "kontur-admin-style"
    "smartarget-corner-ribbon"
    "indemandly"
    "aggregate-rating"
    "flipper"
    "template-map"
    "advanced-pods-bulk-action"
    "mindstien-quick-login"
    "ads-after-first-paragraph"
    "lazy-disqus"
    "dirty-code"
    "easy-options-hide-shipping-method-per-product-wc"
    "woo-on-sale-information"
    "glassboxx-integration-for-woocommerce"
    "after-comment-prompts"
    "easy-fast-optimization"
    "the-colour-clock"
    "va-simple-enhanced-security"
    "edd-geckoboard"
    "wp-lightpics"
    "tt-options"
    "silkypress-input-field-block"
    "advance-wp-redirect"
    "delete-usermetas"
    "ce21-suite"
    "advertentieplanet-for-woocommerce"
    "serious-duplicated-terms"
    "flowbox"
    "essential"
    "default-trackbacks"
    "s2b-ai-assistant"
    "theme-folders"
    "code-school-badges"
    "wp-isotope"
    "get-user-role"
    "paidcontent"
    "bitcoin-price-tooltip"
    "buttons-widgets-for-elementor"
    "bankpay-open-banking-sepa-payments-for-woocommerce"
    "point-blank-super-recent-posts"
    "quick-questionnaire"
    "preview-site-link"
    "simple-affiliate-for-woocommerce"
    "hyakunin-isshu-admin-bar"
    "thebooking"
    "gls-shipping-for-woocommerce"
    "wc-kmercadopago-gpl"
    "lightweight-and-responsive-youtube-embed"
    "lacrm-connector-for-contact-form7"
    "feedbackstr-easyshare"
    "featured-first-then-random-sorting-for-woocommerce"
    "soundcloud-liked-tracks"
    "comment-expirator"
    "ads-benedict"
    "voip-call-charges-lite"
    "advanced-galleria"
    "bravo-security"
    "agile-crm-forms"
    "turinpay-for-woocommerce"
    "auto-update-post-date"
    "pdf-sitemap"
    "wpcf7-extended"
    "hotels-airbnb-map"
    "simple-quick-tags"
    "load-smallchat"
    "wp-add-header-scripts"
    "add-payment-type-to-woocommerce-admin-email"
    "clickable"
    "create-eye-catch-for-classic"
    "hide-posts-for-specific-roles"
    "cf7-bot-forms-add-on"
    "teams-slider-shortcode-pack"
    "at-internet"
    "prove-you-are-a-human-ruh-captcha-plugin"
    "custom-single"
    "bukazu-search-widget"
    "start-a-fire"
    "spampot"
    "planning-center-online-giving"
    "acf-ajax-grid-gallery"
    "better-smooth-scroll"
    "word-and-character-counter"
    "funny-text"
    "wp-horoscope"
    "woo-elastic-slideshow"
    "post-display-counter"
    "posts-and-products-views"
    "jetpack-non-admin-removal"
    "sponsor-redirect"
    "skeletonisr"
    "content4subscribers"
    "english-words-translator-by-vocabla"
    "all-sociable"
    "wp-nearbyfacilities"
    "popconvert"
    "sepa-payment-gateway-for-woocommerce"
    "fullscreen-button"
    "crosswinds-blocks"
    "wp-postcode-lookup-form"
    "email-posts-commentators"
    "rotating-clock-widget"
    "simple-custom-post-likes"
    "gmo-google-map"
    "local-navigation-extended"
    "photocommerce"
    "image-altifier"
    "webatta-deposit-for-wc-products"
    "configure-conference-room"
    "devotionalium"
    "c4d-shoppable-images"
    "simple-tag-shortcode"
    "tinymce-remove-base-64-image"
    "easy-multi-step-form"
    "oko-original-landing-tracker"
    "custom-role-creator"
    "mobile-contact-buttons"
    "accessible-elementor-popups-by-accessibility-zone"
    "litres-widget"
    "hw-yahoo-skype-status-pro"
    "hover-product-details"
    "creo-weather-today-widget"
    "sweet-energy-efficiency"
    "instant-cookie-expire"
    "wigwag"
    "opes-wp-social-tabs"
    "my-wp-login"
    "surbma-bookingcom-shortcode"
    "social-tracker"
    "agile-video-player"
    "custom-taxonomy-order"
    "wp-textimage-linking-shortcode"
    "wp-help-popup"
    "filter-featured-products"
    "db-views-data-table"
    "woo-departamentos-uruguay"
    "nobita-connect"
    "seraphinite-old-slugs-mgr"
    "web-vitals-block"
    "cubepoints-authorizenet-module"
    "dropdown-category-list"
    "wp-app-json"
    "ivguard"
    "nextplugins-woocommerce-vat"
    "edd-payu-latam-gateway"
    "mosmos"
    "paiement-par-carte-dahabia-et-cib-for-woocommerce"
    "testimonium"
    "wp-fixed-ads"
    "dynamic-home-length"
    "cop-css-custom-post-type-lite"
    "loginfy"
    "codexin-image-gallery"
    "likeablepress-sendfox-for-divi"
    "pageproofer"
    "ajax-loading"
    "wp-post-grid-slider-filter-by-xgenious"
    "play-pause-button-for-video"
    "quick-location-maps"
    "phpmydirectory"
    "no-copy-release"
    "admin-back-button"
    "leseo"
    "wm-jqmath"
    "hello-dalai"
    "juratext-importer-fur-rechtstexte24"
    "multisite-new-user-no-confirmation"
    "change-date-language-italian-people"
    "podamibe-2checkout"
    "gateway-aqayepardakht-for-gravity-forms"
    "jobs-from-recruitee"
    "disable-automatic-theme-plugin-updates"
    "post-grid-for-elementor"
    "eye4fraud-for-woocommerce"
    "accept-2checkout-payments-using-contact-form-7"
    "htaccess-ip-block"
    "woocommerce-paygatenet-payment-gateway"
    "woo-points"
    "sidebar-video"
    "classic-menu-in-navigation-block"
    "prerender"
    "wp-window-shopper"
    "wp-careerjet-shortcode"
    "ruven-themes-sharing-links"
    "seopilot"
    "corsi"
    "wordtwit-tweet-failed"
    "3d-effect-text"
    "vw-property-listing"
    "categorized-rss-feed"
    "random-messages"
    "fireauth"
    "bbpress-connect-for-tally-framework"
    "a-little-more-secure"
    "ssl-fixit"
    "ars-affiliate-page"
    "gls-woocommerce"
    "mailmaga-x"
    "pau-accesibilidad-universal"
    "proxy-b-movement"
    "500apps-schedulecc"
    "easy-cookie-consent"
    "klubraum-membership-request"
    "cellulant-tingg-checkout"
    "sc-scrollup"
    "mp-post-navigation-same-category"
    "hth-embed-media-player"
    "toot"
    "wp-delete-tags-tagassassin"
    "sibling-pages"
    "c4d-woo-quickview"
    "kk-update-control"
    "abbreviations"
    "easy-filterable-gallery"
    "calltracker"
    "rss-advanced-widget"
    "investment-decision-helper"
    "location-click-map"
    "watchman"
    "wp-users-masquerade"
    "crowdfunding-and-fundraising-campaign-builder-by-payform"
    "custom-wp-admin-login"
    "contentside-semantic-platform"
    "snap-video-gallery"
    "paymennt-card-payment"
    "session-rewind"
    "accessibility-help-button"
    "lyket-like-buttons"
    "list-media"
    "kcspirit"
    "cbxmcratingreview"
    "disallow-pwned-passwords"
    "dh-notification-bar"
    "security-txt"
    "daily-free-kindle-books"
    "pcf-christmas-countdown"
    "add-zip-codes-to-posts"
    "feedbacks-and-reviews"
    "lamoud-pregnancy-calculator"
    "garanti-payment-gateway-for-woocommerce"
    "bbp-topic-and-reply-author-override"
    "mhm-catch-comment-spam"
    "browser-check"
    "promote-my-extensions"
    "omnisend-for-contact-form-7"
    "link-twitter-users"
    "social-media-panel-for-images"
    "wc-dashboard-widget"
    "fw-public-profil"
    "postdivider"
    "pocketgecko-email"
    "sfx-exchange-rates"
    "recently-viewed-most-viewed-and-sold-products-for-woocommerce"
    "better-captcha-gravity-forms"
    "tp-chat-lite"
    "limit-parameter-for-gallery-shortcode"
    "survey-popup"
    "wppopupmagic"
    "orderforms-stripe"
    "inline-click-to-tweet"
    "roller"
    "ja-wowtoken"
    "hertwill"
    "wc-essential-addons"
    "woo-options"
    "fcp-first-screen-css"
    "page-transition-free-for-wp"
    "gp-project-contributors"
    "w3responsive-tabs"
    "random-quran"
    "small-package-quotes-usps-edition"
    "sendwithus"
    "comment-translator"
    "cjaffiliate-export"
    "chokidar"
    "wc-custom-product-tab-manager"
    "stylish-business-hours"
    "booketbord"
    "shoot-the-zombie"
    "wp-webhooks-comments"
    "cart66-cloud-aweber"
    "wp-evernote-synchronizer"
    "bp-group-analytics"
    "nk-fajne"
    "uqast-embed"
    "dream-broker-embed"
    "k7-church"
    "wt-widgets-elementor"
    "wpfts-add-on-for-wp-download-manager"
    "pb-unblock-some-ips"
    "danker-sitemap-flexible-sitemap-page"
    "intelligencebank-connector"
    "posts-number-widget"
    "bbp-import-google-group"
    "users-login-monitor"
    "assistant-for-nextgen-gallery"
    "wp-quran"
    "kento-simple-fancy-gallery"
    "website-information"
    "breakout-box"
    "materially-flat-admin-theme"
    "pretty-debug"
    "styled-google-maps-block"
    "user-meta-profile-list"
    "size-chart-product-for-woocommerce"
    "woo-cart-dropdown"
    "gf-json-export"
    "iqiplus-sns-share-tools-for-japan"
    "crpostwarning"
    "bbp-markdown"
    "block-spam-comment"
    "clean-protected-and-private-page-titles"
    "retina-stripper"
    "super-host-speed-benchmark"
    "post-ranking-view"
    "theme-independent-stylesheets"
    "momentum"
    "css-reminder"
    "relaypay"
    "rentfetch"
    "restrict-user-taxonomies"
    "protect-your-content"
    "media-library-internet-archive-content"
    "actus-motion"
    "bd-payments-camptix"
    "tabs-pills"
    "k1-page-listing"
    "lead-to-clio"
    "pcf-birthday-countdown"
    "simple-kmdg-resource-center"
    "linkgreen-site-integrations"
    "cf7-country-code-drop-down"
    "ai-contact-form"
    "gravitate-automated-tester"
    "ot-product-price-filter"
    "sr-scrollbar-wp"
    "lastfm-charts"
    "wpr-halloween-scare-popup"
    "sitewide-coloring"
    "secret-image-slide-and-tune"
    "my-sites-menu-fixer"
    "admin-zendesk-help-widget"
    "textplace"
    "edd-tab-manager"
    "mtcaptcha"
    "edd-disable-admin-notices"
    "default-new-window-link-opener"
    "wp-calc-weight"
    "e-payeye-payments"
    "remove-suggestions-from-plugin-search-results"
    "mobile-frame"
    "cbxform"
    "zpr-zeumic-products-database"
    "glofox-shortcodes"
    "lifetime-subscriptions-for-woocommerce"
    "foma-news"
    "amw-clear-upload-folder"
    "sv-forms"
    "wp-ldap"
    "better-om-api"
    "wtt-woo-stock-addon"
    "admin-color-scheme"
    "dn-cookie-notice"
    "scheduled-stickiness"
    "migrate-wufoo-to-gravity-forms"
    "add-autosave-fullscreen-to-tinymce"
    "extra-amount-on-checkout"
    "speakol"
    "wp-what-links-here"
    "a360-embedder"
    "block-editor-gallery-slider"
    "ac-stop-content-copier"
    "fix-event-calendar-caching"
    "pmpro-voguepay"
    "all-my-login-page"
    "simple-upload-widget"
    "dh-rename-uploaded-files"
    "filterable-portfolio-for-beaver-builder-elementor"
    "epnb-featured-image-widget"
    "infinite-scroll-for-elementor-with-ajax"
    "wp-remote-request-check"
    "gasolineras-de-espana"
    "passive-indexation-check"
    "ninja-columns"
    "backuppressgenius"
)

# Define user agents with weights
declare -A USER_AGENTS
USER_AGENTS=(
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"]=5
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"]=7
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"]=6
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36 Edg/91.0.864.54"]=5
    ["Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 OPR/77.0.4054.277"]=3
    ["Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (iPad; CPU OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Vivaldi/4.0"]=1
    ["Mozilla/5.0 (Android 11; Mobile; rv:68.0) Gecko/68.0 Firefox/88.0"]=1
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"]=15
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/534.36"]=12
)

CLOSED_PLUGINS_FILE="${WORDPRESS_WORKDIR}/closed_plugins.txt"
LAST_VERSION_FILE="${WORDPRESS_WORKDIR}/last_versions.txt"
PARALLEL_JOBS=1

DOWNLOAD_ALL_PLUGINS='n'
LIST_ONLY='n'
ALL_PLUGINS_FILE="${WORDPRESS_WORKDIR}/wp-plugin-svn-list.txt"

DELAY_DOWNLOADS='n'
DELAY_DURATION=5

FORCE_UPDATE='n'
CACHE_ONLY='n'

mkdir -p "$WORDPRESS_WORKDIR" "$MIRROR_DIR" "$LOGS_DIR"
DEBUG_MODE=0

while getopts "p:dalD:t:fc" opt; do
    case ${opt} in
        p ) PARALLEL_JOBS=$OPTARG ;;
        d ) DEBUG_MODE=1 ;;
        a ) DOWNLOAD_ALL_PLUGINS='y' ;;
        l ) LIST_ONLY='y' ;;
        D ) DELAY_DOWNLOADS=$OPTARG ;;
        t ) DELAY_DURATION=$OPTARG ;;
        f ) FORCE_UPDATE='y' ;;
        c ) CACHE_ONLY='y' ;;    # New option for cache-only
        \? ) echo "Usage: $0 [-p PARALLEL_JOBS] [-d] [-a] [-l] [-D DELAY_DOWNLOADS] [-t DELAY_DURATION] [-f] [-c]" 1>&2; exit 1 ;;
    esac
done

debug_log() {
    if [ "$DEBUG_MODE" -eq 1 ]; then
        echo "[DEBUG] $1" >&2
    fi
}

get_random_user_agent() {
    echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
}

get_latest_version_and_download_link() {
    local plugin=$1
    debug_log "Checking latest version and download link for $plugin"
    
    local api_url="https://api.wordpress.org/plugins/info/1.0/${plugin}.json"
    local user_agent=$(get_random_user_agent)
    local api_response=$(curl -s -H "User-Agent: $user_agent" "$api_url")
    
    if echo "$api_response" | jq -e '.error' >/dev/null; then
        local error_message=$(echo "$api_response" | jq -r '.error')
        if [ "$error_message" = "closed" ]; then
            echo "closed"
            return 2
        else
        echo "Error: $error_message for plugin $plugin" >&2
        return 1
        fi
    fi
    
    local version=$(echo "$api_response" | jq -r '.version // empty')
    local download_link=$(echo "$api_response" | jq -r '.download_link // empty')
    
    if [ -n "$version" ] && [ -n "$download_link" ]; then
        echo "$version $download_link"
        return 0
    else
        echo "Error: Cannot fetch version or download link for $plugin" >&2
        return 1
    fi
}

download_plugin() {
    local plugin=$1
    local version=$2
    local api_download_link=$3
    local output_file="${MIRROR_DIR}/${plugin}.${version}.zip"
    local header_file="${LOGS_DIR}/${plugin}.${version}.headers"
    local constructed_download_link="${DOWNLOAD_BASE_URL}/${plugin}.${version}.zip"
    local download_link

    if [ "$DEBUG_MODE" -eq 1 ]; then
        debug_log "API-provided download link for $plugin: $api_download_link"
        debug_log "Constructed download link for $plugin: $constructed_download_link"
    fi

    if [ "$DOWNLOAD_LINK_API" == 'y' ] && [ -n "$api_download_link" ]; then
        download_link="$api_download_link"
        debug_log "Using API-provided download link for $plugin: $download_link"
    else
        download_link="$constructed_download_link"
        debug_log "Using constructed download link for $plugin: $download_link"
    fi

    debug_log "Downloading $plugin version $version through Cloudflare Worker"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)
    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o /dev/null "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    else
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o "$output_file" "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    fi

    if [ $? -eq 0 ]; then
        if [ "$CACHE_ONLY" == 'y' ]; then
            debug_log "Plugin $plugin version $version cached successfully."
            return 0
        fi

        local file_size=$(stat -c%s "$output_file")
        if [ "$file_size" -lt 1000 ]; then
            echo "Error: Downloaded file for $plugin is too small (${file_size} bytes). Possible download issue." >&2
            return 1
        fi

        local source=$(grep -i "X-Source:" "$header_file" | cut -d' ' -f2 | tr -d '\r')
        if [ "$source" == "R2" ]; then
            debug_log "Successfully downloaded $plugin version $version from R2 storage"
        elif [ "$source" == "WordPress" ]; then
            debug_log "Successfully downloaded $plugin version $version from WordPress"
            debug_log "R2 bucket saving for plugin zip occurred"
        else
            debug_log "Skipped download for $plugin $version zip (already exists locally)"
        fi

        return 0
    else
        echo "Error: Failed to download $plugin version $version" >&2
        return 1
    fi
}

save_plugin_info() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.json"

    debug_log "Saving plugin json metadata for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying metadata download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    if [ "$CACHE_ONLY" == 'y' ]; then
        # When in cache-only mode, output to /dev/null
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin metadata for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache json metadata for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            if [ "$source" = "R2" ]; then
                debug_log "json metadata for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "json metadata for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin json occurred"
            else
                debug_log "json metadata for $plugin version $version saved (json metadata file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save json metadata for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

fetch_and_save_checksums() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.checksums.json"

    debug_log "Fetching and saving checksums for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying checksums download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    debug_log "Sending request to Worker for checksums: CF_WORKER_URL?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"

    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin checksums for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache checksums for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        debug_log "Received response with status code: $status_code"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            debug_log "Response source: $source"
            if [ "$source" = "R2" ]; then
                debug_log "Checksums for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "Checksums for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin checksums occurred"
            else
                debug_log "Checksums for $plugin version $version saved (checksums file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save checksums for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

process_plugin() {
    local plugin=$1

    # Check if the plugin is already known to be closed
    if grep -q "^$plugin$" "$CLOSED_PLUGINS_FILE" 2>/dev/null; then
        echo "Plugin $plugin is known to be closed. Skipping."
        return 0
    fi

    echo "Processing plugin: $plugin"

    VERSION_AND_LINK=$(get_latest_version_and_download_link "$plugin")
    local version_check_status=$?
    
    if [ $version_check_status -eq 1 ]; then
        echo "Skipping $plugin due to version fetch error."
        return 1
    elif [ $version_check_status -eq 2 ]; then
        echo "Plugin $plugin is closed. Skipping download and processing."
        echo "$plugin" >> "$CLOSED_PLUGINS_FILE"
        if save_plugin_info "$plugin" "closed"; then
            debug_log "Successfully saved json metadata for closed plugin $plugin."
        else
            debug_log "Failed to save json metadata for closed plugin $plugin."
        fi
        return 0
    fi
    
    LATEST_VERSION=$(echo "$VERSION_AND_LINK" | cut -d' ' -f1)
    API_DOWNLOAD_LINK=$(echo "$VERSION_AND_LINK" | cut -d' ' -f2-)

    debug_log "Latest version for $plugin: $LATEST_VERSION"
    debug_log "API download link for $plugin: $API_DOWNLOAD_LINK"

    STORED_VERSION=$(grep "^$plugin" "$LAST_VERSION_FILE" | awk '{print $2}')
    debug_log "Stored version for $plugin: $STORED_VERSION"

    if [ "$CACHE_ONLY" != 'y' ] && [ "$LATEST_VERSION" == "$STORED_VERSION" ] && [ -f "${MIRROR_DIR}/${plugin}.${LATEST_VERSION}.zip" ]; then
        echo "$plugin is up-to-date and exists in mirror directory. Skipping download..."
    else
        start_time=$(date +%s.%N)

        if download_plugin "$plugin" "$LATEST_VERSION" "$API_DOWNLOAD_LINK"; then
            if [ "$CACHE_ONLY" != 'y' ]; then
                sed -i "/^$plugin/d" "$LAST_VERSION_FILE"
                echo "$plugin $LATEST_VERSION" >> "$LAST_VERSION_FILE"
            fi
            echo "Successfully processed $plugin."
        else
            echo "Error: Failed to process $plugin." >&2
        fi

        end_time=$(date +%s.%N)
        duration=$(echo "$end_time - $start_time" | bc)
        printf "Time taken for %s: %.4f seconds\n" "$plugin" "$duration"
    fi

    if save_plugin_info "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully saved json metadata for $plugin."
    else
        debug_log "Failed to save json metadata for $plugin."
    fi

    if fetch_and_save_checksums "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully fetched and saved checksums for $plugin."
    else
        debug_log "Failed to fetch and save checksums for $plugin."
    fi
}

populate_all_plugins() {
    if [ ! -f "$ALL_PLUGINS_FILE" ] || [ "$LIST_ONLY" == 'y' ]; then
        echo "Fetching list of all WordPress plugins..."
        svn list https://plugins.svn.wordpress.org/ | sed 's/\/$//g' > "$ALL_PLUGINS_FILE"
        plugin_count=$(wc -l < "$ALL_PLUGINS_FILE")
        echo "Plugin list (${plugin_count}) saved to $ALL_PLUGINS_FILE"
    fi
    
    if [ "$LIST_ONLY" == 'n' ]; then
        ALL_PLUGINS=()
        while IFS= read -r line; do
            ALL_PLUGINS+=("$line")
        done < "$ALL_PLUGINS_FILE"
        echo "Loaded ${#ALL_PLUGINS[@]} plugins."
    fi
}

if [ "$LIST_ONLY" == 'y' ]; then
    populate_all_plugins
    echo "Plugin list created. Exiting without downloading."
    exit 0
fi

if [ "$DOWNLOAD_ALL_PLUGINS" == 'y' ]; then
    populate_all_plugins
    COMBINED_PLUGINS=("${ALL_PLUGINS[@]}")
else
    if [ ! -d "$PLUGIN_DIR" ]; then
        echo "Warning: Plugin directory $PLUGIN_DIR does not exist or is invalid."
        PLUGIN_LIST=()
    else
        PLUGIN_LIST=($(ls -d "$PLUGIN_DIR"/*/ 2>/dev/null | xargs -n 1 basename))

        if [ ${#PLUGIN_LIST[@]} -eq 0 ]; then
            echo "No plugins found in $PLUGIN_DIR."
        fi
    fi

    COMBINED_PLUGINS=(${PLUGIN_LIST[@]} ${ADDITIONAL_PLUGINS[@]})
    COMBINED_PLUGINS=($(echo "${COMBINED_PLUGINS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
fi

if [ ${#COMBINED_PLUGINS[@]} -eq 0 ]; then
    echo "No plugins to download. Exiting."
    exit 0
fi

mkdir -p "$MIRROR_DIR"
touch "$LAST_VERSION_FILE"

if [ "$PARALLEL_JOBS" -gt 1 ]; then
    echo "Running in parallel with $PARALLEL_JOBS jobs..."
    # First, export all variables including USER_AGENTS
    export DOWNLOAD_BASE_URL MIRROR_DIR LAST_VERSION_FILE DEBUG_MODE DOWNLOAD_LINK_API LOGS_DIR ALL_PLUGINS_FILE DOWNLOAD_ALL_PLUGINS LIST_ONLY CF_WORKER_URL DELAY_DOWNLOADS DELAY_DURATION FORCE_UPDATE CACHE_ONLY USER_AGENTS

    # Then, export the functions
    export -f process_plugin get_latest_version_and_download_link download_plugin debug_log populate_all_plugins save_plugin_info get_random_user_agent fetch_and_save_checksums
    printf "%s\n" "${COMBINED_PLUGINS[@]}" | xargs -P $PARALLEL_JOBS -I {} bash -c 'process_plugin "$@"' _ {}
else
    for plugin in "${COMBINED_PLUGINS[@]}"; do
        process_plugin "$plugin"
    done
fi

if [ -f "$CLOSED_PLUGINS_FILE" ]; then
    echo
    echo "Closed Plugin List:"
    cat "$CLOSED_PLUGINS_FILE" | sort | uniq || true
    echo
    echo "Total closed plugins: $(wc -l < "$CLOSED_PLUGINS_FILE")"
    echo
else
    echo
    echo "No closed plugins found."
    echo
fi
echo "Plugin download process completed."
