#!/bin/bash

# Base directory (script location)
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Configurable directories
WORDPRESS_WORKDIR="${WORDPRESS_WORKDIR:-$BASE_DIR/wordpress-plugins}"
PLUGIN_DIR="${PLUGIN_DIR:-$BASE_DIR/wp-content/plugins}"
MIRROR_DIR="${MIRROR_DIR:-$BASE_DIR/mirror}"
LOGS_DIR="${LOGS_DIR:-$BASE_DIR/plugin-logs}"

# Check for CF_WORKER_URL environment variable
if [ -z "$CF_WORKER_URL" ]; then
    echo "Error: CF_WORKER_URL environment variable is not set." >&2
    exit 1
fi

DOWNLOAD_BASE_URL="https://downloads.wordpress.org/plugin"

# Other variables
DOWNLOAD_LINK_API='y'

ADDITIONAL_PLUGINS=(
    "hide-content-by-role-for-wpbakery"
    "black-ribbon"
    "myagilepixel"
    "preziwp"
    "crudlab-disable-comments"
    "mi-logo-slider"
    "endless-posts-navigation"
    "time-tracker"
    "seo-optimized-share-buttons"
    "thrivedesk"
    "appointmind"
    "custom-highlight-color"
    "tinymce-page-break-button"
    "subscription-epayco"
    "social-streams"
    "dsgvo-tools-kommentar-ip-entfernen"
    "headjs-loader"
    "http-basic-auth"
    "wpfanyi-import"
    "wp-games-embed"
    "wpshopgermany-it-recht-kanzlei"
    "user-sync"
    "side-slide-responsive-menu"
    "wp-votd"
    "cookie-consent-box"
    "easy-custom-fields"
    "machform-shortcode"
    "woo-product-reviews-shortcode"
    "wp-asc"
    "wavy-divider"
    "wupo-group-attributes"
    "fb-opengraph-tags"
    "filename-based-asset-cache-busting"
    "stardekk-cubilis-fastbooker"
    "embedstories"
    "cdnjs"
    "always-show-admin-bar"
    "get-image"
    "shipping-by-city-for-woocommerce"
    "wpml-shortcodes"
    "wc-shipping-method-description"
    "payhip-sell-ebooks"
    "surveyjs"
    "freetobook-booking-button"
    "portugal-chronopost-pickup-woocommerce"
    "add-dashboard-columns"
    "astrology"
    "st-gallery-wp"
    "n-media-wp-simple-quiz"
    "hyperpay-gateways"
    "woo-custom-sale-tag"
    "responsive-lightbox2"
    "wonderplugin-exclude-category"
    "project-tasks"
    "browser-specific-css"
    "n-media-woocommerce-checkout-fields"
    "super-recent-posts"
    "inventory-presser"
    "custom-newsletter-template"
    "rssupplement"
    "sm-page-duplicator"
    "sheet-music-library"
    "plastic-post-style"
    "coronavirus-covid-19-notice-message"
    "ultimate-thesis-options"
    "redirect-old-slugs"
    "read-more-copy-link"
    "baw-force-plugin-updates"
    "wp-list-pages-by-custom-taxonomy"
    "peekaboo"
    "document-data-automation"
    "event-feed-for-eventbrite"
    "wp-sticky-footer-bar"
    "allow-cyrillic-usernames"
    "palmodule-paypal-payment-for-woocoomerce"
    "woo-sku-label-changer"
    "whatwedo-acf-cleaner"
    "awesome-project-manager"
    "checkout-upsell-funnel-for-woo"
    "synved-options"
    "auto-meta-header-10"
    "classic-addons-wpbakery-page-builder-addons"
    "widget-areas-learndash"
    "lesson-bookmark-tutor-lms"
    "tdo-tag-fixes"
    "wp-currencies"
    "wp-developer-assistant"
    "social-buttons"
    "cpm-gallery"
    "bp-blog-author-link"
    "simple-draft-list"
    "disable-wp-registration-page-spam"
    "ut-elementor-addons-lite"
    "security-ninja-for-mainwp"
    "wp-google-recaptcha"
    "bundler"
    "support-tickets-v2"
    "antideo-email-validator"
    "acymailing-integration-for-contact-form-7"
    "aweber-optin-widget"
    "super-events"
    "uwcart-start"
    "motors-vin-decoder"
    "remove-broken-images"
    "cookie-notification"
    "open-links-in-new-tab"
    "clip-for-woocommerce"
    "gif-uploader-wp-grandplugins"
    "no-disposable-email"
    "hide-entry-title"
    "delete-spam-daily"
    "p2-likes"
    "customize-twenty-sixteen"
    "category-featured-images-extended"
    "wha-puzzle"
    "restaurant"
    "rs-csv-importer-media-addon"
    "wp-admin-theme"
    "c9-admin-dashboard"
    "paystack-memberpress"
    "block-editor-search-replace"
    "admin-toolbox"
    "advanced-tabs-block"
    "site-table-of-contents"
    "mailchimp-comment-optin"
    "woo-address-validator"
    "wc-multivendor-marketplace-migration"
    "cleanup-duplicate-meta"
    "print-button-shortcode"
    "spectacula-page-widget"
    "srs-player"
    "canalblog-importer"
    "online-contact-widget"
    "append-or-prepend-content"
    "wp-one-post-widget"
    "bs-payone-woocommerce"
    "va-simple-basic-auth"
    "add-to-social"
    "ninja-embed-plugin"
    "modern-related-posts"
    "use-clients-time-zone"
    "wp-options-editor"
    "hansel-gretel"
    "latest-posts-by-author"
    "fs-for-wp-fullstory-com-integration"
    "next-event-calendar"
    "contact-form-7-star-rating-with-font-awersome"
    "code-snippets-cpt"
    "pushpress-integration"
    "votely-poll-vote-system-by-wpgens"
    "cotacao-moedas-hoje"
    "wp-cyr-cho"
    "genesis-taxonomy-images"
    "wpc-coupon-listing"
    "zd-pre-loader"
    "woo-cdek"
    "test-gateway-for-woocommerce"
    "clickskeks"
    "woo-inventory-count"
    "wp-auto-top"
    "count-all"
    "comment-form-shortcode"
    "blocks-by-weaver"
    "quform-zapier"
    "tribe-object-cache"
    "jpic-wordpress-widget"
    "redirect-page"
    "add-to-feedly"
    "lh-user-taxonomies"
    "emails-no-spam"
    "space-remover"
    "poli-payments-for-woocommerce"
    "linkedin-resume"
    "ai-addons-for-elementor"
    "edd-blocks"
    "custom-csv-exporter"
    "monopay"
    "woo-mobile-bottom-bar"
    "bmi-imc-calculator"
    "artplacer-widget"
    "dx-auto-tags"
    "opennode-for-woocommerce"
    "amazon-affiliate-link-globalizer"
    "tsp-featured-categories"
    "webpurifytextreplace"
    "3d-image-gallery"
    "woo-product-price-x-quantity-preview"
    "ziggeo"
    "woocom-add-multiple-products"
    "league-table-standings"
    "backlink-checker"
    "ical-feeds"
    "htaccess-site-access-control"
    "gust"
    "developress-sticky-footer-bar"
    "wpcountdown"
    "googlyzer"
    "twitter-bubble"
    "wp-oer"
    "woo-best-selling-products"
    "doccheck-login"
    "wp-copy-content-protection"
    "scand-osticket-connector"
    "woo-product-carousel-and-zoom"
    "uix-slideshow"
    "feed-to-post"
    "wpsite-comment-moderator"
    "ultimate-coming-soon"
    "nepali-date-converter"
    "taxonomy-list"
    "unitydog"
    "registration-honeypot"
    "hello-serenity"
    "for-users-only"
    "ultimate-colors"
    "wp-twitter-widget-by-ryoking"
    "inbound-rocket"
    "smart-category-ordering"
    "news-magazine-and-blog-elements"
    "vstemplate-creator"
    "cf7-form-submission-limit-wpappsdev"
    "ads-easy-simple-for-ads-into-post"
    "publicize-with-hashtags"
    "change-wp-page-permalinks"
    "wp-mailhog-smtp"
    "affiliates-manager-simple-membership-integration"
    "wp-block-referral-spam"
    "gamipress-block-users"
    "cookiepro-ccpa"
    "docket-wp"
    "wp-immo-manager"
    "home-categories"
    "azurecurve-flags"
    "incapsula"
    "flat-shipping-rate-by-city-for-woocommerce"
    "gravity-forms-to-excel-addon"
    "dd-contact-form"
    "logo-showcase-free"
    "add-all-nav-links-to-bp-adminbar"
    "wp-font-pairing-preview"
    "smp-twitter-module-oauth"
    "joomsport-achievements"
    "wp-database-optimizer-tools"
    "am-login-logo"
    "comments-capcha-box"
    "meta-box-beaver-themer-integrator"
    "multi-functional-flexi-lightbox"
    "brix-page-builder"
    "tangofy"
    "wp-jquery-accordion-menu"
    "lct-useful-shortcodes-functions"
    "category-and-post-accordion-panel"
    "pay-wp"
    "nleilian-guanjc"
    "pwa4wp"
    "what-template-am-i-using"
    "whmcs-domain-checker"
    "simple-cookie-notice"
    "woorousell"
    "bbpress-mark-as-read"
    "tweetmeme-button"
    "madek-oembed"
    "gravity-forms-data-persistence-add-on-reloaded"
    "genesis-prose-extras"
    "author-work-in-progress-bar"
    "canto"
    "product-cloudzoom-ultimate-for-woocommerce-product-images"
    "woo-product-dropdown-widget"
    "smart-image-loader"
    "free-online-article-rewriter"
    "cww-connector-lite"
    "the-loops"
    "flickr-viewer"
    "marquee-style-rss-news-ticker"
    "multi-order-for-woocommerce"
    "woocommerce-retargeting"
    "simple-bookmarking"
    "free-sms-verification-for-gravity-forms"
    "pixelating-image-slideshow-gallery"
    "pressroom"
    "mentionable"
    "silverlight-gallery"
    "standard-xml-sitemap"
    "box-now-delivery"
    "corona-update"
    "userengage-live-chat-marketing-automation-integration"
    "addonsuite-for-wpadverts"
    "core37-form-builder"
    "iosec-anti-flood-security-gateway-module"
    "engagebay-landing-page-builder"
    "wp-flashcard-lite"
    "wpdevdesign-rankmath-integration-for-oxygen"
    "academy-certificates"
    "disable-jquery-migrate"
    "advance-bank-payment-transfer-gateway"
    "multilevel-navigation-menu"
    "wp-post-corrector"
    "ftp-to-zip"
    "tag-generator"
    "count-posts-in-a-category"
    "animated-mouse-cursor-trail"
    "eshop-csv-export"
    "enable-database-tools"
    "iframe-lazy-load"
    "better-blockquotes"
    "edd-favorites"
    "round-social-media-buttons"
    "directpay-ipg-woocommerce"
    "rss-feed-news-blocks-free"
    "custom-posts-per-page-reloaded"
    "wp-syntax-download-extension"
    "wp-sticky-social"
    "sharing-image"
    "smart-mockups"
    "multi-byte-converter"
    "topbar-for-genesis"
    "anchor-links"
    "transcy"
    "kingkongcart"
    "dbview"
    "hide-user-profile-fields"
    "simple-graph"
    "wp-dropstream"
    "twitter-follow-button-shortcode"
    "wp-revisions-limit"
    "demo-mode"
    "without-payment-for-woocommerce"
    "kofthitscounter"
    "shortcodes-anywhere"
    "random-posts-mp3-player-sharebutton"
    "media-files-tools"
    "wp-zan"
    "bbpress-live"
    "youtube-playlist-thumbs"
    "ram108-typo"
    "edd-mollie-gateway"
    "change-prices-with-time-for-woocommerce"
    "web-application-firewall"
    "flickr-api"
    "fansee-themes-demo-data"
    "vimeo-sidebar-widget"
    "pppp"
    "allpay-aio-for-woocommerce"
    "find-us"
    "customize-login-page"
    "wc-product-author"
    "bbpress-topic-thumbnails"
    "index-press"
    "brainesia-scoll-effect"
    "search-bbpress"
    "product-country-restrictions"
    "comment-meta-display"
    "bunny-companion"
    "easy-events-manager"
    "comment-blacklist-updater"
    "jigsaw-planet"
    "affiliate-disclosure-statement"
    "topup-plus"
    "supreme-maps"
    "clean-wp-admin-menu"
    "skysa-polls-app"
    "hestia-nginx-cache"
    "otm-accessibly"
    "education-connect"
    "blocks-kit"
    "sx-no-homepage-pagination"
    "product-badge-manager-for-woocommerce"
    "calendrier-lunaire"
    "lmbbox-smileys"
    "custom-datepicker-nmr"
    "cricket-score"
    "mybooking-reservation-engine"
    "testimonial-slider-shortcode"
    "advanced-wplink"
    "accessibility-font-resizer"
    "relevant-adsense-ads"
    "history-log-by-click5"
    "promobar"
    "wpyar-edd-saman-bank-gateway"
    "ap-twitter-follow-button"
    "bootstrap-multi-language-responsive-portfolio"
    "remove-special-characters-from-permalinks"
    "superfast-seo"
    "full-text-search"
    "woo-worldpay-hosted-payment-gateway"
    "wp-event-calendar"
    "wordpress-phpbb-last-topics-plugin"
    "wp-calais-archive-tagger"
    "sharespine-woocommerce-connector"
    "nokia-mapsplaces"
    "lupsonline-link-netwerk"
    "page-and-post-lister"
    "custom-widget-classes"
    "buddypress-desktop-notification"
    "delivery-and-pickup-scheduling-for-woocommerce"
    "clean-wp-dashboard"
    "national-weather-service-alerts"
    "wp-simple-calendar"
    "internal-link-builder"
    "author-bio-shortcode"
    "woocommerce-pay-to-upload-modification"
    "custom-iframe-widget"
    "show-menu-shortcode"
    "woo-shipperhq"
    "adblock-x"
    "wireless-wordpress"
    "pastebin-embed"
    "huurkalender-wp"
    "vertical-tab-slider"
    "azan"
    "ozh-colourlovers-admin-css-designer"
    "wn-elementor-glassy"
    "wp-api"
    "tc-custom-taxonomy-filter"
    "jonimo-simple-redirect"
    "erropix-hydrogen-paste"
    "winterlock"
    "language-field"
    "restrict-page-parents"
    "modern-images-wp"
    "display-remote-posts-block"
    "fixed-menu-anchor"
    "jonradio-remember-me"
    "blog-as-pdf"
    "wp-news-feed-widget"
    "eonet-project-manager"
    "multicarousel"
    "football-game-by-kashan-shah"
    "australian-weather-widget-willyweather"
    "colored-admin-post-list"
    "modus-youtube-channel"
    "theme-blvd-featured-image-link-override"
    "all-in-one-accessibility"
    "conversion-and-remarketing-code"
    "igumbi-online-booking"
    "remove-add-to-cart-button-for-woocommerce"
    "slider-thumbails"
    "theme-blvd-string-swap"
    "product-filter-widget-for-elementor"
    "intellectual-property-basic"
    "file-groups"
    "totalrating"
    "evolution-twitter-timeline"
    "archive-remote-images"
    "wp-different-navigation-on-each-page-and-post"
    "the-tech-tribe"
    "easyredirect"
    "tina-mvc"
    "socibook"
    "gravity-forms-icontact"
    "mailster-sparkpost"
    "payform"
    "master-qr-generator"
    "activechat-ai"
    "weather-and-time"
    "nic-photo-editor"
    "vikrestaurants"
    "badr-naver-syndication"
    "ajax-comment-loading"
    "wp-scroll-posts"
    "echbay-optimize-images"
    "pmpro-import-members-from-csv"
    "bitmate-author-donations"
    "basic-seo"
    "absolute-addons"
    "gf-dynamics-crm"
    "jquery-hover-footnotes"
    "arukereso-for-woocommerce"
    "mopinion-feedback-form"
    "bp-activity-comment-notifier"
    "support-chat"
    "wp-ajax-login-and-register"
    "eventin-divi-addon"
    "pagos-moviles-peru"
    "quick-payment-by-upi"
    "buddypress-restrict-messages"
    "wp-open-last-modified"
    "custom-tag-widget"
    "baidu-ping-booster"
    "simple-aweber-integration"
    "quantity-increment-buttons-for-woocommerce"
    "html-landing-page"
    "list-more-custom-field-names"
    "safly-curl-patch"
    "igit-related-posts-widget"
    "markethingme-free-social-media-auto-submitter"
    "delete-post-revision"
    "genesis-featured-grid"
    "woo-ajax-mini-cart"
    "css-menumaker"
    "everse-starter-sites"
    "spiritual-gifts-survey"
    "simple-syntax-highlighting"
    "simple-payment"
    "custom-forgot-mail"
    "post-meta-manager"
    "enable-mastodon-apps"
    "custom-style-script"
    "sale-counter"
    "walmart-affiliate-link"
    "mini-cart-for-woocommerce"
    "pootle-slider"
    "tablesearch"
    "fast-flow-dashboard"
    "stidner-shipping-payson-checkout"
    "socail-profile-linking"
    "better-wordpress-showhide-elements"
    "poll-directory"
    "smtp-settings-for-gravity-forms"
    "flickr-press"
    "category-ajax-chain-selects"
    "sourceplay-navermap"
    "inkgo-product-personalizer-for-woocommerce"
    "simple-google-street-view"
    "nicen-localize-image"
    "library-viewer"
    "globe-gateway-e4"
    "hoplix-print-on-demand-platform"
    "bamboo-slides"
    "animate-in-view"
    "yandex-mail"
    "display-avatars"
    "auto-copyright-year-updater"
    "neat-slider"
    "get-widget-id"
    "break-out-of-frames"
    "wp-contentools"
    "minequery-widget"
    "dpo-group-for-woocommerce"
    "advanced-google-maps-lite"
    "auto-last-youtube-video"
    "possibly-related-recent-posts"
    "wp-course-manager"
    "essential-wp-real-estate"
    "rselements-lite"
    "coupon-lite"
    "faster-appearance-menus"
    "wp-reading-list"
    "wpf-ultimate-carousel"
    "internal-link-manager"
    "search-engine-query-in-wordpress-related-contents"
    "wp-change-custom-post-slug"
    "accu-auto-backup"
    "marketer-addons"
    "wplr-theme-assistant"
    "random-posts-within-date-range-widget"
    "never-moderate-registered-users"
    "wsanalytics-google-analytics-and-dashboards"
    "firework-videos"
    "store-locator-widget"
    "gf-block-email-domains"
    "extra-options-favicons"
    "bokez-awesome-gutenberg-blocks"
    "ip-ban"
    "formdesigner"
    "thirstyaffiliates-for-foogallery-extension"
    "ttxml-importer"
    "tiny-google-analytics"
    "responsive-and-swipe-slider"
    "gui-for-lcp"
    "storefront-wishlist"
    "tp-product-description-in-loop-for-woocommerce"
    "kul-maintenance"
    "addfunc-wysiwyg-helper"
    "yahoo-news-feed"
    "pushed-push-notifications"
    "wowpi"
    "wp-xprs-page-builder"
    "freelancer"
    "likebot"
    "bitcoin-payments"
    "email-as-username-for-wp-members"
    "woocommerce-my-downloads-shortcode"
    "page-layout"
    "high-risk-payments-for-woo"
    "enable-latex"
    "easy-options-for-woocommerce"
    "biblia-y-concordancia"
    "hide-block"
    "wp-weixin-robot"
    "wzbaibaoxiang"
    "awesome-coming-soon"
    "wp-restaurant-price-list"
    "embed-block-for-github"
    "featured-image-pro"
    "imghaste"
    "cvw-social-share"
    "wp-frame-breaker"
    "sprout-clients"
    "engagebay-livechat"
    "live-blogging-plus"
    "scroll-rss-excerpt"
    "easy-bitcoin-donation-widget"
    "wpcacheon"
    "league-table-lite"
    "plugins-condition"
    "hosting-monitor"
    "history-timeline"
    "woo-escrow-gateway"
    "frame-breaker-removes-digg-bar-owly-bar-facebook-bar-etc"
    "remove-redundant-links"
    "simplesplash"
    "ads-master"
    "wp-force-images-download"
    "block-patterns-for-food-bloggers"
    "author-slug"
    "affiliate-links-manager"
    "daily-verse"
    "collage-for-divi"
    "menu-humility"
    "full-circle"
    "better-nearby-posts-links"
    "wp-for-my-clients"
    "boxy-woocommerce-custom-redirect-after-checkout"
    "global-meta-keyword-and-description"
    "gs-projects"
    "easy-support-videos"
    "push-notification-by-feedify"
    "internal-link-widget"
    "dashbar"
    "flickr-wp-widget"
    "accessibility-spring"
    "resource-booking-and-availability-calendar"
    "wavr"
    "lazy-content-slider"
    "wangguard-wysija-newsletter-connector"
    "dailymotion-search-and-publish-videos"
    "wp-post-email-notification"
    "my-snippets"
    "bosima-wechat-page-sharing"
    "simple-linked-variations-for-woocommerce"
    "extended-page-lists"
    "enable-virtual-card-upload-vcardvcf"
    "wysiwyg-inline-code-command"
    "snapycode-mail-ur-friend"
    "jj-swfobject"
    "genesis-gtm4wp"
    "inherit-featured-image"
    "badges-woo"
    "thanh-toan-chuyen-khoan"
    "additional-tax-options-for-woocommerce"
    "get-cash"
    "das-wetter-von-wettercom"
    "estatebud-properties-listings"
    "just-wp-variables"
    "wp-ebay-ads"
    "wc-return-product"
    "yes-co-ores-wordpress-plugin"
    "genesis-whats-new-info"
    "wp-dobby"
    "wp-church-center"
    "profile-picture"
    "wordpress-filter"
    "linkify-tags"
    "listsearch"
    "after-the-deadline-for-buddypress"
    "wc-remove-bg"
    "responsive-news-announcements"
    "extended-table-of-contents-with-nextpage-support"
    "ultimate-timeline"
    "open-graph"
    "acf-role-selector-field"
    "easy-whatsapp-contact"
    "cyclone-widget"
    "jquery-slider-carsousel"
    "custom-post-type-ajax-pagnaition"
    "wp-monsterid"
    "simply-excerpts"
    "default-post-content"
    "freshjet"
    "squad-payment-gateway"
    "paginated-gallery"
    "cpt-ajax-load-more"
    "hide-author-archive"
    "wordpress-plugin-ajax-calendar-with-future-posts"
    "improved-cron"
    "seo-local-rank"
    "wc-restricted-shipping-and-payment"
    "list-plugins"
    "plugins-on-steroids"
    "pixelstats"
    "wp-webcam-widget-shortcode"
    "eonet-frontend-publisher"
    "awesome-color-palettes"
    "wp-to-diaspora"
    "woo-line-notify"
    "ephemeris"
    "wp-ajax-pagination"
    "remove-link-url"
    "slightly-troublesome-permalink"
    "ikhokha-payment-gateway"
    "limit-groups-per-user"
    "storefront-visual-guide"
    "magyar-video-embed"
    "live-news-lite"
    "simple-project-managment"
    "optimized-dropdown-menus"
    "wp-title-case"
    "xox-woocommerce-slidercarousel"
    "scroll-bar-with-back-to-top"
    "mylisting-elementor-toolkit"
    "swiper-js-slider"
    "wp-term-icons"
    "wp-share-list"
    "crucial-real-estate"
    "extra-feed-links"
    "colormeshop"
    "flash-games-page"
    "antispambot"
    "remove-wp-logo-from-admin-bar"
    "nelio-popups"
    "dh-local-seo"
    "wpwh-wp-reset-webhook-integration"
    "mention-comments-authors"
    "tinynav"
    "automation-web-platform"
    "replace-google-fonts-with-bunny-fonts"
    "payment-gateways-by-shipping-for-woocommerce"
    "order-signature-for-woocommerce"
    "easy-booked"
    "defer-css-addon-for-bwp-minify"
    "ultimate-wp-captcha"
    "ngg-smart-image-search"
    "prettify-gc-syntax-highlighter"
    "aliprice"
    "page-post-notes"
    "category-country-aware"
    "email-keep"
    "auto-delete-applications-add-on-for-wp-job-openings"
    "force-pclzip"
    "non-purchasable-woocommerce-products"
    "text-advertisements"
    "related-post-inside-plugin"
    "wp-commerce7"
    "p2p-wpml"
    "upload-janitor"
    "blockons"
    "sogrid"
    "wp-simple-spamcheck"
    "mas-woocommerce-variation-swatches"
    "call-to-action"
    "ody-events"
    "flexidx-home-search"
    "simple-https-redirect"
    "unify"
    "thirteen-colors"
    "frndzk-photo-lightbox-gallery"
    "scribd-doc-embedder"
    "two-factor-login-telegram"
    "external-rss-reader"
    "gmap-targeting"
    "casengo-faq-web-self-service-plugin"
    "rss-feed-validator"
    "hide-or-cut-post-text"
    "jquery-latest-news-ticker"
    "post-category-prev-next-link-fix"
    "systasis-gf-infusionsoft-feed"
    "wp-widget-changer"
    "woocommerce-product-navigation"
    "frontier-set-featured"
    "simple-bar"
    "multistep-checkout-for-woocommerce"
    "cachebuster"
    "fc-retirement-savings-calculator"
    "groupon-master"
    "popup-lightbox"
    "redirect-to-404"
    "chatbase"
    "transifex-live-integration"
    "wp-sitemap-pages-and-posts"
    "calendar-posts"
    "compressx"
    "tiempo"
    "itunes-podcast-review-manager"
    "dot-htmlphpxml-etc-pages"
    "survicate"
    "contact-form-7-textarea-wordcount"
    "category-widgets"
    "rename-wp-loginphp-to-anything-you-want"
    "oganro-travel-online-booking-system"
    "ripple-themes-toolset"
    "pop-up-ads-bottom-right-corner"
    "delicious-xml-importer"
    "my-portfolio-plus"
    "skt-donation"
    "covid-19-bangladesh-live"
    "gist-github-shortcode"
    "bbpress-notices"
    "accessibility-new-window-warnings"
    "yandex-speller-application"
    "jwp-a11y"
    "wp-cycle-plus-captions"
    "airdrop"
    "enhanced-linking"
    "image-size-selection-for-divi"
    "try-on-for-woocommerce"
    "wp-parsi-statistics"
    "serenity-theme-extensions"
    "toplytics"
    "wp-exit-page-redirect"
    "user-registration-using-contact-form-7"
    "embed-image-links"
    "simple-image-xml-sitemap"
    "beautiful-link-preview"
    "bugfu-console-debugger"
    "knowledge-center"
    "mycred-bp-group-leaderboards"
    "google-plus-comments-by-forum-gt"
    "silvasoft-boekhouden"
    "wp-spotify"
    "wp-footer-menu"
    "fast-easy-social-sharing"
    "spiff-3d-product-customizer"
    "sl-logo-slider"
    "responsive-tabs-for-elementor"
    "simple-image-watermark"
    "gallery-image-gallery-photo"
    "webme-cookie-privacy"
    "genesis-widget-toggle"
    "connector-woo-odoo"
    "woo-dpd"
    "wb-sticky-notes"
    "conditional-payments"
    "time-goes-by"
    "eg-archives"
    "easy-slide-show"
    "revoffers-advertiser-integration"
    "wp-sequence-slider"
    "asd-123-456-widget"
    "claim-alexa"
    "google-news-keywords-from-tags"
    "vimeo-everywhere"
    "nfeeds-free-mobile-app"
    "payamito-sms-woocommerce"
    "parse-url"
    "fresh-plugins"
    "genoo"
    "lao-fonts"
    "hover-pin-it"
    "deviant-thumbs"
    "dbwd-bookmark-page"
    "jp-for-twentytwentyone"
    "woo-products-filter"
    "always-valid-lightbox"
    "add-users-sidebar-widget"
    "aws-easy-page-link"
    "dj-on-air-widget"
    "rss-feed-readmore-link"
    "advanced-typekit"
    "tally-theme-setup"
    "img-title-restore"
    "jetpack-shortlinks-for-sharing-buttons"
    "faq-schema-ultimate"
    "oembed-for-360player-io"
    "product-categories-bottom-description-woo-comerce"
    "ecomail"
    "woo-video-gallery"
    "simpleshift-companion"
    "gnupress"
    "aztolat"
    "coming-soon-master"
    "wp-responsive-meet-the-team"
    "wp-syndicate"
    "comment-count"
    "wp-quick-shop"
    "category-posts-tabber"
    "wp-discord-invite"
    "post-types-carousel-slider"
    "surly"
    "deadblocker"
    "deutschdate"
    "splide-carousel"
    "automatic-glossary"
    "404-silent-salesman"
    "wp-shabbat"
    "wp-export-users-plus"
    "foodle-for-democracy-poll"
    "simple-seo-slideshow"
    "logout-clear-cookies"
    "uk-tides"
    "maxmindeu-hotel-reservations"
    "brozzme-add-plugins-thumbnails"
    "velocity"
    "really-simple-xml-and-html-sitemap"
    "co2ok-for-woocommerce"
    "woo-order-cancel-for-customers"
    "genesis-shortcode-generator"
    "current-bitcoin-price"
    "create-a-league"
    "tiny-bar"
    "debug-toolkit"
    "interactive-image-map-builder"
    "easy-popup-lightbox-maker"
    "no-weak-passwords"
    "precious-metals-automated-product-pricing-pro"
    "better-revisions"
    "mmunicode-embed"
    "cits-support-svg-webp-media-upload"
    "disable-wordpress-widgets"
    "woocommerce-shipping-options"
    "date-range-filter"
    "email-capture-lead-generation"
    "video-background-block"
    "related-items"
    "image-slideshow-pearlbells"
    "amr-cron-manager"
    "remita-payment-gateway"
    "kento-3d-model-viewer"
    "page-excerpts"
    "post-carousel-slider"
    "wordpress-easy-allopass"
    "evm-portfolio"
    "in-post-rss-feeds"
    "zi-hide-featured-image"
    "plugversions"
    "pd-android-fcm"
    "download-pdf-after-submit-form"
    "about-us-widget"
    "connector-for-woocommerce-and-zoho-crm"
    "antibot-captcha"
    "cool-correo-argentino-woo"
    "tsw-custom-listing"
    "bulk-change-media-author"
    "occupancy-plan"
    "frase"
    "bmi-calculator"
    "localizejs"
    "wpstatuscake"
    "zip-attachments"
    "database-to-excel"
    "cf7-referrer-tracker"
    "slide-everything-for-elementor"
    "team-section"
    "sliceshow"
    "residential-address-detection"
    "ss-font-awesome-icon"
    "custom-post-display"
    "amocrm-webform"
    "article-forge"
    "cost-calculator"
    "menu-caching"
    "custom-css-for-pages-and-posts"
    "share-link"
    "foodbook-light-online-food-ordering-system"
    "wc-order-tracker"
    "multi-crypto-currency-payment"
    "gsheetconnector-caldera-forms"
    "gravity-forms-image-in-html"
    "show-visitor-ip-address"
    "wp-core-update-cleaner"
    "bbcode-deluxe"
    "seriously-simple-podcasting-genesis-support"
    "android-webcam-and-timelapse"
    "catch-social-share"
    "woocommerce-custom-tab-lite"
    "toolshot-player"
    "call-now-button-ultimate"
    "display-exif"
    "wp-weixin-pay"
    "acf-starrating"
    "browser-body-classes-with-shortcodes"
    "christmas-decorations"
    "powies-irc-chat"
    "ap-google-maps"
    "all-push-notification"
    "which-addon-for-elementor"
    "ninja-shop"
    "simplebooklet"
    "jetpack-easy-playlists"
    "aw-yearly-category-archives"
    "recent-love"
    "simple-al-slider"
    "woo-safepay-gateway"
    "360-viewer-light-for-elementor-wpbakery"
    "image-upload-widget"
    "most-comments"
    "dashboard-wordcount"
    "wp-login-security-2"
    "gg-monarch-sidebar-minimized-on-mobile"
    "required-fields"
    "wpmu-simple-dashboard"
    "recent-lastfm-tracks"
    "auto-animateimage"
    "user-avatar-reloaded"
    "autohan"
    "welcome-visitors"
    "equalweb"
    "linkmydeals"
    "fpp-pano"
    "ravpage"
    "tipu-scroll-to-top"
    "wp-query-console"
    "woo-default-attributes"
    "acf-clone-repeater"
    "fun-facts"
    "calendar-category"
    "bp-activity-share"
    "icdsoft-reseller-store"
    "stock-tools"
    "admin-ip-watcher"
    "wp-hash-password"
    "zeus-admin-theme"
    "zmseo"
    "aa-counter"
    "simple-code-block"
    "gn-keyword-news"
    "buddyforms-custom-login-page"
    "recipeseo"
    "solid-post-likes"
    "bookmark-card"
    "acf-repeater-for-elementor"
    "connectpos-pos-system-for-woocommerce"
    "avoid-duplicate-titles"
    "wp-google-street-view"
    "bidorbuystoreintegrator"
    "fusion-extension-divider"
    "j7-beaver-headers-footers"
    "islamic-books"
    "missed-schedule-wordpress-plugin-fix"
    "axp-cyrtolat"
    "wxy-searchmark"
    "widget-for-yandex-zen"
    "force-admin-color-scheme"
    "booking-x"
    "cf7-ui-slider"
    "essential-classy-addons-for-elementor"
    "rio-emi-calculator"
    "twitter-feed-afo"
    "i3geek-mip"
    "delivery-fees-for-woocommerce"
    "font-awesome-menus"
    "memory-game"
    "users-profile-picture"
    "zerobounce"
    "json-ld-breadcrumbs"
    "simple-calendar-acf"
    "quick-view-for-woocommerce"
    "vg-postcarousel"
    "content-snippet-manager"
    "pinecast-wp-sync"
    "rich-text-biography"
    "ere-download-document"
    "bbpress-do-short-codes"
    "cleanerpress"
    "nertworks-super-mega-popup"
    "propel"
    "improvely-for-woocommerce"
    "better-images-crop"
    "wc-delete-orders"
    "ni-woocommerce-sales-report-email"
    "profile-widget"
    "composer"
    "system-snapshot-report"
    "compare-ninja-comparison-tables"
    "vp-telegram-instant-view"
    "pricing-tables"
    "separator-widget"
    "phpinfo-print"
    "business-review"
    "wc-continue-shopping-options"
    "newsletter-email-mailing-list"
    "wp-referral-light"
    "clean-unused-medias"
    "rel-publisher"
    "2048-number-game"
    "team-speak-widget"
    "wp-auto-links"
    "revisions"
    "catch-popup"
    "commentwitter"
    "personio-integration-light"
    "simple-google-map-by-naf"
    "media-from-zip"
    "terra-themes-tools"
    "mantis-ad-network"
    "wx-weather-widget"
    "sticky-banner"
    "resizefly"
    "audio-comments"
    "no-spam"
    "suffusion-commerce-pack"
    "twitter-feed-scroller"
    "shop-assistant-for-woocommerce-jarvis"
    "ays-slider"
    "revised-meta-tag"
    "default-image-link"
    "client-partner-showcase"
    "globalquran"
    "system-report"
    "bwd-elementor-addons"
    "friendstore-for-woocommerce"
    "post-thumbs"
    "wp-excerpt-settings"
    "woo-advanced-product-information"
    "aforms-eats"
    "feed-kuantokusta-for-woocommerce"
    "wc-support-system"
    "just-an-admin-button"
    "really-simple-captcha-for-buddypress"
    "wc-dpd"
    "cbxpoll"
    "wp1"
    "formality"
    "vulnerable-plugin-checker"
    "wp-security-audit-log-add-on-for-bbpress"
    "moova-for-woocommerce"
    "woo-coupon-url"
    "vc-countdown-timer"
    "buddy-notification-bell"
    "questionnaire"
    "saskaita123-lt"
    "wrap-form-fields-in-gravity-forms"
    "simple-seo-improvements"
    "wp-export-users"
    "bluesnap-payment-gateway-for-woocommerce"
    "custom-top-bar"
    "ajaxed-comments"
    "wp-clone-any-post-type"
    "listdomer-core"
    "wp-css3-button-creator-plugin"
    "silencesoft-disable-menu-items"
    "smugmug-responsive-slider"
    "wp-imageviewer"
    "sort-searchresult-by-title"
    "mendeley-profile"
    "neve-hooks"
    "visualmodo-related-posts"
    "tsl-iframe-unfilter"
    "portfolio-type"
    "display-you-tube-videos"
    "flickr-stream"
    "amember-sidebar-widget"
    "restrict-for-elementor"
    "woo-reviews-manually-approved"
    "https-mixed-content-detector"
    "front-page-builder"
    "dc-full-screen-responsive-menu"
    "menu-per-pages"
    "super-cool-qrcode"
    "user-agent-theme-switcher"
    "simple-preview"
    "content-randomizer"
    "dplayer-for-wp"
    "ibamu"
    "blazing-charts"
    "generic-stats"
    "gg-lightbox"
    "dokan-vendor-info-hider"
    "ambrosite-body-class-enhanced"
    "template-editor"
    "kk-youtube-video"
    "search-by-tags"
    "crocodoc"
    "frontier-buttons"
    "syntaxhighlighter2"
    "tumble"
    "wp-prayer-times-waktu-solat-malaysia-malaysia-prayer-times"
    "ajax-weather"
    "fusedesk"
    "live-tv"
    "comparepress"
    "quick-posts"
    "menu-cache"
    "wp-routes"
    "friendconnect-login"
    "wp-employee-attendance-system"
    "customize-tawk-to-widget"
    "typo3-importer"
    "mautic-for-fluent-forms"
    "prevent-landscape-rotation"
    "wp-comment-notifier-for-all"
    "toms-video-player"
    "smallerik-file-browser"
    "mage-google-maps"
    "per-post-scripts-and-styles"
    "html-php-pages-and-posts"
    "gift-wrapping-for-woocommerce"
    "engagebay-woocommerce-addon"
    "simple-google-photos-grid"
    "wp-bing-search"
    "otfm-gutenberg-spoiler"
    "utm-dot-codes"
    "twitter-feed-widget"
    "acf-to-custom-database-tables"
    "invoice-for-woocommerce"
    "dadevarzan-beaver-builder-modules"
    "top-comments"
    "comment-approved-notifier"
    "custom-background-for-post-and-page"
    "s2member-secure-file-uploader"
    "alex-reservations"
    "woo-simply-add-related-products-to-blog-posts"
    "email-form-under-post"
    "autover"
    "force-delete-posts"
    "wc-j-upsellator"
    "show-posts-shortcode"
    "google-chart-generator"
    "change-author-link-structure"
    "snippet-vault"
    "popup-block"
    "custom-login-admin-front-end-css-with-multisite-support"
    "mightyforms"
    "dennisridder-qtx-seo"
    "assets-manager"
    "aw-woocommerce-kode-pembayaran"
    "hana-flv-extension"
    "edd-helpscout"
    "kalendar-cz"
    "convert-address-to-google-maps-link"
    "kelkoogroup-sales-tracking"
    "vr-frases"
    "woo-order-weight"
    "resize-on-upload"
    "rest-api-meta-endpoints"
    "resads"
    "wave-slider"
    "catalog-mode-pricing-enquiry-forms-promotions"
    "chordpress"
    "view-template-widget-for-toolset-types-views"
    "wp-contact-form7-email-spam-blocker"
    "stick-admin-bar-to-bottom"
    "landing-page-rockstar"
    "easy-pdf-restaurant-menu-upload"
    "tyresaddict-woo-tyre-custom-metadata"
    "userswitcher"
    "wp-simple-insert"
    "link-summarizer"
    "navigation-tree-elementor"
    "muzaara-google-content-api-data-feed"
    "access-keys"
    "flashcard"
    "startup-gym-elementor-parallax-section-effect"
    "youtube-quick-shortcode"
    "in-category-order"
    "weedly"
    "wp-chosen"
    "intasend-payment"
    "registro-de-jornada-laboral"
    "nasa-image-of-the-day"
    "gift-message-for-woocommerce"
    "dokan-product-duplicator"
    "documentpress-display-any-document-on-your-site"
    "woocommerce-coming-soon"
    "press-this-extended"
    "first-order-coupon-manager-for-woocommerce"
    "fa-wp-admin-menu-icons"
    "momo-mobile-money-payments-woocommerce-extension"
    "no-frames"
    "woo-product-finder"
    "ajax-slide"
    "w3c-validation-auto-check"
    "ipgp-user-country-flag"
    "wpdevdesign-oxygen-navigator"
    "cf7-cpfcnpj-validations"
    "smugmug-embed"
    "delete-thumbnails"
    "wp-featherlight-disabled"
    "cryptothanks"
    "securiti-cookie-consent"
    "paymaya-checkout-for-woocommerce"
    "ops-robots-txt"
    "substack-importer"
    "sublime-custom-css-editor"
    "autotags"
    "relation-post-types"
    "quick-post-image-widget"
    "imagetext"
    "garmin-connect"
    "sleekplan"
    "vidseo"
    "wpcasa-polylang"
    "bp-who-favorited"
    "carousel-for-divi"
    "bbpress-no-admin"
    "elegant-zazzle-plugin-ezp"
    "loginrequirepress"
    "expresstechsoftwares-memberpress-discord-add-on"
    "post-gallery-and-archive"
    "easytransac"
    "spcl"
    "ig-posts-carousel"
    "seo-sitemap-generator-with-fetch-urls"
    "paytalk-lipa-na-mpesa"
    "ot-zalo"
    "advanced-table-rate-shipping-for-woocommerce"
    "delivery-date-for-woocommerce"
    "wp-wdfy-integration-of-wodify"
    "custom-windows-pinned-tiles"
    "dojo-for-woocommerce"
    "alopeyk-woocommerce-shipping"
    "show-visitor-ip"
    "marctv-quicktags"
    "wp-universal-exchange-informer"
    "wp-documentation-lite"
    "woo-nimiq-gateway"
    "updownupdown-postcomment-voting"
    "auto-scroll-for-reading"
    "mm-chat"
    "iframe-to-embed"
    "gb-powerlink-lite"
    "mythemeshop-theme-customizer"
    "ns-woocommerce-catalog"
    "rssfeedchecker"
    "extended-featured-content-widget"
    "adjustly-collapse"
    "wsl-login-extends-naver"
    "upgrade-for-unattach-re-attach-media-attachments"
    "ultimo-wp"
    "mactrak"
    "wpadmin-stripe-payment-gateway"
    "track-everything"
    "posthaste"
    "pd-woo-tracking-order"
    "ad-logger"
    "woo-subscription-extras"
    "seguros-promo"
    "webhotelier"
    "vagaro-booking-widget"
    "cbxchangelog"
    "recruitly"
    "easy-page-transition"
    "ajax-load-more-for-relevanssi"
    "codepress-menu"
    "bbpress-new-topic-notifications"
    "3d-wp-tag-cloud-m"
    "legal-plus"
    "category-image"
    "bazo"
    "footer-design-for-elementor"
    "wp-admin-cache"
    "xavins-list-subpages"
    "links-in-captions"
    "ace-edit"
    "tweetpost"
    "fields-framework"
    "wp-og"
    "orbisius-cyberstore"
    "interactive-svg-map"
    "statsfc-fixtures"
    "retweet-anywhere"
    "tillit-payment-gateway"
    "sagepay-server-gateway-for-woocommerce"
    "editionguard-for-woocommerce-ebook-sales-with-drm"
    "be-boost"
    "wp-irc"
    "wp-agenda"
    "simple-multisite-sitemaps"
    "wpcafe-multivendor"
    "enlarge-text"
    "bangla-font-solution"
    "posts-of-current-category"
    "link-google-calendar"
    "the-hits-counter"
    "tp-back-to-top"
    "2-klicks-button-socialshareprivacy-plugin"
    "orbisius-simple-notice"
    "advanced-permalink"
    "mypace-custom-title-tag"
    "peanut-butter-bar-smooth-version"
    "iplocationtools-real-time-visitor-widget"
    "ductile-responsive-video"
    "advanced-google-universal-analytics"
    "avoid-duplicate-posts"
    "vote-it"
    "delivery-pickup-reminder-email-woocommerce"
    "link-shortener"
    "amp-story"
    "fusion-extension-contact-form"
    "vk-sharing-jetpack"
    "live-cricket-scores-widget"
    "storefront-pro-skins"
    "easygram"
    "simple-ftp-directory-lister"
    "readmore-readless"
    "optimum-gravatar-cache"
    "wp-job-manager-registration-use-email"
    "text-file-widget"
    "improve-wp-default-social-icons-block"
    "dominion-domain-checker-wpbakery-addon"
    "mage-reviews"
    "post2qzone"
    "wireclub-chat"
    "badgeos-suggested-achievements-add-on"
    "tag-cloud-widget"
    "jt-express"
    "360-view"
    "copy-to-clipboard-mobile-web"
    "local-development"
    "seemore"
    "continue-shopping-anywhere-for-woocommerce"
    "add-to-cart-button-customizations"
    "upper-right-make-it-bright"
    "lms-chat"
    "va-simple-expires"
    "click-to-call-button"
    "badge"
    "bp-xprofile-rich-text-field"
    "best-posts-summary"
    "twitter-display-and-cache"
    "bulk-convert-post-format"
    "screenshot-machine-shortcode"
    "alt-import-drupal"
    "taxonomy-term-widget"
    "aoringo-tag-upper"
    "wpbulky-wp-bulk-edit-post-types"
    "rails-theme"
    "email-subscription-box-after-post-content"
    "nextgen-gallery-z-cropper"
    "aweber-registration-integration"
    "perfectwpthemes-toolkit"
    "speed-up-menu"
    "wpmm-memory-meter"
    "advanced-wpbakery-addons-formerly-visual-composer"
    "multisite-dashboard-switcher"
    "accept-bitcoin-payments-on-woocommerce-thebigcoin"
    "easymaintenance"
    "gf-popup-confirmation"
    "custom-wp-login-page"
    "woogosend"
    "convert-data"
    "cocart-get-cart-enhanced"
    "yd-featured-block-widget"
    "live-drafts"
    "smart-recent-post"
    "gps-plotter"
    "wp-post-views-counter"
    "mmww"
    "bp-xprofile-shortcode"
    "bp-webcam-avatar"
    "svea-webpay-for-woocommerce"
    "permalinks-to-categorypermalinks"
    "gf-datetime-field-add-on"
    "wp-designer"
    "wp-widget-clipboard"
    "post-rotation"
    "printable-pdf-newspaper"
    "add-index-to-autoload"
    "pz-hatenablogcard"
    "simple-lazy-load-videos"
    "jquery-expandable-comments"
    "civievent-widget"
    "gauntlet-security"
    "embedding-barcodes-into-product-pages-and-orders"
    "anrghg"
    "plugin-dependencies"
    "frontend-dashboard-social-chat"
    "attachment-files-importer"
    "hikari-enhanced-comments"
    "ajaxified-cart-woocommerce"
    "image-banner-ads"
    "buddypress-messages-spam-blocker"
    "wp-admin-menu"
    "wpsyncsheets-elementor"
    "timeslot"
    "clear-statpress"
    "cosmosfarm-comments"
    "forms-3rd-party-xpost"
    "trustprofile"
    "pgp-key-generator"
    "ashuwp-invitaion-code"
    "xllentech-english-islamic-calendar"
    "simple-photos-contest"
    "private-wp-suite"
    "clickio-prism"
    "allaccessible"
    "safe-ai-malware-protection-for-wp"
    "unlimited-brands-for-woocommerce"
    "bridge-helper"
    "advanced-custom-fields-widget"
    "page-menus-widget"
    "open-calais"
    "fly-twitter-on-blog"
    "automizely-marketing"
    "wpt-custom-mo-file"
    "easy-image-filters"
    "css-autoloader"
    "woocommerce-gold-price"
    "rtl-bakery"
    "post-type-requirements-checklist"
    "socialall-social-login"
    "help-dialog"
    "tnc-toolbox"
    "inner-page-menu"
    "wp-announce"
    "user-dashboard"
    "responsive-progress-bar"
    "online-active-users"
    "custom-code"
    "wp-e-commerce-currency-helper"
    "xpro-addons-beaver-builder-elementor"
    "contact-form-7-email-verification"
    "aino-accordion-faq-block"
    "wpml-short-code-translator"
    "user-voice"
    "corona-results-bangladesh"
    "ctt-expresso-para-woocommerce"
    "nino-social-connect"
    "diagnosis"
    "hidden-tags"
    "social-networks-facebooktwittergoogle"
    "catch-dark-mode"
    "wp-tools-divi-product-carousel"
    "cookie-notice-consent"
    "bio-links"
    "pdf-builder-for-ninja-forms"
    "wc1c-main"
    "wp-autokeyword"
    "gecka-terms-ordering"
    "advanced-widgets"
    "wordless"
    "inrdeals-url-appender"
    "auto-twitter-followers-stay-informed"
    "shardb"
    "scim-user-provisioning"
    "feedblitz-membermail"
    "user-session-synchronizer"
    "favorite-post"
    "max-music"
    "feefo-ratings-reviews-for-woocommerce"
    "ad-auto-insert-h"
    "maintenance-mode-with-timer"
    "official-makesbridge-web-form-builder"
    "easy-document-embedder"
    "page-loading-animation"
    "amazon-search"
    "seo-landing-page-generator"
    "easy-form"
    "os-integration"
    "recipe-of-the-day"
    "vercel-deploy-hooks"
    "cloudpayments-gateway-for-woocommerce"
    "add-meta-tag-keywords"
    "logo-or-image-replace"
    "dsgvo-google-web-fonts-gdpr"
    "add-image-to-post"
    "cart-link-for-woocommerce"
    "ip2map"
    "zohocreator"
    "imagefx"
    "wp-share-simple"
    "json-api-cincopa"
    "login-page-logo"
    "wp-feedburner-email-subscriber"
    "social-sharing-themesmatic"
    "delicious-plus"
    "dsgvo-de"
    "ecommerce-shopping-cart-by-inventorycom"
    "external-image-replace"
    "multisite-shared-menu"
    "baw-gravatar-google-image"
    "mailboxvalidator-email-validator"
    "press-about-us"
    "trustist-reviewer"
    "tiket-payment-invoicing"
    "cashbill-payment-method"
    "ecommerce-feeder"
    "sinbyte-indexer"
    "friendly-functions-for-welcart"
    "unlimited-page-sidebars"
    "show-template"
    "customizable-captcha-and-contact-us-form"
    "wc-variations-as-single-product"
    "apply-with-linkedin-buttons"
    "ganxy-embed"
    "trueedit"
    "auto-reply-wechat"
    "vindi-payment-gateway"
    "no-comment"
    "bs-banners"
    "aprils-call-posts"
    "wp-post-icon"
    "excerpts-for-pages"
    "sportspress-for-golf"
    "gs-custom-login"
    "euro-2012-predictor"
    "travel-rates-based-on-geo-location"
    "post-forking"
    "sinoshare"
    "rrf-scroll-to-top"
    "disable-login-language-switcher"
    "geniipress-disable-embeds"
    "menu-simple-role"
    "cf7-dynamics-crm"
    "accept-authorize-net-payments-using-contact-form-7"
    "admin-expert-mode"
    "3q-video-connect"
    "hide-related-products-in-woocommerce"
    "portfolio-grid"
    "woo-email-control"
    "woo-customer-coupons"
    "themefuse-extend-user-profile"
    "graphical-admin-report"
    "genially-embed"
    "serbian-addons-for-woocommerce"
    "chosen"
    "scrollarama"
    "affiliates-eshop-light"
    "better-aria-label-support"
    "mycred-paid-memberships-pro"
    "spam-ip-blocker"
    "webp-images"
    "beauty-orange-wordpress-comment-captcha"
    "convertcalculator"
    "swedbank-pay-payments"
    "automatic-links"
    "mas-addons-for-elementor"
    "broken-link-repair"
    "pretty-file-lister"
    "easy-digital-downloads-htaccess-editor"
    "datalayer-for-ecommerce-free"
    "remove-protected"
    "truth"
    "geniipress-auto-pinch-zoom"
    "green-life-custom-scrollbar"
    "to-title-case"
    "featuring-countcomments"
    "f4-tree"
    "remove-parents"
    "animation-addons-for-elementor"
    "html-emails"
    "wp-zen-coding"
    "socialshare"
    "instant-comment-validation"
    "vertical-image-menu"
    "voice-widgets"
    "plagibot-plagiarism-checker"
    "xrely-autocomplete"
    "ns-sending-update-email"
    "resaline"
    "my-youtube-videos"
    "wp-content-slideshow-reborn"
    "coming-soon-with-divi-soon"
    "asta-html-minifier"
    "the-events-calendar-pro-alarm"
    "contact-form-7-response-message-popup"
    "add-link"
    "iis-chinese-tag-permalink"
    "steemeasy"
    "paw-masonry-gallery"
    "wp-nofollow-categories"
    "seo-blogroll"
    "wp-cookies-alert"
    "tyresaddict-woo-tyre-product-filter"
    "wp-customize"
    "gallery-media-tags"
    "cardboard"
    "rich-category-editor"
    "browser-update-ribbon"
    "show-hidden-post-meta"
    "doshii"
    "back-to-the-top"
    "incogneato-anonymous-suggestion-box"
    "contentoptin"
    "restrict-taxonomies"
    "ni-woocommerce-payment-gateway-charges"
    "verowa-connect"
    "in-over-your-archives"
    "wee-remove-xmlrpc-methods"
    "flexible-modals"
    "wayfinder"
    "oembed-in-comments"
    "sticky-button"
    "superlist-block"
    "miappi-social-wall"
    "wp-my-twitter"
    "wp-super-subdomains"
    "generate-box"
    "force-full-width-shortcode"
    "pretty-comments"
    "track-page-scroll"
    "statsfc-live"
    "remove-wp-generator-meta-tag"
    "buy-this-book"
    "wpsmf"
    "category-search"
    "wptoandroid"
    "wp-frontend-submit"
    "osticket-wp-bridge"
    "extended-user-search-in-wp-admin"
    "term-duplicator"
    "hm-cool-author-box-widget"
    "dynamic-dates"
    "wp-crosspost"
    "wp-noindex"
    "add-html-to-pages"
    "af-tell-a-friend"
    "optune"
    "skysa-rss-reader-app"
    "greek-multi-tool"
    "minim-by-tourwriter"
    "pinglunla"
    "countdown-timer-abt"
    "default-attributes-for-woocommerce"
    "media-features"
    "montapacking-checkout-woocommerce-extension"
    "wp-super-redes-sociais"
    "b1-accounting"
    "last-updated"
    "rapid-cache"
    "safe-mode"
    "zephyr-modern-admin-theme"
    "export-all-post-meta"
    "vertical-carousel-slider"
    "monei"
    "show-the-weather-jp"
    "webpayplus-pst"
    "wpglobus-for-black-studio-tinymce-widget"
    "byteplant-phone-validator"
    "entries-importing-for-gravity-forms"
    "woo-wechatpay"
    "revision-notes"
    "vitrine-submarino"
    "make-filename-lowercase"
    "ada-feedwordpress-keyword-filters"
    "acf-city-selector"
    "mindcat"
    "wp-landing-page"
    "linear"
    "wp-s3-backups"
    "wsb-hub3"
    "lambdatest-screenshot"
    "linklaunder-seo-plugin"
    "add-wpgraphql-redirection"
    "pmpro-infusionsoft"
    "bbt-pinterest-optin"
)

# Define user agents with weights
declare -A USER_AGENTS
USER_AGENTS=(
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"]=5
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"]=7
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"]=6
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36 Edg/91.0.864.54"]=5
    ["Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 OPR/77.0.4054.277"]=3
    ["Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (iPad; CPU OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Vivaldi/4.0"]=1
    ["Mozilla/5.0 (Android 11; Mobile; rv:68.0) Gecko/68.0 Firefox/88.0"]=1
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"]=15
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/534.36"]=12
)

OPENED_PLUGINS_FILE="${WORDPRESS_WORKDIR}/opened_plugins.txt"
CLOSED_PLUGINS_FILE="${WORDPRESS_WORKDIR}/closed_plugins.txt"
LAST_VERSION_FILE="${WORDPRESS_WORKDIR}/last_versions.txt"
PARALLEL_JOBS=1

DOWNLOAD_ALL_PLUGINS='n'
LIST_ONLY='n'
ALL_PLUGINS_FILE="${WORDPRESS_WORKDIR}/wp-plugin-svn-list.txt"

DELAY_DOWNLOADS='n'
DELAY_DURATION=5

FORCE_UPDATE='n'
CACHE_ONLY='n'

mkdir -p "$WORDPRESS_WORKDIR" "$MIRROR_DIR" "$LOGS_DIR"
rm -f "$OPENED_PLUGINS_FILE"
touch "$OPENED_PLUGINS_FILE"
DEBUG_MODE=0

while getopts "p:dalD:t:fc" opt; do
    case ${opt} in
        p ) PARALLEL_JOBS=$OPTARG ;;
        d ) DEBUG_MODE=1 ;;
        a ) DOWNLOAD_ALL_PLUGINS='y' ;;
        l ) LIST_ONLY='y' ;;
        D ) DELAY_DOWNLOADS=$OPTARG ;;
        t ) DELAY_DURATION=$OPTARG ;;
        f ) FORCE_UPDATE='y' ;;
        c ) CACHE_ONLY='y' ;;    # New option for cache-only
        \? ) echo "Usage: $0 [-p PARALLEL_JOBS] [-d] [-a] [-l] [-D DELAY_DOWNLOADS] [-t DELAY_DURATION] [-f] [-c]" 1>&2; exit 1 ;;
    esac
done

debug_log() {
    if [ "$DEBUG_MODE" -eq 1 ]; then
        echo "[DEBUG] $1" >&2
    fi
}

get_random_user_agent() {
    echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
}

get_latest_version_and_download_link() {
    local plugin=$1
    debug_log "Checking latest version and download link for $plugin"
    
    local api_url="https://api.wordpress.org/plugins/info/1.0/${plugin}.json"
    local user_agent=$(get_random_user_agent)
    local api_response=$(curl -s -H "User-Agent: $user_agent" "$api_url")
    
    if echo "$api_response" | jq -e '.error' >/dev/null; then
        local error_message=$(echo "$api_response" | jq -r '.error')
        if [ "$error_message" = "closed" ]; then
            echo "closed"
            return 2
        else
        echo "Error: $error_message for plugin $plugin" >&2
        return 1
        fi
    fi
    
    local version=$(echo "$api_response" | jq -r '.version // empty')
    local download_link=$(echo "$api_response" | jq -r '.download_link // empty')
    
    if [ -n "$version" ] && [ -n "$download_link" ]; then
        echo "$version $download_link"
        return 0
    else
        echo "Error: Cannot fetch version or download link for $plugin" >&2
        return 1
    fi
}

download_plugin() {
    local plugin=$1
    local version=$2
    local api_download_link=$3
    local output_file="${MIRROR_DIR}/${plugin}.${version}.zip"
    local header_file="${LOGS_DIR}/${plugin}.${version}.headers"
    local constructed_download_link="${DOWNLOAD_BASE_URL}/${plugin}.${version}.zip"
    local download_link

    if [ "$DEBUG_MODE" -eq 1 ]; then
        debug_log "API-provided download link for $plugin: $api_download_link"
        debug_log "Constructed download link for $plugin: $constructed_download_link"
    fi

    if [ "$DOWNLOAD_LINK_API" == 'y' ] && [ -n "$api_download_link" ]; then
        download_link="$api_download_link"
        debug_log "Using API-provided download link for $plugin: $download_link"
    else
        download_link="$constructed_download_link"
        debug_log "Using constructed download link for $plugin: $download_link"
    fi

    debug_log "Downloading $plugin version $version through Cloudflare Worker"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)
    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o /dev/null "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    else
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o "$output_file" "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    fi

    if [ $? -eq 0 ]; then
        if [ "$CACHE_ONLY" == 'y' ]; then
            debug_log "Plugin $plugin version $version cached successfully."
            return 0
        fi

        local file_size=$(stat -c%s "$output_file")
        if [ "$file_size" -lt 1000 ]; then
            echo "Error: Downloaded file for $plugin is too small (${file_size} bytes). Possible download issue." >&2
            return 1
        fi

        local source=$(grep -i "X-Source:" "$header_file" | cut -d' ' -f2 | tr -d '\r')
        if [ "$source" == "R2" ]; then
            debug_log "Successfully downloaded $plugin version $version from R2 storage"
        elif [ "$source" == "WordPress" ]; then
            debug_log "Successfully downloaded $plugin version $version from WordPress"
            debug_log "R2 bucket saving for plugin zip occurred"
        else
            debug_log "Skipped download for $plugin $version zip (already exists locally)"
        fi

        return 0
    else
        echo "Error: Failed to download $plugin version $version" >&2
        return 1
    fi
}

save_plugin_info() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.json"

    debug_log "Saving plugin json metadata for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying metadata download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    if [ "$CACHE_ONLY" == 'y' ]; then
        # When in cache-only mode, output to /dev/null
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin metadata for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache json metadata for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            if [ "$source" = "R2" ]; then
                debug_log "json metadata for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "json metadata for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin json occurred"
            else
                debug_log "json metadata for $plugin version $version saved (json metadata file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save json metadata for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

fetch_and_save_checksums() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.checksums.json"

    debug_log "Fetching and saving checksums for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying checksums download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    debug_log "Sending request to Worker for checksums: CF_WORKER_URL?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"

    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin checksums for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache checksums for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        debug_log "Received response with status code: $status_code"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            debug_log "Response source: $source"
            if [ "$source" = "R2" ]; then
                debug_log "Checksums for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "Checksums for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin checksums occurred"
            else
                debug_log "Checksums for $plugin version $version saved (checksums file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save checksums for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

process_plugin() {
    local plugin=$1

    # Check if the plugin is already known to be closed
    if grep -q "^$plugin$" "$CLOSED_PLUGINS_FILE" 2>/dev/null; then
        echo "Plugin $plugin is known to be closed. Skipping."
        return 0
    fi

    echo "Processing plugin: $plugin"

    VERSION_AND_LINK=$(get_latest_version_and_download_link "$plugin")
    local version_check_status=$?
    
    if [ $version_check_status -eq 1 ]; then
        echo "Skipping $plugin due to version fetch error."
        return 1
    elif [ $version_check_status -eq 2 ]; then
        echo "Plugin $plugin is closed. Skipping download and processing."
        echo "$plugin" >> "$CLOSED_PLUGINS_FILE"
        if save_plugin_info "$plugin" "closed"; then
            debug_log "Successfully saved json metadata for closed plugin $plugin."
        else
            debug_log "Failed to save json metadata for closed plugin $plugin."
        fi
        return 0
    fi
    
    LATEST_VERSION=$(echo "$VERSION_AND_LINK" | cut -d' ' -f1)
    API_DOWNLOAD_LINK=$(echo "$VERSION_AND_LINK" | cut -d' ' -f2-)

    debug_log "Latest version for $plugin: $LATEST_VERSION"
    debug_log "API download link for $plugin: $API_DOWNLOAD_LINK"

    STORED_VERSION=$(grep "^$plugin" "$LAST_VERSION_FILE" | awk '{print $2}')
    debug_log "Stored version for $plugin: $STORED_VERSION"

    if [ "$CACHE_ONLY" != 'y' ] && [ "$LATEST_VERSION" == "$STORED_VERSION" ] && [ -f "${MIRROR_DIR}/${plugin}.${LATEST_VERSION}.zip" ]; then
        echo "$plugin is up-to-date and exists in mirror directory. Skipping download..."
    else
        start_time=$(date +%s.%N)

        if download_plugin "$plugin" "$LATEST_VERSION" "$API_DOWNLOAD_LINK"; then
            if [ "$CACHE_ONLY" != 'y' ]; then
                sed -i "/^$plugin/d" "$LAST_VERSION_FILE"
                echo "$plugin $LATEST_VERSION" >> "$LAST_VERSION_FILE"
            fi
            echo "Successfully processed $plugin."
        else
            echo "Error: Failed to process $plugin." >&2
        fi

        end_time=$(date +%s.%N)
        duration=$(echo "$end_time - $start_time" | bc)
        printf "Time taken for %s: %.4f seconds\n" "$plugin" "$duration"
    fi

    if save_plugin_info "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully saved json metadata for $plugin."
    else
        debug_log "Failed to save json metadata for $plugin."
    fi

    if fetch_and_save_checksums "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully fetched and saved checksums for $plugin."
    else
        debug_log "Failed to fetch and save checksums for $plugin."
    fi

    if [ $version_check_status -eq 0 ]; then
        echo "$plugin" >> "$OPENED_PLUGINS_FILE"
    fi
}

populate_all_plugins() {
    if [ ! -f "$ALL_PLUGINS_FILE" ] || [ "$LIST_ONLY" == 'y' ]; then
        echo "Fetching list of all WordPress plugins..."
        svn list https://plugins.svn.wordpress.org/ | sed 's/\/$//g' > "$ALL_PLUGINS_FILE"
        plugin_count=$(wc -l < "$ALL_PLUGINS_FILE")
        echo "Plugin list (${plugin_count}) saved to $ALL_PLUGINS_FILE"
    fi
    
    if [ "$LIST_ONLY" == 'n' ]; then
        ALL_PLUGINS=()
        while IFS= read -r line; do
            ALL_PLUGINS+=("$line")
        done < "$ALL_PLUGINS_FILE"
        echo "Loaded ${#ALL_PLUGINS[@]} plugins."
    fi
}

if [ "$LIST_ONLY" == 'y' ]; then
    populate_all_plugins
    echo "Plugin list created. Exiting without downloading."
    exit 0
fi

if [ "$DOWNLOAD_ALL_PLUGINS" == 'y' ]; then
    populate_all_plugins
    COMBINED_PLUGINS=("${ALL_PLUGINS[@]}")
else
    if [ ! -d "$PLUGIN_DIR" ]; then
        echo "Warning: Plugin directory $PLUGIN_DIR does not exist or is invalid."
        PLUGIN_LIST=()
    else
        PLUGIN_LIST=($(ls -d "$PLUGIN_DIR"/*/ 2>/dev/null | xargs -n 1 basename))

        if [ ${#PLUGIN_LIST[@]} -eq 0 ]; then
            echo "No plugins found in $PLUGIN_DIR."
        fi
    fi

    COMBINED_PLUGINS=(${PLUGIN_LIST[@]} ${ADDITIONAL_PLUGINS[@]})
    COMBINED_PLUGINS=($(echo "${COMBINED_PLUGINS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
fi

if [ ${#COMBINED_PLUGINS[@]} -eq 0 ]; then
    echo "No plugins to download. Exiting."
    exit 0
fi

mkdir -p "$MIRROR_DIR"
touch "$LAST_VERSION_FILE"

if [ "$PARALLEL_JOBS" -gt 1 ]; then
    echo "Running in parallel with $PARALLEL_JOBS jobs..."
    echo "Variables before export:"

    # WordPress-related directories
    echo "WORDPRESS_WORKDIR: $WORDPRESS_WORKDIR"
    echo "PLUGIN_DIR: $PLUGIN_DIR"
    echo "MIRROR_DIR: $MIRROR_DIR"
    echo "LOGS_DIR: $LOGS_DIR"

    # Cloudflare Worker related URLs
    echo "CF_WORKER_URL: $CF_WORKER_URL"

    # Flags and options
    echo "DOWNLOAD_LINK_API: $DOWNLOAD_LINK_API"
    echo "DOWNLOAD_ALL_PLUGINS: $DOWNLOAD_ALL_PLUGINS"
    echo "LIST_ONLY: $LIST_ONLY"
    echo "DELAY_DOWNLOADS: $DELAY_DOWNLOADS"
    echo "DELAY_DURATION: $DELAY_DURATION"
    echo "FORCE_UPDATE: $FORCE_UPDATE"
    echo "CACHE_ONLY: $CACHE_ONLY"

    # File paths
    echo "OPENED_PLUGINS_FILE: $OPENED_PLUGINS_FILE"
    echo "CLOSED_PLUGINS_FILE: $CLOSED_PLUGINS_FILE"
    echo "LAST_VERSION_FILE: $LAST_VERSION_FILE"
    echo "ALL_PLUGINS_FILE: $ALL_PLUGINS_FILE"

    # Parallel job configuration
    echo "PARALLEL_JOBS: $PARALLEL_JOBS"

    # User Agents mapping
    echo "USER_AGENTS: ${USER_AGENTS[@]}"

    # Additional plugins to be processed
    # echo "ADDITIONAL_PLUGINS: ${ADDITIONAL_PLUGINS[@]}"

    # Plugin List (loaded from directory or ALL_PLUGINS_FILE)
    #echo "PLUGIN_LIST: ${PLUGIN_LIST[@]}"
    #echo "COMBINED_PLUGINS: ${COMBINED_PLUGINS[@]}"

    # First, export all variables including USER_AGENTS
    export DOWNLOAD_BASE_URL MIRROR_DIR LAST_VERSION_FILE DEBUG_MODE DOWNLOAD_LINK_API LOGS_DIR ALL_PLUGINS_FILE DOWNLOAD_ALL_PLUGINS LIST_ONLY CF_WORKER_URL DELAY_DOWNLOADS DELAY_DURATION FORCE_UPDATE CACHE_ONLY WORDPRESS_WORKDIR PLUGIN_DIR PARALLEL_JOBS OPENED_PLUGINS_FILE CLOSED_PLUGINS_FILE USER_AGENTS

    # Then, export the functions
    export -f process_plugin get_latest_version_and_download_link download_plugin debug_log populate_all_plugins save_plugin_info get_random_user_agent fetch_and_save_checksums
    printf "%s\n" "${COMBINED_PLUGINS[@]}" | xargs -P $PARALLEL_JOBS -I {} bash -c 'process_plugin "$@"' _ {}
else
    for plugin in "${COMBINED_PLUGINS[@]}"; do
        process_plugin "$plugin"
    done
fi

if [ -f "$CLOSED_PLUGINS_FILE" ]; then
    echo
    echo "Closed Plugin List:"
    cat "$CLOSED_PLUGINS_FILE" | sort | uniq || true
    echo
    echo "Total closed plugins: $(wc -l < "$CLOSED_PLUGINS_FILE")"
    echo
else
    echo
    echo "No closed plugins found."
    echo
fi
echo "Plugin download process completed."
