#!/bin/bash

# Base directory (script location)
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Configurable directories
WORDPRESS_WORKDIR="${WORDPRESS_WORKDIR:-$BASE_DIR/wordpress-plugins}"
PLUGIN_DIR="${PLUGIN_DIR:-$BASE_DIR/wp-content/plugins}"
MIRROR_DIR="${MIRROR_DIR:-$BASE_DIR/mirror}"
LOGS_DIR="${LOGS_DIR:-$BASE_DIR/plugin-logs}"

# Check for CF_WORKER_URL environment variable
if [ -z "$CF_WORKER_URL" ]; then
    echo "Error: CF_WORKER_URL environment variable is not set." >&2
    exit 1
fi

DOWNLOAD_BASE_URL="https://downloads.wordpress.org/plugin"

# Other variables
DOWNLOAD_LINK_API='y'

ADDITIONAL_PLUGINS=(
    "woocommerce-variable-product-description"
    "block-archive-org-robots-txt"
    "nautic-pages"
    "recently-updated-pages-and-posts"
    "happy-santa"
    "gravity-forms-force-ssl"
    "easy-author-avatar-image"
    "hblpay-payment-gateway-for-woocommerce"
    "gutenbooster-addons"
    "show-user-id"
    "solar-wizard-lite"
    "fast-mailerlite"
    "html-tag-and-class-replace"
    "paranoid911"
    "dawanda-shop-plugin"
    "foxy-bookmark"
    "mwb-zendesk-woo-order-sync"
    "qr-code"
    "chinese-tag-names"
    "responsive-posts-widget"
    "download-directory"
    "disable-right-click-images"
    "sprout-invoices-ninja-forms"
    "word-count-wizard"
    "crypto-price-widgets"
    "revenue-share-plugin-for-authorsrsp"
    "custom-shortcode-creator"
    "combined-image-and-text-widget"
    "imgshow"
    "wp-mail-smtp-sendgrid-edition"
    "pdf-invoice-japan-for-woocommerce"
    "wi-contact-form-7-for-elementor"
    "sandcage"
    "duplicate-taxonomy-terms-and-acf-fields"
    "affiliate-products-blocks"
    "wpec-bulk-tools"
    "cfs-custom-category-fields"
    "wp-e-commerce-featured-products"
    "owa-most-popular"
    "weekly-planner"
    "hide-toolbar-plugin"
    "appsgeyser-plug-in"
    "hover-sound"
    "clients"
    "pdf-world-de-pdf-blatterbar-einfugen"
    "you-tube-colourbox-plugin"
    "stonehenge-em-slider"
    "base64-images"
    "mobile-app-showcase"
    "websitescanner-custom-schema"
    "update-from-bottom"
    "editoria11y-accessibility-checker"
    "notice-boxes-with-shortcodes"
    "sales-tax-reports-for-woocommerce"
    "imacprestashop"
    "wp-order-by"
    "shipping-options"
    "post-featured-tag-block-by-gutena"
    "wp-fail2ban-addon-gravity-forms"
    "wp-baidu-fanyi"
    "easy-cc-license"
    "google-real-estate-maps"
    "heic-to-jpeg"
    "countdown-timer-block"
    "drive-folder-embeder"
    "share-on-diaspora"
    "month-name-translation-benaceur"
    "lenix-scss-compiler"
    "sticky-action-buttons-call-chat-navigate-and-more"
    "list-stores-category-dokan"
    "shipping-per-neighborhood-for-woocommerce"
    "ca-yaturbo"
    "spoken-word"
    "premmerce-dev-tools"
    "print-bangla-news"
    "landing-pages-and-domain-aliases"
    "woo-point-of-salepos"
    "easy-custom-css"
    "posteria"
    "duplicate-killer"
    "majestic-before-after-image"
    "buybox-widget"
    "stionic-core"
    "nochex-payment-gateway-for-woocommerce"
    "aw-target-blank"
    "cf-image-resizing"
    "piano-block"
    "afterread"
    "jetrouter"
    "include-matomo"
    "wp-gravatar-mini-cache"
    "wp-avim-reloaded"
    "scroll-up"
    "slidorion"
    "mt-addons-for-elementor"
    "always-remember-me"
    "trimpress"
    "excited-testimonials-showcase"
    "disable-delete-post-or-page-link-wordpress-plugin"
    "wp-nav-menu-cache"
    "wp-dashboard-messages"
    "mailbluster4wp"
    "woocommerce-smart-collection"
    "bns-support"
    "catholic-liturgical-calendar"
    "wp-igniter"
    "cite"
    "infinite-transporter"
    "newsletter-sms-smsapi"
    "yydevelopment-accessibility"
    "wp-food"
    "block-data-attribute"
    "wp-commentwidgetizer"
    "change-background-color-for-pages-posts-widgets"
    "icestats"
    "auto-refresh-api-ajax"
    "cf7-countries"
    "allow-comments-on-pages-by-default"
    "agile-crm-gravity-forms"
    "clixtell-tracking-dynamic-phones"
    "really-simple-backup"
    "woo-better-customer-list"
    "post-link-shortcode"
    "images-optimizer"
    "post-randomizer"
    "loginstyle"
    "wp-news-headline-ticker"
    "wpsiren-random-post-by-click"
    "weather-in-japan"
    "pro-recent-post-widget"
    "nps-computy"
    "ultimate-push-notifications"
    "wp-comments-remover"
    "octonis-page-builder"
    "date-tool"
    "logged-out-admin-bar"
    "regenerate-thumbnails-reminder"
    "cpi-wp-migration"
    "bedbooking-reservation-system"
    "redirector-mod"
    "wh-testimonials"
    "stock-notifier-for-woocommerce"
    "vsf-simple-block"
    "mailwizz-newsletter-box"
    "parse-shortcodes"
    "image-compare-block"
    "wp-image-importer"
    "qr-block"
    "language-based-anti-spam-plugin"
    "seo-for-images"
    "scenechat-video-sharing-and-commenting-tool"
    "pdpa-consent"
    "total-user-count-shortcode"
    "watermark-images-for-wp-and-woo-grandpluginswp"
    "latest-post-accordian-slider"
    "nightingale-companion"
    "scroll-top-advanced"
    "wp-socialshareprivacy"
    "wp-bigfoot"
    "zakah-calculator"
    "gdpr-personal-data-reports"
    "wp-listings-custom-search-form"
    "full-page-load"
    "contact-commenter"
    "wpc-shoppable-images"
    "email-notifications-for-wp-ulike"
    "ressources"
    "aims-textarea-wordcount-withwithout-space-for-contact-form-7"
    "hey-social"
    "social-images-widget"
    "get-news-vnexpress-net"
    "modula-nextgen-migrator"
    "qr-master"
    "enable-shortcodes-inside-widgetscomments-and-experts"
    "b-pinterest-feed"
    "contact-form-7-civicrm-integration"
    "show-post-in-lightbox"
    "wp-present"
    "disable-wp-robots"
    "webeki-soccer-scores"
    "business"
    "opensans-ftw"
    "jquery-tinytips"
    "jm-live-blog"
    "mojito-sinpe"
    "foundation-top-bar-navigation-menu"
    "wp-author-profile-box-lite"
    "campt-razorpay-payment-gateway"
    "amr-personalise"
    "digitimber-cpanel-integration"
    "photostack-gallery"
    "wp-postratings-my"
    "wp-content-layout"
    "google-map-direction"
    "auto-join-groups"
    "give-receipt-attachments"
    "hotelierscom-booking-module"
    "syntax-highlighter-for-elementor"
    "redis-woo-dynamic-pricing-and-discounts"
    "sharp-login"
    "advanced-term-fields-featured-images"
    "apex-digital-toolbox"
    "gallery-slider-for-pinterest"
    "matty-theme-quickswitch"
    "favicon-extender"
    "twitter-user-timelines"
    "gs-woo-brands"
    "product-info-request-for-woocommerce"
    "cart2cart-universal-store-migration-app"
    "draft-notify"
    "wp-ajax-login-and-register-popup"
    "circupress"
    "nearby-map"
    "clearboth"
    "wpgalleria"
    "automatic-ban-ip"
    "my-admin-bookmarks"
    "reduce-stock-of-manual-orders-for-woocommerce"
    "jetpack-slideshow-caption"
    "soccr"
    "lorem-ipsum-by-webline"
    "simple-qa"
    "cost-calculator-cost-estimation"
    "gulri-slider"
    "woocommerce-monster-widget"
    "elink-embed-content"
    "stetic"
    "edd-mailchimp-subscribe"
    "axel-pro-for-woocommerce"
    "hebrew-username"
    "v-form"
    "tipso"
    "no-login"
    "shortcode-shorturl"
    "facebook-secret-meta"
    "author-page-views"
    "iakpress"
    "user-login-stat"
    "clickmeeting"
    "greenrope-analytics"
    "all-in-one-content-restriction"
    "loadgo-for-wp"
    "pretty-simple-progress-meter"
    "wp-maintenance-mode-admin-bar-alert"
    "magic-links"
    "realtime-bitcoin-chart"
    "wp-admin-basic-auth"
    "woo-streetshirts"
    "events-rsvp"
    "text-obfuscator"
    "sku-error-fixer-for-woocommerce"
    "bbpress-unread-posts-v2"
    "bbp-user-online-status"
    "jano-wp-woocommerce-advanced-search"
    "wp-pagseguro-payments"
    "world-weather-wwo"
    "location-specific-menu-items-by-country"
    "button-generator-plugin"
    "aplazo-payment-gateway"
    "free-guest-post"
    "wpcasa-pricing-tables"
    "circle-progress-bar"
    "wordpress-member-private-conversation"
    "genesis-tabs-extended"
    "the-taxonomy-sort"
    "detailed-player-stats-for-sportspress"
    "mycred-for-gd-star-rating"
    "gallery2-image-block-widget"
    "fade-slider"
    "ebaystore"
    "easy-featured-content"
    "custom-field-snippet"
    "easy-social-share"
    "word-count-analysis"
    "list-sub-categories-lsc"
    "play-video-of-song"
    "weather-man"
    "snipe-nginx-cache"
    "increase-maximum-upload-file-size-limit"
    "framework-mobilede"
    "dmca-watermarker"
    "epaka-pl"
    "jquery-notebook"
    "menu-override"
    "wp-job-manager-shortwidget"
    "category-archive-widget"
    "doqrcode"
    "schedulista-shortcode"
    "giveaways-contests-by-promosimple"
    "lightbox-content-images-wpshare247"
    "thememan-by-pluginbuddy"
    "bizapp-for-woocommerce"
    "clearblue-ovulation-calculator"
    "woocommerce-show-free-shipping-only-by-nunoapps"
    "wp-amaps"
    "wp-easy-popup"
    "vello-booking-calendar"
    "wplr-sync-folders"
    "wp-auto-reload-widgets"
    "stripe-manager"
    "external-links-nofollow-open-in-new-tab-favicon"
    "restaurant-bookings"
    "tag-grouping"
    "holiday-class-post-calendar"
    "business-block-widget"
    "agreeme-checkboxes-for-woocommerce"
    "booktuner"
    "f13-movie-shortcode"
    "improved-meta-description-snippets"
    "offermative-discount-pricing-related-products-upsell-funnels-for-woocommerce"
    "support-online"
    "wp-video-enhanced"
    "pencil-wiki"
    "wc-delete-product-images"
    "9pay-gateway"
    "wp-server-date-time"
    "page-builder-companion"
    "admin-options-pages"
    "adgallery-slider"
    "erocks-dashboard-lockdown"
    "cloud-customer-area"
    "generatewp-oembed"
    "visitors-detective"
    "really-disable-emojis"
    "wc-chitchats-shipping"
    "mailster-cool-captcha"
    "copyright-safeguard-footer-notice"
    "cs-page-templates-info"
    "simple-force-ssl"
    "mu-manager"
    "simple-video-management-system"
    "get-liveinternet-statistics"
    "surbma-premium-wp"
    "crowdhandler-virtual-waiting-room"
    "notakey-two-factor-extension"
    "simple-options"
    "woohoo"
    "posts-order-widget"
    "click-tweet"
    "flashnews-typewriter-pearlbells"
    "wp-pjax"
    "each-domain-a-page"
    "super-subpages"
    "google-page-badge"
    "kemet-addons"
    "saoshyant-page-builder"
    "instock-email-alert-for-woocommerce"
    "better-sharing"
    "feedaggregator"
    "lsx-importer-for-wetu"
    "k2-hook-up"
    "gift-hunt"
    "wp-reviews-by-wiremo"
    "world-flag"
    "checkoutpage"
    "recaptcha-jetpack"
    "wp-email-delivery"
    "fare-calculator"
    "maintenance-mode-z"
    "geosmart"
    "ai-for-seo"
    "internet-quran-radio"
    "laposta-signup-embed"
    "advanced-image-grabber"
    "easy-news-ticker"
    "cardanopress-governance"
    "jonradio-reveal-network-activated-plugins"
    "indic"
    "wp-seo-search"
    "miniorange-sms-order-notification-otp-verification"
    "mowster-glossary"
    "blocks-starter-templates"
    "custom-fields-account-registration-for-woocommerce"
    "popup-notifier-for-contact-form-7"
    "clonable"
    "sticky-posts-widget"
    "zz-image-slider"
    "kazooky-loyalty-rewards"
    "qtranslate-support-for-gravityforms"
    "fortressdb"
    "multisite-directory"
    "simple-scroll-top-wp"
    "responsive-mailform"
    "display-wp-mail-error-messages"
    "personal-hit-counter"
    "wp-category-sort"
    "standard-box-sizes"
    "dynamicqrcode"
    "wp-super-login"
    "simple-hierarchical-sitemap"
    "remove-unrestricted-uploads"
    "unfoldwp-import-companion"
    "world-population-counter"
    "categories-multiple-images"
    "bank-melli-edd-gateway"
    "performerjs"
    "gallery-masonry-editor"
    "mailster-wpml"
    "kt-photogallery"
    "mirrorgrid-demo-importer"
    "feedpress-generator"
    "my-envato"
    "limit-revisions"
    "wp-thumbtack-review-slider"
    "service-provider-profile-cpt"
    "orbisius-bbpress-signature"
    "mp-customizer-backups"
    "seosamba-webmasters"
    "medias-toolbox"
    "migratestore"
    "bulk-variations-for-woocommerce"
    "wr-price-list-for-woocommerce"
    "woo-paypal-advanced"
    "gazchaps-woocommerce-purchase-order-payment-gateway"
    "mailtostaff"
    "betaout"
    "em-purchase-code-validator"
    "cc-payment-gateway"
    "cbr-slagingspercentage"
    "wp-fancy-message-box"
    "cartbox-messaging-widgets"
    "people-page"
    "callroot"
    "gutena-team"
    "laposta-woocommerce"
    "guinrank"
    "tiny-table-of-contents-tinytoc"
    "multi-layer-slider-beaver-builder-elementor"
    "safe-paste"
    "pirsch-analytics"
    "big-boom-alert-bar"
    "ai-image-generator"
    "stop-signup-spam"
    "check-pincode-for-woocommerce"
    "onetap"
    "perzonalization"
    "fast-courier-shipping-freight"
    "wp-copy-media-url"
    "vkcomments"
    "zooom"
    "jj-wp-easy-navigation"
    "live-flickr-comment-importer"
    "wp-note-2019"
    "content-visibility"
    "callback-widget"
    "quick-admin"
    "top-coin"
    "cf7-manual-spam-blocker"
    "discount-payment-moona"
    "sanooksookjai-menu-icon"
    "ajaxed-twitter-for-wordpress"
    "webkima-elements"
    "disable-wp-new-user-notification"
    "feature-me"
    "cw-easy-video-player"
    "coinqvest"
    "custom-javascript-inserter"
    "endnotes"
    "twiogle-wp-twitter-comments"
    "doppler-for-woocommerce"
    "voice"
    "nft-gallery"
    "max-css"
    "fabrica-reusable-block-instances"
    "artistography"
    "gentlesource-short-url"
    "wp-login-alerts"
    "simple-parse-push-service"
    "ajax-archives"
    "vbulletin-latest-threads"
    "tutor-lms-author"
    "pwf-wc-product-filters"
    "gravity-forms-related-fields"
    "sewn-in-template-log-in"
    "cbqe-edit-flow"
    "addthischina"
    "custom-tabindex-gravity-forms-add-on"
    "love-calculator"
    "block-email-cf7"
    "wp-stickit"
    "exclude-posts-from-search-results"
    "google-badge-connect-direct-for-wordpress"
    "advanced-quiz"
    "chrome-theme-color-changer"
    "wc-trendyol"
    "blockify"
    "bp-better-directories"
    "guild-armory-roster"
    "jawda-youtube-embed"
    "kirimemail-woocommerce-integration"
    "pgnviewerjs-wp"
    "plezi"
    "woo-change-product-author"
    "cocoon-media-management"
    "lokalise"
    "easy-zillow-reviews"
    "multiple-ajax-calendar"
    "zeevou"
    "rss-llama"
    "image-point"
    "xml-news-sitemap"
    "profiless"
    "crypto-prices"
    "hide-address-fields-for-woocommerce"
    "coming-soon-for-genesis"
    "skype-web-control"
    "faq-in-minute"
    "reuters-direct"
    "slaask"
    "upload-unziper"
    "wp-headmaster"
    "allada-tshirt-designer-for-woocommerce"
    "atticthemes-social-icons"
    "paypal-frontend-registration"
    "geo-maps"
    "seo-friendly-urls-for-woocommerce"
    "energy-search"
    "ffc-football-co2-calculator"
    "mifinity-payments-gateway"
    "wp-html-mail-buddypress"
    "jarryd-and-the-jackles-elementor-random-image"
    "cfs-font-awesome"
    "wp-emoji-sanitizer"
    "top-position-yahoo-finance"
    "teligro"
    "blogroll-dropdown"
    "cloogooq"
    "car-rental-widget-by-morerentalcarscom"
    "cart-ninja-wordpress-shopping-cart"
    "dtdc-econnect"
    "redirect-for-bloom-by-logic-hop"
    "mind-doodle-sitemap"
    "addthis-xmlns"
    "admin-menu-groups"
    "live-editor-file-manager"
    "wp-flexible-map-options"
    "light-xml-sitemap"
    "wp-rainbow-hilite"
    "tp-navigation-menu"
    "custom-post-type-templates-for-elementor"
    "getlaw-wp-api-client"
    "header-promo"
    "post-size-text-changer"
    "simple-thumbs"
    "lzb-select-dynamic"
    "speaker-lite"
    "tinymce-tabfocus-patch"
    "http-digest-auth"
    "like-photo"
    "recent-comments-widget-with-excerpts"
    "gdpr-for-formidable-forms"
    "easy-code-snippets"
    "random-images"
    "social-top-sharing"
    "listicle"
    "web-stories-enhancer"
    "woo-enviofacil"
    "admin-hot-maintenance-mode"
    "divi-socials"
    "linkedinclude"
    "responsive-css-editor"
    "wp-post-list-table"
    "very-simple-google-analytics"
    "wp-profile-builder"
    "twounter"
    "the-publisher-desk-ads-txt"
    "cyclos"
    "redis-object-cache"
    "rss-control"
    "cdekdelivery"
    "simpleprivacy"
    "lexicata"
    "bbs-e-franchise"
    "smart-quote-fixer"
    "post-comment-notification-to-multiple-user"
    "loginradius-customer-identity-and-access-management"
    "bmt-no-right-click"
    "simple-sponsorships"
    "quick-view-woo"
    "client-showcase"
    "wc-recently-viewed-products"
    "woo-paytr-taksit-tab"
    "wptobe-signinup"
    "wpc-shop-as-customer"
    "website-security-check"
    "simple-reverse-comments"
    "todo-block"
    "g-ffl-checkout"
    "user-activity"
    "lh-wayback-machine"
    "pango-sensei-module-collapse"
    "hreview-support-for-editor"
    "bitly-exporter"
    "steam-news-widget"
    "best-listing-toolkit"
    "wpc-update-variations-in-cart"
    "a-gateway-for-pasargad-bank-on-woocommerce"
    "ebaylink"
    "bdwebteam-recent-post-tabs-widget"
    "bank-transfer-confirmation-form"
    "restore-purchased-items-column"
    "wider-gravity-forms-stop-entries"
    "recipe-schema"
    "featured-post-manager"
    "question-answer-faq"
    "random-quotes"
    "universal-analytics"
    "presta-products"
    "sticky-sidebar"
    "wp-dpe-ges"
    "tripadvisor-stream"
    "4stats"
    "reusable-blocks-admin-menu-option"
    "infusionsoft-web-form-javascript"
    "multipurpose-css3-animated-buttons"
    "login-register-using-jwt"
    "o365-wp-restrict"
    "simple-cookie-law"
    "new-dev-livesmart-video-chat"
    "ie6-support-for-2010-theme"
    "dirty-suds-export-to-indesign"
    "embed-react-application"
    "noindex-links"
    "simple-category-search"
    "geidea-online-payments"
    "wp-page-title-with-icon"
    "wp-ispconfig"
    "switch-core"
    "woocommerce-remove-quantity-text"
    "wp-admin-customizer"
    "awesome-studio"
    "disable-administration-email-verification-prompt"
    "smsa-shipping-official"
    "seo-bulk-editor"
    "ajax-content-filter"
    "lemonink"
    "plimus-for-wordpress"
    "blogfa-templater"
    "sequra"
    "fix-admin-contrast"
    "virtuaria-correios"
    "statsfc-next-fixture"
    "wc-simple-product-badge"
    "motaword"
    "philantro"
    "templementor"
    "futusign"
    "mc-divi-title-module"
    "prism-highlight"
    "iwocapay-payment-gateway"
    "scoopit-for-jetpack"
    "wp-snap-extended"
    "surbma-jetpack-development-mode"
    "hide-admin-bar-for-user-roles"
    "sorsawodigital-edd-currency"
    "vagonic-sortable"
    "wp-hyves"
    "top-social-stories-free"
    "accept-stripe-payments-using-contact-form-7"
    "ceceppa-multilingua-support-for-woocommerce"
    "contentshare"
    "sticky-ad-lightweight"
    "password-passthrough"
    "remove-version-info"
    "hideshow-postpage-content"
    "email-checker-for-contact-form-7"
    "mycred-for-rating-form"
    "acymailing-automation-export"
    "virante-in-depth-article-maker"
    "stock-car-listing-from-autocerfa"
    "linkpreview"
    "dpt-dnsmanager"
    "simple-dns-prefetch"
    "license"
    "woo-mailchimp-crm-perks"
    "link-finder"
    "press75-long-form-storybuilder"
    "zero-bs-accounting"
    "wc-discord-notifications"
    "i-make-plugins"
    "circulair-geld"
    "combidesk-moneybird"
    "easy-thumbnail-switcher"
    "default-image-settings"
    "froged"
    "disable-errors-in-plugins"
    "aspexi-easy-login-url"
    "wpdevdesign-oxygen-currently-editing"
    "ultimate-faq-solution"
    "front-page-custom-post-type"
    "simple-google-directions"
    "blocks-everywhere"
    "publish-view"
    "kahis-wp-lite"
    "wp-simplyhired-api"
    "lgpd-framework"
    "insert-video-with-schemaorg-ivws"
    "mandabem"
    "media-meta"
    "bootstraps-columns-controller"
    "eduhack"
    "memeone"
    "wpmu-database-reset"
    "wp-recipes"
    "luckywp-term-description-rich-text"
    "heureka"
    "woocommerce-notify-updated-product"
    "social-traffic-monitor"
    "speedcheck-internet-speed-test"
    "gis-maps"
    "wc-multi-tiered-shipping"
    "list-all-pages"
    "header-code"
    "auto-generate-title"
    "wu-block-comments"
    "image-browser"
    "aurpay-crypto-payment-for-easy-digital-downloads"
    "easy-bet"
    "wc-walletdoc-payment-gateway"
    "cobiro"
    "youtube-post-search"
    "msstiger"
    "dmg-related-pages-widget"
    "wp-cloudflare-geoip-redirect"
    "now-playing-widget-fuer-azuracast-stationen"
    "pssubpages"
    "genesis-featured-image"
    "hm-resume-manager"
    "floating-player"
    "gleam-shortcodes"
    "copy-code-to-clipboard"
    "tooltipglossary"
    "portfolio-cpt"
    "custom-upload-folder"
    "wp-p5js-block"
    "authors-autocomplete-meta-box"
    "wp-section-index"
    "wp-jtweets"
    "video-onclick"
    "cookiecode"
    "sizeme-for-woocommerce"
    "duplicate-posts-page"
    "popular-posts-count"
    "wpg3"
    "panorama-block"
    "sticky-toc-advance-table-of-contents"
    "amp-for-contact-form-7"
    "bin-payment-by-invoice-for-woocommerce"
    "edoc-easy-tables"
    "mp6-light"
    "cf7-conditional-load"
    "csomagpont"
    "weixin-helper"
    "dashboard-user-profile-detais-dupd"
    "onc-master"
    "gamipress-ld-points-per-quiz-score"
    "wc-tiered-shipping"
    "wc-gift-packaging"
    "contact-form-7-tag-field"
    "stripe-gateway-for-events-manager-pro"
    "wordpress-31x-html-editor-font"
    "wpop-contactform-hubspot"
    "theme-junkie-portfolio-content"
    "bloglovin-widget"
    "remove-archive-label"
    "bodi0s-bots-visits-counter"
    "fair-analytics"
    "business-hours"
    "livejournal-crossposter-remix"
    "remove-site-heath-from-dashboard"
    "lsx-sharing"
    "google-trends-widget"
    "night-mode"
    "support-board-cloud"
    "spot-hit"
    "anychat-widget"
    "sitewide-google-analytics"
    "coinwidget-shortcode"
    "sewn-in-simple-seo"
    "wp-online-users-stats"
    "drag-and-drop-front-end-design-builder"
    "current-username-on-navigation-lable"
    "web-page-speed-checker"
    "rel-external"
    "cryptocloud-crypto-payment-gateway"
    "wp-author-profile-widget"
    "custom-base-terms"
    "listen-to-quran-verses"
    "post-slideshow-gallery"
    "double-the-donation"
    "admin-filter-posts-by-year"
    "notice-faq"
    "category-d3-tree"
    "music-press-quick-playlist"
    "product-quotation-for-woocommerce"
    "custom-permalinks-for-custom-post-types"
    "manage-gravity-forms-stripe-subscriptions"
    "syncee-for-suppliers"
    "import-products-from-gsheet-for-woo-importer"
    "alexa-traffic-widget"
    "remove-stopwords-from-slug"
    "jqdock-post-thumbs"
    "age-okay"
    "wp-version-remover"
    "arvancloud-cdn"
    "add-quantity-to-archive-category-page"
    "provide-live-help"
    "address-autocomplete-anything"
    "prayer-times-anywhere"
    "wpsso-merchant-return-policy"
    "aftersalespro"
    "copy-to-clipboard-for-wp"
    "wp-integration"
    "rdv360-reservation-en-ligne"
    "bbpress-post-ratings"
    "arabic-indic-numerals-for-arabic-wp"
    "vev-design"
    "g-core-labs-cdn"
    "eway-crm-extension-for-contact-form-7"
    "wp-admin-todo-list"
    "gravity-forms-iban"
    "novamodule-woocommerce"
    "rua-blog-subscriber-lite"
    "pigeon-pack"
    "bpckeditor"
    "croprefine"
    "ad-publisher"
    "fluentform-block"
    "ultimate-infinite-scroll"
    "comment-link-manager"
    "widgets-widgets-widgets"
    "hebcal-shabbat-times"
    "woo-recent-posts"
    "gigya-wildfire-for-wordpress"
    "trustmary"
    "dont-break-the-code"
    "bibs-twitter-follow-button-reloaded"
    "secure-wp-admin"
    "simple-image-upload"
    "joli-faq-seo"
    "bbpress-auto-subscribe-for-new-topics-and-replies"
    "consultimator"
    "master-mind-author-box"
    "shipping-discount"
    "gutenbye"
    "nomination-and-voting"
    "product-feed-manager-for-woocommerce"
    "select2-post-selector"
    "peerraiser"
    "gdd-adwords-wordpress-plugin"
    "lastfm-recent-album-artwork"
    "vr-jscrollpane-shortcode"
    "post-type-archive-pages"
    "woo-document-preview"
    "wpyog-documents"
    "sa-coronavirus-banner"
    "stacks-mobile-app-builder"
    "whmcs-doali-elementor"
    "custom-event-espresso-list-displayer"
    "better-woocommerce-stars-shortcode"
    "redux-converter"
    "suffusion-bbpress-pack"
    "cpanel-operations"
    "magic-block"
    "simple-post-listing"
    "nolip-nofollow-links-in-posts-reborn"
    "inline-quote-tag"
    "client-status"
    "disable-file-editor"
    "embed-sendy"
    "easy-recent-posts"
    "wp-simple-carousel"
    "wpem-divi-elements"
    "quixchat-button"
    "radslide"
    "wc-slider"
    "sane-widget-sidebar-management"
    "wpmu-fast-verification-for-google-webmaster-tools-and-yahoo-site-explorer"
    "chapters"
    "nevobo-feed"
    "domain-change"
    "saleassist"
    "hormozdi-cryptocurrencies"
    "formidable-honeypot"
    "wc-category-discount"
    "woocommerce-custom-coupon-message"
    "wp-bibtex"
    "recommendations-tastedive"
    "double-opt-in"
    "kahis-notes"
    "sertifier-certificates-open-badges"
    "atp-call-now"
    "string-translation-importer-wpml"
    "user-role-widget-areas"
    "jay-access-flickr"
    "starscape"
    "enviaya-shipping-for-woocommerce"
    "shopsite-plugin"
    "wp-sitebuilder"
    "theme-blvd-piecemaker-addon"
    "jeba-limit-login-attempts"
    "cache-ultra"
    "aklamator-pro-adsense"
    "skysa-announcements-app"
    "swe-country-code-field-gf-add-on"
    "real-ip-detector"
    "wordpress-head-cleaner"
    "coinqvest-for-woocommerce"
    "advanced-floating-sliding-panel"
    "scd-smart-currency-detector-variant-for-wcfm"
    "axle-demo-importer"
    "exif-details"
    "brozzme-fullwidth-divi"
    "call-to-action-popup"
    "a-simple-backend"
    "stklcode-liveticker"
    "single-value-taxonomy-ui"
    "wp-photo-effects"
    "search-into-subcategories"
    "wp-bots-analytics"
    "bp-include-non-member-comments"
    "select-post-export"
    "tracify"
    "buddypressbbpress-email-notification"
    "animation-block"
    "lsx-team"
    "superlinks"
    "gsheetconnector-forminator"
    "woo-mynix-braintree"
    "bstone-light"
    "customerlabs-actionrecorder"
    "ptest-personality-tests-for-wordpress"
    "theme-blvd-post-to-page-link"
    "draft-from-google-docs"
    "simple-address-autocomplete"
    "wp-custom-category-meta"
    "nomorepass-forget-your-passwords"
    "color-widgets"
    "styled-pagination"
    "ebanx-local-payment-gateway-for-woocommerce"
    "find-and-replace-text"
    "connections-business-directory-anniversary-and-birthday-emails"
    "jumpout"
    "author-avatar"
    "featured-posts-widget"
    "disk-space-pie-chart"
    "top-smooth-scroll"
    "wordpress-top-referrers"
    "simple-finance-calculator"
    "top-10-posts"
    "blog-id-in-site-admin-menu"
    "thank-you-page-viewer-for-woocommerce"
    "color-my-posts"
    "custom-shortcodes"
    "mailster-mailersend"
    "seo-free"
    "download-music"
    "smartarget-lucky-wheel"
    "amigo-extensions"
    "wp-ip2nation-installer"
    "bp-member-type-manager"
    "latest-post"
    "wp-delete-posts"
    "minecraft-control-panel"
    "random-related-posts-based-on-category"
    "rewrite-flush-button"
    "fluxtore"
    "performance-profiler"
    "nines-taoke"
    "upload-media-exif-date"
    "image-effects-generator"
    "first-comment-redirect"
    "simple-membership-menu"
    "auto-post"
    "userecho"
    "bye-maridjan-seo"
    "humix"
    "wp-feature-box"
    "mega-store-companion"
    "excerpt-extension"
    "acf-leaflet-map-field"
    "payfull"
    "christmas-snow-3d"
    "integration-for-luminate-and-gravity-forms"
    "scancircle"
    "store-locator-with-google-map"
    "fast404"
    "wp-design-portfolio"
    "leadpages"
    "woo-search-on-product-sku"
    "embed-osm"
    "wp-horizontal-slider"
    "hide-for-group-roles"
    "wp-hatena-notation"
    "product-image-zoom-for-woocommerce"
    "publishtomixi"
    "hide-admin-bar-search"
    "cf-civicrm"
    "purlem-personal-url-marketing"
    "flexo-social-gallery"
    "datareporter-webcare"
    "local-delivery-by-doordash"
    "poolparty-thesaurus"
    "wpp-faster-payment-systemfps-hong-kong"
    "eshop-magic"
    "koalendar-free-booking-widget"
    "wpshapere-lite"
    "wp-github-gist"
    "simple-matomo-tracking-code"
    "mywp-custom-patterns"
    "zonify"
    "simple-calendar-blog-feed"
    "fiscomm-purs-e-fiscalisation"
    "admitad-tracking"
    "invitereferrals-referral-program-for-woocommerce"
    "fusion-extension-comments"
    "limit-image-size"
    "a2z-canada-post-automated-shipping"
    "media-upload-meta-box"
    "myeasywebally"
    "comment-form-validation"
    "wpml-editor-languages"
    "podamibe-appointment-calendar"
    "social-share-watermark"
    "disable-plugin-deactivation"
    "storekeeper-for-woocommerce"
    "rich-taxonomy"
    "preloader-for-divi"
    "vertical-center"
    "pagination-for-pages"
    "enhanced-plugin-admin"
    "signature-fluent-contract-forms-add-on"
    "contact-form-7-tave-3-integration"
    "wp-helpdesk-integration"
    "related-external-links"
    "playlist-for-youtube"
    "woocommerce-total-web-solutions-gateway"
    "mullweg-de"
    "affiliate-link-marker"
    "metrics-query"
    "drafts-of-post-revisions"
    "campaigndot"
    "tansa"
    "voucherify"
    "custom-bulleted-lists"
    "zendesk-help-center"
    "store-toolkit-for-wp-e-commerce"
    "change-woocommerce-product-author"
    "webhook-netlify-deploy"
    "sticky-for-siteorigin"
    "review-slider-google"
    "wc-mpesa-payment-gateway"
    "comments-switcher"
    "wpjqp-datepicker"
    "woo-usp"
    "serped-net"
    "simple-floating-contact-form"
    "block-designer"
    "jobbnorge-block"
    "wordpress-phplist-dual-registration"
    "wsa-cachepurge"
    "user-profile-block"
    "latest-simple-news-ticker"
    "hover-image-and-text"
    "simple-quotes"
    "woo-upsell"
    "search-engines-blocked-in-header"
    "wordpress-nav-menus-access-keys"
    "transact"
    "ecommerce-dashboard"
    "wp-qrcode"
    "brightedge-autopilot"
    "cf7-grid-and-styler-for-divi"
    "form-widget-for-elementor"
    "seriously-simple-spam-blocker"
    "zen-toolkit"
    "wp-dropdown-posts"
    "exclude-category-widget"
    "vandar-woocommerce-gateway"
    "simple-new-post-emails"
    "ajax-awesome-css"
    "category-and-product-woocommerce-tabs"
    "wp-gallery-manager"
    "wp-email-notificator"
    "pw-archives"
    "sb-data-importer-wp-all-import-add-on"
    "image-copytrack"
    "woo-advanced-sku-reports"
    "anyfonttitle"
    "redirect-on-add-to-cart-for-woocommerce"
    "cj-change-howdy"
    "bbp-mentions-email-notifications"
    "claimit"
    "ownid-passwordless-login"
    "cotacao-dolar-hoje"
    "ordered-thumbnails"
    "starbox-voting"
    "cartfox"
    "contact-form-7-popup-response"
    "downloadable-gallery"
    "column-ordering-for-elementor"
    "tags-to-meta-keywords"
    "integrate-polarsteps"
    "net-results-marketing-automation"
    "wpdb-to-sql"
    "sitemap-simple"
    "hm-content-toc"
    "open-link"
    "enqueue-font-awesome-cdn"
    "git-it-write"
    "nofollow-home-internal-links"
    "wp-preloader"
    "domisiding-minecraft-serverbanner-namemc"
    "reimagined-admin"
    "wp-e-commerce-local-pick-up-shipping-module"
    "wp-down-slack-alert"
    "abg-rich-pins"
    "cardanopress-ispo"
    "media-webp"
    "edd-purchase-details"
    "sk-multi-tag"
    "blogger-redirector"
    "productive-forms"
    "tweak-option"
    "language-code-selector-mqtranslate"
    "wp-nice-loader"
    "qinvoice-mollie-ideal-for-gravity-forms"
    "outvoice"
    "kings-tab-slider"
    "bbboing"
    "productive-commerce"
    "no-browser-nag"
    "debug-bar-query-tracer"
    "launches-from-spacex"
    "text-captcha-contact-form-7"
    "cargo-tracking-for-woocommerce"
    "include-sitename-in-search-results"
    "simple-google-translate-widget"
    "juxtapose-images"
    "useragent-content-switcher"
    "crypto-donate-posts"
    "change-login-page-logo"
    "ultra-skype-button"
    "easy-classes"
    "twitter-shortcode"
    "enhanced-bibliplug"
    "simple-g-1-plusone"
    "wc-clictopay-payment-gateway"
    "twitter-follow-button-widget"
    "subzane-subpage-list-widget"
    "yydevelopment-portfolio-boxes"
    "sabines-zoom-gallery"
    "display-timezone"
    "sx-no-author-pagination"
    "admin-starred-posts"
    "eas-eu-compliance"
    "sort-admin-menus"
    "discourage-search-engines-notifier"
    "randompost"
    "footnotation"
    "quotepro-insurance-widget"
    "my-center-deals"
    "woocommerce-onsale-extender"
    "posts-page-custom-template"
    "local-syndication"
    "theme-file-maker"
    "navigable"
    "admin-comment"
    "wpsyncsheets-gravity-forms"
    "gmo-go-to-top"
    "testimonials-pro"
    "kit-com"
    "gosign-accordion-slider-block"
    "switch-jq-version"
    "bw-portfolio"
    "query-inside-post"
    "game-of-the-day"
    "labinator-minimal-maintenance-mode"
    "simple-folio"
    "cricket-scoreboard-widgets"
    "recaptcha-login"
    "wp-yadisk-files"
    "newsletter-popupmaker"
    "wordpress-scheduled-time"
    "minimal-share-buttons"
    "accept-disclaimer-overlayer"
    "fena-ecommerce"
    "storefront-pro-sales-pop"
    "wpmu-prefill-post"
    "rdface"
    "woocommerce-availability-chart"
    "multisite-multidomain-single-sign-on"
    "snapshots"
    "responsive-p5js-for-wp"
    "mj-news"
    "quickpost"
    "post-modified-time-block"
    "remove-amazon-links-from-rss-feed"
    "gou-wc-account-tabs"
    "wpc-copy-billing-address"
    "neon-text"
    "limit-comments-and-word-count"
    "woo-iran-shetab-card-field"
    "voce-cached-nav"
    "prime-addons-for-elementor"
    "absoluterss"
    "hebrewdates"
    "get-my-tweets"
    "website-copy-protection"
    "photojar-post-thumbnailer"
    "aqua-svg-sprite"
    "simple-vote"
    "goldstar"
    "woo-wholesale-discount"
    "bit-social"
    "wp-sms-otp-login"
    "reactive-lite-advance-searching-filtering-grid"
    "take-control-of-the-wordpress-toolbar"
    "r3df-meetup-widget"
    "custom-search-url-nice-search-extension"
    "wp-serverless-forms"
    "altruja"
    "sticky-notes-widget"
    "payplug-payments"
    "bp-import-blog-activity"
    "tokenico-cryptocurrency-token-launchpad-presale-ico-ido-airdrop"
    "boo-recipes"
    "5-stars-rating-funnel"
    "loudvoice-comment-system"
    "quotegenerator"
    "disqus-popular-threads-widget"
    "ns-adblock-blocker"
    "seznam-webmaster"
    "wp-show-site-by-ip"
    "tableofcontent"
    "hide-admin-navbar"
    "advanced-dates"
    "geowidget"
    "users-registered-list"
    "allow-reinstalls"
    "appointment-scheduling-and-booking-manager"
    "expiring-posts"
    "blizhost-cache-purge"
    "simple-auto-tag"
    "live-members-counter-for-discord"
    "lastfm-played-for-wp"
    "featured-custom-posts-widget"
    "wordpress-password-cracker"
    "cryptocurrency-exchanges"
    "twitter-bootstrap-collapse-aka-accordian-shortcode"
    "easyjscss"
    "kinguin"
    "handyplugins-paddlepress"
    "woocommerce-multi-item-slider"
    "phone-button"
    "masterstudy-lms-divi-modules"
    "ilc-flvbox"
    "wp-default-author"
    "oneid"
    "dismiss-gutenberg-nag"
    "formidable-gravity-forms-importer"
    "lazy-load-videos-and-sticky-control"
    "site-traffic-trend"
    "wp-picture-calendar"
    "utrust-for-woocommerce"
    "image-sizes-panel"
    "gamipress-badgeos-importer"
    "private-url"
    "daily-quotes"
    "easy-soundcloud-shortcode"
    "wp-widget-preview"
    "salsa-press"
    "ngsurvey"
    "openpay-pse"
    "mk-simple-backups"
    "romancart-ecommerce"
    "women-quotes"
    "anyguide"
    "catalog-mode-for-woocommerce"
    "wp-libre-form"
    "accordion-faq-for-elementor"
    "ez-schedule-manager-free"
    "eyes-only-plus"
    "javascript-block-widget"
    "aipress"
    "jumiapay-wc"
    "telephone-field-for-elementor-forms"
    "tax-exemption-woo"
    "wp-block-analytics-spam"
    "wp-krpano"
    "jquery-banner-rotate"
    "lorem-ipsum-blocks"
    "quicq"
    "single-post-message"
    "2em"
    "interactive-image"
    "hide-username-front-side"
    "dragonfly"
    "dunstan-error-page"
    "woo-order-google-map-location-finder"
    "snappy-list-builder"
    "currency-calculate"
    "offers-popup"
    "add-link-post"
    "shadow-screen-options"
    "woo-dynamic-re-marketing"
    "reset"
    "woo-becopay-payment-gateway"
    "duo-universal"
    "wordpress-sass"
    "important-links-widget"
    "confection"
    "connect-to-edara"
    "post-meta-searcher"
    "slack-contact-form-7"
    "adrotate-extra-settings"
    "surveyfunnel-lite"
    "cloudflare-rocket-loader-ignore"
    "affiliates-ecwid-light"
    "bulk-edit-upsells-and-cross-sells-for-woocommerce"
    "game-review-block"
    "crafty-clicks-postcode-lookup"
    "gbi-buy-now"
    "larbous-floating-menu"
    "wp-bible-embed"
    "transactium-woocommerce-addon"
    "nari-accountant"
    "category-subscriptions"
    "open-dining-menu"
    "wp-feature-disable"
    "foogallery-migrate"
    "testimonials-slider-block"
    "filter-email-notifications"
    "rtbiz"
    "wp-blocks"
    "frenzy"
    "mg-quotes"
    "holy-quran-random-ayahs"
    "block-logic"
    "quality-checklist-opquast"
    "sonypayment-light-for-woocommerce"
    "fabrica-dashboard"
    "woocommerce-filter-search"
    "wordpress-chinese-planet"
    "select-and-share"
    "packages-configuration-for-woocommerce"
    "simple-skrill"
    "header-footer-code"
    "easy-content-adder"
    "multisite-site-index"
    "woo-product-page-templates"
    "guto-toolkit"
    "fx-simple-loginlogout"
    "comment-saver"
    "simple-note"
    "rv-submenus"
    "lana-shortcodes"
    "additional-block-styles"
    "price-calculator-to-your-website"
    "search-my-theme"
    "food-truck"
    "testimonial-addon-for-wpbakery-page-builder"
    "tags-all-in-one"
    "jetpack-popular-posts"
    "intuitive-navigation"
    "seo-slugs-4-bbpress"
    "corona-covid-19-stats"
    "bootstrap-multi-language-responsive-testimonials"
    "easy-utm-builder"
    "flip"
    "simple-linkedin-feeds"
    "norse-runes-oracle"
    "wp-genesis-box"
    "weg-mit-219a"
    "buddypress-default-group-avatar"
    "livesession"
    "confirm-theme-structure"
    "nutrition-facts-vitamins"
    "parallaxer-lite-parallax-effects-on-images"
    "easy-dashboard"
    "jquery-scrollup"
    "my-quakenet-irc"
    "dl-yandex-webmaster"
    "remove-more-jump"
    "social-icon-links"
    "no-noopener-noreferrer-dont-add-relnoopener-noreferrer"
    "trust-payments-hosted-payment-pages-integration"
    "cache-me-button"
    "gravatar-hovercard"
    "parkingpro-booking-widgets"
    "easycpmods-toolbox"
    "popular-products-for-woocommerce"
    "wp-seo-content-cloaker"
    "comment-form-message"
    "fundraising-thermometer-by-couponbirds"
    "ld-video-resume"
    "wp-duplicate-posts-pages-cpt"
    "interactive-australia-map"
    "hero-for-genesis-framework"
    "rest-api-meta-support"
    "ithoughts-advanced-code-editor"
    "blockquote-cite"
    "gr-lorem-ipsum-generator"
    "ns-simple-intro-loader"
    "wpem-rest-api"
    "wp-calories"
    "blogwings-companion"
    "redbox-pickup"
    "socially-social-bookmarking-widget"
    "auto-image-resize"
    "create-sasnys-gift-voucher"
    "remove-default-checkout-fields-for-woocommerce"
    "disable-right-click-rb"
    "image-size-attributes-remover"
    "wicked-block-builder"
    "churchtithewp"
    "plugin-directory-stats"
    "o3world-members-only-categories"
    "comment-rating-stars"
    "gecka-bgstretcher"
    "digg"
    "stop-pinging-yourself-for-wordpress"
    "gp-machine-translate"
    "magic-food"
    "gweather"
    "coralcdn"
    "osom-login-page-customizer"
    "stop-oldies"
    "delicious-tagroll-shortcode"
    "esb-post-type-order"
    "custom-content-scrollbar"
    "kt-cleanpress"
    "upc-ean-barcode-generator"
    "sb-children-block"
    "buddypress-group-folders"
    "social-photo-feed-widget"
    "wc-notchpay"
    "download-manager-ms"
    "easy-menu-manager-wpzest"
    "wp-loop"
    "wp-photo-ads"
    "disable-comment-url"
    "ultimate-youtube-video-player"
    "cod-confirmation-for-india"
    "indicadores-economicos"
    "wp-konami-code"
    "kapida-kredi-karti-ile-odeme"
    "simple-lightbox-fslight"
    "envo-companion"
    "autochmod"
    "oqey-pdfs"
    "wp-remove-category-from-archive-title"
    "woocommerce-product-type-column"
    "notifikacie-sk"
    "easy-ip-blocker"
    "meta-robots-by-seo-sign"
    "wizhi-multi-filters"
    "booster-beaver"
    "reaktiv-css-builder"
    "matrimony"
    "sh-contextual-help"
    "tuis-author-intro-for-post"
    "easy-taxonomy-images"
    "yamato-credit-for-woo"
    "visual-user-description-editor"
    "pull-quotes"
    "photo-gallery-xml-export"
    "deactivate-xml-rpc"
    "narrafirma"
    "autotube"
    "age-gate-plus"
    "mintpay"
    "mycred-tutor-lms-gamification-in-elearning"
    "dofollow-state"
    "wp-is-mobile-text-widget"
    "tasador-de-coches"
    "simple-contact-forms"
    "floating-button-wp"
    "project-pages"
    "nutritionwp"
    "osm-tiles-proxy"
    "wp-login-flow"
    "woo-friendly-user-agent"
    "text-domain-inspector"
    "intelly-posts-footer-manager"
    "now-reading-redux"
    "wp-deadlines"
    "preload-requests"
    "waj-image-slider"
    "current-template-info"
    "kommunicate-live-chat"
    "simple-buttons-creator"
    "power-boost-for-gravity-forms"
    "useinfluence"
    "oembed-styling"
    "nofraud-protection"
    "support-x"
    "quiz-maker-save-progress"
    "easytranslate"
    "post-thumbnail-widget"
    "wp-youtube-relevent-video-player"
    "limit-daily-posts"
    "photopress-paypal-shopping-cart"
    "fastcomments"
    "opencart-product-in-wp"
    "tour-operator-reviews"
    "add-plain-text-email"
    "google-plus-share-button"
    "ipgp-geolocation"
    "biblefox-for-wordpress"
    "quick-product-image-upload"
    "kento-social-share"
    "polymer-components"
    "noio-iconized-bookmarks"
    "all-in-one-social-feeds"
    "secpay-bitcoin-payment-gateway"
    "user-mail-only-register"
    "genesis-connect-for-woothemes-sensei"
    "third-party-accounts-login"
    "cf-geoplugin-gps"
    "gf-campaign-fields"
    "easy-digital-downloads-continue-shopping"
    "bp-groups-civicrm-sync"
    "wp-simple-thimble"
    "display-yandex-zen-postgrid"
    "gravity-forms-light-blue-api-add-on"
    "helloadherents"
    "simple-rss-aggregator"
    "some-maps"
    "at-reply"
    "amazon-auto-linker"
    "media-trash-button"
    "video-thumbnailer-for-elementor"
    "bbpress-admin-notes"
    "vk-dynamic-if-block"
    "mention-me"
    "responsive-ui-for-beaver-builder"
    "sitewide-message"
    "copyscape"
    "texteller"
    "weather-traveller"
    "sketch"
    "jquery-tabber-widget"
    "counter-hits"
    "top-bar-links"
    "notifications-for-collapsed-admin-menu"
    "exly-wp"
    "wp-typograph-full"
    "drag-and-drop-custom-sidebar"
    "pregnancy-calculator"
    "timeago"
    "multisite-store-viewer"
    "currency-converter-widget-pro"
    "tax-report-for-woocommerce"
    "filestack-upload"
    "auto-smart-thumbnails"
    "copy-protection"
    "fantazy-sidebar"
    "guestplan-booking-widget"
    "relative-url-for-img-and-a-tags"
    "thumbshots"
    "disable-floc"
    "nexi-xpay-build"
    "wp-page-tree"
    "magic-sitemaps"
    "easy-google-tag-manager"
    "moreaboutme"
    "vertical-menu"
    "tinytoc"
    "endomondowp"
    "post-views-new"
    "catch-under-construction"
    "unit-converter"
    "nc-grid-list-view-for-woocommerce"
    "count-content-characters"
    "ehive-search"
    "poll-builder"
    "extra-product-addons-for-woocommerce"
    "dynamic-asset-versioning"
    "cryptophoto-two-and-multi-factor-authentication"
    "bookable-events"
    "full-name-search-in-wp-admin"
    "advanc-link-directory"
    "bp-show-activity-liked-avatars"
    "msd-pre-selected-cat"
    "mobi2go"
    "florahome"
    "gallery-slice"
    "jcwp-like-to-unlock-lite"
    "little-wp-to-twitter"
    "vision6-forms"
    "de-updraftplus-disable-admin-wp-cron-notice"
    "social-planner"
    "webhook-discord"
    "editor-cleanup-for-elementor"
    "cool-virtual-keyboard"
    "space-admin-theme"
    "multiple-twitter-widgets"
    "anchor-smooth-scroll"
    "stop-ie6"
    "trusty-whistleblowing-solution"
    "plugnmeet"
    "reflection"
    "profiles-manager-for-buddypress"
    "bbpress-unread-posts"
    "avoid-googles-cache"
    "tour-operator-special-offers"
)

# Define user agents with weights
declare -A USER_AGENTS
USER_AGENTS=(
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"]=5
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"]=7
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"]=6
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36 Edg/91.0.864.54"]=5
    ["Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 OPR/77.0.4054.277"]=3
    ["Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (iPad; CPU OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Vivaldi/4.0"]=1
    ["Mozilla/5.0 (Android 11; Mobile; rv:68.0) Gecko/68.0 Firefox/88.0"]=1
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"]=15
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/534.36"]=12
)

OPENED_PLUGINS_FILE="${WORDPRESS_WORKDIR}/opened_plugins.txt"
CLOSED_PLUGINS_FILE="${WORDPRESS_WORKDIR}/closed_plugins.txt"
LAST_VERSION_FILE="${WORDPRESS_WORKDIR}/last_versions.txt"
PARALLEL_JOBS=1

DOWNLOAD_ALL_PLUGINS='n'
LIST_ONLY='n'
ALL_PLUGINS_FILE="${WORDPRESS_WORKDIR}/wp-plugin-svn-list.txt"
START_COUNT=0
END_COUNT=0

DELAY_DOWNLOADS='n'
DELAY_DURATION=5

FORCE_UPDATE='n'
CACHE_ONLY='n'

mkdir -p "$WORDPRESS_WORKDIR" "$MIRROR_DIR" "$LOGS_DIR"
rm -f "$OPENED_PLUGINS_FILE"
touch "$OPENED_PLUGINS_FILE"
DEBUG_MODE=0

while getopts "p:dalD:t:fcs:e:" opt; do
    case ${opt} in
        p ) PARALLEL_JOBS=$OPTARG ;;
        d ) DEBUG_MODE=1 ;;
        a ) DOWNLOAD_ALL_PLUGINS='y' ;;
        l ) LIST_ONLY='y' ;;
        D ) DELAY_DOWNLOADS=$OPTARG ;;
        t ) DELAY_DURATION=$OPTARG ;;
        f ) FORCE_UPDATE='y' ;;
        c ) CACHE_ONLY='y' ;;
        s ) START_COUNT=$OPTARG ;;
        e ) END_COUNT=$OPTARG ;;
        \? ) echo "Usage: $0 [-p PARALLEL_JOBS] [-d] [-a] [-l] [-D DELAY_DOWNLOADS] [-t DELAY_DURATION] [-f] [-c] [-s START_COUNT] [-e END_COUNT]" 1>&2; exit 1 ;;
    esac
done

debug_log() {
    if [ "$DEBUG_MODE" -eq 1 ]; then
        echo "[DEBUG] $1" >&2
    fi
}

get_random_user_agent() {
    echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
}

get_latest_version_and_download_link() {
    local plugin=$1
    debug_log "Checking latest version and download link for $plugin"
    
    local api_url="https://api.wordpress.org/plugins/info/1.0/${plugin}.json"
    local user_agent=$(get_random_user_agent)
    local api_response=$(curl -s -H "User-Agent: $user_agent" "$api_url")
    
    if echo "$api_response" | jq -e '.error' >/dev/null; then
        local error_message=$(echo "$api_response" | jq -r '.error')
        if [ "$error_message" = "closed" ]; then
            echo "closed"
            return 2
        else
        echo "Error: $error_message for plugin $plugin" >&2
        return 1
        fi
    fi
    
    local version=$(echo "$api_response" | jq -r '.version // empty')
    local download_link=$(echo "$api_response" | jq -r '.download_link // empty')
    
    if [ -n "$version" ] && [ -n "$download_link" ]; then
        echo "$version $download_link"
        return 0
    else
        echo "Error: Cannot fetch version or download link for $plugin" >&2
        return 1
    fi
}

download_plugin() {
    local plugin=$1
    local version=$2
    local api_download_link=$3
    local output_file="${MIRROR_DIR}/${plugin}.${version}.zip"
    local header_file="${LOGS_DIR}/${plugin}.${version}.headers"
    local constructed_download_link="${DOWNLOAD_BASE_URL}/${plugin}.${version}.zip"
    local download_link

    if [ "$DEBUG_MODE" -eq 1 ]; then
        debug_log "API-provided download link for $plugin: $api_download_link"
        debug_log "Constructed download link for $plugin: $constructed_download_link"
    fi

    if [ "$DOWNLOAD_LINK_API" == 'y' ] && [ -n "$api_download_link" ]; then
        download_link="$api_download_link"
        debug_log "Using API-provided download link for $plugin: $download_link"
    else
        download_link="$constructed_download_link"
        debug_log "Using constructed download link for $plugin: $download_link"
    fi

    debug_log "Downloading $plugin version $version through Cloudflare Worker"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)
    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o /dev/null "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    else
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o "$output_file" "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    fi

    if [ $? -eq 0 ]; then
        if [ "$CACHE_ONLY" == 'y' ]; then
            debug_log "Plugin $plugin version $version cached successfully."
            return 0
        fi

        local file_size=$(stat -c%s "$output_file")
        if [ "$file_size" -lt 1000 ]; then
            echo "Error: Downloaded file for $plugin is too small (${file_size} bytes). Possible download issue." >&2
            return 1
        fi

        local source=$(grep -i "X-Source:" "$header_file" | cut -d' ' -f2 | tr -d '\r')
        if [ "$source" == "R2" ]; then
            debug_log "Successfully downloaded $plugin version $version from R2 storage"
        elif [ "$source" == "WordPress" ]; then
            debug_log "Successfully downloaded $plugin version $version from WordPress"
            debug_log "R2 bucket saving for plugin zip occurred"
        else
            debug_log "Skipped download for $plugin $version zip (already exists locally)"
        fi

        return 0
    else
        echo "Error: Failed to download $plugin version $version" >&2
        return 1
    fi
}

save_plugin_info() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.json"

    debug_log "Saving plugin json metadata for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying metadata download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    if [ "$CACHE_ONLY" == 'y' ]; then
        # When in cache-only mode, output to /dev/null
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin metadata for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache json metadata for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            if [ "$source" = "R2" ]; then
                debug_log "json metadata for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "json metadata for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin json occurred"
            else
                debug_log "json metadata for $plugin version $version saved (json metadata file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save json metadata for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

fetch_and_save_checksums() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.checksums.json"

    debug_log "Fetching and saving checksums for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying checksums download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    debug_log "Sending request to Worker for checksums: CF_WORKER_URL?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"

    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin checksums for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache checksums for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        debug_log "Received response with status code: $status_code"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            debug_log "Response source: $source"
            if [ "$source" = "R2" ]; then
                debug_log "Checksums for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "Checksums for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin checksums occurred"
            else
                debug_log "Checksums for $plugin version $version saved (checksums file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save checksums for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

process_plugin() {
    local plugin=$1
    plugin=$(echo "$plugin" | sed 's/^\/\|\/$//g')

    # Check if the plugin is already known to be closed
    if grep -q "^$plugin$" "$CLOSED_PLUGINS_FILE" 2>/dev/null; then
        echo "Plugin $plugin is known to be closed. Skipping."
        return 0
    fi

    echo "Processing plugin: $plugin"

    VERSION_AND_LINK=$(get_latest_version_and_download_link "$plugin")
    local version_check_status=$?
    
    if [ $version_check_status -eq 1 ]; then
        echo "Skipping $plugin due to version fetch error."
        return 1
    elif [ $version_check_status -eq 2 ]; then
        echo "Plugin $plugin is closed. Skipping download and processing."
        echo "$plugin" >> "$CLOSED_PLUGINS_FILE"
        if save_plugin_info "$plugin" "closed"; then
            debug_log "Successfully saved json metadata for closed plugin $plugin."
        else
            debug_log "Failed to save json metadata for closed plugin $plugin."
        fi
        return 0
    fi
    
    LATEST_VERSION=$(echo "$VERSION_AND_LINK" | cut -d' ' -f1)
    API_DOWNLOAD_LINK=$(echo "$VERSION_AND_LINK" | cut -d' ' -f2-)

    debug_log "Latest version for $plugin: $LATEST_VERSION"
    debug_log "API download link for $plugin: $API_DOWNLOAD_LINK"

    STORED_VERSION=$(grep "^$plugin" "$LAST_VERSION_FILE" | awk '{print $2}')
    debug_log "Stored version for $plugin: $STORED_VERSION"

    if [ "$CACHE_ONLY" != 'y' ] && [ "$LATEST_VERSION" == "$STORED_VERSION" ] && [ -f "${MIRROR_DIR}/${plugin}.${LATEST_VERSION}.zip" ]; then
        echo "$plugin is up-to-date and exists in mirror directory. Skipping download..."
    else
        start_time=$(date +%s.%N)

        if download_plugin "$plugin" "$LATEST_VERSION" "$API_DOWNLOAD_LINK"; then
            if [ "$CACHE_ONLY" != 'y' ]; then
                sed -i "/^$plugin/d" "$LAST_VERSION_FILE"
                echo "$plugin $LATEST_VERSION" >> "$LAST_VERSION_FILE"
            fi
            echo "Successfully processed $plugin."
        else
            echo "Error: Failed to process $plugin." >&2
        fi

        end_time=$(date +%s.%N)
        duration=$(echo "$end_time - $start_time" | bc)
        printf "Time taken for %s: %.4f seconds\n" "$plugin" "$duration"
    fi

    if save_plugin_info "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully saved json metadata for $plugin."
    else
        debug_log "Failed to save json metadata for $plugin."
    fi

    if fetch_and_save_checksums "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully fetched and saved checksums for $plugin."
    else
        debug_log "Failed to fetch and save checksums for $plugin."
    fi

    if [ $version_check_status -eq 0 ]; then
        echo "$plugin" >> "$OPENED_PLUGINS_FILE"
    fi
}

populate_all_plugins() {
    if [ ! -f "$ALL_PLUGINS_FILE" ] || [ "$LIST_ONLY" == 'y' ]; then
        echo "Fetching list of all WordPress plugins..."
        svn list https://plugins.svn.wordpress.org/ | sed 's/\/$//g' > "$ALL_PLUGINS_FILE"
        plugin_count=$(wc -l < "$ALL_PLUGINS_FILE")
        echo "Plugin list (${plugin_count}) saved to $ALL_PLUGINS_FILE"
    fi
    
    if [ "$LIST_ONLY" == 'n' ]; then
        ALL_PLUGINS=()
        if [ "$DOWNLOAD_ALL_PLUGINS" == 'y' ] && [ $START_COUNT -gt 0 ] && [ $END_COUNT -ge $START_COUNT ]; then
            echo "Processing plugins from line $START_COUNT to $END_COUNT"
            while IFS= read -r line; do
                ALL_PLUGINS+=("$line")
            done < <(sed -n "${START_COUNT},${END_COUNT}p" "$ALL_PLUGINS_FILE")
        else
            while IFS= read -r line; do
                ALL_PLUGINS+=("$line")
            done < "$ALL_PLUGINS_FILE"
        fi
        echo "Loaded ${#ALL_PLUGINS[@]} plugins."
    fi
}

if [ "$LIST_ONLY" == 'y' ]; then
    populate_all_plugins
    echo "Plugin list created. Exiting without downloading."
    exit 0
fi

if [ "$DOWNLOAD_ALL_PLUGINS" == 'y' ]; then
    populate_all_plugins
    COMBINED_PLUGINS=("${ALL_PLUGINS[@]}")
else
    if [ ! -d "$PLUGIN_DIR" ]; then
        echo "Warning: Plugin directory $PLUGIN_DIR does not exist or is invalid."
        PLUGIN_LIST=()
    else
        PLUGIN_LIST=($(ls -d "$PLUGIN_DIR"/*/ 2>/dev/null | xargs -n 1 basename))

        if [ ${#PLUGIN_LIST[@]} -eq 0 ]; then
            echo "No plugins found in $PLUGIN_DIR."
        fi
    fi

    COMBINED_PLUGINS=(${PLUGIN_LIST[@]} ${ADDITIONAL_PLUGINS[@]})
    COMBINED_PLUGINS=($(echo "${COMBINED_PLUGINS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
fi

if [ ${#COMBINED_PLUGINS[@]} -eq 0 ]; then
    echo "No plugins to download. Exiting."
    exit 0
fi

mkdir -p "$MIRROR_DIR"
touch "$LAST_VERSION_FILE"

if [ "$PARALLEL_JOBS" -gt 1 ]; then
    echo "Running in parallel with $PARALLEL_JOBS jobs..."
    echo "Variables before export:"

    # WordPress-related directories
    echo "WORDPRESS_WORKDIR: $WORDPRESS_WORKDIR"
    echo "PLUGIN_DIR: $PLUGIN_DIR"
    echo "MIRROR_DIR: $MIRROR_DIR"
    echo "LOGS_DIR: $LOGS_DIR"

    # Cloudflare Worker related URLs
    echo "CF_WORKER_URL: $CF_WORKER_URL"

    # Flags and options
    echo "DOWNLOAD_LINK_API: $DOWNLOAD_LINK_API"
    echo "DOWNLOAD_ALL_PLUGINS: $DOWNLOAD_ALL_PLUGINS"
    echo "LIST_ONLY: $LIST_ONLY"
    echo "DELAY_DOWNLOADS: $DELAY_DOWNLOADS"
    echo "DELAY_DURATION: $DELAY_DURATION"
    echo "FORCE_UPDATE: $FORCE_UPDATE"
    echo "CACHE_ONLY: $CACHE_ONLY"

    # File paths
    echo "OPENED_PLUGINS_FILE: $OPENED_PLUGINS_FILE"
    echo "CLOSED_PLUGINS_FILE: $CLOSED_PLUGINS_FILE"
    echo "LAST_VERSION_FILE: $LAST_VERSION_FILE"
    echo "ALL_PLUGINS_FILE: $ALL_PLUGINS_FILE"

    # Parallel job configuration
    echo "PARALLEL_JOBS: $PARALLEL_JOBS"

    # User Agents mapping
    echo "USER_AGENTS: ${USER_AGENTS[@]}"

    # Additional plugins to be processed
    # echo "ADDITIONAL_PLUGINS: ${ADDITIONAL_PLUGINS[@]}"

    # Plugin List (loaded from directory or ALL_PLUGINS_FILE)
    #echo "PLUGIN_LIST: ${PLUGIN_LIST[@]}"
    #echo "COMBINED_PLUGINS: ${COMBINED_PLUGINS[@]}"

    # First, export all variables including USER_AGENTS
    export DOWNLOAD_BASE_URL MIRROR_DIR LAST_VERSION_FILE DEBUG_MODE DOWNLOAD_LINK_API LOGS_DIR ALL_PLUGINS_FILE DOWNLOAD_ALL_PLUGINS LIST_ONLY CF_WORKER_URL DELAY_DOWNLOADS DELAY_DURATION FORCE_UPDATE CACHE_ONLY WORDPRESS_WORKDIR PLUGIN_DIR PARALLEL_JOBS OPENED_PLUGINS_FILE CLOSED_PLUGINS_FILE USER_AGENTS

    # Then, export the functions
    export -f process_plugin get_latest_version_and_download_link download_plugin debug_log populate_all_plugins save_plugin_info get_random_user_agent fetch_and_save_checksums
    printf "%s\n" "${COMBINED_PLUGINS[@]}" | xargs -P $PARALLEL_JOBS -I {} bash -c 'process_plugin "$@"' _ {}
else
    for plugin in "${COMBINED_PLUGINS[@]}"; do
        process_plugin "$plugin"
    done
fi

if [ "$DOWNLOAD_ALL_PLUGINS" == 'y' ]; then
    if [ -f "$CLOSED_PLUGINS_FILE" ]; then
        echo
        echo "Closed Plugin List: $CLOSED_PLUGINS_FILE"
        echo "Total closed plugins: $(wc -l < "$CLOSED_PLUGINS_FILE")"
    else
        echo
        echo "No closed plugins found."
    fi
    if [ -f "$OPENED_PLUGINS_FILE" ]; then
        echo
        echo "Opened Plugin List: $OPENED_PLUGINS_FILE"
        echo "Total opened plugins: $(wc -l < "$OPENED_PLUGINS_FILE")"
    else
        echo
        echo "No open plugins found."
    fi
fi
echo "Plugin download process completed."
