#!/bin/bash

# Base directory (script location)
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Configurable directories
WORDPRESS_WORKDIR="${WORDPRESS_WORKDIR:-$BASE_DIR/wordpress-plugins}"
PLUGIN_DIR="${PLUGIN_DIR:-$BASE_DIR/wp-content/plugins}"
MIRROR_DIR="${MIRROR_DIR:-$BASE_DIR/mirror}"
LOGS_DIR="${LOGS_DIR:-$BASE_DIR/plugin-logs}"

# Check for CF_WORKER_URL environment variable
if [ -z "$CF_WORKER_URL" ]; then
    echo "Error: CF_WORKER_URL environment variable is not set." >&2
    exit 1
fi

DOWNLOAD_BASE_URL="https://downloads.wordpress.org/plugin"

# Other variables
DOWNLOAD_LINK_API='y'

ADDITIONAL_PLUGINS=(
    "exceltheme-addon"
    "colorful-post"
    "wp-validator"
    "wp-hrms"
    "wpms-network-global-inserts"
    "simple-posts-generator"
    "avalon23-products-filter-for-woocommerce"
    "show-youtube-subscribers-count"
    "fc-wp"
    "affiliates-captcha"
    "friendfeed-api-core"
    "wp-gdpr-cookie-consent"
    "gravity-forms-entries-inventory-management"
    "sms-for-woocommerce"
    "hdforms"
    "pryc-wp-add-timestamp-to-stylecss-link"
    "attachments-plus-plus"
    "turn-on-blog-privacy"
    "eangel"
    "powercash21-payments-gateway"
    "image-filters"
    "genesis-simple-hero-image"
    "handle-external-links"
    "unblock-adblocker"
    "showguests"
    "wp-google-maps-auto-business-place-finder"
    "rename-db-table-prefix"
    "camoo-sms"
    "wp-google-pagespeed-image-optimizer-lite"
    "maxima-velocidad"
    "divisas-chilenas"
    "gosign-grid-container-block"
    "read-me-later"
    "mipl-wc-multisite-sync"
    "fifthsegment-whitelist"
    "stylish-twitter-profile-box"
    "mi-libreria"
    "password-vault"
    "amz-watcher"
    "prohotpoints-gallery"
    "webmicro-braintree-woo-addon"
    "wpjm-schema"
    "buddypress-xmlrpc-receiver"
    "advanced-login-form"
    "mpress-menu-wormhole"
    "author-discussion"
    "maven-algolia"
    "easybackendstyle"
    "facturante"
    "last-modified-dashboard-widget"
    "cube-3d"
    "wp-auto-updates"
    "romancartwppluginstd"
    "ultimateadminsms"
    "multisite-user-role-sync"
    "admin-bar-addition-for-woocommerce"
    "hashtag-url-placeholder"
    "wp-universal-newsletter"
    "ivisa-travel"
    "jsonpress"
    "wp-disable-autofill"
    "isidore-suggestions"
    "post-signature"
    "no-ie"
    "spam-blip"
    "local-magic"
    "liquid-chatgpt"
    "form1"
    "wp-single-login"
    "gp-sticky-buttons"
    "one-meta-description"
    "product-licensing-system"
    "gtuk-unpublish-posts"
    "smartsearchwp"
    "admin-login-template"
    "list-view-for-posts"
    "sticky-blocks"
    "bolcom-partnerprogramme"
    "multi-networks-setup"
    "jajadi-training"
    "addweb-google-popular-post"
    "hello-norris"
    "contact-form-dashboard"
    "personalized-chuck-norris-joke-widget"
    "online-pre-travel-shopping"
    "vivocha-activation-tool"
    "form-data-manager"
    "opal-portfolios"
    "attribute-dropdowns"
    "pushall"
    "auto-ecommerce-seo"
    "free-slider"
    "getshop-ecommerce"
    "codup-read-only-admin"
    "global-settings"
    "autopilot"
    "loxi-event-calendar"
    "csv-to-db"
    "wp-tagtip"
    "mice-operations"
    "list-locations-bmlt"
    "who-stick-it"
    "my-news-ticker"
    "hatena-star"
    "wcmp-razorpay-split-payment"
    "e-mail-campaign-manager"
    "3d-roll-over-links"
    "ctc-flatbuttons"
    "geekpress"
    "twitter-highlight"
    "auto-approve-comments-for-specific-posts"
    "hide-link"
    "wp-initials-avatar"
    "buddypress-multi-group-remove"
    "clean-elementor"
    "booking-system-trafft"
    "videolog-insert-videos"
    "payment-gateway-via-borgun-rpg-for-woocommerce"
    "wp-linked-data"
    "tiledesk-live-chat"
    "get-google-reviews"
    "restrict-registration"
    "aio-tools"
    "user-profile-pic"
    "slug-control"
    "buddypress-activity-stream-atgroups"
    "last-login"
    "improved-nav-menu"
    "wpclothes2order"
    "wedos-online-monitoring"
    "wp-user-role-switcher"
    "ipay-for-woocommerce"
    "wplingua"
    "404s"
    "users-site-menu-link"
    "xo-for-angular"
    "clean-admin-ui"
    "the-publisher-desk"
    "eprolo-pod-dropshipping"
    "fixed-html-toolbar"
    "responsive-search"
    "arcw-popover-addon"
    "dl-maintenance-mode"
    "runpress"
    "dedinomy"
    "topbar-countdown"
    "uw-cals-google-custom-search-engine"
    "tubular"
    "feedplus"
    "payzippy-woocommerce-payment-gateway"
    "custom-cssjs"
    "lct-admin-bar-on-bottom"
    "divelogs-widget"
    "quran-verse-a-day"
    "wp-website-creator"
    "iso-2-utf-data-converter"
    "wp-admin-logo-customization"
    "wp-hresume"
    "filter-posts-by-date-range"
    "yellow-schedule"
    "simple-author-widget"
    "avatar-3d-creator"
    "acf-fields-display"
    "subcontent"
    "chat-button-nsi"
    "simple-dashboard"
    "storefront-hooks-customizer"
    "sharpen-images"
    "wp-css-text-stroke"
    "automatic-submenu"
    "world-domination"
    "product-gallery-slider-for-wc"
    "wp-applink"
    "bangla-number-converter"
    "wp-vulnerability-scanner"
    "appstore-italia"
    "nelio-unlocker"
    "woo-products-tree"
    "wp-colored-coding"
    "shopybot-woocommerce"
    "wp-linkex"
    "sidebar-cart"
    "ci-hub-connector"
    "indieweb-press-this"
    "wpcafe-oxygen-addon"
    "featured-image-in-admin-panel"
    "tag-manager-web-analytics-for-amp"
    "hooks"
    "wp-inline-access"
    "wponerror"
    "combidesk-eboekhouden"
    "responsive-customizer"
    "rss-custom-fields-images"
    "magnify-publisher"
    "floating-section-elementor"
    "coupon-bulker"
    "myorderdesk"
    "application-banner-google-playstore-applestore"
    "legacy-jetpack-custom-css-editor"
    "wpcustom-preloader"
    "accessibility-language"
    "browser-address-bar-color"
    "embed-piwigo"
    "unfluff-io-content-optimization"
    "wpc-attribute-groups"
    "sticky-on-scroll"
    "xbooster-advanced-text-widget"
    "wordpress-database-ping"
    "vacancy-personal-edition"
    "common-ninja"
    "media-folders-lite"
    "xanga-importer"
    "pm-thumbnail-picture-menu"
    "mc-good-bye-howdy"
    "buy-a-brick"
    "speed-up-contact-form-7"
    "logo-scheduler-great-for-holidays-events-and-more"
    "breadcrumbspress"
    "formidable-kinetic"
    "hidecaptcha"
    "wp-random-post"
    "contact-form-7-browsing-history"
    "yd-prevent-comment-impersonation"
    "cm4all-wp-impex"
    "daily-menu"
    "forum-redirect"
    "import-products-variations-and-attributes-free-by-wp-masters"
    "wangguard-registration-notice-add-on"
    "wp-spellcheck"
    "flex-guten"
    "compe-woo-compare-products"
    "cubecolour-metabox-glue"
    "usermeta"
    "magic-edge-lite-image-background-remover"
    "pterotype"
    "system-fonts"
    "footerize"
    "automate-slack-invite-gravityforms"
    "urlyar"
    "external-files"
    "provinces-and-districts-of-panama-for-woocommerce"
    "baby-loader"
    "product-watcher"
    "delivery-rate-for-yamato-transport"
    "website-testimonials"
    "releva-nz"
    "bp-mutual-friends"
    "post-url-qr-code"
    "rainbow-address-bar"
    "bog-ipay-payment-gateway"
    "idpay-paid-memberships-pro"
    "magazine-lister-for-yumpu"
    "edd-license-key-template"
    "woocommerce-count-orders-in-adminbar"
    "wp-3d-motion-slider"
    "nplogin"
    "awesome-featured-post-widget"
    "metabase-post-user-meta-editor"
    "protect-wp-config-from-phishing-attacks"
    "radiopotok"
    "skysa-tweet-app"
    "automater-pl"
    "https-social-migration"
    "recover-text-widgets"
    "un-official-fiverr-plugin"
    "cf7-bitrix24-integration"
    "sp-announcement"
    "block-context"
    "admin-menu-organizer"
    "woocommerce-downlaod-product-from-admin"
    "whisk-recipes"
    "greenweb"
    "table-of-contents-for-tinymce"
    "spam-notifier"
    "user-allowed-ip-addresses"
    "web-screenshots"
    "mapping-of-image-posts"
    "cta-widget-manager"
    "wp-admin-error-handler"
    "subscription"
    "mapotic-community-maps"
    "fix-forum-breadcrumbs"
    "browse-as"
    "archive-cloud"
    "dx-share-selection"
    "integration-for-nummuspay"
    "about-us-shortcode"
    "author-box-plus"
    "social-media-popup-free"
    "news-slider"
    "bulk-create-blogs"
    "outdated-plugin-notifier"
    "accessiblewp-images"
    "wp-rest-api-options"
    "flash-swfobject"
    "product-redirection-for-woocommerce"
    "postcode-redirect"
    "carla"
    "wp-custom-post-template-redux"
    "wp-social-broadcast"
    "wdes-rtmedia-music"
    "add-custom-post-type-slugs-to-admin-body-class"
    "smart-search"
    "display-opencart-category"
    "wp-wave-shortcodes"
    "development-mode-for-jetpack"
    "jc-ajax-comment"
    "shopp-campaign-monitor"
    "website-rating"
    "mailchimp-as-a-registration"
    "help-menu"
    "disable-theme-and-plugin-editor"
    "jet-active-blog-list-ru-edition"
    "woocommerce-checkout-extra-options"
    "save-to-google-drive-by-forum-gt"
    "securepay-for-wpforms"
    "require-post-tags"
    "upscribe"
    "lorem-user-generator"
    "content-molecules"
    "scale-large-image-threshold"
    "wp-digital-clock"
    "ym-twitter-feed"
    "wp-ecommerce-quickpay"
    "awesome-recipe"
    "private-by-default"
    "apercite"
    "dancepress-trwa"
    "thekendienst"
    "meta-news-standout-tag"
    "member-private-navbar"
    "commercial-real-estate-valuation-calculator"
    "pmpro-unlock"
    "headwp"
    "alterskontrollede-plugin"
    "database-debugging-tools-for-developers"
    "accessible-tag-cloud"
    "dynamic-pricing-quantity-table"
    "wowrestro"
    "tag-list"
    "athemes-addons-for-elementor-lite"
    "theme-changer"
    "psw-login-and-registration"
    "withinweb-remove-spam-subscribers"
    "helldap"
    "portfolio-by-lisa-westlund"
    "ontraport-to-wishlist-integration"
    "different-home-for-logged-in-logged-out"
    "coupon-by-user-role-for-woocommerce"
    "recent-post-to-wp-nav-menu"
    "custom-category-listing-page"
    "maui-marketing-script-manager"
    "mask-contact-form"
    "advanced-earthquake-monitor"
    "gamipress-lifterlms-group-leaderboard"
    "nds-wolfcrm-forms-integration"
    "rtsyntax"
    "miraget-b2b-leads-generation"
    "travel-routes"
    "hikari-unicornified-gravatars"
    "floating-icons"
    "harmonia"
    "wpartisan-multisite-crossposter"
    "dramatars"
    "woocom-role-based-reports"
    "ajs-footnotes"
    "urpay-woocommerce"
    "sudo-oauth"
    "wpconcierges-linkedin-insights"
    "wp-redirect-to-homepage-after-login"
    "gf-pushover-add-on"
    "dhivehi-text"
    "flicknpress"
    "bike-rental-manager-calendar"
    "link-footnotes"
    "thesis-theme-featured-posts-box"
    "mitsol-tweets"
    "automatic-tooltips"
    "gift4u-gift-cards-all-in-one-for-woo"
    "flickrphotogallery"
    "uw-madison-events-calendar"
    "language-code"
    "checkview"
    "simple-font-resizer"
    "spreebie-transcoder"
    "all-in-one-performance-accelerator"
    "viewport-exchanger"
    "mooontes-comments-media-upload"
    "choc-chip-eu-cookie-plugin"
    "antdiy"
    "blogs-mexico-ping"
    "apcopay-for-woocommerce"
    "simple-image-slider"
    "video-embed-optimizer"
    "menu-section-titles"
    "wp-admin-buttons"
    "wp-smart-content-protection"
    "cit-media-sync"
    "wp-api-stats"
    "switch-simple-cookie-notice"
    "justrows-free"
    "custom-user-guide"
    "wpdtol-database-table-overview-logs"
    "menu-url-string"
    "flat-file-bootstrap-slider"
    "cartstack-for-woocommerce"
    "recently-purchased-products-for-woo"
    "bp-group-home-widgets"
    "wp-term-locks"
    "get-json-api"
    "wp-getting-started"
    "google-maps-gps-link"
    "invisible-recaptcha-by-threatpress"
    "shop-page-customizer-for-woocommerce"
    "bootstrap-contact-form"
    "aksh-mailchimp-widget"
    "bronto-newsletter-signup"
    "woodpecker-click-to-translate"
    "first-data-for-pmpro"
    "edd-checkout-notes"
    "crowdfunding-regions"
    "widget-magic"
    "cacheability"
    "smtp-locaweb"
    "digi-id-authentication"
    "rss-news-scroller-by-pierpaolo-romanelli"
    "xbooster-social-icons-with-counter"
    "wp-nav-collapse"
    "tsu"
    "ultimate-searchable-accordion-lite-wpbakery-page-builder-addon"
    "add-target-fixer"
    "minimal-contact-form"
    "aviso-de-cookies-de-amplifica"
    "pepperjam-pixel"
    "slider-bootstrap-carousel"
    "nevistas-news"
    "immobilcio-agenzie-immobiliari"
    "optiontree-shortcode"
    "display-category-post-count"
    "auto-generate-submenus"
    "rondeo-sign-in-with-google-button"
    "flickr-flash-slideshow"
    "charitas-lite"
    "wordpress-post-tab-widget"
    "vidjet"
    "utm-switcher"
    "notify-old-blog"
    "sproutedweb-wp-support"
    "bp-template-overloader"
    "ha-font-color-customizer"
    "kaya-login-notification"
    "ekassa-all-products-by-note-shot-oy"
    "dishsoap"
    "tiny-youtube-post-widget"
    "content-visibility-rss-feed"
    "limit-max-ips-per-user"
    "dynamic-url-seo"
    "mediathek"
    "siteattention"
    "recaptcha-lite"
    "the-best-price-filter-for-woocommerce"
    "horizontal-scroll-slider"
    "happierleads"
    "twitter-content-locker"
    "braille"
    "aparat-feed"
    "wc-checkout-for-chinese"
    "os-woocommerce-authorizenet-aim"
    "pg-360-generator"
    "no-copy-block-text-selection"
    "page-teaser-widget"
    "swfobjectjquery"
    "revised-publishing-status"
    "clima-widget"
    "mariadb-health-checks"
    "wp-lenta9may"
    "microid"
    "wp-blockquote-shortcode"
    "cf7-export-csv"
    "contact-for-telegram"
    "menus-history"
    "wp-pocket-urls"
    "cron-tasks-viewer"
    "mapme"
    "wangguard-limited-registration-domain-add-on"
    "gravity-forms-add-button-class"
    "event-espresso-smooth-integration"
    "latest-registered-users"
    "duitku-pop-payment-gateway"
    "embed-wikimedia"
    "wp-geometa"
    "dimbal-poll-manager"
    "virtual-moderator"
    "linkle"
    "lord-linus-business-hours"
    "romanian-billing-fields"
    "woo-phone-number-validator"
    "sahih-al-bukhari-hadiths"
    "wc-show-method-in-orders-list-for-pagseguro"
    "ect-sitemap"
    "conferencer"
    "dusupay-payment-gateway-for-woocommerce"
    "strong-authentication"
    "bbp-profile-link-shortcode"
    "recently-bought-this-for-woocommerce"
    "lotto"
    "tsf-multistep-checkout-for-woocommerce"
    "wpmeetup-widget"
    "ultimate-maintenance-mode-for-woocommerce"
    "suntimes-widget"
    "language-option-for-acf4-fields"
    "web2easy"
    "yun-tui-jian"
    "upress-link"
    "wp-theme-statistic"
    "spotify-follow-button-widget"
    "digitally-custom-posts"
    "advanced-options-editor"
    "rss-campaign"
    "swtor-recruitment"
    "wp-lazy-load"
    "installments-for-stripe-gf"
    "scroll-triggered-widget-area"
    "modal-post-images"
    "jump-to-page-edit"
    "dynamic-countdown-with-acf-and-elementor"
    "well-known-uris"
    "jpeg-png-compressor"
    "quipu-accounting-for-woocommerce"
    "wd3k-give-feedback"
    "grader"
    "count-shortcode"
    "map-engine"
    "wpsol"
    "power-calculator"
    "editor-buttons-simplified"
    "meteohub"
    "pullquote"
    "test-data-creator"
    "rate-this-author"
    "html5-speech"
    "woo-customer-insight"
    "generate-shortcode"
    "categorylist"
    "amity-related-posts"
    "mycred-zoom-rewards"
    "attending-users"
    "food-recipes"
    "wp-fastclick"
    "linked-orders-for-woocommerce"
    "voce-submenu-items"
    "download-featured-images"
    "simple-push-subscribe-button"
    "easygeo"
    "wp-database-fetch"
    "better-editor-for-oxygen"
    "add-product-frontend-for-woocommerce"
    "longshot-ai-long-form-writing-assistant"
    "colors"
    "wp-user-defaults"
    "wp-facts"
    "beautiful-animation"
    "notifadz-by-adrenalead-web-push-notifications"
    "wc-variation-images"
    "tc-disable-browser-upgrade-warning"
    "codelibs"
    "xbox-360-info"
    "wp-hideshow-passwords-woocommerce"
    "trustspot-reviews-for-woocommerce"
    "user-profile-fields"
    "classic-editor-on-off"
    "idpay-payment-learnpress"
    "pdf-invoice-packing-slip-generator-lite-for-woocommerce"
    "text-widget-as-link"
    "url-shortener-for-twitter-tools"
    "developer-options-plugin"
    "lct-temporary-wpautop-disable-shortcode"
    "tour-booking"
    "smartchat"
    "ig-twitter-cards"
    "capitalize-post-title"
    "ga-meta-tags"
    "weddingcity-lite"
    "mycred-square"
    "ublux-wsp"
    "simple-seo-woo-by-falbar"
    "protected-content"
    "featured-image-with-url"
    "speed-accept-bitcoin-payments"
    "site-search-analytics-by-measured-search"
    "wp-nonregcontent"
    "wp-able-player"
    "pt-ao90"
    "tld-woocommerce-downloadable-product-update-emails"
    "wp-front-end-developer"
    "duplicate-post-rb"
    "wpop-wpforms-to-hubspot"
    "news-aggregator"
    "wp-simple-chat"
    "notifycomment"
    "wp-tinypng"
    "pesepay"
    "wiki-append"
    "translate-content"
    "applicantpro"
    "seo-lexikon"
    "disable-feeds-wp"
    "author-image"
    "mcl-slidein-nav"
    "syntaxhighlighter-evolved-swift-brush"
    "wp-pagalocard-woocommerce"
    "power-forms-builder"
    "weixinhost"
    "login-themes"
    "atr-inline-rtl-ltr"
    "wp-slideyournet"
    "sticky-social-link"
    "better-recent-drafts"
    "opal-estate-packages"
    "gp-hub-driver-widget"
    "writing-on-github"
    "hide-wp-engine-legacy-staging"
    "wp-user-vandalism-protection"
    "private-email-notifications"
    "amp-post-script"
    "factoid"
    "like-share-my-site"
    "easy-github-gist-shortcodes"
    "fs-link-posts"
    "custom-registration"
    "multiple-admin-emails"
    "freshmarketer"
    "posts-edit-subpanel-date-format"
    "rk-image-upload"
    "embedded-cdn"
    "post-category-height-edit"
    "kursy-walut-nbp"
    "blog-layout-design"
    "shipping-method-for-hermes-germany-and-wc"
    "woo-braspress"
    "page-siblings"
    "content-visibility-user-role"
    "buen-fin"
    "um-story-lite"
    "simple-breadcrumb"
    "corner-blog-decoration"
    "restaurant-menu-ordering"
    "pictips"
    "idpay-for-restrict-content-pro"
    "invitation-code-for-contact-form-7"
    "press-release"
    "expandable-faq"
    "any-post-slider"
    "off-your-site"
    "mobipaid"
    "live-widget-luftdaten"
    "voice-forms"
    "widget-for-opio-reviews"
    "social-icons-lite"
    "wpcas-server"
    "pages"
    "redirect-to-page-if-not-logged-in"
    "forget-user-info"
    "inventive-gravity-forms-tooltips"
    "redirect-multisite-user-to-their-own-site"
    "appsell"
    "wp-changelog"
    "wp-comment-redirect"
    "select-all-terms"
    "content-sidebars"
    "minor-improvements"
    "extended-theme-option"
    "wp-plugin-installer"
    "benchmark-email-integration-for-cf7"
    "slimage"
    "primary-redirect"
    "mootools-image-lazy-loading"
    "nutshell-analytics"
    "yabe-ukiyo"
    "resume-cv-block"
    "ip-loc8"
    "nofollow-shortcode"
    "rename-vat-to-gst-for-woocommerce"
    "amin-chat-button"
    "note-finder-for-woocommerce"
    "photo-sphere-viewer"
    "dispensary-blocks"
    "woo-widget-for-ratingchamp-reviews"
    "wx-subscribe"
    "wp-awesome-back-to-top"
    "custom-popup-builder-for-elementor"
    "shippop-ecommerce"
    "bugherd-dashboard"
    "simple-account-system"
    "rh-devnia-webfonts"
    "select-estados-e-cidades-brasil"
    "wp-social-meta-by-brozzme"
    "frontend-http-authentication-protection"
    "recent-popular-tags"
    "dojo"
    "trackbacks-template"
    "essential-breadcrumbs"
    "moovin-delivery"
    "my-trending-post"
    "cv-demo-importer"
    "jvh-easy-scss-and-js"
    "woocommerce-checkout-age-varification"
    "mowomo-bloques"
    "guten-bubble"
    "microtango"
    "mwa-zoom-meetup"
    "exit-intent-popups-conversion-optimization-by-exitbee"
    "wish-pics"
    "automatic-twitter-links"
    "simple-checkout-digital-goods"
    "wp-simple-membership"
    "appendad"
    "xtcz-top-box-office"
    "financial-toolbox"
    "whws-display-in-stock-products-first-for-woocommerce"
    "sortable-sticky-posts"
    "hangouts-cosmoquest"
    "log-deprecated-notices-extender"
    "yawave"
    "tmy-globalization"
    "factureaza"
    "admin-hide-tag-filter"
    "xml-shipping-importer-for-woocommerce"
    "prediction-league"
    "coming-soon-mode"
    "show-theme-file"
    "daylife"
    "fatso"
    "bse-kronosexpress-shipping-woocommerce"
    "views-output-formats"
    "convert-to-bangla-date"
    "child-height-predictor"
    "watermark-hotlink-protection"
    "ondoku"
    "script-logic"
    "radyo-dinle"
    "simple-login-sc"
    "disable-custom-css"
    "booklaunch"
    "wp-ourstats-widget"
    "teportfolio"
    "increase-product-variation-limit-for-woocommerce"
    "acs-points"
    "index-pages"
    "simple-payu-latam"
    "buddyslack"
    "robokassa-for-jigoshop"
    "mycred-for-event-espresso-4"
    "withinweb-php-keycodes"
    "easy-curated-lists"
    "wplicense-it"
    "interactive-globes"
    "wp-bio-links"
    "bbp-yoast-seo"
    "gp-shortcuts"
    "nelio-maps"
    "update-notification"
    "stylish-smilies"
    "plugin-columns"
    "easy-woocommerce-brands"
    "automatic-video-page"
    "ucomment"
    "theta-carousel"
    "disable-register"
    "commission-widget-for-dokan"
    "pageslide"
    "wp-smart-variations"
    "kristall-integration"
    "discountx"
    "manual-payment-gateway-nagad"
    "illiant-landings"
    "woocommerce-user-coupon-management"
    "fx-login-customizer"
    "widgets-for-discourse"
    "responsive-background-by-djjmz"
    "wall-clocks"
    "authentiq"
    "lay-tin-vnexpress"
    "ostoolbar"
    "terms-and-conditions-open-in-new-tab"
    "k-brb-maintenance-or-coming-soon"
    "wc-solana-pay"
    "restrict-email-domains"
    "photography-core"
    "ttlive"
    "me-localtime"
    "lmsace-connect"
    "wp-user-rewards"
    "quote-requests-for-woocommerce"
    "ai-preloader"
    "extra-wp-rocket"
    "pz-recentcomments"
    "restrict-partial-content"
    "default-theme-pages"
    "cs-popup-maker"
    "move-to-trash-from-admin-bar"
    "contact-form-7-referrer-addon"
    "css-injector"
    "adgoal-affiliate-marketing-monetization"
    "woo-checkout-braspag"
    "count-unique-visitors-widget"
    "paywithterra-payment-gateway"
    "schedules"
    "simple-license-key-for-woocommerce"
    "subscribe-privacy-jetpack"
    "paperform-form-builder"
    "automatic-file-renamer"
    "lt-unleashed"
    "parsedown-wp"
    "apppago"
    "az-order"
    "simple-voting"
    "welcome-to-the-block-editor-b-gone"
    "aweos-youtube-iframe-load-per-click"
    "sparkle-paddle-payment-gateway-lite"
    "gdpr-for-ninja-forms"
    "directiq-wp"
    "add-ribbon"
    "wp-log"
    "external-css"
    "ytlink"
    "easy-custom-login"
    "cryptoniann-tools"
    "gitdown"
    "teachable"
    "woo-archive-orders"
    "recapture-for-paid-memberships-pro"
    "popularposts"
    "credly-login"
    "flickr-header"
    "edd-prevent-checkout"
    "correios-etiqueta-e-declaracao"
    "simple-user-meta-editor"
    "fetch-spad"
    "visualcrossing-weather-forecast"
    "search-field-for-gravity-forms"
    "elex-product-feed"
    "carriers-of-argentina-for-woocommerce"
    "campaign-monitor-dual-registration"
    "changes"
    "team-member-addon-elementor"
    "image-switcher"
    "better-headers"
    "arsenalpay-for-woocommerce"
    "afiliados-de-amazon-lite"
    "omit-parent-theme-page-templates"
    "wp-list-sub-pages"
    "wp-org-plugin-stats"
    "plugin-disabler"
    "assets-to-footer"
    "webbricks-addons"
    "soccer-formation-ve"
    "wp-inline-js-converter"
    "fusion-retailers"
    "users2mailchimp"
    "stream-sage-for-woocommerce"
    "partnero"
    "wp-bookwidgets"
    "woostock"
    "daily-maui-photo-widget"
    "wp-multi-vendor-marketplace-the-courier-guy-shipping-for-woocommerce"
    "jumbo-share"
    "wpkeyme"
    "riotschedule"
    "stylistic-modals"
    "disable-lost-password-email"
    "shipping-rates-cities-woocommerce"
    "apoyl-weixin"
    "shipvista-live-shipping-rates"
    "aph-syntax-highlighter"
    "wp-viewer-log"
    "integration-for-elementor-forms-clickup"
    "animations-by-imoptimal"
    "rename-post-to-news"
    "responsive-media"
    "offline-pages"
    "wp-church-center-rss-syndication"
    "sharpay"
    "responsive-news-scroller"
    "simple-text-shortcodes"
    "botsonic"
    "change-date-language-english-speakers"
    "sv-posts"
    "briqpay-checkout-addon"
    "klix-image-dimsum"
    "pending-inidicator"
    "reusable-layouts-for-siteorigin"
    "lenses-prescription"
    "loginpetze"
    "connect-learndash-and-discord"
    "mnmlwp-simple-contact-form"
    "chehrak"
    "responsive-mobile-menu"
    "email-scheduling"
    "hytolat"
    "widget-botsify-chatbot"
    "koyomi"
    "influx"
    "simple-job-listings"
    "raw"
    "customizable-xml-feeds"
    "nepali-land-converter"
    "published"
    "gobuddy-the-smart-delivery-solution"
    "custom-resources"
    "label-plugins"
    "tinyfier-wp"
    "contentmx-content-publisher"
    "admin-bar-menu-packer"
    "pearl-twitter"
    "rd-wapp"
    "head-trimmer"
    "wp-term-families"
    "goracash"
    "better-messages-wc-vendors-integration"
    "storemapper"
    "appizy-app-embed"
    "simple-media-directory"
    "iutepay"
    "remove-code-version-tags"
    "get-youtube-subs"
    "pagemenu"
    "sass-compiler"
    "thanh-toan-the-cao-dien-thoai"
    "view-all-pages"
    "stackcommerce-deal-feed"
    "search-engines-blocked-warning"
    "rp-ads-manager"
    "enquir3-feedback"
    "block-widgets-monster"
    "columns-bws"
    "fest-widget"
    "wp-author-ranking"
    "remove-tags-taxonomy"
    "shauns-wp-query-shortcode"
    "github-flavored-markdown-comments"
    "offcanvas-block"
    "infobvandevliet-nl"
    "mobile-app-dashboard-custom-fields-json-api"
    "gsheetconnector-easy-digital-downloads"
    "featured-background"
    "wp-rest-api-filter-fields"
    "pixelpost-importer"
    "connect-ez-click-to-call"
    "luxury-hotel-booking-lite"
    "awesome-slider-lite"
    "display-current-wp-version"
    "wield-menu"
    "disabled-newrelic-for-amp"
    "rg-slider"
    "geolocate-comments"
    "today-yesterday-dates"
    "rt-wp-logo-slider"
    "simple-kml-generator"
    "xpd-reduce-image-filesize"
    "cb-responsive-jquery-accordion"
    "paged-product-variations"
    "womp-wp-e-commerce-dashboard-reporter"
    "air-badge"
    "swiftxr-3darvr-viewer"
    "clear-transient-from-dashboard"
    "analog-clock-display-widget"
    "media-upload-admin-widget"
    "live-support"
    "heading-with-description-elementor-widget"
    "last-modified-header"
    "mindvalley-shortcut-framework"
    "children-index-shortcode-plugin"
    "post-revision"
    "wp-bigcommerce"
    "product-list-field-for-contact-form-7"
    "fireblocks"
    "shortcodes-for-gravity-forms"
    "inline-html-css-javascript-minifier"
    "social-sticky"
    "dashboard-user-profile-dup"
    "twitter-list-widget"
    "yarakuzen"
    "reloadly-topup-widget"
    "better-author-metabox"
    "whats-my-ip"
    "only-self-pings"
    "connector-mobilizon"
    "local-indicator"
    "calendapp"
    "thisismyjam-widget"
    "kissherder"
    "testimonial-master"
    "ps-rotator"
    "ppo-call-to-actions"
    "besan-block"
    "monetize-link"
    "beyond-pay-for-woocommerce"
    "elvanto-login-widget"
    "filter-orders-by-status"
    "wp-easy-poll"
    "posting-links-with-images"
    "ip1-contact-form"
    "wp-keyword-monitor"
    "advanced-custom-routes-custom-endpoints-for-wp-rest-api"
    "response-promotion-redeemer"
    "rocksite-sections"
    "syssy"
    "image-cropper"
    "photos-picker"
    "nextgen-font-awesome-on"
    "pagelog"
    "stopsopa-again"
    "maimenu"
    "cosimo"
    "linkedin-oauth"
    "disable-wp-revisions"
    "geometa-acf"
    "customize-kirki-variants"
    "include-file"
    "nepali-date"
    "canadian-gst-calculator"
    "author-change-notifier"
    "digital-media-combined"
    "payaabb-for-woocommerce"
    "hide-category-by-user-role-for-woocommerce"
    "earth-observatory-iotd-widget"
    "sif"
    "show-rss"
    "ltk-remove-branding"
    "reverse-proxy"
    "monocontact-forms"
    "bb-user-list"
    "wp-extend-toolbar"
    "forms-rb"
    "wuxt-headless-wp-api-extensions"
    "megaventory"
    "popular-authors"
    "mixi-check"
    "javibola-custom-theme"
    "menu-item-ancestor"
    "wp-textillate"
    "jamp-notes"
    "mp-user-roles-sync"
    "fx-photo-tag"
    "inject-header-and-footer"
    "ns-tweet"
    "swiftninjapro-wp-login-whitelist-ip"
    "disable-automatic-background-updates"
    "follow-me-sidebar"
    "featured-post-widget-link-to-category"
    "gp-display-child-categories"
    "paquete-mx"
    "elementic"
    "ss-scroll-to-up"
    "php-console-log"
    "edd-ecommerce-analytics"
    "masoffer-promotion"
    "kaelme-url-shortener"
    "channelsale"
    "easy-redirect-by-ip"
    "wp-terapeut-booking"
    "recent-posts-of-specific-category"
    "ss-link-hover-effect"
    "lh-membership-numbers"
    "utilitify"
    "wp-rss-validator"
    "wp-seedbank"
    "tangles-events"
    "shown-connector"
    "auto-assign-product-to-sale-category"
    "faqs"
    "post-display"
    "ratio-thumbnails-size"
    "dashboard-widget-api"
    "mozscape"
    "show-shipping-class-in-product-page"
    "wp-weblink"
    "html-block"
    "wpc-variation-duplicator"
    "countdown-pro-block"
    "protect-my-contents"
    "obox-intercom"
    "affiliateimportereb"
    "snowflakes"
    "reverse-comment-textarea"
    "wp-e-commerce-popular-products"
    "author-profile-plus"
    "kin-visitantes"
    "cta-bar"
    "wps-testimonials"
    "lazy-news-ticker"
    "certishopping-social-reviews-for-woocommerce"
    "salvador-ai-image-generator"
    "custom-frames"
    "news-in-stack-widget"
    "lastfm-playlists"
    "horoscopul-zilnic-ro"
    "contact-form-7-round-robin-lead-distribution"
    "stella-flags"
    "fitvidsjs-fittextjs-and-letteringjs-3-in-1"
    "inventory-history"
    "cyr2lat-slugs"
    "auto-meta-keywords"
    "mypace-remove-comments-feed-link"
    "yml-import-for-woocommerce"
    "widget-labels"
    "colored-titles-for-each-post-type"
    "woocommerce-frotel"
    "begin-ai"
    "curs-valutar-live-bnr"
    "lite-embed-for-youtube"
    "ga-link-tracker"
    "speedy-loan-calculator"
    "formula04-woocommerce-quick-window"
    "publish-approval"
    "woo-taxonomy-report"
    "ehive-objects-tag-cloud"
    "tunesly"
    "powerxl-radyo"
    "afs-analytics-for-woocommerce"
    "uix-usercenter"
    "affiliate-link-tracker"
    "peprodev-ups"
    "membership-lock"
    "super-fast-side-cart-for-woocommerce"
    "ephemera-widget"
    "where-am-i"
    "torod"
    "auto-quote"
    "themediv-social-widget"
    "mimo-colors"
    "volumetric-shipping"
    "easycommentspaginate"
    "custom-feed-for-tiktok"
    "chillpay-payment-gateway"
    "simplify-mortgage-calculation"
    "donation-pro"
    "wp-mail-sending-widget-form"
    "enhanced-admin-links-in-multisite-my-sites-drop-downs"
    "remove-cart-button-and-price"
    "reenio"
    "epf-upload-field"
    "extended-wp-reset"
    "simple-scheduled-posts-widget"
    "sn-extend-authentication"
    "random-tumblr"
    "this-page-needs-files"
    "sharekoube"
    "wp-reddit"
    "ai-image"
    "creative-facebook-like-box"
    "date-translate"
    "combidesk-twinfield"
    "wp-advanced-newsletter"
    "one-click-modal"
    "hide-comments-are-closed-text"
    "improved-image-editor"
    "gc-testimonials-with-recaptcha"
    "dailymotion-videowall-widget"
    "microstock-photo-powersearch-plugin"
    "easy-ga-google-analytics"
    "alpha-price-table-for-elementor"
    "structured-data-test-button"
    "talks-add-on-for-the-events-calendar"
    "my-certificates-wall"
    "bbpress-monster-widget"
    "restrict-wp-upload-type"
    "attachment-viewer"
    "advanced-custom-fields-w4-post-list-bridge"
    "ds-woocommerce-order-email-export"
    "omnibus-for-woocommerce"
    "twentyten-gallery-fix"
    "more-subscribers"
    "7k-image-uploader-meta-box"
    "visio-playlist"
    "ozh-no-duplicate-comments"
    "ns-ajax-products-search"
    "wc-stripe-payment"
    "um-infinite-scroll"
    "wpeform-lite"
    "credit-key-payment-gateway"
    "ect-social-share"
    "add-contributor"
    "woo-product-wishlist"
    "hygglig-checkout"
    "surbma-gdpr-proof-gravity-forms"
    "date-based-taxonomy-archives"
    "force-jquery-in-head"
    "floating-side-tab"
    "woo-to-moodle"
    "outgrow"
    "printess-editor"
    "f6s"
    "music-management-pro"
    "wp-raffle"
    "admin-live-search"
    "feed-tweetifier"
    "wp-sentence"
    "wp-emfluence"
    "5centscdn"
    "smart-accordion"
    "bundesliga-table"
    "tailtarget"
    "edd-fondy-payment"
    "getmovingjquery"
    "woo-product-remover-from-checkout-page"
    "remove-unwanted-p-tag-from-content"
    "bbp-improvements-for-yoast"
    "validate-gravatar"
    "robohash-avatar"
    "colors-for-woocommerce"
    "unsupported-browser-notification"
    "kento-notify"
    "irandargah-payment-gateway-for-give"
    "fd-beaver-charts"
    "acf-template-tags-for-siteorigin"
    "shortcodes-knvb-api"
    "pj-jquery-ui-helper"
    "w2pe-beaverslider"
    "wp-moneybookers-shortcodes"
    "universal-post-counter"
    "laposte-hexasmal"
    "social-news-center"
    "puffar"
    "post-tweets"
    "add-post-last-updated-date-for-wp"
    "popular-products-block"
    "writetext-ai"
    "pootle-cloud"
    "pubble-messenger"
    "cc-devs"
    "wp-local-emoji"
    "wpcm-cricket"
    "qiriman"
    "jeba-cute-slider"
    "wp-tabular-post-slider"
    "advanced-custom-columns"
    "scheduled"
    "silktide"
    "delay-posts-in-rss-feed"
    "all-in-one-news-scroll"
    "remove-html-from-content"
    "schedule-product-delivery-date-for-woocommerce"
    "media-auto-hash-rename"
    "replace-amazon-links-in-feed-with-post-url"
    "title-to-titletag"
    "socialized"
    "post-status-dashboard"
    "filtration"
    "i2csmobile-for-woo"
    "extended-gravatar"
    "cc-post-republisher"
    "custom-menu-driven-prevnext-links"
    "gp-integration"
    "sme-accounting"
    "corona-awareness-popup"
    "pagewhereyouwant"
    "woocommerce-parspeik"
    "worldcup-widget"
    "replace-howdy"
    "minmax-products-quantities"
    "force-secure-site"
    "white-label-wp-login-page"
    "wp-webhooks-manage-taxonomy-terms"
    "post-sync"
    "purge-cache-for-cloudflare"
    "masoomshahid"
    "howdy"
    "admin-private-note-on-users"
    "midwest-logistics"
    "dashboard-admin-email"
    "eliteprospects-player-link"
    "welcome-clock"
    "aruba-fatturazione-elettronica"
    "postpage-import-export-with-custom-fields-taxonomies"
    "webappdesign-gdpr-comments"
    "telegramschanneltowp"
    "backupbank-no-hassel-automated-backups"
    "mnml-footnotes"
    "payt-upsell-for-elementor"
    "perform"
    "hreflang-x-default-tag-for-wpml-inventivo"
    "booking-calendar-and-notification"
    "lm-easy-emoticons"
    "npr-content-distribution-service"
    "fluent-query-logger"
    "wp-configuration-and-status"
    "social-wall-wp"
    "yarns-microsub-server"
    "backend-custom-fields"
    "oc-smart-table-free"
    "woo-awesome-checkout-popup-form"
    "price-matrix-for-woocommerce"
    "splendid-product-viewer"
    "simple-groups"
    "logic-pro"
    "polls-for-contact-form-7"
    "voxpow"
    "slider-for-writers"
    "blogify-posts-menu"
    "baw-force-new-password"
    "dial-voyants"
    "nfcbc-seo-light"
    "gateway-payougo-checkout"
    "wp-cron-pixie"
    "raise-prices-with-sales-for-woocommerce"
    "hide-thumbnails"
    "find-a-covid-testing-center"
    "wp-panoramio"
    "the-joshua-project-daily-unreached-people-widget"
    "greenshift-smart-code-ai"
    "sensorpress-uptime-monitoring"
    "ads-on-content-amp-pages"
    "smart-phone-addon-for-ninja-forms"
    "directo-pago-payments-for-woocommerce"
    "saint-du-jour-widget"
    "credit-card-payments-for-woocommerce-with-cybersource"
    "visit-site-settings"
    "simple-cleanup"
    "ketno-lazy-page-loader"
    "beautiful-social-widget"
    "attached-images-title-editor"
    "wp-vero"
    "master-password"
    "ldw-mobile-contact-optimizer"
    "chrome-font-rendering-fix"
    "1-source-cleaner"
    "md-toc-generator"
    "ad-free-google-safe-search-for-schools"
    "convertbar-auto-embed"
    "syntaxhighlighter-evolved-sass-brush"
    "bitcartcc-for-woocommerce"
    "blogroll-media-library-image"
    "reposition-thumnails"
    "wpb-form-popup"
    "ajax-product-search"
    "wp-master-widget"
    "podamibe-twitter-feed-widget"
    "wp-g2a-goldmine-cd-keys-affiliate"
    "naked-urls-to-live-links"
    "cool-popular-post"
    "rating-block"
    "sublanguage-switcher-widget"
    "block-spam-comments"
    "golf-handicap-calculator"
    "optin-xpert"
    "color-schemes-roulette"
    "captcha-in-thai-2nd"
    "wtg-tasks-manager"
    "ismobile"
    "wc-zoho-inventory"
    "gravity-forms-capsulecrm-add-on"
    "oc-image-slider"
    "real-ip-and-geo-for-cloudflare"
    "podcast-box"
    "wp-bootscraper"
    "share-on-pixelfed"
    "zwm-zeumic-work-management"
    "telegram-inliner"
    "socwidgit"
    "claim-review-schema"
    "magento-user-compatibility"
    "clicksports-maps"
    "automate-dropshipping-for-b2bdropshipperwwtech"
    "anti-ie6-army"
    "youtube-play-icon"
    "weibo2wp"
    "tua-forma"
    "masterbip-for-elementor"
    "gallagher-website-design"
    "screening-questions-for-wp-job-manager"
    "hopewiser-address-lookup"
    "mowplayer"
    "hulkshare-short-code"
    "lh-tools"
    "acloginwidget"
    "output-optimizer"
    "xml-for-o-yandex"
    "users-to-crm-contacts"
    "wp-article-order"
    "textarea-words-characters-limit"
    "admin-tag-ui"
    "cost-calculator-for-wpforms"
    "hello24-order-on-chat-abandoned-cart-recovery-marketing-automation"
    "infusionsoft-exit-optin"
    "wp-single-page"
    "wc-nastavenia-skcz"
    "worldtides-widget"
    "comment-star-rating"
    "zen-social-sticky"
    "woo-beecloud-integration"
    "gallery-plugin-xmlrpc-interface"
    "video-thumbnail-image-extractor"
    "irisnet-api"
    "0-delay-late-caching-for-feeds"
    "paykeeper"
    "unfc-normalize"
    "shortcodehub"
    "mathematica-toolbox"
    "snazzy-cacheable-facebook-feed"
    "categorize-your-wishlist-for-woocomerceposts-custom-post-types"
    "electroneum-instant-payments-for-woocommerce"
    "awstats-xtended-info"
    "bonzer-custom-fields"
    "build-private-store-for-woocommerce"
    "woo-minimum-order-purchase"
    "simple-indeed-jobroll-widget"
    "searchcloak"
    "uyghur-uly-permalinks"
    "swipejs"
    "digital-blasphemy-widget"
    "qlicknpay"
    "easy-lightbox-2-automated"
    "testimonial-post-type"
    "wp-polymer"
    "dealfront"
    "utms-carry-pages"
    "mxp-sepa-qr-code-addon-for-woocommerce"
    "js-image-zoom-by-csomor"
    "recent-edits"
    "wp-admin-bar-hiddener-tools-plugin"
    "bp-devolved-authority"
    "tinymce-extended-config"
    "ibar"
    "easy-multilevel-nav-menu"
    "prioritize-hooks"
    "wp-query-route-to-rest-api"
    "real-cookie-banner-color-schemes"
    "binaryimagemagick"
    "easy-digital-downloads-clear-cart"
    "job-manager-feed-scroller"
    "livechat-for-easy-digital-downloads"
    "rektic-wp"
    "word-2-cash"
    "unsortable-meta-box"
    "better-wp-admin-bar"
    "qlikview-syntax-highlighter"
    "wp-job-pro"
    "wp-comment-notes"
    "adr-promotion-recommendations"
    "disable-global-style"
    "alttextmagic"
    "woo-chinesize-by-wenprise"
    "better-editor"
    "live-space-sync"
    "wp-dark-emoticons-comment-smiley"
    "pdf-password-protect"
    "payout-payment-gateway"
    "thesis-restore-points"
    "mm-linkedin-connect"
    "simple-disable-xml-rpc"
    "save-posts-with-cmds"
)

# Define user agents with weights
declare -A USER_AGENTS
USER_AGENTS=(
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"]=5
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"]=7
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"]=6
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36 Edg/91.0.864.54"]=5
    ["Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 OPR/77.0.4054.277"]=3
    ["Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (iPad; CPU OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Vivaldi/4.0"]=1
    ["Mozilla/5.0 (Android 11; Mobile; rv:68.0) Gecko/68.0 Firefox/88.0"]=1
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"]=15
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/534.36"]=12
)

OPENED_PLUGINS_FILE="${WORDPRESS_WORKDIR}/opened_plugins.txt"
CLOSED_PLUGINS_FILE="${WORDPRESS_WORKDIR}/closed_plugins.txt"
LAST_VERSION_FILE="${WORDPRESS_WORKDIR}/last_versions.txt"
PARALLEL_JOBS=1

DOWNLOAD_ALL_PLUGINS='n'
LIST_ONLY='n'
ALL_PLUGINS_FILE="${WORDPRESS_WORKDIR}/wp-plugin-svn-list.txt"

DELAY_DOWNLOADS='n'
DELAY_DURATION=5

FORCE_UPDATE='n'
CACHE_ONLY='n'

mkdir -p "$WORDPRESS_WORKDIR" "$MIRROR_DIR" "$LOGS_DIR"
rm -f "$OPENED_PLUGINS_FILE"
touch "$OPENED_PLUGINS_FILE"
DEBUG_MODE=0

while getopts "p:dalD:t:fc" opt; do
    case ${opt} in
        p ) PARALLEL_JOBS=$OPTARG ;;
        d ) DEBUG_MODE=1 ;;
        a ) DOWNLOAD_ALL_PLUGINS='y' ;;
        l ) LIST_ONLY='y' ;;
        D ) DELAY_DOWNLOADS=$OPTARG ;;
        t ) DELAY_DURATION=$OPTARG ;;
        f ) FORCE_UPDATE='y' ;;
        c ) CACHE_ONLY='y' ;;    # New option for cache-only
        \? ) echo "Usage: $0 [-p PARALLEL_JOBS] [-d] [-a] [-l] [-D DELAY_DOWNLOADS] [-t DELAY_DURATION] [-f] [-c]" 1>&2; exit 1 ;;
    esac
done

debug_log() {
    if [ "$DEBUG_MODE" -eq 1 ]; then
        echo "[DEBUG] $1" >&2
    fi
}

get_random_user_agent() {
    echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
}

get_latest_version_and_download_link() {
    local plugin=$1
    debug_log "Checking latest version and download link for $plugin"
    
    local api_url="https://api.wordpress.org/plugins/info/1.0/${plugin}.json"
    local user_agent=$(get_random_user_agent)
    local api_response=$(curl -s -H "User-Agent: $user_agent" "$api_url")
    
    if echo "$api_response" | jq -e '.error' >/dev/null; then
        local error_message=$(echo "$api_response" | jq -r '.error')
        if [ "$error_message" = "closed" ]; then
            echo "closed"
            return 2
        else
        echo "Error: $error_message for plugin $plugin" >&2
        return 1
        fi
    fi
    
    local version=$(echo "$api_response" | jq -r '.version // empty')
    local download_link=$(echo "$api_response" | jq -r '.download_link // empty')
    
    if [ -n "$version" ] && [ -n "$download_link" ]; then
        echo "$version $download_link"
        return 0
    else
        echo "Error: Cannot fetch version or download link for $plugin" >&2
        return 1
    fi
}

download_plugin() {
    local plugin=$1
    local version=$2
    local api_download_link=$3
    local output_file="${MIRROR_DIR}/${plugin}.${version}.zip"
    local header_file="${LOGS_DIR}/${plugin}.${version}.headers"
    local constructed_download_link="${DOWNLOAD_BASE_URL}/${plugin}.${version}.zip"
    local download_link

    if [ "$DEBUG_MODE" -eq 1 ]; then
        debug_log "API-provided download link for $plugin: $api_download_link"
        debug_log "Constructed download link for $plugin: $constructed_download_link"
    fi

    if [ "$DOWNLOAD_LINK_API" == 'y' ] && [ -n "$api_download_link" ]; then
        download_link="$api_download_link"
        debug_log "Using API-provided download link for $plugin: $download_link"
    else
        download_link="$constructed_download_link"
        debug_log "Using constructed download link for $plugin: $download_link"
    fi

    debug_log "Downloading $plugin version $version through Cloudflare Worker"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)
    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o /dev/null "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    else
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o "$output_file" "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    fi

    if [ $? -eq 0 ]; then
        if [ "$CACHE_ONLY" == 'y' ]; then
            debug_log "Plugin $plugin version $version cached successfully."
            return 0
        fi

        local file_size=$(stat -c%s "$output_file")
        if [ "$file_size" -lt 1000 ]; then
            echo "Error: Downloaded file for $plugin is too small (${file_size} bytes). Possible download issue." >&2
            return 1
        fi

        local source=$(grep -i "X-Source:" "$header_file" | cut -d' ' -f2 | tr -d '\r')
        if [ "$source" == "R2" ]; then
            debug_log "Successfully downloaded $plugin version $version from R2 storage"
        elif [ "$source" == "WordPress" ]; then
            debug_log "Successfully downloaded $plugin version $version from WordPress"
            debug_log "R2 bucket saving for plugin zip occurred"
        else
            debug_log "Skipped download for $plugin $version zip (already exists locally)"
        fi

        return 0
    else
        echo "Error: Failed to download $plugin version $version" >&2
        return 1
    fi
}

save_plugin_info() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.json"

    debug_log "Saving plugin json metadata for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying metadata download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    if [ "$CACHE_ONLY" == 'y' ]; then
        # When in cache-only mode, output to /dev/null
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin metadata for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache json metadata for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            if [ "$source" = "R2" ]; then
                debug_log "json metadata for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "json metadata for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin json occurred"
            else
                debug_log "json metadata for $plugin version $version saved (json metadata file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save json metadata for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

fetch_and_save_checksums() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.checksums.json"

    debug_log "Fetching and saving checksums for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying checksums download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    debug_log "Sending request to Worker for checksums: CF_WORKER_URL?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"

    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin checksums for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache checksums for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        debug_log "Received response with status code: $status_code"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            debug_log "Response source: $source"
            if [ "$source" = "R2" ]; then
                debug_log "Checksums for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "Checksums for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin checksums occurred"
            else
                debug_log "Checksums for $plugin version $version saved (checksums file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save checksums for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

process_plugin() {
    local plugin=$1

    # Check if the plugin is already known to be closed
    if grep -q "^$plugin$" "$CLOSED_PLUGINS_FILE" 2>/dev/null; then
        echo "Plugin $plugin is known to be closed. Skipping."
        return 0
    fi

    echo "Processing plugin: $plugin"

    VERSION_AND_LINK=$(get_latest_version_and_download_link "$plugin")
    local version_check_status=$?
    
    if [ $version_check_status -eq 1 ]; then
        echo "Skipping $plugin due to version fetch error."
        return 1
    elif [ $version_check_status -eq 2 ]; then
        echo "Plugin $plugin is closed. Skipping download and processing."
        echo "$plugin" >> "$CLOSED_PLUGINS_FILE"
        if save_plugin_info "$plugin" "closed"; then
            debug_log "Successfully saved json metadata for closed plugin $plugin."
        else
            debug_log "Failed to save json metadata for closed plugin $plugin."
        fi
        return 0
    fi
    
    LATEST_VERSION=$(echo "$VERSION_AND_LINK" | cut -d' ' -f1)
    API_DOWNLOAD_LINK=$(echo "$VERSION_AND_LINK" | cut -d' ' -f2-)

    debug_log "Latest version for $plugin: $LATEST_VERSION"
    debug_log "API download link for $plugin: $API_DOWNLOAD_LINK"

    STORED_VERSION=$(grep "^$plugin" "$LAST_VERSION_FILE" | awk '{print $2}')
    debug_log "Stored version for $plugin: $STORED_VERSION"

    if [ "$CACHE_ONLY" != 'y' ] && [ "$LATEST_VERSION" == "$STORED_VERSION" ] && [ -f "${MIRROR_DIR}/${plugin}.${LATEST_VERSION}.zip" ]; then
        echo "$plugin is up-to-date and exists in mirror directory. Skipping download..."
    else
        start_time=$(date +%s.%N)

        if download_plugin "$plugin" "$LATEST_VERSION" "$API_DOWNLOAD_LINK"; then
            if [ "$CACHE_ONLY" != 'y' ]; then
                sed -i "/^$plugin/d" "$LAST_VERSION_FILE"
                echo "$plugin $LATEST_VERSION" >> "$LAST_VERSION_FILE"
            fi
            echo "Successfully processed $plugin."
        else
            echo "Error: Failed to process $plugin." >&2
        fi

        end_time=$(date +%s.%N)
        duration=$(echo "$end_time - $start_time" | bc)
        printf "Time taken for %s: %.4f seconds\n" "$plugin" "$duration"
    fi

    if save_plugin_info "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully saved json metadata for $plugin."
    else
        debug_log "Failed to save json metadata for $plugin."
    fi

    if fetch_and_save_checksums "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully fetched and saved checksums for $plugin."
    else
        debug_log "Failed to fetch and save checksums for $plugin."
    fi

    if [ $version_check_status -eq 0 ]; then
        echo "$plugin" >> "$OPENED_PLUGINS_FILE"
    fi
}

populate_all_plugins() {
    if [ ! -f "$ALL_PLUGINS_FILE" ] || [ "$LIST_ONLY" == 'y' ]; then
        echo "Fetching list of all WordPress plugins..."
        svn list https://plugins.svn.wordpress.org/ | sed 's/\/$//g' > "$ALL_PLUGINS_FILE"
        plugin_count=$(wc -l < "$ALL_PLUGINS_FILE")
        echo "Plugin list (${plugin_count}) saved to $ALL_PLUGINS_FILE"
    fi
    
    if [ "$LIST_ONLY" == 'n' ]; then
        ALL_PLUGINS=()
        while IFS= read -r line; do
            ALL_PLUGINS+=("$line")
        done < "$ALL_PLUGINS_FILE"
        echo "Loaded ${#ALL_PLUGINS[@]} plugins."
    fi
}

if [ "$LIST_ONLY" == 'y' ]; then
    populate_all_plugins
    echo "Plugin list created. Exiting without downloading."
    exit 0
fi

if [ "$DOWNLOAD_ALL_PLUGINS" == 'y' ]; then
    populate_all_plugins
    COMBINED_PLUGINS=("${ALL_PLUGINS[@]}")
else
    if [ ! -d "$PLUGIN_DIR" ]; then
        echo "Warning: Plugin directory $PLUGIN_DIR does not exist or is invalid."
        PLUGIN_LIST=()
    else
        PLUGIN_LIST=($(ls -d "$PLUGIN_DIR"/*/ 2>/dev/null | xargs -n 1 basename))

        if [ ${#PLUGIN_LIST[@]} -eq 0 ]; then
            echo "No plugins found in $PLUGIN_DIR."
        fi
    fi

    COMBINED_PLUGINS=(${PLUGIN_LIST[@]} ${ADDITIONAL_PLUGINS[@]})
    COMBINED_PLUGINS=($(echo "${COMBINED_PLUGINS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
fi

if [ ${#COMBINED_PLUGINS[@]} -eq 0 ]; then
    echo "No plugins to download. Exiting."
    exit 0
fi

mkdir -p "$MIRROR_DIR"
touch "$LAST_VERSION_FILE"

if [ "$PARALLEL_JOBS" -gt 1 ]; then
    echo "Running in parallel with $PARALLEL_JOBS jobs..."
    # First, export all variables including USER_AGENTS
    export DOWNLOAD_BASE_URL MIRROR_DIR LAST_VERSION_FILE DEBUG_MODE DOWNLOAD_LINK_API LOGS_DIR ALL_PLUGINS_FILE DOWNLOAD_ALL_PLUGINS LIST_ONLY CF_WORKER_URL DELAY_DOWNLOADS DELAY_DURATION FORCE_UPDATE CACHE_ONLY USER_AGENTS

    # Then, export the functions
    export -f process_plugin get_latest_version_and_download_link download_plugin debug_log populate_all_plugins save_plugin_info get_random_user_agent fetch_and_save_checksums
    printf "%s\n" "${COMBINED_PLUGINS[@]}" | xargs -P $PARALLEL_JOBS -I {} bash -c 'process_plugin "$@"' _ {}
else
    for plugin in "${COMBINED_PLUGINS[@]}"; do
        process_plugin "$plugin"
    done
fi

if [ -f "$CLOSED_PLUGINS_FILE" ]; then
    echo
    echo "Closed Plugin List:"
    cat "$CLOSED_PLUGINS_FILE" | sort | uniq || true
    echo
    echo "Total closed plugins: $(wc -l < "$CLOSED_PLUGINS_FILE")"
    echo
else
    echo
    echo "No closed plugins found."
    echo
fi
echo "Plugin download process completed."
