#!/bin/bash

# Base directory (script location)
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Configurable directories
WORDPRESS_WORKDIR="${WORDPRESS_WORKDIR:-$BASE_DIR/wordpress-plugins}"
PLUGIN_DIR="${PLUGIN_DIR:-$BASE_DIR/wp-content/plugins}"
MIRROR_DIR="${MIRROR_DIR:-$BASE_DIR/mirror}"
LOGS_DIR="${LOGS_DIR:-$BASE_DIR/plugin-logs}"

# Check for CF_WORKER_URL environment variable
if [ -z "$CF_WORKER_URL" ]; then
    echo "Error: CF_WORKER_URL environment variable is not set." >&2
    exit 1
fi

DOWNLOAD_BASE_URL="https://downloads.wordpress.org/plugin"

# Other variables
DOWNLOAD_LINK_API='y'

ADDITIONAL_PLUGINS=(
    "bbt-pinterest-optin"
    "smartemailing"
    "accept-bitcoin"
    "shopping-feed"
    "kento-latest-tabs"
    "unc-gallery"
    "dx-contribute"
    "cm-context-related-product-recommendations"
    "taxonomic-seo-permalinks"
    "40nuggets"
    "order-attachments-for-woocommerce"
    "sliced-invoices-contact-form-7"
    "best-seo"
    "wpml-translation-check"
    "devllo-events"
    "at-a-glance"
    "checkout-address-suggestion-and-autocomplete-for-woocommerce"
    "bukza"
    "fusion-extension-blog"
    "styles-twentyfifteen"
    "aco-wishlist-for-woocommerce"
    "page-in-page"
    "authors-posts-widget"
    "woocommerce-smart-send-australian-shipping"
    "twitterpost"
    "decoupled-preview"
    "remove-wp-version-info"
    "multiple-domains-with-analytics"
    "simple-bmi-calculator"
    "html-validation"
    "linkvertise-script-api"
    "textoptimizer"
    "disable-comments-on-attachments"
    "wpify-mapy-cz"
    "disable-user-registration-notification-emails"
    "deny-all-firewall"
    "client-carousel"
    "smart-wp-login"
    "mpcx-slider"
    "word-filter-plus"
    "dot-php-pages"
    "geniewords"
    "last-posts-category-and-post-types"
    "shortcode-lister"
    "lazyload-woocommerce"
    "expandable-menus"
    "admin-cleanup"
    "xylus-toolkit"
    "product-questions-answers-for-woocommerce"
    "bainternet-user-ranks"
    "socicon"
    "newscodes-news-magazine-and-blog-elements"
    "xml-import"
    "template-list-metabox-by-010pixel"
    "sync-opml-to-blogroll"
    "wc-disable-sales"
    "import-xml-csv-listings-to-listable-theme"
    "gravity-forms-update-post"
    "nav-menu-item-duplicate"
    "ns-product-rating-for-woocommerce"
    "bookmark-export"
    "atomic-docs-lockdown"
    "damarfm-player"
    "tayori"
    "quadmenu-generatepress"
    "football-standings"
    "embed-webmap"
    "templatic-badge"
    "infusionsoft-sdk"
    "social-bookmarking-jp"
    "easy-ad-picker"
    "elegant-category-posts"
    "stl-viewer"
    "post-and-page-reactions"
    "add-or-remove-www"
    "enforce-strong-password"
    "solid-dynamics"
    "flower-delivery-by-florist-one"
    "mycred-for-wp-postviews"
    "dynamic-copyright-year-and-shortcode"
    "remove-wp-meta-tags"
    "firedrum-email-marketing"
    "simple-tag-manager"
    "wp-responsive-tabs"
    "pluglab"
    "igsyntax-hiliter"
    "twenty-eleven-showcase-slider"
    "wp-touch-stylesheet-addon"
    "wp-add-active-class-to-menu-item"
    "awsa-shipping"
    "product-image-watermark-for-woo"
    "amazolinkenator"
    "comment-approved-notifier-extended"
    "magic-widgets"
    "cookie-wow-banner"
    "admin-show-sticky"
    "cloud-blocks"
    "fc-retirement-age-calculator"
    "dashboard-lite"
    "duplicate-term"
    "composite-products-conditional-images-for-woocommerce"
    "social-media-manager"
    "admin-page-notes"
    "caspio-deploy2"
    "woo-thumbnails-slider"
    "delicious-cached"
    "woo-cryptobillings-gateway"
    "highest-sell-products-woocommerce"
    "cashvault-woocommerce"
    "birthday-widget-for-buddypress"
    "contact-details"
    "cloud-search"
    "indian-rupee-symbol-for-woocommerce"
    "custom-post-archives"
    "redirect-404-to-home-page-custom-url"
    "wpshore-breadcrumb"
    "hide-member-visibility-for-buddypress"
    "pe-panels"
    "time-machine"
    "cryptocurrency-coins-list-price-list-ticker-icos"
    "mdc-target-blank"
    "wowhead-tooltips"
    "lgpd-compliant-cookie-banner"
    "arvancloud-object-storage"
    "wp-latest-video-widget"
    "get-in-touch-plugin"
    "shift-short-wp-admin-theme"
    "review-widgets-for-foursquare"
    "auto-form-fill"
    "acf-multiple-taxonomy"
    "c3-random-quotes"
    "update-message"
    "customize-wp-admin"
    "filtr8-magazine"
    "wp-applaud"
    "dwl-preloader"
    "scout-tools"
    "still-be-combine-social-photos"
    "kcite"
    "wp-nicedit"
    "bbpress-notification"
    "hierarchical-link-categories"
    "clone-page-tree"
    "a2z-alphabetical-archive-links"
    "social-locker-content"
    "advanced-custom-fields-widget-relationship-field-add-on"
    "ax-scrollto-top"
    "campay-api"
    "noindex-attachment-pages"
    "gochat"
    "delivery-countdown-timer"
    "mdr-webmaster-tools"
    "advance-cash-on-delivery-for-woocommerce"
    "checkbox"
    "bunnycdnbunnyapi"
    "media-list"
    "arcadeready"
    "force-user-login-modified"
    "wp-admin-audit"
    "slidepost"
    "jobs-portal"
    "image-credits-nofollow"
    "proper-pagination"
    "360panoembed"
    "map-cap"
    "easy-update-urls"
    "norman-advanced-archive-widget"
    "wsify-widget"
    "shutter-reloaded-plus"
    "dokan-order-approval"
    "another-soundcloud-quicktag"
    "contentking"
    "betta-boxes-cms"
    "review-widgets-for-szallas-hu"
    "quick-edit-yoastseo"
    "simple-taxonomy-refreshed"
    "woocommerce-product-css-tags"
    "smartwaiver-waiver-widget"
    "feedbucket"
    "sidebar-content-clone"
    "wp-google-charts"
    "pagerank-tools"
    "dashboard-pages"
    "advanced-posts-widget"
    "wp-simple-sitemap"
    "luckywp-glossary"
    "background-particle-js"
    "wp-sticky-side-buttons"
    "connections-business-directory-education-levels"
    "html-mode-locker"
    "octolize-australia-post-shipping"
    "webman-bulk-delete"
    "wp-tactical-popup"
    "wp-responsive-jquery-slider"
    "vriks-video-embedding"
    "wp-rest-api-sidebars"
    "bbpress-admin"
    "wp2epub"
    "upcasted-s3-offload"
    "girocheckout"
    "mp3-link-player"
    "bu-section-editing"
    "add-subpage-here"
    "meteoart"
    "discontinued-product-stock-status-woocommerce"
    "woo-quick-order-table-view"
    "update-stat"
    "sws-hotjar"
    "download-external-images-in-posts"
    "ddirections"
    "view-my-posts-alone"
    "wp-rekogni"
    "list-mixcloud"
    "subtitle-360"
    "nivo-slider-simplified"
    "wp-visited-countries"
    "caag-forms"
    "wp-mailer"
    "wp-e-commerce-country-cart-amount-shipping-module"
    "mailcamp"
    "sympose"
    "bsf-docs"
    "easy-eu-cookie-law"
    "dfoxw-wechatgrab"
    "ui-slider-filter-by-price"
    "wp-headless"
    "approval-workflow"
    "process-site-map"
    "disable-events-and-news-dashboard-widget"
    "wbcom-designs-buddypress-ads"
    "cream6-admin-theme"
    "bootstrap-collapse"
    "a-lead-capture-contact-form-and-tab-button-by-awebvoicecom"
    "estonian-banklinks-for-woocommerce"
    "simple-author-bio"
    "emoji-autocomplete-gutenberg"
    "dd-roles"
    "wp-gif-player-play-and-pause"
    "report-comments"
    "gift-upon-purchase-for-woocommerce"
    "tennis-court-bookings"
    "get-latest-post"
    "advanced-auto-update-disable-tlc"
    "custom-permalink-editor"
    "wp-login-attempt-log"
    "flexslider-for-native-gallery"
    "starred-review"
    "yayswatches"
    "secure-captcha"
    "wayne-audio-player"
    "webseo-admin-theme"
    "xml-multilanguage-sitemap-generator"
    "wp-mail-debugger"
    "universal-google-analytics"
    "night-mode-and-font-size-kit"
    "gamipress-emails-by-type"
    "all-in-one-visual-composer-addons"
    "db-robotstxt"
    "ninja-job-board"
    "wp-flipkart-importer"
    "subme"
    "responsive-sidebar"
    "hide-admin-icons"
    "responsive-social-sharing-icons"
    "cas-maestro"
    "ect-product-carousel"
    "sugoi-tag-inserter"
    "acf-date-time-picker"
    "mg-parallax-slider"
    "wp-visual-sitemap"
    "click-pledge-connect"
    "wp-open-votomat"
    "my-right-horse"
    "onionbuzz-viral-quiz"
    "jcc-payment-gateway-for-wc"
    "wp-api-yoast-meta"
    "crawl-optimization"
    "list-pages-at-depth"
    "serial-number-for-contact-form-7"
    "wp-bootstrap-tabs"
    "wp-plus"
    "columns-alignment-fix-for-elementor"
    "plugin-jetradar-cheap-flights"
    "live-summary-for-gravity-forms"
    "amp-contact-form-7"
    "naver-analytics"
    "twitter-hash-tag-widget"
    "flshow-manager"
    "cambia-utente"
    "pryc-woocommerce-product-search-in-any-search"
    "clean-html"
    "custom-text-on-add-to-cart-button-for-woocommerce"
    "web-to-printq"
    "javascript-qrcode-generator"
    "ahmeti-wp-timeline"
    "media-library-filter"
    "wp-github"
    "headway-views"
    "schema-breadcrumbs"
    "admin-notes"
    "xt-corporate-toolkit"
    "jobify"
    "menubar-color-changer"
    "marketplace-items"
    "pixel-sitemap"
    "grants-for-nonprofits-widget"
    "say-it"
    "cats-job-listings"
    "icafe-library"
    "slider-for-elementor"
    "minecraftserverstatus"
    "chess-game-viewer-control-panel"
    "wiki-page-links"
    "just1stepahead-for-woocommerce"
    "wootrello"
    "podcast-channels"
    "wp-content-scheduler-with-range"
    "tweeter-a-twitter-widget"
    "wp-documentor"
    "payjustnow-for-woocommerce"
    "wpcashlinks-lite"
    "edd-purchase-gravatars"
    "multiple-external-product-urls-for-woocommerce"
    "atr-server-status"
    "include-mastodon-feed"
    "order-sync-with-google-sheets-for-woocommerce"
    "woocommerce-coupon-schedule"
    "woocomm-2co-dynamic-payment-gateway"
    "comments-on-feed"
    "wc-mtn-momo-payment-gateway"
    "photostream-sync"
    "hackrepair-plugin-archiver"
    "easy-donation"
    "orchestrated-blocks"
    "acronyms-2"
    "3dvieweronline-wp"
    "dpabottomofpostpage"
    "bulk-download-for-gravity-forms"
    "gas-injector"
    "buddy-progress-bar"
    "poll-lite"
    "evergreen-content-poster"
    "flamix-bitrix24-and-woo-integrations"
    "sd-questions-and-answers"
    "login-alert"
    "bea-media-analytics"
    "post-read-limited-by-category"
    "back-and-forward-button"
    "falconiform-youtube-widget"
    "ozh-tweet-archiver"
    "massive-addons-for-elementor"
    "googleapis-to-useso"
    "dashboard-quick-link-widget"
    "digital-lottery"
    "random-post-link"
    "quick-bulk-taxonomy-term-creator"
    "majestic-seo-dashboard-graphs"
    "bulk-page-generator"
    "ns-smooth-scroll-back-to-top"
    "sierra-addons"
    "wp-shredderchess"
    "insert-adsense-auto-ads"
    "easy-liveblogs"
    "text-captcha"
    "colorize-admin"
    "shorthand-connect"
    "aaa-option-optimizer"
    "humansnotbots"
    "utopia-under-construction"
    "wp-projects-portfolio"
    "widgets-for-aliexpress-reviews"
    "currency-switcher-for-woocommerce"
    "anyway-feedback"
    "adv-geoip-redirect"
    "speedy-econt-shipping"
    "navidad-indianwebs"
    "wordpress-totals"
    "mightyshare"
    "move-admin-menu-items"
    "datawrapper-oembed"
    "single-post-widget"
    "bebop"
    "wpex-replace"
    "wp-chinese-excerpt"
    "xhanch-my-advanced-settings"
    "post-order-by-category"
    "post-ender"
    "wp-file-search"
    "fny-social-media-share-buttons"
    "ycyclista"
    "wp-screenshot"
    "gazchaps-woocommerce-getaddress-io"
    "smtp-sendgrid"
    "arabic-woocommerce-middle-east-currencies"
    "simply-related-posts"
    "easy-excerpt"
    "redirect-to-url"
    "postcode-based-order-restriction"
    "resize-post-thumbnails"
    "last-modified"
    "bp-edit-user-profiles"
    "toko-ibest-bank-indonesia-for-woocommerce"
    "wp-sanitize"
    "caldavlist"
    "counter-widget"
    "comment-blacklist-manager"
    "events-as-posts"
    "shift8-full-navigation"
    "gutena-lightbox"
    "hide-update-reminder-message"
    "time-tables"
    "bargain"
    "add-swf-support-for-media-uploader-inventivo"
    "ultimate-back-to-top"
    "wpsyncsheets-woocommerce"
    "super-simple-custom-css"
    "alley-business-toolkit"
    "custom-coming-soon"
    "acf-multi-dates-picker"
    "customize-object-selector"
    "shieldfy"
    "frisbo-woocommerce"
    "seo-friendly-table-of-contents"
    "add-to-home-screen"
    "satoshipay"
    "gforms-addon-for-country-and-state-selection"
    "hk-idram-payment-gateway"
    "guardian-news-headlines"
    "connections-business-directory-face-detect"
    "printus-cloud-printing-for-woocommerce"
    "wp-firebase-push-notification"
    "zencart-and-wordpress-user-integration"
    "codemirror-for-codeeditor"
    "bp-bulk-delete"
    "parrotposter"
    "appmax-woocommerce"
    "brozzme-multiple-admin-emails"
    "inax-ir"
    "woo-product-attribute-tab"
    "live-css-preview"
    "reviewexchanger-demo-importer"
    "bang-tinh-lai-suat"
    "thegdprlaw"
    "sportsmanager"
    "label-grid-tools"
    "os-datahub-maps"
    "cothemes-shortcode"
    "vikwidgetsloader"
    "contextual-adminbar-color"
    "getanewsletter"
    "custom-tag-cloud"
    "payment-gateways-by-customer-location-for-woocommerce"
    "formilla-chat-and-marketing"
    "pg-context-sidebar"
    "ab-background-slideshow"
    "clear-sucuri-cache"
    "download-list-block-with-icons"
    "dashboard-builder"
    "ranking-and-competitor-tracking"
    "sign-me-up"
    "wp-conditional-content"
    "learn-manager"
    "gtpay-woo-payment-gateway"
    "yaexam"
    "wp-super-heatmap"
    "easy-popup-announcement"
    "ssi-sumilux"
    "ravatar"
    "lana-widgets"
    "richpanel-for-woocommerce"
    "post-auto-expire-control"
    "attendance-list"
    "posts-social-shares-count"
    "eps-super-search"
    "shelf-planner"
    "custom-mobile-contact-buttons"
    "accessibility-plus"
    "edd-terms-per-product"
    "counter-ecl"
    "woo-benchmark-email"
    "seo-enforcer"
    "bunny-tags"
    "manager-for-icomoon"
    "my-html-post-widgets"
    "inline-tweets"
    "automatically-set-1st-image-as-featured"
    "melapress-login-security"
    "google-org-chart"
    "wp-church-donation"
    "wp-paypal-shortcodes"
    "usermap"
    "multisite-latest-posts-widget"
    "wp-avatar"
    "oik-read-more"
    "host-meta"
    "zmt-fancybox"
    "elegant-visitor-counter"
    "dashboard-directory-size"
    "edd-purchase-rewards"
    "breadcrumb-navigation-widget"
    "photo-video-store"
    "affinipay-payment-gateway"
    "corona-zahlen-deutschland-cng"
    "wpematico-custom-hooks"
    "video-destacado"
    "scroll-styler"
    "powerpress-multisite"
    "buddypress-ads"
    "qr-code-generator-4-all"
    "korea-for-woocommerce"
    "remove-fields"
    "b2bking-private-store-for-woocommerce"
    "responsive-sliding-menu"
    "openhours"
    "font-awesome-the-easy-way"
    "ribbon-maker"
    "reply-w-comment-preview"
    "ownerrez"
    "ds-site-message"
    "dynamic-post"
    "simple-login-redirect"
    "checklist-in-post"
    "mpress-custom-feed-excerpts"
    "gosign-advanced-separator-block"
    "list-posts-by-categories"
    "pay-with-contact-form-7"
    "igit-new-twitter-tweet-share-button-with-counter"
    "game-server-tracker"
    "mu-widgets"
    "wp-clean-admin-theme"
    "coil-web-monetization"
    "buddypress-notifications-manager"
    "formello"
    "simple-category-icons"
    "ajax-post-filter"
    "insticator"
    "wp-insurance"
    "show-environment-in-admin-bar"
    "plugin-logic"
    "lips"
    "suppliers-manager-for-woocommerce"
    "russian-texts-proofreader-glvrd"
    "taobaoke"
    "wc-software-license-manager"
    "authorizenet-simple-donations"
    "aimtell-web-push-notifications"
    "nasim-persian-maker"
    "woo-ups-pickup"
    "flx-dashboard-groups"
    "media-images-widget"
    "wordpress-quick-save"
    "wp-editor-comments-plus"
    "omnileads-scripts-and-tags-manager"
    "tip-jar-wp"
    "event-agent"
    "moneytigo"
    "limit-orders"
    "buddyforms-review"
    "go-dark"
    "splash-header"
    "todo-plugin"
    "wp-search-live"
    "elex-woo-dhl-express-shipping"
    "mint-sliders"
    "gcal-event-addon-woocommerce-bookings"
    "crm-erp-business-solution"
    "wp-ttfgen"
    "organizational-message-notifier"
    "simple-security"
    "theme-blvd-featured-videos"
    "reportattacks"
    "sidebar-menu-items"
    "bbpress-no-captcha-recaptcha"
    "mailarchiver"
    "integrator3"
    "colorize-mobile-browser-bar"
    "social-media-links-for-ultimate-member"
    "responsive-accordion-slider"
    "thinker-sidebar-shortcode"
    "hfd-epost-integration"
    "giga-messenger-bots"
    "wp-tidy-tinymce"
    "bg-orthodox-calendar"
    "mujib-borsho-bangla"
    "visual-hook-guide-for-kadence"
    "text-case-converter"
    "product-category"
    "wp-world-travel"
    "gtwregister"
    "wp-restaurant-booking"
    "daily-fitness-tips"
    "subtome"
    "login-customizer-plus"
    "teamleader-form-integration"
    "jma-youtube-playlists-with-schema"
    "zarinpal-provip-payment"
    "woocommerce-expresspay-payment-gateway"
    "wp-posts-re-order"
    "flurry"
    "posts-filter-multiselect"
    "vouchsafe-captcha-replacement"
    "gg-twitter"
    "ultimate-pdf-flipbooks-flip-books-made-easy"
    "o365-user-authentication"
    "ultimate-popunder"
    "cartograf-cookie-filter"
    "matador-jobs"
    "cyberpret-calculettes"
    "speedsize-ai-image-optimizer"
    "easy-sticky-notification-bar"
    "myd-delivery-widgets"
    "send-anywhere-file-transfer"
    "tienda-crypto-woo"
    "cc-mortgage-calculator"
    "user-bio-widget"
    "wati-chat-and-notification"
    "hot-linked-image-cacher-with-keywords"
    "wp-comment-notification"
    "automatic-footer-copyright"
    "paginated-effects-gallery"
    "quickwebp"
    "drozd-addons-for-elementor"
    "ab-audio-sync"
    "color-keywords"
    "line-auto-post"
    "menu-breadcrumb"
    "tipster-tap"
    "mingrana-wp-to-blockchain"
    "internal-link-finder"
    "affiliates-manager-mailchimp-integration"
    "random-posts-with-thumbnails"
    "mage-enabler"
    "wpshopgermany-protectedshops"
    "rackspace-cloud-files-cdn"
    "activetrail-contact-form-7"
    "taxi-fare-calculator-by-taxifarefindercom"
    "mediapost"
    "rs-members"
    "kargo-takip"
    "child-themes"
    "gosign-readmore-toggle-text-block"
    "loan-calculator-pro"
    "lkn-wc-gateway-cielo"
    "password-protect-staging"
    "codecarebd-bkash-nagad-rocket-payoneer-gateway"
    "ovulation-calculator"
    "calculoid-calculators-builder"
    "spectrocoin-accepting-bitcoin"
    "woocommerce-out-of-stock-message"
    "s2member-addon-for-wp-courseware"
    "wp-random-ads"
    "responsive-flipbooks"
    "wp-ads-within-contents"
    "sell-photo"
    "custom-store-locator"
    "payop-woocommerce"
    "woocommerce-empty-cart-button"
    "googleplusone-button"
    "insert-ads-on-post"
    "lasso"
    "woo-advanced-variation"
    "wp-text-sizer"
    "wp-ptviewer"
    "modify-attachments-meta"
    "flockler"
    "security-and-vulnerability-shield"
    "config-constants"
    "counter-block"
    "bitfire"
    "conversions-extensions"
    "wl-email-encrypter"
    "events-in-city"
    "keep-emoticons-as-text"
    "sellbrite"
    "header-marquee"
    "oik-batchmove"
    "realsatisfied-widget"
    "edit-howdy"
    "wizit-gateway-for-woocommerce"
    "buddypress-gifts-latest-2014"
    "force-login-with-email"
    "perfecto-portfolio"
    "widget-locationizer"
    "wp-fail2ban-addon-contact-form-7"
    "guidant"
    "devvn-tet-holiday"
    "enhanced-custom-menu"
    "peepso-tools-ultimate-member-migrator"
    "classic-widgets-with-block-based-widgets"
    "easy-woocommerce-customizer"
    "woocommerce-click-pledge-gateway"
    "hello-i-am-here"
    "big-boom-directory"
    "swedbank-pay-checkout"
    "optimize-more-images"
    "ember-companion"
    "anti-adblock-adbreach"
    "somenano"
    "svg-menu"
    "currency-converter-rub"
    "embed-gutenberg-block-google-maps"
    "grid-view-gallery"
    "wp-orphanage-extended"
    "hello-spock"
    "clipboard"
    "formcraft-mymail"
    "color-your-bar"
    "frontier-restrict-backend"
    "wicked-block-conditions"
    "rw-elephant-rental-inventory"
    "pager-widget"
    "hottaimoijiruna"
    "kudos-donations"
    "hijri-calendar"
    "threepress"
    "simple-top-commenters"
    "twitter-hash-tag-shortcode"
    "ect-homepage-products"
    "wp-google-lang-transliteration"
    "amazon-payment-services"
    "navegg"
    "fundamento"
    "wpmediawiki"
    "cool-social-icons-widget"
    "gallery-linknone"
    "callphoner"
    "wpredesigned-beautiful-custom-admin-theme"
    "n360-splash-screen"
    "custom-login-css"
    "lockee"
    "qr-code-creator"
    "awesome-event-booking"
    "casso-tu-dong-xac-nhan-thanh-toan-chuyen-khoan-ngan-hang"
    "ink-official"
    "usgs-stream-flow-data"
    "easy-featured-image"
    "xv-random-quotes"
    "add-analytics-code"
    "author-customization"
    "wp-e-commerce-multilingual"
    "wp-post-slider-grandslider"
    "wp-super-speed"
    "ecab-taxi-booking-manager"
    "integration-for-gravity-forms-and-pipedrive"
    "evenium"
    "12-step-meeting-pdf-generator"
    "fireems-stats"
    "video-player-for-wpbakery"
    "disable-directory-listings"
    "windows-live-writer"
    "easy-lite-preloader"
    "activity-link-preview-for-buddypress"
    "theme-manager"
    "gravity-forms-business-hours"
    "plisio-payment-gateway-for-woocommerce"
    "education-addon"
    "qtranslate-separate-comments"
    "templ-optimizer"
    "ultimate-subscribe"
    "wp-changes-tracker"
    "edd-rave"
    "dsgnwrks-twitter-importer"
    "croatian-payment-slip-generator-for-woocommerce"
    "disable-lazy-load"
    "theme-blvd-favicon"
    "login-redirect-url"
    "free-wp-mail-smtp"
    "cocoon-scenery-color"
    "shop-press"
    "current-year-shortcode-vict"
    "wc-importer-for-danea"
    "ajax-search"
    "adredux"
    "custom-display-posts"
    "dable"
    "product-lister-etsy"
    "contact-form-7-elavon-converge"
    "buddypress-analytics"
    "easy-schema-structured-data-rich-snippets"
    "jobify-xml-csv-listings-import"
    "simple-google-static-map"
    "lh-zero-spam"
    "wp-recent-posts-extended"
    "smart-brands-for-woocommerce"
    "relevant-search"
    "wp-login-logo-changer-by-ahmad-awais"
    "affiliatewp-affiliate-qr-codes"
    "prism"
    "notices-duyurular"
    "adfly-website-monetarization"
    "cmb2-field-type-font-awesome"
    "reorder-entry-images"
    "tailor-advanced"
    "acpt-lite"
    "direction-map"
    "libwp"
    "mini-newsletter"
    "bulglish-permalinks"
    "team-members-for-elementor"
    "woocommerce-order-notes-window"
    "woo-payu-paisa"
    "posts-from-single-category-widget"
    "tabbed-widgets-reloaded"
    "sa11y"
    "disable-woocom-logout-confirmation"
    "atom-publishing-protocol"
    "revolution-ajax-content-loader"
    "coming-soon-products-for-woocommerce"
    "category-post-slider"
    "ns-maintenance-mode-for-wp"
    "smashwords-book-widget"
    "nextgen-oqey-skins-lite"
    "wipad"
    "swiss-knife-for-oxygen-buider"
    "simple-countdown"
    "paypal-link-sale"
    "puzzleme"
    "wa-testimonial-slider-wp"
    "delyvax"
    "nganluongvn-payment-gateway-for-woocommerce"
    "gdpr-tools"
    "quote-this"
    "sticky"
    "wp-email-guard"
    "product-notices-for-woocommerce"
    "change-excerpt-length"
    "astounding-spam-prevention"
    "bbpress-custom-reply-notifications"
    "staticfeed"
    "advance-login-style"
    "bp-groups-suggestions"
    "read-more-login"
    "seo-meta-description"
    "venture-lite-companion"
    "video-dashboard"
    "visual-admin-customizer"
    "legacy-google-calendar-events"
    "indeed-api"
    "mdirector-newsletter"
    "simple-paginated-posts"
    "clicky-popular-posts-widget"
    "tierra-billboard-manager"
    "wowrecrut"
    "my-contador-wp"
    "dominant-colors-lazy-loading"
    "studiocart"
    "alobaidi-captcha"
    "awesome-wp-mixitup-portfolio"
    "blog-posts-order"
    "wpuppy"
    "dummy-text-generator"
    "simplicy-post-view"
    "password-policy"
    "bp-post-from-anywhere"
    "mobile-app-for-woocommerce"
    "swe-osome-post-slider"
    "clone-woo-orders-free-by-wp-masters"
    "wc-direct-place-order-without-payment"
    "blazing-woocommerce-shipment-tracking"
    "wp-500px-jsgallery"
    "automatically-empty-trash"
    "magic-robots-txt"
    "woocommerce-book-keeper"
    "comments-shortcode"
    "wpurdu"
    "json-rest-api-wp-api-categories-and-tags"
    "booster-for-wpforms"
    "convertkit-for-paid-memberships-pro"
    "jc-recaptcha"
    "fortvision-platform"
    "abandoned-checkout-recovery-order-notifications-for-woocommerce"
    "stealth-update"
    "flashnews-fading-effect-pearlbells"
    "riovizual"
    "wc-brand"
    "multi-purpose-mail-form"
    "remove-admin-footer-and-version"
    "auto-login-after-registration"
    "buddypress-hovercards"
    "spice-blocks"
    "go-viral"
    "rus-to-eng"
    "f12-floating-menu"
    "buddypress-admin-only-profile-fields"
    "image-comparison"
    "octolize-canada-post-shipping"
    "wc-bacs-paybysquare"
    "page-builder-for-wpforms"
    "maintainn-tools"
    "wp-quick-contact-us"
    "scrubbill"
    "delele-all"
    "ra-widgets-animate"
    "copy-menu"
    "cls-lcp-issues-fix"
    "smaily-for-woocommerce"
    "smart-wp-seo"
    "bp-display-name"
    "woo-layup-payment-gateway"
    "author-box-reloaded-pack"
    "seo-meta"
    "media-finder"
    "woo-paydesign"
    "almost-all-categories"
    "wp-hubspot-woocommerce"
    "wp-webapp"
    "simple-instant-search"
    "social-media-in-the-sidebar"
    "news-kit-elementor-addons"
    "custom-page-extensions"
    "widgetpack-comment-system"
    "accounting-for-woocommerce"
    "translation-tools"
    "instant-featured-image"
    "well-handled"
    "twitter-follow-button-for-wordpress"
    "new-zealand-shipping-zones-for-woocommerce"
    "wordpress-exit-box-lite"
    "sirvoy-booking-engine"
    "feature-request"
    "multiple-image-upload"
    "gameball"
    "affiliates-woocommerce-advanced-integration"
    "auth-armor-passwordless-login"
    "broken-images-redirection"
    "wpsso-add-five-stars"
    "recipe-block"
    "my-twitter-timelines"
    "easily-change-admin-color"
    "diarypress"
    "tiny-bootstrap-elements-light"
    "sell-media-file"
    "revision-removal"
    "logmytrip"
    "agent-image-news"
    "foremedia-ads-inserter"
    "pre-publish-post-checklist"
    "acf-rrule-field"
    "encute"
    "affiliates-jigoshop-light"
    "hebrew-font"
    "replace-content-image-size"
    "review-widgets-for-arukereso"
    "cmb2-admin-extension"
    "wgpwpp"
    "author-popup"
    "featured-comment-widget"
    "disable-attachment-pages"
    "gravity-forms-data-persistence-add-on"
    "eyewear-prescription-form"
    "smdp-affiliate-platform"
    "enhanced-blocks"
    "wip-incoming-lite"
    "syncfields"
    "jellyfish-backdrop"
    "classy-addons-for-elementor"
    "surbma-wp-control"
    "cargus"
    "form-abandonment-tracking"
    "blade"
    "df-pagination"
    "faceted-search-widget"
    "ebook-download"
    "buddypress-no-mentions"
    "popad"
    "the-cache-purger"
    "dropp-for-woocommerce"
    "quick-adsense-cn"
    "advanced-author-box"
    "wp-stripe-express"
    "geolocation-detector-for-gravity-forms"
    "comments-with-openid"
    "eu-cookie-notification"
    "dynamic-copyright-year"
    "2c2p-redirect-api-for-woocommerce"
    "lh-force-lowercase-urls"
    "disable-comment-author-links"
    "opti-mozjpeg-guetzli-webp"
    "woocommerce-branding"
    "billingotomatis-payment-gateway-indonesia"
    "documents-from-git"
    "vixo-embeddable-tables-charts-and-spreadsheets"
    "better-forms"
    "ajax-scroll"
    "asgard"
    "local-sync"
    "mma-call-tracking"
    "the-fill-mill-woocommerce-verifier"
    "singleplatform"
    "giveaways-contests"
    "wp-slug-post-type-custom-language"
    "what-if-bitcoin"
    "best-seo-itranslator-for-wordpress"
    "koraki-social-proof"
    "news-parser"
    "empty-tags-remover"
    "buddypress-jquery-activity-stream-widget"
    "hide-unwanted-shortcodes"
    "rename-wp-admin-login"
    "scss-wp-editor"
    "international-namedays"
    "service-box-with-slider"
    "image-processing-queue"
    "parone"
    "sv-twitch"
    "visual-regression-tests"
    "tribute-testimonial-gridslider"
    "theme-toolkit"
    "fontawesomeio-shortcodes"
    "zip-codes-redirect"
    "awstats-report-viewer"
    "tcpdf"
    "hreflang-for-polylang"
    "conditional-logic-for-elementor-forms"
    "modula-foo-migrator"
    "wpwh-contact-form-7"
    "ttt-crop"
    "remove-comment-notes"
    "depay-donations"
    "booster-pack-for-divi"
    "jab-external-links-newtab"
    "quickswish"
    "custom-class-selector"
    "gf-klaviyo-add-on"
    "logout-button"
    "surbma-divi-remove-project-cpt"
    "pryc-wp-maintanance"
    "comment-testimonials"
    "theperfectweddingnl-widget"
    "members-restricted-access"
    "wp-filter-posts"
    "sensei-lesson-timer"
    "easy-listings-map"
    "foursquare-map"
    "onepay-payment-gateway-for-woocommerce"
    "map-contact"
    "woocommerce-loyal-customer"
    "wp-hamazon"
    "navgoco-menu"
    "pmpro-pods"
    "shorter-links"
    "faq-schema-for-elementor"
    "tainacan-blocksy"
    "aviation-weather-from-noaa"
    "post-country"
    "hardcore-google-fonts-localizer"
    "ultimate-member-widgets-for-elementor"
    "login-restrict"
    "secure-xml-rpc"
    "simple-social-shout-for-givewp"
    "revision-diet"
    "mb-spirit-for-mindbody"
    "remove-wp-version-everywhere"
    "full-calendar-js"
    "custom-options-tree"
    "wp-fancy-captcha"
    "minecraft-server-status-widget"
    "suscriptflech"
    "bp-profile-as-homepage-fork"
    "preenche-endereco-cep"
    "ec-authorizenet"
    "email-verification-on-signups"
    "idraw"
    "simple-cart-reminder"
    "youtube-thumbnail-to-featured-image"
    "wordpress-mu-theme-stats"
    "clear-html-tags"
    "lorem-ipsum-post-generator"
    "eazygrid-for-elementor"
    "block-enhancements"
    "shippingeasy-for-wp-ecommerce"
    "image-hover-effects-for-woocommerce-products"
    "contact-form-7-group-mail"
    "auto-mail"
    "tb-search-in-menu"
    "demomentsomtres-vc-cpw"
    "automizy-elementor-integration"
    "pinit"
    "still-be-image-quality-control"
    "rsvpmaker-widget"
    "wp-sitemaps-config"
    "see-attachments"
    "wp-revision-master"
    "wpc-antispambot"
    "mhm-list-postthumbnail"
    "mimi-captcha"
    "display-mysql-version"
    "ga-tracking-code"
    "simple-members-area"
    "zlick-paywall"
    "new-tab-always"
    "vinvin-seo"
    "leadfox"
    "venngage"
    "gf-freshdesk"
    "mit3xxxde-toolbar"
    "domain-for-sale"
    "weaver-themes-shortcode-compatibility"
    "simplicy-seo"
    "wp-simple-spreadsheet-fetcher-for-google"
    "analog-clock-10"
    "category-checklist-expander"
    "comment-pub"
    "wp-performance-security"
    "multisite-admin-bar-switcher"
    "recurring-timer-widget"
    "ims-countdown"
    "mpress-fix-url-references"
    "advanced-custom-fields-leaflet-field"
    "rock-the-slackbot"
    "cd-baby-player-emded"
    "fusion-extension-sidebar"
    "css-js-files"
    "post-gallery-widget"
    "funnelcockpit"
    "inext-woo-pincode-checker"
    "admin-quick-jump"
    "yuma-companion"
    "cf7-hubspot-forms-add-on-for-contact-form-7"
    "post-as-guest"
    "rating-plus"
    "add-before-after-text-products-price-in-woo"
    "uddoktapay-gateway"
    "radiojar-player"
    "ts-demo-importer"
    "contact-form-vcard-generator"
    "weaver-ii-to-weaver-xtreme"
    "simple-daily-quotes"
    "deliverability"
    "product-price-history"
    "lumturio-wp-monitor"
    "simple-subtitles"
    "buddypress-conditional-profile-field"
    "outdooractive-embed"
    "wp-uf2"
    "amazon-associate-filter"
    "tinymce-preformatted"
    "qiniu-tuchuang"
    "wp-mastodon-share"
    "top-posts-pages-widget"
    "admin-dashboard-last-edits"
    "disable-full-site-editing"
    "modern-polls"
    "gravity-forms-exacttarget"
    "android-appmaker"
    "yahoo-emoticons-for-custom-smileys"
    "woo-installments"
    "disclosure-for-amazon-affiliate"
    "author-box-1"
    "tournamatch"
    "bp-members-avatar-map"
    "tag-sticky-post"
    "disable-core-update-email"
    "slidr"
    "hk-exif-tags"
    "remove-default-widgets"
    "wp-posted-display"
    "postbar-shipping"
    "evangtermine"
    "run-log"
    "wp2wb"
    "socialflow"
    "gravity-forms-active-campaign-add-on"
    "discordian-date-function"
    "interactive-uk-map"
    "date-picker-for-contact-form-7"
    "quote-of-the-day-site2quotes-widget"
    "car-rental-booking-engine-by-ionoleggioauto-com"
    "easy-timeout-session"
    "appypie-web-to-app"
    "playlist-audio-player"
    "emoji-emoticons"
    "perfect-font-awesome-integration"
    "social-media-links"
    "titleimage"
    "motive-commerce-search"
    "advanced-post-image"
    "barcode-qrcode-generator"
    "random-excerpts-fader"
    "mail-queues"
    "bp-messaging-control"
    "internet-speed-test"
    "wc-sold-unit-display"
    "wpdevhub-troubleshooting-guides"
    "wp-sticker-notes"
    "untappd-checkins-widget"
    "my-fastapp"
    "external-related-posts"
    "etoile-theme-companion"
    "woo-visma-integration"
    "wordpress-sentinel"
    "random-numbers-builder"
    "shortcode-for-font-awesome"
    "mobile-navigation-menu"
    "fullscreen-10-for-wp-super-edit"
    "jetpack-gplus-provider"
    "visual-mode-in-cloudfront"
    "keks-pay-for-woocommerce"
    "dilli-email-validator"
    "woo-salesforce-connector"
    "simple-support-ticket-system"
    "badgeos-invite-codes-add-on"
    "underconstruction-for-page"
    "elysio-form"
    "buddypress-activity-tags"
    "give-donation-modules-for-divi"
    "frontend-dashboard-notification"
    "moxo"
    "wordpress-custom-post-type-archive"
    "colored-order-notes-for-woocommerce"
    "weight-based-pricing-for-woocommerce"
    "wp-emailfeedburnerpop"
    "wp-caldav2ics"
    "bitvolution-image-galleria"
    "wp-covid-19-data"
    "resultpress"
    "disable-elementor-editor-translation"
    "odynogooglegroups"
    "best-custom-css"
    "single-post-sidebar-widget"
    "site-announcements"
    "category-archives-block"
    "waktu-solat-countdown"
    "shinobi-reviews"
    "buba-blocks"
    "hide-footer-links"
    "companion-portfolio"
    "global-body-mass-index-calculator"
    "integration-for-contact-form-7-and-google-sheets"
    "ybug-feedback-widget"
    "socialcompare-embed"
    "devvn-snow"
    "bbpress-digest"
    "fancy-transitions-featured-gallery"
    "age-verification-for-woocommerce"
    "custom-email-sender"
    "woo-tbc-payment-gateway"
    "ads-inside-post-aipwp"
    "valentines-day-floating-hearts"
    "pagecdn"
    "sports-news"
    "fx-toc"
    "acymailing-integration-for-the-events-calendar"
    "tr-timthumb"
    "rss-feed-styles"
    "set-email-from-address"
    "holy-quran-random-verse-multilanguage"
    "akwpuploader-alternative-wordpress-image-uploader"
    "zoloblocks"
    "revision-delete"
    "custom-feeds"
    "crm-grc-contact-by-sg"
    "wp-disable-sitemap"
    "persian-date-short-code"
    "rss-links-manager"
    "increase-sociability"
    "wp-marquee"
    "wp-scribd"
    "weibo-like"
    "dropit"
    "advanced-csv-importer"
    "realanswers"
    "impact-partnership-cloud"
    "productprint"
    "ipccp"
    "wp-html-page-sitemap"
    "awesome-team-showcase"
    "wp-social-preview"
    "add-to-cart-redirect"
    "japanese-proofreading-preview"
    "techenabler-header-links-removal"
    "security-force"
    "cvmh-simple-slideshow"
    "sorttable-post"
    "livechat-lazucrub"
    "send-a-wow-dogecoin-donation"
    "markdown-comment-block"
    "mycred-amelia"
    "hide-welcome-panel-for-multisite"
    "extra-styling-for-memberpress"
    "customizer-disabler"
    "beerxml-shortcode"
    "ithemeland-woo-bulk-coupons-editing-lite"
    "nginx-manager"
    "responsive-addons-for-elementor"
    "image-comparison-block"
    "agreement"
    "wc-korkmaz-contract"
    "deploy-netlifypress"
    "simple-tour-guide"
    "cloak-front-end-email"
    "wp247-body-classes"
    "remove-exif-and-metadata"
    "podio-webforms"
    "happy-snowman"
    "wporg-glossary"
    "update-unique-keys"
    "easy-video-gallery-responsive-html5"
    "moving-contents"
    "genesis-media-project"
    "mobicow-mobile-ads"
    "retaggr"
    "twitter-posts"
    "debug-mo-translations"
    "avif-express"
    "widget-inclusion-for-manychat"
    "cf7-dropbox"
    "is-circular-photo-gallery"
    "blog2widget"
    "pcrecruiter-extensions"
    "inet-webkit"
    "blog-optimize"
    "ip-address-approval"
    "really-simple-under-construction"
    "my-wp-brand"
    "website-builder"
    "genei"
    "monetizemore-ads-txt"
    "welcome-mat"
    "zcom-easy-wp-migrator"
    "cnzz51la-for-wordpress"
    "wp-open-comment-links-in-new-window"
    "wps-html-blocks"
    "order-emails-log-for-woocommerce"
    "better-formats"
    "post-update-addon-gravity-forms"
    "no-unsafe-inline"
    "user-custom-discount"
    "tweet-stimonials"
    "alexarank"
    "icanlocalize-translator"
    "cf7-creamailer-extension"
    "delete-all-pending-comments"
    "zk-advanced-feature-post"
    "absolute-links"
    "insitelogin"
    "better-protected-pages"
    "news-tick-o-matic"
    "movie-widget"
    "jigoshop-custom-payment-gateway"
    "gf-engaging-networks-add-on"
    "get-image-from-post"
    "dominant-color"
    "wp-pace"
    "disable-email-notification-for-auto-updates"
    "phpbb-topics-portal"
    "bp-profile-status"
    "simple-voucher"
    "ie-css3-support"
    "wp-smart-property"
    "disable-admin-dashboard-notices"
    "video-wc-gallery"
    "music-sheet-viewer"
    "international-telephone-input-with-flags-and-dial-codes"
    "rss-make-antenna"
    "acf-timber-integration"
    "woo-mobile-money"
    "slippy-slider-responsive-touch-navigation-slider"
    "vanny-bean-speech-bubble"
    "wp-easy-embed"
    "yandex-go-delivery"
    "value-auth-two-factor-and-access-control"
    "eu-cookie-law-wp-cookie-law"
    "quick-cache-clear-for-publisher"
    "recent-post-photos"
    "chords-and-lyrics"
    "vibes"
    "libro-de-visitas-guestbook"
    "love-button"
    "useragent-themes-switcher"
    "re-pro"
    "daily-horoscope-widget"
    "spamshiv-lite-e-mail-address-protection"
    "gravatar-enhanced"
    "tsa-commerce"
    "hikari-title-comments"
    "adresskorrektur-autocomplete-fuer-woo"
    "lastfm-tabs"
    "wp-e-commerce-show-personalisation"
    "old-post-alert"
    "privateplus"
    "wallet-up"
    "slide-banners"
    "wpx-affiliate-manager"
    "gf-facebook-pixel-tracking"
    "buddypress-activity-stream-ajax-notifier"
    "content-box-addon-for-elementor"
    "copy-post"
    "lightweight-google-analytics"
    "disable-media-permalink-by-hardweb-it"
    "lsx-give-payfast-gateway"
    "ajax-easy-attendance-list"
    "compressed-emoji"
    "crop-and-resize-images"
    "automatic-schema"
    "apex-idx"
    "fp-testimonials"
    "mobile-switcher"
    "tiny-url"
    "kau-boys-comment-notification"
    "easy-maintenance-mode-by-wpkoder"
    "avang-email-sender-no-spam"
    "lock-your-updates"
    "smntcs-adobe-typekit-fonts"
    "advanced-tag-list"
    "user-profile-meta"
    "ap-honeypot"
    "multisite-blog-alias"
    "fancify-core"
    "smart-copy-protect"
    "mailchimp-campaign-archive"
    "fv-descriptions"
    "sugar-event-calendar-gravity-forms"
    "htaccess-secure-files"
    "itbazar-products-exporter"
    "pt-wp-discourse-sso"
    "wp-twittersearch"
    "wp-head-cleanup"
    "cop-pdf-attachment-menu"
    "my-woocommerce-product-virtual-showroom"
    "ytsubscribe"
    "akismet-spam-count"
    "love-me"
    "wp-secure-content"
    "just-another-author-widget"
    "bp-lotsa-feeds"
    "browser-sniff"
    "floatingsocialmediapopout"
    "sdac-translate"
    "show-future-posts-on-single-post"
    "add-smart-app-banner"
    "offline-content"
    "wp-categ-menu"
    "keyword-position-checker"
    "add-to-menu"
    "seo-internal-link-building"
    "wpcasa-all-import"
    "website-monitoring"
    "appsero-helper"
    "wc-shipping-rates-importer"
    "ploxel"
    "truendo"
    "acf-youtube-picker"
    "before-after-for-woocommerce"
    "cosmic-bp-user-signup-password"
    "login-with-cognito"
    "rut-chileno-con-validacion"
    "swap-snow-fall"
    "pay-with-a-tweet"
    "post-ideas"
    "restrict-elementor-widgets"
    "wp-widget-extentions"
    "property-hive-mortgage-calculator"
    "hotlink-file-prevention"
    "advanced-related-posts"
    "wp-media-files-name-rename"
    "wpm-news-api"
    "ultimate-shortcodes-creator"
    "easy-googles-widget"
    "cf7-ace-syntax-highlighting"
    "starter-templates"
    "force-post-category-selection"
    "js-css-include-manager"
    "cense-ai-chatbot"
    "simple-secure-contact-form"
    "jambopay-woocommerce-payment-gateway"
    "yd-fast-page-update"
    "subscribe-bar-youtube"
    "the-word-widget"
    "wc-theme-integration"
    "hijri"
    "post-tags-and-archive"
    "tdwfb"
    "vasaio-qr-code"
    "post-links"
    "widget-subtitles"
    "delay-redirects"
    "ssl-quality-checker"
    "coaching-staffs"
    "ui-elements-gravity-forms"
    "knowband-mobile-app-builder-for-woocommerce"
    "mgb-masonry-image-gallery"
    "mobcard-woo-payment-gateway"
    "graceful-email-obfuscation"
    "woohide-hide-billing-fields"
    "custom-post-type"
    "rps-blog-info"
    "google-related-post-links"
    "faq-manager-with-structured-data"
    "force-domain-redirect"
    "variable-inspector"
    "rapid-canonical-urls"
    "getresponse-for-formcraft"
    "interactive-medical-drawing-of-human-body"
    "theme-blvd-woocommerce-patch"
    "ajax-content-renderer"
    "wp-openapi"
    "blank-footnotes"
    "my-website-is-online-uptime-monitoring"
    "exact-links"
    "instantclick"
    "pedalo-connector"
    "linked-variation-for-woocommerce"
    "gd-forum-manager-for-bbpress"
    "ki-live-video-conferences"
    "faq-builder-ays"
    "majpage-menu-class-extender"
    "auto-content-poster"
    "favicon-my-blog"
    "restore-automatic-update"
    "economic-market-news"
    "hello-dolly-for-your-song"
    "simple-woocommerce-favourites"
    "giveaway-boost"
    "vb-wp-move-comments"
    "manual-completions-learndash"
    "dbd-mailto-encoder"
    "guest-order-tracking-for-woocommerce"
    "wp-smooth-scroll"
    "xml-rpc-modernization"
    "recent-posts-widget-unlimited"
    "redirect-after-comment-per-page"
    "grey-admin-color-schemes"
    "media-sitemap"
    "connections-business-directory-income-levels"
    "f70-simple-table-of-contents"
    "tada"
    "feedcache"
    "no-adblock"
    "a-featured-page-widget"
    "custom-ratings"
    "paypal-donation-shortcode"
    "content-bootstrap"
    "bopo-woo-product-bundle-builder"
    "popup-modal"
    "otw-tinymce-widget"
    "php-widgetify"
    "featured-image-from-youtube"
    "mmx-make-me-christmas"
    "51blocks-json-schema"
    "better-user-shortcodes"
    "payex-payment-gateway-for-woocommerce"
    "otys-jobs-apply"
    "merch-systems-storefront"
    "shane-web-guy-portfolio"
    "reinstall-plugins"
    "woocommerce-price-matrix"
    "feedsnap"
    "buddyplug"
    "horizontal-footer-sitemap-widget"
    "bbp-move-topics"
    "wp-welcome-gate"
    "bmi-calculator-widget"
    "hocus-pocus-buttons"
    "upload-to-dropbox"
    "article-with-pictures"
    "woo-shirt-product-designer"
    "yet-another-movie"
    "canonical-attachments"
    "edd-advanced-discounts"
    "private-wp-2"
    "wp-hooks"
    "buddypress-featured-members"
    "course-redirects-for-learndash"
    "wp-tagcanvas"
    "current-location"
    "simplified"
    "academy-elementor-addons"
    "webcamconsult"
    "kayako-messenger-live-chat"
    "affiliatewp-mailchimp-add-on"
    "crypto-payments-woo"
    "wp-posts-widget"
    "display-last-posts"
    "mass-set-post-categories"
    "truenorth-srcset"
    "cf7-icons-and-labels"
    "billmate-checkout-for-woocommerce"
    "cfs-options-screens"
    "otp-login"
    "share-me"
    "choicecuts-image-juggler"
    "folder-slider"
    "live-chat-button"
    "wp-revive-adserver"
    "frictionless"
    "clean-up-wp-head"
    "wp-advanced-include"
    "xve-various-embed"
    "wp-more-feeds"
    "recent-post-widget-thumbnail"
    "multisite-plugin-stats"
    "wiredrive-player"
    "uncache-script"
    "zajax-ajax-navigation"
    "wp-news-sliders"
    "i-divi-post-settings"
    "awesome-fontawesome-collection"
    "wc-product-filter"
    "map-multiple-marker"
    "billbee-auftragsabwicklung-warenwirtschaft-automatisierung"
    "improve-my-city"
    "paystation-woocommerce-payment-gateway"
    "buddyextender"
    "gift-buddypress-addons"
    "integrate-razorpay-contact-form-7"
    "genesis-co-authors-plus"
    "netgo-horizontal-carousel"
    "gift-pack-for-woocommerce"
    "import-export-for-woocommerce"
    "web-push"
    "silent-publish"
    "dzs-enable-debug"
    "woo-booking-bundle-hours"
    "bittipit-bitcoin-donation-button"
    "gift-card-for-woocommerce"
    "bbp-shortcodes"
    "smartrmail-personalized-email-marketing"
    "360-sphere-images"
    "aviary-photo-editor"
    "bitcoin-donate-button"
    "smart-investment-calculator"
    "average-head-footer-code"
    "as-woocommerce-with-owl-carousel"
    "managementmaintainence-recording"
    "shrinkwrap-images"
    "dejureorg-vernetzungsfunktion"
    "disable-yoast-ld-json"
    "shopp-improved"
    "hostplugin-woocommerce-points-and-rewards"
    "statsfc-results"
    "asyncronous-bbpress-subscriptions"
    "semrush-contentshake"
    "ajax-file-upload"
    "paypal-gift-certificate"
    "post-backgrounds"
    "zmanim-widget"
    "latest-apple-movie-trailers"
    "wp-keep-me-logged-in"
    "bp-user-reviews"
    "block-for-masonry-gallery"
    "pixelavo"
    "random-post-box"
    "vast-demo-import"
    "no-cache-ajax-widgets"
    "edge-cache-html-cloudflare-workers"
    "back-to-top"
    "simple-clinic"
    "float-ads-fixed-position"
    "theme-options-z"
    "bp-extend-widgets"
    "disable-thumbnails-and-threshold"
    "replace"
    "pagelist"
    "bp-block-users"
    "wp-background-tile"
    "site-address-migrator"
    "prismpay-woocommerce"
    "wp-smoother"
    "shmapper-by-teplitsa"
    "easy-color"
    "run-external-crons"
    "wc-order-reports"
    "rss-no-more"
    "password-protect-pages"
    "rocketfuel-payment-gateway"
    "earthquakemonitor"
    "wp-custom-sidebars"
    "classic-image-button"
    "document-generator-for-openapi"
    "planaday-api"
    "simple-shortlinks"
    "wp-e-commerce-extra-shipping-option"
    "wordpress-ab-theme-split-tests"
    "pixnet"
    "shopcred"
    "branded-sms-pakistan"
    "jj-nextgen-unload"
    "wxy-advanced-multitheme"
    "hello-simpsons-chalkboard-gag"
    "gleap"
    "ctl-arcade-lite"
    "connections-business-directory-local-time"
    "skautis-integration"
    "import-kintone"
    "rest-api-featured-image"
    "honeypot-comments"
    "sidebar-shortcodes"
    "wholesale-customers-for-woo"
    "magic-meta-box"
    "location-module-for-contact-form-7"
    "templatic-google-amp"
    "bitcoin-online"
    "themekit"
    "reactive-mortgage-calculator"
    "end-page-slide-box"
    "appointify"
    "spolecznosciowa-6-pl-2013"
    "digiseller"
    "room-34-presents-on-this-day"
    "acymailing-integration-for-modern-events-calendar"
    "wp-rest-menu"
    "wp-bxslider"
    "twispay"
    "simplegal"
)

# Define user agents with weights
declare -A USER_AGENTS
USER_AGENTS=(
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"]=5
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"]=7
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"]=6
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36 Edg/91.0.864.54"]=5
    ["Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 OPR/77.0.4054.277"]=3
    ["Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (iPad; CPU OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Vivaldi/4.0"]=1
    ["Mozilla/5.0 (Android 11; Mobile; rv:68.0) Gecko/68.0 Firefox/88.0"]=1
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"]=15
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/534.36"]=12
)

OPENED_PLUGINS_FILE="${WORDPRESS_WORKDIR}/opened_plugins.txt"
CLOSED_PLUGINS_FILE="${WORDPRESS_WORKDIR}/closed_plugins.txt"
LAST_VERSION_FILE="${WORDPRESS_WORKDIR}/last_versions.txt"
PARALLEL_JOBS=1

DOWNLOAD_ALL_PLUGINS='n'
LIST_ONLY='n'
ALL_PLUGINS_FILE="${WORDPRESS_WORKDIR}/wp-plugin-svn-list.txt"

DELAY_DOWNLOADS='n'
DELAY_DURATION=5

FORCE_UPDATE='n'
CACHE_ONLY='n'

mkdir -p "$WORDPRESS_WORKDIR" "$MIRROR_DIR" "$LOGS_DIR"
rm -f "$OPENED_PLUGINS_FILE"
touch "$OPENED_PLUGINS_FILE"
DEBUG_MODE=0

while getopts "p:dalD:t:fc" opt; do
    case ${opt} in
        p ) PARALLEL_JOBS=$OPTARG ;;
        d ) DEBUG_MODE=1 ;;
        a ) DOWNLOAD_ALL_PLUGINS='y' ;;
        l ) LIST_ONLY='y' ;;
        D ) DELAY_DOWNLOADS=$OPTARG ;;
        t ) DELAY_DURATION=$OPTARG ;;
        f ) FORCE_UPDATE='y' ;;
        c ) CACHE_ONLY='y' ;;    # New option for cache-only
        \? ) echo "Usage: $0 [-p PARALLEL_JOBS] [-d] [-a] [-l] [-D DELAY_DOWNLOADS] [-t DELAY_DURATION] [-f] [-c]" 1>&2; exit 1 ;;
    esac
done

debug_log() {
    if [ "$DEBUG_MODE" -eq 1 ]; then
        echo "[DEBUG] $1" >&2
    fi
}

get_random_user_agent() {
    echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
}

get_latest_version_and_download_link() {
    local plugin=$1
    debug_log "Checking latest version and download link for $plugin"
    
    local api_url="https://api.wordpress.org/plugins/info/1.0/${plugin}.json"
    local user_agent=$(get_random_user_agent)
    local api_response=$(curl -s -H "User-Agent: $user_agent" "$api_url")
    
    if echo "$api_response" | jq -e '.error' >/dev/null; then
        local error_message=$(echo "$api_response" | jq -r '.error')
        if [ "$error_message" = "closed" ]; then
            echo "closed"
            return 2
        else
        echo "Error: $error_message for plugin $plugin" >&2
        return 1
        fi
    fi
    
    local version=$(echo "$api_response" | jq -r '.version // empty')
    local download_link=$(echo "$api_response" | jq -r '.download_link // empty')
    
    if [ -n "$version" ] && [ -n "$download_link" ]; then
        echo "$version $download_link"
        return 0
    else
        echo "Error: Cannot fetch version or download link for $plugin" >&2
        return 1
    fi
}

download_plugin() {
    local plugin=$1
    local version=$2
    local api_download_link=$3
    local output_file="${MIRROR_DIR}/${plugin}.${version}.zip"
    local header_file="${LOGS_DIR}/${plugin}.${version}.headers"
    local constructed_download_link="${DOWNLOAD_BASE_URL}/${plugin}.${version}.zip"
    local download_link

    if [ "$DEBUG_MODE" -eq 1 ]; then
        debug_log "API-provided download link for $plugin: $api_download_link"
        debug_log "Constructed download link for $plugin: $constructed_download_link"
    fi

    if [ "$DOWNLOAD_LINK_API" == 'y' ] && [ -n "$api_download_link" ]; then
        download_link="$api_download_link"
        debug_log "Using API-provided download link for $plugin: $download_link"
    else
        download_link="$constructed_download_link"
        debug_log "Using constructed download link for $plugin: $download_link"
    fi

    debug_log "Downloading $plugin version $version through Cloudflare Worker"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)
    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o /dev/null "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    else
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o "$output_file" "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    fi

    if [ $? -eq 0 ]; then
        if [ "$CACHE_ONLY" == 'y' ]; then
            debug_log "Plugin $plugin version $version cached successfully."
            return 0
        fi

        local file_size=$(stat -c%s "$output_file")
        if [ "$file_size" -lt 1000 ]; then
            echo "Error: Downloaded file for $plugin is too small (${file_size} bytes). Possible download issue." >&2
            return 1
        fi

        local source=$(grep -i "X-Source:" "$header_file" | cut -d' ' -f2 | tr -d '\r')
        if [ "$source" == "R2" ]; then
            debug_log "Successfully downloaded $plugin version $version from R2 storage"
        elif [ "$source" == "WordPress" ]; then
            debug_log "Successfully downloaded $plugin version $version from WordPress"
            debug_log "R2 bucket saving for plugin zip occurred"
        else
            debug_log "Skipped download for $plugin $version zip (already exists locally)"
        fi

        return 0
    else
        echo "Error: Failed to download $plugin version $version" >&2
        return 1
    fi
}

save_plugin_info() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.json"

    debug_log "Saving plugin json metadata for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying metadata download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    if [ "$CACHE_ONLY" == 'y' ]; then
        # When in cache-only mode, output to /dev/null
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin metadata for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache json metadata for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            if [ "$source" = "R2" ]; then
                debug_log "json metadata for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "json metadata for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin json occurred"
            else
                debug_log "json metadata for $plugin version $version saved (json metadata file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save json metadata for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

fetch_and_save_checksums() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.checksums.json"

    debug_log "Fetching and saving checksums for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying checksums download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    debug_log "Sending request to Worker for checksums: CF_WORKER_URL?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"

    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin checksums for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache checksums for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        debug_log "Received response with status code: $status_code"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            debug_log "Response source: $source"
            if [ "$source" = "R2" ]; then
                debug_log "Checksums for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "Checksums for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin checksums occurred"
            else
                debug_log "Checksums for $plugin version $version saved (checksums file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save checksums for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

process_plugin() {
    local plugin=$1

    # Check if the plugin is already known to be closed
    if grep -q "^$plugin$" "$CLOSED_PLUGINS_FILE" 2>/dev/null; then
        echo "Plugin $plugin is known to be closed. Skipping."
        return 0
    fi

    echo "Processing plugin: $plugin"

    VERSION_AND_LINK=$(get_latest_version_and_download_link "$plugin")
    local version_check_status=$?
    
    if [ $version_check_status -eq 1 ]; then
        echo "Skipping $plugin due to version fetch error."
        return 1
    elif [ $version_check_status -eq 2 ]; then
        echo "Plugin $plugin is closed. Skipping download and processing."
        echo "$plugin" >> "$CLOSED_PLUGINS_FILE"
        if save_plugin_info "$plugin" "closed"; then
            debug_log "Successfully saved json metadata for closed plugin $plugin."
        else
            debug_log "Failed to save json metadata for closed plugin $plugin."
        fi
        return 0
    fi
    
    LATEST_VERSION=$(echo "$VERSION_AND_LINK" | cut -d' ' -f1)
    API_DOWNLOAD_LINK=$(echo "$VERSION_AND_LINK" | cut -d' ' -f2-)

    debug_log "Latest version for $plugin: $LATEST_VERSION"
    debug_log "API download link for $plugin: $API_DOWNLOAD_LINK"

    STORED_VERSION=$(grep "^$plugin" "$LAST_VERSION_FILE" | awk '{print $2}')
    debug_log "Stored version for $plugin: $STORED_VERSION"

    if [ "$CACHE_ONLY" != 'y' ] && [ "$LATEST_VERSION" == "$STORED_VERSION" ] && [ -f "${MIRROR_DIR}/${plugin}.${LATEST_VERSION}.zip" ]; then
        echo "$plugin is up-to-date and exists in mirror directory. Skipping download..."
    else
        start_time=$(date +%s.%N)

        if download_plugin "$plugin" "$LATEST_VERSION" "$API_DOWNLOAD_LINK"; then
            if [ "$CACHE_ONLY" != 'y' ]; then
                sed -i "/^$plugin/d" "$LAST_VERSION_FILE"
                echo "$plugin $LATEST_VERSION" >> "$LAST_VERSION_FILE"
            fi
            echo "Successfully processed $plugin."
        else
            echo "Error: Failed to process $plugin." >&2
        fi

        end_time=$(date +%s.%N)
        duration=$(echo "$end_time - $start_time" | bc)
        printf "Time taken for %s: %.4f seconds\n" "$plugin" "$duration"
    fi

    if save_plugin_info "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully saved json metadata for $plugin."
    else
        debug_log "Failed to save json metadata for $plugin."
    fi

    if fetch_and_save_checksums "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully fetched and saved checksums for $plugin."
    else
        debug_log "Failed to fetch and save checksums for $plugin."
    fi

    if [ $version_check_status -eq 0 ]; then
        echo "$plugin" >> "$OPENED_PLUGINS_FILE"
    fi
}

populate_all_plugins() {
    if [ ! -f "$ALL_PLUGINS_FILE" ] || [ "$LIST_ONLY" == 'y' ]; then
        echo "Fetching list of all WordPress plugins..."
        svn list https://plugins.svn.wordpress.org/ | sed 's/\/$//g' > "$ALL_PLUGINS_FILE"
        plugin_count=$(wc -l < "$ALL_PLUGINS_FILE")
        echo "Plugin list (${plugin_count}) saved to $ALL_PLUGINS_FILE"
    fi
    
    if [ "$LIST_ONLY" == 'n' ]; then
        ALL_PLUGINS=()
        while IFS= read -r line; do
            ALL_PLUGINS+=("$line")
        done < "$ALL_PLUGINS_FILE"
        echo "Loaded ${#ALL_PLUGINS[@]} plugins."
    fi
}

if [ "$LIST_ONLY" == 'y' ]; then
    populate_all_plugins
    echo "Plugin list created. Exiting without downloading."
    exit 0
fi

if [ "$DOWNLOAD_ALL_PLUGINS" == 'y' ]; then
    populate_all_plugins
    COMBINED_PLUGINS=("${ALL_PLUGINS[@]}")
else
    if [ ! -d "$PLUGIN_DIR" ]; then
        echo "Warning: Plugin directory $PLUGIN_DIR does not exist or is invalid."
        PLUGIN_LIST=()
    else
        PLUGIN_LIST=($(ls -d "$PLUGIN_DIR"/*/ 2>/dev/null | xargs -n 1 basename))

        if [ ${#PLUGIN_LIST[@]} -eq 0 ]; then
            echo "No plugins found in $PLUGIN_DIR."
        fi
    fi

    COMBINED_PLUGINS=(${PLUGIN_LIST[@]} ${ADDITIONAL_PLUGINS[@]})
    COMBINED_PLUGINS=($(echo "${COMBINED_PLUGINS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
fi

if [ ${#COMBINED_PLUGINS[@]} -eq 0 ]; then
    echo "No plugins to download. Exiting."
    exit 0
fi

mkdir -p "$MIRROR_DIR"
touch "$LAST_VERSION_FILE"

if [ "$PARALLEL_JOBS" -gt 1 ]; then
    echo "Running in parallel with $PARALLEL_JOBS jobs..."
    echo "Variables before export:"

    # WordPress-related directories
    echo "WORDPRESS_WORKDIR: $WORDPRESS_WORKDIR"
    echo "PLUGIN_DIR: $PLUGIN_DIR"
    echo "MIRROR_DIR: $MIRROR_DIR"
    echo "LOGS_DIR: $LOGS_DIR"

    # Cloudflare Worker related URLs
    echo "CF_WORKER_URL: $CF_WORKER_URL"

    # Flags and options
    echo "DOWNLOAD_LINK_API: $DOWNLOAD_LINK_API"
    echo "DOWNLOAD_ALL_PLUGINS: $DOWNLOAD_ALL_PLUGINS"
    echo "LIST_ONLY: $LIST_ONLY"
    echo "DELAY_DOWNLOADS: $DELAY_DOWNLOADS"
    echo "DELAY_DURATION: $DELAY_DURATION"
    echo "FORCE_UPDATE: $FORCE_UPDATE"
    echo "CACHE_ONLY: $CACHE_ONLY"

    # File paths
    echo "OPENED_PLUGINS_FILE: $OPENED_PLUGINS_FILE"
    echo "CLOSED_PLUGINS_FILE: $CLOSED_PLUGINS_FILE"
    echo "LAST_VERSION_FILE: $LAST_VERSION_FILE"
    echo "ALL_PLUGINS_FILE: $ALL_PLUGINS_FILE"

    # Parallel job configuration
    echo "PARALLEL_JOBS: $PARALLEL_JOBS"

    # User Agents mapping
    echo "USER_AGENTS: ${USER_AGENTS[@]}"

    # Additional plugins to be processed
    # echo "ADDITIONAL_PLUGINS: ${ADDITIONAL_PLUGINS[@]}"

    # Plugin List (loaded from directory or ALL_PLUGINS_FILE)
    #echo "PLUGIN_LIST: ${PLUGIN_LIST[@]}"
    #echo "COMBINED_PLUGINS: ${COMBINED_PLUGINS[@]}"

    # First, export all variables including USER_AGENTS
    export DOWNLOAD_BASE_URL MIRROR_DIR LAST_VERSION_FILE DEBUG_MODE DOWNLOAD_LINK_API LOGS_DIR ALL_PLUGINS_FILE DOWNLOAD_ALL_PLUGINS LIST_ONLY CF_WORKER_URL DELAY_DOWNLOADS DELAY_DURATION FORCE_UPDATE CACHE_ONLY WORDPRESS_WORKDIR PLUGIN_DIR PARALLEL_JOBS OPENED_PLUGINS_FILE CLOSED_PLUGINS_FILE USER_AGENTS

    # Then, export the functions
    export -f process_plugin get_latest_version_and_download_link download_plugin debug_log populate_all_plugins save_plugin_info get_random_user_agent fetch_and_save_checksums
    printf "%s\n" "${COMBINED_PLUGINS[@]}" | xargs -P $PARALLEL_JOBS -I {} bash -c 'process_plugin "$@"' _ {}
else
    for plugin in "${COMBINED_PLUGINS[@]}"; do
        process_plugin "$plugin"
    done
fi

if [ -f "$CLOSED_PLUGINS_FILE" ]; then
    echo
    echo "Closed Plugin List:"
    cat "$CLOSED_PLUGINS_FILE" | sort | uniq || true
    echo
    echo "Total closed plugins: $(wc -l < "$CLOSED_PLUGINS_FILE")"
    echo
else
    echo
    echo "No closed plugins found."
    echo
fi
echo "Plugin download process completed."
