#!/bin/bash

# Base directory (script location)
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Configurable directories
WORDPRESS_WORKDIR="${WORDPRESS_WORKDIR:-$BASE_DIR/wordpress-plugins}"
PLUGIN_DIR="${PLUGIN_DIR:-$BASE_DIR/wp-content/plugins}"
MIRROR_DIR="${MIRROR_DIR:-$BASE_DIR/mirror}"
LOGS_DIR="${LOGS_DIR:-$BASE_DIR/plugin-logs}"

# Check for CF_WORKER_URL environment variable
if [ -z "$CF_WORKER_URL" ]; then
    echo "Error: CF_WORKER_URL environment variable is not set." >&2
    exit 1
fi

DOWNLOAD_BASE_URL="https://downloads.wordpress.org/plugin"

# Other variables
DOWNLOAD_LINK_API='y'

ADDITIONAL_PLUGINS=(
    "icons-enricher"
    "s3-secure-url"
    "disable-wp-emojis"
    "native-fullscreen"
    "edd-xendit"
    "dashwidget"
    "direct-publisher-for-roku"
    "wp-svg"
    "oni-daiko"
    "entego-n11"
    "simple-share-follow-button"
    "github-user-repo-widget"
    "awcode-toolkit"
    "files-download-delay"
    "role-master"
    "fullcall"
    "eacreadme"
    "custom-thank-you-page-per-product-for-wc"
    "payment-gateway-for-ameriabank"
    "wp-custom-social-sharing"
    "user-and-login-management"
    "contact-easy"
    "ciusan-notification-bar"
    "wpc-product-image-swap"
    "twoo-performant"
    "avante-theme-extensions"
    "rentpress-gravity-forms-add-on"
    "crm-service-wp-forms"
    "admin-ajax-search-in-backend"
    "media-helpers"
    "wp-travelermap"
    "calendar-translation"
    "vividworks-3d-ecommerce-configurator"
    "podigee-player-shortcode"
    "ragic-shortcode"
    "boostimer"
    "belingocredit"
    "keys-to-admin"
    "ni-crm-lead"
    "paystack-for-events-calendar"
    "hiorgserver-terminliste"
    "wc-victoriabank"
    "product-feature-request"
    "arkam-lite"
    "multiple-votes-in-one-page"
    "woocommerce-wholesale-manager"
    "statsfc-poll"
    "my-reading-time-lite"
    "dadevarzan-woo-common"
    "reword"
    "js-crop"
    "waitlisted"
    "wp-tag-seeder"
    "post-summarizer"
    "page-category-and-archive-menu"
    "site-url-shortcode"
    "vmplayer"
    "responsive-flicker-widget"
    "simple-golf-club"
    "disable-author-archive-redirection"
    "shashin-permalinks"
    "post-popularity-chart-widget-lite"
    "administrate-more-comments"
    "pallet-packaging-for-woocommerce"
    "spendeonline"
    "post-to-queue"
    "awebsome-browser-selector-for-caching"
    "quick-slugs"
    "kk-tip-tricks"
    "wp-post-stats-analysis"
    "sardex-for-woocommerce"
    "viavi-wp-testimonials"
    "netdebit-payment-gateway"
    "custom-search-filter"
    "sunray-author-manager"
    "customizer-everywhere"
    "send-denial-anti-spam"
    "oh-my-svg"
    "comments-tinymce"
    "mz-post-and-page-excerpts-widgets"
    "emailtoascii"
    "captchelfie-captcha-by-selfie"
    "app-generator"
    "inespay-payment"
    "playme"
    "users-without-email"
    "opaque-teaser"
    "rotating-blogname"
    "woocommerce-prevent-purchase"
    "wp-code-editor-with-syntax-highlighter"
    "link2post"
    "bonus-plus-wp"
    "aam-online-bangla-radio"
    "wc-begateway-payment"
    "generate-random-orders-for-woocommerce"
    "amazon-affiliate-change-to-smile-link"
    "xml-gallery"
    "pin-dispenser-for-voguepay"
    "integration-for-szamlazz-hu-gravity-forms"
    "cc-clean-head-tags"
    "imposter"
    "edd-fastbill"
    "novocall-callback-widget"
    "guten-editor-blocks"
    "infinite-scroll-product-for-woocommerce"
    "average-travel-costs"
    "bp-memories"
    "global-coupons-for-woocommerce"
    "remove-emoji-css-and-js"
    "mindvalley-post-get-variable"
    "dual-rss-feed-key"
    "read-more-about"
    "notices-api"
    "menu-by-user-roles"
    "dashboard-server-specs"
    "nofollow-for-external-link-tap"
    "wp-service-box"
    "order-picking-for-woocommerce"
    "affieasy"
    "ultimate-email-validator"
    "product-customizer-light"
    "hello-top-100-movie-quotes"
    "wp-boilerplate-shortcode"
    "bookslots-simple-booking-form"
    "paraphraser"
    "magic-shortcodes-builder-lite"
    "merge-duplicate-terms"
    "leadsquared-website-topbar"
    "gnuplot-wordpress-plugin"
    "el-banners"
    "roomvu-marketing"
    "livehelpnow-helpdesk"
    "image-in-the-widget"
    "content-template-engine"
    "ucf-header-bar"
    "the-soccer-stats"
    "wp-folksonomy"
    "bizrate-insights-for-woocommerce"
    "the-tooltip"
    "simple-google-adsense-par-jm-crea"
    "randomize-css"
    "tp-recipe"
    "block-ai-crawlers"
    "saveyourinternet-protest-page"
    "wp-e-commerce-advance-sales-report-lite"
    "professional-opt-in"
    "excel-report-maker"
    "error-and-performance-tracking-with-catchjs"
    "cart-tracking-for-woocommerce"
    "syntax-highlighter-evolved-typescript"
    "envychimp"
    "tm-getcomplied-gdpr-wp"
    "semantic-shortcode"
    "two-level-conditional-menu"
    "auto-image-description-generator"
    "rd-contact-info"
    "team-member-divi"
    "wpf-force-external-nofollow"
    "goemerchant-gateway-for-woocommerce"
    "ndesign-theme-support"
    "inline-navi"
    "show-my-sales"
    "responsive-banner-slider"
    "wp-trackbackpopup"
    "multistore-multivendor"
    "tiny-gtag-js-analytics"
    "search-booking-comfor-wpbakery-page-builder"
    "members-is-user-logged-out-shortcode"
    "syntaxhighlighter-evolved-spacegray"
    "points"
    "subitem-al-slider"
    "wp-viewport"
    "mhshohel-faq"
    "soundst-linkmgr"
    "oganro-travel-portal-search-widget-for-hotelbeds-apitude-api"
    "post-2-epub"
    "wp-cta-top-bar"
    "hack-info"
    "wp-atom-importer"
    "muv-kundenkonto"
    "mosh-companion"
    "chinese-comment-spam-protection"
    "remove-meta-generators"
    "genesis-simple-portfolio"
    "lean-media"
    "breaking-bar"
    "alkubot"
    "accordion-block-lite"
    "surveysparrow-helper"
    "powerup-cf7"
    "welovez-social-login"
    "i-plant-a-tree"
    "twitter-home-time-line"
    "my-email-shortcode"
    "ymc-crossword"
    "wc-auto-complete-orders"
    "advanced-notifications"
    "ban-double-login"
    "easy-dogecoin-gateway"
    "dashboard-log-monitor"
    "wecpi-ce"
    "fupanet-widget-includer"
    "woo-toolkit"
    "cyprus-pharmacies"
    "wc-unitpay"
    "instant-breaking-news"
    "debug-status-display-footer"
    "wp-scriptcase"
    "maester-toolkit"
    "websuite-push-notifier"
    "follow-self-pings"
    "product-percentage-coupon-woo"
    "wpbom"
    "shortcode-in-title"
    "products-skeleton-loader-free"
    "soundfaith-embed"
    "lh-web-application"
    "wp-mycarousel"
    "sidebar-per-user-role"
    "numly-numbers"
    "png-compress"
    "childpages"
    "disable-post-locking"
    "grecaptcha"
    "fm-notification-bar"
    "cw-show-on-selected-pages-sosp"
    "sendthisfile-button"
    "wangguard-blacklisted-words-add-on"
    "mobile-friendly-mortgage-calculator"
    "wc-ja-ja-pagamentos-multicaixa-express"
    "mygdex-prime-for-woocommerce"
    "remove-css-link-ids"
    "adsinserter"
    "sync-wpforms-jetcrm"
    "you-video-gallery"
    "logo-awesome"
    "apicheck-automatische-adres-aanvulling"
    "wpm-floc"
    "the-travel-button"
    "forms-3rdparty-files"
    "transliterate-arabic"
    "arvancloud-vod"
    "easy-coil"
    "simple-course-creator-updates"
    "twitter-hashtag-blaster"
    "modern-comparison-slider"
    "fast-convertkit"
    "pepro-mapify"
    "phpls"
    "b-reputation-reviews"
    "wordpress-booklooker-bot"
    "gallandbe-wp-tools"
    "wpsitesync-for-http-authentication"
    "wp-promo-emails"
    "project-notebooks"
    "bob-pay"
    "posts-unique-view-counter"
    "ot-twitter-feed"
    "cm-tiktok-feed"
    "remove-media-library"
    "news-list-shortcode"
    "twitter-links"
    "contact-block"
    "custom-wp-zapier"
    "twivatar"
    "pagseguro-internacional-payment-gateway-for-woocommerce"
    "anycomment-analytics"
    "wpum-username-length"
    "figensoft-elektronik-izin-toplama"
    "seo-referrer-link-ping"
    "scheduled-jobs-dashboard-widget"
    "postpage-admin-renamer"
    "azurecurve-series-index"
    "woo-sp-cart-lite"
    "helloify-contact-form-and-live-chat"
    "polls-surveys-contests-and-quizzes-for-pages"
    "bubiblock-slider"
    "material-dashboard"
    "contact-page-with-google-map"
    "coviu-video-calls"
    "wp-featured-menus"
    "zencart-products"
    "quest"
    "genuine-product-checker"
    "autopilot-for-upi-qr-code-payment-gateway"
    "autometa"
    "woo-icon-stock"
    "quick-seo"
    "jd-link-exchange"
    "ceske-komentare"
    "colored-tag-cloud-listing"
    "woo-product-slider-by-pangolin-lite"
    "backend-startpage-customizer"
    "steel"
    "wp-960-grid-system-nasty-shortcodes"
    "woo-display-ebit-banner"
    "coming-soon-free"
    "smarter-analytics"
    "easy-justified-gallery"
    "comment-link-suggest-o-tron"
    "plx-reporting"
    "authpro"
    "ple-repeat"
    "wp-float-admin-menu"
    "partners"
    "dropship-with-wholesale2b"
    "woo-force-coupon"
    "emoji-reaction-rating"
    "squat-radar-calendar-integration"
    "wp-couch-mode"
    "tagged-gallery"
    "contact-form-7-to-rest-call"
    "image-preloading"
    "corrispettivi-for-woocommerce"
    "wc-nova-poshta-for-shop"
    "startbox-easy-hooks"
    "weltenretter-media-copyright"
    "inline-image-base64"
    "oc-studio-integration"
    "simplewp-post-filter"
    "placehodor"
    "bamboo-most-read-posts"
    "private-comment-notification-email"
    "ez-backup"
    "random-image-dashboard"
    "markdown-shortcode"
    "fontsize-selector"
    "wp-javascript-error-logger"
    "sticky-recent-random-posts"
    "easy-content-protector"
    "questionpro-surveys"
    "contact-form-sort-code-selection"
    "csv-to-301-redirects"
    "trackmage-woo-shipment-tracking"
    "wp-sweet-justice"
    "bstats"
    "flexible-cookies"
    "mpcx-accordion"
    "beamtheme-addons"
    "mp-recent-post-widget"
    "iconic-rating"
    "simple-discount-badge"
    "nocacheadmincaats"
    "alternate-mobile-tag"
    "twitter-tools-google-analytics-tagging"
    "ozh-spam-magnet-checker"
    "wp-github-tools"
    "piri-faq-ai-assistant"
    "schgr-commons"
    "double-opt-in-for-cf7"
    "practo"
    "talkino"
    "sk-wp-settings-backup"
    "simple-permissions"
    "emergency-management"
    "cfp-dev-shortcodes"
    "pinterest-scroll-to-top-plugin"
    "topgrade"
    "comic-sans-ftw"
    "blocks-for-products"
    "sendapp-notification"
    "woo-stripe-subscription"
    "filkers-video-marketing-with-your-products"
    "reftagger-shortcode"
    "waffarad-affiliate"
    "advanced-media-button-remover"
    "bbpress-featured-replies"
    "wp-feed"
    "ctc-social-sharing"
    "students-count-for-learndash"
    "site-notices-wp"
    "quick-and-easy-seo-tool"
    "domains-switcher"
    "collaspible-tree-for-making-categories-10"
    "lorem-ipsum-dummy-article-shortcode"
    "trailblaze"
    "aikezi-solutions"
    "uplatnica"
    "admin-shipping-calculator"
    "pryc-wp-google-sitelinks-search-box-snippest"
    "track-kickstarter-project"
    "clean-media-library-file-names"
    "customizer-social-icons"
    "hackadelic-discreet-text-widget"
    "post-flagger"
    "paldrop-dropbox-shop"
    "bank-ifsc-code"
    "add-page-from-template"
    "st-admin-protection"
    "shared-ssl"
    "remove-canonical-urls-for-facebook"
    "monster-pulse"
    "responsive-mini-storage-calculator"
    "accredible-learndash-add-on"
    "post-co-authors"
    "wheel-of-fortune-by-ywp"
    "faq-with-categories"
    "bbp-auto-close-topics"
    "sectionize"
    "ha-background-color-customizer"
    "kingmailer-smtp"
    "chat-telegram"
    "review-map-by-revukangaroo"
    "hide-all-updates"
    "webmicro-payflowpro-woo-addon"
    "additional-measurements-units-for-woocommerce"
    "geo-location"
    "recipe-manager"
    "joget-inbox-widget"
    "hidemein"
    "wn-flipbox-pro"
    "cashfree-quick-button"
    "wen-maintenance-mode"
    "ss-fcm-notifications"
    "w2o-football-fans-admin-color-schemes"
    "simple-footnotes-editor-button"
    "add-media-from-url"
    "envypreloader"
    "simple-twitter-timeline"
    "hikari-krumo"
    "simple-social-media"
    "custom-donations"
    "easy-custom-admin-bar"
    "noor-responsive-tab"
    "digowatchwp"
    "pull-to-refresh"
    "auto-image-title-alt"
    "wrap-google-fonts"
    "svs-shortlink-analytics"
    "add-to-post-footer"
    "latest-post-new"
    "import-csv-and-create-users"
    "wp-ecommerce-redirect-to-checkout"
    "fibre"
    "ninja-mortgage-calculator"
    "postmarkapp-email-integrator"
    "review-for-discount"
    "property-hive-rental-affordability-calculator"
    "wp-private-area"
    "weixin-cloned"
    "tomi-menu"
    "rcr8-widget"
    "page-loading"
    "wp-wapuu-widget"
    "cfs-auto-loop-label"
    "scanfully"
    "webcam-addon-for-contact-form-7"
    "woo-xrp"
    "cazamba"
    "bullet-list"
    "um-profile-form-tutorial"
    "social-analytics-and-content-seo-using-socialears"
    "azurecurve-mobile-detection"
    "solid-performance"
    "disable-blocks-widget"
    "crm-hubspot-learndash-integration"
    "paydirect-fpx"
    "live-video-annotation"
    "woo-animated-grid"
    "jobpress"
    "metronet-embed-google-plus"
    "storytelling"
    "permalink-stop-words"
    "exclude-ips-from-google-analytics"
    "vk-simple-copy-block"
    "standout-content"
    "a-long-time-ago"
    "adunblock"
    "weighted-random-authors"
    "floating-related-posts"
    "quantity-discounts"
    "eight-degree-easy-tags"
    "ace-certificazione-energetica"
    "wp-bolcom-affiliates"
    "headless-single-sign-on"
    "dc-artists"
    "quick-embed-libsyn-podcast"
    "elu-hide-admin-menu"
    "currency-converter-for-woocommerce-paypal-standard"
    "embed-tidal"
    "ultimate-classified-listings"
    "aliffiliate-shortcodes"
    "relative-site-url-on-content-save"
    "contest"
    "disqus-conditional-js-load"
    "elegant-calendar-lite"
    "wc-easynote"
    "wanderlust-autocompletado-del-checkout"
    "wpit-funny-name-generator"
    "zmooz-stories"
    "undo-wordpress-default-formatting"
    "wp-design-awards"
    "embedtweet"
    "simple-web-monetization-by-interledger"
    "mwr-hit-counter"
    "custom-index-shortcode"
    "user-last-visit"
    "jkl-timezone-converter"
    "woo-yuansfer"
    "storegrowth-sales-booster"
    "lh-add-headers"
    "wpjbm-application"
    "touchbase-mail-subscribe-form"
    "hostfact-bestelformulier-integratie"
    "woocommerce-zaakpay-payment-gateway"
    "bstabs"
    "http-urls"
    "showtweets-plugin"
    "wp-enviroment-beacon"
    "conversion-tool-by-convkit"
    "oer-curriculum"
    "thorium-extension"
    "ac-addon-members"
    "fetch-tweets-hashtag-cloud"
    "project-donations"
    "pretty-table-of-contents-for-elementor"
    "woo-hide-options"
    "pec-cod-sdi-p-iva-cf-for-woocommerce"
    "discreet-toolbar"
    "where-used"
    "countdown-to-force-logout"
    "surplus-essentials"
    "bbcode-annotator"
    "supercharts"
    "floating-cart-product-for-woocommerce"
    "atp-chatbot"
    "watu-bridge-to-mailchimp"
    "simple-recent-posts-widget"
    "aim-style-vault"
    "elmo-privacylab"
    "user-agent-body-class"
    "product-role-rules"
    "software-sales-prices"
    "wp-smtp-mailer"
    "acelerator"
    "um-wp-user-frontend"
    "official-easymailing"
    "bible-plus"
    "concordancia-de-la-biblia"
    "seo-repair-kit"
    "photo-roll"
    "treweler-map-builder"
    "cycle-responsive-slider"
    "chasee-xact-payment-gateway-for-woocommerce"
    "startklar-image-optimizer"
    "archivescode-addons-for-elementor"
    "show-theme-in-footer"
    "arrivala-online-business-reviews"
    "advanced-social-media-icons"
    "latest-post-link"
    "ni-order-filter-for-woocommerce"
    "smtpcom"
    "memorialday"
    "materialize-accordions"
    "preview-posts-everywhere"
    "dyslexic-fonts"
    "kv-send-email-from-admin"
    "zeaks-code-snippets"
    "jays-wordpress-admin-plugin"
    "wordpress-link-ranker"
    "easypayway-is-a-bangladeshi-payment-gateway-with-the-woocommerce-plugin"
    "login-with-donbaler-oauth"
    "vikmailsmtp"
    "hockeydata-los"
    "deployer-for-git"
    "category-parent-children-selector"
    "barcode-generator"
    "simple-page-hierarchy-widget"
    "loyalty-discounts-for-woocommerce"
    "critical-net-fraud-prevention"
    "mu-central-taxonomies"
    "passwordless"
    "spice-faq"
    "woo-phone-number-required"
    "wp-privacy"
    "enduring-word-bible-commentary"
    "audio-record"
    "mijnpress-onderhoud"
    "post-events"
    "china-super"
    "gfb-author-bio-widget"
    "html5ify-for-wp"
    "uors-external-course-list"
    "gdpress"
    "boot-slider"
    "fvote"
    "nova-dashboard-widget-bbc-news"
    "muse-ai"
    "forms-for-divi"
    "cocart-jwt-authentication"
    "metabackground"
    "qr-invoice"
    "metathesis"
    "lh-custom-dashboard"
    "simple-phpexcel-export"
    "advanced-h2h-for-sportspress"
    "wp2html"
    "resource-library"
    "htm-and-underscores-on-pages-and-post"
    "kdk-wprakuten"
    "widget-dashboard-for-elementor"
    "customize-post-title"
    "prerender-and-prefetch"
    "canto-testimonials"
    "sidebar-content-from-shortcode"
    "pricing-table-free"
    "oganro-dialog-ezcash"
    "theme-stats-view"
    "fastbots-ai-chatbots"
    "mighty-frequently-bought-together"
    "rex-sync"
    "ecomatcher-for-woocommerce"
    "callout-block"
    "cf7-notie"
    "wp-set-featured-image-from-content"
    "url-parameter-shortcode"
    "block-ecommerce-assets-via-robots-txt"
    "virtual-product-checkout-fields-manager"
    "vgw-vg-wort-zahlpixel-plugin"
    "atoz-sorting"
    "pixopoint-code-comments"
    "my-appeal"
    "bibliodam-connect"
    "coming-soon-by-boomdevs"
    "redirect-homepage-after-login"
    "ph-protection"
    "secure-content"
    "wpicnik"
    "gravity-forms-help-scout-search"
    "audio-video-download-buttons-for-youtube"
    "acf-fields-repeater-collapser-admin"
    "bw-posts-top"
    "dlbs-send-a-link"
    "wp-pingpreserver"
    "custom-private-post"
    "pdf-widget"
    "cocolis"
    "email-signature-manager"
    "er-swiffy-insert"
    "wp-use-parent-template"
    "ngs-js-salat-times"
    "html-helpers"
    "ldap-wp-login-integration-with-active-directory"
    "uthsc-wpcas"
    "wp-payhip-integration"
    "phonepe-checkout-solutions"
    "kirchenjahr-evangelisch"
    "wp-pusher-slack-notifications"
    "textblox"
    "wp-page-links"
    "remove-posts-from-admin"
    "nifty-newsletters-woocommerce-subscriptions"
    "creative-tim-rotating-css-cards"
    "qtop"
    "zerys-writer-marketplace"
    "login-page-ui-customizer"
    "recooty"
    "mobile-only-contact-footer"
    "yt-sticky-video"
    "wp-cursbnr"
    "smart-wp"
    "pensopay-checkout-terms-subscriptions"
    "nuntium"
    "wp-click2client"
    "jkl-pricing-tables"
    "zyx-classical-circular-clock"
    "display-all-image-file-path"
    "wall-paint-calculator"
    "campuspress-theme-check"
    "hatena-connect"
    "limelight-forms"
    "thecartpress-australian-states"
    "skyrock-blog-importer"
    "cpm-all-in-one-responsive-poll"
    "simple-popup-block"
    "r-scroll-up"
    "realtycandy-idx-broker-extended"
    "easy-maintenance"
    "wp-author-status"
    "wp-multitarget-uploads-sync-tool"
    "unique-comment-notify"
    "elokenz-most-shared-articles-for-authors"
    "ali2woo-migration-tool"
    "display-reusable-blocks"
    "lgv-anmeldesystem"
    "bbp-valoration"
    "iwd-woocommerce-checkout-suite"
    "bh-faq"
    "dh-new-mark"
    "hide-wp-admin-login"
    "vignete-ads"
    "nestscale-tiktok-pixel-tiktok-ads"
    "our-geolocation"
    "ccavenue-payment-gateway-woocommerce-integration-kit"
    "wp-user-timezone"
    "bh-pricing-table"
    "oxygridlayout-by-oxyninja"
    "pzz-api-client"
    "bx-slider-by-trs"
    "ak-bootstrap-faq"
    "chromeless-widgets-page"
    "amazon-wishlist-pro"
    "wp-easy-sharer"
    "categories-sidebar"
    "quiits-call-me-back-widget"
    "post-tag-automaton"
    "newcarnet-news"
    "fire-fighter-dumpster-online"
    "acf-simple-cache"
    "mass-page-creator"
    "get-custom-content"
    "brickset-api"
    "custom-error-messages-for-gravityforms"
    "funraise-donation-form"
    "post-duplicator-plus"
    "wp-veloce"
    "find-your-reps"
    "video-connect"
    "wp-images-upload-on-piclect"
    "twocolcats"
    "backdrop-post-types"
    "wpant-coupons-pay-for-shipping-woocommerce"
    "fix-gravatar-alt-text-title-tag"
    "my-pricing-table"
    "woo-sale-product-date-info"
    "bonjoro"
    "the-force"
    "mycred-learndash-points-importer"
    "admin-bar-plugin-switcher"
    "ztr-zeumic-work-timer"
    "hex-coupon-for-woocommerce"
    "honeypot-for-forminator-form"
    "scheduled-contents-shortcode"
    "basepress-oxygen-integration"
    "contractor-commerce-integration"
    "firmao-livechat"
    "wc-spoddano"
    "lowermedia-wp-social"
    "zip-embed"
    "lastmal-shipping-for-woocommerce"
    "star-rating-field-for-contact-form-7"
    "securepay-for-fluentforms"
    "mighty-captcha"
    "fancy-latest-post-widget"
    "compare-products-for-woocommerce"
    "json-data-feed"
    "presslabs-site-protection"
    "advanced-db-cleaner-mk"
    "remove-parent-category-from-slug"
    "rest-api-guard"
    "wp-read-time"
    "archive-posts-accordion-panel"
    "hr-performance"
    "radio-islam-indonesia"
    "template-seo-checker"
    "tags-to-meta"
    "woo-compra-directa"
    "levelup"
    "fetchurl"
    "ni-woocommerce-product-editor"
    "scroll-recent-comments"
    "service-for-multi-vendor-auction"
    "contact-form-7-mail-conditions"
    "walktheweb"
    "web-screenshort"
    "browser-title-bar-animation"
    "woo-ik-manufacturer"
    "essential-foto-just-for-jetpack"
    "twentyten-options"
    "mqtranslate-separate-comments"
    "a-year-ago-today"
    "fsm-backend-category-organizer"
    "quadmenu-megamenu"
    "mailchimp-shortcode"
    "querlo-chatbots"
    "simple-course-creator-front-display"
    "wp-theme-update"
    "infogeek-admin-themes"
    "dadevarzan-wp-gallery"
    "linkz-ai"
    "search-exclude-html-tags"
    "footer-shortcodes"
    "eu-tube-user-privacy"
    "banner-slider-for-advertisement"
    "wp-boyka"
    "retrospective"
    "geodigs"
    "advanced-visual-elements"
    "novas-gallery"
    "powerfm-radyo"
    "image-display-control"
    "automatic-cache-flusher-for-w3-total-cache"
    "abtesting-ai"
    "carousel-glider-js"
    "thaana-wp"
    "asterisk-web-callback"
    "wp-bmi"
    "dj-player"
    "marquee-elementor"
    "user-info-in-email-for-contact-form-7"
    "login-page-style"
    "bebetter-social-icons"
    "survey-maker-lite"
    "combidesk-yuki"
    "front-page-exclude-by-date"
    "dynamic-page-content"
    "wp-email-restrictions"
    "power-blocks"
    "datalistit"
    "extra-authors-redirect"
    "snowfall"
    "naoca"
    "disable-contect-editor-for-specific-template"
    "pymseo"
    "woolook"
    "improved-gd-image-editor"
    "sqltable"
    "netflix-buttons"
    "simple-event-listing"
    "acf-url-field-add-on"
    "easy-scroll-to-top"
    "woo-postmates-integration"
    "similar-posts-ai-spai"
    "small-business-loan-calculator"
    "amp-non-amp-auto-ads"
    "fix-paging"
    "wp-reposidget"
    "qqworld-checkout-lite"
    "tedtalks-for-wordpress"
    "tabber"
    "wp-sos-donate"
    "custom-pc-builder-lite-for-woocommerce"
    "pausar-3d-ar-for-elementor"
    "per-product-flat-rate-shipping-for-wc"
    "apple-meta-tags"
    "email-signup-for-link"
    "embed-odnoklassniki-video"
    "twittada"
    "var-dumper"
    "change-title"
    "woo-product-carousel-2"
    "amplitude"
    "visody-3d-product-viewer"
    "flexible-blogtitle"
    "states-and-municipalities-of-venezuela-for-woocommerce"
    "simpleschema-free"
    "wp-chatbull"
    "tooltips-for-gravity-forms-free"
    "terminal-block"
    "stand-ukraine"
    "kahaf-kit"
    "harlem-shake"
    "posts-to-events"
    "maximum-comment-length"
    "children-content-shortcode-plugin"
    "ecgf-registration"
    "tier-management-petfinder"
    "secuplug"
    "nofollow-archives"
    "tyntcom-for-wordpress"
    "defer-transictional-emails-for-woocommerce"
    "monnify-payment-gateway"
    "htaccess-ip-blocker"
    "premium-addons-for-kingcomposer"
    "simple-htaccess-redirects"
    "small-caps"
    "epoch-timelines"
    "beans-visual-hook-guide"
    "fmtc-pods"
    "transmit-sms-share"
    "flickree"
    "woo-lock-downloads-to-ip"
    "b-chart"
    "frm-modal"
    "sackson-web-data"
    "woo-3d-secure-bankart-payment-gateway"
    "wp-marktplaats"
    "azurecurve-rss-suffix"
    "failed-login-firewall"
    "embed-peertube-playlist"
    "remove-custom-fields-metabox"
    "wp-maintenance-switch"
    "ultra-mouse-tail"
    "rest-filter-response-fields"
    "voce-widget-cache"
    "sales-page-addon"
    "soj-soundslides"
    "bws-adsense"
    "aspiesoft-auto-embed"
    "technical-on-page-seo-checker"
    "wpfront-paddle-gateway"
    "content-connector-by-contenidosclick"
    "nook-color-widget"
    "incomment-referrer"
    "posts-screen-excerpt"
    "post-countdown"
    "scroll-up-sticky-header-for-total"
    "optimize-more-css"
    "wp-fossil"
    "woo-badge"
    "unwrap-images"
    "bizsugar-vote-button"
    "call-tracker"
    "icon4menu"
    "full-screen-galleries"
    "upload-directory-cleaner"
    "disable-email-notifications-for-new-user-registration"
    "gus-api-nip24pl"
    "wp-testimonial-carousel"
    "dynamic-contact-info"
    "trackdesk-for-woocommerce"
    "gf-payment-continue"
    "surbma-secure-login"
    "snack-missed-schedule"
    "remove-wordfence-2fa"
    "gifty-for-woocommerce"
    "nwa"
    "cactus-social-feeds"
    "pr-wpcf7-locaweb"
    "lmc-xml-reader"
    "gallerygrid"
    "wp-ldp"
    "save-me"
    "wp-smart-analytics"
    "small-archives"
    "wpit-blog-stats"
    "bmi-wrong-image-link-fix"
    "multiupload-in-custom-taxonomy"
    "courier-address"
    "jetpack-holiday-snow-opt-in"
    "frontype"
    "site24x7-rum"
    "ada-tray-accessibility-widget"
    "custom-fields-as-meta-tags"
    "wp-txt-sitemap"
    "clearsale-total"
    "beden-kitle-hesaplama"
    "affiliate-codecanyon-widget"
    "my-posts"
    "limelight-checkout"
    "disable-magpie-rss-cache"
    "mycred-badgr-achievement-badge"
    "hijri-date"
    "rajce"
    "trusty-woo-products-filter"
    "definitions-internal-linkbuilding"
    "are-you-sure"
    "wp-tweet-this-button"
    "newsletters-from-rss-to-email-newsletters-using-nourish"
    "ubecube-3d-widget"
    "code-analyzer"
    "omnisend-for-gravity-forms-add-on"
    "smoothscroll"
    "copycraft"
    "elementary-addons"
    "wp-similar-basic-auth"
    "smart-social-pack"
    "ninja-forms-unique-textbox"
    "enhanced-ecommerce-plus-easy-digital-downloads"
    "remove-html-editor-from-admin-dashboard"
    "wp-firewall"
    "insert-this-intelligent-content-inserts"
    "lh-browser-shots"
    "publishing-conditions"
    "opizo"
    "wp-feedmail"
    "phonegap-connect"
    "tdc-digital-payment-gateway"
    "case-insensitive-passwords"
    "embed-wistia-vid"
    "stitchz-social-login"
    "buy-him-a-beer"
    "wp-missing-functions"
    "lazy-image-load"
    "simple-csv-exporter"
    "remove-footer-links"
    "shipink"
    "animated-text"
    "gimme-calendar-feeds"
    "adminbar-no-customizer"
    "related-king-pro"
    "sleek-author-box"
    "wp-admin-bar-new-tab-pp"
    "escape-rooms"
    "nk-progress-counter-block"
    "wp-speed-booster"
    "lh-jetpack-related-posts"
    "classy"
    "svs-quiz-survey-contact"
    "nice-scrollbar"
    "wc-products-pack"
    "nocks-nifty-for-woocommerce"
    "dynamic-currency-converter"
    "latest-post-shortcode-link"
    "smart-threema"
    "wp-meetup-activity"
    "urwa-for-dokan"
    "daecolor"
    "woocommerce-backorders-report"
    "uvc-digital-clock"
    "support-my-work"
    "stories-post-type"
    "plugins-deactivator"
    "clickback-web-tracker"
    "customizer-responsive-device-preview"
    "addon-package-for-elementor"
    "wp-readability-analysis"
    "wc-my-statistics"
    "tsp-authors-note"
    "sinon-bangumi-list"
    "wa-fronted"
    "sortable-amazon-wishlist"
    "mw-wp-form-kintone"
    "seo-remove-h1"
    "postmenu"
    "ks-contact-widget"
    "seo-permalinks-modifier"
    "smart-testimonials"
    "airport-transfers"
    "jane-menu"
    "pawboost-lost-and-found-pets"
    "comparis-price-comparison-system-woocommerce"
    "wp-month-calendar"
    "viralparsecom-viral-link-creator"
    "related-images"
    "comment-refs"
    "amazing-service-box-visual-composer-addons"
    "custom-strava-integration"
    "statistical"
    "max-adsense"
    "breadcrumb-navigation-for-seo-with-microdata"
    "ipod-widget"
    "amenities-plugin"
    "freshbooks-wordpress-widget"
    "wp-go-maps-block"
    "wc-casys-payment"
    "wp-youtube-embed"
    "nz-wechat-qr-code-support-chat"
    "author-rss-feed"
    "content-for-your-country"
    "game-dev-quotes"
    "hiweb-core"
    "syntax-highlighter-prismjs"
    "cf7-element-converter"
    "hover-effects-with-lightbox-vc-extension"
    "gcal-days"
    "musicacloud-shortcodes"
    "wp-slug-baidu-translate"
    "prelauncher"
    "woo-virtualcoin-services-gateway"
    "aiify"
    "event-codes"
    "convert-speech-to-text-as-post"
    "aazeen-extension"
    "c4d-woo-cart-icon"
    "1337-social-sharing"
    "cf7-datalist"
    "secure-http-headers"
    "uptain-connect"
    "office-locator"
    "nutsforpress"
    "smart-pwa"
    "duecom-e-commerce-payment-gateway"
    "conditional-lightbox"
    "noindex-password-protected-posts"
    "zenost-shortcodes"
    "rename-author-slug"
    "gravity-forms-enhancements"
    "base-shortcode-for-bootstrap"
    "wp-plugin-packer"
    "controlled-content-block"
    "magiclabs"
    "acf-5-pro-json-storage"
    "woo-new-product-info"
    "squidge"
    "talkie-text-to-speech"
    "statvoo"
    "groups-members-mail"
    "two-columns-archive"
    "micro-contact-form"
    "iran-agency-map"
    "templets"
    "easy-accordion-posts"
    "woot-library"
    "personalization-by-flowcraft"
    "server-information"
    "tci-ultimate-element-themes"
    "admin-php-eval"
    "yatko-coronavirus"
    "ace-user-management"
    "onlinemenukaart"
    "jvm-details-summary"
    "wp-shortlinks"
    "advanced-wp-rest-api"
    "cb-facebook-like-box"
    "woo-freecharge"
    "user-notes-for-bbpress"
    "ignore-menu-items"
    "ace-twilio-for-woocommerce"
    "connect-contact-form-7-to-constant-contact-v3"
    "captionfixer"
    "magic-slider"
    "prospect"
    "product-categories-search-admin-for-woocommerce"
    "responsive-divi-candy"
    "advanced-activecampaign-site-tracking"
    "disable-styles-scripts"
    "bhm-random-quote"
    "filogy-invoice"
    "cart-reset"
    "awesome-wp-comment-rating"
    "redirectify"
    "eventbee-ticketing-widget"
    "lcs-security"
    "adventure-bucket-list"
    "get-in-line"
    "simple-twitter"
    "csv-me"
    "wp-issuetracker"
    "fazbuzz"
    "wp-product-selector"
    "integrate-dropbox"
    "masoffer-product-listing"
    "aati-wp-finetuning"
    "wpmultimediabridge"
    "simple-2fa"
    "back-list"
    "eu-tyre-label-shortcode"
    "netatmosphere"
    "health-and-medical-addons-for-kingcomposer"
    "uniform-js"
    "google-badge"
    "suggest-review"
    "online-appointment-scheduling-software"
    "bi-button-changer"
    "bg-book-publisher"
    "decon-character-counter"
    "ni-woocommerce-customer-product-report"
    "select-to-share"
    "remita-payment-gateway-for-easy-digital-downloads"
    "mahjong-tiles"
    "docubot"
    "topup-africa-widget"
    "fx-calculators"
    "wp-disable-block-editor"
    "alerts-dlx"
    "sidepost"
    "wp-trovaprezzi"
    "cookie-dynamic-tag-for-elementor"
    "media-library-shortcode"
    "rsh-tweet-button"
    "a-sub-site-teaser-widget"
    "avatarplus"
    "colourpress-colourlovers-widget"
    "single-page-pagination"
    "autolisticle-automatically-update-numbered-list-articles"
    "days-ago-post-date-format"
    "advanced-custom-widget"
    "disable-downloadable-repeat-purchase-woocommerce"
    "https-links-in-content"
    "wp-xperts-woocommerce-custom-thank-you-page"
    "invalidate-logged-out-cookies"
    "storagemadeeasy-multicloud-files-backup"
    "security-txt-manager"
    "scripts-removal-for-contact-form-7"
    "clone-gravity-form-entry"
    "editor-cleanup-for-wpbakery"
    "alixcan-canli-yayin-eklentisi"
    "mathilda"
    "x-config-cim-starter-edition"
    "css-live-reload"
    "pardot-marketing"
    "statsfc-squad-selector"
    "simple-google-fonts"
    "simple-google-share"
    "nimbata-call-tracking"
    "anti-hacker"
    "custom-post-types-bubbles"
    "arabic-to-lat"
    "really-simple-maps"
    "wattv-embed"
    "wp-security-by-made-it"
    "paylado-gateway"
    "mb-topbar"
    "servermonitor"
    "zhanzhangb-share"
    "woo-westpac-payway-payment-gateway"
    "intelliwidget-elements"
    "before-its-news-health"
    "wp-notifications-manager"
    "datamafia-dash-note"
    "pbp-dashboard-widget-cleaner"
    "baw-better-plugin-managment"
    "zola-crm-add-on-for-gravity-forms"
    "assist24it"
    "geo-captcha-geo-blacklist"
    "pingfm-status"
    "remove-jquery"
    "turn-off-rest-api"
    "gallery-and-lightbox"
    "elemendas-addons"
    "pop-up-block"
    "content-holders"
    "sort-recently-active-plugins"
    "simply-disable-password-reset"
    "language-switcher-popup"
    "pageone"
    "simple-page-widget"
    "kittens-for-comments"
    "smart-donations-stripe"
    "bakrypt-blockchain-extension"
    "hotel-bookings-progress-bar-for-motopress"
    "remove-special-characters-on-upload"
    "text-modules"
    "easy-banner-link"
    "coupon-zen"
    "instant-translate-widget"
    "dbug"
    "klout-score-badge"
    "lightweight-branded-login-screen"
    "ctcl-image-gallery"
    "reset-password-removed"
    "u-tweets"
    "nps-monitoring"
    "integration-of-zoho-crm-and-wpforms"
    "wp-spacecontent"
    "advance-guest-post"
    "dilmot-live-qa-chats"
    "incilinfo"
    "simple-clone-widget"
    "wp-cookies-enabler"
    "qr-code-management"
    "woo-cielo-boleto"
    "cp-testimonial"
    "os-image-gallery"
    "logistiq-shipping"
    "reject-urls-and-emails-in-textarea"
    "thueapi-thanh-toan-don-gian-voi-he-thong-tu-dong"
    "cb-lost-password-remover"
    "data-source-civicrm-api-for-wpdatatable"
    "url-based-login"
    "current-weather-widget"
    "wp-quick-image"
    "awesome-twitter-feeds"
    "simple-amazon-affiliate"
    "lazy-moderator"
    "defaults-for-buddypress-docs"
    "avoid-repeating-posts"
    "wp-number-of-items-per-page"
    "wp-bootstrap-comments"
    "kledo"
    "image-exif"
    "lazy-lorem-ipsum"
    "rs-diwali-lantern"
    "stripe-political-donations"
    "cloudup-oembed"
    "duzz-seo"
    "administrator-access-to-pmpro-protected-content"
    "cbrrate"
    "nasa-astrology-picture-of-the-day"
    "post-type-comments-for-mycred"
    "advanced-wp-testimonial"
    "a2reviews"
    "oi-frontend-profile"
    "wc-first-data-payment-gateway"
    "check-google-result"
    "wp-ajax-social"
    "easy-photo-album-latest-photos"
    "post-seo-score-checker"
    "wuunder-dynamic-checkout"
    "all-in-one-demo-importexport"
    "postqueue"
    "stop-living-in-the-past"
    "simpul-forms-by-esotech"
    "section-builder-block"
    "remove-site-icon"
    "post-auto-vertical-scrolling"
    "video-youtube-lightbox"
    "rtl-support-for-oxygen-builder"
    "ubiliz-boutique-cadeau"
    "contact-us-bottom-bar"
    "text-snipper"
    "hide-title-post-page"
    "wp-modore"
    "netpay-hosted-form-for-woocommerce"
    "blogfollow"
    "wodhopper"
    "responsive-attention-box"
    "urban-insight-promobar"
    "download-monitor-cors"
    "sherloq"
    "mourning"
    "woo-email-orders"
    "cf7-responses"
    "wc-hub"
    "aw-simple-sorter"
    "css-and-js-enqueuer"
    "pageapp"
    "ag-wp-jalali"
    "trafficguard"
    "widget-builder-for-elementor"
    "scheduled-unsticky"
    "predict-when"
    "irecharge-widget"
    "fpg-endereco-automatico-por-cep-no-checkout"
    "connect-learnpress-discord-add-on"
    "profile-links"
    "siris-loginlogout-redirect"
    "alobaidi-slider"
    "repeater-for-gravity-forms"
    "recently-purchased-product-display-for-woocommerce"
    "better-wp-login-page"
    "now-reading-admin-bar-menu"
    "bp-extend-groups-fields"
    "bvd-easy-social-feeds-images"
    "ultimate-membership-pro-razorpay"
    "woo-gkash"
    "title-tag-everts-simple-version"
    "qr-code-hoerandl"
    "eso-widgets"
    "gs-gomobi-redirector"
    "buddypress-update-email-reminder-lightbox"
    "yd-spread-parameter"
    "author-wordcount"
    "billplz-for-edd"
    "captain-countdown-clock"
    "twitter-expander"
    "ccg-manager"
    "buddypress-admin-access-activity"
    "rewatch-oembed-wp"
    "sugar-calendar-wp-all-import"
    "mlsp-media-embed"
    "plzshareme-url-shortener-viral-booster"
    "blogbus-importer"
    "mytwitterfeed"
    "birthday-mails-bp"
    "credit-calc"
    "network-user-management"
    "updates-to-slack"
    "home-affordability-calculator"
    "gravatar-seo"
    "tars-chatbot"
    "woocommerce-e-mail-login"
    "starboard-suite-reservation-calendars"
    "radio-taxonomy"
    "simple-cache-killer"
    "penanggalan-hijriyah-masehi"
    "nova-poshta-declarations"
    "getback-optimize-web-push-notifications"
    "autoptimize-admin-bar-fix"
    "literal-shortcode"
    "dreamhost-affiliates"
    "wp-paypal-donate"
    "importdoc-block"
    "api2cart-live-shipping-4-woocommerce"
    "image-placeholder"
    "abs-portfolio"
    "twentyfifteen-noto-sans-jp"
    "print-flyers-lite"
    "pushloop"
    "malaysia-prayer-times"
    "authorcomments"
    "restful-hello-dolly"
    "exclude-pages-from-search-results"
    "distance-calculator-by-avtodispetcherru"
    "roles"
    "mind-body-api-integration"
    "latest-tweets-tooltip"
    "woo-product-disable"
    "easy-digital-downloads-coinpayments-gateway"
    "obselling"
    "read-more-buddy"
    "bildquellen-copyright-statement"
    "hide-front-end-wp-admin-bar"
    "juicy-contact-button"
    "fixed-adjacent-post"
    "admin-bar-in-fullscreen-mode"
    "stalkfish"
    "credit2caption"
    "private-file-for-woocommerce"
    "visual-email-builder"
    "languages-frontend-display"
    "seamless-slider"
    "auction-feed"
    "disable-dns-prefetch"
    "wc-cointopay-com"
    "only-rest-api"
    "invoices-by-customer-347"
    "buton-de-follow"
    "wp-social-integration"
    "artifakt-hashtags"
    "svg-enabler"
    "floorplans"
    "doubles-rotation-tournament"
    "ob-db-excel-converter"
    "woo-category-post-widget"
    "conveyancing-quote-calculator"
    "woo-product-boxes"
    "social-traffic-commando"
    "backgammon"
    "signature-notification"
    "event-organiser-vat"
    "wp-share"
    "isimpledesign-clicktell-text-message"
    "woocommerce-extender"
    "youtube-share-overlay-buttons"
    "online-reviews-io"
    "career-builder-jobsearch"
    "christmas-blocks"
    "florapress"
    "budgetmailer-sign-up-form"
    "processingjs-code-directly"
    "regallery"
    "portugal-vasp-kios-woocommerce"
    "members-only-post-type"
    "hg3-include"
    "exchange-addon-add-product-sku"
    "cpt-magic-tool-addons-for-elementor"
    "zestard-product-size-chart"
    "jigoshop-coupon-products"
    "anytimereply"
    "menu-option"
    "flipster"
    "qsd-owl-slider"
    "covid-19-live-tracker"
    "csh-multiscroll"
    "developer-toolbar"
    "exclusive-content-shortcode"
    "clock-tik-tik"
    "hotelrunner"
    "curbside-pickup"
    "microdata-about"
    "jquery-enabler"
    "soundbeat-widget"
    "advanced-concurrent-login-limit"
    "set-aside"
)

# Define user agents with weights
declare -A USER_AGENTS
USER_AGENTS=(
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"]=5
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"]=7
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"]=6
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36 Edg/91.0.864.54"]=5
    ["Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 OPR/77.0.4054.277"]=3
    ["Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (iPad; CPU OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Vivaldi/4.0"]=1
    ["Mozilla/5.0 (Android 11; Mobile; rv:68.0) Gecko/68.0 Firefox/88.0"]=1
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"]=15
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/534.36"]=12
)

OPENED_PLUGINS_FILE="${WORDPRESS_WORKDIR}/opened_plugins.txt"
CLOSED_PLUGINS_FILE="${WORDPRESS_WORKDIR}/closed_plugins.txt"
LAST_VERSION_FILE="${WORDPRESS_WORKDIR}/last_versions.txt"
PARALLEL_JOBS=1

DOWNLOAD_ALL_PLUGINS='n'
LIST_ONLY='n'
ALL_PLUGINS_FILE="${WORDPRESS_WORKDIR}/wp-plugin-svn-list.txt"

DELAY_DOWNLOADS='n'
DELAY_DURATION=5

FORCE_UPDATE='n'
CACHE_ONLY='n'

mkdir -p "$WORDPRESS_WORKDIR" "$MIRROR_DIR" "$LOGS_DIR"
rm -f "$OPENED_PLUGINS_FILE"
touch "$OPENED_PLUGINS_FILE"
DEBUG_MODE=0

while getopts "p:dalD:t:fc" opt; do
    case ${opt} in
        p ) PARALLEL_JOBS=$OPTARG ;;
        d ) DEBUG_MODE=1 ;;
        a ) DOWNLOAD_ALL_PLUGINS='y' ;;
        l ) LIST_ONLY='y' ;;
        D ) DELAY_DOWNLOADS=$OPTARG ;;
        t ) DELAY_DURATION=$OPTARG ;;
        f ) FORCE_UPDATE='y' ;;
        c ) CACHE_ONLY='y' ;;    # New option for cache-only
        \? ) echo "Usage: $0 [-p PARALLEL_JOBS] [-d] [-a] [-l] [-D DELAY_DOWNLOADS] [-t DELAY_DURATION] [-f] [-c]" 1>&2; exit 1 ;;
    esac
done

debug_log() {
    if [ "$DEBUG_MODE" -eq 1 ]; then
        echo "[DEBUG] $1" >&2
    fi
}

get_random_user_agent() {
    echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
}

get_latest_version_and_download_link() {
    local plugin=$1
    debug_log "Checking latest version and download link for $plugin"
    
    local api_url="https://api.wordpress.org/plugins/info/1.0/${plugin}.json"
    local user_agent=$(get_random_user_agent)
    local api_response=$(curl -s -H "User-Agent: $user_agent" "$api_url")
    
    if echo "$api_response" | jq -e '.error' >/dev/null; then
        local error_message=$(echo "$api_response" | jq -r '.error')
        if [ "$error_message" = "closed" ]; then
            echo "closed"
            return 2
        else
        echo "Error: $error_message for plugin $plugin" >&2
        return 1
        fi
    fi
    
    local version=$(echo "$api_response" | jq -r '.version // empty')
    local download_link=$(echo "$api_response" | jq -r '.download_link // empty')
    
    if [ -n "$version" ] && [ -n "$download_link" ]; then
        echo "$version $download_link"
        return 0
    else
        echo "Error: Cannot fetch version or download link for $plugin" >&2
        return 1
    fi
}

download_plugin() {
    local plugin=$1
    local version=$2
    local api_download_link=$3
    local output_file="${MIRROR_DIR}/${plugin}.${version}.zip"
    local header_file="${LOGS_DIR}/${plugin}.${version}.headers"
    local constructed_download_link="${DOWNLOAD_BASE_URL}/${plugin}.${version}.zip"
    local download_link

    if [ "$DEBUG_MODE" -eq 1 ]; then
        debug_log "API-provided download link for $plugin: $api_download_link"
        debug_log "Constructed download link for $plugin: $constructed_download_link"
    fi

    if [ "$DOWNLOAD_LINK_API" == 'y' ] && [ -n "$api_download_link" ]; then
        download_link="$api_download_link"
        debug_log "Using API-provided download link for $plugin: $download_link"
    else
        download_link="$constructed_download_link"
        debug_log "Using constructed download link for $plugin: $download_link"
    fi

    debug_log "Downloading $plugin version $version through Cloudflare Worker"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)
    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o /dev/null "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    else
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o "$output_file" "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    fi

    if [ $? -eq 0 ]; then
        if [ "$CACHE_ONLY" == 'y' ]; then
            debug_log "Plugin $plugin version $version cached successfully."
            return 0
        fi

        local file_size=$(stat -c%s "$output_file")
        if [ "$file_size" -lt 1000 ]; then
            echo "Error: Downloaded file for $plugin is too small (${file_size} bytes). Possible download issue." >&2
            return 1
        fi

        local source=$(grep -i "X-Source:" "$header_file" | cut -d' ' -f2 | tr -d '\r')
        if [ "$source" == "R2" ]; then
            debug_log "Successfully downloaded $plugin version $version from R2 storage"
        elif [ "$source" == "WordPress" ]; then
            debug_log "Successfully downloaded $plugin version $version from WordPress"
            debug_log "R2 bucket saving for plugin zip occurred"
        else
            debug_log "Skipped download for $plugin $version zip (already exists locally)"
        fi

        return 0
    else
        echo "Error: Failed to download $plugin version $version" >&2
        return 1
    fi
}

save_plugin_info() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.json"

    debug_log "Saving plugin json metadata for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying metadata download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    if [ "$CACHE_ONLY" == 'y' ]; then
        # When in cache-only mode, output to /dev/null
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin metadata for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache json metadata for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            if [ "$source" = "R2" ]; then
                debug_log "json metadata for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "json metadata for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin json occurred"
            else
                debug_log "json metadata for $plugin version $version saved (json metadata file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save json metadata for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

fetch_and_save_checksums() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.checksums.json"

    debug_log "Fetching and saving checksums for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying checksums download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    debug_log "Sending request to Worker for checksums: CF_WORKER_URL?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"

    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin checksums for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache checksums for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        debug_log "Received response with status code: $status_code"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            debug_log "Response source: $source"
            if [ "$source" = "R2" ]; then
                debug_log "Checksums for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "Checksums for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin checksums occurred"
            else
                debug_log "Checksums for $plugin version $version saved (checksums file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save checksums for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

process_plugin() {
    local plugin=$1

    # Check if the plugin is already known to be closed
    if grep -q "^$plugin$" "$CLOSED_PLUGINS_FILE" 2>/dev/null; then
        echo "Plugin $plugin is known to be closed. Skipping."
        return 0
    fi

    echo "Processing plugin: $plugin"

    VERSION_AND_LINK=$(get_latest_version_and_download_link "$plugin")
    local version_check_status=$?
    
    if [ $version_check_status -eq 1 ]; then
        echo "Skipping $plugin due to version fetch error."
        return 1
    elif [ $version_check_status -eq 2 ]; then
        echo "Plugin $plugin is closed. Skipping download and processing."
        echo "$plugin" >> "$CLOSED_PLUGINS_FILE"
        if save_plugin_info "$plugin" "closed"; then
            debug_log "Successfully saved json metadata for closed plugin $plugin."
        else
            debug_log "Failed to save json metadata for closed plugin $plugin."
        fi
        return 0
    fi
    
    LATEST_VERSION=$(echo "$VERSION_AND_LINK" | cut -d' ' -f1)
    API_DOWNLOAD_LINK=$(echo "$VERSION_AND_LINK" | cut -d' ' -f2-)

    debug_log "Latest version for $plugin: $LATEST_VERSION"
    debug_log "API download link for $plugin: $API_DOWNLOAD_LINK"

    STORED_VERSION=$(grep "^$plugin" "$LAST_VERSION_FILE" | awk '{print $2}')
    debug_log "Stored version for $plugin: $STORED_VERSION"

    if [ "$CACHE_ONLY" != 'y' ] && [ "$LATEST_VERSION" == "$STORED_VERSION" ] && [ -f "${MIRROR_DIR}/${plugin}.${LATEST_VERSION}.zip" ]; then
        echo "$plugin is up-to-date and exists in mirror directory. Skipping download..."
    else
        start_time=$(date +%s.%N)

        if download_plugin "$plugin" "$LATEST_VERSION" "$API_DOWNLOAD_LINK"; then
            if [ "$CACHE_ONLY" != 'y' ]; then
                sed -i "/^$plugin/d" "$LAST_VERSION_FILE"
                echo "$plugin $LATEST_VERSION" >> "$LAST_VERSION_FILE"
            fi
            echo "Successfully processed $plugin."
        else
            echo "Error: Failed to process $plugin." >&2
        fi

        end_time=$(date +%s.%N)
        duration=$(echo "$end_time - $start_time" | bc)
        printf "Time taken for %s: %.4f seconds\n" "$plugin" "$duration"
    fi

    if save_plugin_info "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully saved json metadata for $plugin."
    else
        debug_log "Failed to save json metadata for $plugin."
    fi

    if fetch_and_save_checksums "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully fetched and saved checksums for $plugin."
    else
        debug_log "Failed to fetch and save checksums for $plugin."
    fi

    if [ $version_check_status -eq 0 ]; then
        echo "$plugin" >> "$OPENED_PLUGINS_FILE"
    fi
}

populate_all_plugins() {
    if [ ! -f "$ALL_PLUGINS_FILE" ] || [ "$LIST_ONLY" == 'y' ]; then
        echo "Fetching list of all WordPress plugins..."
        svn list https://plugins.svn.wordpress.org/ | sed 's/\/$//g' > "$ALL_PLUGINS_FILE"
        plugin_count=$(wc -l < "$ALL_PLUGINS_FILE")
        echo "Plugin list (${plugin_count}) saved to $ALL_PLUGINS_FILE"
    fi
    
    if [ "$LIST_ONLY" == 'n' ]; then
        ALL_PLUGINS=()
        while IFS= read -r line; do
            ALL_PLUGINS+=("$line")
        done < "$ALL_PLUGINS_FILE"
        echo "Loaded ${#ALL_PLUGINS[@]} plugins."
    fi
}

if [ "$LIST_ONLY" == 'y' ]; then
    populate_all_plugins
    echo "Plugin list created. Exiting without downloading."
    exit 0
fi

if [ "$DOWNLOAD_ALL_PLUGINS" == 'y' ]; then
    populate_all_plugins
    COMBINED_PLUGINS=("${ALL_PLUGINS[@]}")
else
    if [ ! -d "$PLUGIN_DIR" ]; then
        echo "Warning: Plugin directory $PLUGIN_DIR does not exist or is invalid."
        PLUGIN_LIST=()
    else
        PLUGIN_LIST=($(ls -d "$PLUGIN_DIR"/*/ 2>/dev/null | xargs -n 1 basename))

        if [ ${#PLUGIN_LIST[@]} -eq 0 ]; then
            echo "No plugins found in $PLUGIN_DIR."
        fi
    fi

    COMBINED_PLUGINS=(${PLUGIN_LIST[@]} ${ADDITIONAL_PLUGINS[@]})
    COMBINED_PLUGINS=($(echo "${COMBINED_PLUGINS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
fi

if [ ${#COMBINED_PLUGINS[@]} -eq 0 ]; then
    echo "No plugins to download. Exiting."
    exit 0
fi

mkdir -p "$MIRROR_DIR"
touch "$LAST_VERSION_FILE"

if [ "$PARALLEL_JOBS" -gt 1 ]; then
    echo "Running in parallel with $PARALLEL_JOBS jobs..."
    echo "Variables before export:"

    # WordPress-related directories
    echo "WORDPRESS_WORKDIR: $WORDPRESS_WORKDIR"
    echo "PLUGIN_DIR: $PLUGIN_DIR"
    echo "MIRROR_DIR: $MIRROR_DIR"
    echo "LOGS_DIR: $LOGS_DIR"

    # Cloudflare Worker related URLs
    echo "CF_WORKER_URL: $CF_WORKER_URL"

    # Flags and options
    echo "DOWNLOAD_LINK_API: $DOWNLOAD_LINK_API"
    echo "DOWNLOAD_ALL_PLUGINS: $DOWNLOAD_ALL_PLUGINS"
    echo "LIST_ONLY: $LIST_ONLY"
    echo "DELAY_DOWNLOADS: $DELAY_DOWNLOADS"
    echo "DELAY_DURATION: $DELAY_DURATION"
    echo "FORCE_UPDATE: $FORCE_UPDATE"
    echo "CACHE_ONLY: $CACHE_ONLY"

    # File paths
    echo "OPENED_PLUGINS_FILE: $OPENED_PLUGINS_FILE"
    echo "CLOSED_PLUGINS_FILE: $CLOSED_PLUGINS_FILE"
    echo "LAST_VERSION_FILE: $LAST_VERSION_FILE"
    echo "ALL_PLUGINS_FILE: $ALL_PLUGINS_FILE"

    # Parallel job configuration
    echo "PARALLEL_JOBS: $PARALLEL_JOBS"

    # User Agents mapping
    echo "USER_AGENTS: ${USER_AGENTS[@]}"

    # Additional plugins to be processed
    # echo "ADDITIONAL_PLUGINS: ${ADDITIONAL_PLUGINS[@]}"

    # Plugin List (loaded from directory or ALL_PLUGINS_FILE)
    #echo "PLUGIN_LIST: ${PLUGIN_LIST[@]}"
    #echo "COMBINED_PLUGINS: ${COMBINED_PLUGINS[@]}"

    # First, export all variables including USER_AGENTS
    export DOWNLOAD_BASE_URL MIRROR_DIR LAST_VERSION_FILE DEBUG_MODE DOWNLOAD_LINK_API LOGS_DIR ALL_PLUGINS_FILE DOWNLOAD_ALL_PLUGINS LIST_ONLY CF_WORKER_URL DELAY_DOWNLOADS DELAY_DURATION FORCE_UPDATE CACHE_ONLY WORDPRESS_WORKDIR PLUGIN_DIR PARALLEL_JOBS OPENED_PLUGINS_FILE CLOSED_PLUGINS_FILE USER_AGENTS

    # Then, export the functions
    export -f process_plugin get_latest_version_and_download_link download_plugin debug_log populate_all_plugins save_plugin_info get_random_user_agent fetch_and_save_checksums
    printf "%s\n" "${COMBINED_PLUGINS[@]}" | xargs -P $PARALLEL_JOBS -I {} bash -c 'process_plugin "$@"' _ {}
else
    for plugin in "${COMBINED_PLUGINS[@]}"; do
        process_plugin "$plugin"
    done
fi

if [ -f "$CLOSED_PLUGINS_FILE" ]; then
    echo
    echo "Closed Plugin List:"
    cat "$CLOSED_PLUGINS_FILE" | sort | uniq || true
    echo
    echo "Total closed plugins: $(wc -l < "$CLOSED_PLUGINS_FILE")"
    echo
else
    echo
    echo "No closed plugins found."
    echo
fi
echo "Plugin download process completed."
