#!/bin/bash

# Base directory (script location)
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Configurable directories
WORDPRESS_WORKDIR="${WORDPRESS_WORKDIR:-$BASE_DIR/wordpress-plugins}"
PLUGIN_DIR="${PLUGIN_DIR:-$BASE_DIR/wp-content/plugins}"
MIRROR_DIR="${MIRROR_DIR:-$BASE_DIR/mirror}"
LOGS_DIR="${LOGS_DIR:-$BASE_DIR/plugin-logs}"

# Check for CF_WORKER_URL environment variable
if [ -z "$CF_WORKER_URL" ]; then
    echo "Error: CF_WORKER_URL environment variable is not set." >&2
    exit 1
fi

DOWNLOAD_BASE_URL="https://downloads.wordpress.org/plugin"

# Other variables
DOWNLOAD_LINK_API='y'

ADDITIONAL_PLUGINS=(
    "chuck-norris-joke-widget"
    "logo-widget"
    "oppso-unit-converter"
    "wp-syntax-hacktify"
    "comment-whitelist"
    "seo-internal-link-shortcode"
    "structured-social-profiles"
    "bitly-url-generator"
    "full-site-title"
    "fleet"
    "deprecation-checker"
    "lipsum-dynamo"
    "widgetized-feature-box-for-thesis-framework"
    "auto-assign-post-category"
    "gigatools-widget"
    "techlineinfo-social-count"
    "brilliant-geocoder-gravity-forms"
    "exxmlrpc"
    "floating-theme-list"
    "single-post-page-export"
    "versiculo-del-dia"
    "add-custom-link-to-wordpress-admin-bar"
    "wp-push-notification-firebase"
    "wp2jekyll"
    "photopress-latest-images"
    "animal-shelter"
    "heygov"
    "pdf-for-elementor-forms"
    "products-purchase-limit-for-woocommerce"
    "simply-polls"
    "tempus"
    "wi-games-shortcode"
    "sberlead"
    "live-center-live-blogging-solution"
    "marketengine"
    "ai-auto-content-generator-for-elementor"
    "easy-smooth-scroll"
    "single-page-restaurant-menu-for-woocommerce"
    "addpoll"
    "login-email-sync"
    "proprofs-embed"
    "outdated-browser"
    "bake-posts"
    "no-place-like-home"
    "avayo-ticketshop"
    "blog-templates"
    "share-on-xing"
    "amazing-wpbakery-page-builder-addons"
    "inspect-http-requests"
    "affiliatewp-activecampaign"
    "login-bbpress"
    "deklaracja-dostepnosci-wcag"
    "nss-wooregistration-form"
    "opal-estate-custom-fields"
    "yoo-bar"
    "fast-wordpress-search"
    "mail-baby-smtp"
    "visual-shortcodes"
    "wc-paypay-gateway"
    "mycred-for-courseware"
    "mobile-kiosk"
    "metgis-weather"
    "qanva-analog-clock-for-elementor"
    "dev-content-blocks"
    "winning-portfolio"
    "frontrom"
    "product-feed-viewer"
    "viber-sharing-button-for-jetpack"
    "wpsite-simple-ad-spot"
    "title-icons"
    "dlocal-go-payments-for-woocommerce"
    "adtaily-widget-light"
    "duplicate-post-and-page"
    "simterm"
    "easy-digital-downloads-keep-add-to-cart"
    "add-tinymce-blockquote-cite"
    "wplyr-media-block"
    "wp-chrono"
    "bp-events-calendar"
    "email-marketing-by-sendx"
    "last-fm"
    "wp-webrupee"
    "atarapay-woocommerce"
    "raptorize-it"
    "admin-email-as-from-address"
    "mcjh-button-shortcode"
    "pull-this"
    "easy-to-use"
    "bible-post"
    "support-wp"
    "indieblocks"
    "google-plus-stream-widget-plugin-for-wordpress"
    "dashboard-option-menu-customize"
    "launch-check"
    "wp-appointments"
    "everlytic"
    "wp-walla"
    "orthotypo-orthotypographie-automatique"
    "curated-search"
    "latest-mobileme-photos"
    "wp-phone"
    "fast-affiliate"
    "short-bio-widget"
    "wp-graphviz"
    "geo-data-store"
    "wp-awesome"
    "envato-marketplace-widget"
    "random-quote-of-the-day"
    "gravatar-like"
    "openotp-authentication"
    "seomoz-widgets"
    "whisperfollow"
    "nota-ai-tools"
    "accesible-blank"
    "simple-stopwatch"
    "embed-bokun"
    "woocommerce-clear-cart-on-browser-close"
    "wp-auto-login"
    "password-protection-expiration"
    "wux-blog-editor"
    "add-editor-to-page-for-posts"
    "advanced-elementor"
    "backup2email"
    "slotti-ajanvaraus"
    "editor-bridge"
    "my-favicon"
    "korean-spell-checker"
    "glo3dapp-woospin"
    "wph-breaking-news"
    "wow-trk-affiliate-marketing-ad-rotator"
    "bramework"
    "workchat"
    "wc-advanced-paypal-payments"
    "sv100-companion"
    "quran-shortcode"
    "syntaxhighlighter-evolved-vhdl-brush"
    "remove-author-column"
    "easiest-newsletter"
    "omega-add-paypal-tracking-for-woocommerce"
    "chapa-payment-gateway-for-woocommerce"
    "nutrifox"
    "woo-product-review-schema"
    "better-business-hours"
    "sitemap-google-news"
    "multi-editor-posts-control"
    "sites-monitor"
    "one-click-migration"
    "static-404"
    "copycontentdetector"
    "accordion-faq-plugin"
    "edd-free-download-text"
    "post-link-shortcodes"
    "simple-vote-me"
    "rock-pop-radio"
    "move-posts-from-uncategorized-category"
    "images-via-imgix"
    "tripzzy"
    "wp-dashboard-cleaner"
    "ohdear"
    "export-simple-301-redirects-to-csv"
    "foursquare"
    "adfever-for-wordpress"
    "goto-redirect"
    "theme-selector"
    "cj-remove-wp-toolbar"
    "daily-fortune-telling-cards"
    "king-grabber"
    "ge-rss-reader"
    "advanced-post-privacy"
    "rumble"
    "link-images-to-none"
    "bbpress-info-widgets"
    "wp-login-with-ajax"
    "cart32-shopping-cart"
    "wp-russian-horoscope"
    "mb-toolset-migration"
    "google-syntax"
    "rrssb"
    "mcm-random-baby-name-generator"
    "widget-music-chart"
    "tce-sharing"
    "team-builder-for-wpbakery-page-builder"
    "in-page-script"
    "editor-cleanup-for-oxygen"
    "grassblade-xapi-wp-courseware"
    "code-generator"
    "rich-snippet-for-ai1ec"
    "wp-custom-slider"
    "amp-sidebar-chooser"
    "slug-or-postid"
    "lorem-ipsum-for-wp-editor"
    "realty-portal-submit-property"
    "aparat-embed"
    "avishi-floating-horizontal-navigation"
    "wp-google-map"
    "easy-wp-optimizer"
    "extra-options-for-twenty-twenty"
    "simple-charts"
    "mazen-seo-connector"
    "vbpress"
    "bitdroplet-sip"
    "wpcf"
    "create-custom-dashboard-widget"
    "noindex-nofollow-all-posts-category"
    "wp-energy-usage-calculator"
    "extra-user-data"
    "weather-forecast"
    "mislider"
    "ultimate-products-feed"
    "pixel-random-quotes-and-images"
    "datapress"
    "text-attributes-for-woocommerce"
    "wptouch-cestina"
    "yext-ai-search"
    "really-simple-series"
    "aeiou"
    "minimum-order-amount-for-checkout"
    "category-family-tree"
    "user-tracker"
    "moderate-trackbacks"
    "user-role-for-flamingo"
    "traderunner"
    "gamipress-h5p-points-per-score"
    "ffl-api"
    "connections-business-directory-legacy-templates"
    "adblock-detector"
    "easy-donations"
    "drop-down-links"
    "wp-adf-ly-dashboard-and-integration"
    "webcam-booth"
    "finest-mini-cart"
    "lti-seo"
    "gp-notification-bar"
    "swa-alexa"
    "import-excel"
    "taxonomy-templates"
    "livees-checkout"
    "vendi-tinymce-anchor"
    "kauf-auf-rechnung-inkl-bonitaetspruefung-sahu-media"
    "sleekstore"
    "sir-trevor-wp"
    "adorable-avatars"
    "wp-coupon-system"
    "briqpay-fortnox-product-sync"
    "post6widgetarea"
    "kundennotecom"
    "novinhub"
    "wwwartlebedevru-typograph"
    "clickship"
    "snordians-h5p-resize-pulse"
    "server-status"
    "thematic-html5"
    "simple-video-embed"
    "coupon-by-roles-for-woocommerce"
    "announcement-banner"
    "ilogistic-fulfillment-order-and-product-sync"
    "launch-with-words"
    "product-view-counter"
    "gallery-creator"
    "cookie-disclaimer"
    "my-css-editor"
    "widget-to-show-posts-in-current-category"
    "related-posts-for-genesis"
    "simple-private-video"
    "ip-statistic"
    "parcelow"
    "ugc-comments"
    "saferoute-woocommerce"
    "image-resizer-on-the-fly"
    "shy-posts"
    "bp-limit-activity-length"
    "wc-stock-dependencies"
    "wp-easter-egg"
    "chapters-for-authors"
    "pointfinder-xml-csv-listings-import"
    "wp-code-protection"
    "music-pack-for-elementor"
    "hr-management"
    "domain-report"
    "add-functions"
    "google-ajax-rss-feed"
    "simple-stock-quotes"
    "dco-address-field-for-contact-form-7"
    "woo-round-up-prices"
    "third-party-cookie-eraser"
    "wp-health-check"
    "wp-color-scrollbar"
    "social-like-box-slider"
    "users-custom-posts-counts"
    "delay-redirect"
    "wp-businessdirectory"
    "follow-me-widgets"
    "sf-category-menu"
    "orbisius-bbpress-notify-me-on-follow-up-replies"
    "newsletter-html-generator"
    "oracle-cards"
    "dp-post-views"
    "waaship"
    "wpmu-linkmanager"
    "wp-headline"
    "ziina"
    "shoutout"
    "mdc-scroll-to-top"
    "header-image-uploader"
    "user-status-manager"
    "download-monitor-restrict-content-integration"
    "gosign-google-maps-block"
    "whizz"
    "product-thumbnail-gallery-for-woocommerce"
    "product-total-price-for-woocommerce"
    "elex-abandoned-cart-recovery-with-dynamic-coupons"
    "flush-permalinks-button"
    "wp-triggers-lite"
    "cooee"
    "paygreen-payment-gateway"
    "dokan-auto-seller"
    "restrict-uploads"
    "cd2-fullstory-integration"
    "multisite-taxonomy-widget"
    "wp-slabtext"
    "woo-order-navigation"
    "wp-instant-links"
    "all-image-list"
    "mobile-featured-image"
    "hashcash-for-contact-form-7"
    "space-manager"
    "advanced-custom-fields-migrator"
    "batch-validator"
    "bulks-internal-links-updater"
    "sj-cornerstone-addon"
    "easy-ads-manager"
    "gallery-for-users"
    "graduates-exporter-learndash"
    "tldr-cta"
    "feed-disabler"
    "easy-store-vacation"
    "wp-testimonial"
    "wp-getresponse"
    "gallery-image-captions"
    "post-title-validation"
    "zigzag-delivery-for-woocommerce"
    "single-mailchimp"
    "tinymce-code-element"
    "wizhi-optimization"
    "notable"
    "corona-virus-alert-bar"
    "featured-item-metabox"
    "solpay-store"
    "cosign-sso"
    "woocommerce-4b-pasat-internet-payment-gateway"
    "timeline-express-date-time-add-on"
    "bp-power-seo"
    "restrict-new-users-by-domain"
    "lite-contact-form"
    "combidesk-exact"
    "altchecker"
    "simple-promo-code"
    "rainbowkit-login-web3-integration-for-sign-in-with-ethereum"
    "multisite-administration-tools"
    "fraudradar"
    "my-idx-home-search"
    "jresizr"
    "authentication-via-otp-using-firebase"
    "wp-advert-manager"
    "link-cloaker-for-affiliates"
    "wp01"
    "salavat-counter"
    "cinematic"
    "opensearch"
    "wp-offline-browser"
    "skip-updates"
    "woo-orders-date-range-filter"
    "easy-qr-code-generator"
    "wp-disk-free"
    "nirweb-smart-sms"
    "magic-liquidizer-responsive-form"
    "admin-post-reminder"
    "bubuku-media-library"
    "beedia"
    "wallkit"
    "swpm-elementor-template-protection"
    "knowledge-base-maker"
    "local-business-microdata-widget"
    "autocomplete-post-search"
    "widget4call"
    "broken-link-notifier"
    "recaptcha-for-easy-digital-downloads"
    "categorized-gallery"
    "1337-rss-feed-made-for-sharing"
    "carta-online"
    "wp-nasaads-query-importer"
    "code-to-widget"
    "callback24"
    "five9"
    "bookingmood"
    "adrotate-email-add-on"
    "resize-vimeo"
    "auto-google-chrome-frame"
    "txt2img"
    "click-login-one-click-auth"
    "vaocher-app"
    "simple-custom-countdown-timer"
    "popup-anyway"
    "user-upgrade-capability"
    "find-my-custom-post-types"
    "mobile-enquiry-and-alert-message-for-woocommerce"
    "drop-prices-for-woocommerce"
    "podcast-player-widget"
    "chatflow-chat-widget"
    "zip-from-media"
    "awesome-shortcodes"
    "dynamaker-cad-configurator-for-woocommerce"
    "wp-random-blog-description"
    "wp-comments-vip"
    "upload-svg"
    "photographer-connections"
    "super-simple-quotes"
    "remove-related-products"
    "slitweb-divi-lightbox-for-jetpack"
    "background-update-notification-email-address"
    "raptive-affiliate"
    "mw-ip-denied"
    "w3s-cf7-zoho"
    "cresta-image-in-widget"
    "display-latest-rss-feeds"
    "stax-woo-addons-for-elementor"
    "smart-loan-calculator"
    "bp-xprofile-custom-fields"
    "jpssp"
    "woocommerce-mundipagg"
    "multitags"
    "wp-utility-script-runner"
    "old-posts-highlighter"
    "mzm-link-soruce-for-fdw"
    "slideshow-press"
    "simple-hijri-calendar"
    "multidomain-redirect"
    "awesome-authors"
    "translation-preserver"
    "simple-cart-solution"
    "no-ie-welcome"
    "get-authors-comments"
    "display-kitchen-sink-by-default-in-visual-editor"
    "generate-thumbnail"
    "lexs-last-update-widget"
    "wp-custom-post-field"
    "teamgate-crm-forms"
    "serviceform-pixel"
    "hide-pages-from-dashboard-page-list"
    "ctrlsfix-hide-login"
    "grainy-gradient-block"
    "date-published-shortcode"
    "p5"
    "eth-embed-anchor-fm"
    "frumentarii"
    "dotepub"
    "personal-tweet-me"
    "wpicp-license"
    "dotdigital-for-woocommerce"
    "advanced-custom-fields-sites-field"
    "pdp-scrool-to-top-bottom"
    "wp-conditional-shortcodes"
    "wp-lorem"
    "woo-cmp-flash-video-player"
    "magic-template-holder"
    "paypal-forms"
    "mf2-feed"
    "creativ-demo-importer"
    "wp-login-image-captcha"
    "no-aioseop-nags"
    "better-login-security-and-history"
    "front-end-categories"
    "bcc-everything"
    "ssl-secure-seal-for-woocommerce"
    "simple-countdown-flip-timer-for-wp"
    "campaign-monitor-synchronization"
    "league-of-legends-shortcodes"
    "incognito-chat"
    "wp-promptpay"
    "woocommerce-automatic-download"
    "data-visualizer"
    "wp-admin-classic-colors"
    "announceme"
    "softdiscover-db-file-manager"
    "comments-to-activecampaign"
    "elvez-edit-copyright"
    "my-coolpay-payment-gateway-for-woocommerce"
    "completely-delete"
    "analytics-unbounce"
    "jobs-that-makesense"
    "wpartisan-filename-sanitizer"
    "calipio-screen-recorder"
    "wp-obituary"
    "image-content-show-hover"
    "makeinfluence"
    "fm-webcam"
    "wpbr-linepay-tw"
    "contact-form-7-freebie"
    "trueroas"
    "external-header-footer"
    "browser-update-notify"
    "do-that-task"
    "artemis-payment-gateway"
    "slenderbox"
    "wp-lopa"
    "wcbox-lite"
    "stellate"
    "eu-cookie-law-notification"
    "realty-portal-agent"
    "just-image-optimizer"
    "jonradio-perpetual-calendar"
    "countdown-to-next-post"
    "arukereso-megbizhato-bolt-integracio"
    "wptobe-memberships"
    "darven-multiplos-precos-informativos"
    "scribble-maps-kml-embed"
    "best-wp-google-map"
    "secure-login"
    "case-insensitive-urls"
    "pz-talk"
    "readable-names"
    "ele-term-list"
    "ione360-configurator"
    "bp-rsed"
    "abandoned-contact-form-7"
    "user-sync-for-azure-office365"
    "move-site-icon-to-settings"
    "json-structuring-markup"
    "awesome-click-to-tweet"
    "bbp-auto-block-spammers"
    "easy-vbox7"
    "termin-kalender"
    "battlefield-3-statistics"
    "rnn-browser-support"
    "essential-form"
    "pryc-wp-antyspam"
    "scrollmagic-for-wp-bakery"
    "download-monitor-migrate-download-counts"
    "create-posts-terms"
    "dom-seo-image"
    "wp-lawyer"
    "disable-editor"
    "xml-editor"
    "a-dashboard-notice"
    "project-cost-calculator"
    "increase-upload-limit"
    "mm-maintenance-redirect-to-page"
    "ns-gdpr"
    "thebrent-private-site"
    "post-theming"
    "firstpage-sg-security-headers"
    "just-another-saperu-integration"
    "accessible-external-text-links"
    "traktivity"
    "supplier-data-fields-for-wc"
    "ai-site-builder"
    "mieruca-heatmap-tag-manager"
    "sc-simple-zazzle"
    "contempo-reviews"
    "shine-pdf"
    "backtop"
    "form-block"
    "easy-ip-redirection"
    "spyrowebz-gallery"
    "smart-admin-search"
    "zu-media"
    "maxicharts-gravity-view-add-on"
    "specify-home-hidden-categories"
    "spillt-recipe-app"
    "external-files-in-media-library"
    "scifi-facets"
    "affiliates-manager-mailpoet-integration"
    "woo-custom-overlays"
    "expire-comment-links"
    "custom-smilies-directory"
    "affiliate-window-banners"
    "vc-galleria"
    "wooproduct-shortcode"
    "wp-roundabout"
    "toky-click-to-call"
    "worten-conector"
    "marctv-mediaelement-tracking"
    "linkedin-perfect-share"
    "storymaps"
    "maxicharts-csv-source-add-on"
    "leader-api"
    "storychief-acf"
    "post-to-pdf"
    "linkgather"
    "ads-bbpress"
    "email-marketing-services-integration"
    "doaj-export"
    "awesome-fitness-testimonials"
    "selfie"
    "wp-car"
    "wphotline-ads-txt"
    "external-products-currency-for-woocommerce"
    "animate-content"
    "chessonline"
    "clean-wp-head"
    "affiliatewp-getresponse-add-on"
    "xllentech-salat-timings"
    "flipbook-catalog-with-woocommerce-link"
    "buzz-comments"
    "admin-ui"
    "ultimate-cursor"
    "bp-emails-for-bbp"
    "woo-live-sale-notify"
    "mrkv-liqpay-extended"
    "media-expirator"
    "falling-cherry-flower"
    "comments-advanced"
    "timespan"
    "twitchpress-login-extension"
    "tab-awesome"
    "ldap-authentication-2"
    "user-titles"
    "fifo-testimonials"
    "template-overide"
    "simple-catalogue"
    "leadboxer"
    "post-modified-date"
    "lifestreamfm"
    "simple-forum-widgets"
    "generate-shortlinks"
    "beforeafter"
    "table-for-divi"
    "remove-wpautop"
    "netpay-checkout"
    "admin-form"
    "triggerbee"
    "price-comparison"
    "mpp-featured-content"
    "woohistory"
    "materialize-contact-form"
    "um-user-list"
    "woo-payjoe-beleg-schnittstelle"
    "zakaat-calculator"
    "dispito"
    "simple-pregnancy-calculator"
    "wp-random-button"
    "disable-comments-by-click5"
    "woo-disable-local-pickup-on-ship-to-different-address"
    "flagged-content"
    "saphali-liqpay-for-donate"
    "download-count-for-woocommerce"
    "override-comment-options"
    "mailshrimp"
    "tweets-by-post"
    "cp-author-online"
    "in-stock-layered-nav-for-woocommerce"
    "p3chat"
    "highlight-comments"
    "forms-actions"
    "swipe-slider"
    "ok-poster-group"
    "gtg-audio-player"
    "1-click-backup-restore-database-by-sunbytes"
    "quickstyle-background"
    "configurator"
    "esv-bible-shortcode-for-wordpress"
    "importyourpost"
    "edd-better-checkout-cart"
    "simpaisa-card-payment-service"
    "tag-images"
    "node-wpapi-auth"
    "real-estate-agency"
    "postpay"
    "imgbacklink"
    "tablentor"
    "hatena-bookmark-autopost"
    "admin-menu-tamplate-plugin"
    "cf7-weclapp-integration"
    "count-cwp"
    "clear-logout"
    "dispensary-gear"
    "auto-cart-update-on-quantity-change"
    "dn-footer-contacts"
    "extra-posts-pages-menu"
    "slug4apig"
    "elevator"
    "ir-manager"
    "wp-funnel-manager"
    "media-placeholders"
    "twentyten-ie6-menus"
    "ie-check"
    "kalender-hijriah"
    "my-contact-form"
    "wp-search-category-admin"
    "display-url-params"
    "home-slider"
    "biographical-info-paragraphed"
    "restrict-registration-for-wp-members"
    "cackle-live-chat"
    "image-comparison-elementor-addon"
    "traction-external-links-speed-bump"
    "thumbmaster"
    "official-leadboltcom-wordpress-plugin"
    "the-hack-repair-guys-admin-login-notifier"
    "camoo-sso"
    "wp-redhelper"
    "ugrm"
    "lifepress"
    "wp-naver-map-in-post"
    "wp-filter-combine-rss-feeds"
    "woo-honey-pot-anti-spam"
    "awcf7-stop-spinning"
    "login-register-redirect-for-woocommerce"
    "tinymce-unrestrictor"
    "katapult"
    "azonbox"
    "cache-manifest-for-wordpress-themes"
    "wp-acf-nullify-gatsby"
    "disable-version-caching"
    "grid-button-for-learndash"
    "wc-iikocloud"
    "wpmdb"
    "lotos-likes"
    "free-images-pictures"
    "wp-client-reference"
    "the-real-estate-voice"
    "cardznet"
    "expertflow-hybrid-chat"
    "woo-local-pickup-pro"
    "random-tagline"
    "dx-advanced-widgets"
    "cleavr-clear-cache"
    "coming-soon-express"
    "wp-unicode"
    "infinite-scroll-block"
    "disable-comments-on-post-categories"
    "easy-image-widget"
    "traffic-lights"
    "wopo-paint"
    "beauty-box-block"
    "woo-color-swatch"
    "reputation-management-for-wordpress"
    "genesis-accessible-dropdown-menu"
    "weclapp"
    "nativery"
    "date-pagination"
    "groups-bbpress"
    "edd-versions"
    "jw-forced-login"
    "tutor-lms-bunnynet-integration"
    "mailster-hcaptcha"
    "fancy-user-listing"
    "randomquotes"
    "reloaded-rezdy"
    "simple-click-tracker-lite"
    "search-placeholder-avada"
    "tsparticles-block"
    "llm-hubspot-blog-import"
    "meinungsmeister"
    "order-picking-app"
    "analytical-spam-filter"
    "wordpress-gps"
    "admin-only-jetpack"
    "3d-presentation"
    "groups-for-membermouse"
    "mzslugs-translator"
    "gdpr-settings-for-wc"
    "hide-woocommerce-product-shipping-information"
    "pcloud-backup"
    "add-categories-post-footer"
    "ni-woocommerce-invoice"
    "disable-registration-page"
    "cf7-to-google-sheets"
    "healthy-site-seo"
    "indicadores-colombia"
    "wpazure-site-library"
    "wp-dump"
    "w4os-opensimulator-web-interface"
    "wc-pre-order"
    "easy-click-to-tweet-by-cheeky-apps"
    "simple-tabs-block"
    "automatic-affiliate-for-amazon"
    "custom-wp-registration-form"
    "pay-to-post"
    "vandar-learnpress"
    "raphicon"
    "scand-multi-mailer"
    "iavote"
    "azurecurve-floating-featured-image"
    "pr-checker"
    "templatify"
    "botao-de-chat-gratis-para-seu-site-rd-station"
    "single-image-widget"
    "image-hover-effects-elementor-addon"
    "1beyt"
    "sd-pdf-template-customizer"
    "rss-feed-add-images-to-your-posts"
    "organize-user-uploads"
    "yampp"
    "bunnys-language-linker"
    "twitterpad"
    "permalink-shortcode"
    "quick-page-navigation"
    "its-migs"
    "images-with-gps-data-and-gpx-on-maps"
    "acf-s3-media-files"
    "office-visits-logbook"
    "yala-themes-toolkit"
    "contact-icons"
    "social-media-sharing"
    "colored-categories"
    "single-user-login"
    "personyze-web-analytics"
    "easy-ad-placement"
    "pdf-flipbook-heyzine"
    "mrcookies"
    "shopbox"
    "wp-subpages"
    "featured-categories"
    "recipes-to-grocery-lists"
    "consistency"
    "ig-pricing-table"
    "the-content-injection"
    "pledgemusic"
    "customization-for-wp-seo"
    "disable-deprecated-warnings"
    "cwd-stealth-links"
    "emailshroud"
    "xsd-socialshareprivacy"
    "canvas-mobile-menu-addition"
    "multi-video-box"
    "csmusiccharts-uk"
    "wp-mail-validator"
    "wordpress-post-update-links"
    "wp-mail-gateway"
    "image-resize-for-chrome-and-safari"
    "in4x-crypto-payment"
    "paga-con-modo"
    "flywire-payment-gateway"
    "wp-address-schema"
    "an-easy-skype-button"
    "scroll-to-top-builder"
    "pronamic-pay-with-mollie-for-gravity-forms"
    "wp-hiderefer"
    "quietly"
    "ccr-colorful-faq"
    "dimme-googlemaps"
    "acf-fields-in-custom-table"
    "integrai"
    "page-specific-scripts"
    "advanced-gallery"
    "gallery-one"
    "sms-sharing-button-for-jetpack"
    "maintenance-mode-coming-soon"
    "add-tiktok-pixel-for-wooccommerce"
    "invoice-payment-for-woocommerce"
    "skloogs-trader"
    "acf-dynamic-choices"
    "price-robot-for-woocommerce"
    "nike-ipod"
    "team-ultimate"
    "country-dropdown-for-contact-form-7"
    "wc-gocardless-instant-bank-payments"
    "rtm-mail-wp-mail-logger"
    "mcpopup-popup-form-for-mailchimp"
    "slick-write"
    "acf-google-map-field-multiple-markers"
    "turkish-liras-currency-for-woocommerce"
    "envira-tamer"
    "pixelpostrss"
    "woocommerce-paybox-gateway"
    "minitek-wall"
    "sc-google-ranking"
    "simple-wp-colorfull-accordion"
    "wp-twitter-wall"
    "kurs-bca"
    "query-monitor-extension-checking-variables"
    "tinyfeedback"
    "just-a-simple-popup"
    "travelling-blogger"
    "amplify"
    "angry-creative-logger"
    "custom-sections"
    "wp-hallo-welt"
    "paywhirl-recurring-payments"
    "modifier-for-colors-label-variations-for-woocomerce"
    "wp-markdown-syntaxhighlighter"
    "wp-ajax-tree"
    "china-addthis"
    "eventish"
    "post-author-ip"
    "referer-spam-blocker"
    "woo-add-empty-cart"
    "tinysocial"
    "universal-email-preference-center"
    "woocommerce-mailchimp-plugin"
    "wc-change-currency-symbol"
    "csv-import-and-exporter"
    "gallery-styles"
    "content-visibility-date-and-time"
    "hero-banner-slider"
    "prettygallery"
    "gravatar-alt-title-fix"
    "wp-quick-maintenance"
    "pw-woocommerce-lets-export"
    "wppaybox"
    "pondol-bbs"
    "gr80-jwplayer-plugin-helper-panel"
    "toplist"
    "qmean"
    "nft-login"
    "advanced-custom-fields-multiple-coordinates"
    "freelance-status"
    "disable-unsplash-cdn"
    "golden-ticket"
    "html-to-post"
    "yydevelopment-related-posts"
    "blaize-companion"
    "duplicate-publish-multisite"
    "mycred-gamipress-importer"
    "access"
    "link-vault"
    "qr-code-generator"
    "slideshare-widget-multislides"
    "inquiry-cart"
    "amazing-ads-manager"
    "https-thumbnails"
    "edd-sl-renew-all"
    "wp-wvip"
    "wc-api-custom-meta"
    "a-faster-load-textdomain"
    "ls-gmap-route"
    "woo-paypal-payflow"
    "critical-css"
    "wp-azure-offload"
    "esms-gui-tin-nhan-sms"
    "martins-free-and-easy-ad-network-get-more-visitors"
    "edd-mobile"
    "wp-imgur-plus"
    "wp-click-check"
    "woocollections-for-woocommerce"
    "email-blacklist-for-elementor-forms"
    "disable-unused-block-editor-blocks"
    "safecode"
    "cc-savings-calculator"
    "comentario-via-e-mail"
    "pagination-translator"
    "mp3-scraper"
    "avatar-tooltip"
    "massive-replacer"
    "texterify"
    "show-dimensions-in-library"
    "slide-puzzle"
    "iran-map"
    "woo-open-graph"
    "gamipress-edd-points-per-purchase-total"
    "show-aposts-shortcode"
    "lead-captor"
    "buddypress-twitter-post"
    "wp-profitshare-advertisers"
    "blocks-for-civicrm"
    "user-hierarchy"
    "fetch-tweets-rotator-template"
    "wpo365-samesite"
    "edit-usernames"
    "xml-for-hotline"
    "customer-reviews-by-revukangaroo"
    "remove-yoast-notices"
    "xiaodu-jsdelivr"
    "wpp-customization"
    "post-filter"
    "ds-adrotator"
    "google-trends-und-charts"
    "language-downloader"
    "wp-bot-counter"
    "meneame-comments-to-wp"
    "neoncrm-sign-in"
    "feng-custom"
    "foundation-columns"
    "bulk-role-change"
    "fx-live-prices"
    "post-descriptions"
    "calj"
    "lbdesign-button-shortcode"
    "subscribe2-cestina"
    "wptao-sms"
    "chat-messenger-with-toolbar"
    "mimo-logo-changer"
    "slug-as-body-class"
    "muv-hide-preview"
    "yg-subdomain"
    "adif-log-search-widget"
    "wp-debug-robot"
    "my-wp-ab-testing"
    "github-readme"
    "exifize-my-dates"
    "flask-micro"
    "woo-halkbank-payment-gateway"
    "easy-liqpay"
    "super-custom-css"
    "vertical-client-carousel"
    "ttc-tripwire-plugin"
    "button-chat-zalo-report-sw"
    "wplit-woo-conditions-for-oxygen"
    "plantuml-renderer"
    "easy-banners-widget"
    "wp-forex-calculator"
    "realty-portal-my-favorites"
    "block-pinterest"
    "integrate-wplms-ga"
    "smart-docs"
    "insector"
    "social-media-by-lazy-cat-themes"
    "mobileme-gallery"
    "moredeal-ai-writer"
    "guild-wars-2-wvw-matchups"
    "copyright-block"
    "protect-pages-and-categories-with-login"
    "oauthphp"
    "cleantalk-bbpress-spam-scanner"
    "widget-for-zendesk-chat-via-api"
    "gestion-tarifs"
    "random-number-generator"
    "hitboxtv-widget"
    "rta-restricted-to-adults-header"
    "simple-accessibility"
    "review-manager"
    "dadevarzan-wp-tender"
    "goodtill-stock-sync"
    "dibsy-payments"
    "fd-buttons-gutenberg"
    "buddypress-activity-anywhere"
    "foxdeli"
    "responsive-oembed"
    "simulador-de-parcelas-taxas-avancadas"
    "bait-stream"
    "digitalpush"
    "simple-fonts-loader"
    "message-mate"
    "comments-form-star-rating"
    "admanage"
    "badgeos-tutorlms"
    "find-and-replace-content"
    "theasys"
    "fuel-bitcentral"
    "tejus-add-cat-image"
    "site-mailer"
    "board-election"
    "keymaster-chord-notation-free"
    "advance-waitlist"
    "theme-my-ontraport-smartform"
    "crossposting-in-safe-way"
    "open-ai-search-bar"
    "wootomation"
    "mins-to-read"
    "visitas-on-line"
    "fade-in-like-google"
    "wp-post-ticker"
    "tdb-hide-recaptcha-badge"
    "mc-visitor-tally"
    "ac-cf7-form-field-repeater"
    "mobile-call-now"
    "infosniper"
    "aweos-offcanvas-menu"
    "feature-box-addon-for-wpbakery-page-builder"
    "easy-map-creator"
    "elevated-comments"
    "disable-webp-by-default"
    "filtered-html-for-editors"
    "ads-management"
    "vgw-metis"
    "expire-password-protected-pages"
    "design-import-export"
    "full-screen-images"
    "vanilla-bean-meta-maid"
    "simple-google-contact-map"
    "xq-secure-form"
    "coinshare-voucher-pay-gateway"
    "disable-feeds-and-hide-usernames"
    "rotating-words-for-visual-composer"
    "post-timer"
    "wp-dashboard-eathim"
    "my-mood-comment"
    "gf-engage-add-on"
    "wp-awesome-city-weather-report"
    "srizon-lorem"
    "i-am-human"
    "pdf-email-on-save"
    "supporthost-star-rating"
    "surveyhero"
    "cat-generator-avatars"
    "advanced-custom-fields-mapbox-geojson-field"
    "hive-support"
    "hide-administrator-bar"
    "bookwize-booking-form"
    "acymailing-integration-for-easy-digital-downloads"
    "woo-subscription-trial-coupon"
    "random-quiz-addon-for-lifterlms"
    "treemagic-cypress"
    "blog-toplist"
    "christmas-template"
    "our-team-widget-for-elementor"
    "realpress"
    "just-output"
    "hide-element"
    "acf-tab-accordion-title-icons"
    "svg-shortcode"
    "display-live-visitors-counter"
    "region-city-landing-pages-builder"
    "rs-logo-showcase"
    "pmp-fondy-payment"
    "oneclickpublish"
    "miragetconnector"
    "dzs-ajaxer-lite-dynamic-page-load"
    "page-style"
    "dashing-memberships"
    "ajax-to-do"
    "client-certificate-authentication"
    "easy-error-reporting"
    "fast-video-and-image-display"
    "bba-mastro"
    "estimated-delivery-date-per-product-for-woocommerce"
    "ra-widgets-bundle"
    "doctor-agenda"
    "pro-text-widget"
    "acme-wpml-language-switch"
    "roofing-cost-calculator"
    "ple-ec3"
    "sweet-titles"
    "korea-address"
    "widont-part-deux"
    "office-hours"
    "google-xml-site-search"
    "ns-free-price-and-donation-for-woocommerce"
    "two-column-admin"
    "better-speed"
    "cf7-salesmate-integration"
    "ajax-press"
    "invoice-payment-gateway-for-woocommerce"
    "trusted-order-notifications"
    "bridgerpay-woocommerce"
    "email-cop"
    "moon-phase-widget"
    "wp-job-manager-custom-management-role"
    "voo-shipping"
    "myqtip-easy-qtip2"
    "theme-checklist"
    "plugin-info-cards"
    "woo-exchange-rate"
    "nd-sports-booking"
    "display-image-dimensions-in-media-library"
    "electric-backups"
    "yt-subscribe-link-locker"
    "control-listings"
    "nbtech-woomenu"
    "awesome-cookie-consent"
    "chat-viber"
    "cross-sell-product-display-for-woocommerce"
    "private4time"
    "yahoo-boss"
    "electric-studio-eu-cookie-law-compliance"
    "easy-currency-converter"
    "registration-page-shortcut"
    "bracketcloud"
    "hnb-payment-gateway"
    "lol-free-champion-rotation"
    "lingapi-for-polylang-and-wpml-wp-translation-tool"
    "crypto-payment-checkout-by-intrxn"
    "skaut-fio-bank-transactions"
    "mythic-wp-management"
    "how-old-am-i"
    "adverts-click-tracker"
    "issues-tracker"
    "wp-easy-survey"
    "custom-options-plus-post-in"
    "emi-calculator"
    "recover-wc-abandoned-cart"
    "simple-qr"
    "wordpress-publication-repository"
    "wp-github-commits"
    "private-website-intranet"
    "scootercontact"
    "selleradise-widgets"
    "free-sms-for-woocommerce"
    "wc-ame-digital"
    "hello-hal"
    "skydrv-hotlink"
    "wordpress-comment-bubble-plugin"
    "persian-reports"
    "foogallery-captions"
    "wp-mourning"
    "zerowp-social-profiles"
    "easy-image-uploader"
    "wp-cas-server"
    "dark-press"
    "web-payment-software-payment-gateway-for-woocommerce"
    "basic-url-shortcodes"
    "integrations-of-zoho-crm-with-elementor-form"
    "embed-solitaire-iframe"
    "wt-display-breeze"
    "wm-options-import-export"
    "availability-scheduler-for-woocommerce"
    "k2-core-block-image-styles"
    "blanka"
    "wc-gateway-cib"
    "jump-page"
    "pagerank-checker"
    "addonify-recaptcha-for-edd"
    "address-bar-ads"
    "simple-popular-posts"
    "post-of-the-day"
    "hidden-login"
    "tooltip-wp"
    "wp-share-old-post-lite"
    "admidio-events"
    "itm-simple"
    "custom-functions-starter-kit"
    "pin-generator"
    "wc-messaging"
    "slideshowpro-shortcode"
    "visit-website-customizer"
    "manage-admin-columns"
    "data-sync-x-by-wbsync"
    "wc-belluno"
    "presentation-block"
    "most-recent-posts"
    "visma-pay-embedded-card-payment-gateway"
    "terms-to-links"
    "wc-serbian-nestpay"
    "keyboard-nav"
    "bridaluxe-storefront"
    "dirtysuds-kill-howdy"
    "recent-products-block"
    "yydevelopment-seo-data"
    "coupons-booster-for-woocommerce"
    "dozent-lms"
    "your-id-please"
    "1qlick"
    "sell-btc-by-hayyatapps"
    "invelity-ikros-invoices"
    "city-hive"
    "raptor-editor"
    "simple-gdpr"
    "sample-content-generator"
    "google-maps-and-distance-finder"
    "engage-by-zubi"
    "capture-url-variables-for-ontraport"
    "taxonomy-checklist-tree"
    "traveledmap-trip-itinerary-embedded-map"
    "wp-copyright"
    "alt-for-images"
    "debt-reduction-calculator-debt-relief-program-calculator-all-in-one"
    "post-specific-widgets"
    "fv-bbpress-tweaks"
    "cookie-dough-compliance-and-consent-for-gdpr"
    "svn-auto-upgrade"
    "column-stretch-elementor"
    "wp-caregiver"
    "woo-restrict-by-category"
    "custom-featured-image-metabox"
    "geocache-stat-bar-widget"
    "no-nofollow"
    "ad-blocking-alert"
    "wp-themes-by-screensize"
    "dashly"
    "wp-api-multiple-posttype"
    "savyour-affiliate-partner"
    "podcastde-wordpress-plugin"
    "customize-private-protected"
    "world-prayer-time"
    "woocommerce-paymaster-gateway-019"
    "wp-sup-contact-form"
    "wordpress-title-cloud"
    "block-editor-for-woocommerce"
    "force-lowercase-urls"
    "storipress"
    "lp-estimated-reading-time"
    "website-open-close-hours"
    "php-text-sidebar-widget"
    "child-page-templates"
    "viavi-dummy-content-generator"
    "dadata-ru"
    "videoask"
    "cf7-domain-blacklist"
    "dash-todo"
    "list-yarpp-block"
    "orbisius-limit-logins"
    "tinymce-code-button"
    "twitter-blogroll"
    "djmetabox"
    "payment-gateway-icons-for-woocommerce"
    "coming-soon-product-for-woocommerce"
    "elfskot-product-configurator"
    "yy-events"
    "adwol-werbung"
    "revenueflex-easy-ads"
    "dt-lms-lite"
    "conversation-starter"
    "download-post-comments"
    "folding-archives"
    "realty-portal-package"
    "trendmd"
    "webisonline"
    "wpml-edits"
    "mt8-post-share"
    "menupublisher-4-wp"
    "wp-pretty-filters"
    "at-news-scroller"
    "migrate-post"
    "sort-page-list-by-last-name"
    "do-more"
    "wootheme-testimonials-to-testimonials"
    "author-bio-plus"
    "web-cam"
    "wp-spam-question-filter"
    "kento-like-post"
    "learnworlds-sso"
    "wc-tinkoff-secure-deal-payment-gateway"
    "change-user"
    "current-star-sign"
    "custom-unit-converter"
    "cam-site-builder"
    "st-insert-post-plugin"
    "enable-responsive-image"
    "formidable-import-pirate-forms"
    "gravity-forms-periodic-notification-e-mails-by-weptile"
    "lemonade-sna-pinterest-edition"
    "adapter-gravity-add-on"
    "dni-woocommerce"
    "related-post-widget-side"
    "vidtok-live-video-chat-using-webrtc"
    "elex-choose-your-delivery-date"
    "em-dashboard"
    "recibir-mensajes-instantaneos"
    "responsive-bmi-calculator"
    "admin-link-box"
    "grassblade-xapi-tutorlms"
    "wp-show-category-posts"
    "reset-slugs"
    "quick-whois"
    "geounit-maps"
    "tabby-free"
    "short-link"
    "myuserpay"
    "add-your-comment-link"
    "application-insights-dashboard-remake"
    "shipping-manager-for-woocommerce"
    "virtual-brick-social-bar-side-widget"
    "integration-of-pathao-for-woocommerce"
    "magic-coupon"
    "nutsforpress-indexing-and-seo"
    "code-blocks-online-code-compiler"
    "gravity-forms-disable-autofill-add-on"
    "makemydonation-imo"
    "wc-telegram"
    "lnbits-bitcoin-onchain-and-lightning-payment-gateway"
    "spectacula-advanced-search"
    "promissa"
    "fuerte-wp"
    "display-active-plugins-first"
    "easy-seo-toolkit"
    "amazon-box"
    "twchat"
    "custom-payment-gateway-for-billdesk"
    "wp-contest"
    "custom-admin-column"
    "disable-bbpress-profile-override"
    "thumbnail-create"
    "wp-check-spammers"
    "output-desk-live-chat"
    "twidger"
    "wp-awesome-login"
    "trademe-widget"
    "wp-clean"
    "simple-constant-contact"
    "paj-divi-menu-options"
    "daily-readings"
    "publish-confirmation"
    "post-meta-box-order"
    "buy-now-button"
    "jp-theme-bar"
    "feedburner-converter"
    "ipb-last-topics"
    "igms-direct-booking"
    "wp-pwa-yoast-seo"
    "ez-ajax-search"
    "df-draggable"
    "multilingual-comments"
    "wp-query-creator"
    "om-addon-for-wp-courseware"
    "bp-searchable-activity"
    "advanced-backwpup-s3-destinations"
    "embed-documents-shortcode"
    "cryptocurrency-payments-for-paid-memberships-pro"
    "buddy-love"
    "kalamatino"
    "tp-flatsome-vertical-menu"
    "eveeno"
    "responsive-youtube-video-player-and-iframe"
    "press-tube"
    "trendy-restaurant-menu"
    "ultimate-slack-notifications"
    "sale-discount-for-woocommerce"
    "sort-by-modified"
    "seo-tile-of-tag"
    "page-excerpts-for-wordpress-three"
    "flashcounter"
    "ravelry-projects-widget"
    "elex-shipengine-shipping-method"
    "woo-paypal-credit-card-rest"
    "collaborate-notes"
    "admin-footer-version-rebranded"
    "whats-new-for-ameba-blog"
    "waafipay-payment-gateway-for-woocommerce"
    "online-indicator-for-twitch"
    "conversational-forms-for-gravity-forms"
    "maxicharts-query-builder-add-on"
    "easy-integrated-image-gallery"
    "moka-get-posts"
    "wp-roster"
    "theme-blvd-admin-presence"
    "headline-split-tester"
    "customdonations"
    "deliveo"
    "responsive-modern-slider"
    "automatic-post-share"
    "tyresaddict-wheel-product-filter"
    "limepay-woocommerce-gateway"
    "omnifeed"
    "manual-credit-card-processing-for-woocommerce"
    "newsletter-artisan"
    "wordpress-shortcode-library"
    "pegapoll"
    "fix-update-in-process"
    "alpha-google-map-for-elementor"
    "wp-qr-code-auto-generator"
    "share-to-microsoft-teams"
    "onepager"
    "shortlink-column"
    "raise-the-money"
    "email-otp-authenticator"
    "hashchecker"
    "wp-quick-menu"
    "realty-portal-agent-dashboard"
    "infinite-scroll-to-tf"
    "show-remote-ip"
    "easy-digital-download-affiliate-banners"
    "briqpay-signup-addon"
    "qr-print"
    "admin-login-notifier"
    "bloat-buster"
    "maintenance-and-noindex-nofollow"
    "documents-for-woocommerce"
    "whws-display-user-meta-shortcode"
    "logs-de-connexion"
    "qiniu-uploader"
    "nav-menu-trim"
    "syntaxhighlighter-evolved-php5"
    "wp-fake-image-replacer"
    "admin-site-switcher"
    "flexible-post-filter"
    "affiliate-product-review"
    "featured-today"
    "dispensary-tinctures"
    "populist"
    "assign-widgets"
    "wp-curtain-raiser"
    "shortcodify"
    "category-list-icon"
    "image-puzzle"
    "visibility-warning"
    "ilc-rich-title"
    "opr-place-reservations"
    "paste-to-media"
    "regiones-ciudades-y-comunas-de-chile"
    "campus-explorer-widget"
    "we-minify-html"
    "twitter-status"
    "emotify-reaction-system"
    "ecommerce-shipping-dashboard-by-ups-for-woocommerce"
    "tweaks-for-elementor"
    "fewer-tags"
    "site-info-dashboard-widget"
    "manager-for-discord"
    "interactive-page-hierarchy"
    "nlb-payment-gateway-for-woocommerce"
    "azurecurve-bbcode"
    "zarza-real-ip"
    "adobe-analytics"
    "embed-maps-block"
    "photoblog-image-fixer"
    "wp-latest-post-blogroll"
    "twitter-follow-button-in-comments"
    "status-buddy"
    "remove-page-from-search-results"
    "category-teaser-widget"
    "ctl-battleship-minesweeper-lite"
    "remove-profile-bio"
    "like-and-who-likes"
    "bbpress-topic-sections"
    "jumper"
    "import-from-ghost"
    "link-products-to-sendinblue"
    "yext-answers"
    "business-open-hours-master"
    "mesomb-for-woocommerce"
    "wplyrics"
    "wp-trip-summary"
    "expandable-banners"
    "tiemediahelper"
    "pages-only"
    "douban-collections"
    "click-to-donate"
    "ag-twitter"
    "change-browser-tab-title-when-tab-is-not-active"
    "add-twitter-pixel"
    "wp-force-password"
    "prevent-pages-from-deleting"
    "alink-tap"
    "diablo-3-tooltip"
    "free-mubjib-borsho"
    "hippoo"
    "descriptions-as-captions-in-galleries"
    "pushbullet-notification"
    "blimply"
    "custom-author"
    "shortcode-emojis"
    "login-with-office-365"
    "features-for-woocommerce"
    "podscms-widgets"
    "south-african-covid-19-banner"
    "check-last-login"
    "ledenbeheer-external-connection"
    "cf7-submissions"
    "admin-featured-thumbnail"
    "show-thumbnail-sizes-name"
    "enwikuna-license-manager"
    "disable-pingbacks"
    "tp2wp-assets-importer"
    "woo-hutkigrosh-gateway"
    "csfd-last-seen"
    "metwit-weather-widget"
    "auto-google-news-poster"
    "my-social-share-buttons"
    "themarketer"
    "freight-shipping-quote"
    "mobile-device-redirection"
    "form-countdown-for-givewp"
    "get-bookings-wp"
    "latest-post-slider"
    "sb-post-widget"
    "disable-site-delete"
    "ajdg-user-cleaner"
    "dynamic-search-widget"
)

# Define user agents with weights
declare -A USER_AGENTS
USER_AGENTS=(
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"]=5
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"]=7
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"]=6
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36 Edg/91.0.864.54"]=5
    ["Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 OPR/77.0.4054.277"]=3
    ["Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (iPad; CPU OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Vivaldi/4.0"]=1
    ["Mozilla/5.0 (Android 11; Mobile; rv:68.0) Gecko/68.0 Firefox/88.0"]=1
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"]=15
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/534.36"]=12
)

OPENED_PLUGINS_FILE="${WORDPRESS_WORKDIR}/opened_plugins.txt"
CLOSED_PLUGINS_FILE="${WORDPRESS_WORKDIR}/closed_plugins.txt"
LAST_VERSION_FILE="${WORDPRESS_WORKDIR}/last_versions.txt"
PARALLEL_JOBS=1

DOWNLOAD_ALL_PLUGINS='n'
LIST_ONLY='n'
ALL_PLUGINS_FILE="${WORDPRESS_WORKDIR}/wp-plugin-svn-list.txt"
START_COUNT=0
END_COUNT=0

DELAY_DOWNLOADS='n'
DELAY_DURATION=5

FORCE_UPDATE='n'
CACHE_ONLY='n'

mkdir -p "$WORDPRESS_WORKDIR" "$MIRROR_DIR" "$LOGS_DIR"
rm -f "$OPENED_PLUGINS_FILE"
touch "$OPENED_PLUGINS_FILE"
DEBUG_MODE=0

while getopts "p:dalD:t:fcs:e:" opt; do
    case ${opt} in
        p ) PARALLEL_JOBS=$OPTARG ;;
        d ) DEBUG_MODE=1 ;;
        a ) DOWNLOAD_ALL_PLUGINS='y' ;;
        l ) LIST_ONLY='y' ;;
        D ) DELAY_DOWNLOADS=$OPTARG ;;
        t ) DELAY_DURATION=$OPTARG ;;
        f ) FORCE_UPDATE='y' ;;
        c ) CACHE_ONLY='y' ;;
        s ) START_COUNT=$OPTARG ;;
        e ) END_COUNT=$OPTARG ;;
        \? ) echo "Usage: $0 [-p PARALLEL_JOBS] [-d] [-a] [-l] [-D DELAY_DOWNLOADS] [-t DELAY_DURATION] [-f] [-c] [-s START_COUNT] [-e END_COUNT]" 1>&2; exit 1 ;;
    esac
done

debug_log() {
    if [ "$DEBUG_MODE" -eq 1 ]; then
        echo "[DEBUG] $1" >&2
    fi
}

get_random_user_agent() {
    echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
}

get_latest_version_and_download_link() {
    local plugin=$1
    debug_log "Checking latest version and download link for $plugin"
    
    local api_url="https://api.wordpress.org/plugins/info/1.0/${plugin}.json"
    local user_agent=$(get_random_user_agent)
    local api_response=$(curl -s -H "User-Agent: $user_agent" "$api_url")
    
    if echo "$api_response" | jq -e '.error' >/dev/null; then
        local error_message=$(echo "$api_response" | jq -r '.error')
        if [ "$error_message" = "closed" ]; then
            echo "closed"
            return 2
        else
        echo "Error: $error_message for plugin $plugin" >&2
        return 1
        fi
    fi
    
    local version=$(echo "$api_response" | jq -r '.version // empty')
    local download_link=$(echo "$api_response" | jq -r '.download_link // empty')
    
    if [ -n "$version" ] && [ -n "$download_link" ]; then
        echo "$version $download_link"
        return 0
    else
        echo "Error: Cannot fetch version or download link for $plugin" >&2
        return 1
    fi
}

download_plugin() {
    local plugin=$1
    local version=$2
    local api_download_link=$3
    local output_file="${MIRROR_DIR}/${plugin}.${version}.zip"
    local header_file="${LOGS_DIR}/${plugin}.${version}.headers"
    local constructed_download_link="${DOWNLOAD_BASE_URL}/${plugin}.${version}.zip"
    local download_link

    if [ "$DEBUG_MODE" -eq 1 ]; then
        debug_log "API-provided download link for $plugin: $api_download_link"
        debug_log "Constructed download link for $plugin: $constructed_download_link"
    fi

    if [ "$DOWNLOAD_LINK_API" == 'y' ] && [ -n "$api_download_link" ]; then
        download_link="$api_download_link"
        debug_log "Using API-provided download link for $plugin: $download_link"
    else
        download_link="$constructed_download_link"
        debug_log "Using constructed download link for $plugin: $download_link"
    fi

    debug_log "Downloading $plugin version $version through Cloudflare Worker"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)
    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o /dev/null "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    else
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o "$output_file" "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    fi

    if [ $? -eq 0 ]; then
        if [ "$CACHE_ONLY" == 'y' ]; then
            debug_log "Plugin $plugin version $version cached successfully."
            return 0
        fi

        local file_size=$(stat -c%s "$output_file")
        if [ "$file_size" -lt 1000 ]; then
            echo "Error: Downloaded file for $plugin is too small (${file_size} bytes). Possible download issue." >&2
            return 1
        fi

        local source=$(grep -i "X-Source:" "$header_file" | cut -d' ' -f2 | tr -d '\r')
        if [ "$source" == "R2" ]; then
            debug_log "Successfully downloaded $plugin version $version from R2 storage"
        elif [ "$source" == "WordPress" ]; then
            debug_log "Successfully downloaded $plugin version $version from WordPress"
            debug_log "R2 bucket saving for plugin zip occurred"
        else
            debug_log "Skipped download for $plugin $version zip (already exists locally)"
        fi

        return 0
    else
        echo "Error: Failed to download $plugin version $version" >&2
        return 1
    fi
}

save_plugin_info() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.json"

    debug_log "Saving plugin json metadata for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying metadata download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    if [ "$CACHE_ONLY" == 'y' ]; then
        # When in cache-only mode, output to /dev/null
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin metadata for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache json metadata for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            if [ "$source" = "R2" ]; then
                debug_log "json metadata for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "json metadata for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin json occurred"
            else
                debug_log "json metadata for $plugin version $version saved (json metadata file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save json metadata for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

fetch_and_save_checksums() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.checksums.json"

    debug_log "Fetching and saving checksums for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying checksums download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    debug_log "Sending request to Worker for checksums: CF_WORKER_URL?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"

    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin checksums for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache checksums for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        debug_log "Received response with status code: $status_code"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            debug_log "Response source: $source"
            if [ "$source" = "R2" ]; then
                debug_log "Checksums for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "Checksums for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin checksums occurred"
            else
                debug_log "Checksums for $plugin version $version saved (checksums file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save checksums for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

process_plugin() {
    local plugin=$1
    plugin=$(echo "$plugin" | sed 's/^\/\|\/$//g')

    # Check if the plugin is already known to be closed
    if grep -q "^$plugin$" "$CLOSED_PLUGINS_FILE" 2>/dev/null; then
        echo "Plugin $plugin is known to be closed. Skipping."
        return 0
    fi

    echo "Processing plugin: $plugin"

    VERSION_AND_LINK=$(get_latest_version_and_download_link "$plugin")
    local version_check_status=$?
    
    if [ $version_check_status -eq 1 ]; then
        echo "Skipping $plugin due to version fetch error."
        return 1
    elif [ $version_check_status -eq 2 ]; then
        echo "Plugin $plugin is closed. Skipping download and processing."
        echo "$plugin" >> "$CLOSED_PLUGINS_FILE"
        if save_plugin_info "$plugin" "closed"; then
            debug_log "Successfully saved json metadata for closed plugin $plugin."
        else
            debug_log "Failed to save json metadata for closed plugin $plugin."
        fi
        return 0
    fi
    
    LATEST_VERSION=$(echo "$VERSION_AND_LINK" | cut -d' ' -f1)
    API_DOWNLOAD_LINK=$(echo "$VERSION_AND_LINK" | cut -d' ' -f2-)

    debug_log "Latest version for $plugin: $LATEST_VERSION"
    debug_log "API download link for $plugin: $API_DOWNLOAD_LINK"

    STORED_VERSION=$(grep "^$plugin" "$LAST_VERSION_FILE" | awk '{print $2}')
    debug_log "Stored version for $plugin: $STORED_VERSION"

    if [ "$CACHE_ONLY" != 'y' ] && [ "$LATEST_VERSION" == "$STORED_VERSION" ] && [ -f "${MIRROR_DIR}/${plugin}.${LATEST_VERSION}.zip" ]; then
        echo "$plugin is up-to-date and exists in mirror directory. Skipping download..."
    else
        start_time=$(date +%s.%N)

        if download_plugin "$plugin" "$LATEST_VERSION" "$API_DOWNLOAD_LINK"; then
            if [ "$CACHE_ONLY" != 'y' ]; then
                sed -i "/^$plugin/d" "$LAST_VERSION_FILE"
                echo "$plugin $LATEST_VERSION" >> "$LAST_VERSION_FILE"
            fi
            echo "Successfully processed $plugin."
        else
            echo "Error: Failed to process $plugin." >&2
        fi

        end_time=$(date +%s.%N)
        duration=$(echo "$end_time - $start_time" | bc)
        printf "Time taken for %s: %.4f seconds\n" "$plugin" "$duration"
    fi

    if save_plugin_info "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully saved json metadata for $plugin."
    else
        debug_log "Failed to save json metadata for $plugin."
    fi

    if fetch_and_save_checksums "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully fetched and saved checksums for $plugin."
    else
        debug_log "Failed to fetch and save checksums for $plugin."
    fi

    if [ $version_check_status -eq 0 ]; then
        echo "$plugin" >> "$OPENED_PLUGINS_FILE"
    fi
}

populate_all_plugins() {
    if [ ! -f "$ALL_PLUGINS_FILE" ] || [ "$LIST_ONLY" == 'y' ]; then
        echo "Fetching list of all WordPress plugins..."
        svn list https://plugins.svn.wordpress.org/ | sed 's/\/$//g' > "$ALL_PLUGINS_FILE"
        plugin_count=$(wc -l < "$ALL_PLUGINS_FILE")
        echo "Plugin list (${plugin_count}) saved to $ALL_PLUGINS_FILE"
    fi
    
    if [ "$LIST_ONLY" == 'n' ]; then
        ALL_PLUGINS=()
        if [ "$DOWNLOAD_ALL_PLUGINS" == 'y' ] && [ $START_COUNT -gt 0 ] && [ $END_COUNT -ge $START_COUNT ]; then
            echo "Processing plugins from line $START_COUNT to $END_COUNT"
            while IFS= read -r line; do
                ALL_PLUGINS+=("$line")
            done < <(sed -n "${START_COUNT},${END_COUNT}p" "$ALL_PLUGINS_FILE")
        else
            while IFS= read -r line; do
                ALL_PLUGINS+=("$line")
            done < "$ALL_PLUGINS_FILE"
        fi
        echo "Loaded ${#ALL_PLUGINS[@]} plugins."
    fi
}

if [ "$LIST_ONLY" == 'y' ]; then
    populate_all_plugins
    echo "Plugin list created. Exiting without downloading."
    exit 0
fi

if [ "$DOWNLOAD_ALL_PLUGINS" == 'y' ]; then
    populate_all_plugins
    COMBINED_PLUGINS=("${ALL_PLUGINS[@]}")
else
    if [ ! -d "$PLUGIN_DIR" ]; then
        echo "Warning: Plugin directory $PLUGIN_DIR does not exist or is invalid."
        PLUGIN_LIST=()
    else
        PLUGIN_LIST=($(ls -d "$PLUGIN_DIR"/*/ 2>/dev/null | xargs -n 1 basename))

        if [ ${#PLUGIN_LIST[@]} -eq 0 ]; then
            echo "No plugins found in $PLUGIN_DIR."
        fi
    fi

    COMBINED_PLUGINS=(${PLUGIN_LIST[@]} ${ADDITIONAL_PLUGINS[@]})
    COMBINED_PLUGINS=($(echo "${COMBINED_PLUGINS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
fi

if [ ${#COMBINED_PLUGINS[@]} -eq 0 ]; then
    echo "No plugins to download. Exiting."
    exit 0
fi

mkdir -p "$MIRROR_DIR"
touch "$LAST_VERSION_FILE"

if [ "$PARALLEL_JOBS" -gt 1 ]; then
    echo "Running in parallel with $PARALLEL_JOBS jobs..."
    echo "Variables before export:"

    # WordPress-related directories
    echo "WORDPRESS_WORKDIR: $WORDPRESS_WORKDIR"
    echo "PLUGIN_DIR: $PLUGIN_DIR"
    echo "MIRROR_DIR: $MIRROR_DIR"
    echo "LOGS_DIR: $LOGS_DIR"

    # Cloudflare Worker related URLs
    echo "CF_WORKER_URL: $CF_WORKER_URL"

    # Flags and options
    echo "DOWNLOAD_LINK_API: $DOWNLOAD_LINK_API"
    echo "DOWNLOAD_ALL_PLUGINS: $DOWNLOAD_ALL_PLUGINS"
    echo "LIST_ONLY: $LIST_ONLY"
    echo "DELAY_DOWNLOADS: $DELAY_DOWNLOADS"
    echo "DELAY_DURATION: $DELAY_DURATION"
    echo "FORCE_UPDATE: $FORCE_UPDATE"
    echo "CACHE_ONLY: $CACHE_ONLY"

    # File paths
    echo "OPENED_PLUGINS_FILE: $OPENED_PLUGINS_FILE"
    echo "CLOSED_PLUGINS_FILE: $CLOSED_PLUGINS_FILE"
    echo "LAST_VERSION_FILE: $LAST_VERSION_FILE"
    echo "ALL_PLUGINS_FILE: $ALL_PLUGINS_FILE"

    # Parallel job configuration
    echo "PARALLEL_JOBS: $PARALLEL_JOBS"

    # User Agents mapping
    echo "USER_AGENTS: ${USER_AGENTS[@]}"

    # Additional plugins to be processed
    # echo "ADDITIONAL_PLUGINS: ${ADDITIONAL_PLUGINS[@]}"

    # Plugin List (loaded from directory or ALL_PLUGINS_FILE)
    #echo "PLUGIN_LIST: ${PLUGIN_LIST[@]}"
    #echo "COMBINED_PLUGINS: ${COMBINED_PLUGINS[@]}"

    # First, export all variables including USER_AGENTS
    export DOWNLOAD_BASE_URL MIRROR_DIR LAST_VERSION_FILE DEBUG_MODE DOWNLOAD_LINK_API LOGS_DIR ALL_PLUGINS_FILE DOWNLOAD_ALL_PLUGINS LIST_ONLY CF_WORKER_URL DELAY_DOWNLOADS DELAY_DURATION FORCE_UPDATE CACHE_ONLY WORDPRESS_WORKDIR PLUGIN_DIR PARALLEL_JOBS OPENED_PLUGINS_FILE CLOSED_PLUGINS_FILE USER_AGENTS

    # Then, export the functions
    export -f process_plugin get_latest_version_and_download_link download_plugin debug_log populate_all_plugins save_plugin_info get_random_user_agent fetch_and_save_checksums
    printf "%s\n" "${COMBINED_PLUGINS[@]}" | xargs -P $PARALLEL_JOBS -I {} bash -c 'process_plugin "$@"' _ {}
else
    for plugin in "${COMBINED_PLUGINS[@]}"; do
        process_plugin "$plugin"
    done
fi

if [ "$DOWNLOAD_ALL_PLUGINS" == 'y' ]; then
    if [ -f "$CLOSED_PLUGINS_FILE" ]; then
        echo
        echo "Closed Plugin List: $CLOSED_PLUGINS_FILE"
        echo "Total closed plugins: $(wc -l < "$CLOSED_PLUGINS_FILE")"
    else
        echo
        echo "No closed plugins found."
    fi
    if [ -f "$OPENED_PLUGINS_FILE" ]; then
        echo
        echo "Opened Plugin List: $OPENED_PLUGINS_FILE"
        echo "Total opened plugins: $(wc -l < "$OPENED_PLUGINS_FILE")"
    else
        echo
        echo "No open plugins found."
    fi
fi
echo "Plugin download process completed."
