#!/bin/bash

# Base directory (script location)
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Configurable directories
WORDPRESS_WORKDIR="${WORDPRESS_WORKDIR:-$BASE_DIR/wordpress-plugins}"
PLUGIN_DIR="${PLUGIN_DIR:-$BASE_DIR/wp-content/plugins}"
MIRROR_DIR="${MIRROR_DIR:-$BASE_DIR/mirror}"
LOGS_DIR="${LOGS_DIR:-$BASE_DIR/plugin-logs}"

# Check for CF_WORKER_URL environment variable
if [ -z "$CF_WORKER_URL" ]; then
    echo "Error: CF_WORKER_URL environment variable is not set." >&2
    exit 1
fi

DOWNLOAD_BASE_URL="https://downloads.wordpress.org/plugin"

# Other variables
DOWNLOAD_LINK_API='y'

ADDITIONAL_PLUGINS=(
    "simplegal"
    "gamipress-reset-user"
    "post-admin-word-count"
    "cbrcurrency"
    "cross-registration-integration"
    "woocommerce-for-salesautopilot"
    "show-me-options"
    "master-post-password"
    "invition-print-ship"
    "order-status-for-woocommerce"
    "bp-gdpr"
    "list-sp-500-constituents-financials"
    "free-responsive-iframe-video-embeds"
    "smooth-accordion"
    "wordpress-signature"
    "emsb-service-booking"
    "wp-logout-redirect"
    "stop-registration-spam"
    "story-show-gallery"
    "woo-paypal-express-checkout"
    "db-tables-importexport"
    "cubeaccount"
    "night-eye"
    "login-me-now"
    "breadcrumb-tmc"
    "generate-disable-mobile"
    "horeka-core"
    "replymail"
    "post-volume-stats"
    "shouty"
    "readability-buttons"
    "memory-usage-bar"
    "absolute-to-relative-urls"
    "snippy"
    "woocommerce-sales-by-country"
    "gantry-export-import-options"
    "simple-load-more"
    "favepay-for-woocommerce"
    "aph-prism-highlighter"
    "e-signature-rtl-right-to-left"
    "wc-sales-notification"
    "woo-media-api"
    "simple-redirection-for-contact-form-7"
    "bucket-list"
    "dt-booking-manager"
    "come-back"
    "getresponse-footer-slideup"
    "press-release-distribution"
    "genolve-toolkit"
    "wp-e-commerce-sample-shipping-module"
    "acychecker"
    "random-gallery"
    "migrate-shopify-to-woocommerce"
    "codechief"
    "custom-call-to-action-block"
    "neptune-real-estate"
    "remove-category-word-from-title"
    "aki-toolset"
    "fuvar-hu-api"
    "url-rewrite-analyzer"
    "dpd-cart"
    "elevio"
    "access-control-by-category"
    "zazzle-widget"
    "connections-business-directory-hobbies"
    "pride-bar"
    "country-caching-extension-for-wp-super-cache"
    "yphplista"
    "jwd-postslider-widget"
    "wpfactory-conditional-shipping-for-woocommerce"
    "marin-companion"
    "codepen-oembed"
    "woocommerce-flipper"
    "orange-front-page"
    "sms-gateway-center-bulk-sms-sender"
    "woo-products-masonry-grid"
    "simple-widget-title-links"
    "mail-nachricht"
    "post-series"
    "latepoint-manager"
    "jupdf-pdf-viewer"
    "bp-beta-tester"
    "statsfc-score-predictor"
    "loginshield"
    "bp-order-date-time-for-woocommerce"
    "user-data"
    "tango-smilies"
    "wpc-additional-variation-images"
    "content-fetcher"
    "skype-share-button"
    "metamagic"
    "crypto-qr-code-wp"
    "publish-confirm-message"
    "apm-child"
    "review-content-type"
    "mypace-custom-meta-robots"
    "integrar-getnet-con-woo"
    "accessible-dropdown-menus"
    "user-access-expiration"
    "convoworks-wp"
    "view-shortcodes"
    "woo-codice-fiscale"
    "country-code-field-for-elementor-form"
    "documents-shortcode"
    "qr-scanner-redirect"
    "deezer-widget"
    "wp-open-hours"
    "generic-elements-for-elementor"
    "onsite-google-analytics-plugin"
    "counting-number-block"
    "socialmark"
    "simple-calendar-picker"
    "overwrite-author-name"
    "login-with-username-or-email"
    "show-user-registration-date"
    "baw-moderator-role"
    "wp-options"
    "global-meta-box-order"
    "wp-user-merger"
    "wp-planification"
    "tableberg"
    "take-notice"
    "simple-course-creator"
    "random-tweet-widget"
    "wp-accelerator-for-chinese"
    "columnizer"
    "rss-custom-fields"
    "biltorvet-dealer-tools"
    "faded-borders-for-images"
    "gabfire-media-module"
    "ssl-certificate-manager"
    "makeiteasy-back-to-top"
    "stonehenge-em-move-bookings"
    "avatars-for-comment-feeds"
    "social-feed-widgets-for-elementor-using-smash-balloon"
    "woo-ajax-cart-count"
    "mk-to-lat"
    "sitewide-admin-headerfooter"
    "plugin-activation-date"
    "wp-content-protection"
    "quick-demo-import"
    "lifterlms-lite-lms-progress-tracker"
    "html-global-lang-attribute"
    "bunnys-print-css"
    "wp-infusionsoft-woocommerce"
    "cpt-woo-integration"
    "cubewp-wallet"
    "jquery-post-preview"
    "filter-for-elementor"
    "mdc-theme-switcher"
    "indonesian-banks-for-woocommerce-free-version"
    "securepay"
    "edd-bitcoin-altcoin-payment-gateway"
    "de-social-login"
    "html-in-author-bio"
    "insert-code"
    "ultimate-sticky-posts"
    "wpantiddos"
    "wpp-elementor-addons"
    "gravatar-wordpress-plugin"
    "image-choices-for-gravity-forms"
    "statistics-website"
    "awesome-shortcodes-for-genesis"
    "list-articles"
    "grey-owl-lightbox"
    "ipb-comments-for-wordpress"
    "formula-1-countdown-widget"
    "attachment-slug"
    "bbpress-sort-topic-replies"
    "aph-merge-scripts"
    "crpaid-link-manager"
    "wc-product-feed-for-pinterest"
    "subaccounts-for-woocommerce"
    "rnwp-app-template-config"
    "vayu-blocks"
    "wishlist-and-compare"
    "my-friends-widgets-for-buddypress"
    "form-styles-for-contact-form-7"
    "image-projector"
    "z-downloads"
    "mailcastr-bot"
    "multi-site-plugins-add-new"
    "adcell-tracking-und-remarketing"
    "eelv-redirection"
    "wc-apg-city"
    "aws-cookies-popup"
    "two-dimensional-code"
    "apexchat"
    "rest-api-for-relevanssi"
    "soft79-wc-pricing-rules"
    "share-line-button"
    "woocommerce-stars-shortcode"
    "info-cards"
    "do-shortcodes-for-rank-math-seo"
    "tts-engine-post-to-speech"
    "cryptocurrency-coin-prices"
    "slope-widgets"
    "quick-press-widget"
    "custom-fields-permalink-redux"
    "server-monitor"
    "wp-fontallic-easypromoweb"
    "ipgp-visitors-origin"
    "hangeul-web-fonts"
    "insert-code-lite"
    "ipqualityscore-fraud-detection"
    "shopper"
    "link-verification-for-mastodon"
    "wp-imdb-api"
    "grayscale-images"
    "scrolling-anchors"
    "hyve-lite"
    "aioseo-multibyte-descriptions"
    "system-requirements-check"
    "secondary-product-image-for-woocommerce"
    "fygaro"
    "webpos-point-of-sale-for-woocommerce"
    "description-list-block"
    "simpler-checkout"
    "add-url-slugs-as-body-classes"
    "woorule"
    "debug-bar-screen-info"
    "stars-at-night"
    "columns-reordering-for-elementor"
    "vi-random-posts-widget"
    "any-ipsum"
    "fp-news-scroller"
    "musicidb-calendar"
    "multisite-maintenance-mode"
    "widgets-for-sourceforge-reviews"
    "wp-srvstatus"
    "advanced-heading"
    "simple-exclude-categories"
    "play-button"
    "simple-google-content-experiments"
    "easy-disable-visual-editor"
    "wp-geo-mashup-map"
    "super-widgets"
    "phpsword-disable-comments"
    "bruteguard"
    "woo-orange-money-payment-gateway-by-rc"
    "precious-metals-chart-and-widgets"
    "cookie-notice-lite"
    "calculate-bmr"
    "wysiwyg-button-manager"
    "wp-gzip"
    "pcloud-wp-backup"
    "random-user-ids"
    "cloodo-worksuite"
    "blogger-2-wp"
    "random-related-posts"
    "block-user-account"
    "gp-removed-powered-by"
    "wp-single-post-navigation-within-category"
    "intelly-welcome-bar"
    "dashpress"
    "art-woocommerce-custom-sale"
    "mail-crypter"
    "display-phpbb-forums"
    "wpc-brands"
    "apk-downloader"
    "engagebay-forms"
    "dynamic-background"
    "porsline"
    "admin-notice"
    "processingjs"
    "wptags-4-metakeywords"
    "codegear-starter"
    "quick-checkout-for-woocommerce"
    "show-private"
    "simple-iframe-buster"
    "kp-fastest-tidio-chat"
    "editorial-access-manager"
    "gestione-circolari-groups"
    "plugin-docs"
    "empty-p-tag"
    "tave-cf7-integration"
    "section-page"
    "yandex-pay"
    "rss-news-scroller"
    "carousel-3d-slider"
    "elite-accordion"
    "russian-date-by-axelnsk"
    "fat-coming-soon"
    "ecwid-widgets-avalanche"
    "realtyna-provisioning"
    "wc-order-pdf-download"
    "optimise-link-automation"
    "show-page-url-pages-all-pages"
    "paged-gallery"
    "elastic-slide"
    "go-high-level-extension-for-gravity-form"
    "recently-edited-content-widget"
    "woo-paytalk-kopokopo-gateway"
    "meridian-one-features"
    "wp-map-route-planner"
    "job-board-light"
    "plugin-optimizer"
    "private-post-by-default"
    "weather-slider"
    "guteblock"
    "button-group"
    "interactive-promo"
    "gdpr-cookies-pro"
    "wp-theme-exporter"
    "podamibe-advertisement-management"
    "wp-external-links-bar"
    "regione-provincia-comune"
    "supaz-easy-background"
    "dynamic-year-block"
    "wpcas"
    "membermouse-addon-for-wp-courseware"
    "smart-posts-widget"
    "skysa-youtube-videos-app"
    "sanremo-trails"
    "stop-comment-spam"
    "wp-youku"
    "yedpay-for-woocommerce"
    "total-users"
    "wp-odoo-form-integrator"
    "show-authors-without-posts"
    "reactflow-session-replay-heatmap"
    "connections-business-directory-facilities"
    "daves-whizmatronic-widgulating-calibrational-scribometer"
    "woo-customers-spreadsheet-bulk-edit"
    "bookeropl"
    "widget-contact-now"
    "connections-business-directory-certifications"
    "mycred-for-totalpoll"
    "fastpixel-website-accelerator"
    "media-playback-speed"
    "horoscope-and-tarot"
    "wpx-google-analytics"
    "simple-event-list"
    "camptix-pagseguro"
    "cigicigi-post-guest"
    "qq-weibo-plugin-for-wordpress"
    "cawaii-admin"
    "lsx-search"
    "audiotube"
    "disable-block-editor"
    "simple-cpt"
    "artificial-intelligence-auto-content-generator"
    "wc-blacklist-manager"
    "sermon-manager-import"
    "kevins-plugin"
    "oms-sidebar-widgets"
    "mootools"
    "wp-redis-user-session-storage"
    "stable-diffusion"
    "wprecovery"
    "wp-roulette-wheel"
    "uix-products"
    "picgrab"
    "preload-fullpage-cache"
    "wp-admin-classic"
    "simple-html-rich-text-for-block-editor"
    "woo-disable-email-notifications"
    "pingmeter-uptime-monitoring"
    "wp-custom-post-rss-feed"
    "acf-range-field"
    "photographers-galleries"
    "lazyload-background-images"
    "magazi-admin-theme"
    "utech-world-time-for-wp"
    "title-icon"
    "jellybox"
    "easy-custom-cssjs"
    "wp-dbmyadmin"
    "dashboard-cleaner"
    "twicpics"
    "am-quick-contact-box"
    "pjw-query-child-of"
    "open-web-analytics-plugin"
    "remove-double-space"
    "rankingbadge"
    "free-gifts-product-for-woocommerce"
    "adsimple-cookie-manager-for-wp"
    "wapuuvatar"
    "wp-wiki-userprofile"
    "customize-external-links-and-add-icon"
    "woo-product-pricing-tables"
    "wp-google-calendar"
    "appten-image-rotator"
    "wp-notify"
    "crypto-dash-tracker"
    "autocomplete-wc-order-status"
    "server-security-scan"
    "i-toolbar"
    "add-to-cart-button-custom-text-and-color"
    "heartland-secure-submit-addon-for-gravity-forms"
    "swf-upload-enabler"
    "small-package-quotes-fedex-edition"
    "ios-alternate-theme"
    "detect-adblock"
    "ultimate-tabbed-widgets"
    "https-to-http-redirect"
    "vk-ads-pixel"
    "wmf-mobile-redirector"
    "cc-circle-progress-bar"
    "duplicate-posts"
    "quick-navigation-interface"
    "gosign-simple-teaser-block"
    "eth-redirect-to-latest-post"
    "tt-post-viewer"
    "which-template-am-i"
    "monetbil-woocommerce-gateway"
    "disable-automatic-updates"
    "imagenius"
    "capitalize-my-title"
    "virus-activity"
    "filter-plus"
    "shortcake-bakery"
    "disable-password-reset-extended"
    "bp-group-control"
    "webp-express-plus"
    "post-featured-image-generator"
    "bsf-changelog"
    "wp-heading-buttons"
    "abbreviation-button-for-tinymce"
    "embed-comment-images"
    "simplesocial"
    "redirect-404-to-parent"
    "easy-leads-free"
    "twochop-games"
    "autofastindex"
    "wp-flexslider-shortcodes"
    "active-directory-employee-list"
    "elementify-visual-widgets"
    "sprout-invoices-gravity-forms"
    "wp-post-type-template"
    "woocommerce-hide-category-counter-by-nunoappscom"
    "moving-users"
    "calculate-prices-based-on-distance-for-woocommerce"
    "lemon-squeezy"
    "bea-fix-loco-translate"
    "timeline-designer"
    "simply-login-regiser"
    "getpaid-item-inventory"
    "liquid-rwd-plus"
    "jw-player-snapshot-tool"
    "better-bp-registration"
    "amazon-context-link-ads"
    "php-server-configuration"
    "dev-debug-tools"
    "modern-addons-elementor"
    "search-widget-post-types-for-elementor"
    "pricing-table-for-elementor"
    "carts-guru"
    "limit-login-countries"
    "audio-widget"
    "somatic-framework"
    "publisher-media-kit"
    "simple-tabs-shortcodes"
    "woocommerce-webship-integrated-quoting"
    "kantbtrue-about-me"
    "resmio-button-and-widget"
    "tabbed-account-area-for-easy-digital-downloads"
    "plenigo"
    "wp-3d-thingviewer-lite"
    "wp-simple-redirect"
    "display-future-posts"
    "constellation-client-portal"
    "cashflows-payments-by-ideal-checkout"
    "lang-attribute"
    "octolize-royal-mail-shipping"
    "my-popular-posts-widget"
    "ecpay-ecommerce-for-woocommerce"
    "opensheetmusicdisplay"
    "wc-free-shipping"
    "add-custom-fields-to-media"
    "vkontakte-group-wall-publisher"
    "woo-stripe-fee-in-report"
    "automattic-for-agencies-client"
    "time-based-greeting"
    "partial-cod-payment-gateway-restrictions-fees"
    "pico"
    "ajaxify"
    "dx-plugin-base"
    "cardanopress"
    "gotham-block-extra-light"
    "designo"
    "wpc-variation-bulk-editor"
    "yoycol-print-on-demand"
    "wp-table-tag-gen"
    "openagenda"
    "daisycon-woocommerce-pixel"
    "awesome-wp-widget-newsticker"
    "lockets"
    "breadcrumbs-shortcode"
    "guten-forms-mailpoet"
    "conditional-logic-for-woo-product-add-ons"
    "improved-gallery"
    "webdesignby-recaptcha"
    "takbull-gateway"
    "belingogeo"
    "add-on-cf7-for-airtable"
    "flash-media-playback"
    "wp-after-login-redirect-advanced"
    "flipboard-magazine-widget"
    "random"
    "amp-sidebar-hamburger-menu"
    "kiwichat"
    "shopvote"
    "mlm-soft-integration"
    "wptemplata"
    "force-user-login-multisite"
    "agile-crm-contact-form-7-forms"
    "confirm-publishing-actions"
    "opencart-product-display"
    "wp-plotly"
    "meta-seo"
    "http-header-authentication-for-application-passwords"
    "saeid-simple-text-rotator"
    "sermonaudio-widgets"
    "amcharts-embed"
    "post-access-controller"
    "simple-post-slider"
    "twitter-hashtag-feed-widget"
    "list-child-pages-shortcode"
    "fanbridge-signup"
    "wasa-kredit-checkout"
    "list-children"
    "themedy-widgets"
    "locus"
    "product-quantity-updater"
    "average-mobile-detect"
    "wow-guild"
    "wp-clear-rss-cache"
    "smspilot-ru-woocommerce"
    "twitchpress"
    "login-with-mobile-number-for-woocommerce"
    "migrate-wp-cron-to-action-scheduler"
    "ih-sliders-showcases"
    "wp-smart-security"
    "community-cloud"
    "authentication-code"
    "fs-shopping-cart"
    "easy-sticky-buttons"
    "app-for-cf"
    "wp-foundation-shortcodes"
    "flip-box-carousel"
    "fancytabs"
    "latest-news-marquee"
    "wp-time-slots-availability-calendar"
    "paste-as-plain-text-by-default"
    "wp-mmenu-lite"
    "mata-hoygan"
    "wp-cdnjs"
    "jomniaga-ad-manager"
    "taxonomy-term-listing-visual-composer-addon"
    "wc-affiliate"
    "wp-latestphotos"
    "lazy-load-enhanced"
    "mage-forms"
    "wp-spotlight-search"
    "force-publish-schedule"
    "embed-power-bi-reports"
    "better-bandsintown"
    "conflict-finder-wp-fix-it"
    "contact-form-pdf-extension"
    "bp-admin-actions"
    "responsive-twitter-widget"
    "buddypress-profile-rating"
    "my-upload-images"
    "google-maps-photo-gallery"
    "soundcloud-latest-tracks"
    "wp-hefo"
    "woo-elite-licenser-addon"
    "grayscale-body"
    "comment-inbox"
    "wp-remote-site-search"
    "advanced-cf7-database"
    "htaccess-login-block"
    "edd-drip"
    "recent-featured-posts-widget"
    "featured-podcast-widget"
    "wceazy"
    "scb-framework"
    "best-local-seo-tools"
    "email-post-activation"
    "wp-to-android-app"
    "mass-ping-tool-for-seo"
    "term-taxonomy-converter"
    "dummy-images"
    "pootle-button"
    "jim-soft-swiss-qr-invoice"
    "infunding"
    "sitepact-klaviyo-contact-form-7"
    "upload-quota-per-user"
    "wordpress-goodreads-bookshelf"
    "social-media-with-defered-javascript"
    "wp-mail"
    "cookiefox"
    "searchie"
    "oxygen-mydata"
    "wizart-home-interior-design-solutions"
    "cleancode-exclude-pages"
    "edit-category-slug"
    "woo-yubikey"
    "fullsteam-gateway"
    "gmapsmania"
    "cryptocurrency-widgets-from-coinlib"
    "twitter-image-host"
    "timer-countdown"
    "custom-css-wp"
    "jeero"
    "dirtysuds-embed-rss"
    "edit-post-link"
    "wpac-typing"
    "auto-files"
    "wordpress-snap"
    "block-background"
    "auto-search-suggestion"
    "ustream-status"
    "show-user-password"
    "disable-registration-email"
    "lock-reusable-blocks"
    "cm-subscriber-stats"
    "hide-products-count"
    "fyrebox-shortcode"
    "wp-branding"
    "mindvalley-pagemash"
    "travelfic-toolkit"
    "activity-log-tablepress"
    "wp-super-secure-and-fast-htaccess"
    "woo-local-pickup"
    "loginer-custom-login-page-builder"
    "manual-related-links"
    "members-blog"
    "live-theme-preview"
    "hello-in-all-languages"
    "acf-woocommerce-account-fields"
    "dg-real-media-library"
    "tailor-portfolio"
    "just-unzip"
    "press-this-new-post"
    "trade-rates-realtime"
    "vertical-diamond-flipbook-flash"
    "woo-product-table-lite"
    "multi-account-tweet-feeds-by-webline"
    "todays-date"
    "wp-image-uploader"
    "price-calculator"
    "diagnoseo"
    "addi-simple-slider"
    "whereabouts"
    "monero-woocommerce-gateway"
    "custom-fields-for-woo-customers"
    "wp-admin-search-meta"
    "amazing-hover-effects-for-wpbakery-page-builder"
    "alex-player"
    "advanced-chart-for-elementor"
    "eshop-invoice"
    "lessify-wp"
    "like-me-if-you-like-this-article"
    "numbers-generator-and-validator"
    "bbpress-notifications"
    "custom-pagination"
    "show-me-the-cookies"
    "snap-finance-checkout"
    "pets"
    "acf-icomoon"
    "jheck-chat"
    "wp-alexa-flash-briefing"
    "twitterwidget"
    "facetwp-manipulator"
    "popupsmart"
    "analog-clock-widget"
    "optipic"
    "ni-payment-reminder-for-woocommerce"
    "gravity-forms-pdf"
    "logout-redirect"
    "event-clndr"
    "enable-theme-and-plugin-editor"
    "single-post-ads"
    "ecall"
    "big-snow-flakes"
    "delete-original-image"
    "smart-id"
    "upload-scanner"
    "reservit-hotel"
    "subscribe2-widget-hack"
    "nepali-date-utilities"
    "pressroom-by-newswire"
    "the-crypto-cashier-bridge-for-woocommerce"
    "wp-ultimate-gallery"
    "bp-fadmin"
    "fogm-messenger-web-chat"
    "add-youtube-video-to-media-library"
    "wp-faq-by-wpdonehere"
    "sidebar-post"
    "g-ffl-cockpit"
    "woo-donation"
    "auto-url"
    "the-daily-dilbert"
    "living-comments"
    "wp-responsive-faqs"
    "custom-access-roles"
    "mycred-buddyboss"
    "wp-simple-and-nice-preloader"
    "wp-cat2calendar"
    "disable-widget-block-editor"
    "wpb-woocommerce-show-sales-numbers"
    "our-profiles"
    "bonkers-addons"
    "wp-customer-feedback"
    "no-frills-prize-draw"
    "filterable-photo-gallery-beaver-builder-elementor"
    "review-widget-addon-for-elementor"
    "activitytime"
    "css-theme-override"
    "tiny-grid"
    "manage-enrollment-learndash"
    "fusion-extension-post-details"
    "remove-google-analytics-comments"
    "login-with-amazon"
    "simple-photo-sphere"
    "phzoom"
    "sso-for-azure-ad"
    "knight-lab-soundcite"
    "easy-digital-downloads-addon-for-wp-courseware"
    "wp-top-navigation"
    "wp-social-links"
    "solo-solis-product-import"
    "wp-block-revealer"
    "best-favicon"
    "goospress"
    "when-last-login-export-user-records"
    "woocommerce-duplicate-billing-address"
    "elevate-parent-category-template"
    "uptime-robot-widget"
    "admin-msg-board"
    "reorder-gallery"
    "easy-multiple-pages"
    "uncomplicated-seo"
    "gtext-widget"
    "woocommerce-safircod"
    "give-a-beer"
    "btcp-pay"
    "secret-content"
    "advanced-custom-fields-address-field-add-on"
    "subscribers-only-content"
    "am-lich"
    "bp-new-ui"
    "tools-engine"
    "buddypress-sitewide-featured-posts"
    "boot-modal"
    "error-notification"
    "twentyten-advanced-headers"
    "alkanecode"
    "next-watermark"
    "ultimate-newsletter"
    "edd-blockonomics"
    "paystack-add-on-for-gravity-forms"
    "advanced-post-search"
    "sm-dashboard-pages-navigator-tree"
    "wpjm-related-jobs"
    "enl-newsletter"
    "mapbox-for-wp-advanced"
    "affiliates-buddypress"
    "protected-post-personalizer"
    "copy-compass"
    "simple-photo-feed"
    "turitop-booking-system"
    "acf-button"
    "product-recommendations-custom-locations"
    "import-users-to-mailchimp"
    "cartpanda"
    "grayscale"
    "scripts-and-styles"
    "quick-and-easy-tweets"
    "skedmaker-online-scheduling"
    "dans-gdrive-viewer"
    "resume-page"
    "wordpress-comment-digg"
    "font-resizer-matching-theme-style"
    "wpml-comment-merging"
    "wp-svejo-net"
    "bulk-edit-for-woocommerce"
    "extension-manager"
    "user-page-and-post-tracking"
    "bootstrap-multi-language-responsive-gallery"
    "elex-discount-per-payment-method"
    "wc-shipos-delivery"
    "style-guide-checker"
    "call-to-action-bar"
    "tectite-forms"
    "remove-tools-menu"
    "multiple-sidebar-generator"
    "dmd-infinite-scroll"
    "wp-template-viewer"
    "product-lister-ebay"
    "bible-reading-plan"
    "conotoxia-payment-gateway"
    "pricelist-for-woocommerce"
    "country-blocker"
    "support-ticket"
    "content-mirror"
    "ultimate-admin-bar"
    "pet-adoption-listings"
    "wp-preload-pjax"
    "eewee-restaurant-menu"
    "daext-helpful"
    "custom-availability-for-woocommerce"
    "astickypostorderer-show-sticky"
    "buddypress-group-twitter"
    "ajax-filter-search"
    "embed-javascript"
    "blocks-grid-builder-for-bootstrap"
    "woo-shipping-method-rl-carriers"
    "subscribe-to-comments-reloaded-better-unsubscribe"
    "airstory"
    "podclankova-inzerce"
    "events-handler"
    "nifty-backups"
    "wp-google-latitude"
    "sureforms"
    "remove-w3c-validation-type-warnings"
    "unlimited-photos"
    "total-posts"
    "accordion-for-wp"
    "users-import-export-with-excel-for-wp"
    "realia-xml-csv-property-listings-import"
    "happyfox-helpdesk"
    "random-sentence-generator"
    "simple-tickets"
    "smart-tag-insert"
    "sb-chart-block"
    "idpay-for-edd"
    "real-simple-contact-form"
    "exalogic-oberon-hotel-reservation"
    "bu-versions"
    "submit-to-google-index-button"
    "automatic-post-date-filler"
    "resize-images-in-posts"
    "kickass-slider"
    "pryc-woocommerce-edit-all-orders"
    "pirobox-extended-for-wp-v10"
    "evangelizo"
    "icustomizer"
    "article-word-count-column"
    "simple-link-library"
    "list-posts-with-pingbacks-trackbacks"
    "wp-after-registration-redirect-user-advanced"
    "slate"
    "favorites-menu-manager"
    "dynamic-latest-post-in-nav-menu"
    "wp-over-network"
    "github-release-downloads"
    "tip-of-the-day"
    "tinymce-generic-wp-shortcode-editor"
    "wp-strong-password"
    "simple-static-google-maps"
    "wp-accounts"
    "sar-disable-rest-api"
    "discontinued-products"
    "very-simple-website-closed"
    "bloglovin-follow"
    "no-spam-at-all"
    "custom-word-cloud"
    "holiday-mode-for-woocommerce"
    "bbp-capabilities"
    "top-spammers"
    "f13-youtube-shortcode"
    "e-commerce-data-interchange"
    "tylr-slidr"
    "disk-usage"
    "colete-online"
    "bulk-term-editor"
    "custom-css"
    "years-ago-today"
    "openestate-php-wrapper"
    "genesis-grid"
    "rss-injection"
    "sparxpres-for-woocommerce"
    "gravity-forms-paystation-3-party-hosted"
    "live-shopping-video-streams"
    "chipbot"
    "sopa-blackout-plugin-for-wordpress"
    "themeid-caldera-form-to-slack"
    "quickemailverification"
    "kdisk"
    "disable-autosave"
    "real-sticky"
    "simple-login-notification"
    "random-post-ajax"
    "easy-admin-notification"
    "search-types-custom-fields-widget"
    "wc-style"
    "linkedin-lite"
    "allpost-contactform"
    "visit-site-link-enhanced"
    "storyftw"
    "klantenvertellen"
    "wp-js-impress"
    "drastic-table-manager"
    "tinymce-table"
    "custom-product-builder-for-woocommerce"
    "wp-adsense"
    "cryout-themeswitch"
    "lh-signing"
    "geo-multi-location-map"
    "hss-embed-streaming-video"
    "its-tracking-code"
    "auto-focus-keyword-for-seo"
    "https-image-fixer"
    "tp-postviews-count-popular-posts-widgets"
    "content-holder"
    "antispam"
    "wp-foft-loader"
    "radeet-pdf-embed"
    "wp-compress-mainwp"
    "link-sort"
    "order-notification-for-telegram"
    "ls-gtrans-widget"
    "cryptocurrency-shortcodes"
    "wp-head-optimizer"
    "easy-quotes"
    "feedaty-rating-for-woocommerce"
    "disable-wysiwyg"
    "affiliate-press"
    "html-widget"
    "awebsome-browser-selector"
    "fluidvids"
    "block-country"
    "order-notification-for-telegram-bot"
    "w3tc-auto-pilot"
    "this-or-that"
    "albumize"
    "mp-easy-icons"
    "custom-password-protected-text"
    "woo-audio-preview"
    "shopp-arrange"
    "progress-tracker"
    "nakiedy-darmowy-system-rezerwacji-online"
    "retro-winamp-block"
    "just-contact-form"
    "cf7-active-campaign"
    "f4-woocommerce-salutation-fields"
    "woocommerce-custom-field-product-search"
    "video-converter"
    "wp-hamburger"
    "add-html-extension-to-pages"
    "email-reminders"
    "fast-live-chat"
    "shortcode-toggle"
    "billplz-for-gravityforms"
    "ads-adder"
    "vwe-voorraadlijst"
    "woocommerce-globalpay"
    "easy-gallery"
    "ams-single-post-template-selector"
    "gs-youtube-gallery"
    "instapunchout"
    "stats-dashboard-for-coinpayments"
    "wp-google-street-view-shortcode"
    "multiple-gallery-on-post"
    "pdf-thumbnails-support-test"
    "easy-google-analytics-wp"
    "export-variable-products"
    "send-email-to-customer-on-cancelled-order-in-woocommerce"
    "sello-channelconnector"
    "create-qr-code-wordpress-plugin"
    "wp-ngrok"
    "easyshipper"
    "initchat"
    "bmi-adultkid-calculator"
    "indeed-apply-shortcode"
    "janeman-core"
    "feed-for-tiktok-shop"
    "nf-merge-tag-addon"
    "bbpress-canned-replies"
    "signature-widget-for-genesis"
    "ultimate-coupon-for-woocommerce"
    "wp-hashtags"
    "mejorcluster"
    "hide-generator-meta-tag"
    "volusion"
    "eazy-flickity-slider"
    "lead-champion-discover"
    "linkify-authors"
    "pagely-reseller-management"
    "simple-page-to-sidebar"
    "chinads-dropshipping-taobao-woocommerce"
    "schemaninja"
    "buddypress-backwards-compatibility"
    "blog-promotion"
    "wp-quick-setup"
    "registration-statistics"
    "bulk-sms"
    "custom-bulk-actions"
    "mediaelementjs-skin"
    "frontend-dashicons"
    "dp-alterminator-missing-alt-manager"
    "wc-easycredit"
    "admail"
    "mailmojo-widget"
    "wp-messenger-customer-chat"
    "gopay-gateway"
    "post-type-icons"
    "ijm-theme-bar"
    "woopos-gift-cards-for-woocommerce"
    "masjidal"
    "cc-canadian-mortgage-calculator"
    "tailored-lightbox"
    "mcw-pwa"
    "quick-google-analytics"
    "posts-date-ranges"
    "genesis-custom-post-types-archives"
    "automizely-returnscenter"
    "card-elements-for-wpbakery"
    "fetch-jft"
    "wp-email-newsletter"
    "tdd-debug-bar-post-meta"
    "date-calculator"
    "wc-remove-tabs-and-fields"
    "wp-responsive-holiday-events-calendar"
    "woopop-electronic-invoice-free"
    "acymailing-integration-for-gravity-forms"
    "as-heard-on"
    "wpdaddy-header-builder"
    "nix-anti-spam-light"
    "tinymce-youtube-embed"
    "magic-popups"
    "advanced-custom-fields-markdown"
    "wopo-cryptocurrency-widget"
    "libro-de-reclamaciones"
    "append-content"
    "keyword-panda-keyword-analyzer-for-seo"
    "filter-pages-by-parent-in-admin"
    "simple-product-sample-for-woocommerce"
    "event-post-type"
    "sociallist-social-bookmarking-widget"
    "wp-phone-number"
    "auto-date-year-month"
    "wp-timezone"
    "bitcoin-calculator-widget"
    "campayn-email-newsletter-sign-up"
    "repeater-field-for-wpforms"
    "portfolio-builder-awesome"
    "invisible-optin"
    "arrow-login-page"
    "content-syndication-toolkit"
    "tc-comment-out"
    "screenly-cast"
    "cf7-zoho-leads"
    "obox-mobile"
    "ade-custom-shipping"
    "mlr-audio"
    "wp-hrm-lite-human-resource-management-system"
    "xhtml-easy-validator"
    "blogware-importer"
    "persian-bbpress-tools"
    "robots-sitemap"
    "wc-carta-docente"
    "gdpr-compliance-tool"
    "wpc-smart-linked-products"
    "registered-user-sync-activecampaign"
    "live-forex-table"
    "ada2go-text-modules"
    "noindex-archives"
    "doordash-storefront"
    "wp-tithely"
    "plastic-tunes"
    "wp-tweet"
    "emailchef"
    "pricetable-wp"
    "zaki-like-dislike-comments"
    "soliloquy-scheduled-slides"
    "post-types-calendar"
    "portfolio-responsive-gallery"
    "wp-mybackup"
    "admin-author-filter"
    "clockify-lite"
    "baokimvn-payment-gateway-for-woocommerce"
    "xmlrpc-attacks-blocker"
    "cash-pickup"
    "keto-calculator"
    "music-store-stripe-add-on"
    "show-user-level-content"
    "moonclerk-wp-shortcode"
    "wp-avoid-slow"
    "photofade"
    "browser-compatibility"
    "block-guide-lines"
    "alert-box-block"
    "opcache-reset"
    "full-screen-morphing-search"
    "poros-slider"
    "caldera-smtp-mailer"
    "admin-post-tag-filter"
    "auto-save-remote-images-drafts"
    "better-admin-help-tabs"
    "elizaibot-chatbots"
    "wc-liqpay"
    "xml-sitemap-generator-by-kaboom"
    "woo-show-product-discount"
    "meta-tags-generator"
    "wordpress-logging-service"
    "analog-clock-wp-7"
    "visual-developer-custom-css"
    "avishi-wp-paypal-payment-button"
    "unagi"
    "hal-html-widget"
    "image-optimizer-for-google-lighthouse"
    "categories-but-exclude-widget"
    "small-package-quotes-ups-edition"
    "cf7-coder"
    "auto-link"
    "simplepage-sync-landing-page-for-web"
    "front-end-theme-preview"
    "gutena-star-ratings"
    "star-review-manager"
    "lana-sitemap"
    "12-step-meeting-list-feedback-enhancement"
    "training"
    "bulk-menu-edit"
    "multi-slider"
    "block-comment-spam-bots"
    "link-preview"
    "cm-faq"
    "wptab-tableau-public-viz-block"
    "snapengage"
    "tube-video-widget-using-post-meta"
    "cmb2-taxonomy"
    "cwidget-countdown"
    "embed-iphoneipad-app"
    "sagepay-form-gateway-for-woocommerce"
    "integrate-umami"
    "loginid-directweb"
    "pdf-forms-for-wpforms"
    "page-parts"
    "wpcasa-ninja-forms"
    "bitcoin-donations"
    "builderius"
    "wp-vanilla-connect"
    "wp-moo-tree"
    "html5-lyrics-karaoke-player"
    "square-sync"
    "woo-custom-products-widget"
    "community-gradebook"
    "extensible-widgets"
    "right-now-reloaded"
    "ux-sniff"
    "bybrick-columns"
    "zawgyi-embed"
    "disqus-recent-comments-widget-advanced"
    "peters-literal-comments"
    "edd-custom-checkout-fields"
    "html-new-user-notification-email"
    "plexx-elementor-extension"
    "howdy-tweaks"
    "digiwallet-for-woocommerce"
    "social-icons-for-woocoomerce-emails"
    "legal-news-headlines"
    "blue-admin-bar"
    "qr-code-and-barcode-scanner-reader"
    "flexible-slider"
    "multisite-post-reader"
    "mailgo"
    "fusion-extension-copyright"
    "passwords-manager"
    "easy-loyalty-points-and-rewards-for-woocommerce"
    "change-wp-empty-trash-time"
    "c4d-woo-bundle"
    "investment-calculator"
    "apollo-bar"
    "check-plagiarism"
    "site-template"
    "simple-contact-information-widget"
    "most-viewed-products-for-woocommerce"
    "shortcode-for-opentable"
    "export-em-events-to-csv"
    "automizely-dropshipping"
    "whmcs-domain-checker-widget"
    "header-footer-composer"
    "jeeng-push-notifications"
    "score-nco-widget"
    "cf7-mollie"
    "cross-domain-tracker-for-affiliatewp"
    "simple-website-logo"
    "pile-gallery"
    "improved-user-experience"
    "wp-admin-formatter-customize-admin-panel"
    "empty-plugin-template"
    "hide-anything"
    "block-editor-for-manychat"
    "aeropage-sync-for-airtable"
    "doubridge"
    "beforeafter-pictures"
    "bux-woocommerce"
    "jclocksgmt-wp"
    "profi-fotos-online"
    "youtube-playlist"
    "roknewsflash"
    "allow-shortcode-in-text-widgets"
    "theme-blvd-layouts-to-posts"
    "post-expiring"
    "importer-for-crocoblock-jetengine"
    "sidebar-widget-collapser"
    "options-view"
    "so-remove-wpml-menu-sync"
    "oc-hotjar"
    "charitydonation-thermometer"
    "tvg-xpress"
    "lj-multi-column-archive"
    "lsx-customizer"
    "admin-sms-alert"
    "bp-ninja"
    "woocommerce-epaybg"
    "ilike-social-media-optimization"
    "announcements"
    "magicpost"
    "style-admin"
    "fay-emails-encoder"
    "sort-my-sites"
    "cinza-grid"
    "acymailing-rss-content"
    "lsx-blog-customizer"
    "primer-mydata"
    "block-widget"
    "live-chat-skype"
    "clipart"
    "debug-printr"
    "simple-share"
    "html5-swiffy-insert"
    "configurable-hotlink-protection"
    "knit-pay-upi"
    "wp-global-screen-options"
    "minecraft-item-library"
    "easy-digital-downloads-lock-downloads-to-ip"
    "content-no-cache"
    "specify-a-vary-accept-encoding-header"
    "gd-power-search-for-bbpress"
    "bbp-anonymous-subscriptions"
    "a-to-z-category-navigation-widget"
    "database-backup"
    "toneden-player-shortcode"
    "vertycal"
    "wp-copy-data-protector"
    "cherry-picker"
    "corona"
    "turbo-admin"
    "jigoshop-basic-bundle-shipping"
    "schedule-content-block"
    "notfoundorg-404-page"
    "bin-stripe-donation"
    "rating-add"
    "wp-jv-custom-email-settings"
    "timeline-feed"
    "xpand-image-gallery"
    "ipgp-ip-address-lookup-widget"
    "advanced-invisible-anti-spam"
    "jason-birthday-widget"
    "ticketsource-events"
    "html-minify"
    "typing-animation-block"
    "mini-statistics"
    "filmgetter"
    "cookie-notify"
    "remove-wp-version-and-shortlink"
    "distance-based-shipping-calculator"
    "tinywebgallery-wrapper"
    "make-money-with-ad7biz-and-wp"
    "zielke-design-project-gallery"
    "sendpress-contact-form-7"
    "adpushup"
    "ai-assistant-elementor"
    "cocart-cors"
    "abbreviation-button-for-the-block-editor"
    "abc-notation"
    "vast-package"
    "domain-sharding"
    "animated-headline-visual-composer"
    "support-hours"
    "most-popular-posts-widget-lite"
    "dx-sales-crm"
    "auyautochat-for-wp"
    "azonpost"
    "css3-buttons"
    "wp-okta-authentication"
    "create-db-tables"
    "csv-wc-product-import-export"
    "simple-site-speed"
    "csv-viewer"
    "virtooal-try-on-mirror"
    "cdn-rewrites"
    "number-counter"
    "woo-prevent-cancel-order"
    "unauthorised-login-redirect"
    "personal-email"
    "hellowoofy-com"
    "r3df-multisite-language-indicator"
    "protectcopyblogs"
    "lightbulb-save-and-close"
    "lh-private-content-login"
    "multiple-payment-solutions-for-woocommerce"
    "developer-loggers-for-simple-history"
    "notice-block"
    "wp-cards"
    "nggtags-for-wp-media-library"
    "ink-own-you-content"
    "track-geolocation-of-users-using-contact-form-7"
    "sagepay-form-payment-gateway-for-gravity-forms"
    "wpsso-commerce-manager-catalog-feed"
    "coursestorm"
    "json-options"
    "truconversion-connect"
    "mega-forms"
    "gothamazon"
    "wp-revisions-manager"
    "wedesin-html-sitemap"
    "watsonfinds"
    "linktothispage"
    "google-badge-widget"
    "minimalistic-event-manager"
    "external-url-as-post-featured-image-thumbnail"
    "disable-privacy-tools"
    "embed-docs"
    "hm-logo-showcase"
    "more-mime-type-filters"
    "gpt-3-ai-content-generator"
    "random-post-on-refresh"
    "team-vcard-generator"
    "hire-me-widget"
    "table-rate-shipping-rates"
    "ad-maven"
    "lastfm-for-artists"
    "post-featured-font-icon"
    "axima-payment-gateway"
    "buddypress-password-strength-meter"
    "wpc-price-by-user-role"
    "abn-lookup-for-gravity-forms"
    "wp-zff-zend-framework-full"
    "manage-pages-custom-columns"
    "acf-repeater-editor-accordion"
    "sullivan-compatibility"
    "kolaykimlik"
    "wpmu-global-search"
    "upcoming-posts-widget"
    "wp-quicktags"
    "floating-menu-button-links"
    "open-beacon-mp4-conversion-and-compression"
    "jiangqie-official-website-mini-program"
    "repayment-calculator"
    "pauls-latest-posts"
    "custom-taxonomy-template"
    "featured-image-resize"
    "post-script-responsive-images"
    "first-visitor-message"
    "birdseed"
    "america-magazine-the-word"
    "buienradar"
    "review-wave-google-places-reviews"
    "oik-css"
    "theme-duplicator"
    "menu-rules"
    "websitechatnet-live-support"
    "chatrify-live-chat"
    "labinator-content-types-duplicator"
    "pixobe-coloring-book"
    "clickbank-sale-notification"
    "video-overlay-ads"
    "hide-it"
    "empty-paragraph-for-tinymce-editor"
    "simple-subscriber-signup-widget"
    "bp-activity-plus-styling"
    "all-in-one-wp-sticky-anything"
    "editor-theme-options"
    "xqueue-maileon"
    "flattr-widget"
    "wp-menu-custom-fields"
    "filter-admin-published-default"
    "lazy-sign-in"
    "simply-social-links"
    "wplm-worrpress-link-management"
    "single-author-g-meta"
    "outboundlinks"
    "ajax-load-more-rest-api"
    "rename-default-post"
    "book-preview-for-woocommerce"
    "wp-media-file-type-manager"
    "woo-quote-calculator-order"
    "pages-are-posts"
    "payday"
    "wg-twitter-widget"
    "bbsigpress"
    "meetup"
    "rsskingpro"
    "printcart-integration"
    "bbpress-reports"
    "wp-igoogle"
    "mojito-shipping"
    "get-background-from-library"
    "marquee-image-crawler"
    "dolyame-payment"
    "boldermail"
    "coinpaprika"
    "wp-badge"
    "buddypress-sitewide-notice-widget"
    "woo-alipay"
    "wp-social-share-buttons"
    "central-connect"
    "pandasms-for-woocommerce"
    "gold-price-based-on-weight"
    "listings-for-appfolio"
    "podcastify"
    "jet-quickpress"
    "add-google-plusone"
    "xisearch-bar"
    "woo-wolly-one-time-buy"
    "webyx-fe"
    "my-wp-glossary"
    "my-online-fashion-store"
    "wpmktgengine-extension-woocommerce"
    "image-auto-sync-oss"
    "call-now-coccoc-pht-blog"
    "skysa-scroll-to-top-app"
    "wp-mailerlite-lite"
    "comment-form-toolbar"
    "jsm-show-registered-shortcodes"
    "save-as-image-by-pdfcrowd"
    "empty-blog"
    "idpay-gateway-gravity-forms"
    "wp-simple-slideshow"
    "jsm-pretty-json-ld"
    "massive-sitemap-generator"
    "mcstatus"
    "so-customizer-hide-menu"
    "rootsrated-content-cloud"
    "mini-rss-reader"
    "foxload-firefox-download"
    "in-memoriam-light-a-candle"
    "simple-age-restriction-warning"
    "wcs-qr-code-generator"
    "debug-bar-post-meta"
    "bp-avatar-hover"
    "wp-remove-dashboard-extra-widgets"
    "wp-author-security"
    "onvo-pay"
    "cinema-seat-reservation-xcloud-pro"
    "mail-debug-for-woocommerce"
    "category-description-widget"
    "cf7-insightly"
    "rooom-3d-product-viewer"
    "th23-media-library-extension"
    "wp-postvoting"
    "bulk-actions"
    "imagefocuspoint"
    "tabs-recent-posts-vs-recent-comments"
    "openmeetings-integration-plugin-widget"
    "get-options"
    "better-writing"
    "atr-random-sku-for-woocommerce"
    "us-debt-clock-widget"
    "ewz-rating"
    "aweber-comment-optin"
    "i-dont-like-spam"
    "dp-rdfa-breadcrumb-generator"
    "virusweather"
    "elevate-seo"
    "webdome-importer-for-woocommerce"
    "copy-text-to-wechat"
    "latest-twitter-updates-with-date-and-time"
    "add-featuredimage-to-all-posts"
    "simple-https"
    "issuu-magazine-display"
    "hidden-posts"
    "qeryz-microsurvey-tool"
    "gm-woo-product-list-widget"
    "mobiloud-smart-app-banner"
    "wpgraphql-blocks"
    "wp-pleasewait"
    "utm-leads-tracker-lite"
    "iksweb-sitemap"
    "rss-image-resize"
    "search-attributes-for-woocommerce"
    "leadsnap"
    "nelio-compare-images"
    "default-category"
    "toolbar-extras-givewp"
    "follow-category-feeds"
    "logy"
    "awp-antivirus"
    "wp-shaper-image-and-text"
    "wp-simplemeetingconfirmation"
    "weather-forecast-widget"
    "datamentor"
    "instapago"
    "ultrapress"
    "thankyou-coupons-for-wc"
    "wp-flickrshow"
    "affiliates-manager-s2member-integration"
    "espn-headlines-widget"
    "multisite-featured-image"
    "dashboard-google-pagerank"
    "profiler-what-slowing-down"
    "g-smtp"
    "activate-users-in-buddypress"
    "posts-table-filterable"
    "commentmailer"
    "wp-social-share-privacy-plugin"
    "woo-attributes-coupon"
    "mortgage"
    "woo-multicaixa"
    "menu-item-types"
    "tweets-as-posts"
    "simple-video-gallery"
    "schedule-maintenance-mode"
    "rtpanel-hooks-editor"
    "wp-payment"
    "wpdoodlez"
    "ultimate-twitter-feeds"
    "lsx-mega-menus"
    "openid-connect-server"
    "payment-gateway-paypalme"
    "ns-ie-compatibility-fixer"
    "wp-filters"
    "spiceforms-form-builder"
    "wp-safely-disable-directory-browsing"
    "simple-discography"
    "weer"
    "html-entities-button"
    "text-to-speech-widget"
    "super-recent-posts-widget"
    "autonomos"
    "contactus"
    "contactsheets-lite"
    "safetag"
    "embed-post"
    "wc-planzer-shipping"
    "bibly"
    "anytrack-affiliate-link-manager"
    "text-message"
    "a5-recent-posts"
    "cf7-color-picker"
    "remove-taxonomy-slug"
    "events-manager-openstreetmap"
    "free-forms-and-crm"
    "video-user-manuals"
    "ogp-plus"
    "falang-for-divi-lite"
    "video-flv-converter"
    "target-visitors"
    "alfacoins-for-woocommerce"
    "grigora-kit"
    "wp-readme-parser"
    "inactivity-auto-sign-out-plugin"
    "shortcode-collection"
    "authorizenet-woocommerce-lightweight-addon"
    "custom-shortcode-sidebars"
    "logo-switcher-divi"
    "fiber-admin"
    "zd-header-tags"
    "slick-google-map"
    "ultimate-multi-design-video-carousel"
    "gallery-columns"
    "fantasy-football"
    "good-question"
    "annie"
    "title-animator"
    "jquery-notify"
    "stylish-links"
    "newsletter-signup"
    "robots-txt-quick-editor"
    "unicon-extensions"
    "wp-custom-cms-block"
    "mandatory-fields"
    "woo-solo-api"
    "wp-vibedeck"
    "woocommerce-super-simple-tax-exemption"
    "agregs-postget"
    "widget-download"
    "debug-bar-cache-lookup"
    "fc-retirement-nest-egg-calculator"
    "post-edit-toolbar"
    "secure-axs"
    "simple-comment-notification"
    "team-broadcast-status-list"
    "interactive-excel-tables"
    "debug-meta-data"
    "sb-banner-widget"
    "chimppress"
    "springboard-video-quick-publish"
    "yt-video-importer-lite"
    "cyberprojekt-image-watermark"
    "popularity-lists-widget"
    "better-management-reserved-stock-for-woocommerce"
    "oca-for-woocommerce"
    "dot-embed"
    "sharemacro"
    "wpsyncsheets-wpforms"
    "default-displayname"
    "inject-query-posts"
    "simple-alert-blocks"
    "dc-nagad"
    "multidomain-multitheme"
    "youtubenails"
    "same-but-different"
    "wp-login-customizer"
    "fp-responsive-slider"
    "buddypress-xml-rpc-receiver"
    "vg-woocarousel"
    "securesubmit"
    "coolwp-pinyin-attachment-name"
    "fast-cart"
    "similar-post-title-checker"
    "themes-speed-test"
    "ecommerce-user-profiles-by-profilegrid"
    "ns-custom-placeholder-image-for-woocommerce"
    "wp-no-frames"
    "photofeed-block-by-gutena"
    "strasho"
    "junkie-content-types"
    "review-schema-markup"
    "social-network-user-detection"
    "linepay-wc"
    "it-listings"
    "most-popular-categories"
    "email-javascript-cloaker"
    "matprat-share"
    "christmas-snow-fall"
    "gf-no-duplicates"
    "cf7-email-body-tinymce-editor"
    "image-slider-block"
    "tailor-woocommerce"
    "baw-better-admin-color-themes"
    "welamazonadds"
    "net-neutrality"
    "jubelio-shipment"
    "helpgent"
    "media-author"
    "wp-news-slider-widgets"
    "roomcloud"
    "wp-chords"
    "validbot"
    "fury-core"
    "rapid-secure-login"
    "ts-webfonts-for-z-com"
    "relative-url-shortcode"
    "development-theme"
    "ltl-freight-quotes-ups-edition"
    "paypal-target-meter"
    "cf7-translate-messages-extension"
    "oik-bwtrace"
    "revive-so"
    "seo-query"
    "bitcoins-and-litecoin-for-wp-woocommerce"
    "ratemyagent-official"
    "repeat-order-button-for-woocommerce"
    "easy-circle-content"
    "ultracart-ecommerce-shopping-cart"
    "artist-image-generator"
    "md5-media-renamer"
    "kf-most-read"
    "liquid-connect"
    "display-good-reads-books"
    "chargify"
    "wp-sms-notifications"
    "wsw-import-export-ecommerce-integration"
    "wp-admin-custom-page"
    "live-ticker-cryptocoin"
    "calculation-for-contact-form-7"
    "horizontal-slider-with-scroll"
    "awesome-responsive-photo-gallery"
    "awstats-script"
    "participad"
    "socius-marketing-page-taxonomy"
    "wp-notes-remover"
    "social-glutton"
    "beastthemes-companion"
    "tags-autolink"
    "buddypress-preklad"
    "posts-columns-manager"
    "autoload-checker"
    "spotlightr"
    "partners-banners"
    "edd-external-products"
    "mindvalley-include-content"
    "argiope-amoena"
    "shortcodes-in-widgets"
    "simplesitemap"
)

# Define user agents with weights
declare -A USER_AGENTS
USER_AGENTS=(
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"]=5
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"]=7
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"]=6
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36 Edg/91.0.864.54"]=5
    ["Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 OPR/77.0.4054.277"]=3
    ["Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (iPad; CPU OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Vivaldi/4.0"]=1
    ["Mozilla/5.0 (Android 11; Mobile; rv:68.0) Gecko/68.0 Firefox/88.0"]=1
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"]=15
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/534.36"]=12
)

LAST_VERSION_FILE="${WORDPRESS_WORKDIR}/last_versions.txt"
PARALLEL_JOBS=1

DOWNLOAD_ALL_PLUGINS='n'
LIST_ONLY='n'
ALL_PLUGINS_FILE="${WORDPRESS_WORKDIR}/wp-plugin-svn-list.txt"

DELAY_DOWNLOADS='n'
DELAY_DURATION=5

FORCE_UPDATE='n'
CACHE_ONLY='n'

mkdir -p "$WORDPRESS_WORKDIR" "$MIRROR_DIR" "$LOGS_DIR"
DEBUG_MODE=0

while getopts "p:dalD:t:fc" opt; do
    case ${opt} in
        p ) PARALLEL_JOBS=$OPTARG ;;
        d ) DEBUG_MODE=1 ;;
        a ) DOWNLOAD_ALL_PLUGINS='y' ;;
        l ) LIST_ONLY='y' ;;
        D ) DELAY_DOWNLOADS=$OPTARG ;;
        t ) DELAY_DURATION=$OPTARG ;;
        f ) FORCE_UPDATE='y' ;;
        c ) CACHE_ONLY='y' ;;    # New option for cache-only
        \? ) echo "Usage: $0 [-p PARALLEL_JOBS] [-d] [-a] [-l] [-D DELAY_DOWNLOADS] [-t DELAY_DURATION] [-f] [-c]" 1>&2; exit 1 ;;
    esac
done

debug_log() {
    if [ "$DEBUG_MODE" -eq 1 ]; then
        echo "[DEBUG] $1" >&2
    fi
}

get_random_user_agent() {
    echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
}

get_latest_version_and_download_link() {
    local plugin=$1
    debug_log "Checking latest version and download link for $plugin"
    
    local api_url="https://api.wordpress.org/plugins/info/1.0/${plugin}.json"
    local user_agent=$(get_random_user_agent)
    local api_response=$(curl -s -H "User-Agent: $user_agent" "$api_url")
    
    if echo "$api_response" | jq -e '.error' >/dev/null; then
        local error_message=$(echo "$api_response" | jq -r '.error')
        if [ "$error_message" = "closed" ]; then
            echo "closed"
            return 2
        else
        echo "Error: $error_message for plugin $plugin" >&2
        return 1
        fi
    fi
    
    local version=$(echo "$api_response" | jq -r '.version // empty')
    local download_link=$(echo "$api_response" | jq -r '.download_link // empty')
    
    if [ -n "$version" ] && [ -n "$download_link" ]; then
        echo "$version $download_link"
        return 0
    else
        echo "Error: Cannot fetch version or download link for $plugin" >&2
        return 1
    fi
}

download_plugin() {
    local plugin=$1
    local version=$2
    local api_download_link=$3
    local output_file="${MIRROR_DIR}/${plugin}.${version}.zip"
    local header_file="${LOGS_DIR}/${plugin}.${version}.headers"
    local constructed_download_link="${DOWNLOAD_BASE_URL}/${plugin}.${version}.zip"
    local download_link

    if [ "$DEBUG_MODE" -eq 1 ]; then
        debug_log "API-provided download link for $plugin: $api_download_link"
        debug_log "Constructed download link for $plugin: $constructed_download_link"
    fi

    if [ "$DOWNLOAD_LINK_API" == 'y' ] && [ -n "$api_download_link" ]; then
        download_link="$api_download_link"
        debug_log "Using API-provided download link for $plugin: $download_link"
    else
        download_link="$constructed_download_link"
        debug_log "Using constructed download link for $plugin: $download_link"
    fi

    debug_log "Downloading $plugin version $version through Cloudflare Worker"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)
    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o /dev/null "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    else
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o "$output_file" "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    fi

    if [ $? -eq 0 ]; then
        if [ "$CACHE_ONLY" == 'y' ]; then
            debug_log "Plugin $plugin version $version cached successfully."
            return 0
        fi

        local file_size=$(stat -c%s "$output_file")
        if [ "$file_size" -lt 1000 ]; then
            echo "Error: Downloaded file for $plugin is too small (${file_size} bytes). Possible download issue." >&2
            return 1
        fi

        local source=$(grep -i "X-Source:" "$header_file" | cut -d' ' -f2 | tr -d '\r')
        if [ "$source" == "R2" ]; then
            debug_log "Successfully downloaded $plugin version $version from R2 storage"
        elif [ "$source" == "WordPress" ]; then
            debug_log "Successfully downloaded $plugin version $version from WordPress"
            debug_log "R2 bucket saving for plugin zip occurred"
        else
            debug_log "Skipped download for $plugin $version zip (already exists locally)"
        fi

        return 0
    else
        echo "Error: Failed to download $plugin version $version" >&2
        return 1
    fi
}

save_plugin_info() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.json"

    debug_log "Saving plugin json metadata for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying metadata download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    if [ "$CACHE_ONLY" == 'y' ]; then
        # When in cache-only mode, output to /dev/null
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin metadata for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache json metadata for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            if [ "$source" = "R2" ]; then
                debug_log "json metadata for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "json metadata for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin json occurred"
            else
                debug_log "json metadata for $plugin version $version saved (json metadata file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save json metadata for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

fetch_and_save_checksums() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.checksums.json"

    debug_log "Fetching and saving checksums for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying checksums download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    debug_log "Sending request to Worker for checksums: CF_WORKER_URL?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"

    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin checksums for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache checksums for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        debug_log "Received response with status code: $status_code"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            debug_log "Response source: $source"
            if [ "$source" = "R2" ]; then
                debug_log "Checksums for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "Checksums for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin checksums occurred"
            else
                debug_log "Checksums for $plugin version $version saved (checksums file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save checksums for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

process_plugin() {
    local plugin=$1

    # Check if the plugin is already known to be closed
    if grep -q "^$plugin$" "$CLOSED_PLUGINS_FILE" 2>/dev/null; then
        echo "Plugin $plugin is known to be closed. Skipping."
        return 0
    fi

    echo "Processing plugin: $plugin"

    VERSION_AND_LINK=$(get_latest_version_and_download_link "$plugin")
    local version_check_status=$?
    
    if [ $version_check_status -eq 1 ]; then
        echo "Skipping $plugin due to version fetch error."
        return 1
    elif [ $version_check_status -eq 2 ]; then
        echo "Plugin $plugin is closed. Skipping download and processing."
        echo "$plugin" >> "$CLOSED_PLUGINS_FILE"
        if save_plugin_info "$plugin" "closed"; then
            debug_log "Successfully saved json metadata for closed plugin $plugin."
        else
            debug_log "Failed to save json metadata for closed plugin $plugin."
        fi
        return 0
    fi
    
    LATEST_VERSION=$(echo "$VERSION_AND_LINK" | cut -d' ' -f1)
    API_DOWNLOAD_LINK=$(echo "$VERSION_AND_LINK" | cut -d' ' -f2-)

    debug_log "Latest version for $plugin: $LATEST_VERSION"
    debug_log "API download link for $plugin: $API_DOWNLOAD_LINK"

    STORED_VERSION=$(grep "^$plugin" "$LAST_VERSION_FILE" | awk '{print $2}')
    debug_log "Stored version for $plugin: $STORED_VERSION"

    if [ "$CACHE_ONLY" != 'y' ] && [ "$LATEST_VERSION" == "$STORED_VERSION" ] && [ -f "${MIRROR_DIR}/${plugin}.${LATEST_VERSION}.zip" ]; then
        echo "$plugin is up-to-date and exists in mirror directory. Skipping download..."
    else
        start_time=$(date +%s.%N)

        if download_plugin "$plugin" "$LATEST_VERSION" "$API_DOWNLOAD_LINK"; then
            if [ "$CACHE_ONLY" != 'y' ]; then
                sed -i "/^$plugin/d" "$LAST_VERSION_FILE"
                echo "$plugin $LATEST_VERSION" >> "$LAST_VERSION_FILE"
            fi
            echo "Successfully processed $plugin."
        else
            echo "Error: Failed to process $plugin." >&2
        fi

        end_time=$(date +%s.%N)
        duration=$(echo "$end_time - $start_time" | bc)
        printf "Time taken for %s: %.4f seconds\n" "$plugin" "$duration"
    fi

    if save_plugin_info "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully saved json metadata for $plugin."
    else
        debug_log "Failed to save json metadata for $plugin."
    fi

    if fetch_and_save_checksums "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully fetched and saved checksums for $plugin."
    else
        debug_log "Failed to fetch and save checksums for $plugin."
    fi
}

populate_all_plugins() {
    if [ ! -f "$ALL_PLUGINS_FILE" ] || [ "$LIST_ONLY" == 'y' ]; then
        echo "Fetching list of all WordPress plugins..."
        svn list https://plugins.svn.wordpress.org/ | sed 's/\/$//g' > "$ALL_PLUGINS_FILE"
        plugin_count=$(wc -l < "$ALL_PLUGINS_FILE")
        echo "Plugin list (${plugin_count}) saved to $ALL_PLUGINS_FILE"
    fi
    
    if [ "$LIST_ONLY" == 'n' ]; then
        ALL_PLUGINS=()
        while IFS= read -r line; do
            ALL_PLUGINS+=("$line")
        done < "$ALL_PLUGINS_FILE"
        echo "Loaded ${#ALL_PLUGINS[@]} plugins."
    fi
}

if [ "$LIST_ONLY" == 'y' ]; then
    populate_all_plugins
    echo "Plugin list created. Exiting without downloading."
    exit 0
fi

if [ "$DOWNLOAD_ALL_PLUGINS" == 'y' ]; then
    populate_all_plugins
    COMBINED_PLUGINS=("${ALL_PLUGINS[@]}")
else
    if [ ! -d "$PLUGIN_DIR" ]; then
        echo "Warning: Plugin directory $PLUGIN_DIR does not exist or is invalid."
        PLUGIN_LIST=()
    else
        PLUGIN_LIST=($(ls -d "$PLUGIN_DIR"/*/ 2>/dev/null | xargs -n 1 basename))

        if [ ${#PLUGIN_LIST[@]} -eq 0 ]; then
            echo "No plugins found in $PLUGIN_DIR."
        fi
    fi

    COMBINED_PLUGINS=(${PLUGIN_LIST[@]} ${ADDITIONAL_PLUGINS[@]})
    COMBINED_PLUGINS=($(echo "${COMBINED_PLUGINS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
fi

if [ ${#COMBINED_PLUGINS[@]} -eq 0 ]; then
    echo "No plugins to download. Exiting."
    exit 0
fi

mkdir -p "$MIRROR_DIR"
touch "$LAST_VERSION_FILE"

if [ "$PARALLEL_JOBS" -gt 1 ]; then
    echo "Running in parallel with $PARALLEL_JOBS jobs..."
    # First, export all variables including USER_AGENTS
    export DOWNLOAD_BASE_URL MIRROR_DIR LAST_VERSION_FILE DEBUG_MODE DOWNLOAD_LINK_API LOGS_DIR ALL_PLUGINS_FILE DOWNLOAD_ALL_PLUGINS LIST_ONLY CF_WORKER_URL DELAY_DOWNLOADS DELAY_DURATION FORCE_UPDATE CACHE_ONLY USER_AGENTS

    # Then, export the functions
    export -f process_plugin get_latest_version_and_download_link download_plugin debug_log populate_all_plugins save_plugin_info get_random_user_agent fetch_and_save_checksums
    printf "%s\n" "${COMBINED_PLUGINS[@]}" | xargs -P $PARALLEL_JOBS -I {} bash -c 'process_plugin "$@"' _ {}
else
    for plugin in "${COMBINED_PLUGINS[@]}"; do
        process_plugin "$plugin"
    done
fi

if [ -f "$CLOSED_PLUGINS_FILE" ]; then
    echo
    echo "Closed Plugin List:"
    cat "$CLOSED_PLUGINS_FILE" | sort | uniq || true
    echo
    echo "Total closed plugins: $(wc -l < "$CLOSED_PLUGINS_FILE")"
    echo
else
    echo
    echo "No closed plugins found."
    echo
fi
echo "Plugin download process completed."
