#!/bin/bash

# Base directory (script location)
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Configurable directories
WORDPRESS_WORKDIR="${WORDPRESS_WORKDIR:-$BASE_DIR/wordpress-plugins}"
PLUGIN_DIR="${PLUGIN_DIR:-$BASE_DIR/wp-content/plugins}"
MIRROR_DIR="${MIRROR_DIR:-$BASE_DIR/mirror}"
LOGS_DIR="${LOGS_DIR:-$BASE_DIR/plugin-logs}"

# Check for CF_WORKER_URL environment variable
if [ -z "$CF_WORKER_URL" ]; then
    echo "Error: CF_WORKER_URL environment variable is not set." >&2
    exit 1
fi

DOWNLOAD_BASE_URL="https://downloads.wordpress.org/plugin"

# Other variables
DOWNLOAD_LINK_API='y'

ADDITIONAL_PLUGINS=(
    "academy"
    "wpsite-follow-us-badges"
    "socials-ignited"
    "mouseflow-for-wordpress"
    "custom-smilies-se"
    "uicore-animate"
    "chatter"
    "ni-woocommerce-sales-report"
    "powr-pack"
    "wah-forms"
    "atarim-visual-collaboration"
    "woo-parcelas-com-e-sem-juros"
    "wp-paint"
    "extensions-for-elementor-form"
    "wpc-buy-now-button"
    "igit-related-posts-with-thumb-images-after-posts"
    "rich-contact-widget"
    "category-icon"
    "footer-mega-grid-columns"
    "filenames-to-latin"
    "author-bio-box"
    "polaroid-gallery"
    "wp-plugin-manager"
    "searchiq"
    "wpb-elementor-addons"
    "zita-site-library"
    "captcha-for-contact-form-7"
    "totalpoll-lite"
    "storefront-top-bar"
    "permalinks-moved-permanently"
    "gspeech"
    "remove-old-slugspermalinks"
    "post-date-randomizer"
    "wordapp"
    "surferseo"
    "simple-post-type-permalinks"
    "sender-net-automated-emails"
    "simple-post-template"
    "maxslider"
    "keydatas"
    "notibar"
    "read-meter"
    "smtp"
    "include-me"
    "orderable"
    "twenty-eleven-theme-extensions"
    "lightweight-accordion"
    "local-search-seo-contact-page"
    "ongkoskirim-id"
    "acme-fix-images"
    "wp-utf8-excerpt"
    "add-on-contact-form-7-mailpoet"
    "webinar-and-video-conference-with-jitsi-meet"
    "wp24-domain-check"
    "woo-align-buttons"
    "events-maker"
    "buzzsprout-podcasting"
    "transcoder"
    "setmore-appointments"
    "blob-mimes"
    "rel-nofollow-checkbox"
    "dinosaur-game"
    "contact-form-query"
    "latest-posts"
    "operation-demo-importer"
    "uber-grid"
    "wpfavs"
    "mortgage-loan-calculator"
    "call-tracking-metrics"
    "woo-satispay"
    "click-to-top"
    "ryans-suckerfish-wordpress-dropdown-menu"
    "memberfindme"
    "sticky-header"
    "shortcodes-finder"
    "editor-menu-and-widget-access"
    "spotify-master"
    "vc-addons-by-bit14"
    "display-environment-type"
    "affiliate-toolkit-starter"
    "simple-system-status"
    "gravity-forms-css-ready-selector"
    "woo-checkout-regsiter-field-editor"
    "simple-ga-ranking"
    "spreadshop"
    "imagerecycle-pdf-image-compression"
    "ajax-cart-autoupdate-for-woocommerce"
    "super-simple-site-offline-beta"
    "shortcode-variables"
    "gum-elementor-addon"
    "wp-leads-builder-any-crm"
    "dk-pdf"
    "paypal-brasil-para-woocommerce"
    "showcase-idx"
    "multiple-roles"
    "woo-cart-weight"
    "export-woocommerce"
    "lightbox-images-for-divi"
    "wp-theme-test"
    "uptodown-apk-download-widget"
    "display-categories-widget"
    "login-with-phone-number"
    "flat-preloader"
    "mmwd-remove-add-to-cart-for-woocommerce"
    "intelliwidget-per-page-featured-posts-and-menus"
    "footer-javascript"
    "wp-responsive-photo-gallery"
    "lazy-load-optimizer"
    "wpop-elementor-addons"
    "fathom-analytics"
    "livesupporti"
    "podamibe-simple-footer-widget-area"
    "woocommerce-product-details-customiser"
    "alphabetic-pagination"
    "share-social-media"
    "anthologize"
    "cart-rest-api-for-woocommerce"
    "responsive-video-embeds"
    "storefront-hamburger-menu"
    "text-replace"
    "user-registration-aide"
    "wplms-coauthors-plus"
    "woo-thank-you-page-customizer"
    "woo-coupon-box"
    "firebox"
    "xlanguage"
    "merchant"
    "wp-about-author"
    "version-info"
    "cryptocurrency-donation-box"
    "posts-like-dislike"
    "bandsintown"
    "pinterest-pinboard-widget"
    "wordpresscom-stats-smiley-remover"
    "lottiefiles"
    "posts-by-tag"
    "localendar-for-wordpress"
    "marvy-animation-addons-for-elementor-lite"
    "woo-shipping-display-mode"
    "jwt-auth"
    "woocommerce-product-image-flipper"
    "responsive-block-editor-addons"
    "woo-title-limit"
    "pdf-builder-for-wpforms"
    "wp-flickr-gallery"
    "query-posts"
    "wbounce"
    "cozy-essential-addons"
    "blog-stats-by-w3counter"
    "wp-most-popular"
    "wordpress-dashboard-editor"
    "product-watermark-for-woocommerce"
    "easy-notify-lite"
    "wp-jquery-update-test"
    "disable-updates"
    "feedburner-alternative-and-rss-redirect"
    "boostify-header-footer-builder"
    "formstack"
    "tourfic"
    "waitlist-woocommerce"
    "lws-cleaner"
    "rus-to-lat-advanced"
    "jsm-show-user-meta"
    "woo-ecommerce-tracking-for-google-and-facebook"
    "post-layouts"
    "wp-jw-player"
    "image-pro-wordpress-image-media-management-and-resizing-done-right"
    "woo-payrexx-gateway"
    "redi-restaurant-reservation"
    "buddypress-groups-extras"
    "podamibe-custom-user-gravatar"
    "sky-login-redirect"
    "contact-form-7-signature-addon"
    "cackle"
    "woocommerce-coupon-shortcodes"
    "wc-frontend-manager-elementor"
    "order-hours-scheduler-for-woocommerce"
    "press-this"
    "bertha-ai-free"
    "wp-seo-html-sitemap"
    "wpzoom-forms"
    "wp-remove-category-base"
    "allow-multiple-accounts"
    "material-design-icons-for-elementor"
    "gtm-ecommerce-woo"
    "simple-xml-sitemap-generator"
    "wp-example-content"
    "woof-by-category"
    "buy-one-get-one-free"
    "wp-fail2ban-redux"
    "wpdm-elementor"
    "plagiarism-checker-by-sst"
    "emarksheet"
    "wplms-mycred-addon"
    "woocommerce-shipping"
    "postaffiliatepro"
    "spotify-play-button-for-wordpress"
    "simple-pull-quote"
    "hyper-cache-extended"
    "woosquare"
    "excerpt-editor"
    "shortcode-redirect"
    "woo-force-authentification-before-checkout"
    "exit-popup"
    "export-featured-images"
    "woo-set-price-note"
    "exit-intent-popups-by-optimonk"
    "wp-captcha-booster"
    "edd-featured-downloads"
    "arrow-twitter-feed"
    "nmedia-mailchimp-widget"
    "woocommerce-all-currencies"
    "imageseo"
    "envialosimple-email-marketing-y-newsletters-gratis"
    "pagarme-payments-for-woocommerce"
    "cart-notices-for-woocommerce"
    "visitors-online"
    "the-paste"
    "advanced-admin-search"
    "elex-woocommerce-role-based-pricing-plugin-basic"
    "user-blocker"
    "woo-lucky-wheel"
    "jetpack-search"
    "post-ratings"
    "awesome-widgets-for-siteorigin-page-builder"
    "wpop-accf"
    "rollbar"
    "buddypress-like"
    "coupon-reveal-button"
    "easy-social-share-buttons"
    "themezee-magazine-blocks"
    "category-sticky-post"
    "mini-twitter-feed"
    "cf7-invisible-recaptcha"
    "woocommerce-apg-sms-notifications"
    "ozh-who-sees-ads"
    "multiple-category-selection-widget"
    "wp-crm-system"
    "slimbox-plugin"
    "unreal-flipbook-addon-for-visual-composer"
    "redirect-url-to-post"
    "redirect-404-error-page-to-homepage"
    "woo-customize"
    "heateor-social-comments"
    "woo-gst"
    "getresponse"
    "uber-nocaptcha-recaptcha"
    "send-images-rss"
    "custom-database-tables"
    "smtp-mail"
    "traffic-counter-widget"
    "slick-popup"
    "simple-icons"
    "gigs-calendar"
    "embedalbum-pro"
    "fatal-error-notify"
    "search-engine-insights"
    "timeline-block"
    "root-relative-urls"
    "wp-w3all-phpbb-integration"
    "add-to-all"
    "cozy-addons"
    "gm-block-bots"
    "related"
    "ot-flatsome-vertical-menu"
    "buddypress-followers"
    "stock-locations-for-woocommerce"
    "wp-show-more"
    "block-slider"
    "mphb-styles"
    "wp-modal-popup-with-cookie-integration"
    "topbar-call-to-action"
    "buddypress-edit-activity"
    "social-bookmarking-reloaded"
    "flip-boxes"
    "wc-multishipping"
    "speechkit"
    "corner-ad"
    "pinterest-master"
    "json-api-auth"
    "bbpress-wp-tweaks"
    "wp-skitter-slideshow"
    "age-verify"
    "product-catalog-feed"
    "back-button-widget"
    "formassembly-web-forms"
    "colorbox-panels"
    "wp-minify-fix"
    "social-comments"
    "full-site-builder-for-elementor"
    "gravity-forms-stripe"
    "chatroll-live-chat"
    "auto-iframe"
    "collabpress"
    "wc-ukr-shipping"
    "bst-dsgvo-cookie"
    "job-board-manager"
    "pepro-ultimate-invoice"
    "omnibus"
    "wp-sort-order"
    "machete"
    "kivicare-clinic-management-system"
    "new-grid-gallery"
    "dynamic-user-directory"
    "woocommerce-product-payments"
    "custom-site-logo"
    "daily-prayer-time-for-mosques"
    "disable-new-user-notifications"
    "fd-elementor-button-plus"
    "wp-visitors-widget"
    "peters-post-notes"
    "contact-forms"
    "woorechnung"
    "woo-free-shipping-bar"
    "enable-accessibility"
    "countdown-timer-for-elementor"
    "no-category-parents"
    "author-hreview"
    "advanced-recent-posts-widget"
    "ipages-flipbook"
    "quotes-for-woocommerce"
    "smartvideo"
    "pixelgrade-assistant"
    "pexlechris-adminer"
    "codemonkeys-hipaa-forms"
    "pageview"
    "cf7-cost-calculator-price-calculation"
    "custom-css-manager-plugin"
    "web-stat"
    "monetag-official"
    "recent-posts-plugin"
    "cf7-zoho"
    "wp-media-folders"
    "wp-biographia"
    "jquery-masonry-image-gallery"
    "multisafepay"
    "button-generation"
    "aspexi-facebook-like-box"
    "ultimate-appointment-scheduling"
    "businessx-extensions"
    "recent-posts-flexslider"
    "primary-addon-for-elementor"
    "seo-tag-cloud"
    "themify-event-post"
    "docxpresso"
    "webtexttool"
    "fg-magento-to-woocommerce"
    "wp-bouncer"
    "custom-payment-gateways-woocommerce"
    "nif-num-de-contribuinte-portugues-for-woocommerce"
    "recaptcha-in-wp-comments-form"
    "ads-for-visual-composer"
    "quillforms"
    "version-control-for-jquery"
    "tabbed"
    "events-for-geodirectory"
    "business-contact-widget"
    "parent-category-toggler"
    "zoho-campaigns"
    "ari-cf7-connector"
    "random-posts-plugin"
    "amp-wp"
    "continue-shopping-for-woocommerce"
    "jotform-oembed"
    "jquery-categories-list"
    "triplea-cryptocurrency-payment-gateway-for-woocommerce"
    "send-users-email"
    "testimonial-add"
    "gf-salesforce-crmperks"
    "widget-yelp-reviews"
    "catalog-booster-for-woocommerce"
    "states-cities-and-places-for-woocommerce"
    "storeone-extension"
    "clever-mega-menu-for-elementor"
    "contact-form-7-paypal-extension"
    "logo-showcase-ultimate"
    "dsgvo-tools-cookie-hinweis-datenschutz"
    "sidebar-manager-light"
    "woongkir"
    "moloni"
    "woocommerce-custom-tabs"
    "yaycurrency"
    "linkable-title-html-and-php-widget"
    "ads-txt-manager"
    "superb-recent-posts-with-thumbnail-images"
    "gonzales"
    "phone-orders-for-woocommerce"
    "inline-spoilers"
    "international-telephone-input-for-contact-form-7"
    "gcs"
    "menu-duplicator"
    "wp-layouts"
    "woo-address-book"
    "hivepress-geolocation"
    "core-web-vitals-pagespeed-booster"
    "yelp-widget-pro"
    "smart-reporter-for-wp-e-commerce"
    "wp-e-commerce-store-toolkit"
    "tinymce-clear-buttons"
    "wp-session-manager"
    "seamless-sticky-custom-post-types"
    "alligator-popup"
    "ah-display-widgets"
    "advance-portfolio-grid"
    "subscribers-com"
    "wps-child-theme-generator"
    "paytr-sanal-pos-woocommerce-iframe-api"
    "ni-woocommerce-custom-order-status"
    "goodbarber"
    "wp-parsely"
    "add-fields-to-checkout-page-woocommerce"
    "squelch-tabs-and-accordions-shortcodes"
    "responsive-filterable-portfolio"
    "all-in-one-cufon"
    "builderall-cheetah-for-wp"
    "marfeelpress"
    "zionbuilder"
    "gpp-slideshow"
    "beds24-online-booking"
    "all-bootstrap-blocks"
    "oik-privacy-policy"
    "bangla-date-display"
    "woocommerce-improved-external-products"
    "woosms-sms-module-for-woocommerce"
    "google-ads-master"
    "bp-default-data"
    "popup-trigger-url-for-elementor-pro"
    "recaptcha-for-all"
    "elemailer-lite"
    "wp-courses"
    "mobile-login-woocommerce"
    "disable-wp-sitemaps"
    "guest-author-name"
    "cw-image-optimizer"
    "jetpack-videopress"
    "get-a-quote-button-for-woocommerce"
    "weblizar-companion"
    "fb-status-updater"
    "profile-extra-fields"
    "wp-calameo"
    "shopmagic-abandoned-carts"
    "quick-restaurant-menu"
    "korea-sns"
    "fs-poster-lite"
    "wpmovielibrary"
    "relevant"
    "woo-custom-cart-button"
    "woo-quote-or-enquiry-contact-form-7"
    "custom-css-editor"
    "tw-recent-posts-widget"
    "page-speed"
    "progress-bar-wp"
    "nofollow-free"
    "loginza"
    "everest-toolkit"
    "broken-link-finder"
    "ultimate-hover-effects"
    "blog-designer-for-elementor"
    "related-posts-via-categories"
    "plugin-security-scanner"
    "list-categories"
    "interactive-world-map"
    "car-demon"
    "wp-user-profile-avatar"
    "kwayy-html-sitemap"
    "cardealer"
    "oliver-pos"
    "free-comments-for-wordpress-vuukle"
    "disable-big-image-threshold"
    "conekta-payment-gateway"
    "woocommerce-country-based-payments"
    "plugin-check"
    "pay-by-paynow-pl"
    "genesis-widgetized-footer"
    "post-type-x"
    "webspellchecker"
    "skt-builder"
    "wc-serial-numbers"
    "image-slider-slideshow"
    "srbtranslatin"
    "login-ip-country-restriction"
    "feed-reading-blogroll"
    "gdpr-data-request-form"
    "user-admin-simplifier"
    "archived-post-status"
    "nd-booking"
    "telegram-for-wp"
    "woo-shipping-gateway"
    "super-video-player"
    "cleverreach-wp"
    "pojo-forms"
    "gold-addons-for-elementor"
    "zoom-widget"
    "video-backgrounds-for-siteorigin-page-builder"
    "adsense-in-post-ads-by-oizuled"
    "better-payment"
    "myrepono-wordpress-backup-plugin"
    "per-page-sidebars"
    "core-rollback"
    "acf-views"
    "woocommerce-more-sorting"
    "wordpress-gallery-plugin"
    "remove-cpt-base"
    "woo-one-click-upsell-funnel"
    "featured-image-caption"
    "custom-bulkquick-edit"
    "a3-responsive-slider"
    "stag-custom-sidebars"
    "wp-instagram-feed-awplife"
    "simple-post-notes"
    "simple-nivo-slider"
    "tinywym-editor"
    "1-jquery-photo-gallery-slideshow-flash"
    "bulk-edit-user-profiles-in-spreadsheet"
    "quick-whatsapp"
    "pojo-lightbox"
    "wp-thumbie"
    "monkeyman-rewrite-analyzer"
    "custom-codes"
    "woo-pagseguro-rm"
    "servebolt-optimizer"
    "wp-survey-and-poll"
    "gravity-forms-email-blacklist"
    "wordpress-2-step-verification"
    "um-terms-conditions"
    "countdown-clock"
    "wpc-variation-swatches"
    "buy-now-woo"
    "axeptio-sdk-integration"
    "arprice-responsive-pricing-table"
    "wp-global-site-tag"
    "event-post"
    "vimeo-master"
    "appmaker-wp-mobile-app-manager"
    "di-themes-demo-site-importer"
    "kstats-reloaded"
    "google-maps-gpx-viewer"
    "woo-vietnam-checkout"
    "admin-bar-dashboard-control"
    "wp-vertical-image-slider"
    "wp-to-top"
    "restricted-to-adults"
    "canada-post-shipping-for-woocommerce"
    "comments-plus"
    "product-recommendation-quiz-for-ecommerce"
    "wpengine-geoip"
    "comment-form"
    "reflex-gallery"
    "cities-shipping-zones-for-woocommerce"
    "insert-headers-and-footers-script"
    "hammy"
    "domain-mapping-system"
    "wc-product-subtitle"
    "wip-custom-login"
    "jonradio-current-year-and-copyright-shortcodes"
    "bulk-post-update-date"
    "video-embedder"
    "kadence-woocommerce-elementor"
    "simple-post-redirect"
    "simple-google-adsense"
    "hide-categories-products-woocommerce"
    "home-page-banner-for-astra-theme"
    "wen-logo-slider"
    "post-feature-widget"
    "rss-for-yandex-zen"
    "magazine-columns"
    "product-size-chart-for-woo"
    "block-catalog"
    "storefront-homepage-contact-section"
    "profile-pic"
    "simple-sidebar-navigation"
    "simple-login-captcha"
    "woocommerce-products-quick-view"
    "coming-soon-maintenance-mode"
    "wpsynchro"
    "aquila-admin-theme"
    "favicon-xt-manager"
    "corona-virus-data"
    "goftino"
    "chamber-dashboard-business-directory"
    "amministrazione-trasparente"
    "enable-classic-editor"
    "magazine-blocks"
    "widgets-reloaded"
    "cpt-editor"
    "button-visually-impaired"
    "buddy-share-it-allusers-fb-yr"
    "responsive-contact-form"
    "sticky-buttons"
    "form-masks-for-elementor"
    "lucky-orange"
    "transparent-image-watermark-plugin"
    "woo-tumblog"
    "quantcast-choice"
    "bp-groupblog"
    "shift8-cdn"
    "wp-popup-scheduler"
    "mass-pagesposts-creator"
    "page-peel"
    "ample-themes-demo-importer"
    "inpost-gallery"
    "backlinks-saver"
    "my-simple-space"
    "doubly"
    "random-posts-widget"
    "featured-image"
    "postpage-specific-custom-css"
    "easy-photo-album"
    "civic-cookie-control-8"
    "extrawatch"
    "permalink-editor"
    "tp-product-image-flipper-for-woocommerce"
    "woocommerce-bulk-order-form"
    "advanced-woocommerce-product-gallery-slider"
    "forge"
    "portfolio-and-projects"
    "error-log-viewer"
    "uicore-elements"
    "wpzoom-addons-for-beaver-builder"
    "create-and-assign-categories-for-pages"
    "fat-rat-collect"
    "wp-first-letter-avatar"
    "travel-booking-toolkit"
    "show-sliders"
    "views-for-wpforms-lite"
    "flexible-coupons"
    "webcomic"
    "wp-export-menus"
    "skt-skill-bar"
    "cartasi-x-pay"
    "same-category-posts"
    "subheading"
    "wp-register-profile-with-shortcode"
    "mihanpanel-lite"
    "tabbed-login"
    "last-modified-timestamp"
    "spocket"
    "wp-team-manager"
    "mihdan-no-external-links"
    "smart-passworded-pages"
    "pisol-mmq"
    "creative-image-slider"
    "contact-form-7-shortcode-enabler"
    "reading-progress-bar"
    "razorpay-quick-payments"
    "webmaster-user-role"
    "acf-vc-integrator"
    "wpsso-rrssb"
    "testimonials-carousel-elementor"
    "eway-payment-gateway"
    "oopspam-anti-spam"
    "insert-special-characters"
    "jj-nextgen-jquery-carousel"
    "google-drive-wp-media"
    "ari-stream-quiz"
    "wp-carousel"
    "ulimate-client-dash"
    "about-me-widget"
    "shipping-zones-by-drawing-for-woocommerce"
    "hivepress-messages"
    "woocommerce-email-validation"
    "advanced-custom-fields-code-area-field"
    "wpbenchmark"
    "contact-coldform"
    "disable-title"
    "wplms-h5p-plugin"
    "wp-express-checkout"
    "theme-blvd-widget-areas"
    "featured-image-generator"
    "epeken-all-kurir"
    "wp-image-borders"
    "the-courier-guy"
    "product-xml-feeds-for-woocommerce"
    "page-tagger"
    "geotargeting"
    "cubepoints-buddypress-integration"
    "organization-chart"
    "rs-wp-books-showcase"
    "mypos-virtual-for-woocommerce"
    "affiliate-links"
    "automatic-translate-addon-for-translatepress"
    "wp-commentnavi"
    "easygravatars"
    "serverbuddy-by-pluginbuddy"
    "a4-barcode-generator"
    "billingo"
    "about-author"
    "peters-custom-anti-spam-image"
    "stop-emails"
    "quick-buy-now-button-for-woocommerce"
    "event-monster"
    "reviews-plus"
    "mwb-bookings-for-woocommerce"
    "wa-sticky-button"
    "grids"
    "paytpv-for-woocommerce"
    "wp-content-slideshow"
    "bible-verse-of-the-day"
    "wapppress-builds-android-app-for-website"
    "food-online-for-woocommerce"
    "debug-bar-timber"
    "christmasify"
    "post-2-post-for-acf"
    "iamport-for-woocommerce"
    "foosales"
    "print-google-cloud-print-gcp-woocommerce"
    "sms4wp"
    "bbpress-login-register-links-on-forum-topic-pages"
    "acf-repeater-flexible-content-collapser"
    "adjust-admin-categories"
    "scroll-triggered-animations"
    "ad-refresh-control"
    "progress-bar"
    "download-media-library"
    "wpb-popup-for-contact-form-7"
    "better-recent-comments"
    "woo-postfinance-checkout"
    "checkout-mestres-wp"
    "affiliatewp-affiliate-area-tabs"
    "romethemeform"
    "disable-author-archives"
    "wp-post-to-pdf-enhanced"
    "woocommerce-catalog"
    "woo-image-seo"
    "rt-slider"
    "mime-types-plus"
    "social-web-suite"
    "tailor"
    "adbusters"
    "custom-add-to-cart-button-for-woocommerce"
    "demo-data-creator"
    "woowbot-woocommerce-chatbot"
    "easyship-woocommerce-shipping-rates"
    "likecoin"
    "disable-update-notifications"
    "extensions-for-elementor"
    "pay-via-barion-for-woocommerce"
    "language-icons-flags-switcher"
    "platforminfo"
    "cf7-salesforce"
    "ziplist-recipe-plugin"
    "qwiz-online-quizzes-and-flashcards"
    "easy-form-builder"
    "bulletin-announcements"
    "background-per-page"
    "wp-410"
    "wp-youtube-live"
    "wp-simple-post-view"
    "content-visibility-for-divi-builder"
    "cornerstone"
    "fixed-and-sticky-header"
    "jellyfish-counter-widget"
    "multiple-sidebars"
    "countdown-block"
    "yada-wiki"
    "interact-quiz-embed"
    "ko-fi-button"
    "remove-comments-are-closed"
    "make-paths-relative"
    "text-hover"
    "woo-category-slider-by-pluginever"
    "chatra-live-chat"
    "my-posts-order"
    "publish-to-schedule"
    "image-upload-for-bbpress"
    "sexy-contact-form"
    "customize-login-image"
    "post-type-archive-descriptions"
    "display-a-meta-field-as-block"
    "read-more-excerpt-link"
    "seers-cookie-consent-banner-privacy-policy"
    "custom-category-templates"
    "wp-http-compression"
    "bp-group-documents"
    "apocalypse-meow"
    "sticky-social-icons"
    "zettle-pos-integration"
    "website-toolbox-forums"
    "simple-login-lockdown"
    "wc-cash-on-pickup"
    "wp-to-hootsuite"
    "pdf-generator-for-wp"
    "payoneer-checkout"
    "woocommerce-sold-out-products"
    "custom-header-extended"
    "dco-comment-attachment"
    "syndicate-press"
    "filterable-portfolio"
    "rock-convert"
    "woo-better-usability"
    "animentor-lottie-bodymovin-elementor"
    "twentytwenty"
    "woo-piva-codice-fiscale-e-fattura-pdf-per-italia"
    "magical-products-display"
    "remove-widget-titles"
    "clover-online-orders"
    "landingi-landing-pages"
    "donations-for-woocommerce"
    "contact-form-7-lead-info-with-country"
    "wp-log-viewer"
    "activity-log-mainwp"
    "wpdirectorykit"
    "station-pro"
    "convert-to-blocks"
    "epoll-wp-voting"
    "404-notifier"
    "wp-ultimate-search"
    "google-news"
    "samedaycourier-shipping"
    "fraudlabs-pro-for-woocommerce"
    "wp-theme-plugin-download"
    "smntcs-woocommerce-quantity-buttons"
    "shareadraft"
    "disable-gutenberg-blocks"
    "owl-carousel-wp"
    "menu-swapper"
    "native-emoji"
    "yoast-comment-hacks"
    "custom-css-pro"
    "pages-in-widgets"
    "post-carousel-slider-for-elementor"
    "map-location-picker-at-checkout-for-woocommerce"
    "widget-post-slider"
    "login-widget-for-ultimate-member"
    "fastdup"
    "section-widget"
    "block-navigation"
    "attesa-extra"
    "clearpay-gateway-for-woocommerce"
    "cart-lift"
    "shareasale-wc-tracker"
    "hivepress-paid-listings"
    "zephyr-project-manager"
    "media-credit"
    "no-comments-on-pages"
    "remove-admin-menus-by-role"
    "tipsy-social-icons"
    "display-post-types"
    "pojo-importer"
    "beacon-by"
    "suffice-toolkit"
    "baiduseo"
    "recent-posts"
    "remove-wp-branding"
    "project-panorama-lite"
    "quadmenu-divi"
    "enhance-wp-rocket-loadcss"
    "card-elements-for-elementor"
    "ultimate-gallery"
    "resize-images-before-upload"
    "custom-font-uploader"
    "user-language-switch"
    "elementinvader-addons-for-elementor"
    "colorful-categories"
    "password-policy-manager"
    "phone-directory"
    "hivepress-reviews"
    "youtube-playlist-player"
    "jc-submenu"
    "product-tabs-manager-for-woocommerce"
    "ad-buttons"
    "affiliatebooster-blocks"
    "admin-page-framework"
    "toocheke-companion"
    "top-table-of-contents"
    "sqlite-database-integration"
    "woocommerce-payment-discounts"
    "wp-database-optimizer"
    "woocommerce-digital-signature"
    "aweber-wp"
    "gecka-submenu"
    "disable-cart-page-for-woocommerce"
    "megamenu-storefront"
    "ultimate-post-list"
    "interconnect-it-weather-widget"
    "smart-cookie-kit"
    "pojo-custom-fonts"
    "pen-extra-features"
    "cleverreach"
    "speed-up-optimize-css-delivery"
    "wp-united"
    "wpc-name-your-price"
    "page-excerpt"
    "continuous-rss-scrolling"
    "meta-keywords-generator"
    "jquery-drop-down-menu-plugin"
    "wp-tools-gravity-forms-divi-module"
    "arile-super"
    "bbpress-integration"
    "martins-link-network"
    "youtube-widget"
    "video-grid"
    "quick-flickr-widget"
    "rescue-shortcodes"
    "custom-layouts"
    "iframe-widget"
    "official-skrill-woocommerce"
    "real-time-validation-for-gravity-forms"
    "woocommerce-custom-options-lite"
    "simple-divi-shortcode"
    "wppageflip"
    "custom-related-products-for-woocommerce"
    "ft-calendar"
    "currency-converter"
    "ultimate-wp-mail"
    "team-builder-member-showcase"
    "popup-notices-for-woocommerce"
    "fulltext-search"
    "moving-media-library"
    "lana-downloads-manager"
    "admin-color-schemes"
    "better-blogroll"
    "block-manager"
    "authnet-cim-for-woo"
    "custom-related-posts"
    "add-whatsapp-button"
    "tpg-get-posts"
    "guest-author"
    "track-the-click"
    "miniclip-games"
    "theme-blvd-sliders"
    "tag-dropdown-widget"
    "yith-proteo-toolkit"
    "ultimate-noindex-nofollow-tool-ii"
    "forget-spam-comment"
    "sidemenu"
    "hivepress-favorites"
    "woocommerce-check-pincode-zipcode-for-shipping"
    "fv-antispam"
    "all-in-one-facebook-like-widget"
    "pe-recent-posts"
    "hover-effects"
    "post-slider-carousel"
    "g-meta-keywords"
    "mailpoet-woocommerce-add-on"
    "embed-code"
    "ticker-ultimate"
    "wp-head-cleaner"
    "good-reviews-wp"
    "product-export-for-woocommerce"
    "categorized-tag-cloud"
    "metro-style-social-widget"
    "wappointment"
    "extra-user-details"
    "customer-reviews-collector-for-woocommerce"
    "flexslider-hg"
    "multisite-toolbar-additions"
    "mantrabrain-starter-sites"
    "honeypot-antispam"
    "blogger-301-redirect"
    "debug-bar-list-dependencies"
    "gumlet"
    "pdf-viewer-block"
    "weekly-schedule"
    "yith-slider-for-page-builders"
    "theme-blvd-widget-pack"
    "bradmax-player"
    "question-answer"
    "waterwoo-pdf"
    "responsive-image-maps"
    "great-real-estate"
    "tao-schedule-update"
    "message-ticker"
    "streamcast"
    "profit-products-tables-for-woocommerce"
    "woocommerce-custom-price-label"
    "landing-page-cat"
    "markup-by-attribute-for-woocommerce"
    "acf-cpt-options-pages"
    "woo-aliexpress-dropshipping"
    "read-more-right-here"
    "awesome-surveys"
    "hide-price-until-login"
    "e-transactions-wc"
    "republish-old-posts"
    "packeta"
    "tag-list-widget"
    "wp-code-highlight"
    "breadcrumbs-divi-module"
    "bwp-recent-comments"
    "wp-multisite-user-sync"
    "wp-smart-import"
    "show-posts-and-pages-id"
    "woocommerce-shipping-gateway-per-product"
    "user-tags"
    "constant-contact-woocommerce"
    "wheel-of-life"
    "skimlinks"
    "customize-posts"
    "very-simple-splash-page"
    "plugin-notes-plus"
    "xpro-theme-builder"
    "wp-job-manager-xml-csv-listings-import"
    "personalize-woocommerce-cart-page"
    "wen-featured-image"
    "login-box"
    "coinpayments-payment-gateway-for-woocommerce"
    "make-tables-responsive"
    "wp-php-console"
    "ambrosite-nextprevious-post-link-plus"
    "seo-super-comments"
    "fancybox-gallery"
    "genesis-author-pro"
    "page-comments-off-please"
    "google-adsense-for-responsive-design-gard"
    "wp-upload-size"
    "fluid-player"
    "software-license-manager"
    "gravity-forms-entry-expiration"
    "pluginception"
    "wordpress-automatic-image-hotlink-protection"
    "unveil-lazy-load"
    "showid-for-postpagecategorytagcomment"
    "woocommerce-product-dependencies"
    "woo-addon-uploads"
    "oik-weightcountry-shipping"
    "bp-activity-social-share"
    "fd-footnotes"
    "mail-integration-365"
    "woocommerce-add-to-cart-custom-redirect"
    "kindeditor-for-wordpress"
    "automatic-featured-image-posts"
    "posts-slider"
    "save-as-pdf-by-pdfcrowd"
    "better-rest-api-featured-images"
    "gzippy"
    "wpfrank-companion"
    "kama-spamblock"
    "buddypress-activity-privacy"
    "vcaching"
    "convertkit-gravity-forms"
    "ozh-better-feed"
    "auto-load-next-post"
    "simple-link-list-widget"
    "better-internal-link-search"
    "booter-bots-crawlers-manager"
    "twiget"
    "onclick-popup"
    "eu-opt-in-compliance-for-mailchimp"
    "buddyforms-members"
    "baw-manual-related-posts"
    "cookie-script-com"
    "football-leagues-by-anwppro"
    "woocommerce-payu-latam-gateway"
    "woo-cardcom-payment-gateway"
    "fixed-bottom-menu"
    "social-testimonials-and-reviews-widget"
    "code-widget"
    "prevent-xss-vulnerability"
    "carousel"
    "mailster-amazonses"
    "blog-floating-button"
    "stars-testimonials-with-slider-and-masonry-grid"
    "izooto-web-push"
    "simple-admin-language-change"
    "wp-custom-taxonomy-image"
    "conditional-extra-fees-for-woocommerce"
    "instant-page"
    "vertically-scroll-rss-feed"
    "multipart-robotstxt-editor"
    "device-mockups"
    "flywp"
    "consent-manager"
    "bloglovin-button"
    "netease-music"
    "timeline-event-history"
    "featured-post-with-thumbnail"
    "stray-quotes"
    "link-view"
    "menu-exporter"
    "wp-time-machine"
    "posts-for-page"
    "wp-advanced-pdf"
    "dynamic-month-year-into-posts"
    "seo-internal-links"
    "redirect-editor"
    "ninja-page-categories-and-tags"
    "format-media-titles"
    "simple-jwt-login"
    "contests-from-rewards-fuel"
    "athemeart-theme-helper"
    "wpjm-extra-fields"
    "organic-profile-block"
    "woo-idpay-gateway"
    "mo-cache"
    "kia-subtitle"
    "sitewide-notice-wp"
    "smart-wishlist-for-more-convert"
    "wp-rtl"
    "automatically-paginate-posts"
    "testimonial-maker"
    "quotes-and-tips"
    "so-page-builder-animate"
    "easy-sticky-sidebar"
    "theme-switcher"
    "slick-slider"
    "woo-combo-offers"
    "ltrrtl-admin-content"
    "wp-post-navigation"
    "bulk-editor"
    "shopping-feed-for-google"
    "provesource"
    "catch-breadcrumb"
    "awsm-team"
    "simple-event-planner"
    "woo-manage-fraud-orders"
    "wp-shopify"
    "statify-widget"
    "cf-google-sheets"
    "a2z-fedex-shipping"
    "elex-woocommerce-google-product-feed-plugin-basic"
    "xt-woo-variation-swatches"
    "wp-no-base-permalink"
    "wp-gotowebinar"
    "simple-add-pages-or-posts"
    "webphysiology-portfolio"
    "different-menus-in-different-pages"
    "slimbox"
    "crowdfundly"
    "impressum"
    "optimization-detective"
    "frontend-post-submission-manager-lite"
    "falang"
    "civicrm-admin-utilities"
    "social-rocket"
    "app-ads-txt"
    "elex-woocommerce-dynamic-pricing-and-discounts"
    "woocommerce-embed-videos-to-product-image-gallery"
    "bigbuy-wc-dropshipping-connector"
    "flippingbook"
    "quick-interest-slider"
    "wpa-seo-auto-linker"
    "simple-maintenance"
    "motors-car-dealership-classified-listings"
    "leadlovers-for-elementor"
    "longer-permalinks"
    "floatbox-plus"
    "ios-images-fixer"
    "wp-missed-schedule-posts"
    "vikrentcar"
    "wp-media-recovery"
    "custom-archive-titles"
    "automatic-wordpress-backup"
    "disable-payment-method-for-woocommerce"
    "openpay-cards"
    "easy-flash-embed"
    "wp-attachment-export"
    "blogroll-rss-widget"
    "my-weather"
    "wc-place-order-without-payment"
    "webcraftic-updates-manager"
    "wing-migrator"
    "free-shipping-notification-woocommerce"
    "nichetable"
    "ns-remove-related-products-for-woocommerce"
    "formcraft-recaptcha"
    "sell-digital-downloads"
    "cssigniter-shortcodes"
    "responsive-facebook-like-box"
    "news-ticker-benaceur"
    "advanced-random-posts"
    "contact-list"
    "advanced-export-for-wp-wpmu"
    "branded-login-screen"
    "embed-lottie-player"
    "counter"
    "user-spam-remover"
    "autoset-featured-image"
    "posts-per-cat"
    "codoc"
    "corona-virus-covid-19-banner"
    "restaurantpress"
    "zoho-flow"
    "premmerce-search"
    "pushcrew"
    "disable-right-click"
    "youtube-master"
    "videographywp"
    "inpost-paczkomaty"
    "wp-smart-contracts"
    "email-marketing"
    "smart-maintenance-mode"
    "century-toolkit"
    "woo-payment-gateway-for-piraeus-bank"
    "taxonomy-switcher"
    "sign-up-sheets"
    "crazy-lazy"
    "tp-education"
    "story-chief"
    "appful"
    "accessibility-light"
    "flying-analytics"
    "wp-responsive-table"
    "shk-hide-title"
    "app-builder"
    "log-http-requests"
    "osm-map-elementor"
    "ceylon-demo-installer"
    "expire-user-passwords"
    "makecommerce"
    "zotabox"
    "wp-social-bookmarking"
    "stock-market-overview"
    "featured-post-creative"
    "dx-delete-attached-media"
    "bns-corner-logo"
    "fix-duplicates"
    "amazon-showcase-wordpress-widget"
    "wptelegram-login"
    "animated-fullscreen-menu"
    "wp-fundraising-donation"
    "who-stole-the-text-justify-button"
    "admin-ssl-secure-admin"
    "searchwp-modal-search-form"
    "widget-visibility-time-scheduler"
    "kitestudio-core"
    "podlove-subscribe-button"
    "wp-strava"
    "product-delivery-date-for-woocommerce-lite"
    "sliderspack-all-in-one-image-sliders"
    "simple-membership-wp-user-import"
    "wp-swiper"
    "post-category-image-with-grid-and-slider"
    "wibiya"
    "woocommerce-iran-post-shipping"
    "wp-downloader"
    "yournewsapp"
    "hotline-phone-ring"
    "custom-login-logo"
    "purge-varnish"
    "creative-clans-slide-show"
    "wp-post-signature"
    "ashe-extra"
    "gravity-forms-no-captcha-recaptcha"
    "genesis-easy-columns"
    "put"
    "tabber-tabs-widget"
    "deposits-for-woocommerce"
    "social-media-badge-widget"
    "easy-product-bundles-for-woocommerce"
    "portugal-states-distritos-for-woocommerce"
    "semisecure-login-reimagined"
    "wp-custom-admin-bar"
    "showeblogin-facebook-page-like-box"
    "pantheon-hud"
    "mystyle-custom-product-designer"
    "simple-universal-google-analytics"
    "addfreestats"
    "query-multiple-taxonomies"
    "cp-related-posts"
    "woocommerce-extend-tabs"
    "wp-yelp-review-slider"
    "og-tags"
    "styler-for-gravity-forms"
    "isape"
    "woocommerce-to-google-merchant-center"
    "login-with-google"
    "bp-security-check"
    "drag-and-drop-multiple-file-upload-for-woocommerce"
    "smart-user-slug-hider"
    "ht-menu-lite"
    "custom-recent-posts-widget"
    "most-popular-posts"
    "on-sale-page-for-woocommerce"
    "terms-and-conditions-popup-for-woocommerce"
    "local-delivery-drivers-for-woocommerce"
    "display-tweets-php"
    "image-watermark-wp"
    "remote-medias-lite"
    "advanced-spoiler"
    "tinymce-spellcheck"
    "ontrapages"
    "custom-login-page-templates"
    "disable-media-pages"
    "woocommerce-email-money-transfer-gateway"
    "black-studio-touch-dropdown-menu"
    "stripe-woocommerce-addon"
    "fcchat"
    "make-section-column-clickable-elementor"
    "compact-archives"
    "webmention"
    "logo-showcase-with-slick-slider"
    "server-info"
    "wp-secure-maintainance"
    "relevanssi-live-ajax-search"
    "wp-image-compression"
    "woo-invoices"
    "contentstudio"
    "jsonfeed"
    "async-social-sharing"
    "sgr-nextpage-titles"
    "cubewp-framework"
    "gutenkit-blocks-addon"
    "woocommerce-incremental-product-quantities"
    "feeds-for-tiktok"
    "woocommerce-checkout-terms-conditions-popup"
    "remove-open-sans-font-from-wp-core"
    "issuem"
    "kenta-blocks"
    "bp-redirect-to-profile"
    "badgeos-learndash-add-on"
    "selection-lite"
    "wp-comment-policy-checkbox"
    "airi-demo-importer"
    "wplms-badgeos"
    "wc-cashapp"
    "ht-wpform"
    "bpost-shipping"
    "yottie-lite"
    "coin-slider-4-wp"
    "birds-custom-login"
    "contextly-related-links"
    "mwp-herd-effect"
    "wp-performance-pack"
    "buffer-my-post"
    "traffic-stats-widget"
    "social-linkz"
    "wp-copysafe-web"
    "paypal-payment-button-by-vcita"
    "spostarbust"
    "move-addons"
    "ultimate-lightbox"
    "change-quantity-on-checkout-for-woocommerce"
    "recaptcha-for-asgaros-forum"
    "buddypress-sliding-login-panel"
    "cache-images"
    "hide-titles"
    "vision"
    "lj-xp"
    "hide-admin-toolbar"
    "hide-comments-feature"
    "share-button"
    "cresta-facebook-messenger"
    "wp-comment-fields"
    "wp-wrapper"
    "proteusthemes-mailchimp-widget"
    "themeegg-toolkit"
    "receiptful-for-woocommerce"
    "memsource-connector"
    "wp-syntaxhighlighter"
    "islidex"
    "flash-gallery"
    "hide-wp-toolbar"
    "official-sendle-shipping-method"
    "wordpress-flash-page-flip"
    "trusted-shops-easy-integration-for-woocommerce"
    "enhanced-category-pages"
    "paytrail-for-woocommerce"
    "admin-bar"
    "simple-site-map-page"
    "recent-posts-plus"
    "object-cache-4-everyone"
    "guestbook-generator"
    "wte-elementor-widgets"
    "keep-backup-daily"
    "lessphp"
    "language-switcher"
    "integration-dynamics"
    "woocommerce-payment-gateway"
    "urvanov-syntax-highlighter"
    "chat-room"
    "disable-author-pages"
    "wp-docs"
    "wc-abandoned-carts-by-small-fish-analytics"
    "page-theme"
    "onet-regenerate-thumbnails"
    "gathercontent-import"
    "allwebmenus-wordpress-menu-plugin"
    "wp-mail-smtp-mailer"
    "ct-mortgage-calculator"
    "woocommerce-smart-sale-badge"
    "masks-form-fields"
    "parallax-image"
    "autologin-links"
    "sticky-posts-switch"
    "goaffpro"
    "custom-post-order"
    "woo-discount-price"
    "integrate-contact-form-7-and-aweber"
    "cww-companion"
    "a2z-dhl-express-shipping"
    "comm100-live-chat"
    "conditional-blocks"
    "woo-variations-table"
    "simple-contact-info-widget"
    "lktags-linkedin-insight-tags"
    "wc-pickup-store"
    "employee-spotlight"
    "jquery-slider"
    "wp-responsive-video-gallery-with-lightbox"
    "wpglobus-translate-options"
    "simple-youtube-responsive"
    "job-manager-career"
    "wp-sendgrid-smtp"
    "constant-contact-signup-form-widget"
    "widget-contact-form-7"
    "imgspider"
    "genesis-simple-headers"
    "dynamic-time"
    "add-new-default-avatar"
    "listly"
    "premmerce-woocommerce-brands"
    "tt-sidebar-login-widget"
    "revision-manager-tmc"
    "wp-multisite-content-copier"
    "vertical-scroll-recent-comments"
    "fish-and-ships"
    "advanced-custom-fields-location-field-add-on"
    "woo-floating-minicart"
    "shibboleth"
    "sql-executioner"
    "nd-elements"
    "filter-page-by-template"
    "excel-like-price-change-for-woocommerce-and-wp-e-commerce-light"
    "simple-google-sitemap"
    "bus-ticket-booking-with-seat-reservation"
    "debug-bar-rewrite-rules"
    "widget-manager-light"
    "bp-activity-shortcode"
    "woocommerce-quaderno"
    "accordion-and-accordion-slider"
    "spiraclethemes-site-library"
    "ups-eu-woocommerce"
    "caddy"
    "pressforward"
    "metrilo-woocommerce-integration"
    "hide-login"
    "wired-impact-volunteer-management"
    "woocommerce-unit-of-measure"
    "soundpress"
    "modernizr"
    "custom-login-url"
    "buddypress-notifications-widget"
    "mycustomwidget"
    "go-fetch-jobs-wp-job-manager"
    "flickr-widget"
    "infusionsoft-official-opt-in-forms"
    "fattura24"
    "woocommerce-ajax-add-to-cart-for-variable-products"
    "tracking-script-manager"
    "http-auth"
    "wp-term-images"
    "contact-manager"
    "post-status-notifier-lite"
    "page-links-single-page-option"
    "image-hover-effects-block"
    "hide-this"
    "woocommerce-discounts-plus"
    "pt-theme-addon"
    "fondy-woocommerce-payment-gateway"
    "post-grid-carousel-ultimate"
    "milat-jquery-automatic-popup"
    "woocommerce-filter-orders-by-product"
    "bbpress-admin-bar-addition"
    "google-syntax-highlighter"
    "bookingcom-product-helper"
    "usersnap"
    "auto-advance-for-gravity-forms"
    "pdf-generator-addon-for-elementor-page-builder"
    "recent-posts-with-excerpts"
    "wp-seo-redirect-301"
    "fancy-admin-ui"
    "wp-ticket"
    "pojo-news-ticker"
    "log-out-shortcode"
    "easy-faqs"
    "contact-form-7-accessible-defaults"
    "annasta-woocommerce-product-filters"
    "clickbank-storefront"
    "simple-ip-ban"
    "wp-gmail-smtp"
    "so-pinyin-slugs"
    "wps-notice-center"
    "wp-flickr-press"
    "wp-gravity-forms-spreadsheets"
    "ninja-charts"
    "manage-xml-rpc"
    "wp-contact-form-iii"
    "wpc-countdown-timer"
    "products-extractor-for-woocommerce"
    "foobar-notifications-lite"
    "react-and-share"
    "woocommerce-jne"
    "events-search-addon-for-the-events-calendar"
    "wp-farsi"
    "sliderpro"
    "ctw-ssl-for-cloudflare"
    "360-image"
    "extensions-leaflet-map"
    "terms-of-use-2"
    "wptuner"
    "woocommerce-securesubmit-gateway"
    "embed-optimizer"
    "theme-one-click-demo-import"
    "kenta-companion"
    "surbma-divi-extras"
    "shortbuild"
    "announcement-ticker-highlighter-scroller"
    "flickr-slideshow-wrapper"
    "popup-more"
    "sales-report-for-woocommerce"
    "preserve-code-formatting"
    "events-planner"
    "pmpro-courses"
    "multifile-upload-field-for-contact-form-7"
    "all-in-one-forms"
    "wc-buckaroo-bpe-gateway"
    "protection-against-ddos"
    "fpw-category-thumbnails"
    "woo-easy-duplicate-product"
    "footable"
    "lazy-seo"
    "simple-sticky-footer"
    "feed-instagram-lite"
    "custom-fields-gutenberg"
    "wp-custom-cursors"
    "img-mouseover"
    "flexible-shipping-dhl-express"
    "speedy-page-redirect"
    "widget-category-cloud"
    "contact-form-7-select-box-editor-button"
    "admin-bar-user-switching"
    "sf-taxonomy-thumbnail"
    "classic-menu-block"
    "wp-mpdf"
    "expire-users"
    "xili-tidy-tags"
    "bbp-voting"
    "wordpress-protection"
    "cliengo"
    "accordion-slider-gallery"
    "preserved-html-editor-markup-plus"
    "wp-forms-signature-contract-add-on"
    "spice-social-share"
    "mb-relationships"
    "inavii-social-feed-for-elementor"
    "remove-woocommerce-product-content"
    "quantity-field-on-shop-page-for-woocommerce"
    "comments-widget-plus"
    "stencil"
    "tagpages"
    "imsupporting"
    "force-default-variant-for-woocommerce"
    "dhlpwc"
    "login-and-out"
    "voucherpress"
    "rocket-wp-mobile"
    "the-holiday-calendar"
    "woo-parcel-pro"
    "country-state-city-auto-dropdown"
    "custom-scrollbar"
    "spam-comments-cleaner"
    "alphaomega-captcha-anti-spam"
    "event-organiser-posterboard"
    "google-video-sitemap-feed-with-multisite-support"
    "comment-notifier"
    "addressfinder-woo"
    "wp-api-swaggerui"
    "acf-field-for-contact-form-7"
    "wumii-related-posts"
    "popup-box"
    "wp-content-filter"
    "ithemeland-free-gifts-for-woo"
    "wp-resume"
    "woocommerce-cloak-affiliate-links"
    "floating-links"
    "quick-view-woocommerce"
    "bbspoiler"
    "easy-admin-color-schemes"
    "rss-just-better"
    "ad-blocking-detector"
    "simple-fullscreen-responsive-slider"
    "shortcode-gallery-for-matterport-showcase"
    "accordions-wp"
    "allow-webp-image"
    "really-simple-featured-video"
    "persian-world"
    "snitch"
    "audio-player-widget"
    "imoney"
    "php-browser-detection"
    "podium"
    "product-categories-designs-for-woocommerce"
    "riddle-playful-content-on-the-go"
    "really-simple-click-to-call"
    "wc-speed-drain-repair"
    "disable-user-login"
    "post-author"
    "bws-smtp"
    "related-youtube-videos"
    "contact-form7-autocomplete"
    "post-terms-order"
    "wp-advanced-search"
    "memory-bump"
    "shortcodes-for-divi"
    "signature-watermark"
    "easyindex"
    "segmentio"
    "rss-in-page"
    "wpdirauth"
    "mobile-bottom-menu-for-wp"
    "xt-woo-quick-view-lite"
    "acf-rgba-color-picker"
    "twitch-tv-embed-suite"
    "dorzki-notifications-to-slack"
    "wholesalex"
    "nav-menu-collapse"
    "wp-codemirror-block"
    "cryptocurrency-widgets-for-elementor"
    "wp-music-player"
    "widget-wrangler"
    "timezonecalculator"
    "wp-multicolor-subscribe-widget"
    "wp-print-friendly"
    "full-width-responsive-slider-wp"
    "woo-pensopay"
    "cf7-post-fields"
    "yandex-share"
    "map-categories-to-pages"
    "update-control"
    "meks-video-importer"
    "wp-responsive-slider-with-lightbox"
    "emailkit"
    "flex-posts"
    "gocache-cdn"
    "weather-layer"
    "mb-elementor-integrator"
    "woo-viet"
    "sitelinks-search-box"
    "log-emails"
    "notify-users-e-mail"
    "wp-hyper-response"
    "inline-javascript"
    "eazydocs"
    "confirm-user-registration"
    "adroll-for-woocommerce-stores-dev"
    "remember-me-controls"
    "woo-moip-official"
    "supreme-google-webfonts"
    "unlimited-blocks"
    "eonet-live-notifications"
    "wpsso-breadcrumbs"
    "bns-featured-category"
    "elementinvader"
    "flexible-shipping-usps"
    "youtube-with-fancy-zoom"
    "bounce-handler-mailpoet"
    "acf-columns"
    "woo-commerce-addon-for-wp-courseware"
    "sidebar-photoblog"
    "countdown-for-the-events-calendar"
    "public-post-preview-configurator"
    "wp-client-reports"
    "piotnetforms"
    "avchat-3"
    "wp-resized-image-quality"
    "speed-up-lazy-load"
    "autocomplete-google-address"
    "rdfa-breadcrumb"
    "random-content"
    "stageshow"
    "series"
    "arforms-form-builder"
    "navayan-subscribe"
    "wp-experiments-free"
    "wp-facebook-pixel"
    "really-simple-gallery-widget"
    "wpdevart-vertical-menu"
    "bambora-online-classic"
    "faustwp"
    "custom-background-changer"
    "mask-form-elementor"
    "slider-factory"
    "envothemes-importer-kingcomposer"
    "attachment-importer"
    "zigaform-calculator-cost-estimation-form-builder-lite"
    "advance-menu-manager"
    "price-by-user-role-for-woocommerce"
    "robokassa"
    "acf-to-wp-api"
    "simple-user-listing"
    "timeline-for-beaver-builder"
    "image-prioritizer"
    "basic-seo-pack"
    "table-of-contents-creator"
    "flowplayer6-video-player"
    "staff-directory-pro"
    "security-headers"
    "wp-latex"
    "post-date-change-redirection"
    "point-of-sale-pos-woocommerce"
    "simple-news"
    "logbook"
    "image-hover-effects-for-visual-composer"
    "freshchat"
    "wc-donation-platform"
    "ws-theme-addons"
    "content-slider-block"
    "lazy-facebook-comments"
    "smooth-page-scroll-updown-buttons"
    "facebook-like-send-button"
    "block-spam-by-math-reloaded"
    "private-google-calendars"
    "custom-emails-for-woocommerce"
    "themify-icons"
    "advanced-twenty-seventeen"
    "thumbnail-cleaner"
    "wp-live-css-editor"
    "builder-template-categories"
    "customizer-login-page"
    "google-image-sitemap-feed-with-multisite-support"
    "disable-wp-notification"
    "realbig-media"
    "http-authentication"
    "catalog-for-woocommerce"
    "title-to-tags"
    "ad-rotator"
    "background-image-cropper"
    "superb-slideshow"
    "seo-tool-keyword-density-checker"
    "event-tickets-with-ticket-scanner"
    "code-prettify"
    "photo-gallery-builder"
    "bit-assist"
    "table-sorter"
    "embed-sched"
    "custom-page-templates-by-vegacorp"
    "csv-2-post"
    "webflow-pages"
    "photospace-responsive"
    "reviews-widgets-for-yelp"
    "slick-engagement"
    "pta-member-directory"
    "easy-code-manager"
    "track-connect"
    "loggedin"
    "hot-random-image"
    "newspack-newsletters"
    "wp-amp-it-up"
    "authors-list"
    "add-lightbox"
    "template-kit-export"
    "custom-simple-rss"
    "wt-yandex-metrika"
    "wp-auto-featured-image"
    "ibuildapp"
    "usagedd"
    "true-lazy-analytics"
    "miniorange-malware-protection"
    "which-template-file"
    "embed-google-fonts"
    "bambora-online-checkout"
    "wc-custom-thank-you"
    "widget-builder"
    "ical-for-wp-calendar"
    "image-widget-rb"
    "bolt-checkout-woocommerce"
    "block-for-woo-product-table"
    "liveagent"
    "query-wrangler"
    "fs-real-estate-plugin"
    "word-press-flow-player"
    "page-loading-effects"
    "superb-slideshow-gallery"
    "woo-price-per-unit"
    "custom-api-for-wp"
    "bulk-datetime-change"
    "pods-alternative-cache"
    "gravitywp-css-selector"
    "freshdesk-support"
    "news-manager"
    "ajax-hits-counter"
    "woo-product-enquiry"
    "reviewscouk-for-woocommerce"
    "products-compare-for-woocommerce"
    "woo-to-facebook-shop"
    "cb-custom-modules"
    "wpsso-tune-image-editors"
    "ogp"
    "wp-reservation"
    "rt-easy-builder-advanced-addons-for-elementor"
    "fb-messenger-chat-for-website"
    "gravity-slider-fields"
    "pagination-styler-for-woocommerce"
    "bp-toolkit"
    "wp-smart-tv"
    "social-sharing-block"
    "auto-image-alt"
    "tabs-widget-for-page-builder"
    "termageddon-usercentrics"
    "export-wp-users-xml-csv"
    "super-zoom-gallery"
    "admin-taxonomy-filter"
    "autocomplete-address-for-woocommerce"
    "wp-custom-login"
    "functionality"
    "embed-chessboard"
    "bootstrap-modals"
    "user-feedback-and-ratings-by-social-intents"
    "wc-payoneer-payment-gateway"
    "bop-search-box-item-type-for-nav-menus"
    "bbb-wplms"
    "void-visual-whmcs-element"
    "payhere-payment-gateway"
    "commerce-coinbase-for-woocommerce"
    "lead-call-buttons"
    "woo-payment-bkash"
    "theme-blvd-wpml-bridge"
    "pushalert-web-push-notifications"
    "custom-shipping-methods-for-woocommerce"
    "yt-player"
    "simple-student-result"
    "wcsdm"
    "ymc-smart-filter"
    "search-box-on-navigation-menu"
    "cf7-add-password-field"
    "contact-form-to-any-api"
    "joan"
    "links-shortcode"
    "send-link-to-friend"
    "wp-edit-password-protected"
    "jquery-news-ticker"
    "disable-visual-editor-wysiwyg"
    "wp-hr-manager"
    "bp-classic"
    "buy-now-button-for-woocommerce"
    "instantio"
    "server-side-cache-autopurge"
    "show-modified-date-in-admin-lists"
    "awesome-ads"
    "cookie-warning"
    "wpsso-strip-schema-microdata"
    "tp-woocommerce-product-gallery"
    "speed-up-javascript-to-footer"
    "lifterlms-labs"
    "ni-woocommerce-cost-of-goods"
    "mihdan-elementor-yandex-maps"
    "wordable"
    "poeditor"
    "wp-russian-typograph"
    "jetpack-module-control"
    "pageviews"
    "gravity-forms-placeholders"
    "contact-form-multi"
    "admin-collapse-subpages"
    "where-did-they-go-from-here"
    "lh-archived-post-status"
    "wooexim"
    "just-tables"
    "metric-converter"
    "russian-post-and-ems-for-woocommerce"
    "js-jobs"
    "hidepost"
    "buddypress-sitewide-activity-widget"
    "book-review"
    "wp-night-mode"
    "advanced-featured-post-widget"
    "pretty-pinterest-pins"
    "callpage"
    "popup-dialog-box"
    "pw-woocommerce-bogo-free"
    "delete-comments-by-status"
    "generate-post-thumbnails"
    "wpcasa"
    "master-post-advert"
    "dropshipping-xml-for-woocommerce"
    "content-mask"
    "button-customizer-for-woocommerce"
    "coingate-for-woocommerce"
    "reaction-buttons"
    "mobile-detector"
    "goolytics-simple-google-analytics"
    "zoom-image"
    "web-fonts"
    "perfecty-push-notifications"
    "simple-seo"
    "auto-prune-posts"
    "darklup-lite-wp-dark-mode"
    "add-custom-header-images"
    "pulsemaps"
    "beam-me-up-scotty"
    "candid-advanced-toolset"
    "popularity-posts-widget"
    "thumbnail-upscale"
    "bluet-keywords-tooltip-generator"
    "cbcurrencyconverter"
    "bangladeshi-payment-gateways"
    "flexible-quantity-measurement-price-calculator-for-woocommerce"
    "feedwordpress-duplicate-post-filter"
    "cf7-repeatable-fields"
    "brid-video-easy-publish"
    "cm-ad-changer"
    "easy-wp-cleaner"
    "language-switcher-for-transposh"
    "rss-icon-widget"
    "woo-better-shipping-calculator-for-brazil"
    "importify"
    "woo-conditional-discount-rules-for-checkout"
    "cf7-redirect-thank-you-page"
    "twitter-mentions-as-comments"
    "wenprise-pinyin-slug"
    "easy-charts"
    "woocommerce-fixed-quantity"
    "art-woocommerce-order-one-click"
    "convertbox-auto-embed"
    "f12-profiler"
    "xt-facebook-events"
    "tour-booking-manager"
    "hotspots"
    "crm-customer-relationship-management-by-vcita"
    "shorten2ping"
    "enable-svg-webp-ico-upload"
    "contact-form-7-recaptcha"
    "imagelinks-interactive-image-builder-lite"
    "word-replacer"
    "simple-signup-form"
    "fancy-elementor-flipbox"
    "contact-form-ready"
    "web-directory-free"
    "very-simple-google-maps"
    "simple-image-link"
    "wpb-woocommerce-related-products-slider"
    "formzu-wp"
    "network-posts-extended"
    "agreeable"
    "woocommerce-html5-video"
    "featured-image-column"
    "backup-and-move"
    "wordpress-tweaks"
    "google-web-fonts-customizer-gwfc"
    "simple-masonry-layout"
    "3b-meteo"
    "deal-or-announcement-with-countdown-timer"
    "order-status-rules-for-woocommerce"
    "mobilook"
    "bb-bootstrap-cards"
    "wp-relativedate"
    "easync-booking"
    "wp-anything-slider"
    "alt-manager"
    "heroic-table-of-contents"
    "elex-hide-woocommerce-shipping-methods-basic"
    "royal-mail-woocommerce-shipping-calculator"
    "views-for-ninja-forms"
    "theme-preview"
    "embed-google-photos-album-easily"
    "taboola"
    "pw-woocommerce-copy-coupon"
    "woocommerce-parcelas"
    "delucks-seo"
    "product-variant-table-for-woocommerce"
    "cool-fade-popup"
    "photoshow"
    "vimeo"
    "bitpay-checkout-for-woocommerce"
    "automatic-responsive-tables"
    "bee-layer-slider"
    "kopa-nictitate-toolkit"
    "wp-post-views"
    "youtube-brackets"
    "advanced-accordion-block"
    "linkedin-master"
    "post-from-site"
    "better-file-editor"
    "woocommerce-video-product-tab"
    "contact-information-widget"
    "pretty-google-calendar"
    "testimonial"
    "admin-in-english"
    "information-reel"
    "wpcom-member"
    "continuous-image-carousel-with-lightbox"
    "plus-webp"
    "woocommerce-apg-free-postcodestatecountry-shipping"
    "legal-texts-connector-it-recht-kanzlei"
    "wp-cleanumlauts2"
    "wp-woo-product-social-share"
    "wp-coming-soon-booster"
    "wp-baidu-map"
    "wp-full-stripe-free"
)

# Define user agents with weights
declare -A USER_AGENTS
USER_AGENTS=(
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"]=5
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"]=7
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"]=6
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36 Edg/91.0.864.54"]=5
    ["Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 OPR/77.0.4054.277"]=3
    ["Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (iPad; CPU OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Vivaldi/4.0"]=1
    ["Mozilla/5.0 (Android 11; Mobile; rv:68.0) Gecko/68.0 Firefox/88.0"]=1
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"]=15
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/534.36"]=12
)

OPENED_PLUGINS_FILE="${WORDPRESS_WORKDIR}/opened_plugins.txt"
CLOSED_PLUGINS_FILE="${WORDPRESS_WORKDIR}/closed_plugins.txt"
LAST_VERSION_FILE="${WORDPRESS_WORKDIR}/last_versions.txt"
PARALLEL_JOBS=1

DOWNLOAD_ALL_PLUGINS='n'
LIST_ONLY='n'
ALL_PLUGINS_FILE="${WORDPRESS_WORKDIR}/wp-plugin-svn-list.txt"

DELAY_DOWNLOADS='n'
DELAY_DURATION=5

FORCE_UPDATE='n'
CACHE_ONLY='n'

mkdir -p "$WORDPRESS_WORKDIR" "$MIRROR_DIR" "$LOGS_DIR"
rm -f "$OPENED_PLUGINS_FILE"
touch "$OPENED_PLUGINS_FILE"
DEBUG_MODE=0

while getopts "p:dalD:t:fc" opt; do
    case ${opt} in
        p ) PARALLEL_JOBS=$OPTARG ;;
        d ) DEBUG_MODE=1 ;;
        a ) DOWNLOAD_ALL_PLUGINS='y' ;;
        l ) LIST_ONLY='y' ;;
        D ) DELAY_DOWNLOADS=$OPTARG ;;
        t ) DELAY_DURATION=$OPTARG ;;
        f ) FORCE_UPDATE='y' ;;
        c ) CACHE_ONLY='y' ;;    # New option for cache-only
        \? ) echo "Usage: $0 [-p PARALLEL_JOBS] [-d] [-a] [-l] [-D DELAY_DOWNLOADS] [-t DELAY_DURATION] [-f] [-c]" 1>&2; exit 1 ;;
    esac
done

debug_log() {
    if [ "$DEBUG_MODE" -eq 1 ]; then
        echo "[DEBUG] $1" >&2
    fi
}

get_random_user_agent() {
    echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
}

get_latest_version_and_download_link() {
    local plugin=$1
    debug_log "Checking latest version and download link for $plugin"
    
    local api_url="https://api.wordpress.org/plugins/info/1.0/${plugin}.json"
    local user_agent=$(get_random_user_agent)
    local api_response=$(curl -s -H "User-Agent: $user_agent" "$api_url")
    
    if echo "$api_response" | jq -e '.error' >/dev/null; then
        local error_message=$(echo "$api_response" | jq -r '.error')
        if [ "$error_message" = "closed" ]; then
            echo "closed"
            return 2
        else
        echo "Error: $error_message for plugin $plugin" >&2
        return 1
        fi
    fi
    
    local version=$(echo "$api_response" | jq -r '.version // empty')
    local download_link=$(echo "$api_response" | jq -r '.download_link // empty')
    
    if [ -n "$version" ] && [ -n "$download_link" ]; then
        echo "$version $download_link"
        return 0
    else
        echo "Error: Cannot fetch version or download link for $plugin" >&2
        return 1
    fi
}

download_plugin() {
    local plugin=$1
    local version=$2
    local api_download_link=$3
    local output_file="${MIRROR_DIR}/${plugin}.${version}.zip"
    local header_file="${LOGS_DIR}/${plugin}.${version}.headers"
    local constructed_download_link="${DOWNLOAD_BASE_URL}/${plugin}.${version}.zip"
    local download_link

    if [ "$DEBUG_MODE" -eq 1 ]; then
        debug_log "API-provided download link for $plugin: $api_download_link"
        debug_log "Constructed download link for $plugin: $constructed_download_link"
    fi

    if [ "$DOWNLOAD_LINK_API" == 'y' ] && [ -n "$api_download_link" ]; then
        download_link="$api_download_link"
        debug_log "Using API-provided download link for $plugin: $download_link"
    else
        download_link="$constructed_download_link"
        debug_log "Using constructed download link for $plugin: $download_link"
    fi

    debug_log "Downloading $plugin version $version through Cloudflare Worker"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)
    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o /dev/null "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    else
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o "$output_file" "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    fi

    if [ $? -eq 0 ]; then
        if [ "$CACHE_ONLY" == 'y' ]; then
            debug_log "Plugin $plugin version $version cached successfully."
            return 0
        fi

        local file_size=$(stat -c%s "$output_file")
        if [ "$file_size" -lt 1000 ]; then
            echo "Error: Downloaded file for $plugin is too small (${file_size} bytes). Possible download issue." >&2
            return 1
        fi

        local source=$(grep -i "X-Source:" "$header_file" | cut -d' ' -f2 | tr -d '\r')
        if [ "$source" == "R2" ]; then
            debug_log "Successfully downloaded $plugin version $version from R2 storage"
        elif [ "$source" == "WordPress" ]; then
            debug_log "Successfully downloaded $plugin version $version from WordPress"
            debug_log "R2 bucket saving for plugin zip occurred"
        else
            debug_log "Skipped download for $plugin $version zip (already exists locally)"
        fi

        return 0
    else
        echo "Error: Failed to download $plugin version $version" >&2
        return 1
    fi
}

save_plugin_info() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.json"

    debug_log "Saving plugin json metadata for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying metadata download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    if [ "$CACHE_ONLY" == 'y' ]; then
        # When in cache-only mode, output to /dev/null
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin metadata for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache json metadata for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            if [ "$source" = "R2" ]; then
                debug_log "json metadata for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "json metadata for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin json occurred"
            else
                debug_log "json metadata for $plugin version $version saved (json metadata file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save json metadata for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

fetch_and_save_checksums() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.checksums.json"

    debug_log "Fetching and saving checksums for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying checksums download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    debug_log "Sending request to Worker for checksums: CF_WORKER_URL?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"

    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin checksums for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache checksums for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        debug_log "Received response with status code: $status_code"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            debug_log "Response source: $source"
            if [ "$source" = "R2" ]; then
                debug_log "Checksums for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "Checksums for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin checksums occurred"
            else
                debug_log "Checksums for $plugin version $version saved (checksums file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save checksums for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

process_plugin() {
    local plugin=$1
    plugin=$(echo "$plugin" | sed 's/^\/\|\/$//g')

    # Check if the plugin is already known to be closed
    if grep -q "^$plugin$" "$CLOSED_PLUGINS_FILE" 2>/dev/null; then
        echo "Plugin $plugin is known to be closed. Skipping."
        return 0
    fi

    echo "Processing plugin: $plugin"

    VERSION_AND_LINK=$(get_latest_version_and_download_link "$plugin")
    local version_check_status=$?
    
    if [ $version_check_status -eq 1 ]; then
        echo "Skipping $plugin due to version fetch error."
        return 1
    elif [ $version_check_status -eq 2 ]; then
        echo "Plugin $plugin is closed. Skipping download and processing."
        echo "$plugin" >> "$CLOSED_PLUGINS_FILE"
        if save_plugin_info "$plugin" "closed"; then
            debug_log "Successfully saved json metadata for closed plugin $plugin."
        else
            debug_log "Failed to save json metadata for closed plugin $plugin."
        fi
        return 0
    fi
    
    LATEST_VERSION=$(echo "$VERSION_AND_LINK" | cut -d' ' -f1)
    API_DOWNLOAD_LINK=$(echo "$VERSION_AND_LINK" | cut -d' ' -f2-)

    debug_log "Latest version for $plugin: $LATEST_VERSION"
    debug_log "API download link for $plugin: $API_DOWNLOAD_LINK"

    STORED_VERSION=$(grep "^$plugin" "$LAST_VERSION_FILE" | awk '{print $2}')
    debug_log "Stored version for $plugin: $STORED_VERSION"

    if [ "$CACHE_ONLY" != 'y' ] && [ "$LATEST_VERSION" == "$STORED_VERSION" ] && [ -f "${MIRROR_DIR}/${plugin}.${LATEST_VERSION}.zip" ]; then
        echo "$plugin is up-to-date and exists in mirror directory. Skipping download..."
    else
        start_time=$(date +%s.%N)

        if download_plugin "$plugin" "$LATEST_VERSION" "$API_DOWNLOAD_LINK"; then
            if [ "$CACHE_ONLY" != 'y' ]; then
                sed -i "/^$plugin/d" "$LAST_VERSION_FILE"
                echo "$plugin $LATEST_VERSION" >> "$LAST_VERSION_FILE"
            fi
            echo "Successfully processed $plugin."
        else
            echo "Error: Failed to process $plugin." >&2
        fi

        end_time=$(date +%s.%N)
        duration=$(echo "$end_time - $start_time" | bc)
        printf "Time taken for %s: %.4f seconds\n" "$plugin" "$duration"
    fi

    if save_plugin_info "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully saved json metadata for $plugin."
    else
        debug_log "Failed to save json metadata for $plugin."
    fi

    if fetch_and_save_checksums "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully fetched and saved checksums for $plugin."
    else
        debug_log "Failed to fetch and save checksums for $plugin."
    fi

    if [ $version_check_status -eq 0 ]; then
        echo "$plugin" >> "$OPENED_PLUGINS_FILE"
    fi
}

populate_all_plugins() {
    if [ ! -f "$ALL_PLUGINS_FILE" ] || [ "$LIST_ONLY" == 'y' ]; then
        echo "Fetching list of all WordPress plugins..."
        svn list https://plugins.svn.wordpress.org/ | sed 's/\/$//g' > "$ALL_PLUGINS_FILE"
        plugin_count=$(wc -l < "$ALL_PLUGINS_FILE")
        echo "Plugin list (${plugin_count}) saved to $ALL_PLUGINS_FILE"
    fi
    
    if [ "$LIST_ONLY" == 'n' ]; then
        ALL_PLUGINS=()
        while IFS= read -r line; do
            ALL_PLUGINS+=("$line")
        done < "$ALL_PLUGINS_FILE"
        echo "Loaded ${#ALL_PLUGINS[@]} plugins."
    fi
}

if [ "$LIST_ONLY" == 'y' ]; then
    populate_all_plugins
    echo "Plugin list created. Exiting without downloading."
    exit 0
fi

if [ "$DOWNLOAD_ALL_PLUGINS" == 'y' ]; then
    populate_all_plugins
    COMBINED_PLUGINS=("${ALL_PLUGINS[@]}")
else
    if [ ! -d "$PLUGIN_DIR" ]; then
        echo "Warning: Plugin directory $PLUGIN_DIR does not exist or is invalid."
        PLUGIN_LIST=()
    else
        PLUGIN_LIST=($(ls -d "$PLUGIN_DIR"/*/ 2>/dev/null | xargs -n 1 basename))

        if [ ${#PLUGIN_LIST[@]} -eq 0 ]; then
            echo "No plugins found in $PLUGIN_DIR."
        fi
    fi

    COMBINED_PLUGINS=(${PLUGIN_LIST[@]} ${ADDITIONAL_PLUGINS[@]})
    COMBINED_PLUGINS=($(echo "${COMBINED_PLUGINS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
fi

if [ ${#COMBINED_PLUGINS[@]} -eq 0 ]; then
    echo "No plugins to download. Exiting."
    exit 0
fi

mkdir -p "$MIRROR_DIR"
touch "$LAST_VERSION_FILE"

if [ "$PARALLEL_JOBS" -gt 1 ]; then
    echo "Running in parallel with $PARALLEL_JOBS jobs..."
    echo "Variables before export:"

    # WordPress-related directories
    echo "WORDPRESS_WORKDIR: $WORDPRESS_WORKDIR"
    echo "PLUGIN_DIR: $PLUGIN_DIR"
    echo "MIRROR_DIR: $MIRROR_DIR"
    echo "LOGS_DIR: $LOGS_DIR"

    # Cloudflare Worker related URLs
    echo "CF_WORKER_URL: $CF_WORKER_URL"

    # Flags and options
    echo "DOWNLOAD_LINK_API: $DOWNLOAD_LINK_API"
    echo "DOWNLOAD_ALL_PLUGINS: $DOWNLOAD_ALL_PLUGINS"
    echo "LIST_ONLY: $LIST_ONLY"
    echo "DELAY_DOWNLOADS: $DELAY_DOWNLOADS"
    echo "DELAY_DURATION: $DELAY_DURATION"
    echo "FORCE_UPDATE: $FORCE_UPDATE"
    echo "CACHE_ONLY: $CACHE_ONLY"

    # File paths
    echo "OPENED_PLUGINS_FILE: $OPENED_PLUGINS_FILE"
    echo "CLOSED_PLUGINS_FILE: $CLOSED_PLUGINS_FILE"
    echo "LAST_VERSION_FILE: $LAST_VERSION_FILE"
    echo "ALL_PLUGINS_FILE: $ALL_PLUGINS_FILE"

    # Parallel job configuration
    echo "PARALLEL_JOBS: $PARALLEL_JOBS"

    # User Agents mapping
    echo "USER_AGENTS: ${USER_AGENTS[@]}"

    # Additional plugins to be processed
    # echo "ADDITIONAL_PLUGINS: ${ADDITIONAL_PLUGINS[@]}"

    # Plugin List (loaded from directory or ALL_PLUGINS_FILE)
    #echo "PLUGIN_LIST: ${PLUGIN_LIST[@]}"
    #echo "COMBINED_PLUGINS: ${COMBINED_PLUGINS[@]}"

    # First, export all variables including USER_AGENTS
    export DOWNLOAD_BASE_URL MIRROR_DIR LAST_VERSION_FILE DEBUG_MODE DOWNLOAD_LINK_API LOGS_DIR ALL_PLUGINS_FILE DOWNLOAD_ALL_PLUGINS LIST_ONLY CF_WORKER_URL DELAY_DOWNLOADS DELAY_DURATION FORCE_UPDATE CACHE_ONLY WORDPRESS_WORKDIR PLUGIN_DIR PARALLEL_JOBS OPENED_PLUGINS_FILE CLOSED_PLUGINS_FILE USER_AGENTS

    # Then, export the functions
    export -f process_plugin get_latest_version_and_download_link download_plugin debug_log populate_all_plugins save_plugin_info get_random_user_agent fetch_and_save_checksums
    printf "%s\n" "${COMBINED_PLUGINS[@]}" | xargs -P $PARALLEL_JOBS -I {} bash -c 'process_plugin "$@"' _ {}
else
    for plugin in "${COMBINED_PLUGINS[@]}"; do
        process_plugin "$plugin"
    done
fi

if [ -f "$CLOSED_PLUGINS_FILE" ]; then
    echo
    echo "Closed Plugin List:"
    cat "$CLOSED_PLUGINS_FILE" | sort | uniq || true
    echo
    echo "Total closed plugins: $(wc -l < "$CLOSED_PLUGINS_FILE")"
    echo
else
    echo
    echo "No closed plugins found."
    echo
fi
echo "Plugin download process completed."
