#!/bin/bash

# Base directory (script location)
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Configurable directories
WORDPRESS_WORKDIR="${WORDPRESS_WORKDIR:-$BASE_DIR/wordpress-plugins}"
PLUGIN_DIR="${PLUGIN_DIR:-$BASE_DIR/wp-content/plugins}"
MIRROR_DIR="${MIRROR_DIR:-$BASE_DIR/mirror}"
LOGS_DIR="${LOGS_DIR:-$BASE_DIR/plugin-logs}"

# Check for CF_WORKER_URL environment variable
if [ -z "$CF_WORKER_URL" ]; then
    echo "Error: CF_WORKER_URL environment variable is not set." >&2
    exit 1
fi

DOWNLOAD_BASE_URL="https://downloads.wordpress.org/plugin"

# Other variables
DOWNLOAD_LINK_API='y'

ADDITIONAL_PLUGINS=(
    "gosquared-official"
    "dp-intro-tours"
    "image-magnify"
    "timesheet"
    "gpp-welcome-message"
    "otpless"
    "wb-custom-product-tabs-for-woocommerce"
    "classified-ads"
    "bbpress-new-topics"
    "dropbox-upload-form"
    "mshop-naver-talktalk"
    "archive-page"
    "codecogs-latex-equation-editor"
    "woo-file-dropzone"
    "pricemesh"
    "cosmica-advance-sections"
    "manual-payment-gateway-bkash"
    "mark-new-posts"
    "go-newrelic"
    "ravens-antispam"
    "wpmuldap"
    "xolo-websites"
    "pwd-wp-login"
    "cryptoniq-lite"
    "gps-tracker"
    "popstats"
    "blocks-for-shopengine"
    "netgo-expandablecollapsible-menu"
    "mailster-block-forms"
    "visibility-control-for-learndash"
    "imageboss"
    "my-recent-youtube-widget"
    "auto-clean-url-seo"
    "cf7-to-mailjet"
    "woo-shipping-additional-days"
    "wp-table-of-paginated-contents"
    "flying-fonts"
    "wp-flex-contact-form"
    "ninja-galleries"
    "mstw-league-manager"
    "ams-google-webmaster-tools"
    "wp-editor-bootstrap-blocks"
    "shortcode-to-display-post-and-user-data"
    "nextgen-tinymce-description"
    "woocommerce-customer-who-viewed-this-item-also-viewed"
    "bootstrap-main-menu-responsive"
    "add-to-header"
    "mycred-blocks"
    "automatically-update-permalinks"
    "wallwisher-shortcode"
    "pie-forms-for-wp"
    "import-tweets-as-posts"
    "atec-cache-info"
    "product-table-for-woocommerce"
    "wirecard-woocommerce-extension"
    "hide-wp"
    "sidebars-for-helloelementortheme"
    "woo-wp-login"
    "iknow-extra"
    "captchinoo-captcha-for-login-form-protection"
    "buddypress-community-stats"
    "personal-admin-footer"
    "sfce-create-event"
    "google-plus-comments"
    "timeline-history"
    "damnsexybookmarks"
    "quentn-wp"
    "wordpress-paypal-donation"
    "coronavirus-data-widgets"
    "seo-pyramid"
    "advance-canonical-url"
    "sprout-invoices-wp-forms"
    "forumconverter"
    "post-thumbnail-extras"
    "galleria-galleria"
    "mdt-reviews"
    "wp-ad-gallery"
    "writio"
    "schema-review"
    "shopready-elementor-addon"
    "html5-cumulus"
    "wp-last-modified"
    "coinremitter-crypto-payment-gateway"
    "lazy-load-for-images"
    "responsive-logo-slideshow"
    "woocommerce-hear-about-us"
    "acf-tooltip"
    "flagship-woocommerce-shipping"
    "genesis-simple-comments"
    "tune-library"
    "widgets-as-shortcodes"
    "mailplus-forms"
    "simple-theme-demo-importer"
    "hubwoo-integration"
    "wp-braintree"
    "find-posts-using-attachment"
    "wompi-el-salvador"
    "course-scheduler-for-learndash"
    "typer-core"
    "pure-metafields"
    "user-meta-display"
    "soisy-pagamento-rateale"
    "twenty-ten-header-rotator"
    "wp-sendsms"
    "unsafe-mimetypes"
    "extra-privacy-for-elementor"
    "woo-giftcards"
    "global-javascript"
    "wp-amazon-carousel"
    "paypal-responder"
    "twitter-avatar-reloaded"
    "wp-postratings-cheater"
    "wp-addonchat"
    "wp-file-get-contents"
    "weaver-for-bbpress"
    "color-palette"
    "wp-custom-cssjs"
    "simply-snow"
    "only-one-device-login-limit"
    "feedburner-footer-slideup"
    "nofollow-links-in-posts"
    "gooten-dropshipping-for-woocommerce"
    "wp-smart-pagination"
    "bulk-edit-events"
    "misiek-page-category"
    "newsletter-block-by-gutena"
    "nextsale-for-woocommerce"
    "smart-post-grid"
    "duplica"
    "poky-product-importer"
    "media-player-style-kit"
    "botpenguinbot"
    "elegance-modal-box"
    "recaptcha-for-bbpress"
    "fb-viral-downloader"
    "rest-api-custom-fields"
    "wp-custom-avatar"
    "ultimate-markdown"
    "fast-chat-button"
    "simple-event-attendance"
    "multiple-post-type-order"
    "widget-recent-posts-with-category-choice"
    "all-in-one-invite-codes"
    "certificate-verification"
    "fontier"
    "wp-vk"
    "bottom-admin-toolbar"
    "reorder-terms"
    "daring-fireball-linked-list"
    "razorpay-gravity-forms"
    "tailpress"
    "comment-info-detector"
    "codeswholesale-for-woocommerce"
    "thumbgen"
    "campus-directory"
    "fast-page-switch"
    "widget-menuizer"
    "template-tag-shortcodes"
    "bdvs-password-reset"
    "crossword-compiler-puzzles"
    "wp-table-reloaded-compatible-for-wp-minify"
    "2d-tag-cloud-widget-by-sujin"
    "querywall"
    "testimonial-by-weblizar"
    "oomph-clone-widgets"
    "wp-theme-optimizer"
    "cloud"
    "eazy-under-construction"
    "cf7-infusionsoft"
    "idea-factory"
    "f2-tag-cloud-widget"
    "copy-move-posts"
    "woocommerce-paypal-here-gateway"
    "mobile-friendly-flickr-slideshow"
    "wc-checkout-getnet"
    "simple-featured-image"
    "woo-direct-checkout-lite"
    "marquee-running-text"
    "bestprice-analytics-integration"
    "animated-typed-js-shortcode"
    "visual-verse-of-the-day-widget"
    "wp2leads"
    "the-guardian-news-feed"
    "tfm-google-product-feed"
    "wp-tube"
    "em-beer-manager"
    "contact-form-7-hide-success-message"
    "excerpt-length"
    "font-squirrel"
    "simple-widget-display-conditions-lite"
    "contact-form-7-star-rating"
    "sort-query-posts"
    "contact-form-db-divi"
    "markdown-on-save"
    "mapifylite"
    "remove-admin-bar-logo"
    "oembed-manager"
    "woocommerce-custom-price"
    "display-name-author-permalink"
    "better-section-navigation"
    "woocommerce-delivery-date"
    "blockskit"
    "esewa"
    "mobilize"
    "cloudflare-stream"
    "woo-checkout-on-popup-free"
    "lh-multisite-cors"
    "remove-taxonomy-url"
    "bws-google-2-step-verification"
    "service-boxes-widgets-text-icon"
    "wpc-ajax-search"
    "perfect-coming-soon-page"
    "free-quotation"
    "exam-matrix"
    "content-widget"
    "gutena-testimonial"
    "powies-uptime-robot"
    "wa11y"
    "raffle-play-woo"
    "wc-digital-goods-checkout"
    "ajax-comment-pager"
    "responsible"
    "comment-spam-wiper"
    "wp-jv-post-reading-groups"
    "affiliate"
    "all-in-one-bookmarking-button"
    "comment-reply-email"
    "custom-dashboard-help"
    "speedguard"
    "woo-event-manager"
    "ang-timeline"
    "kiyoh-customerreview"
    "megaoptim-image-optimizer"
    "collapsed-archives"
    "cf7-builder"
    "8degree-fly-menu-lite"
    "credova-financial"
    "multilang-contact-form"
    "multisite-user-sync"
    "fusion-extension-image"
    "dashboard-widgets-learndash"
    "mycred-h5p"
    "clear-autoptimize-cache-automatically"
    "quick-child-theme-generator"
    "user-frontend-for-elementor"
    "scroll-popup-html-content-ads"
    "content-copy-protection-disable-right-click"
    "appeto-woocommerce"
    "embed-rentle"
    "small-phone-button-basic"
    "video-gallery-block"
    "real-accessability"
    "you-have-a-new-message"
    "jetpack-post-statistic-link-plugin"
    "mhm-forceimagemagick"
    "wp-fancybox"
    "boopis-woocommerce-rfq"
    "change-wp-url"
    "wp-internal-links-lite"
    "decategorizer"
    "knowledgebase"
    "discord-display"
    "heic-support"
    "official-markerly-widget"
    "jcwp-copy-paste-blocker"
    "wpc-order-tip"
    "ezusy-image-swatches-for-variable-product"
    "browser-blocker"
    "url-shortcodes"
    "rocket-reader-speed-reader"
    "merchr-print-on-demand"
    "better-user-search"
    "eshop-languages"
    "social-share-by-wp-dev-shed"
    "green-money-payment-gateway"
    "wordpress-video"
    "wpdevart-pricing-table"
    "fullscreen-slider"
    "back-end-instructions"
    "gforms-export-entries"
    "ozh-simpler-login-url"
    "rename-media"
    "shutterstock"
    "author-recommended-posts"
    "eds-responsive-menu"
    "banglkb"
    "gamipress-notifications-by-type"
    "custom-image-src"
    "tarokina-free"
    "esv-crossref"
    "anyshare"
    "wp-find-your-nearest"
    "wc-spod"
    "easy-embed"
    "great-caroussel"
    "random-tags-cloud-widget"
    "happyfox-chat"
    "classified"
    "whosamungus-whos-amung-us"
    "host-php-info"
    "address-autocomplete-contact-form-7"
    "wp-limit-failed-login-attempts"
    "social2blog"
    "reamaze"
    "eventsads-banner"
    "wp-disable-updates"
    "very-simple-sitemap"
    "send-email-from-admin"
    "wp-ajax-user-chat"
    "better-wlm-api"
    "zalo-live-chat"
    "mag-products-integration"
    "wp-raptor"
    "amazing-post-widget"
    "faq-schema-markup-faq-structured-data"
    "slayers-ad-integration"
    "shortcurl"
    "bns-login"
    "ft-password-protect-children-pages"
    "mas-wp-job-manager-company-reviews"
    "menu-cart-divi"
    "genesis-style-select"
    "urdu-formatter-shamil"
    "video-comments-webcam-recorder"
    "edd-download-images"
    "minimum-length-for-contact-form-7"
    "statsfc-table"
    "good-url-preview-box"
    "woo-update-variations-in-cart"
    "job-manager-by-jobscore"
    "simple-download-counter"
    "wp-subscription-forms"
    "woo-pagadito-payment-gateway"
    "post-expire-date-sidebar"
    "seos"
    "mtphr-members"
    "ap-gravatars"
    "social-space"
    "wp-category-order"
    "hola-free-video-player"
    "table-layout"
    "utw-importer"
    "runners-log"
    "goo-translate-widget"
    "flags-widget"
    "super-custom-login"
    "append-extensions-on-pages"
    "most-popular-post"
    "custom-excerpts"
    "woo-products-restricted-users"
    "acf-archive"
    "select-multiselect-field-contact-form-7"
    "my-default-post-content"
    "wishful-companion"
    "lh-private-buddypress"
    "agy-verification"
    "locker-cat"
    "aviary-editor"
    "brackets-ninja"
    "rate-star-review"
    "lrw-so-widgets-bundle"
    "scategory-permalink"
    "top-contributors"
    "mailersend-official-smtp-integration"
    "eduadmin-booking"
    "grouptivity"
    "baw-wordpress-plugin-security-checker"
    "flip-box-block"
    "column-separator-for-beaver-builder"
    "pretty-file-links"
    "keyring-social-importers"
    "simple-expires"
    "block-editor-bootstrap-blocks"
    "amp-blocks"
    "qtvr-viewer"
    "wp-seo-images"
    "trust-payments-gateway-3ds2"
    "3d-photo-gallery"
    "autocomplete-location-field-contact-form-7"
    "wp-show-login-form"
    "never-let-me-go"
    "custom-admin-url"
    "gravity-forms-notification-attachments"
    "custom-dashboard-page"
    "cf7-submission-dom-tracking"
    "wpsso-wc-shipping-delivery-time"
    "recent-posts-shortcode-widget"
    "popslide"
    "get-params"
    "post-featured-video"
    "wanderlust-andreani-shipping"
    "variations-radio-buttons-for-woocommerce"
    "events-manager-email-users"
    "avecdo-for-woocommerce"
    "info"
    "cestina-zalomeni-radku"
    "contact-form-7-map-field"
    "widget-indicadores-economicos-chile"
    "surbma-divi-lightbox"
    "podcast-feed-player-widget"
    "simple-light-box"
    "turbosmtp"
    "bulk-seo-image"
    "nlingual"
    "gold-price-live"
    "smooth-dynamic-slider"
    "wp-outdated-browser"
    "woo-save-and-share-cart"
    "lws-sms"
    "sales-booster"
    "happy-new-year"
    "extended-profile"
    "akamai"
    "yd-profile-visitor-tracker"
    "create-with-code"
    "svg-autocrop"
    "wc-disable-zoom-lightbox-features"
    "kirimemail-form-integration"
    "smart-faq"
    "coordinadora"
    "car-route-planner"
    "responsive-portfolio-image-gallery"
    "client-proof-visual-editor"
    "latex2html"
    "artpal"
    "multiple-portfolios"
    "visual-subtitle"
    "tinymce-signature"
    "genesis-js-no-js"
    "widgets-for-expedia-reviews"
    "yet-another-social-plugin"
    "bulk-select-featured-image"
    "contact-info"
    "wppool-turnstile-captcha-spam-filter"
    "syntaxhighlighter-ckeditor-button"
    "wp-adblock-dedect"
    "multisite-custom-css"
    "ozpost-multiquote"
    "mprm-menu-cart"
    "social-sidebar"
    "preload-images"
    "custom-breakpoints-for-elementor"
    "edd-service-extended"
    "slide2comment"
    "theatre-wp"
    "sweet-custom-dashboard"
    "interswitch-webpay-woocommerce-payment-gateway"
    "oc2wp-bookmarks"
    "tazapay"
    "import-products-to-wc"
    "canvas-image-resize"
    "rest-api-post-embeds"
    "wp-menu-image"
    "socketlabs"
    "splash-connector"
    "woo-product-shortcodes"
    "wp-owl-carousel"
    "related-posts-line-up-exactry-by-milliard"
    "wechat-payment-for-woo"
    "woo-bigpost-shipping"
    "image-size-selection"
    "super-search"
    "insert-blocks-before-or-after-posts-content"
    "post-list-generator"
    "better-passwords"
    "abd-dashboard-widget-manager"
    "slide-box"
    "coffee-admin-theme"
    "ultimate-preloader"
    "google-maps-ve"
    "related-posts-widget"
    "tweetbutton-for-wordpress"
    "jne-shipping"
    "header-and-footer-script-adder"
    "wp-edit-username"
    "cp2ce"
    "bbpress-votes"
    "wordpress-checkout"
    "review-widgets-for-opentable"
    "bp-multi-network"
    "backend-designer"
    "page-restrict-for-woocommerce"
    "ticketmachine-event-manager"
    "realty-portal"
    "mailgun-email-validator"
    "email-validator-for-contact-form-7"
    "easy-page-flip"
    "born-on-this-day"
    "digital-clock"
    "jeepers-peepers"
    "custom-menu-class"
    "simple-qrcode"
    "tc-testimonial"
    "responsive-twentyten"
    "minimum-age-woocommerce"
    "lava-real-estate-manager"
    "sina-weibo-plugin-for-wordpress"
    "fastbook-responsive-appointment-booking-and-scheduling-system"
    "store-file-uploads-for-contact-form-7"
    "instant"
    "yslider"
    "seo-editor"
    "nicejob"
    "businesspress"
    "deactive-visual-editor"
    "friendfeed-comments"
    "stp-importer"
    "affilinker"
    "better-block-patterns"
    "moods-addon-for-ultimate-tinymce"
    "personizely"
    "anylink"
    "loan-comparison"
    "csv-importer-improved"
    "contact-us-page"
    "variable-column-block"
    "simple-content-construction-kit"
    "302-moved-temporarily"
    "alphas-categories-widget"
    "creative-wp-login-page"
    "fontsampler"
    "custom-user-registration-lite"
    "marketplace-bitcoin-gateway"
    "wpjm-company-profile-page"
    "appthemes-classipress-ads-importer-plugin"
    "i-agree-popups"
    "https-switcher"
    "iwg-hide-dashboard"
    "stratus"
    "easythumbnail-sizes"
    "quick-empty-trash"
    "wp-essentials"
    "att-youtube"
    "german-slugs"
    "cf-meta-tags"
    "tidy-up"
    "hide-links"
    "sketch-bookmarks"
    "rentsyst"
    "our-team-members"
    "sortable-word-count-reloaded"
    "navigation-du-lapin-blanc"
    "wp-event-calender"
    "plugin-output-cache"
    "woo-search-by-product-sku"
    "easy-fattura-elettronica-free"
    "laobuluo-baidu-submit"
    "redirect-post-to-url"
    "wp-open-graph-meta"
    "livebeep"
    "futy-widget"
    "library-management-system"
    "graph-lite"
    "product-assembly-cost"
    "add-quantity-field-on-shop-page-for-woocommerce"
    "wp-testimonials-oiiio"
    "author-profiler"
    "dropbox-cdn"
    "webshipper-automated-shipping"
    "woocommerce-remove-quantity-fields"
    "full-screen-background-css-jquery"
    "post-carousel-addons-for-elementor"
    "media-library-enable-infinite-scrolling"
    "ni-woocommerce-admin-order-columns"
    "simple-faq"
    "squeeze-page-toolkit"
    "custom-login-and-admin-urls"
    "move-comments"
    "russian-currency"
    "posts-and-users-stats"
    "lastfm-rps"
    "3d-viewer-block"
    "offen"
    "themx-maximum-upload-file-size"
    "toggle-content"
    "wordpress-twitter"
    "wp-front-end-login-and-register"
    "woo-cart-redirect-to-checkout-page"
    "display-product-variations-dropdown-on-shop-page"
    "disable-trackbacks"
    "ctabs"
    "simple-admin-notes"
    "metrika"
    "ht-portfolio"
    "wp-author-widget"
    "audio-story-images"
    "mobile-only-desktop-only-content"
    "ascending-posts"
    "allow-javascript-in-text-widgets"
    "emails-catch-all"
    "page-cornr"
    "insert-giphy-block"
    "wpseo-nuke-noob-stuff"
    "newsmanapp"
    "draft-notifier"
    "bp-search-block"
    "reinstall-themes"
    "bp-profile-message-ux"
    "offer-calc"
    "automatic-subdomains"
    "lead-generation"
    "random-post-shortcode"
    "meta-store-elements"
    "pretty-url"
    "sportsteam-widget"
    "sticky-headers"
    "js-vehicle-manager"
    "we-blocks"
    "ab-testing-for-wp"
    "micropoll"
    "strx-simple-sharing-sidebar-widget"
    "user-stats"
    "unlock-protocol"
    "addons-for-kingcomposer"
    "channel-io"
    "genealogy"
    "day-of-week"
    "banner-slider"
    "preloader-sws"
    "sweet-custom-menu"
    "presenter"
    "support-me"
    "simple-user-profile"
    "heatmap"
    "hal"
    "post-block"
    "get-first-image-set-as-featured-image"
    "spoiler-block"
    "woo-autocomplete-search-bar"
    "drafts-dropdown"
    "service-showcase"
    "woocommerce-for-paygent-payment-main"
    "peters-blog-url-shortcodes"
    "youtubefancybox"
    "acf-sidebar-selector-field"
    "import-from-ning"
    "scf-dummy-content"
    "bitcoinnews"
    "myqaptcha"
    "email-creatior"
    "auto-tooltip"
    "wptd-video-popup"
    "bangla-fonts-collection"
    "user-list"
    "photopress-masonry-gallery"
    "tilopay"
    "clear-cache-for-timber"
    "pdf-thumbnail-generator"
    "genesis-logo-uploader"
    "tinypng-for-wp"
    "timeline-express-single-column-add-on"
    "wp-taxonomy-order"
    "banner-manager"
    "manage-user-columns"
    "6storage-rentals"
    "wp-project-managment-ultimate"
    "wp-category-manager"
    "totally-booked"
    "ithink-logistics-ecommerce-shipping-in-india"
    "rvcfdi-para-woocommerce"
    "wpac-like-system"
    "apoyl-weixinshare"
    "mix-master"
    "tab-me"
    "wptextresizecontrols"
    "simple-archive-generator"
    "open-hours"
    "gd-mail-queue"
    "vigilantor"
    "in-twitter"
    "continually"
    "informational-popup"
    "bbpress-simple-advert-units"
    "faire-for-woocommerce"
    "bbpress-members-only"
    "max-addons-for-bricks"
    "easy-post-to-post-links"
    "da-tinymce-restore"
    "application-insights"
    "formaloo-form-builder"
    "flipdish-ordering-system"
    "posturinn"
    "featured-image-widget-slider"
    "wp-tabbed-widget"
    "commonwp"
    "carquery-api"
    "no-login-by-email-address"
    "paymob-for-woocommerce"
    "addsearch-instant-search"
    "easyme-connect"
    "mybookprogress"
    "professional-share"
    "simple-terms-and-conditions-for-buddypress"
    "post-kits-for-elementor"
    "aeroleads-contact-us-details"
    "custom-fields-shortcodes"
    "libro-de-reclamaciones-y-quejas"
    "gsheetconnector-gravity-forms"
    "wp-page-extension"
    "timeline-pro"
    "twitter-bird"
    "zia3-css-js"
    "btc-exchange-widget"
    "journalpress"
    "posts-slideshow-widget"
    "woocommerce-khipu"
    "related-articles"
    "custom-taxonomy-category-and-term-fields"
    "acf-hide-layout"
    "donation-block-for-stripe-by-givewp"
    "sports-leagues"
    "annuncifunebri-onoranza"
    "bing-maps-for-wordpress"
    "b-timeline"
    "wc-m-pesa-payment-gateway"
    "meteorite-extensions"
    "wp-s3-smart-upload"
    "default-admin-color-scheme"
    "checkout-address-sugessions-for-woocommerce"
    "wp-team-list"
    "posts-widget"
    "flowcharts-ai"
    "cf7-spreadsheets"
    "blog-summary"
    "wp-shinystat"
    "bulk-edit-publish-date"
    "lh-agree-to-terms"
    "wp-job-manager-filter-widget"
    "add-replace-affiliate-links-for-amazon"
    "skyboot-portfolio-gallery"
    "full-screen-search-overlay"
    "full-woo-commerce-admin"
    "easy-post-view-counter"
    "post-and-page-excerpt-widgets"
    "tally-graph"
    "woocommerce-bundle-style-coupons"
    "geo-phone-master"
    "eg-series"
    "plyr"
    "wp-vimeo-videos"
    "posts-grid"
    "gizzmo-ai"
    "clean-seo-slugs"
    "maintenance-notice"
    "feedoptimise"
    "product-slider-carousel"
    "recently"
    "no-comment-links"
    "recently-updated-pages"
    "post-status-menu-items"
    "2046s-widget-loops"
    "pollme"
    "pago-redsys-tpv-grafreak"
    "auto-update-plugins"
    "sprout-invoices-formidable-forms"
    "realtyna-core"
    "the-piecemaker"
    "real-post-slider-lite"
    "advanced-custom-fields-viewer"
    "am-lottieplayer"
    "cache-warmer"
    "enable-contributor-uploads"
    "vectr-embedded-graphics-editor"
    "wp-sponsor-flip-wall"
    "wp-hotel-booking-authorize-payment"
    "wp-adsterra-dashboard"
    "pagbank-for-woocommerce"
    "featured-content-showcase"
    "vikrentitems"
    "wp-unitpngfix"
    "snowstorm"
    "adsoptimal"
    "rate-it"
    "custom-twitter-widget-pro"
    "offload-media-cloud-storage"
    "faviroll"
    "ae-visitor"
    "add-custom-codes"
    "wp-sanitize-accented-uploads"
    "avantlink-integration-for-woocommerce"
    "modulobox-lite"
    "reiseblog-widgets"
    "step-by-step-ordering-system-for-woocommerce"
    "super-cool-ad-inserter"
    "chennai-central"
    "gamipress-activity-by-category"
    "wp-media-optimizer-webp"
    "botblocker"
    "special-social-sharing-icons"
    "portugal-ctt-tracking-woocommerce"
    "farazsms"
    "woo-mercadopago-gateway-checkout"
    "wb-ads-rotator-with-split-test"
    "php-server-info"
    "awesome-gallery"
    "jalbum-bridge"
    "fc-mortgage-calculator"
    "olivewp-companion"
    "smntcs-deactivate-image-compression"
    "switch-video-quality"
    "contest-code-checker"
    "wp-otp"
    "staggs"
    "sb-paginate"
    "p2-resolved-posts"
    "affiliate-plus"
    "promote-extensions"
    "wp-action-network"
    "restore-jquery"
    "yabe-webfont"
    "code-click-to-copy"
    "wps-telegram-chat"
    "eazy-login-logo"
    "comment-referrers"
    "kodo-qiniu"
    "blog-post-filter"
    "remove-generator-tag-for-wordpress"
    "u-more-recent-posts"
    "campaign-url-builder"
    "wp-choose-thumb"
    "imporved-simpler-css"
    "knowledge-tags-from-yext"
    "bosta-woocommerce"
    "constant-contact-form"
    "reset-customizer"
    "bangla-font-fixer"
    "bpdev-username-availability-checker"
    "my-missed-schedule"
    "display-html-sitemap"
    "better-resource-hints"
    "todays-date-inserter"
    "bigmailchimp"
    "paypro-gateways-woocommerce"
    "wp-hotjar"
    "kento-testimonial-slider"
    "jb-horizontal-scroller-news-ticker"
    "image-title-remove"
    "collector-checkout-for-woocommerce"
    "grid-accordion-lite"
    "remove-posts-in-category-from-homepage"
    "wordpress-clock"
    "replace-variable-price-range-by-chosen-variation-price-woocommerce"
    "small-package-quotes-wwe-edition"
    "drm-protected-video-streaming"
    "if-so-geolocation"
    "printaura-woocommerce-api"
    "wc-variation-swatches"
    "free-education-helper"
    "bootstrapcdn"
    "affinipay-woocommerce"
    "google-search-cse"
    "richtext-extension"
    "remove-p"
    "add-class-to-elementor-image"
    "buddypress-profile-views"
    "woocomerce-price-by-country"
    "fastspring"
    "cs-shop"
    "vendi-cache"
    "staticpress2019"
    "video-metabox"
    "responsive-menu-card-price-list-items"
    "best-upsell-for-woocommerce"
    "wp-identicon"
    "remoji"
    "strx-youtube-widget"
    "very-simple-password"
    "wp-seo-paginate"
    "user-last-login"
    "picture-organizer"
    "style-manager"
    "qh-testpay"
    "mascaras-para-cf7"
    "acf-page-builder"
    "attach-files-widget"
    "tabsy"
    "bbp-profile-information"
    "social-networks"
    "web-hosting"
    "infinite-scroll-and-ajax-load-more"
    "sheet2site"
    "use-bunnyfont-host-google-fonts"
    "advance-social-sharer"
    "yelp-bar"
    "inline-frame-iframe"
    "ez-staff-list"
    "qqworld-passport"
    "pinyin-slug"
    "cache-cleaner"
    "product-tabs-for-woocommerce"
    "campi-moduli-italiani"
    "kcsg-kartra-pages"
    "header-footer-custom-html"
    "black-widgets"
    "content-security-policy-pro"
    "timeline-verite-shortcode"
    "best-flash-games"
    "progress-bars"
    "mighty-pros-cons"
    "easy-html-sitemap"
    "related-posts-lite"
    "hq-widgets-for-elementor"
    "styled-calendar-customized-google-calendars"
    "google-map-professional"
    "duplicate-title-validate"
    "genesis-custom-backgrounds"
    "ggpush"
    "ziteboard-online-whiteboard"
    "chart-block"
    "tournament-bracket-generator"
    "ai-content-creator"
    "rss-feed-pro"
    "gc-social-wall"
    "woo-sendle-shipping-method"
    "nabz-image-gallery"
    "connect-sendgrid-for-emails"
    "category-page-extender"
    "user-social-profiles"
    "genesis-simple-page-sections"
    "category-excluder"
    "rest-api-console"
    "extended-crm-for-users-insights"
    "surveys-by-feedback-cat"
    "import-shopify-to-wp"
    "risk-free-cash-on-delivery-cod-woocommerce"
    "connections-business-directory-languages"
    "courier-notices"
    "affiliates-events-manager"
    "dynamic-subpages"
    "advanced-search-by-my-solr-server"
    "vcgs-toolbox"
    "wavatars"
    "gravity-pre-submission-confirmation"
    "wp-donate"
    "paypro-global-payment-gateway-for-premiumpress"
    "finteza-analytics"
    "zenfoliopress"
    "responsive-iframe"
    "live-chat-support-system"
    "imajinn-ai"
    "charts-ninja-graphs-and-charts"
    "easy-csv-importer"
    "docs-to-wordpress"
    "gif-master"
    "bible-reading-plans"
    "euro-fxref-currency-converter"
    "text-beautify"
    "logo-and-address-widget-with-schema"
    "was-this-article-helpful"
    "wc-itau-shopline"
    "wp-google-maps-shortcode"
    "memberspace"
    "gamipress-learndash-group-leaderboard"
    "better-image-credits"
    "bbpress-multi-image-uploader"
    "ultimate-member-gallery"
    "metatrader-web-terminal"
    "floating-publish-button"
    "altima-lookbook-free-for-woocommerce"
    "canvas-nestjs"
    "l7-login-customizer"
    "wc-shipping-discount"
    "gs-instagram-portfolio"
    "wp-visual-adverts"
    "hideshowpassword"
    "cookie-monster"
    "esselinknu-settings"
    "wp-get-post-image"
    "rt-newrelic-browser"
    "ambrosite-unlink-parent-pages"
    "pmpro-constant-contact"
    "rating-bws"
    "viewmedica"
    "devvn-local-store"
    "codehaveli-bitly-url-shortener"
    "beomps-korea-postcode-search"
    "simple-email-subscriber"
    "cf7-sweet-alert-popup"
    "laravel-dd"
    "entrywizard"
    "retina-2x"
    "flickrapi"
    "wp-pop-up"
    "affiliates-manager-woocommerce-subscription-integration"
    "ithoughts-tooltip-glossary"
    "optional-email"
    "external-db-auth-reloaded"
    "expandable-dashboard-recent-comments"
    "coming-soon-countdown"
    "genesis-nav-menu-amplified"
    "send-to-mpesa-payment-gateway"
    "publishpress-statuses"
    "about-me-image-widget"
    "siteheart"
    "permalink-validator"
    "wc-departamentos-y-ciudades-colombia"
    "wp-munich-blocks"
    "link-to-bible"
    "mhr-banner"
    "tinypic-lt"
    "slide"
    "nertworks-all-in-one-social-share-tools"
    "rss-feed-anywhere"
    "zazzle-store-gallery"
    "wp-rest-api-pure-taxonomies"
    "wp-iframe-images-gallery"
    "word-count-and-limit"
    "cf7-summary-and-print"
    "squad-modules-for-divi"
    "easy-categories-management-widget"
    "universal-voice-search"
    "qikink-pod-and-drop-shipping"
    "marmoset-viewer"
    "a-smart-excerpt"
    "wp-auth"
    "manuall-dofollow"
    "simple-post-series"
    "nested-ordered-lists"
    "click-to-call-or-chat-buttons"
    "wpcopyrights"
    "totalcontest-lite"
    "simple-seo-categories-posts"
    "infocob-crm-forms"
    "comment-email-reply"
    "woo-sale-discount-scheduler"
    "gf-zendesk"
    "show-content-only"
    "blurry-mobile-menu"
    "piwigomedia"
    "slider-bws"
    "e20r-members-list"
    "ccm19-integration"
    "disable-flamingo-addressbook"
    "wp-statusnet"
    "proofreading"
    "digirisk"
    "future"
    "conexao-wc-mercado-livre"
    "acf-nav-menu-field"
    "woo-visual-hook-guide"
    "disclaimer-popup"
    "popular-post-widget"
    "wp-remote-thumbnail"
    "gravatarlocalcache"
    "shopify"
    "wp-pro-real-estate-7-xml-csv-property-listings-import"
    "dollie"
    "branded-social-images"
    "ninja-araclar"
    "plugins-load-order"
    "ya-turbo"
    "iamport-payment"
    "envoke-supersized"
    "admin-menu-search"
    "remote-provisioning"
    "conditional-add-to-cart"
    "benchmark"
    "chatlive"
    "navigation-menu-ids-classes"
    "woocommerce-bulk-percentage-pricing"
    "rebuild-permalinks"
    "quadpay-gateway-for-woocommerce"
    "spiderpowa-embed-pdf"
    "notifly"
    "vendor-city"
    "add-hierarchy-parent-to-post"
    "stock-export-and-import-for-woocommerce"
    "b-social-share"
    "auto-featured-image-auto-generated"
    "fp-news-ticker"
    "admin-menu-post-list"
    "latch"
    "nicescrollr"
    "base-item-list"
    "shopmagic-for-contact-form-7"
    "xili-postinpost"
    "organized-docs"
    "yd-recent-images"
    "wp-invoice-ultimate"
    "event"
    "tradedoubler-affiliate-tracker"
    "oscar-hotel-booking-engine"
    "product-editor"
    "affiliatewp-sign-up-bonus"
    "ams-post-and-page-duplicator"
    "scroll-to-up"
    "prevent-password-reset"
    "better-wordpress-syntax-based-on-geshi"
    "yakkyofy"
    "storelocator"
    "wc-banco-inter"
    "user-cats-manager"
    "price-offerings-for-woocommerce"
    "calconic"
    "pco-image-widget-field"
    "erima-zarinpal-donate"
    "easy-filter"
    "publitio-offloading"
    "custom-wp-rest-api"
    "falang-for-elementor-lite"
    "page-excerpt-widget"
    "gravity-forms-bootstrap-3-style"
    "meetup-widgets"
    "contribuinte-checkout"
    "hide-header-on-posts-for-a-landing-page"
    "byline"
    "posts"
    "ez-zenback"
    "wp-digg-this"
    "wc-exporter-for-danea"
    "build-app-online"
    "fix-multiple-redirects"
    "hide-real-download-path"
    "smartcat-wpml"
    "post-slider-lite"
    "star-rating-block"
    "wp-server"
    "tag-cloud-shortcode"
    "buddypress-sticker"
    "cision-block"
    "pinterest-importer"
    "new-year-countdown-clock"
    "grunion-ajax"
    "woo-guaranteed-reviews-company"
    "phone2app"
    "laughing-squid-dashboard-widget"
    "jetpack-only-for-admins"
    "reuse-builder"
    "adjustly-nextpage"
    "wp-login-logo"
    "easy-font-resize"
    "quote-of-the-day-and-random-quote"
    "blue-wrench-videos-widget"
    "wp-jscrollpane"
    "gateway-aqayepardakht-for-woocommerce"
    "taxonomy-tinymce"
    "linkedin-inshare-button"
    "edd-product-slider"
    "wp-notice-popup"
    "wc-order-search-admin"
    "website-openclosed-toggle"
    "like-share-zalo-button"
    "acf-contact-form-7"
    "navception"
    "team-display"
    "markup-markdown"
    "inbbe-chat-bot"
    "reviews-widgets"
    "smart-popup-blaster"
    "list-related-attachments-widget"
    "wc-kalkulator"
    "mxp-dev-tools"
    "ithemeland-woo-bulk-orders-editing-lite"
    "inline-footnotes"
    "wp-to-klick-tipp-tag-basiertes-e-mail-marketing"
    "my-twitpics"
    "recent-posts-from-each-category"
    "copyproof-website"
    "subscriptions-renewal-reminders"
    "dregister"
    "admin-bar-id-menu"
    "youtube-upload-widget"
    "simple-map-no-api"
    "footnotes-for-wordpress"
    "bitly-linker"
    "shinystat-analytics"
    "wp-google-ad-manager-plugin"
    "simple-twitter-plugin"
    "wp-finance"
    "benchmark-email-wordpress"
    "crazyrocket-pop-ups"
    "email-validator-by-byteplant"
    "wp-scanner"
    "responsive-testimonials"
    "payment-gateway-via-valitor-for-woocommerce"
    "already-existing-tags"
    "css-optimizer-remove-unused-css"
    "muki-tag-cloud"
    "shayanweb-admin-fontchanger"
    "manage-customized-plugin-updates"
    "swiss-toolkit-for-wp"
    "jobwp"
    "neville-extensions"
    "talkjs"
    "frontier-restrict-media"
    "wpcasa-contact-form-7"
    "ninja-footers-lite"
    "wp-education"
    "bew-menu-cart"
    "hide-titles-on-hover"
    "transaction-integration-for-affiliatewp-and-optimizepress"
    "woocommerce-calculate-shipping-button"
    "wp-plugin-security-check"
    "jf-simple-coming-soon"
    "get-subpages-list"
    "refer-a-friend-program-for-woocommerce"
    "login-in-widget"
    "vfb-custom-validation-messages"
    "visual-recipe-index"
    "wp-inline-edit"
    "friendfeed-activity-widget"
    "better-links"
    "wp-mautic-form-integrator"
    "create-user-with-password-multisite"
    "maximum-purchase-for-woocommerce"
    "contact-form-7-leads-tracking"
    "php-to-pages"
    "translate-this-google-translate-web-element-shortcode"
    "taketin-to-wp-membership"
    "effect-maker"
    "ni-woocommerce-sales-report-by-user-role"
    "index-wp-users-for-speed"
    "front-end-pm-ultimate-member-integration"
    "bootstrap-buttons"
    "playpress"
    "exchange-rates-today"
    "news-cpt"
    "bread-crumb-matching-any-theme-skin"
    "paydunya-woocommerce-payment-gateway"
    "wp-cpg-widget"
    "embed-block-for-tiktok"
    "responsive-google-maps"
    "class-blogs"
    "adsense-under-image"
    "simple-adsense"
    "wp-export-all-post-information-excel-format"
    "cf7-zendesk"
    "yasip"
    "add-email-signature"
    "buttons-to-edit-next-previous-post"
    "parallax-scrolling-enllax-js"
    "echbay-admin-security"
    "wp-news-ticker"
    "ip2location-variables"
    "post-count"
    "emc2-popup-disclaimer"
    "fusion-extension-button"
    "chatlio"
    "ketchup-coupons"
    "ht-event"
    "wp-require-auth"
    "listar-directory-listing"
    "implied-cookie-consent"
    "my-quicktags"
    "recent-photos"
    "woocommerce-basic-ordernumbers"
    "kapost-byline"
    "wp-js-list-pages-shortcodes"
    "ht-mega-for-wpbakery"
    "admin-bar-edit-page-links"
    "ark-hidecommentlinks"
    "sellix-pay"
    "instant-gzip-compression"
    "enhanced-menu-editor"
    "tweetpress"
    "connect-shopify-and-woocommerce"
    "woocommerce-google-adwords-conversion-tracking"
    "advanced-comments"
    "live-broadcast"
    "list-sub-pages"
    "subpage-view"
    "elements-hive-for-breakdance"
    "webling"
    "p2-by-email"
    "oembed-soundcloud"
    "ws-custom-scrollbar"
    "wp-db-driver"
    "wd3k-ajax-sliding-contact-form"
    "m2wp"
    "gravity-forms-highrise"
    "p-login"
    "photo-protect"
    "custom-cookie-message"
    "marketplace-for-woocommerce"
    "good-old-share"
    "elite-licenser-lite"
    "buddypress-real-names"
    "creative-portfolio"
    "x-scroll-to-top-responsive"
    "booking-calendar-with-availability-management"
    "search-by-product-tags-for-woocommerce"
    "embedder"
    "bb-toolbox"
    "wp-4-me-title-remover"
    "atr-portfolio"
    "wp-override-translations"
    "add-watermark"
    "wp-user-chat"
    "simple-social-icon-widget"
    "javascript-flickr-badge"
    "bp-profile-cover"
    "checkmail-validation-for-contact-form-7"
    "actblue-contributions"
    "wen-call-to-action"
    "paymentwall-for-woocommerce"
    "responsive-block-control"
    "responsive-client-logo-carousel-slider"
    "wpoptin"
    "jcarousel-for-wordpress"
    "bbp-buddypress-profile-information"
    "digital-signature-for-contact-form-7"
    "wp-steam-auth"
    "tdd-recent-posts"
    "scheduled-post-guardian"
    "multiple-admin-email-addresses"
    "smooth-scroll"
    "birthday-discount-vouchers"
    "simple-login-form"
    "google-news-xml-sitemap-generator"
    "easy-scheduled-posts"
    "cursor-control"
    "qr-code-tag-for-wc-from-goaskle-com"
    "cforms2-really-simple-captcha"
    "card-oracle"
    "ip2location-world-clock"
    "item-lists-for-elementor"
    "amelia-calendar-essential-shortcodes"
    "hide-related-video-youtube"
    "jiangqie-free-mini-program"
    "ghl-wizard"
    "toggles"
    "debug-wp-redirect"
    "comment-mention"
    "pdf2post"
    "wp-facebox"
    "countdown-flipclock"
    "mailpoet-paid-memberships-pro-add-on"
    "coin-stats-cryptocurrency-widgets"
    "customized-wysiwyg-editor-page-widths"
    "identify-external-links"
    "easy-logo-link-change"
    "easy-replace-image"
    "teletter-telegram-newsletter"
    "show-all-pages-url"
    "slash-edit"
    "kikfyre-events-calendar-tickets"
    "shipping-zone-duplicator-for-woocommerce"
    "m1miniweather"
    "mp-tweet-list"
    "cf7-preview"
    "code-snippet-dm"
    "real-kit"
    "custom-field-manager"
    "contentde"
    "automatic-alternative-text"
    "admin-bar-wrap-fix"
    "extended-options"
    "commonsbooking"
    "show-website-content-in-wordpress-page-or-post"
    "htaccess-server-info-server-status"
    "jotform-shopping-cart"
    "gravity-forms-upload-rules"
    "firsth3tagadsense"
    "rss-filter"
    "tgchannel"
    "rest-api-enabler"
    "netlifes-tag-cloud-fatcloud"
    "zarinpal-paid-memberships-pro"
    "nicer-permalinks-for-vietnamese"
    "speech-to-text"
    "convert-experiments"
    "author-product-review"
    "mytory-markdown"
    "simple-session-support"
    "wp-proposals"
    "posts-to-do-list"
    "buddypress-upload-avatar-ajax"
    "alt-text-tools"
    "buddypress-russian-months"
    "tagline-rotator"
    "bp-local-avatars"
    "edd-additional-shortcodes"
    "link-widget-title"
    "cryptomus"
    "wp-permalink-translator"
    "wc-correios-easy-tracking-code"
    "hexam"
    "roundit"
    "image-gallery-with-ajax-comments"
    "scanpay-for-woocommerce"
    "guitar-chord-widget-for-wordpress"
    "snap-pixel-for-woocommerce"
    "easy-featured-images"
    "lorem-ipsum-block"
    "webspeechapi-for-wp"
    "post-connector"
    "clickwhale"
    "pesapal-for-woocommerce"
    "gt-post-approval"
    "post-type-convertr"
    "simple-youtube-shortcode"
    "unilevel-mlm-plan"
    "totalprocessing-card-payments"
    "mycred-birthdays"
    "us-weather-widget-willyweather"
    "ai-content-generation"
    "animate"
    "wp-roadmap"
    "surbma-divi-project-shortcodes"
    "caspers-fly-in-cta"
    "export-comment-authors"
    "buddypress-block-activity-stream-types"
    "anything-order"
    "classic-smilies"
    "linkedin-profile-badge"
    "easy-theme-options"
    "easy-table-rate-shipping-for-woocommerce"
    "custom-image-sizes-by-99-robots"
    "user-role-based-shipping-method"
    "3d-snow"
    "tube-video-ads-lite"
    "os-media"
    "widget-saver"
    "woocommerce-customer-delivery-date-time-selection"
    "woo-autocomplete-checkout-address"
    "wp-fakeloader"
    "codescar-radio-widget"
    "myaliceai"
    "wpupyun"
    "affiliates-manager-paid-membership-pro-integration"
    "aviasalesru-search-widget"
    "oqey-add-ons"
    "fc-savings-calculator"
    "bbpress2-shortcode-whitelist"
    "aweos-wp-lock"
    "mofuse"
    "woo-gls-print-label-and-tracking-code"
    "network-username-restrictions-override"
    "complete-image-sitemap"
    "3cx-webinars"
    "money-manager"
    "excitel-click-to-call"
    "website-toolbox-chat-rooms"
    "color-posts"
    "read-more-link"
    "wp-user-stylesheet-switcher"
    "automatic-post-scheduler"
    "cool-ryan-easy-popups"
    "embed-soundcloud-block"
    "smart-watermark"
    "birthday-emails"
    "affiliates-manager-google-recaptcha-integration"
    "adaptive-learning-with-learndash"
    "yelp-reviews-ticker"
    "wc-ship-est"
    "panorom"
    "adwords-remarketing"
    "bee-offline"
    "super-light-cache-buster"
    "weeconnectpay"
    "vr-views"
    "wpml-translate-shortcode"
    "contact-form-7-multi-step-addon"
    "wp-pubsubhubbub"
    "simple-analitycs-tag-manager"
    "magic-the-gathering-card-tooltips"
    "author-recent-posts"
    "two-factor-2fa-via-email"
    "floating-login"
    "404-to-home"
    "dirtysuds-category-thumbnail"
    "widgets-of-posts-by-same-categories"
    "amazify"
    "cube-3d-slider"
    "product-category-dropdowns"
    "bulk-featured-image"
    "grassblade-xapi-learnpress"
    "wdes-responsive-mobile-menu"
    "ultimate-carousel-for-divi"
    "hq-rental-software"
    "only-one-category"
    "zeno-report-comments"
    "indian-currency-inr-symbol-for-woocommerce"
    "fusion-extension-map"
    "firephp-firebug-php"
    "calculator"
    "splitit-installment-payments"
    "comment-quicktags"
    "wpsection"
    "dashboard-columns"
    "accessibility-by-audioeye"
    "email-verification-for-contact-form-7"
    "immonex-kickstart"
    "wp-random-post-inside"
    "automatic-tag-link"
    "fv-testimonials"
    "image-cdn"
    "pbp-iul"
    "sopa-blackout"
    "must-read-posts"
    "marketing-automation"
    "generate-cache"
    "slide-in-popup"
    "xml-sitemap-for-stella"
    "wcpas-product-attributes-shortcode"
    "regiones-de-chile-para-woocommerce"
    "chromeless-youtube"
    "village-client-area"
    "site-pin"
    "cleaner-dashboard"
    "weather-widget-by-calcatraz"
    "manageview-your-posts-only"
    "siteground-email-marketing"
    "nagad-payment-gateway"
    "simple-site-lockdown"
    "snapscan-online-payments"
    "dp-admin-pagepost-menus"
    "currently-reading"
    "disqus-popular-posts"
    "simple-revision-control"
    "youtube-subscriber"
    "disable-right-click-and-content-copy-protection"
    "blockly"
    "bulkpress-export"
    "wovn-io"
    "warning"
    "munk-sites"
    "gleam"
    "winsite-image-optimizer"
    "pressidium-cookie-consent"
    "pre-publish-reminders"
    "category-posts-slider-pro"
    "nice-page-transition"
    "color-manager"
    "wp-redirect-permalink"
    "press-news-events"
    "toolbar-extras-mainwp"
    "disable-rest-api-and-require-jwt-oauth-authentication"
    "edd-variable-pricing-descriptions"
    "youngwhans-simple-latex"
    "contact-us-simple-form"
    "order-status-history-for-woocommerce"
    "image-for-open-graph-meta"
    "open-search-document"
    "ig-shortcodes"
    "octolize-shipping-notices"
    "wp-dynamic-links"
    "jigoshop-store-toolkit"
    "infusionsoft-web-tracker"
    "page-protection"
    "world-weather"
    "related-posts-flatsome"
    "lytebox"
    "image-alt-text"
    "tedtalks-embedder"
    "soft79-cart-links-for-woocommerce"
    "va-removing-exif"
    "coin-miner"
    "movie-database"
    "events-manager-pro-securesubmit-gateway"
    "admangler"
    "addon-gravityforms-sendinblue-free"
    "linet-erp-woocommerce-integration"
    "altis-accelerate"
    "order-auto-complete-for-woocommerce"
    "user-session-control"
    "woocommerce-sort-by-stock"
    "media-library-tools"
    "wp-perfect-plugin"
    "handtalk"
    "advanced-export"
    "fixed-circular-navigation-menu"
    "dropcaps-shortcodes-and-widget"
    "crypto-voucher-widget"
    "woo-custom-fee"
    "gamipress-wc-points-per-purchase-total"
    "blocks-export-import"
    "seo-site-auditor-agency"
    "acf-multisite-sync"
    "dadi-cookie-consent-lite"
    "5usujian-super-serv"
    "persian-admin-fonts"
    "easy-child-theme-creator"
    "google-authenticator-encourage-user-activation"
    "telegram-chat"
    "lfecfdi-para-woocommerce"
    "imperfect-quotes"
    "allow-numeric-stubs"
    "postmatic-social-commenting"
    "auto-publish-tumblr"
    "supersonic"
    "phetsarath-ot"
    "free-web-push-notification"
    "wpb-floating-menu-or-categories"
    "free-dictionary"
    "tabs-pro"
    "bp-messages-tool"
    "adwork-media-ez-content-locker"
    "wpsite-content-resharer"
    "veeqo-for-woocommerce"
    "wp-utf8-sanitize"
    "lana-breadcrumb"
    "disable-password-reset"
    "stellar-places"
    "push-syndication"
    "ocultar-anadir-al-carrito"
    "mealingua"
    "bbp-last-post"
    "kostenlose-immobilienbewertung-lead-generator"
    "wpc-pinterest-widget"
    "cpt-archives-in-nav-menus"
    "wpradio"
    "sar-one-click-security"
    "woocommerce-display-products-by-tags"
    "fg-fix-serialized-strings"
    "abwp-simple-counter"
    "product-bundles-variation-bundles"
    "smart-countdown-fx-easy-recurring-events"
    "voya-chile-lugares-y-cotizador-de-despachos"
    "zotya-htaccess-protect"
    "wcs-custom-permalinks-hotfix"
    "buddypress-edit-activity-stream"
    "flamix-bitrix24-and-contact-forms-7-integrations"
    "wp-typed-js"
    "boxed-content"
    "extend-link"
    "seo-help"
    "inline-preview"
    "pie-calendar"
    "easysnippet"
    "multi-twitter-widget"
    "tinycoffee"
    "wp-dash-message"
    "ecards-lite"
    "cp-referrer-and-conversions-tracking"
    "acf-media-credit"
    "mobile-app-editor"
    "news-bar"
    "eu-cookie-consent"
    "translit-it"
    "flexible-faq"
    "ab-video"
    "echbay-tag-manager"
    "multi-rss-reader-widet"
    "wp-insert-rss-thumbnails"
    "woocommerce-view"
    "azaflash-retargeting"
    "mybloglog-recent-reader-widget"
    "gmaps-for-visual-composer-free"
    "theme-blvd-image-sizes"
    "advanced-custom-fields-nextgen-gallery-custom-field"
    "easy-backstretch"
    "bing-website-translator"
    "full-breadcrumb"
    "gravity-forms-dps-pxpay"
    "wp-ie-buster"
    "shatner-name-your-own-price-for-woocommerce"
    "linkify-categories"
    "textbuilder"
    "multilingual-text"
    "snappay-alipay-wechat-payment-gateway"
    "wp-anchor-header"
    "fp-linkedin-profile"
    "disqus-notify-content-author"
    "realty"
    "easy-google-syntax-highlighter"
    "ect-add-to-cart-button"
    "store-credit-for-woocommerce"
    "gdpr-press"
    "convertor-valutar-curs-bnr"
    "woo-for-elementor"
    "emerchantpay-payment-page-for-woocommerce"
    "wp-default-sender-email-by-it-pixelz"
    "dinamize"
    "zendrop-dropshipping-and-fulfillment"
    "ats-privacy-policy"
    "amb-variable-affiliate-products-for-woocommerce"
    "wp-rc-reply-ajax"
    "wp-easy-booking"
    "google-docs-rsvp-guestlist"
    "aparat-responsive"
    "pdf-embed-block"
    "hoo-companion"
    "list-urls"
    "seo-content-helper"
    "sms-notifications-for-woocommerce"
    "clp-custom-login-page"
    "wptools-masonry-gallery-posts-for-divi"
    "full-comments-on-dashboard"
    "sweepwidget"
    "wp-salesforce"
    "custom-nextpage"
    "wp-find-and-replace"
    "cleanup-action-scheduler"
    "eber"
    "akaunting-for-woocommerce"
    "menu-in-menu"
    "ticketack"
    "loading-bar"
    "wp-reset-comment-form"
    "wideo"
    "cookies-pro"
    "dc-simple-share-buttons"
    "auto-approve-comments"
    "while-it-is-loading"
    "virus-finder"
    "fancyboxify"
    "bbp-jp-utility"
    "vibe-buddypress-woocommerce"
    "gravity-forms-click-pledge"
    "editor-enhancer-for-oxygen"
    "easy-wordpress-mailchimp-integration"
    "wp-users-disable"
    "getpaid-wallet"
    "simple-custom-login"
    "order-attachment-for-woocommerce"
    "apoyl-baidupush"
    "auto-login-when-resister"
    "chat2"
    "podigee"
    "smart-custom-display-name"
    "webd-woocommerce-advanced-reporting-statistics"
    "image-link"
    "speed-up-page-cache"
    "kramer"
    "cf7-advanced-datepicker"
    "greenhouse-job-board"
    "buy-x-get-y-free-by-storepro"
    "imagedrop"
    "front-page-scheduler"
    "ajar-productions-in5-embed"
    "acf-real-media-library-field"
    "google-webfonts-integrate"
    "wordpress-quotes"
    "portfolio-mgmt"
    "timeline-express-no-icons-add-on"
    "toms-image-slider"
    "css-cache-buster"
    "yql-auto-tagger"
    "myadmanager"
    "woocommerce-sales-by-location-report"
    "better-image-sizes"
    "optimize-more"
    "wp-db-booster"
    "bp-distance-search"
    "opensearchserver-search"
    "lh-dashboard-notes"
    "absolutte-blocks"
    "simple-ajax-insert-comments-lite"
    "yepty"
    "ultimate-bar"
    "pushly"
    "responsive-video-embed"
    "workbox-google-analytics"
    "wordpress-ads-plug-in"
    "codepen-embed-block"
    "catfolders-document-gallery"
    "speed-up-translation"
    "tag-cloud-canvas"
    "simple-ticker"
    "seopress-for-mainwp"
    "amcaptcha"
    "wp-markkeyword"
    "genesis-connect-edd"
    "youcan-pay-for-woocommerce"
    "shopmagic-for-google-sheets"
    "auto-subpage-menu"
    "internal-link-shortcode"
    "pdf-creator-lite"
    "picturefillwp"
    "pal-for-contact-form"
    "jigoshop-exporter"
    "rest-gutenberg"
    "embed-extended"
    "woo-schedule-stock-manager"
    "dashi"
    "ibegin-share"
    "reservas-online"
    "fusion-extension-video"
    "azurecurve-tag-cloud"
    "simple-tabs"
    "hide-n-disable-comment-url-field"
    "formularios-de-contacto-salesup"
    "product-expiry-for-woocommerce"
    "ai-copilot"
    "broadcast-companion"
    "global-s-h-bxslider"
    "review-disclaimer"
    "wp-pluginsthemes-auto-update"
    "post-views-summary"
    "feedflare"
    "list-category"
    "scss-library"
    "feeds-of-twitter"
    "real-wp-shop-lite"
    "templategalaxy"
    "eazy-xmlrpc-pingback-disable"
    "frontend-admin-menu"
    "integrity-checker"
    "poppop"
    "reference-knowledgebase-and-docs"
    "rest-xmlrpc-data-checker"
    "vereinonline"
    "cache-buster"
    "page-section-for-themereviewer"
    "pingcrawl"
    "shortcodes-for-amp-web-stories-and-elementor-widget"
    "woocommerce-payment-gateway-ccbill"
)

# Define user agents with weights
declare -A USER_AGENTS
USER_AGENTS=(
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"]=5
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"]=7
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"]=6
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36 Edg/91.0.864.54"]=5
    ["Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 OPR/77.0.4054.277"]=3
    ["Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (iPad; CPU OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Vivaldi/4.0"]=1
    ["Mozilla/5.0 (Android 11; Mobile; rv:68.0) Gecko/68.0 Firefox/88.0"]=1
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"]=15
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/534.36"]=12
)

CLOSED_PLUGINS_FILE="${WORDPRESS_WORKDIR}/closed_plugins.txt"
LAST_VERSION_FILE="${WORDPRESS_WORKDIR}/last_versions.txt"
PARALLEL_JOBS=1

DOWNLOAD_ALL_PLUGINS='n'
LIST_ONLY='n'
ALL_PLUGINS_FILE="${WORDPRESS_WORKDIR}/wp-plugin-svn-list.txt"

DELAY_DOWNLOADS='n'
DELAY_DURATION=5

FORCE_UPDATE='n'
CACHE_ONLY='n'

mkdir -p "$WORDPRESS_WORKDIR" "$MIRROR_DIR" "$LOGS_DIR"
DEBUG_MODE=0

while getopts "p:dalD:t:fc" opt; do
    case ${opt} in
        p ) PARALLEL_JOBS=$OPTARG ;;
        d ) DEBUG_MODE=1 ;;
        a ) DOWNLOAD_ALL_PLUGINS='y' ;;
        l ) LIST_ONLY='y' ;;
        D ) DELAY_DOWNLOADS=$OPTARG ;;
        t ) DELAY_DURATION=$OPTARG ;;
        f ) FORCE_UPDATE='y' ;;
        c ) CACHE_ONLY='y' ;;    # New option for cache-only
        \? ) echo "Usage: $0 [-p PARALLEL_JOBS] [-d] [-a] [-l] [-D DELAY_DOWNLOADS] [-t DELAY_DURATION] [-f] [-c]" 1>&2; exit 1 ;;
    esac
done

debug_log() {
    if [ "$DEBUG_MODE" -eq 1 ]; then
        echo "[DEBUG] $1" >&2
    fi
}

get_random_user_agent() {
    echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
}

get_latest_version_and_download_link() {
    local plugin=$1
    debug_log "Checking latest version and download link for $plugin"
    
    local api_url="https://api.wordpress.org/plugins/info/1.0/${plugin}.json"
    local user_agent=$(get_random_user_agent)
    local api_response=$(curl -s -H "User-Agent: $user_agent" "$api_url")
    
    if echo "$api_response" | jq -e '.error' >/dev/null; then
        local error_message=$(echo "$api_response" | jq -r '.error')
        if [ "$error_message" = "closed" ]; then
            echo "closed"
            return 2
        else
        echo "Error: $error_message for plugin $plugin" >&2
        return 1
        fi
    fi
    
    local version=$(echo "$api_response" | jq -r '.version // empty')
    local download_link=$(echo "$api_response" | jq -r '.download_link // empty')
    
    if [ -n "$version" ] && [ -n "$download_link" ]; then
        echo "$version $download_link"
        return 0
    else
        echo "Error: Cannot fetch version or download link for $plugin" >&2
        return 1
    fi
}

download_plugin() {
    local plugin=$1
    local version=$2
    local api_download_link=$3
    local output_file="${MIRROR_DIR}/${plugin}.${version}.zip"
    local header_file="${LOGS_DIR}/${plugin}.${version}.headers"
    local constructed_download_link="${DOWNLOAD_BASE_URL}/${plugin}.${version}.zip"
    local download_link

    if [ "$DEBUG_MODE" -eq 1 ]; then
        debug_log "API-provided download link for $plugin: $api_download_link"
        debug_log "Constructed download link for $plugin: $constructed_download_link"
    fi

    if [ "$DOWNLOAD_LINK_API" == 'y' ] && [ -n "$api_download_link" ]; then
        download_link="$api_download_link"
        debug_log "Using API-provided download link for $plugin: $download_link"
    else
        download_link="$constructed_download_link"
        debug_log "Using constructed download link for $plugin: $download_link"
    fi

    debug_log "Downloading $plugin version $version through Cloudflare Worker"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)
    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o /dev/null "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    else
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o "$output_file" "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    fi

    if [ $? -eq 0 ]; then
        if [ "$CACHE_ONLY" == 'y' ]; then
            debug_log "Plugin $plugin version $version cached successfully."
            return 0
        fi

        local file_size=$(stat -c%s "$output_file")
        if [ "$file_size" -lt 1000 ]; then
            echo "Error: Downloaded file for $plugin is too small (${file_size} bytes). Possible download issue." >&2
            return 1
        fi

        local source=$(grep -i "X-Source:" "$header_file" | cut -d' ' -f2 | tr -d '\r')
        if [ "$source" == "R2" ]; then
            debug_log "Successfully downloaded $plugin version $version from R2 storage"
        elif [ "$source" == "WordPress" ]; then
            debug_log "Successfully downloaded $plugin version $version from WordPress"
            debug_log "R2 bucket saving for plugin zip occurred"
        else
            debug_log "Skipped download for $plugin $version zip (already exists locally)"
        fi

        return 0
    else
        echo "Error: Failed to download $plugin version $version" >&2
        return 1
    fi
}

save_plugin_info() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.json"

    debug_log "Saving plugin json metadata for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying metadata download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    if [ "$CACHE_ONLY" == 'y' ]; then
        # When in cache-only mode, output to /dev/null
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin metadata for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache json metadata for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            if [ "$source" = "R2" ]; then
                debug_log "json metadata for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "json metadata for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin json occurred"
            else
                debug_log "json metadata for $plugin version $version saved (json metadata file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save json metadata for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

fetch_and_save_checksums() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.checksums.json"

    debug_log "Fetching and saving checksums for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying checksums download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    debug_log "Sending request to Worker for checksums: CF_WORKER_URL?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"

    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin checksums for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache checksums for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        debug_log "Received response with status code: $status_code"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            debug_log "Response source: $source"
            if [ "$source" = "R2" ]; then
                debug_log "Checksums for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "Checksums for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin checksums occurred"
            else
                debug_log "Checksums for $plugin version $version saved (checksums file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save checksums for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

process_plugin() {
    local plugin=$1

    # Check if the plugin is already known to be closed
    if grep -q "^$plugin$" "$CLOSED_PLUGINS_FILE" 2>/dev/null; then
        echo "Plugin $plugin is known to be closed. Skipping."
        return 0
    fi

    echo "Processing plugin: $plugin"

    VERSION_AND_LINK=$(get_latest_version_and_download_link "$plugin")
    local version_check_status=$?
    
    if [ $version_check_status -eq 1 ]; then
        echo "Skipping $plugin due to version fetch error."
        return 1
    elif [ $version_check_status -eq 2 ]; then
        echo "Plugin $plugin is closed. Skipping download and processing."
        echo "$plugin" >> "$CLOSED_PLUGINS_FILE"
        if save_plugin_info "$plugin" "closed"; then
            debug_log "Successfully saved json metadata for closed plugin $plugin."
        else
            debug_log "Failed to save json metadata for closed plugin $plugin."
        fi
        return 0
    fi
    
    LATEST_VERSION=$(echo "$VERSION_AND_LINK" | cut -d' ' -f1)
    API_DOWNLOAD_LINK=$(echo "$VERSION_AND_LINK" | cut -d' ' -f2-)

    debug_log "Latest version for $plugin: $LATEST_VERSION"
    debug_log "API download link for $plugin: $API_DOWNLOAD_LINK"

    STORED_VERSION=$(grep "^$plugin" "$LAST_VERSION_FILE" | awk '{print $2}')
    debug_log "Stored version for $plugin: $STORED_VERSION"

    if [ "$CACHE_ONLY" != 'y' ] && [ "$LATEST_VERSION" == "$STORED_VERSION" ] && [ -f "${MIRROR_DIR}/${plugin}.${LATEST_VERSION}.zip" ]; then
        echo "$plugin is up-to-date and exists in mirror directory. Skipping download..."
    else
        start_time=$(date +%s.%N)

        if download_plugin "$plugin" "$LATEST_VERSION" "$API_DOWNLOAD_LINK"; then
            if [ "$CACHE_ONLY" != 'y' ]; then
                sed -i "/^$plugin/d" "$LAST_VERSION_FILE"
                echo "$plugin $LATEST_VERSION" >> "$LAST_VERSION_FILE"
            fi
            echo "Successfully processed $plugin."
        else
            echo "Error: Failed to process $plugin." >&2
        fi

        end_time=$(date +%s.%N)
        duration=$(echo "$end_time - $start_time" | bc)
        printf "Time taken for %s: %.4f seconds\n" "$plugin" "$duration"
    fi

    if save_plugin_info "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully saved json metadata for $plugin."
    else
        debug_log "Failed to save json metadata for $plugin."
    fi

    if fetch_and_save_checksums "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully fetched and saved checksums for $plugin."
    else
        debug_log "Failed to fetch and save checksums for $plugin."
    fi
}

populate_all_plugins() {
    if [ ! -f "$ALL_PLUGINS_FILE" ] || [ "$LIST_ONLY" == 'y' ]; then
        echo "Fetching list of all WordPress plugins..."
        svn list https://plugins.svn.wordpress.org/ | sed 's/\/$//g' > "$ALL_PLUGINS_FILE"
        plugin_count=$(wc -l < "$ALL_PLUGINS_FILE")
        echo "Plugin list (${plugin_count}) saved to $ALL_PLUGINS_FILE"
    fi
    
    if [ "$LIST_ONLY" == 'n' ]; then
        ALL_PLUGINS=()
        while IFS= read -r line; do
            ALL_PLUGINS+=("$line")
        done < "$ALL_PLUGINS_FILE"
        echo "Loaded ${#ALL_PLUGINS[@]} plugins."
    fi
}

if [ "$LIST_ONLY" == 'y' ]; then
    populate_all_plugins
    echo "Plugin list created. Exiting without downloading."
    exit 0
fi

if [ "$DOWNLOAD_ALL_PLUGINS" == 'y' ]; then
    populate_all_plugins
    COMBINED_PLUGINS=("${ALL_PLUGINS[@]}")
else
    if [ ! -d "$PLUGIN_DIR" ]; then
        echo "Warning: Plugin directory $PLUGIN_DIR does not exist or is invalid."
        PLUGIN_LIST=()
    else
        PLUGIN_LIST=($(ls -d "$PLUGIN_DIR"/*/ 2>/dev/null | xargs -n 1 basename))

        if [ ${#PLUGIN_LIST[@]} -eq 0 ]; then
            echo "No plugins found in $PLUGIN_DIR."
        fi
    fi

    COMBINED_PLUGINS=(${PLUGIN_LIST[@]} ${ADDITIONAL_PLUGINS[@]})
    COMBINED_PLUGINS=($(echo "${COMBINED_PLUGINS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
fi

if [ ${#COMBINED_PLUGINS[@]} -eq 0 ]; then
    echo "No plugins to download. Exiting."
    exit 0
fi

mkdir -p "$MIRROR_DIR"
touch "$LAST_VERSION_FILE"

if [ "$PARALLEL_JOBS" -gt 1 ]; then
    echo "Running in parallel with $PARALLEL_JOBS jobs..."
    # First, export all variables including USER_AGENTS
    export DOWNLOAD_BASE_URL MIRROR_DIR LAST_VERSION_FILE DEBUG_MODE DOWNLOAD_LINK_API LOGS_DIR ALL_PLUGINS_FILE DOWNLOAD_ALL_PLUGINS LIST_ONLY CF_WORKER_URL DELAY_DOWNLOADS DELAY_DURATION FORCE_UPDATE CACHE_ONLY USER_AGENTS

    # Then, export the functions
    export -f process_plugin get_latest_version_and_download_link download_plugin debug_log populate_all_plugins save_plugin_info get_random_user_agent fetch_and_save_checksums
    printf "%s\n" "${COMBINED_PLUGINS[@]}" | xargs -P $PARALLEL_JOBS -I {} bash -c 'process_plugin "$@"' _ {}
else
    for plugin in "${COMBINED_PLUGINS[@]}"; do
        process_plugin "$plugin"
    done
fi

if [ -f "$CLOSED_PLUGINS_FILE" ]; then
    echo
    echo "Closed Plugin List:"
    cat "$CLOSED_PLUGINS_FILE" | sort | uniq || true
    echo
    echo "Total closed plugins: $(wc -l < "$CLOSED_PLUGINS_FILE")"
    echo
else
    echo
    echo "No closed plugins found."
    echo
fi
echo "Plugin download process completed."
