#!/bin/bash

# Base directory (script location)
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Configurable directories
WORDPRESS_WORKDIR="${WORDPRESS_WORKDIR:-$BASE_DIR/wordpress-plugins}"
PLUGIN_DIR="${PLUGIN_DIR:-$BASE_DIR/wp-content/plugins}"
MIRROR_DIR="${MIRROR_DIR:-$BASE_DIR/mirror}"
LOGS_DIR="${LOGS_DIR:-$BASE_DIR/plugin-logs}"

# Check for CF_WORKER_URL environment variable
if [ -z "$CF_WORKER_URL" ]; then
    echo "Error: CF_WORKER_URL environment variable is not set." >&2
    exit 1
fi

DOWNLOAD_BASE_URL="https://downloads.wordpress.org/plugin"

# Other variables
DOWNLOAD_LINK_API='y'

ADDITIONAL_PLUGINS=(
    "visual-text-editor"
    "select-all-categories-and-taxonomies-change-checkbox-to-radio-buttons"
    "genesis-printstyle-plus"
    "wp-player"
    "simple-back-to-top"
    "filesfm-file-upload-form"
    "clickbank-niche-storefronts"
    "wp-travel-blocks"
    "tw-pagination"
    "live-scores-for-sportspress"
    "hide-broken-shortcodes"
    "shortcode-ui-richtext"
    "safe-report-comments"
    "hrecipe"
    "better-random-redirect"
    "custom-checkout-fields-for-woocommerce"
    "orillacart"
    "wisdm-reports-for-learndash"
    "civicrm-wp-member-sync"
    "events-block-for-the-events-calendar"
    "custom-script-for-customizer"
    "blog-time"
    "wp-importer"
    "stars-rating"
    "smntcs-custom-logo-link"
    "wp-stripe"
    "gosign-background-container"
    "magic-login"
    "ere-recently-viewed"
    "mailster-contact-form-7"
    "wprequal"
    "zen-menu-logic"
    "quadmenu-oceanwp"
    "debug-bar-remote-requests"
    "woo-show-stock"
    "dd-simplest-maintenance-mode"
    "wecantrack"
    "emergency-password-reset"
    "pastacode"
    "wf-magnific-lightbox"
    "trackfree-woocommerce-tracking"
    "indieauth"
    "slideshow-se"
    "manage-privacy-options"
    "simple-blog-card"
    "wp-newsticker"
    "timetics"
    "online-accessibility"
    "lava-ajax-search"
    "widgets-for-thumbtack-reviews"
    "integrate-firebase"
    "buddypress-simple-events"
    "which-template"
    "mtphr-widgets"
    "animated-text-block"
    "ip2location-tags"
    "woo-cancel-abandoned-order"
    "easy-testimonial-rotator"
    "wp-database-cleaner"
    "wp-font-resizer"
    "widget-icon"
    "appexperts"
    "affiliatewp-order-details-for-affiliates"
    "html-contact-form"
    "shortcode-empty-paragraph-fix"
    "editor-block-outline"
    "block-referer-spam"
    "go-redirects"
    "digiwidgets-image-editor"
    "conditional-fields-for-elementor-form"
    "expand-divi"
    "ajax-comments"
    "goal-tracker-ga"
    "viperbar"
    "postmash-custom"
    "gm-woocommerce-quote-popup"
    "nelio-featured-posts"
    "change-last-modified-date"
    "lowermedia-sticky-js-menus"
    "chamber-dashboard-member-manager"
    "woo-m-pesa-payment-gateway"
    "fidgetr"
    "tawkto-manager"
    "custom-author-byline"
    "mad-mimi"
    "easy-noindex-and-nofollow"
    "exactly-gdpr-google-maps"
    "super-static-cache"
    "forminix"
    "just-writing"
    "accessibility-toolbar"
    "smart-app-banner"
    "social-feed-block"
    "crouton"
    "filter-for-divi"
    "products-per-page-for-woocommerce"
    "amikelive-adsense-widget"
    "netopia-payments-payment-gateway"
    "wpsimpletools-disable-comments"
    "acf-tablepress"
    "restrict-usernames"
    "woo-free-product-sample"
    "world-clock-widget"
    "quadmenu-astra"
    "webemailprotector"
    "auto-cloudinary"
    "custom-post-type-list-shortcode"
    "qrcode-wprhe"
    "skt-blocks"
    "webpay-woocommerce-plugin"
    "cb-parallax"
    "code-manager"
    "carousels-slider-for-divi"
    "random-redirect"
    "schema-default-image"
    "ssquiz"
    "booking-and-rental-manager-for-woocommerce"
    "github-embed"
    "nextgen-resize"
    "woozap"
    "simple-adblock-notice"
    "auto-disable-editor"
    "accordion-slider"
    "custom-content-width"
    "social-engine"
    "rightmessage"
    "phpinfo-wp"
    "recurring-donation"
    "import-meetup-events"
    "database-for-cf7"
    "blackbar"
    "quotmarks-replacer"
    "clear-floats-button"
    "service-boxs"
    "analytics-head"
    "mass-users-password-reset"
    "database-toolset"
    "boatdealer"
    "buddypress-easy-albums-photos-video-and-music-next-gen"
    "sendpulse-email-marketing-newsletter"
    "woo-custom-gateway"
    "wp-snap"
    "members-role-hierarchy"
    "wp-sentinel"
    "opal-service"
    "woo-picpay"
    "absolute-relative-urls"
    "categorify"
    "rebusted"
    "ttv-easy-embed-player"
    "material-admin-theme"
    "wordpress-admin-bar-improved"
    "form-forms"
    "super-transition-slideshow"
    "syntax-highlighter-compress"
    "kangu"
    "simple-gdpr-cookie-compliance"
    "easy-populate-posts"
    "lock-my-bp"
    "bbpress-new-ui"
    "productsize-chart-for-woocommerce"
    "library-bookshelves"
    "super-web-share"
    "secure-db-connection"
    "magical-blocks"
    "svg-block"
    "nice-navigation"
    "jotform-feedback-button"
    "youtube-videos-widget"
    "grid-list-toggle-for-woocommerce"
    "mailster-google-analytics"
    "wp-cron-http-auth"
    "pmpro-payfast"
    "sniplets"
    "most-read-posts-in-xx-days"
    "orangebox"
    "wp-basic-authentication"
    "wp-healthcheck"
    "affiliateimporteral"
    "payment-gateways-by-user-roles-for-woocommerce"
    "old-core-files"
    "all-in-menu"
    "paged-comments"
    "sky-elementor-addons"
    "exchange-rates-widget"
    "ucenter-integration"
    "floating-adsense-bar"
    "my-movie-database"
    "acf-recent-posts-widget"
    "mine-cloudvod"
    "simpleshop-cz"
    "thumbnail-editor"
    "featured-posts-slideshow"
    "quran-text-multilanguage"
    "playwire"
    "gmo-font-agent"
    "user-permissions"
    "wp-pgp-encrypted-emails"
    "export-media-urls"
    "coupon-pop-for-wp"
    "wp-forum-latest-posts"
    "wp-mobile-themes"
    "ce-corona"
    "login-with-vipps"
    "product-pre-orders-for-woo"
    "hide-jetpack-promotions"
    "bwp-external-links"
    "cryptocurrency-payment-gateway"
    "newsboard"
    "gravity-fieldset-for-gravity-forms"
    "wp-dispensary"
    "localize"
    "yaad-sarig-payment-gateway-for-wc"
    "wp-real-estate-property-listing-crm"
    "widget-youtube-subscribtion"
    "bbp-messages"
    "real-estate"
    "quran-radio"
    "random-featured-post-plugin"
    "wc-zelle"
    "ninja-forms-layout"
    "wooms"
    "fv-code-highlighter"
    "latest-news-widget"
    "wp-post-template"
    "acf-admin-flexible-content-collapse"
    "buddypress-friends-on-line"
    "disable-revisions"
    "cbach-wp-gridster"
    "z-inventory-manager"
    "wp-autotags"
    "wp-tabular"
    "wplike2get"
    "simple-feed-copyright"
    "humanstxt"
    "wp-simple-html-sitemap"
    "sm-gallery"
    "civist"
    "product-countdown-for-woocommerce"
    "pandavideo"
    "genesis-post-teasers"
    "uber-media"
    "syndicate-out"
    "themedy-toolbox"
    "wider-admin-menu"
    "albacross"
    "bp-poke"
    "eu-cookie-law-compliance"
    "gravitywp-count"
    "file-changes-monitor"
    "wysiwyg"
    "content-management-system-dashboard"
    "advanced-custom-post-search"
    "exif-caption"
    "checkout-paypal-woo"
    "wpd-bb-additions"
    "content-anchor-links"
    "mailchimp-for-formcraft"
    "tatum"
    "openpay-stores"
    "gutena-tabs"
    "wp-migrate-2-aws"
    "api-bearer-auth"
    "qq-kefu"
    "woo-payment-on-delivery"
    "wp-call-me-back"
    "responsive-owl-carousel-elementor"
    "ever-compare"
    "gosign-contact-person-box-block"
    "ays-random-posts-and-pages"
    "nm-gift-registry-and-wishlist-lite"
    "woobuilder"
    "melipayamak"
    "export-categories"
    "woo-clover-gateway-by-zaytech"
    "bp-custom-menu"
    "enteraddons"
    "wpcodefactory-helper"
    "auto-copyright-1"
    "institute-management"
    "custom-post-type-archives"
    "cryptocurrency-product-for-woocommerce"
    "preloader-awesome"
    "vibe-seo-pack"
    "simple-no-comments"
    "term-menu-order"
    "ninja-mail"
    "order-tip-woo"
    "better-stop-adblock"
    "echbay-phonering-alo"
    "weixin-robot"
    "course-booking-system"
    "google-font-fix"
    "pojo-builder-animation"
    "wpc-product-videos"
    "wpms-sidebar-login-widget"
    "bulk-watermark"
    "joemobi"
    "ultraaddons-elementor-lite"
    "acf-flexible-content-extended"
    "persian-date"
    "kargo-takip-turkiye"
    "wp-e-commerce-custom-fields"
    "menu-buttons"
    "nextgen-gallery-geo"
    "enable-vcard-upload"
    "html-wp"
    "virusdie"
    "digital-signature-contact-form-7-addon"
    "recent-post-thumbnail-slider-widget"
    "wp-ever-accounting"
    "gettext-override-translations"
    "woocommerce-domination"
    "woo-accordions"
    "live-composer-lite"
    "radcontrol"
    "client-portal-suitedash-login"
    "ai-wp-writer"
    "vdocipher"
    "advanced-sermons"
    "woo-payzen-payment"
    "wpwatermark"
    "dofollow-case-by-case"
    "protected-video"
    "dokan-menu-hider"
    "required-taxonomies"
    "stock-exporter-for-woocommerce"
    "rate"
    "ultimate-blocks-for-gutenberg"
    "wp-user-switch"
    "design"
    "genealogical-tree"
    "category-wise-search"
    "current-menu-item-for-custom-post-types"
    "redirect-by-custom-field"
    "omnipress"
    "rs-event-multiday"
    "broken-links-remover"
    "basic-interactive-world-map"
    "fast-category-cloud-wordpress-plugin"
    "hivepress-authentication"
    "vkontakte"
    "nurelm-get-posts"
    "easy-image-display"
    "bbpressmoderation"
    "custom-taxonomy-sort"
    "aweos-google-maps-iframe-load-per-click"
    "flexible-recent-posts"
    "smtp-yandex-mail-server"
    "seo-blogger-to-wordpress-301-redirector"
    "vertical-scroll-recent-registered-user"
    "marquee-xml-rss-feed-scroll"
    "drop-caps"
    "wpmathpub"
    "custom-color-palette"
    "woo-for-logged-users"
    "simple-database-repair"
    "force-reinstall"
    "edd-hide-download"
    "blog-posts-and-category-for-elementor"
    "wp-story"
    "quantities-and-units-for-woocommerce"
    "powerpack-for-learndash"
    "custom-post-type-auto-menu"
    "checkout-manager-for-woocommerce"
    "advanced-search-widget"
    "announce-from-the-dashboard"
    "tinymce-thumbnail-gallery"
    "featured-image-plus"
    "jm-breaking-news"
    "eu-cookie-law-consent"
    "wp-school-calendar-lite"
    "fast-clickfunnels"
    "wpdr-simple-downloads"
    "html5-slideshow-presentations"
    "postlists"
    "tantan-spam"
    "demo-awesome"
    "color-or-image-variation-swatches-for-woocommerce"
    "webfish-dropdown-menu"
    "t-countdown"
    "sample-data"
    "dokan-invoice"
    "lava-bp-post"
    "documentation"
    "ozh-click-counter"
    "sr-product-360o-view"
    "pro-categories-widget"
    "import-external-attachments"
    "headless-mode"
    "wenprise-alipay-checkout-for-woocommerce"
    "jp-students-result-management-system"
    "author-chat"
    "definitive-addons-for-elementor"
    "waymark"
    "wp-export-categories-taxonomies"
    "show-support-ribbon"
    "my-youtube-playlist"
    "platycorp-etsy-syncer"
    "slick-sitemap"
    "simple-slug-translate"
    "myshouts-shoutbox"
    "super-simple-slider"
    "comment-moderation-e-mail-to-post-author"
    "kiotvietsync"
    "admin-category-search"
    "woo-product-showcase"
    "wc-order-limit-lite"
    "pagopar-woocommerce-gateway"
    "five-star-ratings-shortcode"
    "translator"
    "block-for-font-awesome"
    "yaypricing"
    "manageable"
    "kalender-digital"
    "role-and-customer-based-pricing-for-woocommerce"
    "anonymous-restricted-content"
    "author-images"
    "blueimp-lightbox"
    "youtube-channel-showcase"
    "leira-letter-avatar"
    "wp-meta-keywords-meta-description"
    "picture-gallery"
    "theme-junkie-team-content"
    "viral-coming-soon"
    "password-bcrypt"
    "molongui-bump-offer"
    "wp-authenticity-checker-wac"
    "simple-social-sharing-widgets-icons-updated"
    "cbnet-twitter-widget"
    "widget-or-sidebar-per-shortcode"
    "payment-form-for-paypal-pro"
    "autopost-to-mastodon"
    "clover-payments-for-woocommerce"
    "catfolders"
    "wc-confirm-payment"
    "gravity-forms-multiple-form-instances"
    "book-a-place"
    "ultimate-modal"
    "clearout-email-validator"
    "woocommerce-moip"
    "feed-template-customize"
    "wp-countup-js"
    "simple-automatic-updates"
    "rest-api-helper"
    "buddymobile"
    "adkingpro"
    "opcache-manager"
    "bloom-for-publishers"
    "wp-basic-elements"
    "tc-portfolio"
    "wordpress-login-redirect"
    "bp-job-manager"
    "nooz"
    "getyourguide-widget"
    "no-image-link"
    "hide-categories"
    "wp-oauth"
    "mygeopositioncom-geotags-geometatags"
    "autoshare-for-twitter"
    "rps-include-content"
    "premmerce-woocommerce-wishlist"
    "sticky-add-to-cart-for-woocommerce"
    "estonian-shipping-methods-for-woocommerce"
    "wp-aparat"
    "loop-post-navigation-links"
    "jcarousel-post-slider"
    "wp-upload-restriction"
    "document-library-lite"
    "wp-change-email-sender"
    "wp-columnize"
    "firebase-authentication"
    "post-views-for-jetpack"
    "advanced-sitemap-generator"
    "bulk-image-resizer"
    "custom-widget-area"
    "allow-php-execute"
    "database-collation-fix"
    "nudgify"
    "themeforest-check"
    "user-access-shortcodes"
    "recras"
    "call-to-action-block-wppool"
    "7feeds-news-ticker"
    "wp-post-real-time-statistics"
    "wpadcenter"
    "flip-cards-module-divi"
    "bbpress-genesis-extend"
    "olalaweb-mailchimp-campaign-manager"
    "extended-post-status"
    "full-background"
    "vf-expansion"
    "wp-reroute-email"
    "user-files"
    "grid-shortcodes"
    "mycred-learndash"
    "tabulate"
    "relative-image-urls"
    "export-post-info"
    "bootstrap"
    "storyform"
    "maintenance-coming-soon-redirect-animation"
    "spam-free"
    "paypal-express-checkout"
    "easy-marijuana-age-verify"
    "image-carousel-divi"
    "tutor-lms-migration-tool"
    "comment-validation"
    "cecabank-woocommerce"
    "mavis-https-to-http-redirect"
    "media-grid"
    "wt-geotargeting"
    "paystack-gateway-paid-memberships-pro"
    "simple-footnotes"
    "front-end-users"
    "wp-sheet-editor-yoast-seo"
    "wp-hide-categories"
    "app-store-assistant"
    "linkpizza-manager"
    "fonts-add"
    "chatbot-com-ai-platform"
    "ultimate-custom-cursor"
    "listify-xml-csv-listings-import"
    "import-spreadsheets-from-microsoft-excel"
    "wpc-price-by-quantity"
    "print-science-designer"
    "ultimate-popup-creator"
    "simple-testimonials"
    "gravatar-favicon"
    "indent-lists-button"
    "automated-keywords-generator"
    "foxtool"
    "ultimate-member-wp-user-frontend-addon"
    "email-tracker"
    "plethora-tabs-accordions"
    "syncee-global-dropshipping"
    "woo-billing-with-invoicexpress"
    "callbell-chat-widget"
    "sitemap-with-woocommerce"
    "wp-sifr"
    "wp-whos-online"
    "payflex-payment-gateway"
    "chl-change-html-lang"
    "panda-pods-repeater-field"
    "nomiddleman-crypto-payments-for-woocommerce"
    "menus"
    "edit-custom-fields"
    "banner-garden"
    "easy-pinterest"
    "simple-catalog-for-woocommerce"
    "wp-bootstrap-carousel"
    "rss-featured-image"
    "safreen-widgets"
    "speakpipe-voicemail-for-websites"
    "photo-express-for-google"
    "slingblocks"
    "reading-position-indicator"
    "sitesupercharger"
    "rover-idx"
    "wp-mobilizer"
    "contact-form-7-getresponse-extension"
    "optinly"
    "eazy-enable-blogroll"
    "ajax-read-more"
    "mp-share-center"
    "elegant-subscription-popup"
    "vc-design-template-library"
    "leadinfo"
    "songkick-concerts-and-festivals"
    "mixcloud-embed"
    "adsense-for-feeds"
    "proofread-bot"
    "price-table-block"
    "weather-map-widget"
    "pingfm-custom-url-status-updates"
    "eprolo-dropshipping"
    "wa-chatbox-manager"
    "drop-in-image-slideshow-gallery"
    "cbnet-mbp-auto-activate"
    "insert-adsense"
    "custom-post-type-date-archives"
    "add-coupon-by-link-for-woocommerce"
    "bne-gallery-extended"
    "bulk-actions-select-all"
    "multi-column-taxonomy-list"
    "meta"
    "wporlogin"
    "sv-provenexpert"
    "long-url-maker"
    "set-all-first-images-as-featured"
    "wp-pano"
    "cm-video-lesson-manager"
    "wp-mail-options"
    "video-blogster-lite"
    "syntaxhighlighter-tinymce-button"
    "socialize-it"
    "wp-github-sync"
    "category-post-widget"
    "ymm-search"
    "wp-mini-program"
    "mini-ajax-woo-cart"
    "recapture-for-edd"
    "creative-addons-for-elementor"
    "css-for-elementor"
    "resend-welcome-email"
    "lightweight-cookie-notice-free"
    "simple-buddypress-profile-privacy"
    "wp-mailgun-smtp"
    "add-on-gravity-forms-mailpoet"
    "getastra"
    "adunblocker"
    "no-hentry"
    "checkout-upsell-and-order-bumps"
    "unlimited-logo-carousel"
    "advanced-most-recent-posts"
    "include-klaviyo-for-elementor-pro"
    "easy-amazon-product-information"
    "minimum-purchase-amount-for-woo-cart"
    "price-calc"
    "pvb-contact-form-7-calculator"
    "wp-oscommerce"
    "flexible-spacer-block"
    "post-cloner"
    "sensei-post-to-course"
    "smtp-mailing-queue"
    "callback-request"
    "ajax-contact-form"
    "twitter-cards"
    "zoom-magnifier-for-woocommerce"
    "feed-json"
    "privy-crm-integration"
    "tako-movable-comments"
    "wpcomplete"
    "uptime-robot-monitor"
    "push-monkey-desktop-push-notifications"
    "gsheetconnector-ninja-forms"
    "code-markup"
    "bp-favorite-notification"
    "vkontakte-share-button"
    "post-lists-view-custom"
    "woo-mini-cart-drawer"
    "better-author-bio"
    "content-blocks-builder"
    "agecheckernet"
    "yandex-pinger"
    "welcome-popup"
    "tz-flickr-widget"
    "wp-notcaptcha"
    "smartslider"
    "pipdig-snapcode-widget"
    "luckywp-cookie-notice-gdpr"
    "store-manager-connector"
    "wp-easy-menu"
    "wp-user-login-notifier"
    "turn-rank-math-faq-block-to-accordion"
    "reverbnation-master"
    "lemmony-companion"
    "last-viewed-posts"
    "archivarix-external-images-importer"
    "wc-pedido-minimo"
    "arconix-portfolio"
    "popunder-popup"
    "ic-besocial"
    "uichemy"
    "custom-wp-login-widget"
    "rss-slider-on-post"
    "tradays-economic-calendar"
    "frontpage-category-filter"
    "gif-animation-preview"
    "manca-lp-wc-integration"
    "sidebar-menu-widget"
    "the-plus-visual-composer-addons"
    "admin-custom-font"
    "awd-weightcountry-shipping"
    "attendance-manager"
    "autoclose"
    "webcam-2way-videochat"
    "elisqlreports"
    "wp-line-notify"
    "papercite"
    "wp-sitemap"
    "shortcode-maker"
    "confetti"
    "countdown-time"
    "mailerlite-featured-image-in-rss-feed"
    "smart-search-for-woocommerce"
    "woo-esto"
    "sharethis-follow-buttons"
    "singsong"
    "gs-books-showcase"
    "ethereumico"
    "fr-custom-payment-gateway-icon-for-woocommerce"
    "wp-hydra"
    "black-studio-homepage-builder"
    "dd-lastviewed"
    "easy-shortcode-buttons"
    "easy-random-quotes"
    "host-header-injection-fix"
    "king-addons"
    "cudazi-scroll-to-top"
    "google-plus-author"
    "buddypress-profile-completion"
    "contact-form-7-response-colorbox-popup"
    "wp-force-lowercase-urls"
    "remove-image-links"
    "remote-images-grabber"
    "sweeppress"
    "woo-cart-count-shortcode"
    "wposs"
    "seed-buddhist-year"
    "wp-hotwords"
    "video-list-manager"
    "category-posts-widget"
    "xmasb-quotes"
    "whitelist-ip-for-limit-login-attempts"
    "pending-submission-notifications"
    "sportspress-tv"
    "doppler-form"
    "wp-smart-flexslider"
    "wp-twitter-button"
    "cleverreach-wc"
    "membees-member-login-widget"
    "wp-flexslider"
    "cm-map-locations"
    "sexy-bookmarks-sidebar-plugin"
    "orbis"
    "organize-media-folder"
    "require-post-category"
    "post-views-stats-counter"
    "bulk-user-management"
    "newsme"
    "bulk-menu-creator"
    "uafrica-shipping"
    "tinymce-visualblocks"
    "woo-billingo-plus"
    "prezi-embedder"
    "affiliatewp-woocommerce-redirect-affiliates"
    "pmpro-zapier"
    "animated-blocks"
    "bcm-duplicate-menu"
    "ere-colors"
    "gt-tabs"
    "image-formatr"
    "404-error-monitor"
    "remove-ip"
    "wpuntexturize"
    "bp-forum-editor"
    "wp-custom-author-url"
    "woo-product-barcode-label-printing"
    "wp-auto-translate-free"
    "publish-date-datepicker"
    "checkbot"
    "transferito"
    "nonprofit-board-management"
    "az-video-and-audio-player-addon-for-elementor"
    "archive-control"
    "featured-videos-for-genesis"
    "google-auto-post"
    "wp-downloadcounter"
    "amp-woocommerce"
    "youlist"
    "webman-templates"
    "wp-force-http"
    "restore-link-title-field"
    "paystack-for-give"
    "wpgraphql-acf"
    "terms-of-service-and-privacy-policy"
    "vertical-marquee-post-title"
    "jvm-rich-text-icons"
    "pdpa-thailand"
    "atlas-content-modeler"
    "user-groups"
    "ts-widget-pack"
    "linkedin-login"
    "logistra-woocommerce-integrasjon-fra-wildrobot-app"
    "fd-payments-for-woo"
    "upi-qr-code-payment-gateway"
    "emulsion-addons"
    "easy-profile-widget"
    "add-custom-page-template"
    "e-namad-shamed-logo-manager"
    "rss-with-images"
    "wow-progress"
    "dokan-wpml"
    "magni-image-flip-for-woocommerce"
    "markdown-editor"
    "getwid-megamenu"
    "wechat-subscribers-lite"
    "wholesale-market"
    "social-video-gallery"
    "support-genix-lite"
    "media-player-addons-for-elementor"
    "simple-google-docs-viewer"
    "javascript-autoloader"
    "two-factor-provider-webauthn"
    "taxonomy-converter"
    "acumbamail-signup-forms"
    "smtp-amazon-ses"
    "simple-directory"
    "jquery-accordion-slideshow"
    "corvuspay-woocommerce-integration"
    "mpress-image-refresh"
    "woocommerce-chilean-peso-currency"
    "sensei-buddypress"
    "social-contact-form"
    "tilda-publishing"
    "coming-soon-for-woocommerce"
    "hypothesis"
    "google-shortlink"
    "wp-updates-settings"
    "lpagery"
    "listings-post-type-enable"
    "category-featured-images"
    "fitness-calculators"
    "tooltip-for-gravity-forms"
    "17fav-bookmark-share"
    "external-login"
    "custom-sidebars-by-proteusthemes"
    "text-expander"
    "pagbank-connect"
    "simple-code-highlighter"
    "pe-easy-slider"
    "recommend-a-friend"
    "maven-member"
    "filr-protection"
    "all-in-one-social-network-buttons"
    "post-by-email"
    "viral-loops-wp-integration"
    "wp-mylinks"
    "wp-easy-contact"
    "motopress-appointment-lite"
    "event-o-matic"
    "cookie-confirm"
    "wp-favicon-remover"
    "no-www"
    "tapfiliate"
    "wp-performance"
    "wp-file-permission-check"
    "wp-cdn-rewrite"
    "expandable-accordion-categories-ultimate-for-woocommerce"
    "woo-dynamic-pricing-discounts-lite"
    "snow"
    "f4-media-taxonomies"
    "my-smtp-wp"
    "media-downloader"
    "edd-downloads-as-services"
    "pmpro-aweber"
    "responsive-slideshow"
    "atomic-reach-audience-engager"
    "fast-index"
    "comment-approved"
    "align-rss-images"
    "shipping-servientrega-woocommerce"
    "yampi-checkout"
    "whatconverts"
    "cf7-google-captcha-load-after-page"
    "discount-and-dynamic-pricing"
    "portfolio-pro"
    "c4d-woo-variation-swatches"
    "wp-simpleweather"
    "blacklist-updater"
    "social-counter"
    "wp-katex"
    "orange-themes-custom-widgets"
    "parallel-loading-system"
    "wp-smart-image-ii"
    "video-posts-webcam-recorder"
    "disable-rss"
    "antispam-for-all-fields"
    "gamipress-link"
    "music-player-for-easy-digital-downloads"
    "quote-master"
    "wp-sticky-menu"
    "role-based-redirect"
    "ckeditor-12"
    "stock-sync-with-google-sheet-for-woocommerce"
    "get-url-cron"
    "wpc-image-widget"
    "99fy-core"
    "social-share-and-social-locker-arsocial"
    "bainternet-posts-creation-limits"
    "share-on-mastodon"
    "image-gallery"
    "email-subscribers-advanced-form"
    "wp-lijit-wijit"
    "buddy-registration-widget"
    "auto-schedule-posts"
    "control-xml-rpc-publishing"
    "buddypress-message-attachment"
    "seo-content-control"
    "ultimate-blogroll"
    "facebook-ogg-meta-tags"
    "olark-for-wp"
    "zarinpal-paid-downloads"
    "leira-roles"
    "external-permalinks-redux"
    "integration-for-contact-form-7-and-pipedrive"
    "number-of-view"
    "connector-gravityforms-mailerlite"
    "advanced-query-loop"
    "statpress-dashboard-widget-lite"
    "gf2pdf"
    "canon-aede"
    "duplicate-pages-posts"
    "cf-images"
    "audio-player-block"
    "woocommerce-thumbnail-input-quantities"
    "webconnex-form-managment"
    "bit-smtp"
    "custom-skins-contact-form-7"
    "alligator-menu-popup"
    "mass-custom-fields-manager"
    "gs-behance-portfolio"
    "iw-magnific-popup"
    "bank-mellat"
    "youtube-sidebar"
    "gradient-button-for-elementor"
    "shipping-nova-poshta-for-woocommerce"
    "mk-slider"
    "smart-blocks"
    "bp-check-in"
    "increase-upload-file-size-maximum-execution-time-limit"
    "invitereferrals-customer-referral-program"
    "elementor-gravity-forms"
    "i3geek-baiduxzh"
    "jj-nextgen-image-list"
    "woocommerce-dropbox"
    "visual-editor-tinymce-buttons"
    "advanced-post-excerpt"
    "dropbox-photo-sideloader"
    "ivycat-ajax-testimonials"
    "wp-emmet"
    "gravity-forms-placeholder-support-add-on"
    "forum-restrict"
    "wpml-flag-in-menu-extended"
    "calendar-archives"
    "maxicharts"
    "svensoft-social-share-buttons"
    "db-backup"
    "easy-query"
    "advanced-twitter-profile-widget"
    "top-ten-lists"
    "media-download"
    "esaudioplayer"
    "cf7-advance-security"
    "internal-linking-of-related-contents"
    "ar-subpages-widget"
    "plugin-activation-status"
    "infinite-uploads"
    "add-pinterest-conversion-tags"
    "upload-media-by-zip"
    "auto-updates"
    "widget-detector-elementor"
    "expandable-row-for-beaver-builder"
    "seo-key"
    "woo-payping-gateway"
    "flexible-refund-and-return-order-for-woocommerce"
    "media-file-sizes"
    "google-authenticator-per-user-prompt"
    "wpcom-migration"
    "attire-blocks"
    "gutena-accordion"
    "wordpress-random-image"
    "smoothness-slider-shortcode"
    "install-profiles"
    "pronamic-client"
    "wp-multi-store-locator"
    "arlo-training-and-event-management-system"
    "expanding-archives"
    "nested-shortcodes"
    "quick-view-and-buy-now-for-woocommerce"
    "forms-signature-formidable-online-contract-automation"
    "hash-form"
    "issuupress"
    "visitor-analytics-io"
    "buddypress-profile-progression"
    "elex-usps-shipping-method"
    "atlas-search"
    "agnosia-bootstrap-carousel"
    "remove-schema"
    "push-notification-for-post-and-buddypress"
    "default-product-image-for-woocommerce"
    "google-transliteration"
    "subdomains"
    "official-add-to-homescreen"
    "pixel-gallery"
    "import-markdown"
    "mojo-under-construction"
    "ppm-carousel"
    "custom-write-panel"
    "wp-cycle-text-announcement"
    "wpc-estimated-delivery-date"
    "assetsminify"
    "best-restaurant-menu-by-pricelisto"
    "the-feedback-company"
    "right-click-disable-or-ban"
    "hezarfen-for-woocommerce"
    "plugins-speed-test"
    "parallax-slider-block"
    "wc-partial-shipment"
    "recent-comments-with-avatars"
    "playerjs"
    "news-widget"
    "paybox-woocommerce-gateway"
    "sozlesmeler"
    "eventpress"
    "simpleform"
    "custom-currency-for-woocommerce"
    "samesite"
    "contact-form-block"
    "really-simple-popup"
    "wplook-twitter-follow-button-new"
    "wp-front-end-profile"
    "cart-recovery"
    "allow-swf-upload"
    "product-notes-for-woocommerce"
    "friends-link-widget"
    "fmtc-affiliate-disclosure"
    "add-polylang-support-for-customizer"
    "tsp-featured-posts"
    "wpextended"
    "sf-author-url-control"
    "rendez-vous"
    "soundcloud-sound-competition"
    "manual-control"
    "wp-archives"
    "emu2-email-users-2"
    "rest-routes"
    "templatic-categoryicons"
    "hostel"
    "pixelines-email-protector"
    "restrict-media-library-access"
    "turn-off-comments"
    "add-customer-for-woocommerce"
    "woo-country-restrictions-advanced"
    "wpsso-user-locale"
    "hm-multiple-roles"
    "show-ip-address"
    "constructor-for-siteorigin"
    "fakturo"
    "wpc-share-cart"
    "litcommerce"
    "zanto"
    "woo-product-multi-layout"
    "cf7-submission-id"
    "collapsible-archive-widget"
    "shrinktheweb-website-preview-plugin"
    "easy-accordion-block"
    "kama-wp-smile"
    "daext-interlinks-manager"
    "sv-tracking-manager"
    "ttv-easy-embed-wall"
    "replace-text"
    "custom-url-to-featured-image"
    "yd-feedwordpress-content-filter"
    "writesonic"
    "simple-access-control"
    "animate-slider"
    "nirweb-support"
    "rio-video-gallery"
    "drip"
    "gf-edit-entries"
    "imoje"
    "whistles"
    "blackbox-debug-bar"
    "refersion-for-woocommerce"
    "redirect-to-login-if-not-logged-in"
    "news-ticker-widget-for-elementor"
    "elex-woo-flexible-pricing"
    "cryptapi-payment-gateway-for-woocommerce"
    "print-me"
    "now-in-store-catalog-builder"
    "wpqiniu"
    "wc-qr-codes"
    "mini-slides"
    "wdv-about-me-widget"
    "ukr-to-lat"
    "aweber-footer-slideup"
    "portfolio-designer-lite"
    "inspiry-stripe-payments"
    "woo-sticky-product-bar"
    "wp-mapit"
    "mobile-dj-manager"
    "wp-mailing-group"
    "google-news-editors-picks-news-feeds"
    "cat-tag-filter-widget"
    "multi-image-metabox"
    "all-related-posts"
    "text-selection-color"
    "gutenverse-form"
    "fast-ebay-listings"
    "unlimited-background-slider"
    "memberlite-shortcodes"
    "quote-of-the-day-by-brainyquote"
    "wp-project"
    "vitepos-lite"
    "computer-repair-shop"
    "members-only-menu-plugin"
    "easy-utm-tracking-with-contact-form-7"
    "full-utf-8"
    "custom-field-finder"
    "auto-tag-generator"
    "acme-divi-modules"
    "woo-superb-slideshow-transition-gallery-with-random-effect"
    "smartlib-tools"
    "mrw-web-design-simple-tinymce"
    "advanced-custom-fields-google-map-extended"
    "zapper-payments"
    "wp-safe-mode"
    "jarvis"
    "my-loginlogout"
    "woocom-securepay-payment-gateway"
    "cryptex"
    "ninja-announcements"
    "woocommerce-gift-coupon"
    "creative-clans-embed-script"
    "global-payments-woocommerce"
    "super-emoji-plus"
    "developry-google-fonts"
    "bluetrait-event-viewer"
    "cloudflare-page-cache"
    "chat-help"
    "ask-me-anything-anonymously"
    "candy-social-widget"
    "seur"
    "kintone-form"
    "link-juice-optimizer"
    "wpreplace"
    "slider-blocks"
    "nofollow-link"
    "bu-navigation"
    "easy-weather-widget"
    "wp-cms"
    "yesno"
    "image-captcha"
    "table-creator"
    "papa-rss-import"
    "more-taxonomies"
    "grooveshark"
    "bbpress-protected-forums"
    "extended-title-remover"
    "wp-referrer-spam-blacklist"
    "wp-pdf-templates"
    "ideapress-json-api"
    "artibot"
    "wp-custom-countdown"
    "premmerce-woocommerce-wholesale-pricing"
    "tt-guest-post-submit"
    "admin-menus-fixed"
    "culqi-full-integration"
    "wpgiftregistry"
    "affiliatewp-checkout-referrals"
    "storefront-blog-excerpt"
    "gatewayapi"
    "wp-post-branches"
    "cgm-event-calendar"
    "smarter-navigation"
    "export-plugin-details"
    "gym-studio-membership-management"
    "author-box-for-divi"
    "pay-in-store-woocommerce-payment-gateway"
    "mas-wp-job-manager-company"
    "admin-bar-login"
    "noindex-pages"
    "codeless-page-builder"
    "video-sidebar-widget"
    "leo-product-recommendations"
    "fraktjakt-shipping-for-woocommerce"
    "meta-description"
    "recapture-for-woocommerce"
    "transdirect-shipping"
    "advanced-posts-blocks"
    "content-bot"
    "mapquest-map-builder"
    "translucent-image-slideshow-gallery"
    "wp-pinterest"
    "gitium"
    "cf7-constant-contact"
    "kades-crypto-widgets"
    "wp-feed-post-thumbnail"
    "follow-us-on-widget"
    "media-hygiene"
    "mailtrap-for-wp"
    "custom-error-pages"
    "wpfomo"
    "portfolio-x"
    "live-stock-prices-for-wordpress"
    "yahoo-weather"
    "mpcx-lightbox"
    "tierra-audio-playlist-manager"
    "simple-cookie-notification-bar"
    "wp-amazon-ads"
    "payment-gateway-via-borgun-for-woocommerce"
    "rsscloud"
    "genesis-featured-image-header"
    "rs-wp-themes-one-click-demo-content"
    "baw-multiple-pass-for-protected-pages"
    "gf-constant-contact"
    "hearthisat"
    "what-template"
    "bon-toolkit"
    "wp-migrate-db-anonymization"
    "book-now"
    "widget-embed-lastest-tweets"
    "photoshelter-gallery-widget"
    "category-template-hierarchy"
    "reorder-by-term"
    "minimum-password-strength"
    "bulk-content-creator"
    "wizscriber-video-scribing-banner-ads"
    "tochat-be"
    "duplicate-widgets"
    "dashboard-to-do-list"
    "baidushare-wp"
    "svgator"
    "password-hash"
    "smartarget-contact-us"
    "disable-responsive-images"
    "fluent-forms-connector-for-mailpoet"
    "wc-easypay-pk"
    "disable-variable-product-price-range-show-only-lowest-price-in-variable-products"
    "cf7-data-source"
    "woocommerce-gateway-affirm"
    "bbpress-bbcode"
    "momoyoga-integration"
    "breadcrumb-navxt-multidimension-extensions"
    "plugin-report"
    "simple-blog-authors-widget"
    "kafkai"
    "user-posts-limit"
    "uws-unyson-woocommerce-shortcodes"
    "ux-flat"
    "bws-google-maps"
    "aria-font"
    "resume-cv"
    "force-update-translations"
    "wp-code-prettify"
    "bot-block-stop-spam-google-analytics-referrals"
    "quick-count"
    "classic-text-widget"
    "zoho-marketinghub"
    "child-theme-check"
    "woowgallery"
    "myticket-events"
    "woocommerce-maintenance-mode"
    "buddypress-xprofile-image-field"
    "help-scout"
    "background-music-menu"
    "buddypress-captcha"
    "paid-memberships-pro-for-wp-courseware"
    "ldap-login-password-and-role-manager"
    "ooyala-video-browser"
    "simple-posts-ticker"
    "easy-media-replace"
    "popping-sidebars-and-widgets-light"
    "pods-seo"
    "event-organiser-csv"
    "simple-google-analytics-tracking"
    "task-scheduler"
    "electric-studio-download-counter"
    "advanced-image-hover-effect-for-elementor"
    "qs-dark-mode"
    "laposta-signup-basic"
    "better-rtl-support"
    "ipushpull"
    "mc4wp-wpml"
    "autocompleter"
    "google-docs-shortcode"
    "woo-category-slider-for-elementor"
    "random-posts-from-category"
    "kkiapay-woocommerce"
    "acf-accordion"
    "muzaara-adwords-optimize-dashboard"
    "popup-surveys"
    "add-any-extension-to-pages"
    "portfolio-toolkit"
    "atec-cache-apcu"
    "super-simple-jquery-parallax-background"
    "sr-partner"
    "user-access-manager-nextgen-gallery-extension"
    "inlinkz-scripter"
    "wp-youtube-gallery"
    "mobile-redirect-plus-lite"
    "cbxwpsimpleaccounting"
    "custom-links-in-elementor-image-carousel"
    "clock-in-portal"
    "galau-ui-visual-editor"
    "wc-out-of-stock-message"
    "topic"
    "woo-quantity-buttons"
    "fami-woocommerce-compare"
    "hide-plugins"
    "post-editor-buttons"
    "b-blocks"
    "air-wp-sync"
    "just-tinymce-styles"
    "social-share-buttons-lite"
    "zartis-job-plugin"
    "product-layouts"
    "quick-adsense-mobile"
    "buddyforms-acf"
    "toggle-box"
    "wp-scroll-to-top"
    "wp-abstracts-manuscripts-manager"
    "moon-phases"
    "custom-javascript-editor"
    "categoy-thumbnail-list"
    "protect-admin-account"
    "wp-permastructure"
    "dynamic-qr-code"
    "slider-templates"
    "sessions"
    "google-photos-embed"
    "bbb-administration-panel"
    "pattern-manager"
    "admin-commenters-comments-count"
    "tsp-easy-dev"
    "awesome-logos"
    "external-events-calendar"
    "front-editor"
    "custom-css-for-elementor"
    "currencyconverter"
    "wc-frontend-manager-direct-paypal"
    "copy-link"
    "users-by-date-registered"
    "featured-image-via-url"
    "wp-analytics"
    "woo-backorder-manager"
    "universam-demo"
    "sequential-order-numbers-for-woocommerce"
    "vr-calendar-sync"
    "sidebar-image-banner-ads-widget"
    "blip-slideshow"
    "hybrid-slideshow"
    "checkoutwc-lite"
    "libxml2-fix"
    "integrate-charitable-instamojo"
    "review-widgets-for-capterra"
    "awesplash"
    "realhomes-paypal-payments"
    "seo-searchterms-admin"
    "wp-wizard-cloak"
    "ecwid-useful-tools"
    "easy-age-verify"
    "gutenberg-custom-fields"
    "supplier-order-email"
    "video-slider-with-thumbnails"
    "cyfe"
    "studypress"
    "qode-quick-view-for-woocommerce"
    "custom-global-variables"
    "yummly-rich-recipes"
    "advanced-speed-increaser"
    "search-shortcode"
    "related-links"
    "referrer-detector"
    "darklooks-dark-mode-switcher"
    "import-xml-csv-settings-to-rank-math-seo"
    "genesis-simple-customizations"
    "multilevel-referral-plugin-for-woocommerce"
    "affiliatewp-affiliate-info"
    "ultimate-media-cleaner"
    "posts-in-category-widget"
    "web-en-construccion-indianwebs"
    "sticky-social-bar"
    "backtotop"
    "brickslabs-bricks-navigator"
    "simple-galleria-for-wordpress"
    "divup-content"
    "ft-signature-manager"
    "miniorange-wp-ldap-login"
    "tng-wordpress-plugin"
    "validated-field-for-acf"
    "wpmagplus-companion"
    "appointment-reservation-and-rental-booking-for-woocommerce"
    "wp-flickr"
    "improved-save-button"
    "wp-lorem-ipsum-generator"
    "tuxedo-responsive-widget-columns"
    "translate-words"
    "simple-smtp"
    "cf7-intelligence"
    "gf-hcaptcha"
    "acf-google-font-selector-field"
    "spoki"
    "ec-stars-rating"
    "post-updated-date"
    "wp-logged-in-only"
    "ithemeland-bulk-posts-editing-lite"
    "jquery-featured-content-gallery"
    "nofollowr"
    "woofunnels-woocommerce-nmi-gateway"
    "accessibility"
    "tp-piebuilder"
    "vc-image-hotspot"
    "cf7-redirects"
    "parallel-theme-extensions"
    "cardealerpress"
    "advanced-partial-payment-or-deposit-for-woocommerce"
    "bp-activity-autoloader"
    "wcmpg"
    "zplmod-title-checker"
    "power-code-editor"
    "just-one-category"
    "quriobot"
    "emma-emarketing-plugin"
    "wp-hide-admin-bar"
    "social-icons-widget"
    "postalicious"
    "qr-code-woocommerce"
    "wc-payphone-gateway"
    "tinymce-smiley-button"
    "multiple-post-passwords"
    "wechat-weixin-payments-for-woocommerce"
    "wc-ac-hook"
    "mizan-demo-importer"
    "beauty-contact-popup-form"
    "iugu-woocommerce"
    "woo-mpgs"
    "boleto-pag-seguro-direto"
    "mhr-custom-anti-copy"
    "lazy-widget-loader"
    "awin-advertiser-tracking"
    "yayextra"
    "cm-custom-reports"
    "ucalc"
    "enhanced-links"
    "dooodl"
    "site-secrets"
    "status-press-widget"
    "contact-form-with-shortcode"
    "mncombine"
    "shopmagic-for-twilio"
    "wp-parsi-iran-weather"
    "mobstac-blogger"
    "tweet-master"
    "easy-auto-reload"
    "responsive-flickr-gallery"
    "woocommerce-inventory-management"
    "challonge"
    "wp-notification-bell"
    "bangla-date-and-time"
    "wpspoiler"
    "kattene"
    "wplang-lite"
    "site-health-tool-manager"
    "cnhk-slideshow"
    "calculated-fields-for-acf"
    "custom-post-type-sticky"
    "vimeo-simplegallery"
    "super-post-cleaner"
    "documentcloud"
    "wp-photonav"
    "always-use-jetpack-open-graph"
    "stop-xml-rpc-attacks"
    "captivatesync-trade"
    "user-name-security"
    "bbcode"
    "qtranslate-support-for-woocommerce"
    "request-call-back"
    "mass-delete-tags"
    "add-to-cart-button-labels-for-woocommerce"
    "mixlr-shortcode"
    "search-by-id"
    "tantan-reports"
    "wordpress-admin-notepad"
    "password-protect-plugin-for-wordpress"
    "online-booking-engine"
    "easypay-mobile-money"
    "sm-sticky-featured-widget"
    "wow-recruit-widget"
    "wp-discord-post-plus"
    "gravity-forms-css-themes-with-fontawesome-and-placeholder-support"
    "mshop-mysite"
    "metasync"
    "quick-drafts-access"
    "page-sidebar-for-twentyseventeen"
    "broadly"
    "ht-builder"
    "wp-social-avatar"
    "innovs-woo-manager"
    "wp-eventbrite-embedded-checkout"
    "premmerce-user-roles"
    "reusable-gutenberg-blocks-widget"
    "fundpress"
    "zigaform-form-builder-lite"
    "featured-posts"
    "admin-menu-manager"
    "logic-hop"
    "edd-sale-price"
    "a2z-ups-shipping"
    "full-picture-analytics-cookie-notice"
    "soup-show-off-upcoming-posts"
    "gnucommerce"
    "dans-gcal"
    "wc-duplicate-order"
    "postcode-shipping"
    "gravity-forms-personality-quiz-add-on"
    "iloveimg"
    "ni-woocommerce-order-export"
    "spectacula-threaded-comments"
    "typing-text"
    "live-cricket-score"
    "attributes-for-blocks"
    "health-endpoint"
    "identity-verification-for-woocommerce"
    "advanced-css3-related-posts-widget"
    "delivery-times-for-woocommerce"
    "responsive-image-gallery"
    "content-update-scheduler"
    "listapp-mobile-manager"
    "affiliatewp-leaderboard"
    "bb-bootstrap-alerts"
    "trackserver"
    "better-images"
    "commenting-feature"
    "ai-mojo"
    "visitorcontact"
    "wp-film-studio"
    "mail-boxes-etc"
    "wp-media-categories"
    "gamipress-button"
    "update-notifier"
    "cn-excerpt"
    "review-stream"
    "bulk-images-to-posts"
    "wpbkash"
    "creative-commons"
    "hash-link-scroll-offset"
    "post-lockdown"
    "quantcast-quantifier"
    "inspectlet-heatmaps-and-user-session-recording"
    "quickshare"
    "super-cpt"
    "genki-announcement"
    "ambrosite-nextprevious-page-link-plus"
    "spatialmatch-free-lifestyle-search"
    "webd-woocommerce-product-excel-importer-bulk-edit"
    "missed-schedule-post-publisher"
    "formscrm"
    "bp-user-to-do-list"
    "woo-ultimate-order-combination"
    "skp-greeklish-slugs"
    "ultimate-google-fonts"
    "any-user-twitter-feed"
    "php-live-wordpress"
    "woocommerce-payment-methods"
    "echbay-search-everything"
    "tinymce-colorpicker"
    "mrlegend-typedjs"
    "manags-events"
    "woo-epos-now-integration"
    "wavesurfer-wp"
    "form-generator-powered-by-jotform"
    "clima"
    "writeshare"
    "woo-order-notes"
    "widget-entries"
    "gpp-testimonials-widget"
    "import-from-yml"
    "purchased-items-column-woocommerce"
    "traffic"
    "my-instagram-feed"
    "testerwp-ecommerce-companion"
    "css-optimizer"
    "list-view-google-calendar"
    "simple-export-import-for-acf-data"
    "email-to-download"
    "christmas-lights"
    "lock-pages"
    "limit-post-titles"
    "google-web-fonts-for-wordpress"
    "match-me-for-buddypress"
    "top-authors"
    "google-map-locations"
    "upload-media-by-url"
    "publitio"
    "ap-extended-mime-types"
    "retro-game-emulator"
    "text-typing"
    "ultimate-member-job-manager"
    "wp-autoset-featured-image-plus"
    "prodigy-commerce"
    "wt-woocommerce-wishlist"
    "multi-feed-reader"
    "seo-breadcrumbs"
    "acf-fold-flexible-content"
    "email-notification-on-login"
    "screen-reader-with-fontsize"
    "category-featured-image"
    "date-counter"
    "woo-delete-product-images"
    "custom-title"
    "reverse-order-comments"
    "admin-bar-toggle"
    "themify-store-locator"
    "flash-feed-scroll-reader"
    "custom-field-widget"
    "micropub"
    "1-click-migration"
    "disable-jpeg-compression"
    "super-payments"
    "pin-it-button"
    "convertable-contact-form-builder-analytics-and-lead-management-dashboard"
    "bp-phototag"
    "guitar-tuner"
    "porn-videos-embed"
    "bp-group-tinychat"
    "gs-woo-variation-swatches"
    "page-blocks"
    "woo-products-by-category"
    "nextgen-gallery-search-galleries"
    "simple-customizer"
    "sticky-custom-post-types"
    "livecall-inbound-sales-calls"
    "brandfolder"
    "add-rss"
    "echo-show-ids"
    "seo-advicer"
    "buddyforms-woocommerce-form-elements"
    "bens-translator"
    "archive-posts-sort-customize"
    "buddypress-sitemap-generator"
    "featured-video"
    "letter-avatars"
    "modular-custom-css"
    "wp-rest-api-cache"
    "genesis-beta-tester"
    "autocomplete-learndash"
    "web-maps-for-wp"
    "lazysizes"
    "a-year-before"
    "slickplan-importer"
    "auto-save-remote-images"
    "smntcs-disable-rest-api-user-endpoints"
    "maps-for-wp"
    "user-shortcodes"
    "weeblramp"
    "dynamic-price-and-discounts-for-woocommerce"
    "custom-cursor-for-wp"
    "auto-youtube-importer"
    "wp-news-magazine"
    "acf-unique-id-field"
    "automatic-pages-for-privacy-policy-terms-about-and-contact"
    "mylinksdump"
    "binance-pay"
    "protect-the-children"
    "woo-alpha-bank-payment-gateway"
    "templatic-singletemplate"
    "check-conflicts"
    "floating-contact"
    "fr-multi-bank-transfer-payment-gateways-for-woocommerce"
    "wenprise-wechatpay-checkout-for-woocommerce"
    "ams-hide-page-and-post-title"
    "content-table"
    "photo-image-gallery"
    "ceske-sluzby"
    "rdp-wiki-embed"
    "avalex"
    "gdpr-for-gravity-forms"
    "theme-slider"
    "litextension-data-migration-to-woocommerce"
    "wc-moneris-payment-gateway"
    "unique-title-checker"
    "device-detector"
    "list-category-posts-with-pagination"
    "educare"
    "cnn-news"
    "wp-post-formats"
    "simple-rating"
    "piio-image-optimization"
    "latest-news-plugin"
    "itunes-link-engine"
    "ajaxize"
    "woocommerce-frontend-shop-manager-free-version"
    "woocommerce-popup-extension"
    "simple-trackback-disabler"
    "i-order-terms"
    "acf-color-swatches"
    "shipway-shipment-tracking-and-notify"
    "contact-form-7-phone-mask-module"
    "newstastic-post-slider"
    "wpdash-notes"
    "block-wp-login"
    "site-favicon"
    "categorycustomfields"
    "blogger-image-import"
    "learndash-topic-progression-using-storyline-or-captivate"
    "gallery-widget-pro"
    "my-simply-calender"
    "drop-cap-shortcode"
    "youtube-video-sitemap-generator"
    "wp-hooks-finder"
    "publish-post-email-notification"
    "custom-referral-spam-blocker"
    "gmo-showtime"
    "email-blaster-newsletter-signup-form"
    "taggator"
    "geo-targetly-geo-redirect"
    "custom-login-page-wp"
    "domain-check"
    "bootstrap-one-page-woocommerce-checkout"
    "kn-mobile-sharebar"
    "woo-add-custom-fee"
    "stop-media-comment-spamming"
    "helpcrunch-live-chat"
    "force-email-login"
    "wc-customer-source"
    "hikari-email-url-obfuscator"
    "shipping-coordinadora-woocommerce"
    "gatekeeper"
    "interactive-us-map"
    "ioncube-tester-plus"
    "ni-woocommerce-dashboard-report"
    "pp-thai-url"
    "background-control"
    "notification-attachments-for-gravity-forms"
    "wpsso-rest-api"
    "google-content-experiments"
    "grid-archives"
    "pdfjs-viewer-for-elementor"
    "layered-pop"
    "widgets-for-ebay-reviews"
    "premmerce-woocommerce-variation-swatches"
    "buddypress-foaf"
    "conversejs"
    "zhanzhangb-baidu-submit"
    "full-text-feed"
    "smartformat"
    "list-authors"
    "add-external-media"
    "attachment-manager"
    "avif-support"
    "bbp-signature"
    "gallery-voting"
    "rest-api-head-tags"
    "random-post-for-widget"
    "eupago-gateway-for-woocommerce"
    "exclusive-divi"
    "wp-disable-automatic-updates"
    "more-link-modifier"
    "talentlms"
    "wp-bulk-post-duplicator"
    "naver-webmaster-tool-syndication-v2"
    "connections-business-directory-hours"
    "img-title-removal"
    "genesis-featured-page-extras"
    "disable-user-password-reset-emails"
    "smartifw"
    "timeline-awesome"
    "pw-woocommerce-on-sale"
    "buddy-bbpress-support-topic"
    "html-purified"
    "woo-rabo-omnikassa"
    "paymill"
    "chatnox-live-chat"
    "ajax-product-filter-for-woocommerce"
    "verge3d"
    "aspose-pdf-importer"
    "ewsel-lightbox-for-galleries"
    "easy-mailchimp-opt-in"
    "copymatic"
    "woo-phone-validator"
    "first-payment-date-for-woocommerce-subscriptions"
    "ridhi-companion"
    "mihdan-mailru-pulse-feed"
    "bulk-password-reset"
    "registerone-event-forms"
    "wp-custom-taxonomy-meta"
    "wc-ssl-seal"
    "cc-addon-pack"
    "security-safe"
    "woocommerce-auto-category-thumbnails"
    "facturare-persoana-fizica-sau-juridica"
    "mlsimport"
    "coupon-x-discount-pop-up"
    "post-words-count"
    "quick-favicon"
    "wp-e-commerce-style-email"
    "pick-giveaway-winner"
    "collapsing-links"
    "multi-image-upload"
    "feedburner-optin-form"
    "clp-varnish-cache"
    "book-press"
    "vendi-abandoned-plugin-check"
    "ime-ready-taxonomy"
    "simple-image-grabber"
    "wp-easy-backup"
    "disable-recaptcha-cf7"
    "wpsocialstats"
    "vkontakte-cross-post"
    "trusona"
    "paytr-taksit-tablosu-woocommerce"
    "holded-integration"
    "downgrade"
    "electric-studio-auto-expire-post"
    "fast-user-switching"
    "static-block"
    "google-maps-master"
    "cryptocurrency-ticker"
    "file-icons"
    "faq-block-for-gutenberg"
    "smarter-archives"
    "classic-editor-plus"
    "docspress"
    "civicrm-wp-profile-sync"
    "math-captcha-for-elementor-forms"
    "automatic-image-alt-attributes"
    "simple-retail-menus"
    "go-to-top"
    "scroll-magic-addon-for-elementor"
    "rapidmail-newsletter-software"
    "peepsomigrate"
    "feather-login-page"
    "wp-parsi-navigation-trees"
    "unit-price-for-woocommerce"
    "sideoffer"
    "biblesupersearch"
    "live-score"
    "book-review-block"
    "advanced-blogroll"
    "sm-vertical-menu"
    "floating-news-headline"
    "product-image-hover-effects-wooc-wpshare247"
    "google-plus-google"
    "wpsso-wp-sitemaps"
    "supple-forms"
    "wp-widgets-shortcode"
    "wpc-custom-related-products"
    "bp-restrict"
    "wp-tabber-widget"
    "inlocation"
    "wpecomm-mercado-pago-module"
    "alc"
    "review-buddypress-groups"
    "wp-counter"
    "woocommerce-export-orders"
    "focus-videos"
    "buddypress-xprofiles-acl"
    "mouse-cursor-customizer"
    "services-section"
    "new-twitter-button"
    "advanced-categories-widget"
    "buckets"
    "easy-gdpr-consent-mailchimp"
    "wp-post-notifier-for-all"
    "import-youtube-videos-as-wp-post"
    "post-title-colors"
    "ultimate-popup-free"
    "suki-sites-import"
    "wp-tinymce-tables"
    "dobsondev-shortcodes"
    "charts-for-tablepress-chartist"
    "displayproduct"
    "avantex-companion"
    "sociable-re"
    "per-page-widgets"
    "dotmailer-sign-up-widget"
    "disable-parent-menu-link"
    "duitku-social-payment-gateway"
    "mailster-gmail"
    "mp-spam-be-gone"
    "widgets-for-zillow-reviews"
    "timeline-blocks"
    "security-header-generator"
    "restaurant-menu-manager"
    "fancybox-plus"
    "custom-logo"
    "overwrite-uploads"
    "taskbuilder"
    "wp-ogp"
    "sticky-add-to-cart-bar-for-wc"
    "animated-icon-banner-for-visual-composer"
    "before-after"
    "bulk-noindex-nofollow-toolkit-by-mad-fish"
    "epayco-gateway"
    "planyo-online-reservation-system"
    "amp-enhancer"
    "nifty-menu-options"
    "contact-form-7-confirm-email-feild"
    "cdn-tools"
    "random-image-block"
    "crypto-exchange"
    "advanced-animation"
    "delete-duplicate-data"
    "wc-myparcel-belgium"
    "wp-post-video-player"
    "comment-timeout"
    "bp-birthday-greetings"
    "scheduled-announcements-widget"
    "smart-attachment-page-remove"
    "simple-language-switcher"
    "wp-data-sync"
    "logtivity"
    "visual-recent-posts"
    "uninstall-yoast-seo"
    "wc-venipak-shipping"
    "bonus-for-woo"
    "really-simple-google-tag-manager"
    "easy-sale-badges-for-woocommerce"
    "excellent-transition-gallery"
    "total-control-html5-audio-player-basic"
    "ajax-archive-calendar"
    "advanced-custom-fields-recaptcha-field"
    "houzez-property-feed"
    "elex-helpdesk-customer-support-ticket-system"
    "gamma-gallery"
    "calorie-calculator"
    "youtube-uploader"
    "wpcasa-advanced-search"
    "yoast-seo-fix-for-qtranslate"
)

# Define user agents with weights
declare -A USER_AGENTS
USER_AGENTS=(
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"]=5
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"]=7
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"]=6
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36 Edg/91.0.864.54"]=5
    ["Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 OPR/77.0.4054.277"]=3
    ["Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (iPad; CPU OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Vivaldi/4.0"]=1
    ["Mozilla/5.0 (Android 11; Mobile; rv:68.0) Gecko/68.0 Firefox/88.0"]=1
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"]=15
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/534.36"]=12
)

OPENED_PLUGINS_FILE="${WORDPRESS_WORKDIR}/opened_plugins.txt"
CLOSED_PLUGINS_FILE="${WORDPRESS_WORKDIR}/closed_plugins.txt"
LAST_VERSION_FILE="${WORDPRESS_WORKDIR}/last_versions.txt"
PARALLEL_JOBS=1

DOWNLOAD_ALL_PLUGINS='n'
LIST_ONLY='n'
ALL_PLUGINS_FILE="${WORDPRESS_WORKDIR}/wp-plugin-svn-list.txt"

DELAY_DOWNLOADS='n'
DELAY_DURATION=5

FORCE_UPDATE='n'
CACHE_ONLY='n'

mkdir -p "$WORDPRESS_WORKDIR" "$MIRROR_DIR" "$LOGS_DIR"
rm -f "$OPENED_PLUGINS_FILE"
touch "$OPENED_PLUGINS_FILE"
DEBUG_MODE=0

while getopts "p:dalD:t:fc" opt; do
    case ${opt} in
        p ) PARALLEL_JOBS=$OPTARG ;;
        d ) DEBUG_MODE=1 ;;
        a ) DOWNLOAD_ALL_PLUGINS='y' ;;
        l ) LIST_ONLY='y' ;;
        D ) DELAY_DOWNLOADS=$OPTARG ;;
        t ) DELAY_DURATION=$OPTARG ;;
        f ) FORCE_UPDATE='y' ;;
        c ) CACHE_ONLY='y' ;;    # New option for cache-only
        \? ) echo "Usage: $0 [-p PARALLEL_JOBS] [-d] [-a] [-l] [-D DELAY_DOWNLOADS] [-t DELAY_DURATION] [-f] [-c]" 1>&2; exit 1 ;;
    esac
done

debug_log() {
    if [ "$DEBUG_MODE" -eq 1 ]; then
        echo "[DEBUG] $1" >&2
    fi
}

get_random_user_agent() {
    echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
}

get_latest_version_and_download_link() {
    local plugin=$1
    debug_log "Checking latest version and download link for $plugin"
    
    local api_url="https://api.wordpress.org/plugins/info/1.0/${plugin}.json"
    local user_agent=$(get_random_user_agent)
    local api_response=$(curl -s -H "User-Agent: $user_agent" "$api_url")
    
    if echo "$api_response" | jq -e '.error' >/dev/null; then
        local error_message=$(echo "$api_response" | jq -r '.error')
        if [ "$error_message" = "closed" ]; then
            echo "closed"
            return 2
        else
        echo "Error: $error_message for plugin $plugin" >&2
        return 1
        fi
    fi
    
    local version=$(echo "$api_response" | jq -r '.version // empty')
    local download_link=$(echo "$api_response" | jq -r '.download_link // empty')
    
    if [ -n "$version" ] && [ -n "$download_link" ]; then
        echo "$version $download_link"
        return 0
    else
        echo "Error: Cannot fetch version or download link for $plugin" >&2
        return 1
    fi
}

download_plugin() {
    local plugin=$1
    local version=$2
    local api_download_link=$3
    local output_file="${MIRROR_DIR}/${plugin}.${version}.zip"
    local header_file="${LOGS_DIR}/${plugin}.${version}.headers"
    local constructed_download_link="${DOWNLOAD_BASE_URL}/${plugin}.${version}.zip"
    local download_link

    if [ "$DEBUG_MODE" -eq 1 ]; then
        debug_log "API-provided download link for $plugin: $api_download_link"
        debug_log "Constructed download link for $plugin: $constructed_download_link"
    fi

    if [ "$DOWNLOAD_LINK_API" == 'y' ] && [ -n "$api_download_link" ]; then
        download_link="$api_download_link"
        debug_log "Using API-provided download link for $plugin: $download_link"
    else
        download_link="$constructed_download_link"
        debug_log "Using constructed download link for $plugin: $download_link"
    fi

    debug_log "Downloading $plugin version $version through Cloudflare Worker"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)
    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o /dev/null "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    else
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o "$output_file" "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    fi

    if [ $? -eq 0 ]; then
        if [ "$CACHE_ONLY" == 'y' ]; then
            debug_log "Plugin $plugin version $version cached successfully."
            return 0
        fi

        local file_size=$(stat -c%s "$output_file")
        if [ "$file_size" -lt 1000 ]; then
            echo "Error: Downloaded file for $plugin is too small (${file_size} bytes). Possible download issue." >&2
            return 1
        fi

        local source=$(grep -i "X-Source:" "$header_file" | cut -d' ' -f2 | tr -d '\r')
        if [ "$source" == "R2" ]; then
            debug_log "Successfully downloaded $plugin version $version from R2 storage"
        elif [ "$source" == "WordPress" ]; then
            debug_log "Successfully downloaded $plugin version $version from WordPress"
            debug_log "R2 bucket saving for plugin zip occurred"
        else
            debug_log "Skipped download for $plugin $version zip (already exists locally)"
        fi

        return 0
    else
        echo "Error: Failed to download $plugin version $version" >&2
        return 1
    fi
}

save_plugin_info() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.json"

    debug_log "Saving plugin json metadata for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying metadata download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    if [ "$CACHE_ONLY" == 'y' ]; then
        # When in cache-only mode, output to /dev/null
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin metadata for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache json metadata for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            if [ "$source" = "R2" ]; then
                debug_log "json metadata for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "json metadata for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin json occurred"
            else
                debug_log "json metadata for $plugin version $version saved (json metadata file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save json metadata for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

fetch_and_save_checksums() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.checksums.json"

    debug_log "Fetching and saving checksums for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying checksums download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    debug_log "Sending request to Worker for checksums: CF_WORKER_URL?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"

    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin checksums for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache checksums for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        debug_log "Received response with status code: $status_code"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            debug_log "Response source: $source"
            if [ "$source" = "R2" ]; then
                debug_log "Checksums for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "Checksums for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin checksums occurred"
            else
                debug_log "Checksums for $plugin version $version saved (checksums file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save checksums for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

process_plugin() {
    local plugin=$1

    # Check if the plugin is already known to be closed
    if grep -q "^$plugin$" "$CLOSED_PLUGINS_FILE" 2>/dev/null; then
        echo "Plugin $plugin is known to be closed. Skipping."
        return 0
    fi

    echo "Processing plugin: $plugin"

    VERSION_AND_LINK=$(get_latest_version_and_download_link "$plugin")
    local version_check_status=$?
    
    if [ $version_check_status -eq 1 ]; then
        echo "Skipping $plugin due to version fetch error."
        return 1
    elif [ $version_check_status -eq 2 ]; then
        echo "Plugin $plugin is closed. Skipping download and processing."
        echo "$plugin" >> "$CLOSED_PLUGINS_FILE"
        if save_plugin_info "$plugin" "closed"; then
            debug_log "Successfully saved json metadata for closed plugin $plugin."
        else
            debug_log "Failed to save json metadata for closed plugin $plugin."
        fi
        return 0
    fi
    
    LATEST_VERSION=$(echo "$VERSION_AND_LINK" | cut -d' ' -f1)
    API_DOWNLOAD_LINK=$(echo "$VERSION_AND_LINK" | cut -d' ' -f2-)

    debug_log "Latest version for $plugin: $LATEST_VERSION"
    debug_log "API download link for $plugin: $API_DOWNLOAD_LINK"

    STORED_VERSION=$(grep "^$plugin" "$LAST_VERSION_FILE" | awk '{print $2}')
    debug_log "Stored version for $plugin: $STORED_VERSION"

    if [ "$CACHE_ONLY" != 'y' ] && [ "$LATEST_VERSION" == "$STORED_VERSION" ] && [ -f "${MIRROR_DIR}/${plugin}.${LATEST_VERSION}.zip" ]; then
        echo "$plugin is up-to-date and exists in mirror directory. Skipping download..."
    else
        start_time=$(date +%s.%N)

        if download_plugin "$plugin" "$LATEST_VERSION" "$API_DOWNLOAD_LINK"; then
            if [ "$CACHE_ONLY" != 'y' ]; then
                sed -i "/^$plugin/d" "$LAST_VERSION_FILE"
                echo "$plugin $LATEST_VERSION" >> "$LAST_VERSION_FILE"
            fi
            echo "Successfully processed $plugin."
        else
            echo "Error: Failed to process $plugin." >&2
        fi

        end_time=$(date +%s.%N)
        duration=$(echo "$end_time - $start_time" | bc)
        printf "Time taken for %s: %.4f seconds\n" "$plugin" "$duration"
    fi

    if save_plugin_info "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully saved json metadata for $plugin."
    else
        debug_log "Failed to save json metadata for $plugin."
    fi

    if fetch_and_save_checksums "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully fetched and saved checksums for $plugin."
    else
        debug_log "Failed to fetch and save checksums for $plugin."
    fi

    if [ $version_check_status -eq 0 ]; then
        echo "$plugin" >> "$OPENED_PLUGINS_FILE"
    fi
}

populate_all_plugins() {
    if [ ! -f "$ALL_PLUGINS_FILE" ] || [ "$LIST_ONLY" == 'y' ]; then
        echo "Fetching list of all WordPress plugins..."
        svn list https://plugins.svn.wordpress.org/ | sed 's/\/$//g' > "$ALL_PLUGINS_FILE"
        plugin_count=$(wc -l < "$ALL_PLUGINS_FILE")
        echo "Plugin list (${plugin_count}) saved to $ALL_PLUGINS_FILE"
    fi
    
    if [ "$LIST_ONLY" == 'n' ]; then
        ALL_PLUGINS=()
        while IFS= read -r line; do
            ALL_PLUGINS+=("$line")
        done < "$ALL_PLUGINS_FILE"
        echo "Loaded ${#ALL_PLUGINS[@]} plugins."
    fi
}

if [ "$LIST_ONLY" == 'y' ]; then
    populate_all_plugins
    echo "Plugin list created. Exiting without downloading."
    exit 0
fi

if [ "$DOWNLOAD_ALL_PLUGINS" == 'y' ]; then
    populate_all_plugins
    COMBINED_PLUGINS=("${ALL_PLUGINS[@]}")
else
    if [ ! -d "$PLUGIN_DIR" ]; then
        echo "Warning: Plugin directory $PLUGIN_DIR does not exist or is invalid."
        PLUGIN_LIST=()
    else
        PLUGIN_LIST=($(ls -d "$PLUGIN_DIR"/*/ 2>/dev/null | xargs -n 1 basename))

        if [ ${#PLUGIN_LIST[@]} -eq 0 ]; then
            echo "No plugins found in $PLUGIN_DIR."
        fi
    fi

    COMBINED_PLUGINS=(${PLUGIN_LIST[@]} ${ADDITIONAL_PLUGINS[@]})
    COMBINED_PLUGINS=($(echo "${COMBINED_PLUGINS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
fi

if [ ${#COMBINED_PLUGINS[@]} -eq 0 ]; then
    echo "No plugins to download. Exiting."
    exit 0
fi

mkdir -p "$MIRROR_DIR"
touch "$LAST_VERSION_FILE"

if [ "$PARALLEL_JOBS" -gt 1 ]; then
    echo "Running in parallel with $PARALLEL_JOBS jobs..."
    # First, export all variables including USER_AGENTS
    export DOWNLOAD_BASE_URL MIRROR_DIR LAST_VERSION_FILE DEBUG_MODE DOWNLOAD_LINK_API LOGS_DIR ALL_PLUGINS_FILE DOWNLOAD_ALL_PLUGINS LIST_ONLY CF_WORKER_URL DELAY_DOWNLOADS DELAY_DURATION FORCE_UPDATE CACHE_ONLY USER_AGENTS

    # Then, export the functions
    export -f process_plugin get_latest_version_and_download_link download_plugin debug_log populate_all_plugins save_plugin_info get_random_user_agent fetch_and_save_checksums
    printf "%s\n" "${COMBINED_PLUGINS[@]}" | xargs -P $PARALLEL_JOBS -I {} bash -c 'process_plugin "$@"' _ {}
else
    for plugin in "${COMBINED_PLUGINS[@]}"; do
        process_plugin "$plugin"
    done
fi

if [ -f "$CLOSED_PLUGINS_FILE" ]; then
    echo
    echo "Closed Plugin List:"
    cat "$CLOSED_PLUGINS_FILE" | sort | uniq || true
    echo
    echo "Total closed plugins: $(wc -l < "$CLOSED_PLUGINS_FILE")"
    echo
else
    echo
    echo "No closed plugins found."
    echo
fi
echo "Plugin download process completed."
