#!/bin/bash

# Base directory (script location)
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Configurable directories
WORDPRESS_WORKDIR="${WORDPRESS_WORKDIR:-$BASE_DIR/wordpress-plugins}"
PLUGIN_DIR="${PLUGIN_DIR:-$BASE_DIR/wp-content/plugins}"
MIRROR_DIR="${MIRROR_DIR:-$BASE_DIR/mirror}"
LOGS_DIR="${LOGS_DIR:-$BASE_DIR/plugin-logs}"

# Check for CF_WORKER_URL environment variable
if [ -z "$CF_WORKER_URL" ]; then
    echo "Error: CF_WORKER_URL environment variable is not set." >&2
    exit 1
fi

DOWNLOAD_BASE_URL="https://downloads.wordpress.org/plugin"

# Other variables
DOWNLOAD_LINK_API='y'

ADDITIONAL_PLUGINS=(
    "subscription-shortcodes"
    "image-nsfw"
    "social-elementor-lite"
    "hetjens-registered-only"
    "update-comments-count"
    "default-post-datetime"
    "show-me-the-admin"
    "woosync-product-stock-synchronizer-for-woocommerce"
    "woo-recargo-de-equivalencia"
    "authorsy"
    "homepage-helden-contact-info"
    "fast-events"
    "easy-kickstarter-widget"
    "pro-related-post-widget"
    "sovrn-mobile-ad-manager"
    "simple-wp-login"
    "index-tag-page"
    "red5-recorder"
    "amilia-store"
    "multi-site-user-replicator-3000"
    "realty-portal-floor-plan"
    "bp-add-post-updates-to-activity"
    "johnny-cache"
    "game-catalog"
    "easy-acf-connect-for-themer"
    "swedbank-pay-payment-menu"
    "easypromos"
    "block-spammers"
    "wp2pcloud"
    "pass-url-parameters-to-embeded-iframe"
    "mrz-social"
    "learny-lms"
    "very-simple-link-manager"
    "treedbox-admin-menu"
    "stonehenge-em-gateway-selector"
    "juvo-mail-editor"
    "legal-page-generator"
    "restore-columns"
    "unslider-image"
    "keyword-landing-page-generator"
    "wiki-menus"
    "easy-image-alternate-text"
    "tendopay"
    "photo-gallery-rb"
    "wp-responsive-slideshows"
    "foxlis-geo"
    "wp-ipua"
    "vazir-font"
    "gozen-forms"
    "advanced-image-comparison-for-elementor"
    "link-replacer"
    "own-post-media-for-authors"
    "miniorange-radius-client"
    "show-archive-descriptions"
    "ejls-easy-json-ld-setter"
    "live-support-tickets"
    "free-woocommerce-wishlist"
    "simple-sugarsync-upload"
    "unblock-cs-jss-for-googlebot"
    "radio-tools"
    "leaderboard-lite"
    "woo-simple-frontend-manager"
    "enable-numeric-slugs"
    "seo-internal-links-revisited"
    "responsive-vertical-recent-post-ticker"
    "wpxmas-snow"
    "orbisius-blank-slate"
    "tubentertain"
    "external-links-new-tab-nofollow"
    "bluff-post"
    "echo-rewards"
    "better-footnotes"
    "cm-blocks"
    "dr-widgets-blocks"
    "juiz-outdated-post-message"
    "demopress"
    "featured-image-reminder"
    "mention-links"
    "all-posts-page-link"
    "website-information-report"
    "howuku"
    "wpsitemap"
    "simple-wall"
    "advanced-custom-fields-menu-field-add-on"
    "page-comments"
    "bbcode-widget-titles"
    "muvi-media-connect"
    "mailgun-subscriptions"
    "wordphone"
    "cackle-social-login"
    "seo-writing-assistant-semrush-custom-fields"
    "usetiful-digital-adoption-platform"
    "woocommerce-phone-order-gateway"
    "auto-fill-form-fields"
    "wp-notepad"
    "html-for-all-url"
    "patsatech-wc-opayo-server"
    "cumulonimbus"
    "echosign"
    "serpzilla"
    "nexxplay"
    "mybox-b2b"
    "blocks-product-editor-for-woocommerce"
    "prosolution-wp-client"
    "lazy-load-image-filter"
    "city-dropdown-for-woocommerce"
    "gp-related-posts"
    "local-links"
    "bubok-publisher"
    "link-media-from-tinymce"
    "teleport"
    "simple-share-from-admin"
    "hybrid-byline"
    "posts-categories-in-sidebar"
    "nice-animation-progressbar"
    "wikilookup"
    "formidable-pro-add-color-picker-field"
    "duplicate-images"
    "quickchat"
    "kw-essential-share-buttons"
    "maps-deriction"
    "triple-pricing-table"
    "feed-geomashup"
    "mailercloud-integrate-webforms-synchronize-contacts"
    "wp-sms-functions"
    "apoyl-video"
    "ezpz-sp"
    "f4-improvements"
    "accordion-categories"
    "envato-affiliater"
    "brewery-db"
    "fx-skype-link-enabler"
    "cpt-custom-page-template"
    "woo-addon-for-payubiz"
    "notifications-to-all-administrators"
    "killit"
    "simple-event-schedule"
    "easy-login-logout"
    "remove-woocommerce-billing-address-for-free-checkout"
    "smart-menu-shortcode"
    "easy-digital-downloads-paddle-integration"
    "ruven-themes-social-widget"
    "mg-advancedoptions"
    "additional-authors"
    "linkedlist"
    "editor-cleanup-for-flatsome"
    "post-metaboxes-tabs"
    "group-forum-crumbs"
    "master-paper-collapse-toggle"
    "simple-paypal-button-for-visual-composer"
    "wd-image-magnifier-xoss"
    "plugin-maker"
    "bookwize-integrated-cinnamon"
    "badgeos-buddypress-notifier"
    "datapocket"
    "password-only-login"
    "save-as-pdf"
    "mfs-survey"
    "membersonic-addon-for-wp-courseware"
    "just-in-case-gallery"
    "disable-downloadable-repeat-purchase"
    "smcountdown"
    "flexo-countdown"
    "hello-samuel-l-jackson"
    "content-ignite"
    "raw-latest-posts-widget"
    "virtual-sidebar"
    "faster-youtube-embed"
    "seo-crawlytics-data-export"
    "no-duplicate-content-in-comments"
    "mykraft-responsive-video-shortcode"
    "mmm-unity-loader"
    "i7avatar"
    "wc-sms"
    "caption-links"
    "mipl-stockist-store-locator"
    "awesomepress"
    "donate-ribbon"
    "tvprofil-box"
    "emojicom"
    "sitemap-html-generator"
    "selloship"
    "gosign-post-teaser-block"
    "suggest-comments"
    "404gottenorg-404-page"
    "qr-code-scan-me-anywhere"
    "embed-github"
    "dynamic-cart-messages-woocommerce"
    "custom-sucuri"
    "max-stats-table-for-wp-pro-quiz"
    "dc-edd-bkash-payment"
    "display-wordpress-version"
    "orcas-responsive-wiki"
    "icpbeian"
    "wp-upcoming-releases"
    "umatter2us"
    "contact-form-24"
    "reddit-widget"
    "wp-comments-manager"
    "ljusers"
    "wpflickr"
    "buddypress-profile-view-from-admin"
    "wp-hook-finder"
    "menu-location"
    "post-type-archive-in-menu"
    "boombox-shortcode"
    "correct-audio-video-uploads"
    "betterify"
    "dbd-pinterest-widget"
    "wp-keyboard-navigation"
    "website-authority-checker"
    "cresta-post-widget"
    "popup-ads-management"
    "autosku-for-woocommerce-variable-products"
    "juiz-lang-attributes"
    "bh-wp-autologin-urls"
    "quizz"
    "blaatschaap-oauth"
    "mediafire-filedrop-manager"
    "sabapayamak"
    "devexhub-gallery"
    "slider-path"
    "jojo-woocommerce-description"
    "tinypress"
    "similar-posts-ontology"
    "seo-advanced-custom-fields-analyzer"
    "angellist"
    "knowledge-graph"
    "image-carousel-shortcode"
    "lana-seo"
    "ordered-product-identifier"
    "tsp-facepile"
    "restaurant-food-menu"
    "remove-disqus-ads"
    "sm2wp-google-minimal"
    "stop-cf7-multiclick"
    "ldb-external-links"
    "xml-ify-wordpress-multiple-posts"
    "github-gist-shortcode"
    "integrate-ga4-google-analytics"
    "zpt-metals"
    "gatormail-smart-forms"
    "casino-games"
    "disable-pointers"
    "related-post-shortcode"
    "0-errors"
    "wp-game"
    "f4-simple-whitelabel"
    "woocommerce-egypt-cities"
    "woocommerce-netsaxept"
    "sr-scroll-to-top-wp"
    "wp-sidebar-essential"
    "frotel-woocommerce"
    "sl-currency-symbol-changer"
    "wpbackbutton"
    "googlemapper-2"
    "fotherplot"
    "wp-btbuckets"
    "wp-offscreen-navigation"
    "avatars-meta-box"
    "file-select-control-for-elementor"
    "wp-mathjax-plus"
    "datacake-core"
    "wp-login-page-customizer"
    "mindmeister-shortcode"
    "image-shortcake"
    "mediaview"
    "free-post-mail"
    "woo-hnb"
    "toolbar-plugins-link"
    "geekshed-embed"
    "category-and-tag-specific-widgets"
    "adlib-woo2lex-manuell"
    "integration-between-leaflet-map-and-civicrm"
    "rating-review-matrix"
    "elemental-calculator"
    "wpfiles"
    "chesstempoviewer"
    "elegant-responsive-content-slider"
    "wp-doubanshow"
    "last-name-first-name"
    "imageflux"
    "custom-upload-folders"
    "wp-recaptcha-library"
    "wp-vote"
    "stream-to-slack"
    "attachments-handler"
    "tuis-author-intro-for-archive"
    "sf-pages-for-custom-posts"
    "oktium-face2-widget"
    "multiple-images-widget"
    "admin-sticky-widget-areas"
    "social-media-block"
    "woo-atom-payment-gateway"
    "your-tables"
    "wp-chooseyourtheme"
    "website-backup-bot"
    "applixir"
    "admin-columns-icons-addon"
    "dummy-text-shortcode"
    "zes-admin-update-notification"
    "disable-grunion-admin-link"
    "voltax-video-player"
    "rt-elementor-widgets"
    "content-visibility-geolocation"
    "fresh-connect"
    "woo-custom-registration"
    "devarai-crosswords"
    "redq-events"
    "wp-box-simpple"
    "mapp-intelligence"
    "excerpt-character-limiter"
    "wp-autolead"
    "display-recently-registered-users"
    "sheets2table"
    "cc-ontario-tax-calculator"
    "post-read-time"
    "page-templates-for-posts"
    "front-end-category-management"
    "writers-block-block"
    "post-page-notes"
    "lh-buddypress-login-on-activation"
    "wp-gif-resizer"
    "gyta-buyback"
    "upload-multiple-image"
    "shop-calendar"
    "noindex-past-events"
    "swiftpay-payment-gateway-for-woocommerce"
    "noshlyok"
    "custom-post-types-image"
    "odvut-author-bio"
    "mobile-responsive-sidebar"
    "dropday-for-woocommerce"
    "embedding-pdf"
    "gf-multi-uploader"
    "gravity-forms-tave-add-on"
    "justin"
    "track-site-traffic"
    "wp-hash-filename"
    "akari-worker"
    "simple-login-logout"
    "wp-post-url"
    "wp-transitions"
    "media-license"
    "easy-embed-for-youtube-wall"
    "itunes-charts"
    "guten-forms-akismet"
    "upcoming-meetings-bmlt"
    "bauernregeln"
    "tumblr-ajax"
    "sweepstakes-app"
    "woo-sadad-payment-gateway"
    "eliminate-notify-email"
    "highlight"
    "sogrid-lite-social-networks-posts-grid"
    "wp-featured-posts"
    "yummy-cookies"
    "c-purge-cache"
    "post-format-filter"
    "oh-authors-recent-posts-widget"
    "admin-bug-report"
    "cat-comment-filter"
    "kalimah-shortcodes"
    "site-reset"
    "ray-social-feeds-for-twitter"
    "button-widget"
    "custom-wp-update-message"
    "wpdelaycron"
    "ruvuv-extension-for-elementor"
    "superauth"
    "media-library-image-gallery"
    "fleetwire-fleet-management"
    "simple-blueprint-installer"
    "q-cleanup"
    "post-notify-users"
    "wp-dropzone"
    "query-shortcode"
    "my-extreme-twitter"
    "woocommerce-product-review-sorting"
    "last-commented-posts"
    "smart-tools-for-woocommerce"
    "ezcount"
    "realty-portal-agent-profile"
    "ld-assignment-uploads-ctrl"
    "widgets-master"
    "icerik-bulutu"
    "wp-app-store-landing-page"
    "regiondo-booking-widget"
    "invelity-mygls-connect"
    "mpwizard"
    "visited-countries"
    "israel-cities-dropdown"
    "network-favicons"
    "narando"
    "featured-widget"
    "bleep-filter"
    "wc-change-product-author"
    "recaptcha-for-login-and-registration"
    "readme-detonator"
    "featured-users-wordpress-plugin"
    "dev-toolbox"
    "ezrentout-online-webstore"
    "shink-monetization"
    "db-search-with-elasticsearch"
    "woo-country-based-bank-accounts"
    "ppm-faq"
    "automated-db-schenker-shipping"
    "matrix-wishlist"
    "dtslider"
    "game-of-15"
    "simple-wistia-embed"
    "smooth-directory"
    "secure-uploads"
    "parsijoo-map"
    "same-height"
    "wpmu-blog-name-restrictions-override"
    "easy-edd-for-elementor"
    "image-flip-for-woocommerce"
    "bulk-password-protect-post-types"
    "bp-favorite-groups"
    "job-tracker"
    "advanced-custom-css"
    "innovator-ai"
    "edgemesh"
    "xml-rpc-de-whitespacer"
    "horoscopus"
    "locco-emoticons"
    "yapb-geotag"
    "extra-classes"
    "gecko-google-calendar"
    "bootstrap-carousel-2x-post-widget"
    "ibexrentacar"
    "merchant-xml-feed-generator"
    "writer-helper"
    "is-your-server-ready-for-wordpress-32"
    "test-user-role"
    "intro-wrapper"
    "moneybookers-merchant-gateway-for-eshop"
    "topspin-streaming-player-plugin"
    "cookieless-analytics"
    "trunc-logging"
    "dotenv"
    "user-drop-down-roles-in-registration"
    "wp-heatmap"
    "topcat"
    "protect-wp-videos"
    "unlist-my-post"
    "wp-minor-edit"
    "woo-in-stock-notifier"
    "badgeos-open-badges-issuer-add-on"
    "rootitr"
    "docular"
    "responsive-header"
    "wordpress-white-label"
    "wp-disable-site-health"
    "wp-sitemap-control"
    "integrate-khalti-in-wc-store"
    "autowp-ai-content-writer-rewriter"
    "get-tweets-in-php"
    "wn-webpage-slider-for-elementor"
    "js-twentytwenty"
    "easy-translate"
    "jay-rss-show"
    "disable-elements-for-wpbakery-page-builder"
    "bip-pages"
    "product-badges-for-woocommerce"
    "image-hotspot-block"
    "ipv6detector"
    "smiling-video"
    "price-slider"
    "slim-slider"
    "triggerfish-bytbil-accesspaket"
    "b-laser"
    "easy-peasy-google-analytics"
    "popup-notification-news-alert"
    "sprinque"
    "springbot"
    "isurvey"
    "social-share-love"
    "wysiwyg-editor-for-contact-form-7"
    "alpha-sms"
    "ics-button"
    "add-multiple-marker"
    "actionwear-products-sync"
    "post-worktime-logger"
    "hikari-featured-comments"
    "omnify-widget"
    "increase-maximum-execution-time"
    "excerpt-by-characters"
    "notify-events"
    "simple-shortcode-woocommerce-shipping-calculator"
    "favicon-images-for-comments"
    "product-id-permalink-for-woocommerce"
    "export-without-shortcodes"
    "remove-generator-information"
    "wp-gallery-download-link"
    "furgefutar-hu-integracio"
    "copyright-editor-easy"
    "post-saint"
    "azampay"
    "redirect-shop-page-for-non-registered-users-woocommerce"
    "smart-post-slider"
    "cs-likes-counter"
    "simple-expand"
    "mitfahrgelegenheit"
    "asynchronous-jquery-loader"
    "integrate-sharpspring-and-gravity-forms"
    "inventivo-cookie-notice"
    "embed-custom-field"
    "youtube-player-with-playlist"
    "local-storage-back-up"
    "woocommerce-checkout-password-strength-meter"
    "hura-custom-cursors"
    "wp-ragadjust"
    "mediavine-pagination"
    "ehive-account-details"
    "face-recognition"
    "video-audio-bbcodes"
    "helpdesk-support-tickets"
    "dark-visitors"
    "ga-code"
    "oc-customers-import"
    "order-search-repair-for-woocommerce"
    "travel-game"
    "sms-alert-for-contact-form-7"
    "diwali"
    "wp-oniad"
    "mynewsdesk"
    "cost-of-goods"
    "neoncrm-events-widget"
    "semantic-tags"
    "fdsphotofeed-v100"
    "woocommerce-api-lockdown"
    "dark-site"
    "ajax-search-bar"
    "old-style-admin-ui"
    "md-custom-content"
    "get-directions-from-mobile"
    "quantimodo"
    "qsynced"
    "itman-page-speed-insights"
    "woo-pixelpay-gateway"
    "cf7-multi-step-forms"
    "cookie-consent-for-developers"
    "bigdump-restore"
    "unilms"
    "chronological-spam-removal"
    "genie-image-ai"
    "show-fit-file"
    "evidence"
    "listen2it"
    "responsive-table-for-woocommerce"
    "ahmeti-wp-guzel-sozler"
    "os-attendance-management"
    "shadow-terms"
    "maintenance-checklist"
    "ubuntu-sidebar"
    "newsletter-buddypress"
    "hello-wapuu"
    "av-csv-2-posts"
    "blip-widget"
    "collabpay"
    "acf-soundcloud-playlists"
    "paint-color-insert-tool"
    "easy-php-sudoku-game"
    "backstage"
    "productviewer"
    "wp-replace-unlicensed-and-broken-images"
    "spodelime"
    "wp-mail-ses"
    "gallery-excerpt"
    "wp-responsive-contact-form"
    "randomquotr"
    "restrict-content-pro-terms-and-conditions"
    "sully"
    "callback-for-monarch-by-logic-hop"
    "rte-comments"
    "socialhub"
    "wp-tag-generator"
    "genesis-inline"
    "cognativex"
    "simple-debug-info-panel"
    "wow-blue-quotes"
    "octoboard"
    "meinturnierplande-widget-viewer"
    "wp-scroll-2"
    "tk-shortcode-link"
    "sp-google-maps"
    "pay-to-view"
    "nodelytics"
    "very-simple-paypal-donation-form"
    "cf7-show-page"
    "insertify"
    "wphobby-pdf-invoices-for-woocommerce"
    "add-custom-css-and-js"
    "exact-match-disallowed-comment-contact-forms"
    "stop-write"
    "woo-cart-items-bulk-deletion"
    "jetpack-follow-link-for-p2"
    "easy-access-reusable-blocks"
    "pop-up-element-for-flatsome-theme"
    "wc-coupons-by-country"
    "multi-mobile-redirect"
    "shopp-seo"
    "addon-sweetalert-contact-form-7"
    "wp-keys-giveaway"
    "infast"
    "chameleon-jobs"
    "hack-me-if-you-can"
    "wp-lazy-loaded-images"
    "bot-cat"
    "flexblocks"
    "cache-google-font"
    "toast-responsive-menu"
    "tcbd-popover"
    "dropwp-generator"
    "s3cloud"
    "monetize-wp"
    "my-sites-widget"
    "wp-togetherjs"
    "admin-bar-fix"
    "wp-user-profile-restriction"
    "file-uploader-for-woocommerce"
    "feed-seo"
    "showdown"
    "ajax-admin"
    "simple-no-bot"
    "kwik-delivery-for-wcommerce"
    "application-passwords-manager"
    "kanban-gravity-forms"
    "cron-task-viewer-redux"
    "wp-better-seo-links"
    "pay-addons-for-elementor"
    "digital-warranty-card-generator"
    "healthy-bmi-calculator"
    "split-order-by-category"
    "client-dash-wp-help-add-on"
    "mxyoutuber-responsive"
    "plugin-installer-from-public-url"
    "woocommerce-coupon-column"
    "quote-post-type-plugin"
    "image-color-palette"
    "recent-comments-by-entry"
    "wp-emi-calculator"
    "gosign-youtube-video-player-block"
    "c7-form-builder"
    "post-scroll-widget"
    "hr-widget"
    "wp2baiduzone"
    "dps-pxpay-for-wp-ecommerce"
    "sk-wp-admin-login-captcha"
    "disable-auto-updates"
    "disable-wp-emoji-icons"
    "cpt-on-front-page"
    "aomailer"
    "asiabill-payment-gateway-for-woocommerce"
    "faltu-testimonial-rotator"
    "naver-syndication"
    "netbible-tagger"
    "nexternal"
    "wp-prestashop-categories"
    "talika"
    "pricing-table-blocks"
    "return-shortlink-button"
    "change-media-parent"
    "comment-signature"
    "videonab"
    "dx-localhost"
    "twittercart"
    "wp-e-commerce-free-checkout"
    "face-authentication-login"
    "brasil-61-conteudo-gratuito-para-radios-sites-e-blogs"
    "admin-bar-plus"
    "google-reader-subscriptions"
    "wp-post-limiter"
    "ice-bio-url-shortener"
    "seolat-tool-plus"
    "snevejr"
    "vintagejs"
    "ple-navigation"
    "about-post-type"
    "b-accordion"
    "xt-easy-google-adsense-injection"
    "twitter-tools-supr-link"
    "add-wpgraphql-send-mail"
    "ergonet-varnish-cache"
    "wp-auto-thumbnails"
    "adjacent-archive-links"
    "wc-getloy-gateway"
    "let-them-unsubscribe"
    "market-360-viewer"
    "stage-wp-plugin-manager"
    "wp-sstat-visitors"
    "sharethis-reviews"
    "wp-mail-changer"
    "gltf-media-type"
    "clust-client-portal"
    "payment-gateway-for-woocommerce-by-helcim"
    "wp-parsi-permalink-translator"
    "floating-top-link"
    "easy-post-series"
    "tmediaa-weather-plugin"
    "wehewehe"
    "did-you-mean"
    "database-read-replicas"
    "gift-cards-coupon-input"
    "auto-block-recovery"
    "wp-responsive-images"
    "awesome-timeline"
    "feed-comments-number"
    "jetpack-mobile-theme-floating-ad"
    "pdf-secure"
    "a-better-planet"
    "comment-recovery"
    "tolstoy-video"
    "os-bxslider"
    "media-post-permalink"
    "extended-woocommerce-customer-management-for-users-insights"
    "luckywp-wiki-linking"
    "whistleblowing-system"
    "media-library-search"
    "auto-register-for-woocommerce"
    "rtl-rss-feed-fixer"
    "wordfez"
    "matcms"
    "advanced-custom-fields-wpml-language-selector"
    "super-related-posts"
    "wpubg"
    "wp-replicate-post"
    "media-menu-order"
    "comment-hierarchy-adjust"
    "popcorn"
    "plugins-genius"
    "there-can-be-only-one"
    "jk-google-analytics"
    "abbs-bing-search"
    "metabox-header-color"
    "mybbsync"
    "animated-headline-elementor"
    "beautiful-pull-quotes"
    "antispam-login-form"
    "text-drift"
    "sinalite-for-woocommerce"
    "is-gallery"
    "quatro-splatkovy-predaj"
    "embed-google-data-studio"
    "set-the-stage"
    "geoplugin-currency-shortcode"
    "agnoplay"
    "timify"
    "toolkit-for-learndash-lms"
    "simple-category-posts-widget"
    "recurring-payment-donation-through-stripe"
    "nsfw"
    "ctl-playful-kitty-c2-lite"
    "wp-vm-testimonials-plus"
    "aino-notification-block"
    "yd-setup-locale"
    "manchete-atual-fotojornal"
    "affiliateimporterbg"
    "gf-insightly"
    "acl-woo-advanced-customer-dashboard"
    "modula-photoblocks-gallery-migrator"
    "canvaspop-photo-printing-api"
    "reportcomments"
    "blocked-in-china"
    "feeds-in-theme"
    "woo-payswitch-theteller-payment-gateway"
    "edd-invoice-data"
    "simplegmaps"
    "simply-json"
    "admin-menu-customizer"
    "auto-delete-post"
    "goto-contact-center-webchat"
    "brg-gutenberg-slider"
    "woocommerce-recently-viewed-products-from-all-visitor-by-samsys"
    "dialog-ez-cash-payment-gateway-for-woocommerce"
    "jet-unit-site-could"
    "smartphone-location-lookup"
    "madeep-wp-connector"
    "admin-sticky-sidebar"
    "country-flags"
    "woo-payvalida-gateway"
    "appilix"
    "edd-bulk-sale-price"
    "kangtai-netease-music-office-player"
    "wc-spin-to-win-wheel"
    "hire-me-status-widget"
    "contentbird-cms-integration"
    "new-recent-posts-select-categories-by-thao-marky"
    "imienniczek"
    "packerland-custom-blocks"
    "webmicro-merchantone-woo-addon"
    "lti-tool"
    "sb-tbfa"
    "affilitate-link-cookie-maker"
    "weekly-archive-widget"
    "revision-history"
    "sv-sticky-menu"
    "simply-strava"
    "wp-crop-stop"
    "wpcontrol"
    "gongan-beian"
    "pizza-builder-for-woocommerce"
    "revcanonical"
    "logic-hop-hubspot-add-on"
    "bw-slideshow"
    "shamor"
    "merpress"
    "sd-count-per-day-overview"
    "np-forex-commodity-widget"
    "remsupp"
    "ns-product-brand"
    "http-syndication"
    "price-quantity-plugin"
    "jq-daily-pop-up"
    "elfsight-testimonials-slider"
    "video-block-with-ads"
    "custom-admin-ui"
    "irandargah-payment-gateway-for-woocommerce"
    "javascript-image-loader"
    "elash-slider"
    "wp-adc"
    "seo-search-permalink"
    "ehive-objects-gallery-widget"
    "blahbox"
    "advanced-comments-moderation"
    "nippombashi-2016"
    "gf-add-on-autoexport-entries-to-csv"
    "handywriter"
    "localize-time"
    "alister"
    "post-for-chatwork"
    "goal-tracker-for-patreon"
    "keyword-collector"
    "cc-tagger"
    "change-category-checkbox-to-radio-button"
    "oswald-lite-extension"
    "bonanza-woocommerce-free-gifts-lite"
    "sites-settings"
    "woo-framework-shortcodes"
    "publish-to-netlify"
    "launchrock"
    "my-accordion"
    "cf7-blacklist"
    "woo-bookings-extensions"
    "category-archives"
    "coppermine-badge-widget"
    "schedule"
    "affilizz"
    "wpappsdev-pcbuilder"
    "scale-it-up"
    "simple-shortcode-buttons"
    "page-edit-toolbar"
    "first-data-payment-gateway-for-woocommerce"
    "nutsforpress-login-watchdog"
    "focus-slider"
    "woo-tabs"
    "page-for-random-banners"
    "permalink-encoding"
    "lazyest-gallery-hide-menu"
    "click4assistance-live-chat-real-time-visitor-monitoring"
    "wp-hide-adminbar"
    "fast-backend"
    "wp-strip-image-metadata"
    "ultimate-membership-pro-payfast"
    "proprofs-chat"
    "stionic-users"
    "helioviewerorg-latest-image-of-the-sun"
    "jonathansblog-featured-image-setter"
    "picker"
    "email-me"
    "bliskapaczka-pl"
    "outstanding-bar"
    "instant-pay"
    "quick-maps"
    "woo-classement"
    "add-toolbar-content-links"
    "custom-query-shortcode"
    "advanced-logo-showcase"
    "orderstorm-e-commerce"
    "infinite-scroll-random-post"
    "shortcode-bootstrap-visuals"
    "allow-latex-uploads"
    "custom-woo-builder-for-elementor"
    "followize-extension-cf7"
    "wp-allow-hosts"
    "tuxedo-importer"
    "ar-back-to-top"
    "current-post"
    "wonder-cache"
    "sort-any-table"
    "site-performance"
    "weekly-fortune-telling-cards"
    "wc-stripe-checkout-payment-gateway"
    "rb-external-thumbnail"
    "word-of-the-day-from-thefreedictionarycom"
    "urlslab"
    "schedule-your-content"
    "dynamic-placeholder-images"
    "easyqr"
    "editorx"
    "export-customers-data"
    "toggleable-admin-bar"
    "fancy-grid-portfolio"
    "disable-all-comments"
    "wpdevtool"
    "wp-storymap"
    "user-dropdown-menu"
    "wp-review-schema"
    "customize-widgets-plus"
    "accedeme-for-wp"
    "wp-ngd-widget-css-classes"
    "bsk-gravity-forms-custom-validation"
    "mk-post-and-page-excerpts-widgets"
    "callbackkiller-service-widget"
    "jetpack-feedback-exporter"
    "analytics-enabler"
    "links-synthesis"
    "advanced-robots-txt-optimizer-editor"
    "mu-post-to-multiple-blogs"
    "multi-vendor-marketplace-lite-for-woocommerce"
    "wopo-toolkit"
    "comment-form-inline-errors"
    "rundiz-postorder"
    "wp-assistant"
    "get-snarky"
    "wp-unit"
    "shp-icon"
    "convead-for-woocommerce"
    "add-shortlink-to-posts"
    "mail2users"
    "menukaart"
    "dx-sources"
    "webcollage"
    "add-browser-search"
    "brodos-net-onlineshop"
    "freesoul-responsive-check"
    "gosign-vimeo-video-player-block"
    "boxer-block"
    "image-compress"
    "boones-sortable-columns"
    "wp-disabler"
    "fancy-elements-for-avada"
    "woo-australia-fastway-shipping-method"
    "woo-omnifund-gateway"
    "tj-google-sitemaps-xml"
    "collaboration"
    "vimeo-badge-widget"
    "wp-version-tag-remover"
    "minerva-knowledge-base-lite"
    "turkish-captcha-enjoy"
    "mijnpress-hightraffic"
    "random-file-upload-names"
    "order-approval-by-customer-for-woocommerce"
    "simple-contact-widget"
    "lab404-related-posts"
    "wp-art-store"
    "pushover-notifications-for-jetpack"
    "propertyengine-real-estate"
    "st-email-backup-for-published-posts"
    "image-hover-effect-for-visual-composer"
    "secure-resizer"
    "backend-google-translate"
    "trustami-badge-for-customer-reviews-and-google-stars"
    "login-alert-notification"
    "jewelfit-virtual-jewellery-try-on"
    "hetjens-mediarss"
    "gamipress-wpachievements-importer"
    "widgplus-google-widget"
    "runkeeper-fitness-feed"
    "spreadsheet-paste-block"
    "lh-table-of-contents"
    "easycontent"
    "outranking"
    "addefend-easy-integration"
    "auto-translator-for-wpml-wpmlat"
    "proranktracker"
    "smart-shopify-product"
    "hizzle-downloads"
    "palto-carousel"
    "writing-prompt"
    "haxhitsplayer"
    "products-admin-notes-simple"
    "multiple-page-generator"
    "wp-math"
    "unified-login-error-messages"
    "sp-admin"
    "custom-categories-rss"
    "qtranslate-remove-one-language-menu-item"
    "pendig-reviews-dashboard-widget"
    "statcounter-popular-posts"
    "flexible-slide-to-top-accordion"
    "useful-tab-block-responsive-amp-compatible"
    "xtras-learndash"
    "easy-image-share"
    "wp-slider-captcha"
    "categories4page"
    "easy-reader"
    "galleria-javascript-gallery3-slideshow"
    "iterative-headlines"
    "comment-text"
    "credo-payment-forms"
    "rest-api-search"
    "ganohrs-toggle-shortcode"
    "better-utf8-excerpt"
    "money-space"
    "wp-syntax-effects"
    "event-importer-for-meetup-and-the-events-calendar"
    "church-post-types"
    "slash-comments"
    "wp-live-group-chat"
    "top-recent-commenters"
    "video-reviews"
    "rss-license"
    "rh-wp-property-feed"
    "smntcs-utilities"
    "featured-box"
    "dynamic-product-categories-design"
    "dsubscribers"
    "pressplay-lite"
    "bp-directory-views"
    "simple-shortcode-for-jw-player-7"
    "theme-roulette"
    "wp-nano-ad"
    "fslider"
    "wp-shkshell"
    "bluesnap-payments"
    "coschool"
    "cookieless-comments"
    "platformly"
    "google-visualization-charts"
    "f70-lead-document-download"
    "import-products-to-ok-ru"
    "woo-suggestion-engine"
    "disable-drop-cap"
    "wp-geoposts"
    "jellyreach"
    "crudlab-google-plus"
    "s3k-seo-meta-for-category-posts"
    "styble"
    "bbpress-support-forum-checked-by-default"
    "poetry"
    "movylo-widget"
    "intranet-restriction-for-posts-and-pages"
    "timelines"
    "wp-antispambot"
    "wp-maltor"
    "extra-settings-for-woocommerce"
    "woo-coupons-by-categories-and-tags"
    "gam-db-backup"
    "link-grab-o-matic"
    "davids-ultra-quicktags"
    "author-admin-view-archive-link"
    "a-sticky-note"
    "carbon-breadcrumbs"
    "references"
    "woo-paymaya-payment-gateway"
    "spotify-play-for-wordpress"
    "wp-breadcrumbs"
    "posts-per-page-customizer"
    "cf7-marketo-lite"
    "very-simple-google-map"
    "simple-keyword-to-link"
    "tree-nation-for-woocommerce"
    "child-page-tree"
    "menu-to-page-display"
    "wp-webservices"
    "blur-text"
    "we-testimonial-slider"
    "digioh"
    "zpp-widget"
    "wp-cloudflare-guard"
    "wp-wikipedia-excerpt"
    "embed-skype-button"
    "restricted-site-notifier"
    "jk-html-to-pdf"
    "acf-wysiwyg-styling"
    "disable-back-button"
    "wp-uploads-stats"
    "multisite-rest-api"
    "idx-connect-for-gravityforms"
    "manual-order"
    "terminflix"
    "minicomposer"
    "wp-image-mask"
    "pocket-wp"
    "wc-discord-invite"
    "acymailing-integration-for-uncanny-automator"
    "pagecat-list"
    "molongui-post-contributors"
    "followize"
    "ng-animated-slider"
    "delivery-date-system-for-woocommerce"
    "verofy-payment-gateway"
    "trepidation-mobile-head"
    "chat-for-aesop-story-engine"
    "wp-paymobile-content-locker"
    "wp-contributions"
    "forms-by-systemo"
    "squeeze"
    "wp-frequently-searched-words"
    "tuxedo-css-editor"
    "perfect-columns"
    "book-widget"
    "elements-buddy"
    "tag-to-link-jqueryrank-sculpting"
    "quizzes-for-buddypress"
    "self-sustaining-spam-stopper"
    "wp-snapshot"
    "basic-security"
    "password-for-wp"
    "formspammertrap-for-comments"
    "osmig-signup-plugin"
    "nuventech-ad-network"
    "hacklog-xiami"
    "nutrition-facts"
    "gf-excel-import"
    "wp-tab-anchors"
    "mdjm-google-calendar-sync"
    "hs-access"
    "weepay-payment-gateway-sanal-pos-modulu"
    "dokan-access-manager"
    "easy-digital-downloads-custom-favicon"
    "easy-repeater"
    "electric-studio-flickr-mosaic"
    "wgapiauth"
    "wp-blog"
    "multisite-system-cron"
    "product-quantity-dropdown-for-woocommerce"
    "amr-shortcodes"
    "twenty-thirteen-header-animations"
    "page-template-filter"
    "axedit-seasons"
    "rt-mega-menu"
    "vabe-button"
    "api2cart-webhook-helper"
    "optimizer-shortcodes-email"
    "custom-page-templates-setup"
    "buddypress-xprofile-validate-with-regex"
    "white-rabbit-suite"
    "ngp-forms"
    "wp-splashing-images"
    "follow-us-on-social-media"
    "dashboard-info"
    "sh-jobamatic"
    "product-weight"
    "revcent-payments"
    "wp-condition"
    "jaspreetchahals-wordpress-bot-detector-lite"
    "smntcs-simple-events-widget"
    "custom-shape-dividers"
    "emb3d-model-viewer"
    "ultimate-image-hover-effects"
    "dvla-search"
    "scroll-tool"
    "creative-elements-for-elementor"
    "coupon-maker"
    "get-user-info"
    "sandbox-payment-gateway"
    "hummgroup"
    "dashboard-for-pressbooks-h5p"
    "consensus-embed"
    "wp-reset-filters"
    "bp-gifts"
    "wordpress-file-backup"
    "lianlian-pay-for-woocommerce"
    "data-tables"
    "show-state-field-for-woocommerce"
    "default-twitter-image"
    "stupid-simple-qr"
    "stylish-order-form-builder"
    "dewa-kirim-woocommerce-gojek"
    "target-page-navigation"
    "sticky-notice"
    "extended-simple-history-for-beaver-builder"
    "ajax-load-more-by-bkker-theme"
    "wp-math-2"
    "imnicamail"
    "textcensor-for-articles"
    "vitepay"
    "display-site-numbers"
    "translator-with-baidu-service"
    "dfx-woo-role-changer"
    "ultimate-gdpr-consent"
    "the-ccpa-framework"
    "remove-web-field-from-comments-form"
    "self-shortener"
    "managedorg-product-driver"
    "repositoryzip"
    "free-click-to-chat-button-by-timelinesai"
    "contact-form-7-sequence-generator"
    "member-content-visibility"
    "wp-offload-s3-filter-image-file-types"
    "simple-ajax-pagination"
    "disable-dashboard-widgets"
    "recommend-referral-integration"
    "better-google-forms"
    "accessibility-font"
    "mjp-security-plugin"
    "inlinemanual"
    "integration-for-elementor-forms-cookies"
    "cookie-scanner"
    "wptimize"
    "wsklad"
    "wp-video-floater"
    "dynamic-text"
    "comprobante-de-pago-peru"
    "wuunder-for-woocommerce"
    "ldap-ad-staff-employee-directory-search"
    "google-locker"
    "tiger-form"
    "website-compare"
    "eventer"
    "prevent-skype-overwriting"
    "netflix-rss-feeder"
    "my-sites-sort-and-filter"
    "dashboard-search-memberpress"
    "wp-app-enabler"
    "buddypress-groups-autojoin-admins"
    "alex-syntax-highlighter"
    "restrict-dates-add-on-for-gravity-forms"
    "zibal-payment-gateway-for-easy-digital-downloads"
    "default-post-tags"
    "subpagelister"
    "disable-wp-core-updates-advance"
    "oqey-rss"
    "athlon-manage-calameo-publications"
    "visitors-notify"
    "gl-import-external-images"
    "up-sell-product-display-for-woocommerce"
    "crudlab-scroll-to-top"
    "sd-google-calendar-combiner"
    "testimonial-block"
    "admin-note"
    "colorizer"
    "voyage-plus"
    "gutenipsum"
    "adminbar-link-comments-to-pending"
    "woo-custom-profile-picture"
    "seo-backlinks-saver"
    "eclips-media-guard"
    "url-smasher"
    "churro"
    "ebi-pay"
    "estimate-delivery-per-product-for-woocommerce"
    "bh-related-post"
    "immotoolbox-connect"
    "wp-qoutes"
    "bacon-ipsum"
    "multidomain-support-for-elementor"
    "coding-blocks"
    "alt-text-generator-gpt-vision"
    "restrict-anonymous-access"
    "convertize"
    "wp-testimonial-block"
    "change-og-url-to-http"
    "dx-out-of-date"
    "link-icons"
    "discountify"
    "woo-nganluong-gateway"
    "build-trigger-gatsby"
    "lsd-google-maps-embedder"
    "media-modal"
    "disable-add-new-plugins"
    "wp-tour"
    "responsive-youtube-videos"
    "star-rate-for-administrators"
    "bse-jcc-payment-gateway-redirect"
    "wc-products-slider"
    "sensei-video-protection"
    "rhino-portfolio"
    "gruveo-call-button"
    "nutrition-facts-label"
    "wp-tuit"
    "syntaxhighlighter-evolved-yaml-brush"
    "civicrm-contribution-page-widget"
    "lite-syntax-highlighting"
    "realtime-comments"
    "zvi-callback-widget"
    "wparabic"
    "kblog-metadata"
    "dportfolio"
    "fix-reversed-comments-pagination"
    "add-code-to-rss"
    "bmail"
    "shipping-rate-by-cities"
    "wc-usaepay-payment-gateway"
    "custom-templates"
    "sendtonews-oembed"
    "layouts-importer"
    "always-valid-lightbox-mod"
    "hand-talk"
    "simple-changed-files"
    "fonetic-web-callback"
    "tdb-g-fonts-swap"
    "io-code-highlight"
    "lich-van-nien"
    "kakao-tam"
    "viet-nam-saleor-for-woocommerce"
    "bbpress-admin-replies"
    "dt-elementor-iconfont-library"
    "wupsales-reward-points-for-woocommerce"
    "men-quotes-on-women"
    "lj-random-or-recent"
    "eewee-admincustom"
    "manceppo-inbound-marketing"
    "gigl-delivery"
    "hide-edit-with-elementor"
    "sendbox-shipping"
    "wpmu-marketpress-allow-comments-addon"
    "wp-autoblog"
    "pal-digital-goods-express-checkout-for-woo"
    "custom-archives"
    "wp-campaign-manager"
    "fanbridge-toolbox"
    "shortburst-newsletter-sign-up"
    "wp-post-encode"
    "cf-civicrm-formprocessor"
    "openai-tools-for-wp-wc"
    "explore-pages"
    "floating-table-of-contents"
    "patternswp"
    "free-shipping-notice-for-woocommerce"
    "hetjens-expiration-date"
    "kindle-best-seller-calculator"
    "multimedia-comments"
    "team-master"
    "redirection-reporting"
    "wp-jqpuzzle"
    "slick-slideshow"
    "ai-content"
    "everypay-payment-gateway"
    "pushpanda-free-web-push-notifications"
    "attendance-management-for-lifterlms"
    "display-xenforo-node"
    "strx-zurb-css3-awesome-buttons"
    "nelio-forms"
    "redirect-link-format"
    "woocommerce-gateway-paytpv"
    "simpul-tweets-by-esotech"
    "wp-rss-cache-flusher"
    "link-exchange-lite"
    "hypernotes"
    "apricot-rocket-crm"
    "maxicharts-colors-add-on"
    "categorized"
    "hebrew-events-calendar"
    "vedicastroapi"
    "cf7-blocks"
    "wp-custom-admin-login-lite"
    "weather-grabber"
    "lastfm-recent-plays-wordpress-plugin"
    "neoforum"
    "automatic-page-load-progress-bar"
    "auto-slug"
    "migme"
    "captivate-by-smartasset"
    "anything-block"
    "use-innodb"
    "dolly"
    "pure-writing"
    "wp-multiple-titles"
    "koha-login-widget"
    "combat-comments-bot"
    "i-tell-you-what"
    "misterplan"
    "albumreviewer"
    "hcard-shortcode"
    "grouped-comments-widget"
    "digital-publishing"
    "extended-custom-post"
    "ninjateam-telegram"
    "google-knowledge-phone-number"
    "at-internet-analyzer-ii"
    "theme-junkie-features-content"
    "b-testimonial"
    "mimo-masonry"
    "generic-openid-connect"
    "offload-videos-bunny-netaws-s3"
    "bizreview"
    "category-gallery"
    "repeater-entries-widget"
    "profitshare"
    "web-font-display"
    "wp-nutrition-facts"
    "pressboard-stories"
    "goodbye-bar"
    "blogtimes"
    "widget-bumbablog-adserver"
    "free-customer-service-tools-by-openwidget"
    "basticom-framework"
    "ni-woocommerce-multi-currency-report"
    "last-video-widget"
    "download-monitor-page-addon-qr-code"
    "lovely-social-media-page-buttons"
    "gf-heidelpay"
    "farticles"
    "demo-importer-companion"
    "mail-mage"
    "pt-variants"
    "wc-load-more-product"
    "cartopress"
    "detect-search-engine-referrer"
    "st-category-wp"
    "testimonial-review"
    "floating-action-buttons"
    "lonely-sticky"
    "accordion-box"
    "livereload"
    "simcast"
    "ultimate-browser-specific-css"
    "responsive-images"
    "mailclient"
    "recommended-for-you"
    "bbp-views"
    "google-plus-page-shortcode"
    "integration-for-cardconnect-and-gravity-forms"
    "oembed-infogram"
    "imwptip"
    "mb-acf-migration"
    "best-splash"
    "click-to-call-for-twilio"
    "ultimate-conversion-tracking-code"
    "menu-tamer"
    "sugar-events-calendar-ninja-forms-add-on"
    "run-this"
    "actirise"
    "define-constants"
    "wplms-learnpress-migration"
    "widg-net-cookies"
    "cykelpartner-xml-products-viewer"
    "hetjens-feed-redirect"
    "auto-login-user-on-register"
    "my-affirmation"
    "woo-search-order-by-sku"
    "wc-welcome-message"
    "automatically-add-product-to-cart-after-visit-woocommerce"
    "a-ads"
    "sidebar-table-of-contents"
    "text-message-sms-extension-for-contact-form-7"
    "sherk-custom-post-type-displays"
    "ocean-contact-info"
    "mycred-zapier"
    "knvb-api"
    "wp-adsense-guard"
    "promo"
    "postbox-email-logs"
    "wubtitle"
    "addfunc-backgrounds"
    "sports-betting-odds"
    "blogger-title-fix"
    "mata-mayusculas"
    "flaming-password-reset"
    "shipox-for-woocommerce"
    "all-social-fw-style-widget"
    "functionscapacitor"
    "translatewise-chat"
    "wp-social-integrator"
    "wc-products-by-brands"
    "custom-advertisements-management"
    "kevinjohn-gallagher-pure-web-brilliants-social-graph-control"
    "hash-converter"
    "wp-sounds"
    "categorias-y-paginas-por-familia-y-profundidad"
    "bwl-advanced-faq-manager-lite"
    "videowalls-for-ziggeo"
    "checkout-field-visibility-for-woocommerce"
    "redirection-https-for-apache"
    "gallery-face-groups"
    "bulk-deactivate"
    "deliverea-shipping"
    "engaging-buttons"
    "epx-ecommerce"
    "epoi-wp-points-and-rewards"
    "bgstyle"
    "dt-directory-lite-addon"
    "media-toolkit"
    "frontify"
    "wp-currency-exchange-rates"
    "range-slider-contact-form-7-plus"
    "opace-essential-seo-toolkit"
    "custom-post-slider"
    "optio-dentistry"
    "remove-feed-links"
    "woodpecker"
    "days-until"
    "wpsupervisor-client"
    "source-view"
    "banner-introduction-slider"
    "atlasmic"
    "wp-restaumatic"
    "morepuzzles"
    "gg-infucaptcha-recaptcha-for-infusionsoft"
)

# Define user agents with weights
declare -A USER_AGENTS
USER_AGENTS=(
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"]=5
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"]=7
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"]=6
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36 Edg/91.0.864.54"]=5
    ["Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 OPR/77.0.4054.277"]=3
    ["Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (iPad; CPU OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Vivaldi/4.0"]=1
    ["Mozilla/5.0 (Android 11; Mobile; rv:68.0) Gecko/68.0 Firefox/88.0"]=1
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"]=15
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/534.36"]=12
)

CLOSED_PLUGINS_FILE="${WORDPRESS_WORKDIR}/closed_plugins.txt"
LAST_VERSION_FILE="${WORDPRESS_WORKDIR}/last_versions.txt"
PARALLEL_JOBS=1

DOWNLOAD_ALL_PLUGINS='n'
LIST_ONLY='n'
ALL_PLUGINS_FILE="${WORDPRESS_WORKDIR}/wp-plugin-svn-list.txt"

DELAY_DOWNLOADS='n'
DELAY_DURATION=5

FORCE_UPDATE='n'
CACHE_ONLY='n'

mkdir -p "$WORDPRESS_WORKDIR" "$MIRROR_DIR" "$LOGS_DIR"
DEBUG_MODE=0

while getopts "p:dalD:t:fc" opt; do
    case ${opt} in
        p ) PARALLEL_JOBS=$OPTARG ;;
        d ) DEBUG_MODE=1 ;;
        a ) DOWNLOAD_ALL_PLUGINS='y' ;;
        l ) LIST_ONLY='y' ;;
        D ) DELAY_DOWNLOADS=$OPTARG ;;
        t ) DELAY_DURATION=$OPTARG ;;
        f ) FORCE_UPDATE='y' ;;
        c ) CACHE_ONLY='y' ;;    # New option for cache-only
        \? ) echo "Usage: $0 [-p PARALLEL_JOBS] [-d] [-a] [-l] [-D DELAY_DOWNLOADS] [-t DELAY_DURATION] [-f] [-c]" 1>&2; exit 1 ;;
    esac
done

debug_log() {
    if [ "$DEBUG_MODE" -eq 1 ]; then
        echo "[DEBUG] $1" >&2
    fi
}

get_random_user_agent() {
    echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
}

get_latest_version_and_download_link() {
    local plugin=$1
    debug_log "Checking latest version and download link for $plugin"
    
    local api_url="https://api.wordpress.org/plugins/info/1.0/${plugin}.json"
    local user_agent=$(get_random_user_agent)
    local api_response=$(curl -s -H "User-Agent: $user_agent" "$api_url")
    
    if echo "$api_response" | jq -e '.error' >/dev/null; then
        local error_message=$(echo "$api_response" | jq -r '.error')
        if [ "$error_message" = "closed" ]; then
            echo "closed"
            return 2
        else
        echo "Error: $error_message for plugin $plugin" >&2
        return 1
        fi
    fi
    
    local version=$(echo "$api_response" | jq -r '.version // empty')
    local download_link=$(echo "$api_response" | jq -r '.download_link // empty')
    
    if [ -n "$version" ] && [ -n "$download_link" ]; then
        echo "$version $download_link"
        return 0
    else
        echo "Error: Cannot fetch version or download link for $plugin" >&2
        return 1
    fi
}

download_plugin() {
    local plugin=$1
    local version=$2
    local api_download_link=$3
    local output_file="${MIRROR_DIR}/${plugin}.${version}.zip"
    local header_file="${LOGS_DIR}/${plugin}.${version}.headers"
    local constructed_download_link="${DOWNLOAD_BASE_URL}/${plugin}.${version}.zip"
    local download_link

    if [ "$DEBUG_MODE" -eq 1 ]; then
        debug_log "API-provided download link for $plugin: $api_download_link"
        debug_log "Constructed download link for $plugin: $constructed_download_link"
    fi

    if [ "$DOWNLOAD_LINK_API" == 'y' ] && [ -n "$api_download_link" ]; then
        download_link="$api_download_link"
        debug_log "Using API-provided download link for $plugin: $download_link"
    else
        download_link="$constructed_download_link"
        debug_log "Using constructed download link for $plugin: $download_link"
    fi

    debug_log "Downloading $plugin version $version through Cloudflare Worker"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)
    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o /dev/null "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    else
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o "$output_file" "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    fi

    if [ $? -eq 0 ]; then
        if [ "$CACHE_ONLY" == 'y' ]; then
            debug_log "Plugin $plugin version $version cached successfully."
            return 0
        fi

        local file_size=$(stat -c%s "$output_file")
        if [ "$file_size" -lt 1000 ]; then
            echo "Error: Downloaded file for $plugin is too small (${file_size} bytes). Possible download issue." >&2
            return 1
        fi

        local source=$(grep -i "X-Source:" "$header_file" | cut -d' ' -f2 | tr -d '\r')
        if [ "$source" == "R2" ]; then
            debug_log "Successfully downloaded $plugin version $version from R2 storage"
        elif [ "$source" == "WordPress" ]; then
            debug_log "Successfully downloaded $plugin version $version from WordPress"
            debug_log "R2 bucket saving for plugin zip occurred"
        else
            debug_log "Skipped download for $plugin $version zip (already exists locally)"
        fi

        return 0
    else
        echo "Error: Failed to download $plugin version $version" >&2
        return 1
    fi
}

save_plugin_info() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.json"

    debug_log "Saving plugin json metadata for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying metadata download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    if [ "$CACHE_ONLY" == 'y' ]; then
        # When in cache-only mode, output to /dev/null
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin metadata for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache json metadata for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            if [ "$source" = "R2" ]; then
                debug_log "json metadata for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "json metadata for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin json occurred"
            else
                debug_log "json metadata for $plugin version $version saved (json metadata file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save json metadata for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

fetch_and_save_checksums() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.checksums.json"

    debug_log "Fetching and saving checksums for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying checksums download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    debug_log "Sending request to Worker for checksums: CF_WORKER_URL?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"

    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin checksums for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache checksums for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        debug_log "Received response with status code: $status_code"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            debug_log "Response source: $source"
            if [ "$source" = "R2" ]; then
                debug_log "Checksums for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "Checksums for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin checksums occurred"
            else
                debug_log "Checksums for $plugin version $version saved (checksums file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save checksums for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

process_plugin() {
    local plugin=$1

    # Check if the plugin is already known to be closed
    if grep -q "^$plugin$" "$CLOSED_PLUGINS_FILE" 2>/dev/null; then
        echo "Plugin $plugin is known to be closed. Skipping."
        return 0
    fi

    echo "Processing plugin: $plugin"

    VERSION_AND_LINK=$(get_latest_version_and_download_link "$plugin")
    local version_check_status=$?
    
    if [ $version_check_status -eq 1 ]; then
        echo "Skipping $plugin due to version fetch error."
        return 1
    elif [ $version_check_status -eq 2 ]; then
        echo "Plugin $plugin is closed. Skipping download and processing."
        echo "$plugin" >> "$CLOSED_PLUGINS_FILE"
        if save_plugin_info "$plugin" "closed"; then
            debug_log "Successfully saved json metadata for closed plugin $plugin."
        else
            debug_log "Failed to save json metadata for closed plugin $plugin."
        fi
        return 0
    fi
    
    LATEST_VERSION=$(echo "$VERSION_AND_LINK" | cut -d' ' -f1)
    API_DOWNLOAD_LINK=$(echo "$VERSION_AND_LINK" | cut -d' ' -f2-)

    debug_log "Latest version for $plugin: $LATEST_VERSION"
    debug_log "API download link for $plugin: $API_DOWNLOAD_LINK"

    STORED_VERSION=$(grep "^$plugin" "$LAST_VERSION_FILE" | awk '{print $2}')
    debug_log "Stored version for $plugin: $STORED_VERSION"

    if [ "$CACHE_ONLY" != 'y' ] && [ "$LATEST_VERSION" == "$STORED_VERSION" ] && [ -f "${MIRROR_DIR}/${plugin}.${LATEST_VERSION}.zip" ]; then
        echo "$plugin is up-to-date and exists in mirror directory. Skipping download..."
    else
        start_time=$(date +%s.%N)

        if download_plugin "$plugin" "$LATEST_VERSION" "$API_DOWNLOAD_LINK"; then
            if [ "$CACHE_ONLY" != 'y' ]; then
                sed -i "/^$plugin/d" "$LAST_VERSION_FILE"
                echo "$plugin $LATEST_VERSION" >> "$LAST_VERSION_FILE"
            fi
            echo "Successfully processed $plugin."
        else
            echo "Error: Failed to process $plugin." >&2
        fi

        end_time=$(date +%s.%N)
        duration=$(echo "$end_time - $start_time" | bc)
        printf "Time taken for %s: %.4f seconds\n" "$plugin" "$duration"
    fi

    if save_plugin_info "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully saved json metadata for $plugin."
    else
        debug_log "Failed to save json metadata for $plugin."
    fi

    if fetch_and_save_checksums "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully fetched and saved checksums for $plugin."
    else
        debug_log "Failed to fetch and save checksums for $plugin."
    fi
}

populate_all_plugins() {
    if [ ! -f "$ALL_PLUGINS_FILE" ] || [ "$LIST_ONLY" == 'y' ]; then
        echo "Fetching list of all WordPress plugins..."
        svn list https://plugins.svn.wordpress.org/ | sed 's/\/$//g' > "$ALL_PLUGINS_FILE"
        plugin_count=$(wc -l < "$ALL_PLUGINS_FILE")
        echo "Plugin list (${plugin_count}) saved to $ALL_PLUGINS_FILE"
    fi
    
    if [ "$LIST_ONLY" == 'n' ]; then
        ALL_PLUGINS=()
        while IFS= read -r line; do
            ALL_PLUGINS+=("$line")
        done < "$ALL_PLUGINS_FILE"
        echo "Loaded ${#ALL_PLUGINS[@]} plugins."
    fi
}

if [ "$LIST_ONLY" == 'y' ]; then
    populate_all_plugins
    echo "Plugin list created. Exiting without downloading."
    exit 0
fi

if [ "$DOWNLOAD_ALL_PLUGINS" == 'y' ]; then
    populate_all_plugins
    COMBINED_PLUGINS=("${ALL_PLUGINS[@]}")
else
    if [ ! -d "$PLUGIN_DIR" ]; then
        echo "Warning: Plugin directory $PLUGIN_DIR does not exist or is invalid."
        PLUGIN_LIST=()
    else
        PLUGIN_LIST=($(ls -d "$PLUGIN_DIR"/*/ 2>/dev/null | xargs -n 1 basename))

        if [ ${#PLUGIN_LIST[@]} -eq 0 ]; then
            echo "No plugins found in $PLUGIN_DIR."
        fi
    fi

    COMBINED_PLUGINS=(${PLUGIN_LIST[@]} ${ADDITIONAL_PLUGINS[@]})
    COMBINED_PLUGINS=($(echo "${COMBINED_PLUGINS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
fi

if [ ${#COMBINED_PLUGINS[@]} -eq 0 ]; then
    echo "No plugins to download. Exiting."
    exit 0
fi

mkdir -p "$MIRROR_DIR"
touch "$LAST_VERSION_FILE"

if [ "$PARALLEL_JOBS" -gt 1 ]; then
    echo "Running in parallel with $PARALLEL_JOBS jobs..."
    # First, export all variables including USER_AGENTS
    export DOWNLOAD_BASE_URL MIRROR_DIR LAST_VERSION_FILE DEBUG_MODE DOWNLOAD_LINK_API LOGS_DIR ALL_PLUGINS_FILE DOWNLOAD_ALL_PLUGINS LIST_ONLY CF_WORKER_URL DELAY_DOWNLOADS DELAY_DURATION FORCE_UPDATE CACHE_ONLY USER_AGENTS

    # Then, export the functions
    export -f process_plugin get_latest_version_and_download_link download_plugin debug_log populate_all_plugins save_plugin_info get_random_user_agent fetch_and_save_checksums
    printf "%s\n" "${COMBINED_PLUGINS[@]}" | xargs -P $PARALLEL_JOBS -I {} bash -c 'process_plugin "$@"' _ {}
else
    for plugin in "${COMBINED_PLUGINS[@]}"; do
        process_plugin "$plugin"
    done
fi

if [ -f "$CLOSED_PLUGINS_FILE" ]; then
    echo
    echo "Closed Plugin List:"
    cat "$CLOSED_PLUGINS_FILE" | sort | uniq || true
    echo
    echo "Total closed plugins: $(wc -l < "$CLOSED_PLUGINS_FILE")"
    echo
else
    echo
    echo "No closed plugins found."
    echo
fi
echo "Plugin download process completed."
