#!/bin/bash

# Base directory (script location)
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Configurable directories
WORDPRESS_WORKDIR="${WORDPRESS_WORKDIR:-$BASE_DIR/wordpress-plugins}"
PLUGIN_DIR="${PLUGIN_DIR:-$BASE_DIR/wp-content/plugins}"
MIRROR_DIR="${MIRROR_DIR:-$BASE_DIR/mirror}"
LOGS_DIR="${LOGS_DIR:-$BASE_DIR/plugin-logs}"

# Check for CF_WORKER_URL environment variable
if [ -z "$CF_WORKER_URL" ]; then
    echo "Error: CF_WORKER_URL environment variable is not set." >&2
    exit 1
fi

DOWNLOAD_BASE_URL="https://downloads.wordpress.org/plugin"

# Other variables
DOWNLOAD_LINK_API='y'

ADDITIONAL_PLUGINS=(
    "cryptocurrency-widgets-pack"
    "woo-products-slider-pro"
    "hashtagger"
    "aitasi-coming-soon"
    "360-product-rotation"
    "woo-button-text"
    "xslt"
    "yatra"
    "subscribe-remind"
    "jomres"
    "wc-builder"
    "wp-pdf-generator"
    "vertical-scroll-image-slideshow-gallery"
    "hierarchical-pages"
    "easy-paypal-shopping-cart"
    "analytics-spam-blocker"
    "youtube-simple-gallery"
    "responsify-wp"
    "skroutz-analytics-woocommerce"
    "fullworks-anti-spam"
    "wp-search-insights"
    "trustedsite"
    "favicon-generator"
    "cronjob-scheduler"
    "premmerce"
    "akfeatured-post-widget"
    "yext"
    "keyy"
    "woo-gerencianet-official"
    "hierarchical-html-sitemap"
    "falcon"
    "all-in-one-slideshow"
    "page-in-widget"
    "simple-colorbox"
    "real-time-bitcoin-currency-converter"
    "first-order-discount-woocommerce"
    "collapsing-pages"
    "wp-cleanup"
    "wp-remove-query-strings-from-static-resources"
    "readers-from-rss-2-blog"
    "genesis-club-lite"
    "newsletter2go"
    "read-more"
    "qr-redirector"
    "pdf-and-ppt-viewer"
    "flexible-frontend-login"
    "tc-logo-slider"
    "nomad-world-map"
    "qr-code-composer"
    "comment-image"
    "page-as-subdomain-lite"
    "ldd-directory-lite"
    "extrawatch-pro"
    "thumbnail-crop-position"
    "grid"
    "standard-widget-extensions"
    "giga-slider"
    "disable-media-sizes"
    "market-exporter"
    "hide-categories-on-shop-page"
    "memcached-redux"
    "memcached-is-your-friend"
    "rich-event-timeline"
    "duplicate-posts-erazer"
    "shipworks-e-commerce-bridge"
    "cf7-telegram"
    "affiliatewp-affiliate-area-shortcodes"
    "skype-master"
    "customize-twenty-seventeen"
    "pixgridder"
    "garden-gnome-package"
    "addonify-quick-view"
    "preserved-html-editor-markup"
    "wc-shippo-shipping"
    "hero-banner-ultimate"
    "mpdf-addon-for-pdf-invoices"
    "wp-image-size-limit"
    "filter-gallery"
    "debug-bar-constants"
    "helper-lite-for-pagespeed"
    "woo-mp"
    "featured-post"
    "contact-me-widget"
    "upcoming-events-lists"
    "wp-autoupdates"
    "uix-shortcodes"
    "currency-switcher"
    "recent-comments-plugin"
    "subscribe-plugin"
    "routeapp"
    "auto-ping-booster"
    "orion-sms-otp-verification"
    "ecommerce-extra"
    "vc-simple-all-responsive"
    "business-manager"
    "mainwp-key-maker"
    "stampedio-product-reviews"
    "buddypress-wall"
    "admin-tools"
    "woocommerce-dropdown-cart"
    "dino-game"
    "seo-image-alt-tags"
    "jquery-vertical-scroller"
    "layouts-for-elementor"
    "gianism"
    "disable-wpautop"
    "wpsocialite"
    "admin-slug-column"
    "hpbseo"
    "content-excel-importer"
    "evento"
    "captcha-them-all"
    "image-slider-with-description"
    "bugherd"
    "custom-content-portfolio"
    "rss-news-display"
    "super-block-slider"
    "employee-directory"
    "social-buttons-pack"
    "unattach"
    "wc-paymongo-payment-gateway"
    "wp-reading-progress"
    "sight"
    "pardakht-delkhah"
    "myfatoorah-woocommerce"
    "whols"
    "amo-team-showcase"
    "admin-page-spider"
    "ninja-signature-contract-forms-add-on"
    "ip-based-login"
    "payplus-payment-gateway"
    "woo-shipping-dpd-baltic"
    "wpc-show-single-variations"
    "cbnet-favicon"
    "tinywp-mobile-detect"
    "checkout-for-paypal"
    "customerly"
    "easy-primary-category"
    "registration-form-widget"
    "wordpress-connect"
    "mapster-wp-maps"
    "hw-image-widget"
    "advanced-custom-fields-nextgen-gallery-field-add-on"
    "wpsso-ratings-and-reviews"
    "wp-useragent"
    "smart-countdown-fx"
    "christmas-greetings"
    "smaily-for-wp"
    "cp-polls"
    "video-tab-for-woocommerce"
    "raw-html-snippets"
    "aforms-form-builder-for-price-calculator-cost-estimation"
    "wc-external-product-new-tab"
    "wp-likes"
    "advanced-lazy-load"
    "event-tickets-manager-for-woocommerce"
    "shopbuilder"
    "organic-widget-area-block"
    "shortcodes-to-show-or-hide-content"
    "list-all-urls"
    "olark-live-chat"
    "footnotes-made-easy"
    "linguise"
    "geolocation"
    "keycaptcha"
    "social-links"
    "pareto-security"
    "upload-url-path-enabler"
    "wc-multiple-email-recipients"
    "checkout-address-autofill-for-woocommerce"
    "woocommerce-custom-currencies"
    "add-to-calendar-button"
    "tainacan"
    "live-blogging"
    "wordpress-plugin-random-post-slider"
    "wp-plugin-info-card"
    "nova-blocks"
    "woocommerce-and-1centerprise-data-exchange"
    "tangible-loops-and-logic"
    "sitekit"
    "facebook-wall-and-social-integration"
    "wp-plugin-dependencies"
    "currency-converter-widget"
    "custom-category-template"
    "stockdio-historical-chart"
    "lite-cache"
    "pitchprint"
    "ui-for-wp-simple-paypal-shopping-cart"
    "auto-seo"
    "photoshelter-official-plugin"
    "disable-responsive-images-complete"
    "htaccess"
    "url-coupons-for-woocommerce-by-algoritmika"
    "import-to-photo-gallery-from-nextgen-gallery"
    "disable-user-gravatar"
    "network-subsite-user-registration"
    "good-old-gallery"
    "xili-dictionary"
    "mass-email-to-users"
    "shortcodes-for-buddypress"
    "links-auto-replacer"
    "mobile-app"
    "cf7-redirection"
    "standout-css3-buttons"
    "activity-log-gravity-forms"
    "visitor-stats-widget"
    "simple-dropbox-upload-form"
    "lws-affiliation"
    "quick-search"
    "multiple-products-to-cart-for-woocommerce"
    "simple-css-for-widgets"
    "woo-pagseguro-parceled"
    "avatar-privacy"
    "phplist-form-integration"
    "all-in-one-wp-builder"
    "einsatzverwaltung"
    "avatar"
    "admin-category-filter"
    "wp-favicon"
    "background-update-tester"
    "404-simple-redirect"
    "stax"
    "disable-users"
    "nofollow-case-by-case"
    "bxslider-integration"
    "3dprint-lite"
    "accessibility-widget"
    "very-simple-knowledge-base"
    "wpnextpreviouslink"
    "popup-wp"
    "wp-flipclock"
    "widget-logic-visual"
    "tabify-edit-screen"
    "vivawallet-woocommerce-gateway"
    "affiliaa-affiliate-program-with-mlm"
    "bp-group-management"
    "the-pack-addon"
    "raychat"
    "ajax-comment-preview"
    "bulk-attachment-download"
    "my-auctions-allegro-free-edition"
    "2mb-autocode"
    "activate-update-services"
    "wp-hotel-booking-woocommerce"
    "cache-performance"
    "translate"
    "wp-hosting-performance-check"
    "es-woocommerce-activecampaign"
    "wordpress-theme-demo-bar"
    "wp-image-slideshow"
    "wordpress-link-directory"
    "robo-maps"
    "santas-christmas-countdown"
    "integrate-convertkit-wpforms"
    "rv-embed-pdf"
    "user-activation-keys"
    "wp-publication-archive"
    "youtube-subscribe-widget"
    "pg-simple-affiliate-shop"
    "persian-font"
    "temporary-login"
    "visual-products-configurator-for-woocommerce"
    "syntaxhighlighter-plus"
    "catch-sticky-menu"
    "wp-anti-clickjack"
    "woo-coming-soon"
    "cart66-cloud"
    "slider-revolution-search-replace"
    "woo-add-gtin"
    "wordpress-meta-keywords"
    "random-image-selector"
    "wp-payeezy-pay"
    "jps-get-rss-feed"
    "wpc-badge-management"
    "most-popular-tags"
    "html-special-characters-helper"
    "supersaas-appointment-scheduling"
    "hide-categories-or-products-on-shop-page"
    "quote-comments"
    "gravitec-net-web-push-notifications"
    "qode-wishlist-for-woocommerce"
    "cloudimage"
    "woocommerce-login-popup-and-shortcodes"
    "buddypress-registration-groups-1"
    "inline-tweet-sharer"
    "woo-custom-fields-for-variation"
    "nextgen-flex-slider-template"
    "wc-category-showcase"
    "easy-portfolio"
    "wordpress-mu-sitewide-tags"
    "streamweasels-twitch-integration"
    "friends"
    "many-tips-together"
    "surbma-gdpr-proof-google-analytics"
    "simplepress"
    "unlimited-elementor-inner-sections-by-boomdevs"
    "export-to-blogger"
    "crowdsec"
    "flawless-themes-demo-importer"
    "chat-me-now"
    "woo-wallee"
    "wonderpush-web-push-notifications"
    "webtoffee-product-feed"
    "accordion-toggle"
    "elex-request-a-quote"
    "woocommerce-role-pricing"
    "easy-youtube-subscribe"
    "shortcode"
    "frontend-dashboard-templates"
    "thin-out-revisions"
    "cielo-woocommerce"
    "post-list-featured-image"
    "elex-product-price-custom-text-before-after-text-and-discount-for-woocommerce"
    "unbloater"
    "auto-submenu"
    "softaculous"
    "kvcore-idx"
    "remove-taxonomy-base-slug"
    "embed-office-viewer"
    "more-types"
    "wp-anything-downloader"
    "weather-master"
    "quicklink"
    "sitelock"
    "crypto-converter-widget"
    "options-for-twenty-nineteen"
    "wip-woocarousel-lite"
    "simple-sales-tax"
    "ultimate-woocommerce-brands"
    "algori-image-video-slider"
    "xmas-snow"
    "pomo-editor"
    "open-menu"
    "triberr-wordpress-plugin"
    "sociable-zyblog-edition"
    "badge-management-for-woocommerce"
    "heateor-open-graph-meta-tags"
    "custom-meta"
    "getpaid-stripe-payments"
    "crafthemes-demo-import"
    "simple-ads-txt"
    "wp-migration-for-onamaecom"
    "listdom"
    "min-and-max-quantity-for-woocommerce"
    "wc-peach-payments-gateway"
    "coneblog-widgets"
    "simple-meta-tags"
    "dco-insert-analytics-code"
    "contact-form-newsletter"
    "voting-platform-feelbacks"
    "miniorange-oauth-20-server"
    "liquid-blocks"
    "flickr-set-slideshows"
    "simple-mathjax"
    "faq-for-woocommerce"
    "vice-versa"
    "rock-content"
    "change-case-for-tinymce"
    "layouts-for-wpbakery"
    "bmo-expo"
    "anythingslider-for-wordpress"
    "theatre"
    "popcashnet-code-integration-tool"
    "add-featured-image-to-rss-feed"
    "search-live"
    "games"
    "acf-autosize"
    "blog-copier"
    "sliding-panel"
    "delivery-drivers-for-woocommerce"
    "wp-copy-protect"
    "wp-base-booking-of-appointments-services-and-events"
    "simple-post-views-count"
    "wp-thumb"
    "wc-multi-currency"
    "slidely-slideshows-embed"
    "gtm-server-side"
    "cartpauj-register-captcha"
    "wp-notes-widget"
    "grid-columns"
    "gator-cache"
    "sem-bookmark-me"
    "spots"
    "ns-category-widget"
    "google-webfont-optimizer"
    "linker"
    "ghost"
    "attribute-stock-for-woocommerce"
    "fv-gravatar-cache"
    "qyrr-code"
    "easy-remove-item-menu"
    "language-fallback"
    "future-posts-calendar"
    "custom-posts-per-page"
    "activedemand"
    "object-sync-for-salesforce"
    "wp-fastest-site-search"
    "wp-phpbb-bridge"
    "cryptocurrency-payments-using-metamask-for-woocommerce"
    "personal-favicon"
    "scrolling-social-sharebar"
    "commons-in-a-box"
    "reactpress"
    "airplane-mode"
    "wp-keyword-suggest"
    "button-block"
    "decalog"
    "ilovepdf"
    "my-bootstrap-menu"
    "seo-slider"
    "accordion-shortcode"
    "wp-appkit"
    "smartling-connector"
    "review-builder"
    "post-tiles"
    "hide-featured-image-on-all-single-pagepost"
    "treepress"
    "staatic"
    "cubewp-forms"
    "pjw-mime-config"
    "pingler-v10"
    "simply-rets"
    "artiss-currency-converter"
    "blue-captcha"
    "dark-mode-for-wp-dashboard"
    "customer-email-verification-for-woocommerce"
    "ajax-load-more-for-acf"
    "yoo-slider"
    "sb-login"
    "bc-woo-custom-thank-you-pages"
    "woolab-ic-dic"
    "thumbnails"
    "featured-galleries"
    "estimated-delivery-for-woocommerce"
    "wp-post-styling"
    "product-share"
    "team-view"
    "pryc-wp-add-custom-content-to-bottom-of-post"
    "fancy-coming-soon-maintenance-mode"
    "wow-media-library-fix"
    "zbplayer"
    "eleganto-advanced-sections"
    "redux-developer-mode-disabler"
    "ele-blog"
    "utubevideo-gallery"
    "social-widget"
    "zalomeni"
    "mpress-hide-from-search"
    "fresh-forms-for-gravity"
    "buddypress-extended-friendship-request"
    "real-estate-manager"
    "astra-theme-visual-hooks"
    "post-timeline"
    "cookiehub"
    "utf-8-db-converter"
    "chatbot-chatgpt"
    "hide-updates"
    "buddycommerce"
    "wpdatatables-forminator"
    "qa-heatmap-analytics"
    "wp-popular-posts-tool"
    "extra-product-options-for-woocommerce"
    "content-text-slider-on-post"
    "woocommerce-extra-fee-option"
    "category-subcategory-list-widget"
    "void-elementor-whmcs-elements"
    "auto-attachments"
    "page-optimize"
    "nota-fiscal-eletronica-woocommerce"
    "dash-notifier"
    "events-manager-wpml"
    "slider-block"
    "event-calendar-newsletter"
    "cp-image-store"
    "widget-visibility-without-jetpack"
    "google-fonts-for-woo-framework"
    "bangla-web-fonts"
    "wpazure-kit"
    "currency-per-product-for-woocommerce"
    "flatty-flat-admin-theme"
    "cf7-message-filter"
    "wprealestate"
    "admin-and-client-message-after-order-for-woocommerce"
    "woocommerce-product-fees"
    "wp-simple-mail-sender"
    "mshop-npay"
    "contact-form-7-autoresponder-addon-plugin"
    "unplug-jetpack"
    "de-updraftplus-backup-exclude-image-thumbnails"
    "media-search-enhanced"
    "product-specifications"
    "sportspress-for-basketball"
    "css"
    "advanced-google-translate"
    "thumbnail-grid"
    "sidebartabs"
    "sogo-accessibility"
    "verify-domain-for-apple-pay-with-stripe"
    "add-code-to-head"
    "daddy-plus"
    "mywebtonet-performancestats"
    "givewp-donation-widgets-for-elementor"
    "gelato-integration-for-woocommerce"
    "wishsuite"
    "anchor-episodes-index"
    "vr-visitas"
    "wpc-product-options"
    "privilege-menu"
    "wpc-linked-variation"
    "disable-variable-product-price-range"
    "woo-payment-gateway-officeguy"
    "groups-404-redirect"
    "woo-3d-viewer"
    "skysa-official"
    "simple-membership-form-shortcode"
    "random-image-gallery-with-fancy-zoom"
    "order-on-mobile-for-woocommerce"
    "nextgen-cooliris-gallery"
    "simple-masonry-gallery"
    "seo-meta-tags"
    "easy-retweet"
    "make-builder"
    "wc-minimum-order-amount"
    "cf7-antispam"
    "24liveblog"
    "reply-to"
    "integration-for-elementor-forms-sendinblue"
    "mowomo-redes-sociales"
    "custom-link-widget"
    "blox-lite"
    "featured-page-widget"
    "woo-bulk-price-update"
    "profitori"
    "the-simplest-favicon"
    "fb-messenger-livechat"
    "propovoice"
    "hester-core"
    "asynchronous-javascript"
    "right-click-disable-orignal"
    "responder"
    "social-boost"
    "bp-activity-filter"
    "a3-portfolio"
    "advance-wc-analytics"
    "get-post-list-with-thumbnails"
    "conditional-woo-checkout-field"
    "add-linked-images-to-gallery-v01"
    "best-logo-slider"
    "cookie-notice-and-consent-banner"
    "analytics-tracker"
    "embed-google-map"
    "foxyshop"
    "soundcloud-ultimate"
    "easy-gallery-slider"
    "webdzier-companion"
    "yumpu-epaper-publishing"
    "codeflavors-floating-menu"
    "shipit"
    "inspiry-memberships"
    "spider-random-post"
    "wp-snow"
    "wp-protect-content"
    "pages-posts"
    "pressable-automated-migration"
    "gostats-for-wordpress"
    "ketchup-shortcodes-pack"
    "disable-plugin-autoupdate-emails"
    "simple-sticky-header-on-scroll"
    "pw-woocommerce-exclude-free-shipping"
    "wp-login-and-logout-redirect"
    "disable-block-editor-fullscreen-mode"
    "certificate-customizer-for-tutor-lms"
    "devices-elementor"
    "remove-jquery-migrate"
    "custom-price-for-woocommerce"
    "bbpress-enable-tinymce-visual-tab"
    "critical-css-for-wp"
    "wp-photo-sphere"
    "apaczka"
    "quick-download-button"
    "cf7-popups"
    "instant-breadcrumbs"
    "permalink-manager-for-woocommerce"
    "chatbro"
    "inactive-user-deleter"
    "cm-header-footer-script-loader"
    "facebook-fan-page-widget"
    "wp-cors"
    "woo-rave"
    "language-switcher-for-elementor"
    "easy-slider-revolution"
    "custom-post-order-category"
    "jquery-post-splitter"
    "pushover-for-woocommerce"
    "robotstxt-rewrite"
    "ele-conditions"
    "page-title-splitter"
    "simple-twitter-widget"
    "academic-bloggers-toolkit"
    "wp-copysafe-pdf"
    "woo-reviews-by-wiremo"
    "restaurant-cafe-addon-for-elementor"
    "font-burner-control-panel"
    "ninja-gdpr-compliance"
    "cf7-google-map"
    "estatik-mortgage-calculator"
    "wp-greet"
    "aryo-widget-device"
    "simple-testimonials-showcase"
    "editor-full-width"
    "floating-ads-bottom"
    "formlift"
    "baap-mobile-version"
    "woo-retailcrm"
    "bbpress-post-topics"
    "wp-user-groups"
    "post-custom-templates-lite"
    "enable-cors"
    "pagely-multiedit"
    "rest-api-toolbox"
    "cm-email-blacklist"
    "imagemagick-sharpen-resized-images"
    "multisite-cloner"
    "android-50-lollipop-status-bar-customiser"
    "wp-bannerize-pro"
    "wpzoom-video-popup-block"
    "wp-post-expires"
    "vooplayer"
    "odlinks"
    "sociality"
    "geographical-redirect"
    "wc-gsheetconnector"
    "easy-chart-builder"
    "awesome-wp-image-gallery"
    "navigation-menu-as-dropdown-widget"
    "events-made-easy-frontend-submit"
    "cyan-backup"
    "change-author"
    "debug-log-manager"
    "booqable-rental-reservations"
    "mihdan-yandex-turbo-feed"
    "gsheetconnector-for-elementor-forms"
    "wc-shipping-packages"
    "piwik-pro"
    "seraphinite-post-docx-source"
    "broadstreet"
    "cookie-cat"
    "social-sharing-buttons"
    "menu-in-post"
    "ilmenite-cookie-consent"
    "disable-generate-thumbnails"
    "banner-upload"
    "arconix-flexslider"
    "woocommerce-cart-stock-reducer"
    "quick-box-popup"
    "mailster"
    "random-image-gallery-with-pretty-photo-zoom"
    "strx-magic-floating-sidebar-maker"
    "checkout-com-unified-payments-api"
    "easyappointments"
    "autoship-cloud"
    "multisite-global-search"
    "irobotstxt-seo"
    "tabs-shortcode"
    "modal-block"
    "banhammer"
    "agile-crm-lead-management"
    "booking-and-rental-system-woocommerce"
    "surbma-yoast-breadcrumb-shortcode"
    "woo-out-of-stock-products"
    "fluent-security"
    "mpl-publisher"
    "simple-google-calendar-widget"
    "realhomes-currency-switcher"
    "image-gallery-block"
    "responsive-horizontal-vertical-and-accordion-tabs"
    "storefront-add-slider"
    "mb-rest-api"
    "post-type-converter"
    "sync-post-with-other-site"
    "wp-whydonate"
    "add-lightbox-title"
    "acf-typography-field"
    "wp-frontend-delete-account"
    "user-export-with-their-meta-data"
    "tripay-payment-gateway"
    "portfolio-manager-powered-by-behance"
    "jet-event-system-for-buddypress"
    "checkout-countdown-for-woocommerce"
    "buddymeet"
    "bp-activity-plus-reloaded"
    "online-lesson-booking-system"
    "admin-customizer"
    "themehigh-multiple-addresses"
    "related-products-manager-woocommerce"
    "wp-widget-in-navigation"
    "ethpress"
    "wp-stripe-donation"
    "wp-theme-changelogs"
    "dashboard-commander"
    "cookiepro"
    "google-news-sitemap-feed-with-multisite-support"
    "team-rosters"
    "webengage"
    "swifty-bar"
    "horizontal-scroll-image-slideshow"
    "max-image-size-control"
    "fancy-product-designer-rest-api"
    "sociofluid"
    "links-with-icons-widget"
    "hacklog-remote-image-autosave"
    "userlike"
    "debug-log-config-tool"
    "dropshipping-xox"
    "rss-digest"
    "next-page-not-next-post"
    "transmail"
    "pdf-thumbnails"
    "newsplugin"
    "luckywp-acf-menu-field"
    "quick-bulk-post-page-creator"
    "surge"
    "appbanners"
    "cookie-information-consent-solution"
    "sar-friendly-smtp"
    "ubigeo-peru"
    "transportersio"
    "ai-related-products"
    "provide-support-live-chat"
    "ga-for-wp"
    "word-stats"
    "simple-page-access-restriction"
    "pdf-invoices-and-packing-slips-for-woocommerce"
    "subscriptions-memberships-for-paypal"
    "tilt-social-share-widget"
    "kama-clic-counter"
    "easy-digital-downloads-free-link"
    "wonderplugin-conditional-display"
    "mobileadmin"
    "live-copy-paste"
    "mapmyuser-widget"
    "ai-content-writing-assistant"
    "easy-automatic-newsletter"
    "schedule-posts-calendar"
    "rootspersona"
    "push-notification-for-wp-by-pushassist"
    "interactive-maps"
    "oik-weight-zone-shipping"
    "noaa-weather"
    "wp-post-hide"
    "stock-quotes-list"
    "core-framework"
    "dreamstime-stock-photos"
    "confirm-plus-contact-form-7"
    "easy-swipebox"
    "popup-addon-for-ninja-forms"
    "wp-instagram-feed"
    "folder-gallery"
    "woo-additional-terms"
    "visual-editor-font-size"
    "breaking-news-ticker"
    "crm-perks-forms"
    "taggbox-widget"
    "sync-wc-google"
    "tealium"
    "maz-loader"
    "twitter-friendly-links"
    "cm-table-of-content"
    "woocommerce-remove-sku"
    "feedfocal"
    "wp-administration-style"
    "bubble-menu"
    "debug-bar-post-types"
    "trustmate-io-integration-for-woocommerce"
    "nearby-now"
    "info-boxes-shortcode-and-widget"
    "wholesale-pricing-for-woocommerce"
    "spam-captcha"
    "ideapush"
    "wanderlust-oca-e-pak-shipping-rates"
    "zahls-ch-payment-gateway"
    "cp-reservation-calendar"
    "advanced-rich-text-tools"
    "jonradio-shortcodes-anywhere-or-everywhere"
    "tool-for-ada-section-508-and-seo"
    "aspexi-facebook-like-box-sidebox"
    "theme-tester"
    "wp-synhighlight"
    "custom-template-learndash"
    "heroic-glossary"
    "donations-block"
    "glotpress"
    "floating-action-button"
    "frontend-dashboard-custom-post"
    "file-un-attach"
    "copyscape-premium"
    "smart-maintenance-countdown"
    "adsense-privacy-policy"
    "woo-edit-templates"
    "wp-e-commerce-weightregion-shipping"
    "blogroll-links"
    "limit-post-add-on"
    "quick-301-redirects"
    "profile-widget-ninja"
    "multilingual-contact-form-7-with-polylang"
    "admin-columns-for-acf-fields"
    "hrm"
    "jobboardwp"
    "acf-blocks"
    "apester-interactive-content"
    "book-review-library"
    "rss-image-widget"
    "frizzly"
    "wp-content-security-policy"
    "cresta-posts-box"
    "acurax-on-click-pop-under"
    "godaddy-payments"
    "shortcode-cleaner-lite"
    "wp-qrcode-me-v-card"
    "gdpr-compliant-recaptcha-for-all-forms"
    "notice-bar"
    "xmas-decoration"
    "rizzi-guestbook"
    "disable-everything"
    "ai-responsive-gallery-album"
    "lh-add-media-from-url"
    "clever-mega-menu"
    "display-template-name"
    "highlight-author-comments"
    "rewrite"
    "wp-woocommerce-quickbooks"
    "woocommerce-products-carousel-all-in-one"
    "shipping-simulator-for-woocommerce"
    "simple-visitor-counter-widget"
    "cart-products-suggestions-for-woocommerce"
    "janolaw-agb-hosting"
    "wordpress-custom-sidebar"
    "wp-sendgrid"
    "wp-nmi-gateway-pci-woocommerce"
    "muut"
    "leadster-marketing-conversacional"
    "wpterm"
    "proper-network-activation"
    "responsive-mobile-friendly-tooltip"
    "cf7-email-add-on"
    "sku-for-woocommerce"
    "fonto"
    "add-social-share"
    "test-plugin-3"
    "di-blocks"
    "elementor-contact-form-7"
    "post-list-designer"
    "userheat"
    "shins-pageload-magic"
    "elementor-caldera-forms"
    "la-sentinelle-antispam"
    "protected-posts-logout-button"
    "recent-posts-by-category-widget"
    "wp-social-buttons"
    "starter-sites"
    "ajax-loginregister"
    "image-wall"
    "toggles-shortcode-and-widget"
    "image-rotation-fixer"
    "crowdfunding-for-woocommerce"
    "typepad-emoji-for-tinymce"
    "bp-user-profile-reviews"
    "ms-custom-login"
    "iworks-pwa"
    "real-estate-right-now"
    "affiliatewp-affiliate-product-rates"
    "hivepress-claim-listings"
    "conversational-forms"
    "woo-wholesale-pricing"
    "social-offers-and-digital-downloads"
    "qtranslate-meta"
    "rzp-woocommerce"
    "jekyll-exporter"
    "cpanel-manager-from-worpit"
    "evergreen-post-tweeter"
    "stream-status-for-twitch"
    "event-rocket"
    "wp-spry-menu"
    "woocommerce-mis-report"
    "simple-wp-retina"
    "add-tiktok-advertising-pixel"
    "wp-speedup"
    "grow-for-wp"
    "hit-counter-max"
    "quadlayers-telegram-chat"
    "feedpress"
    "bannerspace"
    "fami-sales-popup"
    "connect-contact-form-7-to-social-apps"
    "swfobject-reloaded"
    "wp-associate-post-r2"
    "tc-product-catalog"
    "cookielay"
    "contact-form-7-bwp-recaptcha-extension"
    "pagemeta"
    "icalendrier"
    "wc-city-select"
    "wpb-woocommerce-custom-tab-manager"
    "ajax-filter-posts"
    "taxonomy-filter"
    "wp-click-track"
    "marketking-multivendor-marketplace-for-woocommerce"
    "rimons-twitter-widget"
    "cron-logger"
    "widget-display-conditions"
    "woo-coupons-bulk-editor"
    "wp-airbnb-review-slider"
    "category-custom-post-order"
    "wpb-woocommerce-category-slider"
    "awsom-pixgallery"
    "recent-comments"
    "tdlc-birthdays"
    "advanced-advertising-system"
    "airwallex-online-payments-gateway"
    "helloasso"
    "wpc-force-sells"
    "add-descendants-as-submenu-items"
    "codepeople-theme-switch"
    "wen-skill-charts"
    "admin-bar-position"
    "cf7-views"
    "easy-code-placement"
    "wp-pluginsused"
    "private-buddypress"
    "genesis-featured-content-widget"
    "social-fabric-analytics-by-collective-bias"
    "clean-testimonials"
    "membership-for-woocommerce"
    "referralcandy-for-woocommerce"
    "ttv-easy-embed"
    "wp-geshi-highlight"
    "marketing-automation-and-personalization"
    "smart-phone-field-for-gravity-forms"
    "sunny"
    "calais-auto-tagger"
    "noakes-menu-manager"
    "yet-another-featured-posts-plugin"
    "kboard-widget"
    "activity-reactions-for-buddypress"
    "wp-insert-code"
    "author-category"
    "syndication-links"
    "wordpress-prevent-copy-paste-plugin"
    "flexo-archives-widget"
    "cloudsecure-wp-security"
    "bp-live-notification"
    "wp-events-manager-woocommerce-payment-methods-integration"
    "wp-bulletin-board"
    "patterns-kit"
    "restrict-usernames-emails-characters"
    "chatwee"
    "tierra-audio-with-autoresume"
    "wp-voting"
    "ncode-image-resizer"
    "wpgraphql-smart-cache"
    "taskbreaker-project-management"
    "serial-codes-generator-and-validator"
    "wpapptouch"
    "icon"
    "wholesale-pricing-woocommerce"
    "woocommerce-export-customer-email"
    "microsoft-start"
    "btcpay-greenfield-for-woocommerce"
    "woocommerce-sermepa-payment-gateway"
    "easy-paypal-events-tickets"
    "prestashop-integration"
    "landing-sites"
    "wp-search-suggest"
    "woo-payment-gateway-for-vivapayments"
    "wordpress-special-characters-in-usernames"
    "wp-gcalendar"
    "dropdown-menus"
    "woocommerce-extra-price-fields"
    "cache-external-scripts"
    "redirect-list"
    "karailievs-sitemap"
    "reepay-checkout-gateway"
    "bzscore-live-score"
    "purify-wp-menues"
    "wp-photo-text-slider-50"
    "mailster-woocommerce"
    "pp-express-wc4jp"
    "b-carousel-block"
    "woo-add-to-cart-text-change"
    "page-transition"
    "feedjit-widget"
    "force-sell-for-woocommerce"
    "admin-notices-manager"
    "horizontal-slider"
    "smart-wysiwyg-blocks-of-content"
    "shariff-sharing"
    "bulgarisation-for-woocommerce"
    "wp-tao"
    "rel-nofollow"
    "campaign-monitor-wp"
    "contact-form-7-datepicker-fix"
    "wpautop-control"
    "wp-easyarchives"
    "giga-store-advanced-sections"
    "category-images"
    "mtphr-shortcodes"
    "wpperformancetester"
    "private-wp"
    "editor-blocks"
    "shiny-updates"
    "funnelforms-free"
    "wordproof-timestamp"
    "disable-admin-bar"
    "sticky-floating-forms-lite"
    "before-after-images-for-divi"
    "creative-blocks"
    "boxers-and-swipers"
    "360deg-javascript-viewer"
    "daily-top-10-posts"
    "pmpro-events"
    "photo-swipe"
    "surbma-yoast-seo-sitemap-to-robotstxt"
    "ecommerce-product-carousel-slider-for-elementor"
    "netgsm"
    "news-ticker-for-elementor"
    "gestpay-for-woocommerce"
    "gs-portfolio"
    "best-editor"
    "disable-woocommerce-reviews"
    "customizable-post-listings"
    "image-uploader-for-welcart"
    "wp-sanitize-file-name-plus"
    "complete-google-seo-scan"
    "easy-twitter-feeds"
    "momo-venmo"
    "fancy-image-show"
    "simple-sticky-note"
    "tb-testimonials"
    "ultimeter"
    "woo-locations"
    "social-lite"
    "the-future-is-now"
    "easy-heads-up-bar"
    "zenphotopress"
    "indieweb-post-kinds"
    "adblock-invite"
    "woo-2checkout"
    "sqlite-object-cache"
    "gs-envato-portfolio"
    "minimum-order-amount-for-woocommerce"
    "graphical-statistics-report"
    "genesis-widgetized-notfound"
    "tls-1-2-compatibility-test"
    "easy-post-types"
    "wp-image-protect"
    "marketing-automation-by-convertfox"
    "insta-type-gallery"
    "wps-team"
    "email-post-changes"
    "bp-xprofile-location"
    "task-manager"
    "widgetwhats-app"
    "ht-instagram"
    "zamango-page-navigation"
    "sendpulse-web-push"
    "mphb-divi"
    "quick-localization"
    "ultimate-live-cricket-lite"
    "wp-lucky-wheel"
    "wp-championship"
    "woo-free-shipping-per-product"
    "monsters-editor-10-for-wp-super-edit"
    "super-simple-contact-form"
    "auto-hide-admin-menu-items"
    "so-masonry"
    "bloglentor-for-elementor"
    "dd-post-carousel"
    "audio-player-with-playlist-ultimate"
    "product-options-for-woocommerce"
    "change-permalink-helper"
    "jetpack-post-views"
    "clickbank-ads-clickbank-widget"
    "wpc-free-shipping-bar"
    "social-proof-testimonials-slider"
    "autoremove-attachments"
    "nextgen-3d-flux-slider-template"
    "wp-random-post-thumbnails"
    "faq-schema-for-pages-and-posts"
    "woo-boost-sales"
    "wp-author-slug"
    "save-with-keyboard"
    "pw-black-friday"
    "changyan"
    "weather-widget"
    "wc-invoice-gateway"
    "sticky-add-to-cart-woo"
    "twitter-goodies-widgets"
    "very-simple-woocommerce-upsell-popup"
    "solidres"
    "table-of-contents"
    "export-plugins-and-templates"
    "selection-sharer"
    "typekit"
    "wp-fade-in-text-news"
    "pinterest-verify-meta-tag"
    "payment-qr-woo"
    "wp-access-areas"
    "ultimate-410"
    "the-visitor-counter"
    "hyperlink-group-block"
    "media-categories-2"
    "content-scheduler"
    "flash-world-clock"
    "mwuse"
    "postmen-woo-shipping"
    "dms"
    "wp-admin-notification-center"
    "carousel-upsells-and-related-product-for-woocommerce"
    "content-freeze"
    "pods-gravity-forms"
    "graphcomment-comment-system"
    "scrollup-master"
    "oembed-for-buddypress"
    "cp-appointment-calendar"
    "stealth-publish"
    "buy-now-pay-later-addi"
    "image-widget-deluxe"
    "wallsio"
    "cp-blocks"
    "wp-business-intelligence-lite"
    "exchange-rate-table"
    "minnit-chat"
    "minestatus"
    "lazy-load-xt"
    "noindex-seo"
    "woo-payment-gateway-for-eurobank"
    "responsive-welcome-bar"
    "surbma-yes-no-popup"
    "author-profile"
    "permalink-fix-disable-canonical-redirects-pack"
    "awesome-sticky-header"
    "bbp-topic-count"
    "url-shortener"
    "amazon-widgets-shortcodes"
    "safelayout-cute-preloader"
    "paid-downloads"
    "obituary-assistant-by-funeral-home-website-solutions"
    "clicface-trombi"
    "ai-content-generator"
    "one-click-order-reorder"
    "nova-poshta-ttn"
    "atomchat"
    "websitevoice"
    "wpsso-wc-metadata"
    "free-cdn"
    "themify-audio-dock"
    "sql-buddy"
    "quizzin"
    "layouts-for-divi"
    "wp-security-audit-log-add-on-for-wpforms"
    "mlanguage"
    "attachment-taxonomies"
    "woo-product-remover"
    "paypal-framework"
    "mergado-marketing-pack"
    "niso-carousel-slider"
    "advanced-scrollbar"
    "onoffice-for-wp-websites"
    "photoswipe-for-nextgen-gallery"
    "category-feature"
    "logo-switcher"
    "like-gate"
    "curatorio"
    "simple-membership-mailchimp-integration"
    "wp-youtube-channel-gallery"
    "product-code-for-woocommerce"
    "pagepost-specific-social-share-buttons"
    "bring-fraktguiden-for-woocommerce"
    "search-analytics"
    "disable-application-passwords"
    "easy-sidebar-menu-widget"
    "woo-conditional-payment-gateways"
    "ar-for-wordpress"
    "vertical-response-newsletter-widget"
    "easy-property-listings-xml-csv-import"
    "woc-order-alert"
    "ays-facebook-popup-likebox"
    "wpc-product-tabs"
    "author-box-2"
    "constant-contact"
    "people-profile-cpt"
    "theme-downloader"
    "social-exchange-plugin"
    "simple-business-manager"
    "all-in-one-contact-buttons-wpshare247"
    "woocommerce-rrp"
    "affiliate-power"
    "quick-remove-menu-item"
    "smart-keywords-tool"
    "bbpress-private-replies"
    "search-google"
    "lastfm-for-wordpress"
    "display-admin-page-on-frontend"
    "ad-code-manager"
    "cab-grid"
    "revechat"
    "advanced-settings"
    "force-gzip"
    "wdesignkit"
    "speed-up-browser-caching"
    "codepen-embedded-pen-shortcode"
    "best-contact-form-for-wordpress"
    "flexible-wishlist"
    "ellipsis-human-presence-technology"
    "aino-blocks"
    "simple-header-footer-html"
    "userback"
    "cbnet-different-posts-per-page"
    "business-one-toolkit"
    "bulk-price-converter-for-woocommerce"
    "wpsearch"
    "map-me"
    "kento-pricing-table-free"
    "contact-me-on-zalo"
    "woorise"
    "ajax-campaign-monitor-forms"
    "lightbox-block"
    "admin10x"
    "woocommerce-variation-details-on-page-product"
    "post-type-archive-mapping"
    "wp-colorful-tag-cloud"
    "export-2-excel"
    "mslsmenu"
    "automatic-copyright-year"
    "cbnet-multi-author-comment-notification"
    "hide-admin-bar-from-front-end"
    "meks-audio-player"
    "blue-login-style"
    "rave-payment-forms"
    "icon-list"
    "wpcal"
    "woocommerce-custom-product-data-fields"
    "sticky-block"
    "co-marquage-service-public"
    "remote-database-backup"
    "wp-mail-returnpath"
    "wordpoints"
    "pmpro-discord-add-on"
    "miniorange-login-security"
    "material-design"
    "ere-similar-properties"
    "cvw-pb-animation"
    "woo-xml-feed-for-skroutzgr-bestpricegr"
    "lead-generated"
    "beamer"
    "wpsite-post-status-notifications"
    "socialintents-slack-chat"
    "consolto-videochat"
    "smartbill-facturare-si-gestiune"
    "wp-super-faq"
    "browser-caching-with-htaccess"
    "custom-background-extended"
    "payerurl-crypto-currency-payment-gateway-for-woocommerce"
    "wp-maintenance-mode-site-under-construction"
    "onwebchat"
    "gravityforms-eway"
    "wp-private"
    "carousel-of-post-images"
    "addonify-wishlist"
    "disable-gutenberg-autosave"
    "simple-restrict"
    "duplicate-content-addon-for-polylang"
    "wc-widgets"
    "senangpay-payment-gateway-for-woocommerce"
    "currency-exchange-for-woocommerce"
    "custom-admin-page"
    "lessbuttons"
    "employee-scheduler"
    "warm-cache"
    "wp-copyrighted-post"
    "woo-minicart"
    "emailoctopus"
    "rtsocial"
    "alma-gateway-for-woocommerce"
    "social-medias-connect"
    "dropdown-multisite-selector"
    "bsk-gravityforms-blacklist"
    "custom-smilies"
    "wp-family-tree"
    "csp-manager"
    "styler-for-ninja-forms-lite"
    "counter-visitor-for-woocommerce"
    "expandcollapse-funk"
    "no-nonsense"
    "plainview-activity-monitor"
    "document-embedder-addons-for-elementor"
    "wc-responsive-video"
    "ultimate-store-kit"
    "animations-for-blocks"
    "simplelightbox"
    "bp-member-type-generator"
    "calculo-de-despacho-via-starken-para-woocommerce"
    "advance-wp-query-search-filter"
    "ajax-bootmodal-login"
    "api-bing-map-2018"
    "hacklog-remote-attachment"
    "post-or-page-hide-title"
    "block-pattern-builder"
    "rename-xml-rpc"
    "total-slider"
    "auto-tag-links"
    "wp-countdown-timer"
    "random-file"
    "trackingmore-woocommerce-tracking"
    "syntax-highlighting-code-block"
    "acf-duplicate-repeater"
    "hifi"
    "custom-menu"
    "preserve-editor-scroll-position"
    "wp-tota11y"
    "footer-credits"
    "fast-tube"
    "responsive-google-map"
    "wordpress-mu-secure-invites"
    "phpbb-single-sign-on"
    "wetterwarner"
    "customize-submit-button-for-gravity-forms"
    "8-degree-availability-calendar"
    "background-slider-master"
    "wp-worthy"
    "meet-my-team"
    "wp-dynamic-keywords-injector"
    "connect-daily-web-calendar"
    "hreflang-manager-lite"
    "svg-flags-lite"
    "dashboard-welcome-for-beaver-builder"
    "affiliatewp-store-credit"
    "fancy-heaer-slider"
    "biteship"
    "accordion-slider-lite"
    "remove-author-pages"
    "aio-time-clock-lite"
    "bp-profile-shortcodes-extra"
    "cm-invitation-codes"
    "woocommerce-local-pickup-time-select"
    "cool-responsive-mega-menu"
    "wpecounter"
    "christmas-panda"
    "floating-click-to-contact-buttons"
    "skt-themes-demo-importer"
    "social-dropdown"
    "order-export-for-woocommerce"
    "threat-scan-plugin"
    "urdu-keyboard"
    "high-compress"
    "css-ready-classes-gravity-forms"
    "wp-lazy-loading"
    "ad-manager-for-wp"
    "chaport"
    "off-canvas-sidebars"
    "slack"
    "wp-calorie-calculator"
    "indieweb"
    "pdf-viewer-by-themencode"
    "social-mobile-messaging-bar"
    "addonify-compare-products"
    "page-menu"
    "counter-box"
    "teamspeak-3-viewer-plugin-for-wordpress-widget"
    "hide-wp-comment-author-link"
    "live-search-popup"
    "wp-open-street-map"
    "wp-notification-center"
    "conditional-discount-rule-for-woocommerce"
    "advanced-reporting-for-woocommerce"
    "ppinger"
    "user-messages"
    "acumulus"
    "user-ip-and-location"
    "myweather"
    "wp-download-codes"
    "powies-whois"
    "mailrelay"
    "stock-sync-for-woocommerce"
    "um-forumwp"
    "lock-user-account"
    "wp-social-share"
    "tc-woocommerce-product-slider"
    "prevent-file-access"
    "kevinjohn-gallagher-pure-web-brilliants-base-framework"
    "variation-duplicator-for-woocommerce"
    "plugins-list"
    "walker-core"
    "statify-blacklist"
    "keyword-research-tool"
    "infobox"
    "hitpay-payment-gateway"
    "savvii-wp-migrate"
    "list-all-posts-by-authors-nested-categories-and-titles"
    "workbox-video-from-vimeo-youtube-plugin"
    "bestazon"
    "clean-my-archives"
    "order-approval-woocommerce"
    "what-template-file-am-i-viewing"
    "comfortable-reading"
    "devformatter"
    "custom-html-bodyhead"
    "uniconsent-cmp"
    "content-writer"
    "cf7-to-api-basic-auth"
    "widgets-control"
    "auto-syntaxhighlighter"
    "floating-window-music-player"
    "recent-posts-widget-plus"
    "embed-rss"
    "social-master"
    "codenovo-portfolio"
    "yahoo-media-player"
    "live-scores"
    "disable-post-revision"
    "form-to-chat"
    "striper"
    "related-posts-list-grid-and-slider-all-in-one"
    "wp-hidden-password-protected-page"
    "jj-nextgen-jquery-cycle"
    "beautiful-yahoo-weather"
    "export-emails"
    "wp-fingerprint"
    "smart-post-lists-light"
    "popup-for-contact-form-7"
    "super-switch"
    "minqueue"
    "buddyforms-ultimate-member"
    "ninja-forms-modal"
    "flashfader"
    "multisite-user-role-manager"
    "change-wc-price-title"
    "wp-rest-yoast-meta"
    "wp-affiliate-disclosure"
    "10to8-online-booking"
    "depay-payments-for-woocommerce"
    "shipday-for-woocommerce"
    "hover-effects-for-visual-composer"
    "styles-for-wp-pagenavi-addon"
    "popularity-stats"
    "force-first-last"
    "smart-send-logistics"
    "floating-contact-buttons"
    "infinite-ajax-scrolling-for-woocommerce"
    "shortcode-toc"
    "beauty-gravity"
    "ni-woocommerce-product-enquiry"
    "single-category-permalink"
    "local-market-explorer"
    "quotes-llama"
    "staffer"
    "code-block-for-elementor"
    "debug-bar-transients"
    "thememiles-toolset"
    "apaczka-pl"
    "easy-image-sizes"
    "cluevo-lms"
    "nexter-extension"
    "idle-user-logout"
    "preloader-for-website"
    "utf-8-database-converter"
    "yandexmetrika"
    "notix-web-push-notifications"
    "sh-slideshow"
    "cowidgets-elementor-addons"
    "featured-image-zoom"
    "wp-voting-contest"
    "page-visits-counter-lite"
    "shop-as-client"
    "wp-sidebar-login"
    "thickbox-content"
    "http2-server-push"
    "occupancyplan"
    "etracker"
    "headline-analyzer"
    "kaskus-emoticons"
    "wp-links"
    "scroll-to-top-button"
    "kona-instagram-feed-for-gutenberg"
    "secure-downloads"
    "auto-post-images-api"
    "easy-share-solution"
    "sharpen-resized-images"
    "salesmanago"
    "license-envato"
    "cryptowp"
    "my-wp-tagcanvas"
    "wp-mediatagger"
    "wc-pagarme-pix-payment"
    "online-booking"
    "easy"
    "buddypress-login-redirect"
    "wp-onpage-seo"
    "opal-megamenu-for-elementor"
    "remove-featured-image"
    "leadbooster-by-pipedrive"
    "easy-wp-page-navigation"
    "duplicate-widget"
    "google-website-optimizer-for-wordpress"
    "gravitywp-merge-tags"
    "etruel-del-post-copies"
    "wp-user-profiles"
    "comment-form-quicktags"
    "cms-navigation"
    "export-order-items-for-woocommerce"
    "wphindi"
    "save-import-image-from-url"
    "moowoodle"
    "nextgen-nivoslider"
    "i-love-social-bookmarking"
    "xavins-review-ratings"
    "interactive-map-of-the-us-regions"
    "wp-site-verification-tool"
    "subpage-listing"
    "mass-page-remover"
    "bp-profile-as-homepage"
    "scratch-win-giveaways-for-website-facebook"
    "repeat-order-for-woocommerce"
    "page-loader"
    "wpcleaner"
    "css3-rotating-words"
    "increase-maximum-upload-file-size"
    "delicious-for-wordpress"
    "calendar-plus"
    "ajax-contact-me"
    "spatie-ray"
    "wp-automatic-updates"
    "piglatin"
    "ultimate-floating-widgets"
    "stock-market-news"
    "pdf-importer-for-wpform"
    "wp-post-redirect"
    "affiliates-contact-form-7"
    "nice-search"
    "featured-posts-grid"
    "woo-fattureincloud"
    "telsender"
    "embed-video-thumbnail"
    "include-lottie-animation-for-elementor"
    "sanitize-spanish-filenames"
    "invoice-gateway-for-woocommerce"
    "multilanguage-add-on-for-visual-composer"
    "wp-mapbox-gl-js"
    "gravity-forms-duplicate-prevention"
    "pinoy-pop-up-on-exit"
    "slash-admin"
    "woocommerce-image-hover"
    "admin-color-schemer"
    "a-slideshow"
    "easy-textillate"
    "block-editor-colors"
    "csv-to-html"
    "faf"
    "bulk-image-title-attribute"
    "moosend-email-marketing"
    "site-search-360"
    "custom-html-block-extension"
    "popular-posts-by-webline"
    "oss-upload"
    "jetpack-sharing-butttons-shortcode"
    "good-old-twitter-feed-widget"
    "related-posts-via-taxonomies"
    "wc-robokassa"
    "mangapress"
    "html-after-url"
    "easy-paypal-custom-fields"
    "easy-lightbox-wp"
    "cleverpush"
    "yd-wpmu-sitewide-options"
    "docs-viewer-add-on-for-wp-job-openings"
    "availability"
    "webplus-liqpay-woocommerce"
    "cm-business-directory"
    "wp2cloud-wordpress-to-cloud"
    "devvn-float-left-right-ads"
    "advanced-custom-field-widget"
    "portfolios"
    "woo-boleto-paghiper"
    "ai-post-generator"
    "flipbox"
    "pre-publish-checklist"
    "tumult-hype-animations"
    "razorpay-payment-button"
    "sql-chart-builder"
    "easy-social-media"
    "convert-a-link"
    "flickr-shortcode-importer"
    "svea-checkout-for-woocommerce"
    "twitter-posts-to-blog"
    "bp-featured-members"
    "custom-profile-filters-for-buddypress"
    "maxi-blocks"
    "wen-responsive-columns"
    "rss-manager"
    "currency-converter-calculator"
    "djd-site-post"
    "google-1"
    "menus-plus"
    "gallery-with-thumbnail-slider"
    "dashboard-sticky-notes"
    "shipping-mipaquete-woocommerce"
    "parallax-section"
    "twitoaster"
    "best-related-posts"
    "travelers-map"
    "tantan-s3"
    "chatwing"
    "bp-automatic-friends"
    "text-spinner"
    "wp-real-estate"
    "database-sync"
    "insert-javascript-css"
    "bh-custom-preloader"
    "woocommerce-product-faqs"
    "theme-blvd-news-scroller"
    "add-featured-image-column"
    "panorama"
    "push7"
    "wp-jquery-plus"
    "rezgo"
    "stonehenge-em-osm"
    "wp-discord-post"
    "custom-404-error-page"
    "buddypress-first-letter-avatar"
    "mx-time-zone-clocks"
    "cookie-law-bar"
    "logo-showcase"
    "add-on-woocommerce-mailpoet"
    "dh-anti-adblocker"
    "enhanced-ajax-add-to-cart-for-woocommerce"
    "html5-video-player-with-playlist"
    "network-privacy"
    "wpzon"
    "pricing-tables-for-visual-composer"
    "user-private-files"
    "vk-google-job-posting-manager"
    "super-slider"
    "theme-switcher-reloaded"
    "jssor-slider"
    "clariti"
    "twitch-status"
    "job-board"
    "fusion-extension-gallery"
    "widget-video-box"
    "disable-toolbar"
    "premium-chat"
    "mailingboss"
    "uncomment"
    "memberfindme-login-connector"
    "simple-flickr-photostream-widget"
    "left-right-image-slideshow-gallery"
    "plugin-compatibility-checker"
    "include-fussball-de-widgets"
    "advanced-ads-genesis"
    "browser-theme-color"
    "injection-guard"
    "wp-cassify"
    "venobox-lightbox"
    "kill-adblock"
    "easy-maps-block"
    "wp-meetup"
    "email-customizer-woocommerce"
    "featured-products-first-for-woocommerce"
    "pepro-bacs-receipt-upload-for-woocommerce"
    "chatway-live-chat"
    "audiomack"
    "chameleon"
    "xml-image-sitemap"
    "wp-counter-up"
    "uploadcare"
    "media-category-library"
    "wordpress-meta-description"
    "woocommerce-braintree-payment-gateway"
    "wp-top-news"
    "dynamic-hostname"
    "wp-jquery-datatable"
    "coming-soons"
    "image-text-widget"
    "blockmeister"
    "wishlist"
    "woocommerce-product-generator"
    "wp-zoho-crm"
    "shipment-tracker-for-woocommerce"
    "email-domain-verification-in-cf7"
    "custom-classes"
    "woo-customers-manager"
    "custom-field-list-widget"
    "team-member-block"
    "sublanguage"
    "meta-box-yoast-seo"
    "visma-pay-payment-gateway"
    "kopa-page-builder"
    "content-manager-light"
    "delete-old-posts-programmatically"
    "oss-aliyun"
    "wp-ride-booking"
    "cbxuseronline"
    "multiple-packages-for-woocommerce"
    "wplistcal"
    "custom-product-tabs-wp-all-import-add-on"
    "novelist"
    "page-management-dropdown"
    "yourls-link-creator"
    "php-info-wp"
    "simple-optimizer"
    "woocommerce-product-gift-wrap"
    "administrator-z"
    "swifty-image-widget"
    "mortgage-calculators-wp"
    "categories-in-hierarchical-order"
    "bns-add-widget"
    "skt-nurcaptcha"
    "voguepay-woocommerce-payment-gateway"
    "wp-clean-admin-menu"
    "wp-flickr-embed"
    "shippit-simplified-australia-shipping"
    "mini-popup"
    "rss-scroller"
    "login-dongle"
    "the-excerpt-re-reloaded"
    "genesis-super-customizer"
    "exs-widgets"
    "gs-woocommerce-products-slider"
    "tilted-tag-cloud-widget"
    "woo-partially"
    "tc-pricing-table"
    "batch-comment-spam-deletion"
    "vegas-fullscreen-background-slider"
    "adwords-conversion-tracking-code"
    "finance-calculator-with-application-form"
    "expire-passwords"
    "power-ups-for-elementor"
    "google-fonts-acceleration"
    "wc-dropi-integration"
    "disabler"
    "no-bot-registration"
    "ss-downloads"
    "wordpress-media-flickr"
    "payment-integration-wompi"
    "top-flash-embed"
    "aio-files-excluder"
    "bulk-comments-management"
    "s3bubble-amazon-web-services-oembed-media-streaming-support"
    "scrollbar"
    "xps-ship-integration"
    "ays-chatgpt-assistant"
    "remove-all-comments"
    "wechat-shop-download"
    "native-ads-adnow"
    "customize-snapshots"
    "passwordless-login"
    "reachedge"
    "acf-image-mapping-hotspots"
    "quick-meta-keywords"
    "display-all-image-sizes"
    "debug-bar-shortcodes"
    "dracula-dark-mode"
    "wp-fluid-images"
    "starfish-reviews"
    "wp-better-permalinks"
    "frontend-dashboard-extra"
    "hsts-ready"
    "bp-disable-activation-reloaded"
    "wp-image-lazy-load"
    "farsi-font-for-elementor"
    "notification-for-telegram"
    "mass-messaging-in-buddypress"
    "miniorange-wp-as-saml-idp"
    "cloudguard"
    "registered-users-only-2"
    "responsive-cookie-consent"
    "gallery-photo-video"
    "super-simple-event-calendar"
    "searchpro"
    "pro-mime-types"
    "mass-delete-unused-tags"
    "wp-tracking-codes"
    "wpc-sticky-add-to-cart"
    "wp-stats-view-counter"
    "audience-analytics-by-quantcast"
    "page-and-post-restriction"
    "woobox"
    "cf7-html-email-template-extension"
    "woo-additional-fees-on-checkout-wordpress"
    "mj-contact-us"
    "world-cup-predictor"
    "simple-analytics"
    "donate-button"
    "cf7-calendar"
    "modeloform"
    "woomotiv"
    "admin-customization"
    "image-map-hotspots"
    "bws-pinterest"
    "faq-concertina"
    "jquery-easy-menu"
    "remove-uppercase-accents"
    "wp-nonstop-smushit"
    "visual-builder-for-contact-form-7"
    "comunas-de-chile-para-woocommerce"
    "xml-sitemap-generator"
    "acf-advanced-taxonomy-selector"
    "woocommerce-category-banner"
    "order-status-control-for-woocommerce"
    "wp-font-face"
    "pixel-manager-for-woocommerce"
    "wp-ya-share"
    "maintenance-mode-for-woocommerce"
    "botnet-attack-blocker"
    "mailster-sendgrid"
    "raffle-ticket-generator"
    "shockingly-big-ie6-warning"
    "paypal-currency-converter-basic-for-woocommerce"
    "frontend-dashboard-pages"
    "people-lists"
    "sola-support-tickets"
    "wp-e-commerce-exporter"
    "daisycon"
    "gd-pages-navigator"
    "rewrite-testing"
    "wpc-insert-code"
    "aplazame"
    "remove-wp-overhead"
    "filebird-document-library"
    "baw-invitation-codes"
    "inline-svg-elementor"
    "validated"
    "better-menu-widget"
    "advance-custom-html"
    "couponapi"
    "typebot"
    "xo-post-background"
    "heateor-social-login"
    "ry-wc-city-select"
    "phpbb-recent-topics"
    "loan-calculator-wp"
    "wp-mailster"
    "sonetel-website-chat"
    "wp-isell-photo"
    "kata-plus"
    "b-tiktok-feed"
    "va-social-buzz"
    "crypto-com-pay-checkout-for-woocommerce"
    "mpress-custom-front-page"
    "do-spaces-sync"
    "theme-builder-for-elementor"
    "woocommerce-fortnox-integration"
    "robokassa-for-woocommerce"
    "custom-users-order"
    "maps-block-apple"
    "social-media-widgets"
    "recipepress-reloaded"
    "video-sync-for-vimeo"
    "password-strength-for-woocommerce"
    "event-registration-calendar-by-vcita"
    "wp-tiger"
    "gd-security-headers"
    "add-youtube-feed"
    "ether-and-erc20-tokens-woocommerce-payment-gateway"
    "wp-require-login"
    "shortcode-elementor"
    "author-profiles"
    "wp-slideshow"
    "imagekit"
    "plugins-last-updated-column"
    "clicface-organi"
    "onpay-io-for-woocommerce"
    "advanced-custom-fields-contact-form-7-field"
    "plugin-groups"
    "simple-locator"
    "coldbox-addon"
    "easy-related-posts"
    "nextgen-gallery-colorboxer"
    "aweos-php-server-info"
    "custom-post-type-cleanup"
    "sm-sticky-clicky-star"
    "fullestop-lock-down-admin"
    "calculator-builder"
    "icon-list-block"
    "horizontal-motion-gallery"
    "post-carousel-slider-for-visual-composer"
    "mailster-recaptcha"
    "advanced-testimonial-carousel-for-elementor"
    "purchase-orders-for-woocommerce"
    "testimonial-widgets"
    "wp-helper-lite"
    "hangul-font-nanumgothic-google"
    "easy-post-views-count"
    "pushover-notifications"
    "jsm-show-term-meta"
    "barcode-scanner-lite-pos-to-manage-products-inventory-and-orders"
    "zuppler-online-ordering"
    "gb-gallery-slideshow"
    "send-e-mail"
    "platnosci-online-blue-media"
    "circle-image-slider-with-lightbox"
    "reusable-content-blocks"
    "wptao"
    "delete-multiple-themes"
    "wp-scroll-depth"
    "ichart"
    "elegant-custom-fonts"
    "sign-in-with-google"
    "contact-form-7-campaignmonitor-addon"
    "cf7-skins-innozilla"
    "fusewp"
    "featured-posts-scroll"
    "quick-restaurant-reservations"
    "ryans-simple-cms"
    "salat-times"
    "netreviews"
    "tbthemes-demo-import"
    "gf-mollie-by-indigo"
    "surbma-smooth-scroll"
    "zara-4"
    "image-carousel-for-divi"
    "customizer-reset"
    "google-wordpress-widgets"
    "shipping-by-rules-for-woocommerce"
    "wp-advanced-math-captcha"
    "wp-lorem-ipsum"
    "disqus-recent-comments-widget"
    "sp-rtl-rus-to-lat"
    "wp-charts-and-graphs"
    "emoji-settings"
    "hide-all-notices"
    "responsive-image-widget"
    "tabby-checkout"
    "wc-cart-pdf"
    "affiliatewp-allowed-products"
    "category-widget"
    "image-rotation-repair"
    "syntax-highlighter-mt"
    "image-quality"
)

# Define user agents with weights
declare -A USER_AGENTS
USER_AGENTS=(
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"]=5
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"]=7
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"]=6
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36 Edg/91.0.864.54"]=5
    ["Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 OPR/77.0.4054.277"]=3
    ["Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (iPad; CPU OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Vivaldi/4.0"]=1
    ["Mozilla/5.0 (Android 11; Mobile; rv:68.0) Gecko/68.0 Firefox/88.0"]=1
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"]=15
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/534.36"]=12
)

OPENED_PLUGINS_FILE="${WORDPRESS_WORKDIR}/opened_plugins.txt"
CLOSED_PLUGINS_FILE="${WORDPRESS_WORKDIR}/closed_plugins.txt"
LAST_VERSION_FILE="${WORDPRESS_WORKDIR}/last_versions.txt"
PARALLEL_JOBS=1

DOWNLOAD_ALL_PLUGINS='n'
LIST_ONLY='n'
ALL_PLUGINS_FILE="${WORDPRESS_WORKDIR}/wp-plugin-svn-list.txt"
START_COUNT=0
END_COUNT=0

DELAY_DOWNLOADS='n'
DELAY_DURATION=5

FORCE_UPDATE='n'
CACHE_ONLY='n'

mkdir -p "$WORDPRESS_WORKDIR" "$MIRROR_DIR" "$LOGS_DIR"
rm -f "$OPENED_PLUGINS_FILE"
touch "$OPENED_PLUGINS_FILE"
DEBUG_MODE=0

while getopts "p:dalD:t:fcs:e:" opt; do
    case ${opt} in
        p ) PARALLEL_JOBS=$OPTARG ;;
        d ) DEBUG_MODE=1 ;;
        a ) DOWNLOAD_ALL_PLUGINS='y' ;;
        l ) LIST_ONLY='y' ;;
        D ) DELAY_DOWNLOADS=$OPTARG ;;
        t ) DELAY_DURATION=$OPTARG ;;
        f ) FORCE_UPDATE='y' ;;
        c ) CACHE_ONLY='y' ;;
        s ) START_COUNT=$OPTARG ;;
        e ) END_COUNT=$OPTARG ;;
        \? ) echo "Usage: $0 [-p PARALLEL_JOBS] [-d] [-a] [-l] [-D DELAY_DOWNLOADS] [-t DELAY_DURATION] [-f] [-c] [-s START_COUNT] [-e END_COUNT]" 1>&2; exit 1 ;;
    esac
done

debug_log() {
    if [ "$DEBUG_MODE" -eq 1 ]; then
        echo "[DEBUG] $1" >&2
    fi
}

get_random_user_agent() {
    echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
}

get_latest_version_and_download_link() {
    local plugin=$1
    debug_log "Checking latest version and download link for $plugin"
    
    local api_url="https://api.wordpress.org/plugins/info/1.0/${plugin}.json"
    local user_agent=$(get_random_user_agent)
    local api_response=$(curl -s -H "User-Agent: $user_agent" "$api_url")
    
    if echo "$api_response" | jq -e '.error' >/dev/null; then
        local error_message=$(echo "$api_response" | jq -r '.error')
        if [ "$error_message" = "closed" ]; then
            echo "closed"
            return 2
        else
        echo "Error: $error_message for plugin $plugin" >&2
        return 1
        fi
    fi
    
    local version=$(echo "$api_response" | jq -r '.version // empty')
    local download_link=$(echo "$api_response" | jq -r '.download_link // empty')
    
    if [ -n "$version" ] && [ -n "$download_link" ]; then
        echo "$version $download_link"
        return 0
    else
        echo "Error: Cannot fetch version or download link for $plugin" >&2
        return 1
    fi
}

download_plugin() {
    local plugin=$1
    local version=$2
    local api_download_link=$3
    local output_file="${MIRROR_DIR}/${plugin}.${version}.zip"
    local header_file="${LOGS_DIR}/${plugin}.${version}.headers"
    local constructed_download_link="${DOWNLOAD_BASE_URL}/${plugin}.${version}.zip"
    local download_link

    if [ "$DEBUG_MODE" -eq 1 ]; then
        debug_log "API-provided download link for $plugin: $api_download_link"
        debug_log "Constructed download link for $plugin: $constructed_download_link"
    fi

    if [ "$DOWNLOAD_LINK_API" == 'y' ] && [ -n "$api_download_link" ]; then
        download_link="$api_download_link"
        debug_log "Using API-provided download link for $plugin: $download_link"
    else
        download_link="$constructed_download_link"
        debug_log "Using constructed download link for $plugin: $download_link"
    fi

    debug_log "Downloading $plugin version $version through Cloudflare Worker"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)
    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o /dev/null "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    else
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o "$output_file" "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    fi

    if [ $? -eq 0 ]; then
        if [ "$CACHE_ONLY" == 'y' ]; then
            debug_log "Plugin $plugin version $version cached successfully."
            return 0
        fi

        local file_size=$(stat -c%s "$output_file")
        if [ "$file_size" -lt 1000 ]; then
            echo "Error: Downloaded file for $plugin is too small (${file_size} bytes). Possible download issue." >&2
            return 1
        fi

        local source=$(grep -i "X-Source:" "$header_file" | cut -d' ' -f2 | tr -d '\r')
        if [ "$source" == "R2" ]; then
            debug_log "Successfully downloaded $plugin version $version from R2 storage"
        elif [ "$source" == "WordPress" ]; then
            debug_log "Successfully downloaded $plugin version $version from WordPress"
            debug_log "R2 bucket saving for plugin zip occurred"
        else
            debug_log "Skipped download for $plugin $version zip (already exists locally)"
        fi

        return 0
    else
        echo "Error: Failed to download $plugin version $version" >&2
        return 1
    fi
}

save_plugin_info() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.json"

    debug_log "Saving plugin json metadata for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying metadata download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    if [ "$CACHE_ONLY" == 'y' ]; then
        # When in cache-only mode, output to /dev/null
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin metadata for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache json metadata for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            if [ "$source" = "R2" ]; then
                debug_log "json metadata for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "json metadata for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin json occurred"
            else
                debug_log "json metadata for $plugin version $version saved (json metadata file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save json metadata for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

fetch_and_save_checksums() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.checksums.json"

    debug_log "Fetching and saving checksums for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying checksums download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    debug_log "Sending request to Worker for checksums: CF_WORKER_URL?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"

    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin checksums for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache checksums for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        debug_log "Received response with status code: $status_code"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            debug_log "Response source: $source"
            if [ "$source" = "R2" ]; then
                debug_log "Checksums for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "Checksums for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin checksums occurred"
            else
                debug_log "Checksums for $plugin version $version saved (checksums file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save checksums for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

process_plugin() {
    local plugin=$1
    plugin=$(echo "$plugin" | sed 's/^\/\|\/$//g')

    # Check if the plugin is already known to be closed
    if grep -q "^$plugin$" "$CLOSED_PLUGINS_FILE" 2>/dev/null; then
        echo "Plugin $plugin is known to be closed. Skipping."
        return 0
    fi

    echo "Processing plugin: $plugin"

    VERSION_AND_LINK=$(get_latest_version_and_download_link "$plugin")
    local version_check_status=$?
    
    if [ $version_check_status -eq 1 ]; then
        echo "Skipping $plugin due to version fetch error."
        return 1
    elif [ $version_check_status -eq 2 ]; then
        echo "Plugin $plugin is closed. Skipping download and processing."
        echo "$plugin" >> "$CLOSED_PLUGINS_FILE"
        if save_plugin_info "$plugin" "closed"; then
            debug_log "Successfully saved json metadata for closed plugin $plugin."
        else
            debug_log "Failed to save json metadata for closed plugin $plugin."
        fi
        return 0
    fi
    
    LATEST_VERSION=$(echo "$VERSION_AND_LINK" | cut -d' ' -f1)
    API_DOWNLOAD_LINK=$(echo "$VERSION_AND_LINK" | cut -d' ' -f2-)

    debug_log "Latest version for $plugin: $LATEST_VERSION"
    debug_log "API download link for $plugin: $API_DOWNLOAD_LINK"

    STORED_VERSION=$(grep "^$plugin" "$LAST_VERSION_FILE" | awk '{print $2}')
    debug_log "Stored version for $plugin: $STORED_VERSION"

    if [ "$CACHE_ONLY" != 'y' ] && [ "$LATEST_VERSION" == "$STORED_VERSION" ] && [ -f "${MIRROR_DIR}/${plugin}.${LATEST_VERSION}.zip" ]; then
        echo "$plugin is up-to-date and exists in mirror directory. Skipping download..."
    else
        start_time=$(date +%s.%N)

        if download_plugin "$plugin" "$LATEST_VERSION" "$API_DOWNLOAD_LINK"; then
            if [ "$CACHE_ONLY" != 'y' ]; then
                sed -i "/^$plugin/d" "$LAST_VERSION_FILE"
                echo "$plugin $LATEST_VERSION" >> "$LAST_VERSION_FILE"
            fi
            echo "Successfully processed $plugin."
        else
            echo "Error: Failed to process $plugin." >&2
        fi

        end_time=$(date +%s.%N)
        duration=$(echo "$end_time - $start_time" | bc)
        printf "Time taken for %s: %.4f seconds\n" "$plugin" "$duration"
    fi

    if save_plugin_info "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully saved json metadata for $plugin."
    else
        debug_log "Failed to save json metadata for $plugin."
    fi

    if fetch_and_save_checksums "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully fetched and saved checksums for $plugin."
    else
        debug_log "Failed to fetch and save checksums for $plugin."
    fi

    if [ $version_check_status -eq 0 ]; then
        echo "$plugin" >> "$OPENED_PLUGINS_FILE"
    fi
}

populate_all_plugins() {
    if [ ! -f "$ALL_PLUGINS_FILE" ] || [ "$LIST_ONLY" == 'y' ]; then
        echo "Fetching list of all WordPress plugins..."
        svn list https://plugins.svn.wordpress.org/ | sed 's/\/$//g' > "$ALL_PLUGINS_FILE"
        plugin_count=$(wc -l < "$ALL_PLUGINS_FILE")
        echo "Plugin list (${plugin_count}) saved to $ALL_PLUGINS_FILE"
    fi
    
    if [ "$LIST_ONLY" == 'n' ]; then
        ALL_PLUGINS=()
        if [ "$DOWNLOAD_ALL_PLUGINS" == 'y' ] && [ $START_COUNT -gt 0 ] && [ $END_COUNT -ge $START_COUNT ]; then
            echo "Processing plugins from line $START_COUNT to $END_COUNT"
            while IFS= read -r line; do
                ALL_PLUGINS+=("$line")
            done < <(sed -n "${START_COUNT},${END_COUNT}p" "$ALL_PLUGINS_FILE")
        else
            while IFS= read -r line; do
                ALL_PLUGINS+=("$line")
            done < "$ALL_PLUGINS_FILE"
        fi
        echo "Loaded ${#ALL_PLUGINS[@]} plugins."
    fi
}

if [ "$LIST_ONLY" == 'y' ]; then
    populate_all_plugins
    echo "Plugin list created. Exiting without downloading."
    exit 0
fi

if [ "$DOWNLOAD_ALL_PLUGINS" == 'y' ]; then
    populate_all_plugins
    COMBINED_PLUGINS=("${ALL_PLUGINS[@]}")
else
    if [ ! -d "$PLUGIN_DIR" ]; then
        echo "Warning: Plugin directory $PLUGIN_DIR does not exist or is invalid."
        PLUGIN_LIST=()
    else
        PLUGIN_LIST=($(ls -d "$PLUGIN_DIR"/*/ 2>/dev/null | xargs -n 1 basename))

        if [ ${#PLUGIN_LIST[@]} -eq 0 ]; then
            echo "No plugins found in $PLUGIN_DIR."
        fi
    fi

    COMBINED_PLUGINS=(${PLUGIN_LIST[@]} ${ADDITIONAL_PLUGINS[@]})
    COMBINED_PLUGINS=($(echo "${COMBINED_PLUGINS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
fi

if [ ${#COMBINED_PLUGINS[@]} -eq 0 ]; then
    echo "No plugins to download. Exiting."
    exit 0
fi

mkdir -p "$MIRROR_DIR"
touch "$LAST_VERSION_FILE"

if [ "$PARALLEL_JOBS" -gt 1 ]; then
    echo "Running in parallel with $PARALLEL_JOBS jobs..."
    echo "Variables before export:"

    # WordPress-related directories
    echo "WORDPRESS_WORKDIR: $WORDPRESS_WORKDIR"
    echo "PLUGIN_DIR: $PLUGIN_DIR"
    echo "MIRROR_DIR: $MIRROR_DIR"
    echo "LOGS_DIR: $LOGS_DIR"

    # Cloudflare Worker related URLs
    echo "CF_WORKER_URL: $CF_WORKER_URL"

    # Flags and options
    echo "DOWNLOAD_LINK_API: $DOWNLOAD_LINK_API"
    echo "DOWNLOAD_ALL_PLUGINS: $DOWNLOAD_ALL_PLUGINS"
    echo "LIST_ONLY: $LIST_ONLY"
    echo "DELAY_DOWNLOADS: $DELAY_DOWNLOADS"
    echo "DELAY_DURATION: $DELAY_DURATION"
    echo "FORCE_UPDATE: $FORCE_UPDATE"
    echo "CACHE_ONLY: $CACHE_ONLY"

    # File paths
    echo "OPENED_PLUGINS_FILE: $OPENED_PLUGINS_FILE"
    echo "CLOSED_PLUGINS_FILE: $CLOSED_PLUGINS_FILE"
    echo "LAST_VERSION_FILE: $LAST_VERSION_FILE"
    echo "ALL_PLUGINS_FILE: $ALL_PLUGINS_FILE"

    # Parallel job configuration
    echo "PARALLEL_JOBS: $PARALLEL_JOBS"

    # User Agents mapping
    echo "USER_AGENTS: ${USER_AGENTS[@]}"

    # Additional plugins to be processed
    # echo "ADDITIONAL_PLUGINS: ${ADDITIONAL_PLUGINS[@]}"

    # Plugin List (loaded from directory or ALL_PLUGINS_FILE)
    #echo "PLUGIN_LIST: ${PLUGIN_LIST[@]}"
    #echo "COMBINED_PLUGINS: ${COMBINED_PLUGINS[@]}"

    # First, export all variables including USER_AGENTS
    export DOWNLOAD_BASE_URL MIRROR_DIR LAST_VERSION_FILE DEBUG_MODE DOWNLOAD_LINK_API LOGS_DIR ALL_PLUGINS_FILE DOWNLOAD_ALL_PLUGINS LIST_ONLY CF_WORKER_URL DELAY_DOWNLOADS DELAY_DURATION FORCE_UPDATE CACHE_ONLY WORDPRESS_WORKDIR PLUGIN_DIR PARALLEL_JOBS OPENED_PLUGINS_FILE CLOSED_PLUGINS_FILE USER_AGENTS

    # Then, export the functions
    export -f process_plugin get_latest_version_and_download_link download_plugin debug_log populate_all_plugins save_plugin_info get_random_user_agent fetch_and_save_checksums
    printf "%s\n" "${COMBINED_PLUGINS[@]}" | xargs -P $PARALLEL_JOBS -I {} bash -c 'process_plugin "$@"' _ {}
else
    for plugin in "${COMBINED_PLUGINS[@]}"; do
        process_plugin "$plugin"
    done
fi

if [ "$DOWNLOAD_ALL_PLUGINS" == 'y' ]; then
    if [ -f "$CLOSED_PLUGINS_FILE" ]; then
        echo
        echo "Closed Plugin List: $CLOSED_PLUGINS_FILE"
        echo "Total closed plugins: $(wc -l < "$CLOSED_PLUGINS_FILE")"
    else
        echo
        echo "No closed plugins found."
    fi
    if [ -f "$OPENED_PLUGINS_FILE" ]; then
        echo
        echo "Opened Plugin List: $OPENED_PLUGINS_FILE"
        echo "Total opened plugins: $(wc -l < "$OPENED_PLUGINS_FILE")"
    else
        echo
        echo "No open plugins found."
    fi
fi
echo "Plugin download process completed."
