#!/bin/bash

# Base directory (script location)
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Configurable directories
WORDPRESS_WORKDIR="${WORDPRESS_WORKDIR:-$BASE_DIR/wordpress-plugins}"
PLUGIN_DIR="${PLUGIN_DIR:-$BASE_DIR/wp-content/plugins}"
MIRROR_DIR="${MIRROR_DIR:-$BASE_DIR/mirror}"
LOGS_DIR="${LOGS_DIR:-$BASE_DIR/plugin-logs}"

# Check for CF_WORKER_URL environment variable
if [ -z "$CF_WORKER_URL" ]; then
    echo "Error: CF_WORKER_URL environment variable is not set." >&2
    exit 1
fi

DOWNLOAD_BASE_URL="https://downloads.wordpress.org/plugin"

# Other variables
DOWNLOAD_LINK_API='y'

ADDITIONAL_PLUGINS=(
    "fast-translate"
    "img-show-box"
    "cloud-printing-for-woocommerce"
    "rt-filter-page-list"
    "author-profile-widget"
    "acquired-payments-gateway-for-woocommerce"
    "get-filesize-shortcode"
    "wp-minibar"
    "x3p0-legacy-widget"
    "supplemento-contrassegno-woocommerce"
    "lottery-number-supplier"
    "easyfonts"
    "bbp-notify-admins"
    "oplao-weather-professional-weather-widget"
    "honey-coinhive-captcha"
    "retrigger-notifications-gravity-forms"
    "billmate-order-management-for-woocommerce"
    "validator-pizza"
    "lh-ogp-meta-tags"
    "cf7-robly"
    "storeman"
    "polaroid-slider-lite"
    "tinymce-code-formatting"
    "auto-location-for-wp-job-manager"
    "affiliates-formidable"
    "jobsearch"
    "esb-url-extension"
    "remove-problematic-formatting-options-from-tinymce"
    "zitengine-skrill-manual-payment"
    "simple-diary"
    "footer-links-commando"
    "add-html-extension-to-specific-pages"
    "woocommerce-fulfillment-integration"
    "bookme-free-appointment-booking-system"
    "cl-wp-info"
    "restaurant-pickup-delivery-dine-in"
    "yapb-queue"
    "id-arrays"
    "wc-pickupp"
    "smallpay"
    "viglink-spotlight-by-shortcode"
    "dispensary-coupons"
    "settings-api"
    "wpshopgermany-handlerbund"
    "easy-options-page"
    "vkcommerce"
    "simple-blog"
    "wp-kasviewer"
    "elite-crypto-checkout"
    "add-entries-functionality-to-wpforms"
    "searchrelevance"
    "widget-display-filter"
    "extendago-wp-connection"
    "headlines"
    "beetle-tracking"
    "zensor"
    "f4-error-pages"
    "live-flight-radar"
    "instabot"
    "woocommerce-jamef"
    "email-address-obfuscation"
    "enigma-buttons"
    "tweetbacks-helper"
    "advanced-posts-listing"
    "metro-share-widget"
    "responsive-slides"
    "logged-in-conditional-text-widget"
    "image-counter"
    "woo-coinnexus"
    "remove-links-from-comments"
    "google-trends-shortcode"
    "wp-chessflash"
    "online-users"
    "ichigen-san"
    "adminquickbar"
    "wenprise-better-emails"
    "ab-simple-weather"
    "send-chat-tools"
    "wp-table-editor"
    "delivery-drivers-for-vendors"
    "carousel-for-awesome-filterable-portfolio"
    "go-night-pro"
    "seo404"
    "xenioo-web-chat"
    "wp2smfbridge"
    "statusmc"
    "get-post-content-shortcode"
    "woocommerce-rejoiner"
    "speakerdeck-embed"
    "wp-ie6update"
    "dbtable-to-datatable"
    "simple-proxy"
    "dominokit"
    "search-and-replace-text"
    "math-input-with-mathquill"
    "jituzu-tools"
    "map-addons-for-elementor-waze-map"
    "price-per-unit-for-woocommerce"
    "hamro-nepali-patro-calendar"
    "wp-genericfooter"
    "smartbroker"
    "lh-rdf"
    "fullscreen-mode-b-gone"
    "preserve-taxonomy-hierarchy"
    "dx2-post-hit-counter"
    "wp-academic-publications"
    "authorgrid"
    "billy"
    "contact-form-7-quiz-placeholders"
    "login-site-icon"
    "text-widget-oembed"
    "stock-message"
    "btcnew"
    "embed-and-integrate-etsy-shop"
    "republication-tracker-tool"
    "spark-gf-failed-submissions"
    "ajax-loader-cache"
    "htd-404"
    "bp-show-activity-liked-names"
    "wpb-product-size-charts-for-woocommerce"
    "exam-and-quiz-online-proctoring-with-lms-integration"
    "mail-queue"
    "qqworld-cloud-storage"
    "wp2flickr"
    "admin-help-docs"
    "gravity-forms-sticky-form"
    "aucor-core"
    "conditional-tags-shortcode"
    "ethereumads"
    "celtic-lti"
    "my-reading-library"
    "youtube-not-found"
    "wp-mailtrap"
    "socialhead-for-google-shopping-product-feeds-woo"
    "custom-error-log"
    "blog-to-html"
    "buddy-press-force-password-change"
    "markdown-highlighter"
    "flickr-thumbnails-widget"
    "better-admin-users-search"
    "ip2location-hello-greeting"
    "wpml-widget-filter"
    "news-keywords"
    "shellshock-check"
    "engagebay-add-on-for-contact-form-7"
    "page-whitelists"
    "unique-comments"
    "wp-client-testimonial"
    "trust-swiftly-verification"
    "pagelines-plus"
    "posts-by-category"
    "ai-disable-comments"
    "adblock-alerter"
    "publishing-checklist"
    "copyright-shortcode"
    "wp-content-permission"
    "pimp-my-site-christmas-edition"
    "lootly-for-woocommerce"
    "wp-seatingchart"
    "network-ping"
    "command-palette"
    "simple-primary-category"
    "blocks-for-gutenberg"
    "smart-calendar"
    "my-unique-content"
    "extra-checkout-fields-for-woocommerce"
    "chainwire-integration"
    "payments4g-4geeks-payments"
    "wp-maps"
    "ogoship-nettivarasto-api-for-woocommerce"
    "clima-freekitime"
    "ninja-forms-mailpoet"
    "ship-depot"
    "email-no-bot"
    "svg-spritemap"
    "xl-testimonial-carousel"
    "rtl-feed-presian"
    "add-user-autocomplete"
    "sastra-essential-addons-for-elementor"
    "notification-buddypress"
    "predictive-search"
    "jet-footer-code"
    "dr-flex"
    "enormail-sign-up-forms"
    "redirect-unattached-images"
    "mailster-piwik"
    "buy-now-plus"
    "modal-builder-block"
    "wpexperts-square-for-give"
    "accessible-web-badge"
    "ajax-load-more-for-elementor"
    "green-active-plugins"
    "wordpress-image-compressor"
    "related-documents-widget"
    "widgets-bundle"
    "statusnet-widget"
    "replace-protected-password"
    "secupress-ssl-fixer"
    "blockskit-import"
    "automated-registration-of-the-course"
    "wporg-plugin-embed"
    "wc-bulk-assign-linked-products"
    "gmap-point-list"
    "codoforum-sso"
    "git-sync"
    "woocommerce-simple-tickets"
    "post-slider-for-elementor"
    "wp-redirectify"
    "simple-self-styleable-pop-up"
    "qualtrics-survey-embeds"
    "wp-yahoo-smtp"
    "ls-icecast-onair"
    "gerar-certificado"
    "locale-auto-switch"
    "content-syndication-toolkit-reader"
    "wp-pic-tagger"
    "nfcbc-seo-plugin-add-on"
    "wp-e-commerce-bulk-category-pricing"
    "wp-pizzeria"
    "dashify"
    "recent-posts-for-custom-post-types"
    "crowd-control"
    "average-wysiwyg-helper"
    "post-content-slider"
    "1on1-secure"
    "sso-oauth-discord-by-path-digital"
    "coursecheck"
    "disable-user"
    "in-context-comments"
    "geo-redirects"
    "correct-my-headings"
    "contact-form-7-ui"
    "debug-bar-widgets"
    "admin-header-note"
    "picturebook"
    "all-in-one-widget"
    "wpb-image-widget"
    "text-styler"
    "archives-by-category-v20"
    "gmap-shortcode"
    "eychat"
    "anonymize-links"
    "easy-flashcards"
    "imagescaler-modded"
    "comments-avatar-lazyload"
    "mooberry-show-latest-posts"
    "referrer-input-for-contact-form-7"
    "stancer"
    "cinza-slider"
    "league-table-importer-for-sportspress"
    "wp-dropdown-hierarchial-category-ui"
    "grider-portfolio"
    "rapidmail-newsletter-e-mail-marketing-for-woocommerce"
    "mycred-retro"
    "stopwatch"
    "history-tracker"
    "disable-xml-rpc-fully"
    "headway-leaf-gravity-forms"
    "css-addons"
    "do-shortcode-widget-everywhere-wpshare247"
    "google-plus-favicon"
    "realtor-express"
    "odds-widgets"
    "wc-konnect-gateway"
    "add-infos-to-the-events-calendar"
    "advanced-page-template"
    "force-frame"
    "achprocessing"
    "dl-block"
    "woocommerce-interswitch-webpay-module"
    "trading-signals-widget"
    "array-partition"
    "restaurant-addon-for-elementor"
    "tinymce-for-wp-e-commerce-additional-description"
    "now-showing-at-local-venues"
    "aditum-gateway"
    "clicksend-lead-capture-form"
    "tidyhive-featured-posts"
    "genki-feedburner-sitestats"
    "prodibi-photo-library"
    "free-shipping-badge"
    "published-by"
    "custom-post-status"
    "jquery-cookie-law"
    "woocommerce-vat-checkout-add"
    "music-let-loose-mp3-audio-player"
    "wp-email-verify"
    "woo-tracking-the-courier-guy"
    "shortcode-shortcode"
    "akismet-credit-inserter"
    "xunhu-wechat-payment-for-easy-digital-downloads"
    "orbisius-random-name-generator"
    "wp-interakt-integration"
    "multi-rss"
    "spediex-for-theme"
    "hide-and-seek-header"
    "gocardless-wordpress-plugin"
    "woocomerce-favicon-cart-badge"
    "bbpress-code-snippets"
    "wp-cs-server-info"
    "gameplorers-wpcolorbox"
    "cotton-framework"
    "toursys-connect"
    "site-icon-pro"
    "zarinpal-payment-gateway-for-camptix"
    "wp-rest-headless"
    "geolocator"
    "new-admin-menus"
    "advanced-columns-block"
    "passwordless-wp"
    "all-in-one-sitemap-generator"
    "blocs-developer"
    "category-reminder"
    "image-automatic-height-width"
    "edit-lock"
    "print-label-and-tracking-code-for-dpd"
    "validar-certificados-de-cursos"
    "issue-manager"
    "tag-this"
    "gna-search-shortcode"
    "simple-lightgallery"
    "skaut-font"
    "sqrl-login"
    "simple-frontend-template-display"
    "category-pie"
    "monthchunks"
    "hypotext"
    "noindex-login"
    "woocommerce-chosen-variation-dropdowns"
    "rssjs"
    "racar-clear-cart-for-woocommerce"
    "accessibility-assistant"
    "mailersend-transactional-emails-for-woocommerce"
    "livechat-elementor"
    "remote-image-gallery-import"
    "hikari-internal-links"
    "linked-articles"
    "bp-multiple-forum-post"
    "taxonomy-taxi"
    "bg-rutube-embed"
    "mercalona-woo-etiqueta-correios"
    "linear-tag-cloud"
    "tiny-wow-colors"
    "bbcomments"
    "hayona-cookies"
    "euf-elementor-used-forms"
    "sexyrate"
    "likert-survey-master"
    "memberwunder"
    "dynamik-website-builder-and-beaver-builder-integration"
    "vision6-gravity-forms"
    "timezone-conversion-widget"
    "placemarks"
    "extract-text-from-image-etfi"
    "proof-factor-social-proof-notifications"
    "rss-enhancements-for-the-events-calendar"
    "wp-proxy"
    "paypalpro-woocommerce-addon"
    "gcal-events-list"
    "blog-crosspost"
    "gplus"
    "wpmastertoolkit"
    "wp-gatsby-markdown-exporter"
    "zoom-openseadragon"
    "docs"
    "sksdev-toolkit"
    "jp-latest-posts-shortcode"
    "g3client"
    "feed-key-generator"
    "ti-stat"
    "woo-airbuy-gateway"
    "sitemap-shortcode"
    "formatting-correcter"
    "mg-post-contributors"
    "mpower-woocommerce-payment-gateway"
    "moose-elementor-kit"
    "ayo-shortcodes"
    "remote-api"
    "user-insight"
    "anytrack-for-woocommerce"
    "ctrl-s"
    "cargo-shipping-location-for-woocommerce"
    "user-taxonomies"
    "import-xml-csv-listings-to-inventor-wp"
    "about-author-box"
    "universal-clocks"
    "ry-nice-upload-filename"
    "falang-for-yootheme-lite"
    "last-user-ip"
    "wp-api-json-feed"
    "blesk-companion"
    "category-listing-for-woocommerce"
    "yonox-add-multiple-posts"
    "responsive-divi-backgrounds"
    "print-posts"
    "the-twitter-profile"
    "notifier-to-slack"
    "payment-gateway-accept-blue-for-woocommerce"
    "woo-coupon-reminder"
    "code-explorer"
    "tha-hooks-interface"
    "browser-resize-images"
    "skeleton-key"
    "mailchimp-subscriber-chiclet"
    "pages-autolink"
    "video-blogger"
    "distance-rate-shipping-for-woocommerce"
    "in-stock-mailer-for-woocommerce"
    "cf7-paystack-add-on"
    "arcaptcha"
    "ai-blog-buddy"
    "wp-distance-calculator"
    "auto-sticky-post"
    "cf7-cc-avenue-add-on"
    "missing-menu-items"
    "uptime-robot-by-utopian-themes"
    "webtorrent"
    "baw-breach-avoider"
    "color-palette-generator"
    "key-figures"
    "affiliates-manager-stripe-payments-integration"
    "marketpress-statistics"
    "payment-method-checkout-fee-for-woocommerce"
    "simple-ad-authentication"
    "remote-my-project-playlist-plugin-for-wordpress"
    "tabbed-contents"
    "wc-hide-shipping-methods-except-pont"
    "auto-load-page-template"
    "post-title-icons"
    "marketplaces"
    "auto-post-expiration"
    "simple-calendar-for-elementor"
    "deactivate-xml-rpc-service"
    "wp-inline-comment-errors"
    "child-support-calculator"
    "pdalex-glossary"
    "lucidlms"
    "corona-test-results"
    "classroom"
    "map-to-address"
    "automated-postnord-shipping"
    "r3df-multisite-blog-slug-remover"
    "fast-post-lists"
    "fastcgi-finish-request-on-shutdown"
    "email-verify"
    "wp-prism-syntax-highlighter"
    "amazon-ranking"
    "smaly-widget"
    "specific-files-for-posts-and-pages"
    "logicaldoc"
    "play-it"
    "dns-prefetch"
    "pasazh"
    "adstxt-guru-connect"
    "news-in-pictures"
    "shokola-custom-white-label"
    "blogroll-in-posts"
    "sip-social-proof-woocommerce"
    "url-path-shortcodes"
    "easy-tooltips"
    "display-order-details"
    "simplistic-seo"
    "kosmos-esync-dashboard-connector"
    "twigpress"
    "replytocom-controller"
    "ls-wp-ccsearch"
    "set-front-page-post-count"
    "loyaltydog"
    "integration-of-zoho-crm-and-contact-form-7"
    "iteras"
    "recommended-links"
    "shared-users"
    "sherk-skills-landing-pages"
    "login-as-users"
    "dermandar"
    "cdyne-call-me"
    "reset-meta-box-positions"
    "irecharge"
    "all-in-one-avada-addons"
    "eelv-share-post"
    "cradsense-under-image-reloaded"
    "eshipper-commerce"
    "miniorange-discord-integration"
    "list-backorders-for-woocommerce"
    "recaptcha-wp"
    "dx-template-manager"
    "block-wpscan"
    "ns-custom-alert-popup-box"
    "disable-login-language-selector"
    "simple-pay-jp-payment"
    "gatorleads"
    "invelity-gls-online-connect"
    "content-upgrades"
    "sms-sender"
    "third-party-api-authentication"
    "responsive-mobile-select-menu"
    "ultimate-post-types"
    "pro-reports-for-memberpress"
    "blog-terminal"
    "wp-image-shrinker"
    "make-clickable-wp"
    "replace-howdy-with-other-word"
    "awebsome-comment-author-mail-validation"
    "wp-change-status-notifier"
    "nft-marketplace"
    "gf-gourl-add-on"
    "webmicro-nmi-woo-addon"
    "wlw-login"
    "formafzar"
    "en-gb-localisation"
    "acf-code-generator"
    "plugin-auditor"
    "caching-compatible-cookie-optin-and-javascript"
    "wp-authorcomment"
    "seo-defend"
    "ch-captcha"
    "ivolunteer"
    "fix-sitemap-xml-yoast-seo-for-yandex"
    "mosparo-integration"
    "integrate-woocommerce-with-vend"
    "kriptomat-cryptocurrency-price-widget"
    "exit-intent-pop-ups-by-maxtraffic"
    "pepro-cf7-database"
    "jquery-superbox-image"
    "wp-popup-optin"
    "orbisius-simple-feedback"
    "web-manifest"
    "edd-paytm-gateway"
    "vanilla-bean-themelogin"
    "postman-widget"
    "delivery-drivers-manager"
    "lana-contact-form"
    "admin-restriction"
    "simple-logo-carousel"
    "translate-wp-with-google-languages-translator"
    "rsv-360-view"
    "user-security-tools"
    "proofratings"
    "claim-gst"
    "quicklogin"
    "wp-business-hours"
    "footer-code"
    "no-more-admin"
    "multisite-auditor"
    "ci-image-widget"
    "featured-post-type-widget"
    "avaibook"
    "pay-advantage"
    "exclude-from-search"
    "slideshow-wp"
    "magic-liquidizer-responsive-navigationbar"
    "simple-lyteload"
    "import-hotels-from-csv-for-bookingcom-affiliates"
    "kenzap-team-members-gutenberg-blocks"
    "wooinventory-lite"
    "the-events-calendar-private-category"
    "halloween-countdown-widget"
    "around-this-date-in-the-past"
    "buddypress-groups-import"
    "generate-legacy-mobile-menu"
    "regenerate-product-lookup-table-for-woocommerce"
    "lightgallerywp"
    "wc-variations-ajax"
    "cf7-multiupload"
    "cipher"
    "zia3-css-fullscreen-background-slideshow"
    "multiple-email-recipients-wc"
    "better-code-editor"
    "gamipress-learndash-points-importer"
    "hellodialog"
    "custom-upload-folders-plus"
    "wikilink"
    "hitmeter-counter"
    "enable-default-editor"
    "add-to-circle-widget"
    "tradebit-download-shop"
    "custom-post-type-privacy"
    "nofollow-external-links-seo"
    "elite-notification"
    "admin-social-shares"
    "vzaar-media-management"
    "easy-post-re-order"
    "oxyplug-prefetch"
    "m7-go-top"
    "image-gallery-box-by-crudlab"
    "wpblast"
    "image-to-text"
    "transport-and-business-locator"
    "dts-debugger"
    "japan-tenki"
    "user-importer-and-generator"
    "ci-publish-facebook"
    "good-reads"
    "qqpress"
    "yamap-block-gutenberg"
    "wpheka-web-server-information"
    "wpgo-power-charts-lite"
    "plugin-tags"
    "rss-add-image-header"
    "role-based-tax-exclusion"
    "helio"
    "remove-page-title-from-elementor-pages-by-default"
    "text-to-share"
    "id-services"
    "advanced-custom-fields-position-field"
    "russocialknopki-23"
    "bookvault"
    "wordpress-logger"
    "wcs-web-maintenance"
    "my-gstock-portfolio"
    "citations"
    "ltl-freight-quotes-estes-edition"
    "easy-blog-ideas"
    "rexpansive-page-builder"
    "weekly-time-table"
    "tweakr"
    "bamboo-migration"
    "easy-pixels-contact-form-extension-by-jevnet"
    "comments-with-hypercommentscom"
    "my-marginalia"
    "responsive-contact-form-mailchimp-extension"
    "sherk-carousel-banners"
    "my-settings"
    "ultimate-wp-reset"
    "woo-variations-select2"
    "similar-products"
    "hm-product-catalog"
    "iande"
    "wp-rslogin"
    "swtor-server-status"
    "ebiziner"
    "wm-zoom"
    "fantacampionatoonline"
    "recrawler"
    "wp-image-cropper"
    "jquery-archives"
    "sb-hotel-rooms"
    "auto-logout-extended"
    "qodax-checkout-manager"
    "robowoo"
    "dokan-store-carousel"
    "sane-visual-editor"
    "aco-currency-switcher-for-woocommerce"
    "products-stock-manager-with-excel"
    "the-time-ago"
    "client-and-product-testimonials"
    "merge-minify-refresh-clear-caches"
    "dashboard-technorati-reactions-extended"
    "bangla-al-quran"
    "digital-checkout-for-woocommerce"
    "paystack-sprout-invoices"
    "sunrise"
    "custom-viewer-count-widget"
    "easy-digital-downloads-store-hours"
    "currysearch"
    "mdl-shortcodes"
    "tweets-rotator-2013"
    "wp-excel-2-db"
    "woocommerce-fat-zebra-gateway"
    "pwp-lytebox"
    "skreverb"
    "aptivada-for-wp"
    "products-rearrange-woocommerce"
    "child-pages-card"
    "google-play-store-app-search-and-insert"
    "twitterfountain"
    "gf-registration-for-editor-role"
    "yaam-youtube-autoplay-and-mute"
    "book-cover"
    "fx-categories-widget"
    "auto-delete-unattached-media"
    "cxx-margin-and-padding-utility"
    "multi-social-favicon"
    "wp-fail2ban-logging"
    "bp-user-widgets"
    "booktrope-counter"
    "sudoku-shortcode"
    "statsfc-form"
    "related-categories-for-woocommerce"
    "custom-cart-and-checkout-info-for-woocommerce"
    "gou-manage-related-posts-similar-posts"
    "just-simple-accordions"
    "wany-chat"
    "theme-helper"
    "hearken"
    "crypto-price-and-stats"
    "unofficial-wordpresscom-google-maps-shortcode"
    "woocommerce-molds"
    "buddypress-custom-profile-filters"
    "bi-clean-cache"
    "hangman"
    "add-post-type-instructions"
    "easy-menu-handler"
    "newsletter-subscription-widget-for-sendblaster"
    "sf-generate-tags"
    "mu-plugins-tool"
    "runkeeper-plugin"
    "multimediamonster-cookie-law-authorization"
    "multi-author-adsense"
    "supplier-and-purchase-order-management-for-woocommerce"
    "dka-child-pages-widget"
    "ft-remove-private-from-post-titles"
    "embed-grooveshark"
    "crazy-call-to-action-box"
    "fix-category-count"
    "woo-laundry-pickup-delivery-service"
    "plagium"
    "melibo-chatbot"
    "goauth"
    "orbisius-simple-shortlink"
    "incredible-font-awesome"
    "th-reviews-bar"
    "shipbob-express-rates"
    "cf7-signature"
    "tg-customized-tags"
    "wp-audio-verse"
    "add-ids-to-header-tags"
    "flickr-auto-poster"
    "mymood"
    "redirect-gravatar-requests"
    "wprecaptcha"
    "advanced-comments-widget"
    "million-shades-toolkit"
    "duplicate-content-cure"
    "buddytask"
    "adatosystems-friday-zmanim"
    "bulk-postmeta-editor"
    "colorful-tag-cloud"
    "immediate-list-building-pro-lite"
    "blog-directory-blogville"
    "re-welcome"
    "recent-posts-block"
    "menu-card"
    "safer-email-link"
    "mailster-mailjet"
    "contact-form-7-with-chatwork"
    "theme-blvd-simple-permalink"
    "recaptcha-by-roger"
    "directorist-wpml-integration"
    "weart-category-posts-widget"
    "ip-tools"
    "guest-support"
    "filepicker-media-uploader"
    "social-author-box"
    "gmo-page-transitions"
    "audio-editor-recorder"
    "modula-envira-migrator"
    "awesome-testimonials"
    "shorten2ping-ng"
    "honey-coinhive-widget"
    "my-maintenance-mode"
    "presswell-art-direction"
    "simpleticker"
    "admin-big-width"
    "cloud-sso-single-sign-on"
    "wp-super-settings"
    "quickblog-wp-blog-exporter"
    "page-navigation-menu"
    "easy-video-publisher"
    "wp-image-zoomify"
    "tailored-tools"
    "alojapro-widget"
    "postpoll"
    "minecraft-map-to-image"
    "listamester"
    "dynamic-shortcode-widget-for-elementor"
    "fussballde-widget-includer"
    "kenzap-timeline"
    "admin-dark-mode"
    "avatars"
    "perfect-tense"
    "wordmagic-content-writer"
    "movie-grabber"
    "wpbookmark"
    "easy-hide-admin-menu-items"
    "vc-gallery"
    "mw-wp-hacks"
    "woocommerce-users-custom-meta-search"
    "products-csv-importer-for-woocommerce"
    "eighties-bbpress"
    "credit-card-number-generator"
    "paywerk-payments"
    "category-buttons"
    "auto-insert-title-to-link"
    "wp-article-feedback"
    "unik-ultimate-pricing-table"
    "flowplayer-wrapper"
    "belcoio"
    "tito"
    "css-share-buttons"
    "escape-html"
    "typewriter"
    "contact-form-7-anti-spambot"
    "simple-wp-firephp"
    "htm-on-pages"
    "laika-pedigree-tree"
    "wpachievements-free"
    "techsarathy-sendy-cf7-integration"
    "et-mailing"
    "who-is-online-now"
    "drivefx-woocommerce"
    "inplayer-paywall"
    "optimate-ads"
    "boleto-cora"
    "youram-youtube-embed"
    "rss-to-posts"
    "master-table-for-elementor"
    "wumii-comment"
    "gdpr-notice-original"
    "quick-coming-soon"
    "location-picker"
    "show-widget-area-names"
    "insert-callout"
    "best-foot-forward"
    "pushstate"
    "swiss-5-cent-rounding"
    "expresspigeon-webform-widget"
    "easy-mls-listings-import"
    "advanced-exit-popup"
    "older-posts-widget"
    "disable-right-click-powered-by-pixterme"
    "google-reader"
    "wp-permalauts-extended"
    "search-simple-fields"
    "coinbase-commerce-for-contact-form-7"
    "gf-form-locator"
    "cf7-autosaver"
    "color-bg-tag-cloud"
    "class-widget-ats-text"
    "moderate-pingbacks"
    "thinkit-wp-contact-form"
    "post-share-count"
    "kakao-talk-link"
    "surbma-salesautopilot-shortcode"
    "siiimple"
    "instant-page-load"
    "mon-laboratoire"
    "gallery-image-content-post"
    "mstw-csv-exporter"
    "contact-bot"
    "import-cdn-remote-images"
    "meta-extensions"
    "rbl-navigator"
    "wpgalleryimage-shortcode"
    "edd-status-board"
    "woo-product-variations-popup"
    "rr-fictitious-payment-for-woocommerce"
    "ymlp"
    "paidy-wc"
    "decode-reply-tool"
    "cat-pass"
    "remove-script-stylesheet-versions"
    "shortlinks"
    "wordpress-23-login"
    "wp-shortcm"
    "faster-with-stats"
    "cool-sticky-menu"
    "daumview"
    "fazae-wp-booster"
    "dictation-speech-recognition"
    "image-zoom-in-out"
    "sopro"
    "acf-onyx-poll"
    "wp-video-playlist"
    "linkbuildr"
    "post-type-slider-for-customizr"
    "all-districts-news"
    "ayah-of-the-day"
    "forcesslswitcher"
    "rinf-news-ticker"
    "christian-science-bible-lesson-subjects"
    "bambuser-for-wordpress"
    "announcements-ticker"
    "idsk-demodata"
    "cyclopress"
    "xola-bookings-for-tours-activities"
    "contact-form-7-radio-field-mandatory"
    "catalog-organization"
    "onlyoffice"
    "wp-last-updated"
    "plugin-reviews"
    "sb-tab-widget"
    "2performant-link2"
    "wh-tweaks"
    "all-countries-counties-for-wc"
    "wp-api-customizer"
    "imagecomply"
    "setupad"
    "fatora-payment-getway"
    "livepreview"
    "gphotos"
    "greenerwp"
    "myspeakingpage"
    "case-study"
    "login-page-logo-change"
    "appmax"
    "log-user-stats"
    "change-howdy"
    "wp-bookmarks"
    "pramadillo-activecampaign-email-preference-center"
    "wp-custom-login-branding"
    "cool-coming-soon"
    "ams-page-scroll-back-to-top"
    "in-the-loop"
    "local-open-sans"
    "lobia"
    "bookingkit"
    "jp-students-exam-admit-card-generator"
    "wpos-lite-version"
    "eidogo-for-wordpress"
    "menu-cart-for-woocommerce"
    "wp-multi-author"
    "k-outdated-plugin-checker-k-opc"
    "fullscreen-menu"
    "customizer-browser-history"
    "aliiike-web-recommender-system"
    "email-notification-on-admin-login"
    "woocommerce-epdq-payment-gateway"
    "acymailing-integration-for-eventon"
    "remove-cart-products"
    "uptime-robot"
    "calculate-values-with-shortcodes"
    "irm-newsroom"
    "placepress"
    "categories-page"
    "fny-database-backup"
    "social-media-engine"
    "display-your-zenodo-community"
    "mp-smart-redirect"
    "twittrup"
    "memorista"
    "wordplurk-improve"
    "malcure-security-suite"
    "ns-countdown"
    "linkmarklet"
    "nexa-blocks"
    "comment-validation-computy"
    "get-your-ebay-feedback"
    "apsense-share-button"
    "pagespot"
    "simple-running-log"
    "ipag-woocommerce"
    "wp-responsive-video"
    "grab-call-code"
    "ldap-integration"
    "responsive-media-gallery"
    "open-badge-factory"
    "jcolorboxzoom"
    "smart-wetransfer"
    "fullcalendar"
    "popup-seo-optimized"
    "edunext-openedx-integrator"
    "powers-triggers-of-woo-to-chat"
    "random-page-redirect-for-wordpress"
    "woocommerce-dynamic-pricing-exclusions"
    "okv-oauth"
    "bubble-chat"
    "church-social"
    "keywords-highlight-tool"
    "animated-featured-image"
    "rest-api-cache"
    "shortcode-support-for-elementor-templates"
    "apimo"
    "monitor-pages"
    "woocommerce-payment-reminder"
    "add-login-text"
    "firebug-lite"
    "insert-video-with-shortcode"
    "menu-obfuscator"
    "wp-clean-characters"
    "dessky-snippets"
    "jkl-unit-converter"
    "yarpp-for-bbpress"
    "template-widget-for-beaver-builder"
    "github-bitbucket-project-lister"
    "painterro"
    "favorites-posts"
    "drainware-comments-filter"
    "radio-islam"
    "redisearch"
    "kazoo-templated-content"
    "woo-vendor-module-add-ons-woocommerce"
    "rendr"
    "pageviews-counter"
    "bookster"
    "taghound-media-tagger"
    "interactive-uk-regional-map"
    "iphone-widget"
    "woo-quantity-based-shipping-rate"
    "greet-bubble"
    "arca-payment-gateway"
    "wordpass"
    "permalink-persian-to-english"
    "mygooglepluswidget"
    "mobilemonkey-x-ray-installer"
    "zurb-foundation-5-clearing-gallery"
    "sample-reviews"
    "daily-inspiration"
    "wpp-ip-blocker"
    "mydirtyhobby-affiliate-sign-up"
    "better-media-library-fields"
    "image-credits"
    "many-sidebars"
    "list-all-authors"
    "woocommerce-pesapal-standard-gateway"
    "easy-video-gallery"
    "followthis-topic-box"
    "event-calendar-exporter"
    "wp-mock-slider"
    "ivenc-calculator"
    "bp-search"
    "oxyplug-preload"
    "current-moon-information"
    "tinycode"
    "wp-tweetbox"
    "groups-blog-protect"
    "wp-edit-homepage"
    "faq-and-answers"
    "woocommerce-single-product-search-redirect"
    "image-carousel-addon-for-beaver-builder"
    "load-html-files"
    "acf-yith-woocommerce-compare-support"
    "tcbd-auto-refresher"
    "woocommerce-mark-orders-as-complete"
    "responsive-subheader"
    "mh-display-prayer-times"
    "statsfc-prediction-league"
    "ghost-inspector"
    "tw-disable-revisions"
    "sagepay-direct-gateway-for-woocommerce"
    "snap-a-site"
    "all-social-share-options"
    "wp-kradeno"
    "cookie-message"
    "custom-fields-in-rss"
    "custombot"
    "admin-bookmarks"
    "kontur-copy-code-button"
    "custom-sitemap-template"
    "buddyfence"
    "goanimate"
    "taro-external-permalink"
    "custom-dashboard"
    "wp-login-door"
    "digital-business-card"
    "chunks"
    "cc-quebec-tax-calculator"
    "simpul-youtube-by-esotech"
    "gravity-forms-user-restrictions"
    "fetenweb-image-src-metatag"
    "sbs-seat-booking-system"
    "simple-upcoming"
    "wp-clippy"
    "amazing-wp-e-commerce"
    "gentime"
    "lh-booking-widget"
    "kernel-video-sharing"
    "indiv-for-tablepress"
    "page-template-usage-info"
    "gf-prevent-duplicates"
    "gravity-forms-reset-button"
    "custom-excerpt-length"
    "bns-chesscom-badge"
    "special-teaser-widget"
    "cw-author-info"
    "wpxlsdata"
    "sokan-integration"
    "hoo-document-importer"
    "wp-typeit"
    "mk-smart-player"
    "remove-links-and-scripts"
    "surbma-datepicker-localization-for-gravity-forms"
    "simple-require-login"
    "commenter-data"
    "ignore-code"
    "kommentvalasz"
    "simple-cookie-control"
    "disable-wp-plugin-updates-advance"
    "scheduled-contnet-by-streama"
    "ultimate-downloadable-products-for-woocommerce"
    "menu-badge"
    "debug-bar-plugin-activation"
    "children-pages"
    "nokaut-offers-box"
    "bbp-api"
    "akismet-notifier"
    "geopost"
    "login-non-admin-redirection"
    "json-rest-api-force-ssl"
    "alternative-payments-for-woocommerce"
    "alipay-donate"
    "onecom-migrator"
    "society6-widget"
    "pay-what-you-want"
    "nested-ordered-lists-for-block-editor"
    "woocommerce-payment-gateway-for-saferpay"
    "woocommerce-digital-download-free-shipping"
    "post-reading-times"
    "smwpp-cta"
    "grabber-for-qqworld-auto-save-images"
    "media-library-downloader"
    "stomp"
    "freightview-for-woocommerce"
    "sitecare-score"
    "realty-portal-advanced-search"
    "shortcode-with-preview-block"
    "upload-files-by-default-when-inserting-media"
    "widget-output-filters"
    "wp-login-delay"
    "theme-importer"
    "instant-approval-payment-gateway"
    "freetobook-responsive-widget"
    "gosign-notification-and-alert-block"
    "minicrm-woocommerce-sync"
    "dragblock"
    "hackathon"
    "sync-media-with-aws-s3-cloudfront"
    "concertpress"
    "anteraja"
    "block-permissions"
    "seo-gpt"
    "customizer-block-cf7"
    "preenchimento-automatico-cep-brasil"
    "catchtheweb-barclay-epdq-payment-gateway"
    "wc-product-tabs-plus"
    "admin-hangul-font"
    "social-wiggle"
    "text-message-contact-form"
    "notifications-woocommerce"
    "delivery-area-with-google-maps"
    "spotify-embed-creator"
    "wonder-fontawesome"
    "tailored-easy-exclude"
    "user-age-calculator"
    "website-speed-optimization"
    "wordpress-sinhala-comments"
    "datadev-jadlog-for-woocommerce"
    "easy-basic-authentication"
    "external-content"
    "user-groups-restrictions"
    "show-content-by-user-level"
    "wp-load-gallery"
    "cogwork"
    "simple-login-page-customizer"
    "shipping-rates-for-hk-post"
    "lianamailer-gf"
    "social-stream"
    "cut-the-lights"
    "wp-post-background"
    "tag-linker"
    "deploy-helper"
    "recstory"
    "dynamic-page-header-images"
    "melascrivi"
    "shauno-simple-gallery"
    "alchemist-ajax-upload"
    "seo-http-headers-easy"
    "idbbee"
    "transifex-wp-translation"
    "payment-fees-for-woocommerce"
    "bee-pricing-table"
    "near-login"
    "namasha-by-mdesign"
    "weedmaps-menu-embed"
    "bible"
    "matchchat"
    "anchors-menu"
    "amp-google-analytics-4-support"
    "nm-font-awesome"
    "acf-google-maps-radius-search"
    "arabic-comments-number"
    "wpamanuke-prettyphoto-wp-plugins"
    "simple-halloween-decoration-for-your-page"
    "woo-jenga-payment-gateway"
    "ajax-load-more-for-terms"
    "store-opening-closing-hours-manager"
    "keyword-filter"
    "fuseforms-for-mailchimp"
    "responsive-investment-calculator"
    "wp-smtp-contact-form"
    "just-highlight"
    "empty-meta-cleanup-for-wp-job-manager"
    "post-rating-and-review"
    "eliminate-render-blocking-css"
    "coral-remote-images"
    "static-optimizer"
    "rikkis-wp-social-icons"
    "top-songs"
    "wc-product-3d-viewer"
    "userlast"
    "wp-login-attempts"
    "codeshop-amazon-affiliate"
    "title-rus-to-eng"
    "corona-virus-covid19-banner"
    "custom-menu-for-wc-my-account"
    "lenbox-cbnx"
    "appmaps"
    "show-authors-in-page-list"
    "author-stats"
    "es-custom-fields-interface"
    "page-slideshow"
    "embed-stl"
    "parallax-scroll-wp"
    "metadata-seo"
    "wp-hotmail-smtp"
    "vodpod-embedder"
    "buoy"
    "cf7-woo-product-registration"
    "wp-experience-api"
    "student-inquiry-listing"
    "easy-symlinks"
    "maphilight"
    "octrace-support"
    "video-accessibility"
    "graphcdn"
    "my-google-books-library"
    "smntcs-wapuu-widget"
    "woo-paylate"
    "add-link-on-copied-text"
    "tims-nextcloud-sso-oauth2"
    "mockpress"
    "eshopswithiq"
    "post-categories-tree"
    "dusky-dark-mode"
    "country-flags-info-widget"
    "edd-coupon-counter"
    "wpcontenteditable"
    "clearbit"
    "custom-js"
    "browsers"
    "myanmar-currency-exchange-rates"
    "widget-area-chooser"
    "lh-page-links-to"
    "e-billing-payment-gateway"
    "better-learndash-api"
    "simple-magazine"
    "wp-feedticker"
    "woo-admin-app-connector"
    "scripted-api"
    "enhanced-calendar"
    "happy-birthday-reminder"
    "admin-bar-queries"
    "wp-emoji"
    "dropdown-navigation-menus"
    "simpleform-contact-form-submissions"
    "codedeyo-google-trends-for-bloggers"
    "character-countdown"
    "smntcs-image-dimensions"
    "naver-blog-api"
    "cleanse-rel-category-tag"
    "woo-track-list-and-sample-player"
    "qbank-dam-connector"
    "0gravatar"
    "wp-tournament-registration"
    "article-difficulty-level"
    "iris-color-picker-enhancer"
    "custom-columns"
    "show-qr-url"
    "wt-co-authors"
    "media-category"
    "simple-cron"
    "favicon-notifications"
    "wp-responsive-and-easy-tabs"
    "bulk-generate-thumbnails"
    "emissary-for-woocommerce"
    "wp-autosave"
    "post-as-subdomain-free"
    "wp-tumblr"
    "tp-show-product-images-on-checkout-page-for-woocommerce"
    "xml-sitemaps-manager"
    "terms-before-download"
    "exploit-scanner-for-active-theme"
    "shop-sms-notifications"
    "azigen"
    "paylink"
    "islamic-phrases"
    "multisite-xml-rpc"
    "maniac-seo"
    "secure-paste"
    "sukhjot-google-map"
    "better-rest-endpoints"
    "404-to-301-redirect-by-felix"
    "remove-ozh-unobstrusive-credits-in-footer"
    "footer-flyout-widget"
    "advanced-control-manager"
    "ccs-navigation"
    "shortcodes-for-font-awesome"
    "javascript-framebreaker"
    "embed-twine"
    "gdpr-cache-scripts-styles"
    "advanced-order"
    "cloud-image-gallery"
    "youtube-video-feed"
    "acf-display"
    "display-webgl-shader"
    "featured-blogs-list"
    "banggood-dropshipping"
    "simple-fancybox"
    "target-blank-to-button-block"
    "sticky-menu-block"
    "ss-old-urls"
    "yabandpay-for-woocommerce"
    "ird-slider"
    "replace-contents"
    "woocommerce-fields-for-japan"
    "shuftipro-kyc-identity-verification"
    "proper-redirect"
    "my-restaurant-menu"
    "mycred-wp-simple-pay-addon"
    "navarak-code-highlighter"
    "hide-site-title"
    "no-update-reminder"
    "woo-category-discount"
    "tennisthor"
    "vwriter-guest-post"
    "chrome-frame"
    "xcompliant"
    "lime-talk-live-chat"
    "falling-snow"
    "shopeat-button"
    "plugin-list"
    "rufilenametranslit"
    "mycopyright"
    "wp-snakemember-integration"
    "check-baidu-result"
    "cc-roundabout-3d-slider"
    "fx-ssl"
    "ipay-ghana-woocommerce"
    "movable-anything"
    "dynamic-front-end-heartbeat-control"
    "bf-advanced-images"
    "plot-prices"
    "relative-posts"
    "ajaxed-registration-page"
    "dp-debug-menu"
    "codup-wp-freshsales"
    "comment-move"
    "activity-logs"
    "tinymce-entities-patch"
    "gk-sms"
    "instruct"
    "vm-menu-reorder"
    "google-news-unique-permalink-id"
    "comment-privileges-by-post"
    "flexy-seo"
    "omnivore"
    "show-product-variations-for-woocommerce"
    "ab-tasty"
    "wp-autobuzz"
    "woo-out-of-stock-last"
    "bitcoin-lightning-publisher"
    "mxp-pixnet2wp"
    "flat-login"
    "audiotracks"
    "wp-speech-balloon"
    "custom-canonical"
    "vertical-timeline-responsive"
    "wp-tag-manager"
    "ebible"
    "dynaposty-dynamic-landing-pages"
    "siteswp-wc-print-orders-brazil"
    "users2csv"
    "gallery2-importer"
    "auto-scrolling-testimonials"
    "easy-feature-lists"
    "primer-by-chloedigital"
    "n0wpscan"
    "colorlab"
    "arconix-testimonials"
    "xmap"
    "simple-google-authorship-and-avatar"
    "minapper-wechat-search"
    "brozzme-switch-duplicate"
    "draugiem-pase"
    "nicebackgrounds"
    "simply-static-callback"
    "flash-demo-import"
    "wp-pukiwiki"
    "debug-bar-hook-log"
    "wp-gold-charts"
    "featured-post-exclude-category-for-genesis"
    "snow-effect"
    "attachment-page-comment-control"
    "payhub-payment-gateway-for-woocommerce"
    "elpix-rate-post-in-comment"
    "leadback"
    "cf7-4dem-it-extension"
    "edd-extra-notes-on-checkout"
    "brozzme-material-loading"
    "digital-marketing-agency-templates-for-elementor"
    "mf-plus-wpml"
    "codemirror-for-post-editor"
    "my-facebook-tags"
    "display-your-checkatrade"
    "acf-tab-merge"
    "wc-payment-gateway-line-pay"
    "current-age"
    "wp-avertere"
    "guardiankey"
    "buddypress-admin-notifications"
    "contributors-posts"
    "covid-19-coronavirus-viral-pandemic-prediction-tools-free-version"
    "preload-current-images"
    "wp-jobs2careers"
    "ezplayer"
    "polylang-dynamic-sitemap-generator"
    "azurecurve-shortcodes-in-widgets"
    "wp-select-box-navi"
    "include-url"
    "custom-taxonomy-templates"
    "broken-image-checker"
    "omnishop"
    "wp-seo-yoast-integration-mq-translate"
    "tagposts"
    "extend-kses"
    "ls-oembed-support-for-scratch-mit"
    "ns-widget-recent-comments"
    "admin-column-custom"
    "wp-tracking-manager"
    "random-content-shortcode"
    "wp-showhide-elements"
    "auto-link-tags"
    "wpm-user-sync"
    "wp-team-members"
    "livestreamcom-thumbnail-widget"
    "taro-clockwork-post"
    "rdv-category-image"
    "debug-log"
    "hover-video-preview"
    "very-basic-content-restriction"
    "logged-in-as"
    "customcat-helper"
    "show-featured-image-size-in-admin-topbar"
    "gallerio"
    "steam-group-widget"
    "simple-regenerate-slug"
    "easy-invoice"
    "wp-loginout"
    "beacon-for-helpscout"
    "taxcaster"
    "invitations-for-slack"
    "wp-ranking-pro"
    "remove-quick-edit"
    "edd-disable-purchase-receipt"
    "evolution-footer-scripts"
    "web4pro-about-me"
    "tickethero"
    "geo-location-comments"
    "bookkeeping"
    "google-plus-stream-for-wordpress"
    "brandnestor"
    "posts-list-block"
    "xmail-the-right-way"
    "project-force-field"
    "gpsiesembed"
    "paguelofacil"
    "basic-front-end-login"
    "ssl-fixer"
    "wp-country"
    "woo-ups-shipping"
    "simple-crm-profile-page"
    "pushnami-web-push-notifications"
    "floating-admin-button"
    "beagency-lite"
    "shootq-wordpress-contact-form-7-integration"
    "ogp-generator"
    "imagemeta"
    "best-post-page"
    "simple-front-end-edit-buttons"
    "cf7-redirect"
    "dboptimizer"
    "author-details"
    "osomblocks"
    "new-popular-posts-widget"
    "ux-flatsome-addons"
    "fake-login-area"
    "eth-escape-headspace2"
    "aajoda-testimonials"
    "ihs-geo-location"
    "nemesis-all-in-one"
    "wp-log-action"
    "simple-faqs"
    "regenerate-thumbnails-html"
    "kuvatfi-embed"
    "slcm"
    "comment-approval-notification"
    "share-button-klass"
    "comment-reply-by-admins-notifier"
    "feature-on-homepage"
    "passwordless-authentication"
    "footer-design-for-wpbakery-page-builder"
    "ltl-freight-quotes-rl-edition"
    "rdpano"
    "debugwp"
    "wp-smiley-switcher"
    "lazy-load-disable"
    "scroll-to-top-or-bottom"
    "stick-post-widget"
    "post-author-filter"
    "custom-options"
    "catch-duplicate-switcher"
    "baidu-textcensor"
    "edd-changelog"
    "wp-flot"
    "actignite"
    "affiliates-for-woocommerce"
    "kickstarter-tracker-widget"
    "cluevo-lms-extension-gdocs-modules"
    "wc-innocard-loyalty-integration"
    "copy-to-clipboard"
    "hide-comments-are-closed"
    "fancy-product-for-elementor"
    "akismet-htaccess-writer"
    "wpebanover"
    "disable-wp-sitemap"
    "quick-event-calendar"
    "ehive-object-details"
    "contact-form-7-charts"
    "awesome-progess-bar"
    "freetobook-review-widget"
    "wp-version-in-query-string-modifier"
    "sharing-club"
    "capitalize-text-input"
    "wp-mtn-momo"
    "answering-contact-form"
    "nikeplus"
    "wp-tic-tac-toe"
    "aged-content-message"
    "group-contact-buttons-pht-blog"
    "funnel"
    "add-google-social-profiles-to-knowledge-graph-box"
    "read-more-for-feed-burner-feed"
    "easy-testimonial"
    "currentlywatching"
    "brighttalk-wp-shortcode"
    "de-hide-updraftplus-dashboard-news"
    "responsive-slide"
    "cedcommerce-onbuy-integration"
    "sticky-back2top-for-genesis"
    "mobile-banner"
    "marketing-automation-by-azexo"
    "znavcarousel"
    "simple-social-feed"
    "responsive-video-for-wp"
    "wp-figlet"
    "apoyl-grabweixin"
    "riveted"
    "wp-revision-list"
    "mighty-content-locker"
    "cheq-essentials-go-to-market-security"
    "ultimate-image-gallery"
    "statsfc-player-rater"
    "jeba-horizontal-timeline"
    "contact-form-db-for-enfold"
    "subre-product-subscription-for-woo"
    "niso-carousel"
    "stylish-social-share"
)

# Define user agents with weights
declare -A USER_AGENTS
USER_AGENTS=(
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"]=5
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"]=7
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"]=6
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36 Edg/91.0.864.54"]=5
    ["Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 OPR/77.0.4054.277"]=3
    ["Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (iPad; CPU OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Vivaldi/4.0"]=1
    ["Mozilla/5.0 (Android 11; Mobile; rv:68.0) Gecko/68.0 Firefox/88.0"]=1
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"]=15
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/534.36"]=12
)

CLOSED_PLUGINS_FILE="${WORDPRESS_WORKDIR}/closed_plugins.txt"
LAST_VERSION_FILE="${WORDPRESS_WORKDIR}/last_versions.txt"
PARALLEL_JOBS=1

DOWNLOAD_ALL_PLUGINS='n'
LIST_ONLY='n'
ALL_PLUGINS_FILE="${WORDPRESS_WORKDIR}/wp-plugin-svn-list.txt"

DELAY_DOWNLOADS='n'
DELAY_DURATION=5

FORCE_UPDATE='n'
CACHE_ONLY='n'

mkdir -p "$WORDPRESS_WORKDIR" "$MIRROR_DIR" "$LOGS_DIR"
DEBUG_MODE=0

while getopts "p:dalD:t:fc" opt; do
    case ${opt} in
        p ) PARALLEL_JOBS=$OPTARG ;;
        d ) DEBUG_MODE=1 ;;
        a ) DOWNLOAD_ALL_PLUGINS='y' ;;
        l ) LIST_ONLY='y' ;;
        D ) DELAY_DOWNLOADS=$OPTARG ;;
        t ) DELAY_DURATION=$OPTARG ;;
        f ) FORCE_UPDATE='y' ;;
        c ) CACHE_ONLY='y' ;;    # New option for cache-only
        \? ) echo "Usage: $0 [-p PARALLEL_JOBS] [-d] [-a] [-l] [-D DELAY_DOWNLOADS] [-t DELAY_DURATION] [-f] [-c]" 1>&2; exit 1 ;;
    esac
done

debug_log() {
    if [ "$DEBUG_MODE" -eq 1 ]; then
        echo "[DEBUG] $1" >&2
    fi
}

get_random_user_agent() {
    echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
}

get_latest_version_and_download_link() {
    local plugin=$1
    debug_log "Checking latest version and download link for $plugin"
    
    local api_url="https://api.wordpress.org/plugins/info/1.0/${plugin}.json"
    local user_agent=$(get_random_user_agent)
    local api_response=$(curl -s -H "User-Agent: $user_agent" "$api_url")
    
    if echo "$api_response" | jq -e '.error' >/dev/null; then
        local error_message=$(echo "$api_response" | jq -r '.error')
        if [ "$error_message" = "closed" ]; then
            echo "closed"
            return 2
        else
        echo "Error: $error_message for plugin $plugin" >&2
        return 1
        fi
    fi
    
    local version=$(echo "$api_response" | jq -r '.version // empty')
    local download_link=$(echo "$api_response" | jq -r '.download_link // empty')
    
    if [ -n "$version" ] && [ -n "$download_link" ]; then
        echo "$version $download_link"
        return 0
    else
        echo "Error: Cannot fetch version or download link for $plugin" >&2
        return 1
    fi
}

download_plugin() {
    local plugin=$1
    local version=$2
    local api_download_link=$3
    local output_file="${MIRROR_DIR}/${plugin}.${version}.zip"
    local header_file="${LOGS_DIR}/${plugin}.${version}.headers"
    local constructed_download_link="${DOWNLOAD_BASE_URL}/${plugin}.${version}.zip"
    local download_link

    if [ "$DEBUG_MODE" -eq 1 ]; then
        debug_log "API-provided download link for $plugin: $api_download_link"
        debug_log "Constructed download link for $plugin: $constructed_download_link"
    fi

    if [ "$DOWNLOAD_LINK_API" == 'y' ] && [ -n "$api_download_link" ]; then
        download_link="$api_download_link"
        debug_log "Using API-provided download link for $plugin: $download_link"
    else
        download_link="$constructed_download_link"
        debug_log "Using constructed download link for $plugin: $download_link"
    fi

    debug_log "Downloading $plugin version $version through Cloudflare Worker"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)
    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o /dev/null "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    else
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o "$output_file" "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    fi

    if [ $? -eq 0 ]; then
        if [ "$CACHE_ONLY" == 'y' ]; then
            debug_log "Plugin $plugin version $version cached successfully."
            return 0
        fi

        local file_size=$(stat -c%s "$output_file")
        if [ "$file_size" -lt 1000 ]; then
            echo "Error: Downloaded file for $plugin is too small (${file_size} bytes). Possible download issue." >&2
            return 1
        fi

        local source=$(grep -i "X-Source:" "$header_file" | cut -d' ' -f2 | tr -d '\r')
        if [ "$source" == "R2" ]; then
            debug_log "Successfully downloaded $plugin version $version from R2 storage"
        elif [ "$source" == "WordPress" ]; then
            debug_log "Successfully downloaded $plugin version $version from WordPress"
            debug_log "R2 bucket saving for plugin zip occurred"
        else
            debug_log "Skipped download for $plugin $version zip (already exists locally)"
        fi

        return 0
    else
        echo "Error: Failed to download $plugin version $version" >&2
        return 1
    fi
}

save_plugin_info() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.json"

    debug_log "Saving plugin json metadata for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying metadata download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    if [ "$CACHE_ONLY" == 'y' ]; then
        # When in cache-only mode, output to /dev/null
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin metadata for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache json metadata for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            if [ "$source" = "R2" ]; then
                debug_log "json metadata for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "json metadata for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin json occurred"
            else
                debug_log "json metadata for $plugin version $version saved (json metadata file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save json metadata for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

fetch_and_save_checksums() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.checksums.json"

    debug_log "Fetching and saving checksums for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying checksums download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    debug_log "Sending request to Worker for checksums: CF_WORKER_URL?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"

    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin checksums for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache checksums for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        debug_log "Received response with status code: $status_code"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            debug_log "Response source: $source"
            if [ "$source" = "R2" ]; then
                debug_log "Checksums for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "Checksums for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin checksums occurred"
            else
                debug_log "Checksums for $plugin version $version saved (checksums file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save checksums for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

process_plugin() {
    local plugin=$1

    # Check if the plugin is already known to be closed
    if grep -q "^$plugin$" "$CLOSED_PLUGINS_FILE" 2>/dev/null; then
        echo "Plugin $plugin is known to be closed. Skipping."
        return 0
    fi

    echo "Processing plugin: $plugin"

    VERSION_AND_LINK=$(get_latest_version_and_download_link "$plugin")
    local version_check_status=$?
    
    if [ $version_check_status -eq 1 ]; then
        echo "Skipping $plugin due to version fetch error."
        return 1
    elif [ $version_check_status -eq 2 ]; then
        echo "Plugin $plugin is closed. Skipping download and processing."
        echo "$plugin" >> "$CLOSED_PLUGINS_FILE"
        if save_plugin_info "$plugin" "closed"; then
            debug_log "Successfully saved json metadata for closed plugin $plugin."
        else
            debug_log "Failed to save json metadata for closed plugin $plugin."
        fi
        return 0
    fi
    
    LATEST_VERSION=$(echo "$VERSION_AND_LINK" | cut -d' ' -f1)
    API_DOWNLOAD_LINK=$(echo "$VERSION_AND_LINK" | cut -d' ' -f2-)

    debug_log "Latest version for $plugin: $LATEST_VERSION"
    debug_log "API download link for $plugin: $API_DOWNLOAD_LINK"

    STORED_VERSION=$(grep "^$plugin" "$LAST_VERSION_FILE" | awk '{print $2}')
    debug_log "Stored version for $plugin: $STORED_VERSION"

    if [ "$CACHE_ONLY" != 'y' ] && [ "$LATEST_VERSION" == "$STORED_VERSION" ] && [ -f "${MIRROR_DIR}/${plugin}.${LATEST_VERSION}.zip" ]; then
        echo "$plugin is up-to-date and exists in mirror directory. Skipping download..."
    else
        start_time=$(date +%s.%N)

        if download_plugin "$plugin" "$LATEST_VERSION" "$API_DOWNLOAD_LINK"; then
            if [ "$CACHE_ONLY" != 'y' ]; then
                sed -i "/^$plugin/d" "$LAST_VERSION_FILE"
                echo "$plugin $LATEST_VERSION" >> "$LAST_VERSION_FILE"
            fi
            echo "Successfully processed $plugin."
        else
            echo "Error: Failed to process $plugin." >&2
        fi

        end_time=$(date +%s.%N)
        duration=$(echo "$end_time - $start_time" | bc)
        printf "Time taken for %s: %.4f seconds\n" "$plugin" "$duration"
    fi

    if save_plugin_info "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully saved json metadata for $plugin."
    else
        debug_log "Failed to save json metadata for $plugin."
    fi

    if fetch_and_save_checksums "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully fetched and saved checksums for $plugin."
    else
        debug_log "Failed to fetch and save checksums for $plugin."
    fi
}

populate_all_plugins() {
    if [ ! -f "$ALL_PLUGINS_FILE" ] || [ "$LIST_ONLY" == 'y' ]; then
        echo "Fetching list of all WordPress plugins..."
        svn list https://plugins.svn.wordpress.org/ | sed 's/\/$//g' > "$ALL_PLUGINS_FILE"
        plugin_count=$(wc -l < "$ALL_PLUGINS_FILE")
        echo "Plugin list (${plugin_count}) saved to $ALL_PLUGINS_FILE"
    fi
    
    if [ "$LIST_ONLY" == 'n' ]; then
        ALL_PLUGINS=()
        while IFS= read -r line; do
            ALL_PLUGINS+=("$line")
        done < "$ALL_PLUGINS_FILE"
        echo "Loaded ${#ALL_PLUGINS[@]} plugins."
    fi
}

if [ "$LIST_ONLY" == 'y' ]; then
    populate_all_plugins
    echo "Plugin list created. Exiting without downloading."
    exit 0
fi

if [ "$DOWNLOAD_ALL_PLUGINS" == 'y' ]; then
    populate_all_plugins
    COMBINED_PLUGINS=("${ALL_PLUGINS[@]}")
else
    if [ ! -d "$PLUGIN_DIR" ]; then
        echo "Warning: Plugin directory $PLUGIN_DIR does not exist or is invalid."
        PLUGIN_LIST=()
    else
        PLUGIN_LIST=($(ls -d "$PLUGIN_DIR"/*/ 2>/dev/null | xargs -n 1 basename))

        if [ ${#PLUGIN_LIST[@]} -eq 0 ]; then
            echo "No plugins found in $PLUGIN_DIR."
        fi
    fi

    COMBINED_PLUGINS=(${PLUGIN_LIST[@]} ${ADDITIONAL_PLUGINS[@]})
    COMBINED_PLUGINS=($(echo "${COMBINED_PLUGINS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
fi

if [ ${#COMBINED_PLUGINS[@]} -eq 0 ]; then
    echo "No plugins to download. Exiting."
    exit 0
fi

mkdir -p "$MIRROR_DIR"
touch "$LAST_VERSION_FILE"

if [ "$PARALLEL_JOBS" -gt 1 ]; then
    echo "Running in parallel with $PARALLEL_JOBS jobs..."
    # First, export all variables including USER_AGENTS
    export DOWNLOAD_BASE_URL MIRROR_DIR LAST_VERSION_FILE DEBUG_MODE DOWNLOAD_LINK_API LOGS_DIR ALL_PLUGINS_FILE DOWNLOAD_ALL_PLUGINS LIST_ONLY CF_WORKER_URL DELAY_DOWNLOADS DELAY_DURATION FORCE_UPDATE CACHE_ONLY USER_AGENTS

    # Then, export the functions
    export -f process_plugin get_latest_version_and_download_link download_plugin debug_log populate_all_plugins save_plugin_info get_random_user_agent fetch_and_save_checksums
    printf "%s\n" "${COMBINED_PLUGINS[@]}" | xargs -P $PARALLEL_JOBS -I {} bash -c 'process_plugin "$@"' _ {}
else
    for plugin in "${COMBINED_PLUGINS[@]}"; do
        process_plugin "$plugin"
    done
fi

if [ -f "$CLOSED_PLUGINS_FILE" ]; then
    echo
    echo "Closed Plugin List:"
    cat "$CLOSED_PLUGINS_FILE" | sort | uniq || true
    echo
    echo "Total closed plugins: $(wc -l < "$CLOSED_PLUGINS_FILE")"
    echo
else
    echo
    echo "No closed plugins found."
    echo
fi
echo "Plugin download process completed."
