#!/bin/bash

# Base directory (script location)
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Configurable directories
WORDPRESS_WORKDIR="${WORDPRESS_WORKDIR:-$BASE_DIR/wordpress-plugins}"
PLUGIN_DIR="${PLUGIN_DIR:-$BASE_DIR/wp-content/plugins}"
MIRROR_DIR="${MIRROR_DIR:-$BASE_DIR/mirror}"
LOGS_DIR="${LOGS_DIR:-$BASE_DIR/plugin-logs}"

# Check for CF_WORKER_URL environment variable
if [ -z "$CF_WORKER_URL" ]; then
    echo "Error: CF_WORKER_URL environment variable is not set." >&2
    exit 1
fi

DOWNLOAD_BASE_URL="https://downloads.wordpress.org/plugin"

# Other variables
DOWNLOAD_LINK_API='y'

ADDITIONAL_PLUGINS=(
    "newpost-catch"
    "woo-bulk-edit-products"
    "speed-contact-bar"
    "emails-verification-for-woocommerce"
    "server-ip-memory-usage"
    "nofollow-for-external-link"
    "ad-invalid-click-protector"
    "gf-entries-in-excel"
    "woocommerce-custom-product-tabs-lite"
    "storefront-product-sharing"
    "snow-monkey-editor"
    "fonts"
    "front-end-editor"
    "yith-woocommerce-product-bundles"
    "easy-affiliate-links"
    "pdf-light-viewer"
    "cp-contact-form-with-paypal"
    "better-robots-txt"
    "newsletters-lite"
    "tiled-gallery-carousel-without-jetpack"
    "wp-google-analytics"
    "wp-ultimate-review"
    "travelpayouts"
    "wpb-woocommerce-product-slider"
    "xo-featured-image-tools"
    "woocommerce-easy-booking-system"
    "zemanta"
    "woocommerce-predictive-search"
    "wunderground"
    "wpstream"
    "cms-commander-client"
    "wp-super-cache-clear-cache-menu"
    "attachments"
    "zoho-mail"
    "wpc-variations-radio-buttons"
    "real-custom-post-order"
    "tag-groups"
    "hide-featured-image"
    "jquery-smooth-scroll"
    "change-admin-email-setting-without-outbound-email"
    "woocommerce-easy-table-rate-shipping"
    "wp-recaptcha-integration"
    "woo-authorize-net-gateway-aim"
    "ayecode-connect"
    "product-video-gallery-slider-for-woocommerce"
    "wp-call-button"
    "woo-advanced-product-size-chart"
    "wp101"
    "gravityformscli"
    "smartsupp-live-chat"
    "login-as-user"
    "portfolio"
    "armember-membership"
    "mailchimp-wp"
    "canvas"
    "wp-maximum-execution-time-exceeded"
    "cwis-antivirus-malware-detected"
    "custom-menu-wizard"
    "mihdan-index-now"
    "hashbar-wp-notification-bar"
    "wc-product-customer-list"
    "wp-author-date-and-meta-remover"
    "embed-privacy"
    "oneclick-whatsapp-order"
    "bbpress-notify-nospam"
    "audio-and-video-player"
    "blog-filter"
    "quick-event-manager"
    "location-weather"
    "wp-linkedin-auto-publish"
    "yith-woocommerce-popup"
    "redirect-404-error-page-to-homepage-or-custom-page"
    "faster-image-insert"
    "add-to-any-subscribe"
    "invite-anyone"
    "italy-cookie-choices"
    "wp-help"
    "xo-security"
    "mantenimiento-web"
    "facebook-photo-fetcher"
    "woocommerce-cart-tab"
    "multi-column-tag-map"
    "woocommerce-colors"
    "video-background"
    "mysterythemes-demo-importer"
    "nelio-ab-testing"
    "finale-woocommerce-sales-countdown-timer-discount"
    "styler-for-wpforms"
    "simple-google-analytics"
    "user-avatar"
    "gtmetrix-for-wordpress"
    "yoast-seo-settings-xml-csv-import"
    "widgetize-pages-light"
    "jetsticky-for-elementor"
    "import-users-from-csv"
    "metronet-tag-manager"
    "wpmbytplayer"
    "woo-usps-simple-shipping"
    "wp-testimonial-with-widget"
    "anspress-question-answer"
    "currency-switcher-woocommerce"
    "multilanguage"
    "slidedeck-lite-for-wordpress"
    "automatic-updater"
    "worpit-admin-dashboard-plugin"
    "nextgen-gallery-optimizer"
    "juiz-social-post-sharer"
    "smart-variations-images"
    "contact-form-7-add-confirm"
    "yith-woocommerce-tab-manager"
    "subscriptions-for-woocommerce"
    "woocommerce-products-per-page"
    "wp-private-content-plus"
    "responsive-coming-soon"
    "favorites"
    "themebeez-toolkit"
    "woo-paypal-gateway"
    "front-end-pm"
    "mstore-api"
    "user-verification"
    "learnpress-bbpress"
    "codistoconnect"
    "imdb-video-movie-trailers"
    "restore-classic-widgets"
    "updraftcentral"
    "smart-custom-fields"
    "easyjobs"
    "date-time-picker-field"
    "webpushr-web-push-notifications"
    "ultimate-maps-by-supsystic"
    "acf-image-aspect-ratio-crop"
    "wp-svg-images"
    "crazyegg-heatmap-tracking"
    "eventprime-event-calendar-management"
    "contact-form-7-modules"
    "breadcrumb-trail"
    "cforms2"
    "comment-link-remove"
    "cf7-to-zapier"
    "wufoo-shortcode"
    "custom-post-template"
    "mediavine-control-panel"
    "ht-slider-for-elementor"
    "theme-demo-import"
    "woocommerce-bulk-discount"
    "simple-link-directory"
    "carousel-horizontal-posts-content-slider"
    "ultimate-tag-cloud-widget"
    "groundhogg"
    "simple-google-sitemap-xml"
    "custom-order-statuses-woocommerce"
    "child-themify"
    "copy-the-code"
    "colorlib-coming-soon-maintenance"
    "better-search"
    "customize-my-account-for-woocommerce"
    "easy-woocommerce-discounts"
    "facebook-likebox-widget-and-shortcode"
    "scripts-to-footerphp"
    "disable-wp-rest-api"
    "desert-companion"
    "mb-custom-post-type"
    "wp-coder"
    "gallery-slider-for-woocommerce"
    "zip-recipes"
    "bulky-bulk-edit-products-for-woo"
    "wp-lightbox-bank"
    "easy-modal"
    "affilinet-performance-module"
    "floating-social-bar"
    "sticky-side-buttons"
    "wpscan"
    "wp-email-template"
    "visual-footer-credit-remover"
    "pure-chat"
    "woo-redsys-gateway-light"
    "geo-mashup"
    "fv-top-level-cats"
    "wp-sheet-editor-bulk-spreadsheet-editor-for-posts-and-pages"
    "wp-datepicker"
    "webappick-pdf-invoice-for-woocommerce"
    "meow-lightbox"
    "ml-slider-lightbox"
    "woo-custom-stock-status"
    "rsvp"
    "no-page-comment"
    "cryptx"
    "multibanco-ifthen-software-gateway-for-woocommerce"
    "wp-rest-cache"
    "aco-woo-dynamic-pricing"
    "wp-snow-effect"
    "wp-cycle"
    "nginx-champuru"
    "colissimo-shipping-methods-for-woocommerce"
    "baw-login-logout-menu"
    "one-click-ssl"
    "the-preloader"
    "wp-display-header"
    "wp-social-reviews"
    "woo-coupon-usage"
    "buddydrive"
    "export-user-data"
    "wc-smart-cod"
    "wp-memory-usage"
    "design-upgrade-learndash"
    "patreon-connect"
    "user-login-history"
    "forum-server"
    "gtm-kit"
    "multisite-clone-duplicator"
    "sms-alert"
    "baidu-submit-link"
    "fourteen-colors"
    "juicer"
    "tinymce-templates"
    "media-library-organizer"
    "wpsite-show-ids"
    "mystickysidebar"
    "hide-metadata"
    "tag-manager-header-body-footer"
    "link-juice-keeper"
    "db-cache-reloaded-fix"
    "wpupper-share-buttons"
    "blogger-importer-extended"
    "product-quantity-for-woocommerce"
    "music-player-for-woocommerce"
    "elespare"
    "editorplus"
    "product-blocks"
    "wp-dashboard-notes"
    "blog-designer-for-post-and-widget"
    "login-page-styler"
    "sliced-invoices"
    "countdown-timer"
    "woostify-sites-library"
    "webba-booking-lite"
    "organize-series"
    "gf-form-multicolumn"
    "conveythis-translate"
    "wp-updates-notifier"
    "disqus-conditional-load"
    "embed-form"
    "codeflavors-vimeo-video-post-lite"
    "xml-sitemaps"
    "tablesome"
    "dreamhost-automated-migration"
    "disable-embeds"
    "jquery-lightbox-for-native-galleries"
    "wp-cfm"
    "front-end-only-users"
    "addfunc-head-footer-code"
    "anwp-post-grid-for-elementor"
    "far-future-expiry-header"
    "post-tags-and-categories-for-pages"
    "image-hover-effects-ultimate-visual-composer"
    "clickcease-click-fraud-protection"
    "rss-feed-widget"
    "bosa-elementor-for-woocommerce"
    "bit-integrations"
    "debloat"
    "wplr-sync"
    "all-in-one-video-pack"
    "taxonomy-metadata"
    "migrate-to-liquidweb"
    "catch-themes-demo-import"
    "amazon-product-in-a-post-plugin"
    "review-schema"
    "wp-hide-backed-notices"
    "team-showcase-supreme"
    "prime-mover"
    "embed-pdf-viewer"
    "export-woocommerce-customer-list"
    "video-popup"
    "wp-header-images"
    "plugin-central"
    "easyreservations"
    "my-wp-translate"
    "th-advance-product-search"
    "embed-calendly-scheduling"
    "button-contact-vr"
    "buddypress-group-email-subscription"
    "theme-junkie-custom-css"
    "elex-woocommerce-catalog-mode"
    "wp-auto-republish"
    "printify-for-woocommerce"
    "carousel-without-jetpack"
    "uber-login-logo"
    "mechanic-visitor-counter"
    "points-and-rewards-for-woocommerce"
    "options-for-twenty-twenty-one"
    "powerpack-addon-for-beaver-builder"
    "woocommerce-apg-weight-and-postcodestatecountry-shipping"
    "wp-less"
    "bogo"
    "jquery-validation-for-contact-form-7"
    "responsive-select-menu"
    "custom-meta-widget"
    "elastic-email-sender"
    "slicewp"
    "google-analytics-opt-out"
    "import-facebook-events"
    "if-so"
    "sparkle-demo-importer"
    "woocommerce-extra-product-sorting-options"
    "quick-paypal-payments"
    "wordpress-plugin-for-simple-google-adsense-insertion"
    "create-block-theme"
    "instawp-connect"
    "login-rebuilder"
    "woorewards"
    "woo-pdf-invoice-builder"
    "cleaner-gallery"
    "apppresser"
    "wp-media-category-management"
    "auth0"
    "oik"
    "custom-icons-for-elementor"
    "meks-easy-social-share"
    "shortcode-for-current-date"
    "ultimate-reviews"
    "mediavine-create"
    "yith-custom-login"
    "what-would-seth-godin-do"
    "woopra"
    "one-stop-shop-woocommerce"
    "plugins"
    "theme-translation-for-polylang"
    "website-monetization-by-magenet"
    "graphina-elementor-charts-and-graphs"
    "snow-monkey-forms"
    "ipanorama-360-virtual-tour-builder-lite"
    "cresta-whatsapp-chat"
    "wps-bidouille"
    "event-espresso-decaf"
    "minify-html-markup"
    "nextgen-scrollgallery"
    "datafeedr-api"
    "apply-online"
    "wp-pagenavi-style"
    "news-announcement-scroll"
    "lightning-advanced-unit"
    "keyword-statistics"
    "demo-importer-plus"
    "parsi-font"
    "flexible-posts-widget"
    "meta-generator-and-version-info-remover"
    "advanced-random-posts-widget"
    "conditional-shipping-for-woocommerce"
    "download-now-for-woocommerce"
    "wp-serverinfo"
    "hide-admin-bar-from-non-admins"
    "glossary-by-codeat"
    "woo-gift-cards-lite"
    "knit-pay"
    "materialis-companion"
    "ba-book-everything"
    "easy-image-gallery"
    "csv-importer"
    "c3-cloudfront-clear-cache"
    "woo-product-carousel-slider-and-grid-ultimate"
    "disable-feeds"
    "wp-mail-catcher"
    "file-renaming-on-upload"
    "booking-calendar-contact-form"
    "dropship-me"
    "ghostkit"
    "rtl-tester"
    "mas-woocommerce-brands"
    "show-posts"
    "slider-video"
    "flexible-invoices"
    "instantsearch-for-woocommerce"
    "yith-woocommerce-waiting-list"
    "ari-fancy-lightbox"
    "insert-script-in-headers-and-footers"
    "pardot"
    "responsivevoice-text-to-speech"
    "themify-popup"
    "image-horizontal-reel-scroll-slideshow"
    "rss-includes-pages"
    "better-analytics"
    "post-slider-and-carousel"
    "lazy-loading-responsive-images"
    "taxonomy-images"
    "html5-jquery-audio-player"
    "link-checker"
    "custom-post-type-widgets"
    "woocommerce-quickpay"
    "re-add-text-justify-button"
    "analytics-cat"
    "buddyforms"
    "twitter-auto-publish"
    "ads-for-wp"
    "flying-scripts"
    "wp-revisions-control"
    "lightbox-pop"
    "blank-slate"
    "developer"
    "unconfirmed"
    "woo-conditional-product-fees-for-checkout"
    "wp-manutencao"
    "wt-woocommerce-related-products"
    "simple-urls"
    "woocommerce-eu-vat-compliance"
    "pixcodes"
    "new-social-media-widget"
    "flying-pages"
    "wp-expand-tabs-free"
    "vod-infomaniak"
    "fluency-admin"
    "search-in-place"
    "download-attachments"
    "audioigniter"
    "arconix-faq"
    "embedly"
    "basic-google-maps-placemarks"
    "vk-post-author-display"
    "email-customizer-for-woocommerce"
    "meks-time-ago"
    "affiliatex"
    "advanced-ads-adsense-in-feed"
    "sprout-invoices"
    "debug-bar-console"
    "album-and-image-gallery-plus-lightbox"
    "lazy-load-for-comments"
    "wp-popup-builder"
    "advanced-tinymce-configuration"
    "wptools"
    "post-type-archive-links"
    "woo-single-product-page-customizer"
    "send-emails-with-mandrill"
    "convertkit-for-woocommerce"
    "tlp-portfolio"
    "mb-sitemap-generator"
    "wp-map-block"
    "gourl-woocommerce-bitcoin-altcoin-payment-gateway-addon"
    "wonderplugin-slider-lite"
    "responsive-slider"
    "constant-contact-api"
    "socialize"
    "zakeke-interactive-product-designer"
    "youtube-showcase"
    "delicious-recipes"
    "pearl-header-builder"
    "title-and-nofollow-for-links"
    "rumbletalk-chat-a-chat-with-themes"
    "404-redirection"
    "read-more-without-refresh"
    "responsive-gallery-grid"
    "specia-companion"
    "widget-for-eventbrite-api"
    "wppizza"
    "travel-agency-companion"
    "aqua-page-builder"
    "wpvivid-backup-mainwp"
    "hd-quiz"
    "entry-views"
    "coupon-creator"
    "bookit"
    "duplicate-page-or-post"
    "wc-product-table-lite"
    "wc-hide-shipping-methods"
    "colorlib-404-customizer"
    "maxgalleria"
    "jsm-show-post-meta"
    "storefront-footer"
    "rabbit-loader"
    "woocommerce-gift-wrapper"
    "slider-hero"
    "wpc-grouped-product"
    "smart-image-resize"
    "wp-fullcalendar"
    "map-block-gutenberg"
    "music-player-for-elementor"
    "wp-ajaxify-comments"
    "simple-side-tab"
    "latest-posts-block-lite"
    "jetwidgets-for-elementor"
    "acf-rus-to-lat"
    "new-image-gallery"
    "updater"
    "anything-popup"
    "hellobar"
    "team"
    "music-store"
    "meta-slider-and-carousel-with-lightbox"
    "seo-booster"
    "jupiterx-core"
    "cyr-and-lat"
    "easy-svg"
    "modal-for-elementor"
    "collectchat"
    "woocomm-popup-cart-ajax"
    "wp-realtime-sitemap"
    "search-replace"
    "yoco-payment-gateway"
    "ws-form"
    "quiz-cat"
    "easy-google-adsense"
    "flare"
    "login-or-logout-menu-item"
    "simplemodal-login"
    "simple-floating-menu"
    "wpkoi-templates-for-elementor"
    "nmedia-user-file-uploader"
    "qode-essential-addons"
    "wp-twitter-feeds"
    "wp-search-with-algolia"
    "wp-cafe"
    "login-security-recaptcha"
    "weather-effect"
    "seo-image-optimizer"
    "manual-image-crop"
    "nginx-cache"
    "drop-shadow-boxes"
    "flush-opcache"
    "responsive-lightbox-lite"
    "activitypub"
    "prevent-direct-access"
    "magic-content-box-lite"
    "gravity-forms-addons"
    "mail-mint"
    "legal-pages"
    "amazonsimpleadmin"
    "wp-twilio-core"
    "woo-currency"
    "404-redirected"
    "gallery-lightbox-slider"
    "white-label"
    "upprev"
    "lightbox-popup"
    "zoho-crm-forms"
    "wp-mailto-links"
    "limit-attempts"
    "uptolike-share"
    "wp-rss-retriever"
    "zippy"
    "jf3-maintenance-mode"
    "product-variation-swatches-for-woocommerce"
    "popularis-extra"
    "add-logo-to-admin"
    "add-expires-headers"
    "woocommerce-product-sku-generator"
    "add-category-to-pages"
    "woocommerce-quick-buy"
    "antihacker"
    "bb-header-footer"
    "abc-pricing-table"
    "wp-blog-post-layouts"
    "addon-so-widgets-bundle"
    "woo-poly-integration"
    "booking-ultra-pro"
    "groovy-menu-free"
    "woo-category-slider-grid"
    "thim-elementor-kit"
    "blockonomics-bitcoin-payments"
    "blockart-blocks"
    "integration-for-szamlazzhu-woocommerce"
    "timed-content"
    "formilla-live-chat"
    "mega-elements-addons-for-elementor"
    "mail-subscribe-list"
    "intercom"
    "superb-social-share-and-follow-buttons"
    "business-hours-indicator"
    "wp-child-theme-generator"
    "themefarmer-companion"
    "woocommerce-paynl-payment-methods"
    "w4-post-list"
    "decorator-woocommerce-email-customizer"
    "testimonial-slider"
    "mobile-smart"
    "woo-notification"
    "spiffy-calendar"
    "premium-seo-pack"
    "wp-test-email"
    "review-widgets-for-booking-com"
    "nginx-mobile-theme"
    "cooked"
    "jc-importer"
    "wp-vgwort"
    "sunshine-photo-cart"
    "classic-editor-and-classic-widgets"
    "wp-conditional-captcha"
    "acf-qtranslate"
    "companion-sitemap-generator"
    "wp-smart-preloader"
    "menubar"
    "genesis-layout-extras"
    "miniorange-login-with-eve-online-google-facebook"
    "woo-correios-calculo-de-frete-na-pagina-do-produto"
    "woocommerce-ajax-cart"
    "wunderwp"
    "stylish-cost-calculator"
    "woo-instamojo"
    "disable-blog"
    "accessibility-checker"
    "cf7-multi-step"
    "whp-hide-posts"
    "democracy-poll"
    "wp-google-search"
    "doofinder-for-woocommerce"
    "job-postings"
    "wp-yandex-metrika"
    "wp-force-https"
    "yeloni-free-exit-popup"
    "wp-job-portal"
    "onlywire-bookmark-share-button"
    "cb-change-mail-sender"
    "xo-event-calendar"
    "carousel-block"
    "wpvulnerability"
    "fv-all-in-one-seo-pack"
    "jw-player-7-for-wp"
    "adplugg"
    "mycryptocheckout"
    "vk-link-target-controller"
    "agile-store-locator"
    "mediapress"
    "fusion"
    "pagebar"
    "wp-spell-check"
    "pi-woocommerce-order-date-time-and-type"
    "accordion-blocks"
    "woo-product-variation-gallery"
    "wp-hide-dashboard"
    "adamrob-parallax-scroll"
    "clone-guard-security-scanning"
    "variation-swatches-style"
    "user-meta"
    "booster-extension"
    "scroll-top"
    "bp-registration-options"
    "attachment-pages-redirect"
    "ultimate-auction"
    "woo-cart-all-in-one"
    "woo-product-timer"
    "aco-product-labels-for-woocommerce"
    "jet-style-manager"
    "simple-301-redirects-addon-bulk-uploader"
    "simple-yearly-archive"
    "xpro-elementor-addons"
    "simple-file-list"
    "woo-product-tables"
    "namaste-lms"
    "wc-password-strength-settings"
    "handl-utm-grabber"
    "wcboost-wishlist"
    "bit-form"
    "wordpress-navigation-list-plugin-navt"
    "controlled-admin-access"
    "hyperdb"
    "gutenify"
    "wp-rest-api-controller"
    "woo-related-products-refresh-on-reload"
    "icon-block"
    "wp-multilang"
    "advanced-classifieds-and-directory-pro"
    "ga-germanized"
    "docket-cache"
    "podlove-web-player"
    "featured-articles-lite"
    "search-console"
    "wp-stripe-checkout"
    "scriptless-social-sharing"
    "fully-background-manager"
    "file-upload-types"
    "woo-checkout-for-digital-goods"
    "highlight-search-terms"
    "google-tag-manager"
    "surbma-divi-gravity-forms"
    "related-post"
    "salt-shaker"
    "liveforms"
    "analytics-insights"
    "holler-box"
    "vertical-news-scroller"
    "events-widgets-for-elementor-and-the-events-calendar"
    "learnpress-prerequisites-courses"
    "pre-party-browser-hints"
    "code-syntax-block"
    "videojs-html5-player"
    "childify-me"
    "wpml-widgets"
    "seo-data-transporter"
    "responsive-mortgage-calculator"
    "memberful-wp"
    "seed-fonts"
    "service-box"
    "opengraph"
    "woocommerce-product-tabs"
    "adaptive-images"
    "mooberry-book-manager"
    "duo-wordpress"
    "ajax-login-and-registration-modal-popup"
    "wc-ajax-product-filter"
    "unusedcss"
    "shared-files"
    "smooth-scroll-up"
    "admin-bar-disabler"
    "onelogin-saml-sso"
    "woocommerce-accepted-payment-methods"
    "pagination"
    "gift-up"
    "jetpack-backup"
    "wp-featured-content-slider"
    "androapp"
    "plugin-detective"
    "wp-google-my-business-auto-publish"
    "brightcove-video-connect"
    "magical-posts-display"
    "smooth-back-to-top-button"
    "magical-addons-for-elementor"
    "cyrlitera"
    "feature-a-page-widget"
    "granular-controls-for-elementor"
    "woocommerce-accommodation-bookings"
    "easy-contact"
    "theme-switcha"
    "smtp2go"
    "memcached"
    "login-logout"
    "wp-copyright-protection"
    "easy-add-thumbnail"
    "uni-woo-custom-product-options"
    "dk-new-medias-image-rotator-widget"
    "quick-contact-form"
    "clone-posts"
    "wps-menu-exporter"
    "ry-woocommerce-tools"
    "gridlist-view-for-woocommerce"
    "pronamic-google-maps"
    "my-eyes-are-up-here"
    "wp-persian"
    "theme-blvd-layout-builder"
    "photoswipe-masonry"
    "animated-typing-effect"
    "change-login-logo"
    "genesis-portfolio-pro"
    "wp-bootstrap-blocks"
    "woocommerce-simply-order-export"
    "banner-management-for-woocommerce"
    "rave-woocommerce-payment-gateway"
    "wp-optimize-by-xtraffic"
    "wp-activity-log-for-woocommerce"
    "blogger-to-wordpress-redirection"
    "hide-shipping-method-for-woocommerce"
    "layout-grid"
    "wp-widget-disable"
    "gs-facebook-comments"
    "genesis-featured-page-advanced"
    "share-buttons"
    "html-forms"
    "th-all-in-one-woo-cart"
    "wp-twitter-feed"
    "alx-extensions"
    "woo-refund-and-exchange-lite"
    "featured-image-admin-thumb-fiat"
    "simple-user-avatar"
    "wpschoolpress"
    "secondary-title"
    "woo-custom-add-to-cart-button"
    "gallery-images-ape"
    "custom-css-and-javascript"
    "the-plus-addons-for-block-editor"
    "mortgage-calculator"
    "learnpress-import-export"
    "edwiser-bridge"
    "hashthemes-demo-importer"
    "fancy-facebook-comments"
    "stylish-price-list"
    "pdf-forms-for-contact-form-7"
    "paytm-payments"
    "under-construction-maintenance-mode"
    "flexible-table-block"
    "lw-all-in-one"
    "wp-deferred-javascripts"
    "livechat-woocommerce"
    "customizer-reset-by-wpzoom"
    "woocommerce-login-and-registration"
    "semrush-seo-writing-assistant"
    "mimetypes-link-icons"
    "calendar-event"
    "monster-widget"
    "integrate-google-drive"
    "log-deprecated-notices"
    "flo-forms"
    "permalink-finder"
    "wp-document-revisions"
    "automatic-domain-changer"
    "wpcore"
    "woo-abandoned-cart-recovery"
    "bulk-move"
    "woo-product-excel-importer"
    "justified-gallery"
    "wpgetapi"
    "ultimate-security-checker"
    "plugin-load-filter"
    "sharedaddy"
    "simple-google-maps-short-code"
    "plausible-analytics"
    "acf-field-date-time-picker"
    "wp-bottom-menu"
    "simple-membership-after-login-redirection"
    "top-commentators-widget"
    "smart-marketing-for-wp"
    "athemes-blocks"
    "wc-apg-nifcifnie-field"
    "cookie-bar"
    "boxtal-connect"
    "b2bking-wholesale-for-woocommerce"
    "chart-builder"
    "wpdm-gutenberg-blocks"
    "montonio-for-woocommerce"
    "wp-and-divi-icons"
    "sakura-rs-wp-ssl"
    "wp-portfolio"
    "wp-saml-auth"
    "wp-jamstack-deployments"
    "my-wp-login-logo"
    "child-theme-wizard"
    "void-elementor-post-grid-addon-for-elementor-page-builder"
    "retainful-next-order-coupon-for-woocommerce"
    "woo-product-country-base-restrictions"
    "ricg-responsive-images"
    "propertyhive"
    "wc-quantity-plus-minus-button"
    "debug-bar-extender"
    "custom-post-type-maker"
    "embed-iframe"
    "oauth2-provider"
    "member-access"
    "logo-carousel-slider"
    "301-redirects"
    "show-hidecollapse-expand"
    "metorik-helper"
    "surbma-magyar-woocommerce"
    "captcha-bws"
    "wordpress-css-drop-down-menu"
    "yandex-metrika"
    "authorizer"
    "tantan-flickr"
    "revolut-gateway-for-woocommerce"
    "dominant-color-images"
    "wpc-ajax-add-to-cart"
    "disable-real-mime-check"
    "wp-webhooks"
    "google-picasa-albums-viewer"
    "all-404-pages-redirect-to-homepage"
    "instagrate-to-wordpress"
    "learning-management-system"
    "simple-ajax-chat"
    "church-theme-content"
    "duplicate-pp"
    "social-share-with-floating-bar"
    "flatpm-wp"
    "document-emberdder"
    "cue"
    "visual-editor-custom-buttons"
    "pdf-embed"
    "wp-editor-widget"
    "insights"
    "genesis-custom-blocks"
    "authorsure"
    "category-ajax-filter"
    "delete-pending-comments"
    "additional-product-fields-for-woocommerce"
    "show-only-lowest-prices-in-woocommerce-variable-products"
    "no-captcha-recaptcha"
    "remove-yoast-seo-comments"
    "wp-job-manager-companies"
    "tockify-events-calendar"
    "locatoraid"
    "wp-ultimate-post-grid"
    "easy-woocommerce-auto-sku-generator"
    "wpify-woo"
    "wordpress-hit-counter"
    "departamentos-y-ciudades-de-colombia-para-woocommerce"
    "js-composer-qtranslate-x"
    "themefuse-maintenance-mode"
    "easymega"
    "wp-webinarsystem"
    "real-thumbnail-generator-lite"
    "disable-right-click-for-wp"
    "wp-swfobject"
    "wp-rest-api-v2-menus"
    "wp-consent-api"
    "sns-count-cache"
    "simple-staff-list"
    "highlighting-code-block"
    "basic-user-avatars"
    "sellkit"
    "bulk-edit-categories-tags"
    "hit-sniffer-blog-stats"
    "advanced-image-styles"
    "bbp-private-groups"
    "ts-webfonts-for-conoha"
    "wp-colorbox"
    "trackship-for-woocommerce"
    "modal-dialog"
    "nav-menu-images"
    "datafeedr-product-sets"
    "cds-simple-seo"
    "live-sales-notifications-for-woocommerce"
    "wpvivid-imgoptim"
    "custom-user-profile-photo"
    "friendly-captcha"
    "wpelemento-importer"
    "wp-copy-protect-with-color-design"
    "gd-bbpress-tools"
    "auto-post-scheduler"
    "debug-this"
    "seo-automated-link-building"
    "xserver-migrator"
    "ali2woo-lite"
    "vikbooking"
    "import-eventbrite-events"
    "amimoto-dashboard"
    "category-specific-rss-feed-menu"
    "genesis-visual-hook-guide"
    "themezee-toolkit"
    "woo-product-attachment"
    "weather-atlas"
    "photo-galleria"
    "woo-donations"
    "sales-pop"
    "woo-added-to-cart-notification"
    "wp-githuber-md"
    "accessibe"
    "jquery-image-lazy-loading"
    "dmca-badge"
    "wp-discussion-board"
    "shutter-reloaded"
    "parcelpanel"
    "etsy-shop"
    "astra-hooks"
    "acf-theme-code"
    "otf-regenerate-thumbnails"
    "ht-contactform"
    "contact-form-7-extras"
    "wooswipe"
    "new-photo-gallery"
    "sp-faq"
    "sf-move-login"
    "gutena-forms"
    "mybooktable"
    "assistant"
    "woocommerce-gateway-eway"
    "sem-author-image"
    "when-last-login"
    "gratisfaction-all-in-one-loyalty-contests-referral-program-for-woocommerce"
    "woo-widget-product-slideshow"
    "wp-font-awesome"
    "css-js-manager"
    "beautiful-taxonomy-filters"
    "blocks-css"
    "selfhost-google-fonts"
    "one-time-login"
    "custom-elementor-icons"
    "block-builder"
    "disable-auto-update-email-notifications"
    "wp-ada-compliance-check-basic"
    "add-to-cart-button-custom-text"
    "simple-website-redirect"
    "uipress-lite"
    "ultimate-slider"
    "lws-optimize"
    "conditional-payments-for-woocommerce"
    "next-active-directory-integration"
    "auto-robot"
    "themezee-widget-bundle"
    "wp-wall"
    "easy-facebook-like-box"
    "advanced-post-list"
    "all-in-one-seo-pack-importer"
    "collapsing-archives"
    "export-import-menus"
    "acf-options-for-polylang"
    "bricksable"
    "roses-like-this"
    "push-notification"
    "seowriting"
    "billplz-for-woocommerce"
    "the-social-links"
    "woocommerce-product-stock-alert"
    "ultimate-under-construction"
    "wp-last-login"
    "slate-admin-theme"
    "lead-capturing-call-to-actions-by-vcita"
    "simple-youtube-embed"
    "fg-prestashop-to-woocommerce"
    "team-free"
    "yaysmtp"
    "sell-media"
    "woocommerce-email-inquiry-cart-options"
    "datafeedr-woocommerce-importer"
    "wp-awesome-faq"
    "cf7-hubspot"
    "wpml-to-polylang"
    "salert"
    "advanced-product-search-for-woo"
    "multiple-domain"
    "peachpay-for-woocommerce"
    "advanced-post-manager"
    "wp-lister-for-amazon"
    "swiftype-search"
    "cf-geoplugin"
    "salesforce-wordpress-to-lead"
    "configurable-tag-cloud-widget"
    "cm-answers"
    "huzzaz-video-gallery"
    "gutenbee"
    "responsive-slider-gallery"
    "lenix-elementor-leads-addon"
    "text-to-audio"
    "flexible-shipping-fedex"
    "custom-login-page"
    "radio-station"
    "wp-crowdfunding"
    "fg-drupal-to-wp"
    "testimonial-builder"
    "simple-login-log"
    "latest-post-shortcode"
    "wish-list-for-woocommerce"
    "tagembed-widget"
    "image-hover-effects"
    "rest-api-oauth1"
    "mathjax-latex"
    "wedocs"
    "custom-checkout-layouts-for-woocommerce"
    "shop-feed-for-instagram-by-snapppt"
    "media-deduper"
    "genesis-columns-advanced"
    "page-animations-and-transitions"
    "wp-slimbox2"
    "dologin"
    "sumup-payment-gateway-for-woocommerce"
    "name-directory"
    "iyzico-woocommerce"
    "zendesk"
    "payplug"
    "simple-comment-editing"
    "pakkelabels-for-woocommerce"
    "simple-revisions-delete"
    "sinatra-core"
    "watchful"
    "eu-vat-for-woocommerce"
    "wp-original-media-path"
    "smntcs-google-webmaster-tools"
    "judgeme-product-reviews-woocommerce"
    "hash-elements"
    "upsell-order-bump-offer-for-woocommerce"
    "media-slider"
    "wpo-tweaks"
    "image-hover-effects-visual-composer-extension"
    "buy-one-click-woocommerce"
    "ebook-store"
    "woocommerce-admin-bar-addition"
    "categorytinymce"
    "add-wpgraphql-seo"
    "wc-thanks-redirect"
    "wp-trending-post-slider-and-widget"
    "stock-ticker"
    "yamaps"
    "booking-manager"
    "lightview-plus"
    "sparkpost"
    "png-to-jpg"
    "ignitiondeck"
    "stop-wp-emails-going-to-spam"
    "restrict-widgets"
    "advanced-floating-content-lite"
    "search-by-sku-for-woocommerce"
    "cm-download-manager"
    "bp-xprofile-custom-field-types"
    "responsive-tabs"
    "wp-duplicate-page"
    "adsensei-b30"
    "pta-volunteer-sign-up-sheets"
    "liquid-speech-balloon"
    "cafe-lite"
    "wp-pipes"
    "import-woocommerce"
    "get-custom-field-values"
    "user-activity-tracking-and-log"
    "leadconnector"
    "client-portal"
    "wcboost-products-compare"
    "hungarian-pickup-points-for-woocommerce"
    "slider-responsive-slideshow"
    "skaut-google-drive-gallery"
    "mellat-woocommerce"
    "jj-nextgen-jquery-slider"
    "getsocial"
    "spam-master"
    "mobile-contact-bar"
    "cc-child-pages"
    "woocommerce-paypal-pro-payment-gateway"
    "popular-widget"
    "contact-us-page-contact-people"
    "simple-blog-stats"
    "estimate-delivery-date-for-woocommerce"
    "auto-thickbox"
    "wp-showhide"
    "bold-timeline-lite"
    "color-filters"
    "dashboard-welcome-for-elementor"
    "podcast-subscribe-buttons"
    "wp-connect"
    "gallery-box"
    "element-ready-lite"
    "easy-timer"
    "simple-cache"
    "shoutcast-icecast-html5-radio-player"
    "wp-easy-pay"
    "scroll-back-to-top"
    "transbank-webpay-plus-rest"
    "dispensary-age-verification"
    "rss-image-feed"
    "wptelegram-widget"
    "image-cleanup"
    "bkash"
    "insert-or-embed-articulate-content-into-wordpress"
    "podcast-importer-secondline"
    "checkout-files-upload-woocommerce"
    "swap-google-font-display"
    "beehive-analytics"
    "wpglobus-for-wpbakery-visual-composer"
    "flexy-breadcrumb"
    "projecthuddle-child-site"
    "new-album-gallery"
    "fluent-support"
    "woo-payment-gateway-paysera"
    "conditional-widgets"
    "wp-club-manager"
    "genesis-simple-menus"
    "appointy-appointment-scheduler"
    "yith-paypal-express-checkout-for-woocommerce"
    "gallery-portfolio"
    "woocommerce-other-payment-gateway"
    "exportfeed-for-woocommerce-product-to-etsy"
    "woo-tools"
    "pmpro-buddypress"
    "announcer"
    "inpost-for-woocommerce"
    "magic-liquidizer-responsive-table"
    "efficient-related-posts"
    "mp-restaurant-menu"
    "comments-like-dislike"
    "upload-larger-plugins"
    "awebooking"
    "hide-admin-notices"
    "elex-bulk-edit-products-prices-attributes-for-woocommerce-basic"
    "texty"
    "hitsteps-visitor-manager"
    "my-tickets"
    "toolkit-for-envato"
    "dashboard-widgets-suite"
    "cm-on-demand-search-and-replace"
    "debug-bar-cron"
    "woocommerce-pdf-invoices-italian-add-on"
    "social-share-button"
    "better-plugin-compatibility-control"
    "soundcloud-master"
    "free-stock-photos-foter"
    "codecolorer"
    "no-gutenberg"
    "auto-hide-admin-bar"
    "affiliates-woocommerce-light"
    "ultimate-woocommerce-auction"
    "gd-rating-system"
    "buddypress-multilingual"
    "subtitles"
    "wp-imageflow2"
    "benchmark-email-lite"
    "audit-trail"
    "resume-builder"
    "fitvids-for-wordpress"
    "add-widget-after-content"
    "real-category-library-lite"
    "email-subscribe"
    "product-sales-report-for-woocommerce"
    "adthrive-ads"
    "share-this-image"
    "wpsso-am"
    "database-for-wpforms"
    "simple-popup-plugin"
    "slimjetpack"
    "sb-rss-feed-plus"
    "gs-pinterest-portfolio"
    "restropress"
    "sales-countdown-timer"
    "gallery-master"
    "donorbox-donation-form"
    "wordlift"
    "brands-for-woocommerce"
    "smart-recent-posts-widget"
    "arconix-shortcodes"
    "mphb-elementor"
    "artiss-transient-cleaner"
    "pixproof"
    "added-to-cart-popup-woocommerce"
    "open-in-new-window-plugin"
    "super-simple-google-analytics"
    "pre-orders-for-woocommerce"
    "cf7-google-analytics"
    "product-input-fields-for-woocommerce"
    "registered-users-only"
    "jetwoo-widgets-for-elementor"
    "rps-image-gallery"
    "gallery-block-lightbox"
    "woo-jtl-connector"
    "convertful"
    "easy-upload-files-during-checkout"
    "user-roles-and-capabilities"
    "stagtools"
    "shiprocket"
    "wpdeepl"
    "forms-3rdparty-integration"
    "full-screen-menu-for-elementor"
    "demo-import-kit"
    "post-grid-and-filter-ultimate"
    "themify-shortcodes"
    "list-pages-shortcode"
    "getty-images"
    "wc-cancel-order"
    "wp-change-default-from-email"
    "avadanta-companion"
    "nextgen-gallery-voting"
    "wp-browser-update"
    "grid-plus"
    "wp-clone-template"
    "tutormate"
    "bp-album"
    "pmpro-mailchimp"
    "newsletter-subscription-form"
    "woo-order-test"
    "woocommerce-google-dynamic-retargeting-tag"
    "tag-pages"
    "bulkpress"
    "sensei-certificates"
    "wp-job-manager-colors"
    "export-wp-page-to-static-html"
    "ga-in"
    "tarteaucitronjs"
    "quick-and-easy-testimonials"
    "wpb-accordion-menu-or-category"
    "front-page-category"
    "foliopress-wysiwyg"
    "photography-portfolio"
    "disable-cart-fragments"
    "most-commented"
    "very-simple-meta-description"
    "kama-thumbnail"
    "slim-maintenance-mode"
    "lightweight-grid-columns"
    "review-widgets-for-airbnb"
    "custom-post-types"
    "sitemap-by-click5"
    "import-xml-feed"
    "animated-live-wall"
    "timeline-and-history-slider"
    "wp-links-page"
    "zoho-forms"
    "subscriber"
    "marker-io"
    "wp-security-hardening"
    "wp-enable-webp"
    "unlist-posts"
    "fluentforms-pdf"
    "wc-no-shipping-message"
    "radio-player"
    "woocommerce-compare-products"
    "extended-evaluation-for-statify"
    "woo-single-page-checkout"
    "wp-gatsby"
    "bft-autoresponder"
    "local-time-clock"
    "download-theme"
    "seed-social"
    "kaya-qr-code-generator"
    "myworks-woo-sync-for-quickbooks-online"
    "multicons"
    "all-in-one-intranet"
    "buddypress-members-only"
    "gravity-signature-forms-add-on"
    "mobble"
    "amount-left-free-shipping-woocommerce"
    "zotpress"
    "yotpo-social-reviews-for-woocommerce"
    "wp-my-instagram"
    "crafty-social-buttons"
    "forms-for-campaign-monitor"
    "listo"
    "wp-exporter"
    "photoblocks-grid-gallery"
    "awp-companion"
    "frontend-reset-password"
    "woo-xendit-virtual-accounts"
    "woocommerce-novalnet-gateway"
    "wpshop"
    "rublon"
    "woo-order-on-whatsapp"
    "visual-link-preview"
    "table-addons-for-elementor"
    "youzify"
    "wp-basic-auth"
    "addons-for-beaver-builder"
    "advanced-custom-fields-nav-menu-field"
    "wp-video-posts"
    "wp-mautic"
    "payment-gateways-per-product-categories-for-woocommerce"
    "acymailing"
    "easy-footnotes"
    "wp-coupons-and-deals"
    "intelly-countdown"
    "auto-listings"
    "badgeos-community-add-on"
    "post-pay-counter"
    "contact"
    "iframely"
    "brozzme-db-prefix-change"
    "avatar-manager"
    "bluehost-site-migrator"
    "specific-content-for-mobile"
    "reftagger"
    "tc-custom-javascript"
    "japanese-font-for-tinymce"
    "shop-page-wp"
    "fix-image-rotation"
    "simple-wp-maintenance-mode"
    "pop-up"
    "getsitecontrol"
    "cart-for-woocommerce"
    "post-meta-inspector"
    "remove-add-to-cart-woocommerce"
    "advanced-free-flat-shipping-woocommerce"
    "bigcommerce"
    "publishpress-checklists"
    "fix-rss-feed"
    "google-calendar-widget"
    "wp-social-widget"
    "vanilla-forums"
    "wp-term-order"
    "social-bookmarks"
    "paytium"
    "stockpack"
    "license-manager-for-woocommerce"
    "nazy-load"
    "random-banner"
    "ajax-calendar"
    "faster-pagination"
    "email-list-builder-by-social-intents"
    "formcraft-form-builder"
    "json-api-user"
    "australian-post-woocommerce-extension"
    "spice-post-slider"
    "list-custom-taxonomy-widget"
    "wp-front-end-editor"
    "darkmysite"
    "wp-editormd"
    "note"
    "woo-asaas"
    "automatic-featured-images-from-videos"
    "debug-bar-actions-and-filters-addon"
    "wp-optin-wheel"
    "slideshow"
    "modal-popup-box"
    "contentad"
    "free-images"
    "chp-ads-block-detector"
    "order-export-and-more-for-woocommerce"
    "ip-location-block"
    "missed-scheduled-posts-publisher"
    "wp-team-showcase-and-slider"
    "event-page-templates-addon-for-the-events-calendar"
    "tinymce-custom-styles"
    "autoclear-autoptimize-cache"
    "advanced-local-pickup-for-woocommerce"
    "easy-notification-bar"
    "speculation-rules"
    "lwscache"
    "buymeacoffee"
    "sugar-calendar-lite"
    "images-to-webp"
    "gravity-forms-constant-contact"
    "tracemyip-visitor-analytics-ip-tracking-control"
    "youtube-simplegallery"
    "borderless"
    "smart-grid-gallery"
    "wp-discourse"
    "google-places-reviews"
    "easy-image-collage"
    "batcache"
    "th-variation-swatches"
    "cf7-database"
    "html5-videogallery-plus-player"
    "cashfree"
    "dark-mode"
    "statpresscn"
    "nextgen-gallery-sidebar-widget"
    "allow-html-in-category-descriptions"
    "popup-with-fancybox"
    "webman-amplifier"
    "learnpress-buddypress"
    "acf-openstreetmap-field"
    "404-to-homepage"
    "snazzy-archives"
    "woocommerce-lightbox"
    "disabled-source-disabled-right-click-and-content-protection"
    "dibs-easy-for-woocommerce"
    "jetgridbuilder"
    "wp-easy-uploader"
    "constant-contact-forms-by-mailmunch"
    "absolute-reviews"
    "wp-html-compression"
    "vk-filter-search"
    "wp-geo"
    "cf7-mailchimp"
    "advanced-post-queries"
    "spider-analyser"
    "rank-my-wp"
    "ulisting"
    "split-test-for-elementor"
    "myagileprivacy"
    "authors"
    "wp-pda"
    "disable-theme-and-plugin-auto-update-emails"
    "chained-quiz"
    "themehunk-megamenu-plus"
    "jquery-archive-list-widget"
    "elastic-theme-editor"
    "google-maps-for-wordpress"
    "viglink"
    "responsive-vector-maps"
    "open-graph-protocol-framework"
    "decent-comments"
    "pojo-sidebars"
    "woocommerce-call-for-price"
    "page-specific-menu-items"
    "jquery-ui-widgets"
    "seriously-simple-stats"
    "xml-for-google-merchant-center"
    "product-visibility-by-user-role-for-woocommerce"
    "templateberg"
    "playbuzz"
    "b-slider"
    "trinity-audio"
    "wp-postviews-plus"
    "download-after-email"
    "woocommerce-breadcrumbs"
    "wp-inventory-manager"
    "krokedil-paysoncheckout-20-for-woocommerce"
    "date-time-picker-for-contact-form-7"
    "fsm-custom-featured-image-caption"
    "wordpress-flash-uploader"
    "wp-event-aggregator"
    "sirv"
    "wp-auto-updater"
    "unfiltered-mu"
    "bp-verified-member"
    "fullscreen-galleria"
    "recaptcha-woo"
    "storefront-footer-bar"
    "mollie-forms"
    "woo-multistep-checkout"
    "3r-elementor-timeline-widget"
    "wp-magazine-modules-lite"
    "posts-data-table"
    "worth-the-read"
    "bookingcom-official-searchbox"
    "new-contact-form-widget"
    "trash-duplicate-and-301-redirect"
    "accessible-poetry"
    "woo-auto-coupons"
    "simple-ldap-login"
    "social-media-icons"
    "replace-image"
    "wpc-product-quantity"
    "customize-admin"
    "gsheetconnector-wpforms"
    "dvk-social-sharing"
    "code-profiler"
    "snow-storm"
    "cookies-for-comments"
    "autoconvert-greeklish-permalinks"
    "auto-sizes"
    "disable-site"
    "genesis-footer-builder"
    "single-post-template"
    "woocommerce-email-test"
    "multisite-plugin-manager"
    "shiftcontroller"
    "clean-archives-reloaded"
    "everest-backup"
    "woocommerce-remove-all-products"
    "media-library-helper"
    "slicknav-mobile-menu"
    "wats"
    "rise-blocks"
    "woo-postnl"
    "wp-youtube-player"
    "woo-blocker-lite-prevent-fake-orders-and-blacklist-fraud-customers"
    "awesome-contact-form7-for-elementor"
    "sold-out-badge-for-woocommerce"
    "relative-url"
    "image-carousel"
    "smart-seo-tool"
    "multiple-domain-mapping-on-single-site"
    "wp-scraper"
    "custom-upload-dir"
    "lws-hide-login"
    "website-file-changes-monitor"
    "modular-connector"
    "super-testimonial"
    "teachpress"
    "exclude-pages-from-menu"
    "woocommerce-max-quantity"
    "gift-voucher"
    "len-slider"
    "wpjam-qiniu"
    "byconsole-woo-order-delivery-time"
    "blaze-demo-importer"
    "terms-descriptions"
    "wistia-wordpress-oembed-plugin"
    "wps-visitor-counter"
    "ns-featured-posts"
    "buddypress-cover-photo"
    "woo-order-splitter"
    "advanced-css-editor"
    "gallery-photo-gallery"
    "product-page-shipping-calculator-for-woocommerce"
    "woo-quickview"
    "themeinwp-import-companion"
    "the-moneytizer"
    "wp-fusion-lite"
    "auto-tag"
    "admin-css-mu"
    "hide-admin-menu"
    "midtrans-woocommerce"
    "fareharbor"
    "juiz-last-tweet-widget"
    "multiple-featured-images"
    "powered-cache"
    "toggle-wpautop"
    "zeno-font-resizer"
    "recaptcha-for-mw-wp-form"
    "premmerce-woocommerce-product-filter"
    "userswp-recaptcha"
    "browser-shots"
    "integromat-connector"
    "opening-hours"
    "xt-visitor-counter"
    "bellows-accordion-menu"
    "disable-lazy-loading"
    "woo-virtual-reviews"
    "polylang-theme-strings"
    "mabel-shoppable-images-lite"
    "wp-parallax-content-slider"
    "widgets-in-menu"
    "serbian-transliteration"
    "contact-form-to-db"
    "pilotpress"
    "flexmls-idx"
    "vc-templates-import-export"
    "bazz-callback-widget"
    "yookassa"
    "breezing-forms"
    "delete-me"
    "custom-search-plugin"
    "disk-usage-sunburst"
    "event-calendar-scheduler"
    "view-admin-as"
    "panopress"
    "heatmap-for-wp"
    "qtranslate-to-wpml-export"
    "furgonetka"
    "th-product-compare"
    "maintenance-page"
    "wp-time-slots-booking-form"
    "coupon-generator-for-woocommerce"
    "better-elementor-addons"
    "flat-rate-per-countryregion-for-woocommerce"
    "horizontal-scrolling-announcements"
    "cancel-order-request-woocommerce"
    "contact-form-7-widget"
    "genesis-dambuster"
    "swatchly"
    "wp-category-permalink"
    "sailthru-widget"
    "block-specific-plugin-updates"
    "facebook-shop-by-storeyacom"
    "smart-archives-reloaded"
    "storefront-title-toggle"
    "tf-numbers-number-counter-animaton"
    "wp-approve-user"
    "hkdev-maintenance-mode"
    "post-content-shortcodes"
    "exmage-wp-image-links"
    "webwinkelkeur"
    "delete-expired-transients"
    "oik-nivo-slider"
    "proteccion-datos-rgpd"
    "prevent-browser-caching"
    "pricingtable"
    "userswp-social-login"
    "wp-login-form"
    "icon-element"
    "enhanced-admin-bar-with-codex-search"
    "wp-terms-popup"
    "vanilla-pdf-embed"
    "doneren-met-mollie"
    "cf7-polylang"
    "nextgen-download-gallery"
    "wp-monalisa"
    "thickbox"
    "joomsport-sports-league-results-management"
    "adminify"
    "force-refresh"
    "eventon-lite"
    "woo-stickers-by-webline"
    "mangboard"
    "image-source-control-isc"
    "audio-album"
    "gridable"
    "food-store"
    "revisionize"
    "lws-tools"
    "nextgen-gallery-custom-fields"
    "lastudio-element-kit"
    "ninja-forms-addon-manager"
    "button"
    "simply-show-ids"
    "woocommerce-pay-per-post"
    "wp-smartcrop"
    "leaky-paywall"
    "bulk-media-register"
    "wp-responsive-thumbnail-slider"
    "easy-nivo-slider"
    "import-users"
    "authldap"
    "current-year-shortcode"
    "checkfront-wp-booking"
    "templatespare"
    "social-toolbar"
    "modern-footnotes"
    "wp-api-menus"
    "product-open-pricing-name-your-price-for-woocommerce"
    "wp-date-and-time-shortcode"
    "wp-subscribe-form"
    "wp-payment-form"
    "zipmoney-payments-woocommerce"
    "page-generator"
    "color-and-image-swatches-for-variable-product-attributes"
    "another-mailchimp-widget"
    "options-for-twenty-twenty"
    "buddypress-learndash"
    "performant-translations"
    "wonderplugin-pdf-embed"
    "category-posts-in-custom-menu"
    "gourl-bitcoin-paid-memberships-pro"
    "wp-mail-log"
    "user-specific-content"
    "ninja-forms-recaptcha-field"
    "wc-variations-radio-buttons"
    "narrative-so"
    "open-graphite"
    "advanced-forms"
    "3d-viewer"
    "ajax-load-more-anything"
    "qty-increment-buttons-for-woocommerce"
    "woocommerce-superfaktura"
    "contact-form-7-success-page-redirects"
    "cubepoints"
    "new-video-gallery"
    "easy-wp-meta-description"
    "extensions-for-cf7"
    "wp-dummy-content-generator"
    "windows-azure-storage"
    "definitely-allow-mobile-zooming"
    "reseller-store"
    "wp-force-logout"
    "wp-mailfrom-ii"
    "gourl-bitcoin-paypal-donations-give-addon"
    "erp-pdf-invoice"
    "anycomment"
    "ebay-feeds-for-wordpress"
    "gradient-starter-templates"
    "bp-social-connect"
    "generate-pdf-using-contact-form-7"
    "sportspress-for-soccer"
    "ultimate-bootstrap-elements-for-elementor"
    "fooevents-calendar"
    "makestories-helper"
    "opt-out-for-google-analytics"
    "genesis-custom-headers"
    "pix-por-piggly"
    "bp-custom-order-status-for-woocommerce"
    "evermore"
    "scrollsequence"
    "facebook-like-thumbnail"
    "open-user-map"
    "phonepe-payment-solutions"
    "baqend"
    "update-urls"
    "gs-testimonial"
    "jsm-force-ssl"
    "datafeedr-comparison-sets"
    "preferred-languages"
    "cartpops"
    "proxy-vpn-blocker"
    "icon-widget"
    "gabfire-widget-pack"
    "gourl-bitcoin-easy-digital-downloads-edd"
    "keyring"
    "cf7-phone-mask-field"
    "automatic-youtube-gallery"
    "ezcache"
    "aibuddy-openai-chatgpt"
    "child-pages-shortcode"
    "universal-google-adsense-and-ads-manager"
    "oasis-workflow"
    "m-chart"
    "click-to-tweet-by-todaymade"
    "toyyibpay-for-woocommerce"
    "multisite-post-duplicator"
    "wp-newrelic"
    "before-after-image-comparison-slider-for-elementor"
    "comments-import-export-woocommerce"
    "styleguide"
    "advanced-permalinks"
    "12-step-meeting-list"
    "gs-team-members"
    "useful-blocks"
    "authenticator"
    "advanced-custom-field-repeater-collapser"
    "amcharts-charts-and-maps"
    "product-blocks-for-woocommerce"
    "mycurator"
    "apcu-manager"
    "smartideo"
    "cognito-forms"
    "optimize-images-resizing"
    "wepos"
    "ts-webfonts-for-onamaecom"
    "wp-cron-status-checker"
    "express-checkout"
    "desktopserver"
    "omise"
    "yahman-add-ons"
    "wp-rest-api-log"
    "school-management-system"
    "require-featured-image"
    "wp-supersized"
    "user-role"
    "generate-child-theme"
    "yourls-wordpress-to-twitter"
    "side-menu-lite"
    "wordpress-gzip-compression"
    "url-params"
    "sell-downloads"
    "custom-post-type-pdf-attachment"
    "coinbase-commerce"
    "robots-txt-editor"
    "daggerhart-openid-connect-generic"
    "real3d-flipbook-lite"
    "spreaker-shortcode"
    "prismatic"
    "options-importer"
    "upstream"
    "cf7-styler"
    "enquiry-quotation-for-woocommerce"
    "woo-quick-view"
    "wp-vipergb"
    "ultra-companion"
    "multiline-files-for-contact-form-7"
    "wp-attachments"
    "dashboard-notepad"
    "responsive-full-width-background-slider"
    "basepress"
    "wp-registration"
    "visual-web-optimizer"
    "arabic-webfonts"
    "stock-market-ticker"
    "add-pinterest-follow-button"
    "wp-content-pilot"
    "giveasap"
    "zoninator"
    "gourl-wp-ecommerce-bitcoin-altcoin-payment-gateway-addon"
    "equal-height-columns"
    "fix-another-update-in-progress"
    "category-checklist-tree"
    "colissimo-delivery-integration"
    "woo-tabbed-category-product-listing"
    "columns"
    "wp-custom-body-class"
    "smart-archive-page-remove"
    "facebook-comments-master"
    "ticket-tailor"
    "genesis-widget-column-classes"
    "extensive-vc-addon"
    "flickr-photostream"
    "tumblr-widget-for-wordpress"
    "top-level-cats"
    "easy-author-image"
    "activity-log-wp-seo"
    "password-protected-woo-store"
    "max-upload-filesize"
    "review-widgets-for-amazon"
    "wp-categories-widget"
    "fastly"
    "wc-custom-add-to-cart-labels"
    "bulk-remove-posts-from-category"
    "simple-membership-custom-messages"
    "multiparcels-shipping-for-woocommerce"
    "woo-product-category-discount"
    "genesis-featured-widget-amplified"
    "tlp-food-menu"
    "formidablepro-2-pdf"
    "buddypress-toolbar"
    "post-my-contact-form-7"
    "spam-destroyer"
    "ppv-live-webcams"
    "wallet-system-for-woocommerce"
    "refer-a-friend-for-woocommerce-by-wpgens"
    "gourl-jigoshop-bitcoin-payment-gateway-processor"
    "debug"
    "tubepressnet"
    "siteimprove"
    "bv-pantheon-migration"
    "wp-auctions"
    "picu"
    "simple-iframe"
    "gourl-bbpress-premium-membership-bitcoin-payments"
    "wooshark-aliexpress-importer"
    "crowdsignal-forms"
    "rpb-chessboard"
    "remove-xmlrpc-pingback-ping"
    "bws-google-analytics"
    "exchange-rates"
    "dark-mode-toggle"
    "team-showcase"
    "um-online"
    "wp-remote-users-sync"
    "maximum-products-per-user-for-woocommerce"
    "affiliate-coupons"
    "highlight-and-share"
    "wp-custom-login-page-logo"
    "eu-cookies-bar"
    "jetpack-lite"
    "reusable-blocks-extended"
    "gourl-wpmudev-marketpress-bitcoin-payment-gateway-addon"
    "username-updater"
    "generalstats"
    "toolbar-publish-button"
    "post-avatar"
    "log-cleaner-for-ithemes-security"
    "wp-extra"
    "football-pool"
    "conversation-watson"
    "wp-quicklatex"
    "gourl-spelling-notifications"
    "wcfm-marketplace-rest-api"
    "wp-mobile-detect"
    "wp-hotelier"
    "wp-books-gallery"
    "wt-security"
    "product-configurator-for-woocommerce"
    "masvideos"
    "the-welcomizer"
    "tripetto"
    "iks-menu"
    "leyka"
    "most-and-least-read-posts-widget"
    "cp-easy-form-builder"
    "multisite-user-management"
    "ht-easy-google-analytics"
    "athemes-toolbox"
    "floating-button"
    "amazon-link-engine"
    "comment-reply-email-notification"
    "wonderplugin-video-embed"
    "gourl-appthemes-bitcoin-payments-classipress-vantage-jobroller"
    "bugsnag"
    "frontend-dashboard"
    "simple-redirect"
    "wrc-pricing-tables"
    "sheets-to-wp-table-live-sync"
    "easy-social-sharing"
    "anti-captcha"
    "native-lazyload"
    "wallets"
    "equivalent-mobile-redirect"
    "multiple-pages-generator-by-porthas"
    "wp-old-post-date-remover"
    "superb-tables"
    "wpo365-msgraphmailer"
    "google-plus-authorship"
    "wp-meta-data-filter-and-taxonomy-filter"
    "funnelkit-stripe-woo-payment-gateway"
    "wc4bp"
    "infographic-and-list-builder-ilist"
    "cache-control"
    "code-block-pro"
    "srs-simple-hits-counter"
    "simple-feed-stats"
    "liveblog"
    "the-casengo-chat-widget"
    "my-wp"
    "always-edit-in-html"
    "automatic-post-tagger"
    "find-my-blocks"
    "auction-nudge"
    "pages-with-category-and-tag"
    "shopkeeper-extender"
    "pmpro-bbpress"
    "donation-thermometer"
    "t4b-news-ticker"
    "rencontre"
    "custom-favicon"
    "import-shopify-to-woocommerce"
    "wp-multi-network"
    "visual-term-description-editor"
    "edd-auto-register"
    "website-article-monetization-by-magenet"
    "subscription-options"
    "free-shipping-label"
    "aws-cdn-by-wpadmin"
    "favhero-favicon-generator"
    "nice-login-register-widget"
    "disable-welcome-messages-and-tips"
    "simple-chat-button"
    "coolclock"
    "display-featured-image-genesis"
    "pods-beaver-builder-themer-add-on"
    "britetechs-companion"
    "seo-auto-linker"
    "wordpress-faq-manager"
    "better-admin-bar"
    "table-of-contents-block"
    "deposits-partial-payments-for-woocommerce"
    "post-title-marquee-scroll"
    "oembed-plus"
    "wp-markdown"
    "wp-posts-carousel"
    "wp-featured-content-and-slider"
    "post-types-unlimited"
    "woo-seo-addon"
    "stax-buddy-builder"
    "cos-html-cache"
    "pgall-for-woocommerce"
    "wp-contact-form-7-spam-blocker"
    "jquery-manager"
    "tk-google-fonts"
    "mango-buttons"
    "woo-zoho"
    "sezzle-woocommerce-payment"
    "wp-sliding-login-register-panel"
    "wp-logo-showcase"
    "woo-swish-e-commerce"
    "joli-table-of-contents"
    "mailhawk"
    "popular-posts-plugin"
    "algori-pdf-viewer"
    "leenkme"
    "woocommerce-es"
    "more-privacy-options"
    "wc-min-max-quantities"
    "ccavanue-woocommerce-payment-getway"
    "wp-cron-control"
    "wp-persistent-login"
    "wincher-rank-tracker"
    "rometheme-for-elementor"
    "redirector"
    "gravity-forms-wcag-20-form-fields"
    "lead-forensics-roi"
    "gallery-widget"
    "clean-up-booster"
    "bulk-delete-comments"
    "variation-price-display"
    "woocommerce-new-product-badge"
    "bne-testimonials"
    "issuu-pdf-sync"
    "request-a-quote"
    "linkedin-auto-publish"
    "ryviu"
)

# Define user agents with weights
declare -A USER_AGENTS
USER_AGENTS=(
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"]=5
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"]=7
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"]=6
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36 Edg/91.0.864.54"]=5
    ["Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"]=4
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 OPR/77.0.4054.277"]=3
    ["Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (iPad; CPU OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"]=2
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Vivaldi/4.0"]=1
    ["Mozilla/5.0 (Android 11; Mobile; rv:68.0) Gecko/68.0 Firefox/88.0"]=1
    ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"]=15
    ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/534.36"]=12
)

LAST_VERSION_FILE="${WORDPRESS_WORKDIR}/last_versions.txt"
PARALLEL_JOBS=1

DOWNLOAD_ALL_PLUGINS='n'
LIST_ONLY='n'
ALL_PLUGINS_FILE="${WORDPRESS_WORKDIR}/wp-plugin-svn-list.txt"

DELAY_DOWNLOADS='n'
DELAY_DURATION=5

FORCE_UPDATE='n'
CACHE_ONLY='n'

mkdir -p "$WORDPRESS_WORKDIR" "$MIRROR_DIR" "$LOGS_DIR"
DEBUG_MODE=0

while getopts "p:dalD:t:fc" opt; do
    case ${opt} in
        p ) PARALLEL_JOBS=$OPTARG ;;
        d ) DEBUG_MODE=1 ;;
        a ) DOWNLOAD_ALL_PLUGINS='y' ;;
        l ) LIST_ONLY='y' ;;
        D ) DELAY_DOWNLOADS=$OPTARG ;;
        t ) DELAY_DURATION=$OPTARG ;;
        f ) FORCE_UPDATE='y' ;;
        c ) CACHE_ONLY='y' ;;    # New option for cache-only
        \? ) echo "Usage: $0 [-p PARALLEL_JOBS] [-d] [-a] [-l] [-D DELAY_DOWNLOADS] [-t DELAY_DURATION] [-f] [-c]" 1>&2; exit 1 ;;
    esac
done

debug_log() {
    if [ "$DEBUG_MODE" -eq 1 ]; then
        echo "[DEBUG] $1" >&2
    fi
}

get_random_user_agent() {
    echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
}

get_latest_version_and_download_link() {
    local plugin=$1
    debug_log "Checking latest version and download link for $plugin"
    
    local api_url="https://api.wordpress.org/plugins/info/1.0/${plugin}.json"
    local user_agent=$(get_random_user_agent)
    local api_response=$(curl -s -H "User-Agent: $user_agent" "$api_url")
    
    if echo "$api_response" | jq -e '.error' >/dev/null; then
        local error_message=$(echo "$api_response" | jq -r '.error')
        if [ "$error_message" = "closed" ]; then
            echo "closed"
            return 2
        else
        echo "Error: $error_message for plugin $plugin" >&2
        return 1
        fi
    fi
    
    local version=$(echo "$api_response" | jq -r '.version // empty')
    local download_link=$(echo "$api_response" | jq -r '.download_link // empty')
    
    if [ -n "$version" ] && [ -n "$download_link" ]; then
        echo "$version $download_link"
        return 0
    else
        echo "Error: Cannot fetch version or download link for $plugin" >&2
        return 1
    fi
}

download_plugin() {
    local plugin=$1
    local version=$2
    local api_download_link=$3
    local output_file="${MIRROR_DIR}/${plugin}.${version}.zip"
    local header_file="${LOGS_DIR}/${plugin}.${version}.headers"
    local constructed_download_link="${DOWNLOAD_BASE_URL}/${plugin}.${version}.zip"
    local download_link

    if [ "$DEBUG_MODE" -eq 1 ]; then
        debug_log "API-provided download link for $plugin: $api_download_link"
        debug_log "Constructed download link for $plugin: $constructed_download_link"
    fi

    if [ "$DOWNLOAD_LINK_API" == 'y' ] && [ -n "$api_download_link" ]; then
        download_link="$api_download_link"
        debug_log "Using API-provided download link for $plugin: $download_link"
    else
        download_link="$constructed_download_link"
        debug_log "Using constructed download link for $plugin: $download_link"
    fi

    debug_log "Downloading $plugin version $version through Cloudflare Worker"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)
    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o /dev/null "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    else
        curl -s -L -H "User-Agent: $user_agent" -D "$header_file" -o "$output_file" "${CF_WORKER_URL}?url=${download_link}&plugin=${plugin}&version=${version}&type=zip${cache_only_param}"
    fi

    if [ $? -eq 0 ]; then
        if [ "$CACHE_ONLY" == 'y' ]; then
            debug_log "Plugin $plugin version $version cached successfully."
            return 0
        fi

        local file_size=$(stat -c%s "$output_file")
        if [ "$file_size" -lt 1000 ]; then
            echo "Error: Downloaded file for $plugin is too small (${file_size} bytes). Possible download issue." >&2
            return 1
        fi

        local source=$(grep -i "X-Source:" "$header_file" | cut -d' ' -f2 | tr -d '\r')
        if [ "$source" == "R2" ]; then
            debug_log "Successfully downloaded $plugin version $version from R2 storage"
        elif [ "$source" == "WordPress" ]; then
            debug_log "Successfully downloaded $plugin version $version from WordPress"
            debug_log "R2 bucket saving for plugin zip occurred"
        else
            debug_log "Skipped download for $plugin $version zip (already exists locally)"
        fi

        return 0
    else
        echo "Error: Failed to download $plugin version $version" >&2
        return 1
    fi
}

save_plugin_info() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.json"

    debug_log "Saving plugin json metadata for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying metadata download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi

    # Add cache_only parameter if CACHE_ONLY is set
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    if [ "$CACHE_ONLY" == 'y' ]; then
        # When in cache-only mode, output to /dev/null
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin metadata for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache json metadata for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=json${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            if [ "$source" = "R2" ]; then
                debug_log "json metadata for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "json metadata for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin json occurred"
            else
                debug_log "json metadata for $plugin version $version saved (json metadata file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save json metadata for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

fetch_and_save_checksums() {
    local plugin=$1
    local version=$2
    local output_file="${LOGS_DIR}/${plugin}.${version}.checksums.json"

    debug_log "Fetching and saving checksums for $plugin version $version"

    if [ "$DELAY_DOWNLOADS" == 'y' ]; then
        debug_log "Delaying checksums download for $DELAY_DURATION seconds"
        sleep "$DELAY_DURATION"
    fi

    local force_update_param=""
    if [ "$FORCE_UPDATE" == 'y' ]; then
        force_update_param="&force_update=true"
    fi
    local cache_only_param=""
    if [ "$CACHE_ONLY" == 'y' ]; then
        cache_only_param="&cache_only=true"
    fi

    local user_agent=$(get_random_user_agent)

    debug_log "Sending request to Worker for checksums: ${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"

    if [ "$CACHE_ONLY" == 'y' ]; then
        curl -s -H "User-Agent: $user_agent" -o /dev/null "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}"
        if [ $? -eq 0 ]; then
            debug_log "Plugin checksums for $plugin version $version cached successfully."
            return 0
        else
            echo "Error: Failed to cache checksums for $plugin version $version" >&2
            return 1
        fi
    else
        local response=$(curl -s -H "User-Agent: $user_agent" -w "%{http_code}" -o "$output_file" "${CF_WORKER_URL}?plugin=${plugin}&version=${version}&type=checksums${force_update_param}${cache_only_param}")
        local status_code="${response: -3}"

        debug_log "Received response with status code: $status_code"

        if [ "$status_code" = "200" ] && [ -s "$output_file" ]; then
            local source=$(jq -r '.["X-Source"] // empty' "$output_file" 2>/dev/null)
            debug_log "Response source: $source"
            if [ "$source" = "R2" ]; then
                debug_log "Checksums for $plugin version $version retrieved from R2 bucket"
            elif [ "$source" = "WordPress" ]; then
                debug_log "Checksums for $plugin version $version fetched from WordPress"
                debug_log "R2 bucket saving for plugin checksums occurred"
            else
                debug_log "Checksums for $plugin version $version saved (checksums file already exists)"
            fi
            return 0
        else
            echo "Error: Failed to save checksums for $plugin version $version (HTTP status: $status_code)" >&2
            if [ -s "$output_file" ]; then
                debug_log "Error response: $(cat "$output_file")"
            fi
            return 1
        fi
    fi
}

process_plugin() {
    local plugin=$1

    # Check if the plugin is already known to be closed
    if grep -q "^$plugin$" "$CLOSED_PLUGINS_FILE" 2>/dev/null; then
        echo "Plugin $plugin is known to be closed. Skipping."
        return 0
    fi

    echo "Processing plugin: $plugin"

    VERSION_AND_LINK=$(get_latest_version_and_download_link "$plugin")
    local version_check_status=$?
    
    if [ $version_check_status -eq 1 ]; then
        echo "Skipping $plugin due to version fetch error."
        return 1
    elif [ $version_check_status -eq 2 ]; then
        echo "Plugin $plugin is closed. Skipping download and processing."
        echo "$plugin" >> "$CLOSED_PLUGINS_FILE"
        if save_plugin_info "$plugin" "closed"; then
            debug_log "Successfully saved json metadata for closed plugin $plugin."
        else
            debug_log "Failed to save json metadata for closed plugin $plugin."
        fi
        return 0
    fi
    
    LATEST_VERSION=$(echo "$VERSION_AND_LINK" | cut -d' ' -f1)
    API_DOWNLOAD_LINK=$(echo "$VERSION_AND_LINK" | cut -d' ' -f2-)

    debug_log "Latest version for $plugin: $LATEST_VERSION"
    debug_log "API download link for $plugin: $API_DOWNLOAD_LINK"

    STORED_VERSION=$(grep "^$plugin" "$LAST_VERSION_FILE" | awk '{print $2}')
    debug_log "Stored version for $plugin: $STORED_VERSION"

    if [ "$CACHE_ONLY" != 'y' ] && [ "$LATEST_VERSION" == "$STORED_VERSION" ] && [ -f "${MIRROR_DIR}/${plugin}.${LATEST_VERSION}.zip" ]; then
        echo "$plugin is up-to-date and exists in mirror directory. Skipping download..."
    else
        start_time=$(date +%s.%N)

        if download_plugin "$plugin" "$LATEST_VERSION" "$API_DOWNLOAD_LINK"; then
            if [ "$CACHE_ONLY" != 'y' ]; then
                sed -i "/^$plugin/d" "$LAST_VERSION_FILE"
                echo "$plugin $LATEST_VERSION" >> "$LAST_VERSION_FILE"
            fi
            echo "Successfully processed $plugin."
        else
            echo "Error: Failed to process $plugin." >&2
        fi

        end_time=$(date +%s.%N)
        duration=$(echo "$end_time - $start_time" | bc)
        printf "Time taken for %s: %.4f seconds\n" "$plugin" "$duration"
    fi

    if save_plugin_info "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully saved json metadata for $plugin."
    else
        debug_log "Failed to save json metadata for $plugin."
    fi

    if fetch_and_save_checksums "$plugin" "$LATEST_VERSION"; then
        debug_log "Successfully fetched and saved checksums for $plugin."
    else
        debug_log "Failed to fetch and save checksums for $plugin."
    fi
}

populate_all_plugins() {
    if [ ! -f "$ALL_PLUGINS_FILE" ] || [ "$LIST_ONLY" == 'y' ]; then
        echo "Fetching list of all WordPress plugins..."
        svn list https://plugins.svn.wordpress.org/ | sed 's/\/$//g' > "$ALL_PLUGINS_FILE"
        plugin_count=$(wc -l < "$ALL_PLUGINS_FILE")
        echo "Plugin list (${plugin_count}) saved to $ALL_PLUGINS_FILE"
    fi
    
    if [ "$LIST_ONLY" == 'n' ]; then
        ALL_PLUGINS=()
        while IFS= read -r line; do
            ALL_PLUGINS+=("$line")
        done < "$ALL_PLUGINS_FILE"
        echo "Loaded ${#ALL_PLUGINS[@]} plugins."
    fi
}

if [ "$LIST_ONLY" == 'y' ]; then
    populate_all_plugins
    echo "Plugin list created. Exiting without downloading."
    exit 0
fi

if [ "$DOWNLOAD_ALL_PLUGINS" == 'y' ]; then
    populate_all_plugins
    COMBINED_PLUGINS=("${ALL_PLUGINS[@]}")
else
    if [ ! -d "$PLUGIN_DIR" ]; then
        echo "Warning: Plugin directory $PLUGIN_DIR does not exist or is invalid."
        PLUGIN_LIST=()
    else
        PLUGIN_LIST=($(ls -d "$PLUGIN_DIR"/*/ 2>/dev/null | xargs -n 1 basename))

        if [ ${#PLUGIN_LIST[@]} -eq 0 ]; then
            echo "No plugins found in $PLUGIN_DIR."
        fi
    fi

    COMBINED_PLUGINS=(${PLUGIN_LIST[@]} ${ADDITIONAL_PLUGINS[@]})
    COMBINED_PLUGINS=($(echo "${COMBINED_PLUGINS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
fi

if [ ${#COMBINED_PLUGINS[@]} -eq 0 ]; then
    echo "No plugins to download. Exiting."
    exit 0
fi

mkdir -p "$MIRROR_DIR"
touch "$LAST_VERSION_FILE"

if [ "$PARALLEL_JOBS" -gt 1 ]; then
    echo "Running in parallel with $PARALLEL_JOBS jobs..."
    # First, export all variables including USER_AGENTS
    export DOWNLOAD_BASE_URL MIRROR_DIR LAST_VERSION_FILE DEBUG_MODE DOWNLOAD_LINK_API LOGS_DIR ALL_PLUGINS_FILE DOWNLOAD_ALL_PLUGINS LIST_ONLY CF_WORKER_URL DELAY_DOWNLOADS DELAY_DURATION FORCE_UPDATE CACHE_ONLY USER_AGENTS

    # Then, export the functions
    export -f process_plugin get_latest_version_and_download_link download_plugin debug_log populate_all_plugins save_plugin_info get_random_user_agent fetch_and_save_checksums
    printf "%s\n" "${COMBINED_PLUGINS[@]}" | xargs -P $PARALLEL_JOBS -I {} bash -c 'process_plugin "$@"' _ {}
else
    for plugin in "${COMBINED_PLUGINS[@]}"; do
        process_plugin "$plugin"
    done
fi

if [ -f "$CLOSED_PLUGINS_FILE" ]; then
    echo
    echo "Closed Plugin List:"
    cat "$CLOSED_PLUGINS_FILE" | sort | uniq || true
    echo
    echo "Total closed plugins: $(wc -l < "$CLOSED_PLUGINS_FILE")"
    echo
else
    echo
    echo "No closed plugins found."
    echo
fi
echo "Plugin download process completed."
