name: 0 - Trigger All Plugin Download Workflows

on:
  workflow_dispatch:

jobs:
  trigger_workflows:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

      - name: Trigger Workflows
        run: |
          # Trigger the 1000-plugin workflow first
          echo "Triggering workflow for 1000 plugins"
          gh workflow run ./scripts/get-all-plugins-workflow-1000.yml --ref refs/heads/master
          sleep 10

          # Trigger the rest of the workflows (multiples of 2000)
          for i in {2000..56000..2000}
          do
            echo "Triggering workflow for $i plugins"
            gh workflow run ./scripts/get-all-plugins-workflow-$i.yml --ref refs/heads/master
            sleep 10
          done
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}