name: All Mirror WordPress Plugins 56000

on:
  workflow_dispatch:      # Allows manual triggering of the workflow

jobs:
  mirror_plugins:
    runs-on: ubuntu-latest

    steps:
      - name: Check Disk Space Before
        run: |
          df -hT || true

      - name: Remove unused components
        uses: ngocptblaplafla/more-space-plz@v1
        with:
          aliyun: true
          android-sdk: true
          apache: true
          aws-tools: true
          azcopy: true
          azure-cli: true
          azure-devops-cli: true
          bazel: true
          bicep: true
          clang: true
          cmake: true
          codeql-bundle: true
          container-tools: true
          docker: true
          docker-data: true
          dotnet: true
          firefox: true
          gcc-compilers: true
          gfortran: true
          google-chrome: true
          google-cloud-cli: true
          golang: true
          haskell: true
          heroku: true
          homebrew: true
          java-tools: true
          julia: true
          kotlin: true
          kubernetes-tools: true
          leiningen: true
          man: true
          microsoft-edge: true
          miniconda: true
          mono: true
          mssql-tools: true
          mysql: true
          nginx: true
          nodejs: true
          nvm: true
          oc-cli: true
          oras-cli: true
          packer: true
          php: true
          postgresql: true
          powershell: true
          pulumi: true
          rlang: true
          ruby: true
          rust: true
          sbt: true
          selenium: true
          snap: true
          sqlpackage: true
          swift: true
          terraform: true
          vcpkg: true
          yq: true

      - name: Check Disk Space After
        run: |
          df -hT || true

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install requests

      - name: Run query_plugins.py Script
        run: |
          python3 ./scripts/query_plugins.py -pages 1 -perpage 1 > plugin_results.json

      - name: Upload Plugin Results as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-results
          path: plugin_results.json

      - name: Set Execute Permission
        run: chmod +x ./scripts/get_all_plugins_r2_workflow-56000.sh

      - name: Test List Plugins Flag (-l)
        env:
          CF_WORKER_URL: ${{ secrets.CF_WORKER_URL }}
        run: |
          ./scripts/get_all_plugins_r2_workflow-56000.sh -l

      - name: Upload Plugin List
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: plugin-list
          path: /home/runner/work/wordpress-plugin-workflows/wordpress-plugin-workflows/scripts/wordpress-plugins/wp-plugin-svn-list.txt

      - name: Run ./scripts/get_all_plugins_r2_workflow-56000.sh and Log Output
        env:
          CF_WORKER_URL: ${{ secrets.CF_WORKER_URL }}
        run: |
          time ./scripts/get_all_plugins_r2_workflow-56000.sh -p 4 -d -D y -t 1 -c 2>&1 | tee script_output-56000.log

      - name: Check Locally Downloaded WP Plugins
        run: |
          ls -lAhrt /home/runner/work/wordpress-plugin-workflows/wordpress-plugin-workflows/scripts/mirror || true

      - name: Check Locally Downloaded WP Plugins Disk Space Used
        run: |
          du -sh /home/runner/work/wordpress-plugin-workflows/wordpress-plugin-workflows/scripts/mirror || true

      - name: Check WP Plugins Mirror Logs
        run: |
          ls -lAhrt /home/runner/work/wordpress-plugin-workflows/wordpress-plugin-workflows/scripts/plugin-logs || true

      - name: Check WP WorkDir
        run: |
          ls -lAhrt /home/runner/work/wordpress-plugin-workflows/wordpress-plugin-workflows/scripts/wordpress-plugins || true

      - name: Upload Script Output Log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: script_output-56000-log
          path: script_output-56000.log

      - name: Prepare Plugin Logs for Upload
        run: |
          find /home/runner/work/wordpress-plugin-workflows/wordpress-plugin-workflows/scripts/plugin-logs -type f | while read file; do
            newname=$(echo "$file" | sed -e 's/[:"<>|*?]/_/g' -e 's/\$/_/g' -e 's/\r/_/g' -e 's/\n/_/g')
            if [ "$file" != "$newname" ]; then
              mv "$file" "$newname"
              echo "Renamed $file to $newname"
            fi
          done

      - name: Upload Plugin Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: plugin-logs
          path: /home/runner/work/wordpress-plugin-workflows/wordpress-plugin-workflows/scripts/plugin-logs/
